lib/runtime/LoadScriptRuntimeModule.js
test/Stats.test.js
test/__snapshots__/StatsTestCases.test.js.snap

fixes #11247
fixes #11248
bugfix
manually, we have no automated browser tests :(
no
nothing

fix script loading problem with multiple parallel runtimes

---

schemas/WebpackOptions.json
test/__snapshots__/Cli.test.js.snap

Cli related change
Yes
No
Probably nothing

exclude --module-rules-options from schema for cli

---

declarations/WebpackOptions.d.ts
schemas/WebpackOptions.json
test/__snapshots__/Cli.test.js.snap
types.d.ts

fix description 
NA
No
nothing

fix: optimization.emitOnErrors description

---

lib/node/ReadFileChunkLoadingRuntimeModule.js
lib/node/RequireChunkLoadingRuntimeModule.js
lib/util/identifier.js
lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js
test/configCases/entry/weird-names/chunk.js
test/configCases/entry/weird-names/index.js
test/configCases/entry/weird-names/test.config.js
test/configCases/entry/weird-names/webpack.config.js

improve and fix backtracing to root folder from nested directories

---

lib/web/JsonpHelpers.js
test/__snapshots__/StatsTestCases.test.js.snap

fixes https://github.com/webpack/webpack/issues/11279
bugfix
Sorry, it is too difficult for me.  
No.
Nothing.

fix: add the id of runtime chunk to entryInfo #11279

---

package.json
yarn.lock

deps
existing tests
no
nothing

upgrade watchpack to beta 14

---

azure-pipelines.yml

stop testing mac os in node 10 as it's too flanky

---

test/cases/parsing/chunks/test.filter.js
test/cases/parsing/class/test.filter.js
test/cases/parsing/complex-require/test.filter.js
test/cases/parsing/es6.nominimize/test.filter.js
test/cases/parsing/extract-amd.nominimize/test.filter.js
test/cases/parsing/harmony-tdz/test.filter.js
test/cases/parsing/issue-2522/test.filter.js
test/cases/parsing/issue-2523/test.filter.js
test/cases/parsing/issue-2618/test.filter.js
test/cases/parsing/issue-2622/test.filter.js
test/cases/parsing/issue-2895/test.filter.js
test/cases/parsing/issue-3238/test.filter.js
test/cases/parsing/issue-3252/test.filter.js
test/cases/parsing/issue-3273/test.filter.js
test/cases/parsing/issue-4357/test.filter.js
test/cases/parsing/issue-4608-2/test.filter.js
test/cases/parsing/issue-4870/test.filter.js
test/cases/scope-hoisting/inside-class/test.filter.js

terser support more stuff so no need to ignore these test cases

---

lib/Compilation.js
test/configCases/assets/delete-asset/chunk.js
test/configCases/assets/delete-asset/index.js
test/configCases/assets/delete-asset/webpack.config.js
types.d.ts

feature
yes
no
Compilation.emitAsset, updateAsset and deleteAsset can be used to modify assets in webpack.

add Compilation.deleteAsset

---

lib/RuntimeTemplate.js
test/configCases/externals/async-externals/index.js
test/configCases/externals/async-externals/module.mjs
test/configCases/externals/async-externals/webpack.config.js

Naive approach but it seems to work just fine.
bugfix https://github.com/webpack/webpack/issues/11197
Yes
No
-

fix #11197: dynamic import promise externals

---

lib/javascript/JavascriptParser.js
test/cases/parsing/issue-11283/A.js
test/cases/parsing/issue-11283/index.js

bugfix
fixes #11283 
yes
no
nothing

fix(#11283) bug with switch case

---

lib/ExternalModule.js
lib/util/extractUrlAndGlobal.js
test/extractUrlAndGlobal.unittest.js

bug fix.
`urlAndGlobal.split("@")` would fail in cases like `"_@https://cdn.jsdelivr.net/npm/lodash@4.17.19/lodash.min.js"` containing two `@`.
yes.
no
nothing.

fix ExternalModule bug

---

lib/Compiler.js

improve error message

---

lib/MainTemplate.js
lib/index.js
lib/web/JsonpChunkLoadingRuntimeModule.js
lib/web/JsonpTemplatePlugin.js
types.d.ts

remove unused code
existing tests
yes
nothing

remove unused code

---

lib/cache/PackFileCacheStrategy.js
lib/index.js
types.d.ts

feature
partially, existing tests
no
Plugins should consume `require("webpack").sources` instead of `require("webpack-sources")` to avoid version conflicts for persistent caching

Partial caching, expose webpack-sources

---

lib/WebpackOptionsApply.js
lib/electron/ElectronTargetPlugin.js
lib/index.js
lib/node/NodeSourcePlugin.js
types.d.ts

expose missing target plugins

---

declarations.d.ts
lib/optimize/RealContentHashPlugin.js
package.json
test/__snapshots__/StatsTestCases.test.js.snap
test/statsCases/real-content-hash/test.config.js
test/statsCases/real-content-hash/webpack.config.js
types.d.ts
yarn.lock

accept Source-like objects in assets and cache sources for RealContentHashPlugin

---

lib/javascript/BasicEvaluatedExpression.js
lib/javascript/JavascriptParser.js
test/JavascriptParser.unittest.js
test/cases/parsing/evaluate/index.js
test/cases/parsing/evaluate/regexp/a.filtered.js
test/cases/parsing/evaluate/regexp/a.js

feat
closes https://github.com/webpack/webpack/issues/3237
yes
no
nothing

feat: evaluate new RegExp

---

declarations.d.ts
lib/Compilation.js
lib/Compiler.js
lib/ContextModule.js
lib/DefinePlugin.js
lib/FileSystemInfo.js
lib/Module.js
lib/NormalModule.js
lib/ProgressPlugin.js
lib/cache/PackFileCacheStrategy.js
lib/cache/ResolverCachePlugin.js
lib/dependencies/LoaderPlugin.js
lib/optimize/ConcatenatedModule.js
lib/serialization/BinaryMiddleware.js
lib/util/LazySet.js
lib/util/internalSerializables.js
lib/util/registerExternalSerializer.js
package.json
test/__snapshots__/StatsTestCases.test.js.snap
test/watchCases/cache/child-compilation-cache/0/index.js
types.d.ts
yarn.lock

performance
existing tests
no
nothing

Persistent Caching performance improvements and logging for large builds

---

lib/NormalModule.js

cache modules even if they are not parsed

---

lib/dependencies/ImportMetaPlugin.js
lib/javascript/JavascriptParser.js
test/cases/parsing/meta-property/index.js
types.d.ts

bugfix
fixes #11310 
yes
no
nothing

fix: meta property hook rework

---

lib/node/NodeTargetPlugin.js

Bugfix for #6497, #11376
Bugfix
No
No
Nothing

Fix "ModuleNotFound 'module'" error (#6497, #11376)

---

lib/index.js
lib/javascript/JavascriptModulesPlugin.js
lib/javascript/JavascriptParser.js
lib/optimize/ConcatenatedModule.js
test/JavascriptParser.unittest.js
types.d.ts

small refactoring
no
no
nothing

use bitmask instead of array+set in getMemberExpressionInfo

---

lib/HotModuleReplacementPlugin.js
lib/HotUpdateChunk.js
lib/Template.js
lib/javascript/JavascriptModulesPlugin.js
lib/util/runtime.js
test/hotCases/disposing/remove-chunk-with-shared/chunk1.js
test/hotCases/disposing/remove-chunk-with-shared/chunk2.js
test/hotCases/disposing/remove-chunk-with-shared/index.js
test/hotCases/disposing/remove-chunk-with-shared/module.js
test/hotCases/disposing/remove-chunk-with-shared/shared.js

fix incorrect disposing of modules during HMR

---

lib/NormalModule.js
lib/WebpackOptionsApply.js
lib/config/defaults.js
lib/config/normalization.js
test/Defaults.unittest.js

refactor
existing tests
no
nothing

extract loader.target from target option

---

lib/javascript/JavascriptParser.js
test/cases/parsing/this-in-arrow-iife/index.js

yarnpkg/berry#1832
bugfix
yes
no
nothing

fixes parsing of 'this' in arrow iife

---

lib/buildChunkGraph.js
test/__snapshots__/StatsTestCases.test.js.snap
test/configCases/graph/conditional-ensure/a.js
test/configCases/graph/conditional-ensure/b.js
test/configCases/graph/conditional-ensure/c1.js
test/configCases/graph/conditional-ensure/c2.js
test/configCases/graph/conditional-ensure/webpack.config.js

fixes #8677
bugfix
yes
no
nothing

make sure to generate correct chunk connection for blocks that are only connected in some runtimes (webpack 4)

---

lib/FileSystemInfo.js
lib/buildChunkGraph.js
test/__snapshots__/StatsTestCases.test.js.snap
test/configCases/graph/conditional-ensure/a.js
test/configCases/graph/conditional-ensure/b.js
test/configCases/graph/conditional-ensure/c1.js
test/configCases/graph/conditional-ensure/c2.js
test/configCases/graph/conditional-ensure/webpack.config.js
test/configCases/hash-length/output-filename/webpack.config.js

fixes #8677
bugfix
yes
no
nothing

make sure to generate correct chunk connection for blocks that are only connected in some runtimes

---

lib/FileSystemInfo.js
lib/RuntimeGlobals.js
lib/container/ContainerEntryModule.js
lib/container/RemoteRuntimeModule.js
lib/sharing/ConsumeSharedRuntimeModule.js
lib/sharing/ShareRuntimeModule.js
test/configCases/container/circular/a.js
test/configCases/container/circular/b.js
test/configCases/container/circular/index.js
test/configCases/container/circular/test.config.js
test/configCases/container/circular/webpack.config.js
types.d.ts

fix circular references between containers and modules in containers

---

lib/FileSystemInfo.js

fixes #11293
bugfix
no, too difficult
no
nothing

avoid error for managed paths that only contain a node_modules

---

package.json
yarn.lock

deps
existing tests
yes
nothing

update our own dependencies

---

lib/FileSystemInfo.js
test/configCases/cache-dependencies/managed-items/index.js
test/configCases/cache-dependencies/managed-items/loader.js
test/configCases/cache-dependencies/managed-items/node_modules/package/package.json
test/configCases/cache-dependencies/managed-items/webpack.config.js

fix incorrect iteration

---

lib/HotModuleReplacementPlugin.js
lib/dependencies/CommonJsExportsParserPlugin.js
lib/dependencies/HarmonyImportSpecifierDependency.js
lib/index.js
lib/util/deprecation.js
lib/validateSchema.js
test/Validation.test.js
types.d.ts

clean up, bugfix, avoid crash
no, but that's not super important here
no
nothing

little improvements

---

lib/Compiler.js
lib/Watching.js
test/Compiler.test.js
types.d.ts

Resolves #11481 
feature
No
No
New `compiler.watching` property.

feat: add watching property to compiler

---

lib/optimize/SplitChunksPlugin.js
test/configCases/split-chunks/issue-11513/big-module.js
test/configCases/split-chunks/issue-11513/chunk1.js
test/configCases/split-chunks/issue-11513/chunk2.js
test/configCases/split-chunks/issue-11513/index.js
test/configCases/split-chunks/issue-11513/test.config.js
test/configCases/split-chunks/issue-11513/wasm.wat
test/configCases/split-chunks/issue-11513/webpack.config.js

fixes #11513
bugfix
yes
no
nothing

when splitChunks entry violates minSize or minRemainingSize retry without offending modules

---

declarations/WebpackOptions.d.ts
lib/RuntimePlugin.js
schemas/WebpackOptions.json
test/__snapshots__/Cli.test.js.snap
test/configCases/filename-template/filename-function/a.js
test/configCases/filename-template/filename-function/b.js
test/configCases/filename-template/filename-function/chunk1.js
test/configCases/filename-template/filename-function/chunk2.js
test/configCases/filename-template/filename-function/test.config.js
test/configCases/filename-template/filename-function/webpack.config.js
types.d.ts

feature
yes
no
`output.chunkFilename` can be a function, like with `output.filename`

output.chunkFilename can be a function

---

lib/javascript/JavascriptModulesPlugin.js
test/__snapshots__/StatsTestCases.test.js.snap
test/watchCases/plugins/mini-css-extract-plugin/1/index.js
types.d.ts

add bootstrap code to content hash
bugfix
yes
no
nothing

use better hash for renderManifest to avoid unnecessary invalidation

---

declarations/WebpackOptions.d.ts
lib/config/defaults.js
lib/dependencies/WorkerDependency.js
package.json
schemas/WebpackOptions.json
test/Defaults.unittest.js
test/__snapshots__/Cli.test.js.snap
test/configCases/asset-url/target-web2/index.js
types.d.ts
yarn.lock

add resolve.preferRelative
set preferRelative for new URL() and new Worker() to fix relative requests
fixes #11491
yes
no, bugfix
* `resolve.preferRelative` allows to resolve `module/path` like `./module/path` in addition to `(node_modules/)module/path`.
* new URL() behaves this way

update enhanced-resolve and webpack-sources

---

lib/stats/DefaultStatsFactoryPlugin.js
lib/stats/DefaultStatsPrinterPlugin.js
test/__snapshots__/StatsTestCases.test.js.snap

probably fixes #11545
bugfix, improvement
no, exisiting tests
no
nothing

improve stats grouping

---

lib/webpack.js
test/Compiler.test.js

fixes #11553
bugfix
yes
no
nothing

revert error and add deprecation instead

---

lib/ConcatenationScope.js
lib/optimize/ConcatenatedModule.js
test/cases/scope-hoisting/delete-issue-10831/index.js
test/cases/scope-hoisting/delete-issue-10831/module.js

fixes #10831
bugfix
yes
no
nothing

fix delete in concatenated module

---

lib/ChunkGraph.js
lib/FlagDependencyUsagePlugin.js
lib/Module.js
lib/ModuleGraphConnection.js
lib/async-modules/InferAsyncModulesPlugin.js
lib/buildChunkGraph.js
lib/dependencies/HarmonyImportDependency.js
lib/dependencies/HarmonyImportSpecifierDependency.js
lib/ids/OccurrenceModuleIdsPlugin.js
lib/javascript/JavascriptModulesPlugin.js
lib/optimize/ConcatenatedModule.js
lib/optimize/ModuleConcatenationPlugin.js
lib/wasm-sync/WasmFinalizeExportsPlugin.js
types.d.ts

fix some nitpicks with active state

---

lib/BannerPlugin.js
lib/DllPlugin.js
lib/DllReferencePlugin.js
lib/IgnorePlugin.js
lib/LoaderOptionsPlugin.js
lib/NormalModule.js
lib/ProgressPlugin.js
lib/SourceMapDevToolPlugin.js
lib/WatchIgnorePlugin.js
lib/asset/AssetModulesPlugin.js
lib/container/ContainerPlugin.js
lib/container/ContainerReferencePlugin.js
lib/container/ModuleFederationPlugin.js
lib/debug/ProfilingPlugin.js
lib/ids/HashedModuleIdsPlugin.js
lib/ids/OccurrenceChunkIdsPlugin.js
lib/ids/OccurrenceModuleIdsPlugin.js
lib/json/JsonModulesPlugin.js
lib/optimize/AggressiveSplittingPlugin.js
lib/optimize/LimitChunkCountPlugin.js
lib/optimize/MinChunkSizePlugin.js
lib/sharing/ConsumeSharedPlugin.js
lib/sharing/ProvideSharedPlugin.js
lib/validateSchema.js
package.json
yarn.lock

refactoring
No need
No
Nothing

chore(deps): update `schema-utils`

---

lib/util/deterministicGrouping.js

bugfix, Fixes #11048 
Not yet
No
Nothing.

fix: getNumberOfMatchingSizeTypes function call

---

lib/index.js
types.d.ts

Fixes #11154 
export more types.
No
Nothing I guess.

Export more types from types.d.ts

---

lib/optimize/SideEffectsFlagPlugin.js
test/cases/side-effects/empty-modules/pure.js

fixes #11615
bugfix
yes
no
nothing

fixes crash in SideEffectsFlagPlugin

---

lib/optimize/ConcatenatedModule.js
test/cases/scope-hoisting/import-order-11617/a.js
test/cases/scope-hoisting/import-order-11617/b.js
test/cases/scope-hoisting/import-order-11617/c.js
test/cases/scope-hoisting/import-order-11617/index.js
test/cases/scope-hoisting/import-order-11617/tracker.js
test/cases/scope-hoisting/import-order-11617/x.js
test/cases/scope-hoisting/import-order-11617/y.js

fixes #11617
bugfix
yes
no
nothing

skip connections copied to concatenated module

---

lib/ProvidePlugin.js
test/configCases/parsing/issue-11619/index.js
test/configCases/parsing/issue-11619/node_modules/aaa.js
test/configCases/parsing/issue-11619/webpack.config.js

fixes #11619
bugfix
yes
no
nothing

fix called variables with ProvidePlugin

---

lib/config/defaults.js
lib/electron/ElectronTargetPlugin.js

This fixes electron/index.js being bundled as described in #11599, and also fixes `electron-renderer` to use the correct chunk format, as it is in a browser and not in a module context.
Bugfix.
Not yet
No
Nothing

Fix require handling with electron; fixes #11599

---

lib/optimize/RealContentHashPlugin.js

emit error instead of crashing when unexpected problem occurs

---

lib/dependencies/CommonJsImportsParserPlugin.js
test/cases/runtime/missing-module-exception/index.js
test/cases/runtime/missing-module-exception/warnings.js

fixes #11639
bugfix
yes
no
nothing

flag commonjs dependency in try block as optional

---

lib/optimize/ConcatenatedModule.js
test/cases/scope-hoisting/side-effects-11662/index.js
test/cases/scope-hoisting/side-effects-11662/node_modules/package/d.js
test/cases/scope-hoisting/side-effects-11662/node_modules/package/e.js
test/cases/scope-hoisting/side-effects-11662/node_modules/package/index.js
test/cases/scope-hoisting/side-effects-11662/node_modules/package/module.js
test/cases/scope-hoisting/side-effects-11662/node_modules/package/package.json

fixes #11662
bugfix
yes
no
nothing

follow reexport in concatenated modules even if they are skipped due to side effects

---

lib/EntryOptionPlugin.js
lib/index.js
test/__snapshots__/StatsTestCases.test.js.snap
test/statsCases/child-compiler-apply-entry-option/TestApplyEntryOptionPlugin.js
test/statsCases/child-compiler-apply-entry-option/webpack.config.js
types.d.ts

fix: expose EntryPlugin creation

---

lib/Compilation.js
test/configCases/worker/worker-contenthash/index.js
test/configCases/worker/worker-contenthash/module.js
test/configCases/worker/worker-contenthash/test.config.js
test/configCases/worker/worker-contenthash/test.filter.js
test/configCases/worker/worker-contenthash/webpack.config.js
test/configCases/worker/worker-contenthash/worker.js

fixes #11677
bugfix
yes
no
nothing

order runtime chunks correctly when they depend on each other

---

lib/ExportsInfo.js
lib/FlagDependencyUsagePlugin.js
lib/optimize/ConcatenatedModule.js
lib/util/runtime.js
test/TestCases.template.js
test/cases/side-effects/issue-11673/index.js
test/cases/side-effects/issue-11673/module.js
test/cases/side-effects/issue-11673/node_modules/package/index.js
test/cases/side-effects/issue-11673/node_modules/package/package.json
test/cases/side-effects/issue-11673/test.filter.js
test/cases/side-effects/issue-11673/worker.js
types.d.ts

fixes #11673
bugfix
yes
no
nothing

fix unused modules in chunk when optimizing runtime-specific 

---

lib/Compilation.js
test/configCases/assets/delete-asset/chunk2.js
test/configCases/assets/delete-asset/index.js
test/configCases/assets/delete-asset/webpack.config.js

update chunk to files mapping when deleting assets

---

lib/NormalModule.js
types.d.ts

According to the jsdoc, the actually params order is incorrect.

fix: reorder params

---

lib/Compilation.js
types.d.ts

fix order of asset optimization to fix conflict between compression-plugin and real hash plugin

---

lib/ExternalModule.js
test/configCases/externals/this/index.js
test/configCases/externals/this/webpack.config.js
types.d.ts

Make external modules of type 'this' work with module concatenation

---

declarations/WebpackOptions.d.ts
package.json
schemas/WebpackOptions.json
test/Validation.test.js
test/__snapshots__/Cli.test.js.snap
types.d.ts

fixes #6845 
An Important Change for adding the options to enable/disable followSymlinks of watchpack
Yes I have updated the snapshots and the typing 
No
Documentation fo followSymlinks need to be enhanced .
FollowSymLinks is a directive in your web server configuration that tells your web server to follow so called symbolic links. As one would expect, FollowSymLinks is an acronym for Follow Symbolic Links. 
Ok

followSymLinks Options Added with the snapshots and typings updated

---

package.json
test/configCases/resolve-merging/override/loader.js
yarn.lock

test: example problem of #11668

---

lib/Compiler.js
test/watchCases/cache/immutable/0/index.js
test/watchCases/cache/immutable/1/index.js
test/watchCases/cache/immutable/webpack.config.js

fixes #11820
bugfix
yes
no
nothing

re-check immutable state when removing a query string

---

declarations.d.ts
lib/ContextModule.js
lib/DelegatedModule.js
lib/ExternalModule.js
lib/Module.js
lib/NormalModule.js
lib/RawModule.js
lib/RuntimeModule.js
lib/SourceMapDevToolModuleOptionsPlugin.js
lib/SourceMapDevToolPlugin.js
lib/container/ContainerEntryModule.js
lib/javascript/JavascriptModulesPlugin.js
test/NormalModule.unittest.js
test/__snapshots__/StatsTestCases.test.js.snap
test/configCases/source-map/no-source-map/chunk.js
test/configCases/source-map/no-source-map/index.js
test/configCases/source-map/no-source-map/loader.js
test/configCases/source-map/no-source-map/webpack.config.js
types.d.ts

add useSimpleSourceMap flag to enable/disable OrignalSource for generated code

---

lib/ProgressPlugin.js

bugfix (performance)
no
no
nothing

fix a unneeded cache store when using child compilers

---

package.json
test/__snapshots__/StatsTestCases.test.js.snap
yarn.lock

update terser-webpack-plugin and webpack-sources

---

bin/webpack.js

bug fix, we already use right logic for running, just don't use it after webpack-cli installation 
fixes #11836
No, I don't find tests for CLI, I think we should add them
No
No

fix: run cli after installed

---

lib/ConcatenationScope.js
lib/optimize/ConcatenatedModule.js
lib/util/runtime.js
test/configCases/graph/issue-11863/a.js
test/configCases/graph/issue-11863/b.js
test/configCases/graph/issue-11863/c.js
test/configCases/graph/issue-11863/shared-x.js
test/configCases/graph/issue-11863/shared-y.js
test/configCases/graph/issue-11863/shared-z.js
test/configCases/graph/issue-11863/shared.js
test/configCases/graph/issue-11863/test.config.js
test/configCases/graph/issue-11863/webpack.config.js
types.d.ts

fix #11863
bugfix
yes
no
nothing

handle the case when execution order in a concatenated module is runtime-dependent

---

lib/optimize/ConcatenatedModule.js
test/cases/scope-hoisting/issue-11840/Mixin.js
test/cases/scope-hoisting/issue-11840/index.js

fixes #11840
bugfix
yes
no
nothing

handle renaming in super class expression in nested scopes correctly

---

lib/dependencies/HarmonyImportDependencyParserPlugin.js
lib/javascript/JavascriptParser.js
test/__snapshots__/StatsTestCases.test.js.snap
test/cases/scope-hoisting/issue-11897/cjs.js
test/cases/scope-hoisting/issue-11897/index.js
test/cases/scope-hoisting/issue-11897/module.js
types.d.ts

fixes #11897
bugfix
yes
no
nothing

improve handling of ASI in concatenated modules and with imports

---

lib/javascript/JavascriptParser.js
lib/optimize/ConcatenatedModule.js
test/__snapshots__/StatsTestCases.test.js.snap
test/cases/scope-hoisting/issue-11897/iife.js
test/cases/scope-hoisting/issue-11897/index.js

fixes #11897
bugfix
yes
no
nothing

handle ASI issue between concatenated modules

---

lib/Compilation.js
types.d.ts

Documented the `minimized` property on AssetInfo.
No, I didn't see type tests but let me know if there's a test you want me to add.
No
Nothing AFAIK

docs(type): documented minimized property on asset-info

---

lib/ExportsInfo.js
lib/optimize/SideEffectsFlagPlugin.js
test/cases/scope-hoisting/side-effects-11990-star/chunk1.js
test/cases/scope-hoisting/side-effects-11990-star/chunk2.js
test/cases/scope-hoisting/side-effects-11990-star/index.js
test/cases/scope-hoisting/side-effects-11990-star/module-concat.js
test/cases/scope-hoisting/side-effects-11990-star/module.js
test/cases/scope-hoisting/side-effects-11990-star/package.json
test/cases/scope-hoisting/side-effects-11990-star/reexport-concat.js
test/cases/scope-hoisting/side-effects-11990-star/reexport.js
test/cases/scope-hoisting/side-effects-11990-star/reexport2.js
test/cases/scope-hoisting/side-effects-11990/chunk1.js
test/cases/scope-hoisting/side-effects-11990/chunk2.js
test/cases/scope-hoisting/side-effects-11990/index.js
test/cases/scope-hoisting/side-effects-11990/module-concat.js
test/cases/scope-hoisting/side-effects-11990/module.js
test/cases/scope-hoisting/side-effects-11990/package.json
test/cases/scope-hoisting/side-effects-11990/reexport-concat.js
test/cases/scope-hoisting/side-effects-11990/reexport.js
test/cases/scope-hoisting/side-effects-11990/reexport2.js
types.d.ts

fixes #11990
bugfix
yes
no
nothing

fixes unused export bug

---

lib/ContextModule.js
lib/RuntimeTemplate.js
lib/optimize/ConcatenatedModule.js
lib/runtime/CreateFakeNamespaceObjectRuntimeModule.js
test/Stats.test.js
test/__snapshots__/StatsTestCases.test.js.snap
test/cases/json/import-lazy/index.js
test/cases/mjs/non-enumerable/analysable-module.js
test/cases/mjs/non-enumerable/esModule.js
test/cases/mjs/non-enumerable/index.js
test/cases/mjs/non-enumerable/test.js
test/cases/mjs/non-enumerable/test.mjs
test/cases/mjs/non-enumerable/warnings.js
test/cases/mjs/non-enumerable/weird-module.js
test/configCases/split-chunks-common/move-to-grandparent/index.js

fixes #11995
bugfix
yes
no, behavior changes are bugfixes
TODO

make visible exports from non-harmony modules more consistent

---

lib/javascript/JavascriptParser.js
test/cases/parsing/asi/a.js
test/cases/parsing/asi/index.js
types.d.ts

bugfix #12006  
yes
no
nothing

fix: check statements in path for asi safe

---

examples/reexport-components/README.md
examples/reexport-components/build.js
examples/reexport-components/components/Button.js
examples/reexport-components/components/Checkbox.js
examples/reexport-components/components/Dialog.js
examples/reexport-components/components/DialogInline.js
examples/reexport-components/components/index.js
examples/reexport-components/components/package.json
examples/reexport-components/example.js
examples/reexport-components/pages/Dashboard.js
examples/reexport-components/pages/Login.js
examples/reexport-components/template.md
examples/reexport-components/webpack.config.js

add reexports example

---

lib/Compilation.js
types.d.ts

Please see #11947 
Added typings

fixes "Type '(compiler: Compiler) => void' is not assignable to type '() => void'.ts"

---

lib/WebpackOptionsApply.js
lib/dependencies/HarmonyImportSpecifierDependency.js
lib/javascript/EnableChunkLoadingPlugin.js
lib/library/EnableLibraryPlugin.js
lib/util/registerExternalSerializer.js
package.json
test/configCases/asset-modules/http-url/webpack.config.js
test/configCases/asset-modules/https-url/webpack.config.js
types.d.ts
yarn.lock

deps
lint
no
nothing
blocked by
* https://github.com/microsoft/TypeScript/issues/41697
* https://github.com/microsoft/TypeScript/issues/41699
* https://github.com/prettier/prettier/issues/9740

upgrade typescript major version

---

lib/optimize/ConcatenatedModule.js
lib/optimize/SideEffectsFlagPlugin.js
test/cases/side-effects/issue-12071/index.js
test/cases/side-effects/issue-12071/module.js
test/cases/side-effects/issue-12071/package.json
test/cases/side-effects/issue-12071/reexport.js
test/cases/side-effects/issue-12071/reexport2-concat.js
test/cases/side-effects/issue-12071/reexport2.js

fix #12071
bugfix
yes
no
nothing

only move export info targets when also moving dependencies

---

lib/optimize/ConcatenatedModule.js
test/cases/side-effects/issue-12114/a.js
test/cases/side-effects/issue-12114/b.js
test/cases/side-effects/issue-12114/index.js
test/cases/side-effects/issue-12114/node_modules/base/index.js
test/cases/side-effects/issue-12114/node_modules/base/package.json
test/cases/side-effects/issue-12114/node_modules/tslib.js
test/cases/side-effects/issue-12114/reexport.js

fixes #12114

---

declarations/WebpackOptions.d.ts
lib/ModuleFilenameHelpers.js
lib/ModuleInfoHeaderPlugin.js
lib/WebpackOptionsApply.js
lib/stats/DefaultStatsFactoryPlugin.js
lib/stats/StatsFactory.js
schemas/WebpackOptions.json
test/__snapshots__/Cli.test.js.snap
test/__snapshots__/StatsTestCases.test.js.snap
types.d.ts

#12102
performance
n/a
no
`output.pathinfo` supports `false | true | "verbose"` `true` is the default. `"verbose"` shows more info.

improve rebuild performance

---

lib/Compilation.js
lib/Compiler.js
lib/util/source.js
test/configCases/asset-modules/different-query/index.js
test/configCases/asset-modules/different-query/webpack.config.js

fixes #11894
bugfix
yes
no
nothing

fix handling of multiple identical assets with different querystrings

---

lib/Compilation.js
test/configCases/process-assets/html-plugin/webpack.config.js

fix triggering processAssets for some assets twice

---

lib/MainTemplate.js
lib/ModuleInfoHeaderPlugin.js
lib/RuntimeGlobals.js
lib/RuntimeModule.js
lib/RuntimeTemplate.js
lib/hmr/HotModuleReplacementRuntimeModule.js
lib/javascript/JavascriptModulesPlugin.js
lib/node/ReadFileChunkLoadingRuntimeModule.js
lib/node/RequireChunkLoadingRuntimeModule.js
lib/prefetch/ChunkPrefetchFunctionRuntimeModule.js
lib/prefetch/ChunkPrefetchPreloadPlugin.js
lib/prefetch/ChunkPrefetchStartupRuntimeModule.js
lib/prefetch/ChunkPrefetchTriggerRuntimeModule.js
lib/runtime/AutoPublicPathRuntimeModule.js
lib/runtime/CompatRuntimeModule.js
lib/runtime/PublicPathRuntimeModule.js
lib/sharing/ConsumeSharedRuntimeModule.js
lib/wasm-async/AsyncWasmChunkLoadingRuntimeModule.js
lib/wasm-sync/WasmChunkLoadingRuntimeModule.js
lib/web/JsonpChunkLoadingPlugin.js
lib/web/JsonpChunkLoadingRuntimeModule.js
lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js
test/Stats.test.js
test/__snapshots__/StatsTestCases.test.js.snap
types.d.ts

* fix missing char for module info header
* refactor jsonp chunk loading to avoid need to startup when not using deferred startup
bugfix
existing tests
no
nothing

fix startup logic preventing inlining entry modules

---

lib/serialization/BinaryMiddleware.js
lib/serialization/FileMiddleware.js
lib/serialization/ObjectMiddleware.js
lib/util/fs.js
test/BinaryMiddleware.unittest.js
types.d.ts

fixes #12126
* use 64bit instead 32bit for length now to allow cache files > 2GB.
* internally this is still limited to 52bit due to javascript number limits -> 4096TiB should be enough
* read cache file in multiple steps to allow files > 2GB
* add buffer deduplication to avoid duplicate code in cache file
* Tested it with 15GB cache file
bugfix, performance
yes
no
nothing

allow to store large caches

---

lib/cache/PackFileCacheStrategy.js
test/BuildDependencies.test.js
test/fixtures/buildDependencies/run.js

errors in initial cache no longer cause build dependencies to be ignored

---

declarations/WebpackOptions.d.ts
lib/Module.js
package.json
schemas/WebpackOptions.json
tsconfig.types.json
types.d.ts
yarn.lock

* matched value can be undefined in function rule condition (#12214)
bugfix
yes
no.
There might be new type-checking errors on dependent project if `undefined` or `null` is not handled and project is compiled in strict mode. But this only points out a case that exists before at runtime.
nothing

update typings to include undefined/null types

---

declarations.d.ts
lib/Compilation.js
lib/index.js
lib/validateSchema.js
package.json
types.d.ts
yarn.lock

fixes #12151
typings, bugfix
no
no
nothing

add some missing types and exports

---

declarations/WebpackOptions.d.ts
lib/rules/RuleSetCompiler.js
schemas/WebpackOptions.json
test/configCases/rule-set/query/index.js
types.d.ts

both are treated as empty string
fixes #12214
bugfix
yes
no (a bug fix)
nothing

treat `undefined` equal to not existing in rules

---

declarations/WebpackOptions.d.ts
lib/Compilation.js
lib/stats/DefaultStatsFactoryPlugin.js
lib/stats/DefaultStatsPresetPlugin.js
lib/stats/DefaultStatsPrinterPlugin.js
lib/stats/StatsFactory.js
lib/stats/StatsPrinter.js
package.json
schemas/WebpackOptions.json
test/__snapshots__/Cli.test.js.snap
types.d.ts
yarn.lock

* expose known stats context and options types
* fix `object` type in typings
typings
yes
no
nothing

improve typings

---

lib/util/propertyAccess.js
test/cases/code-generation/issue-12232/index.js
test/cases/code-generation/issue-12232/module.js

fix #12232

---

lib/ExportsInfo.js
lib/Module.js
test/__snapshots__/StatsTestCases.test.js.snap
test/hotCases/hashing/exports-info-influence/index.js
test/hotCases/hashing/exports-info-influence/module.js
test/hotCases/hashing/exports-info-influence/referencer.js
test/hotCases/hashing/exports-info-influence/webpack.config.js
types.d.ts

fixes a problem where changing modules affects hashes in some other part of the application during development
bugfix
yes
no
nothing

ignore cloned ExportInfo during hashing

---

lib/ChunkTemplate.js
lib/MainTemplate.js
lib/ModuleFilenameHelpers.js
lib/ModuleTemplate.js
lib/asset/AssetModulesPlugin.js
lib/cache/PackFileCacheStrategy.js
lib/dependencies/ContextDependency.js
lib/dependencies/ImportMetaPlugin.js
lib/index.js
lib/javascript/JavascriptParser.js
lib/json/JsonModulesPlugin.js
lib/optimize/SplitChunksPlugin.js
lib/serialization/BinaryMiddleware.js
lib/serialization/FileMiddleware.js
lib/serialization/SerializerMiddleware.js
lib/util/memoize.js
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js
lib/wasm-sync/WebAssemblyModulesPlugin.js

Hi
I am new to opensource contribution and I was interested in webpack so I started going through the codebase.
There was a function named memorize I didn't know what it did. after a couple of searches I came to know it was called memoize function.
It changes name of a function to more accurate one making it easy to understand the codebase for new contributors like me
This doesn't require any tests
I don't think so since it is an util
Nothing

Changed name of memorize function to memoize

---

lib/ContextModule.js
test/cases/context/issue-10969/index.js

resolves #10969
Bugfix
Yes
No
Nothing

refactor regex

---

lib/CompatibilityPlugin.js
lib/EvalDevToolModulePlugin.js
lib/EvalSourceMapDevToolPlugin.js
test/configCases/library/0-create-library/webpack.config.js
test/configCases/library/1-use-library/webpack.config.js

fix problems with using nested bundles with eval devtools

---

examples/source-map/README.md
lib/EvalDevToolModulePlugin.js
lib/EvalSourceMapDevToolPlugin.js
test/__snapshots__/StatsTestCases.test.js.snap

There was a typo and I appreciate webpack- 
was: "This devtool is **not neither** made for production nor for readable output files."
should be: "This devtool is **neither** made for production nor for readable output files."
Typo
No
No
Nothing

fix eval-source-map typo

---

lib/javascript/EnableChunkLoadingPlugin.js
lib/library/EnableLibraryPlugin.js
lib/wasm/EnableWasmLoadingPlugin.js

improve checkEnabled error messages

---

lib/dependencies/ImportMetaPlugin.js
lib/dependencies/URLPlugin.js
lib/javascript/JavascriptParser.js
test/cases/parsing/meta-property/index.js

fixes #12339
bugfix
yes
no
nothing

fix handling of MetaProperty

---

declarations/WebpackOptions.d.ts
lib/ExternalModuleFactoryPlugin.js
lib/ResolverFactory.js
lib/util/cleverMerge.js
schemas/WebpackOptions.json
test/cleverMerge.unittest.js
test/configCases/layer/rules/index.js
test/configCases/layer/rules/module.js
test/configCases/layer/rules/webpack.config.js
types.d.ts

feature
yes
no
`externals.byLayer` can be a function

byProperty functions, allow function for externals.byLayer

---

bin/webpack.js

fix: webpack-cli installation message

---

lib/optimize/SplitChunksPlugin.js
test/configCases/split-chunks/issue-12307/a.js
test/configCases/split-chunks/issue-12307/b.js
test/configCases/split-chunks/issue-12307/index.js
test/configCases/split-chunks/issue-12307/shared-module.js
test/configCases/split-chunks/issue-12307/webpack.config.js

fix bug where module size is added multiple times to the split chunk

---

lib/InvalidDependenciesModuleWarning.js
lib/NormalModule.js
lib/index.js
package.json
test/configCases/deprecations/invalid-dependencies/index.js
test/configCases/deprecations/invalid-dependencies/loader.js
test/configCases/deprecations/invalid-dependencies/warnings.js
test/configCases/deprecations/invalid-dependencies/webpack.config.js
test/statsCases/define-plugin/webpack.config.js
types.d.ts
yarn.lock

bugfix, warning
yes
no
nothing

fix problems with invalid dependencies from modules

---

lib/optimize/SplitChunksPlugin.js
test/ConfigTestCases.test.js
test/configCases/split-chunks/issue-12307/a.js
test/configCases/split-chunks/issue-12307/b.js
test/configCases/split-chunks/issue-12307/index.js
test/configCases/split-chunks/issue-12307/shared-module.js
test/configCases/split-chunks/issue-12307/webpack.config.js

fixes #12371
bugfix
yes
no
nothing

fix bug where module size is added multiple times to the split chunk info

---

lib/InvalidDependenciesModuleWarning.js
lib/Module.js
lib/ModuleDependencyWarning.js
lib/optimize/ConcatenatedModule.js
lib/util/internalSerializables.js
test/BuildDependencies.test.js
test/ConfigTestCases.template.js
test/TestCases.template.js

Ensure that no warnings/errors occur during testing
add serialization for some missing warnings
bugfix
yes
no
nothing

fix caching crash in ConcatenatedModule

---

declarations.test.d.ts
declarations/WebpackOptions.d.ts
package.json
types.d.ts
yarn.lock

bugfix (typings)
no
no
nothing

separate index signatures from properties to generate valid typescript

---

azure-pipelines.yml
declarations/WebpackOptions.d.ts
lib/WebpackOptionsDefaulter.js
package.json
schemas/WebpackOptions.json
test/configCases/resolving/issue-12386/index.js
test/configCases/resolving/issue-12386/webpack.config.js
yarn.lock

enable backward-compatible behavior for resolve.roots

---

lib/Compiler.js
lib/ContextModuleFactory.js
lib/FileSystemInfo.js
lib/serialization/FileMiddleware.js
lib/util/fs.js
test/configCases/types/filesystems/test.filter.js
test/configCases/types/filesystems/webpack.config.js
types.d.ts

fixes #12400
typings
yes
no
nothing

make filesystem types compatible with memfs and normal fs

---

lib/dependencies/AMDDefineDependency.js
test/cases/parsing/local-modules/index.js

The modified line was syntactically incorrect
Fixes https://github.com/webpack/webpack/issues/12310
bugfix for an obvious JS syntax error
Up to you guys
nothing

Fix #12310

---

lib/ContextModule.js

Refactoring.
No need in a new test.
No
Nothing

Remove duplicate import

---

lib/FileSystemInfo.js
lib/util/processAsyncTree.js

improve resolveBuildDependencies performance

---

lib/NormalModuleFactory.js

When upgrading from v4 some plugins/loaders are not still updated yet so it was difficult for the end-user to track it down properly. Adding the tap name improves debug
also related to https://twitter.com/sseraphini/status/1329848098965872643
not needed
no

fix(normal-module-factory): improve dx on deprecation messages

---

lib/javascript/JavascriptModulesPlugin.js
test/ConfigTestCases.template.js
test/__snapshots__/StatsTestCases.test.js.snap
test/configCases/module/runtime-chunk/index.js
test/configCases/module/runtime-chunk/test.config.js
test/configCases/module/runtime-chunk/webpack.config.js

fixes #12244
bugfix
yes
no
nothing

only return result of startup when needed

---

lib/library/AssignLibraryPlugin.js
test/Errors.test.js

improvement
Fixes #11632 
yes
No
Nothing

AssignLibraryPlugin: improve error message for invalid library name

---

lib/AutomaticPrefetchPlugin.js

improve AutomaticPrefetchPlugin performance

---

test/Compiler.test.js
test/MultiCompiler.test.js

test update.
Nope
Nope.
Nothing.

tests: update metadata

---

lib/debug/ProfilingPlugin.js
test/ProfilingPlugin.test.js
types.d.ts

fixes #11780
bugfix
yes
no
nothing

fix timestamps generated by ProfilingPlugin on some OS and node.js versions

---

lib/javascript/JavascriptParser.js
test/cases/parsing/iife/a.js
test/cases/parsing/iife/index.js
test/cases/parsing/iife/side-effect-call.js
test/cases/parsing/iife/test.filter.js

recreated from https://github.com/webpack/webpack/pull/12045
blocked by https://github.com/terser/terser/issues/880
fix #12044 
yes
no
nothing

fix: walk iife function expression params

---

lib/javascript/JavascriptModulesPlugin.js
test/__snapshots__/StatsTestCases.test.js.snap

refactoring, https://github.com/webpack/webpack/discussions/12514
No need
No
No

refactor: add semicolon

---

lib/CodeGenerationResults.js
lib/Dependency.js
lib/ModuleGraph.js
lib/ModuleGraphConnection.js
lib/NormalModule.js
lib/dependencies/HarmonyExportImportedSpecifierDependency.js
lib/dependencies/HarmonyImportSideEffectDependency.js
lib/dependencies/HarmonyImportSpecifierDependency.js
lib/dependencies/URLDependency.js
lib/optimize/InnerGraph.js
lib/util/runtime.js
types.d.ts

performance
exiting tests
no
nothing

avoid allocations

---

lib/ProgressPlugin.js
types.d.ts

bugfix
Not required.
No.
Not required

Fix types. Set ProgressPlugin options optional

---

lib/index.js
types.d.ts

export `EntryObject` for typescript usage:
```ts
import type {EntryObject} from 'webpack'
const entry: EntryObject = {
main: './src/index.js'
}
```
Currently I have to define it myself https://github.com/chenxsan/voidjs/blob/master/packages/voidjs-cli/src/DevServer/index.ts#L35:
```
export interface EntryObject {
[index: string]:
| [string, ...string[]]
| {
import: string | string[]
dependOn: string | string[]
}
}
```
No, I believe it's not needed.
Nope.
Nothing.

export EntryObject for typescript usage

---

lib/validateSchema.js

fix typo in validateScema.js

---

lib/hmr/lazyCompilationBackend.js

bugfix - `experiments.lazyCompilation.client` value is being ignored currently.
no, this is a quick fix for an experimental feature
no
nothing

Fix lazy compilation ignoring the 'client' configuration option

---

cspell.json
lib/Compilation.js
lib/FlagDependencyUsagePlugin.js
lib/ModuleProfile.js
lib/ProgressPlugin.js
lib/util/ArrayQueue.js
lib/util/AsyncQueue.js
lib/util/ParallelismFactorCalculator.js
test/__snapshots__/StatsTestCases.test.js.snap
types.d.ts

fixes #2811
feature
no
no
`profile: true` option will log out a summary of module timings

log out module profile summary when profiling is enabled

---

lib/util/runtime.js
test/configCases/entry/issue-12562/app.js
test/configCases/entry/issue-12562/home.js
test/configCases/entry/issue-12562/log.js
test/configCases/entry/issue-12562/test.config.js
test/configCases/entry/issue-12562/test.js
test/configCases/entry/issue-12562/webpack.config.js

fix #12562
bugfix
yes
no
nothing

fix #12562

---

lib/serialization/BinaryMiddleware.js
test/BinaryMiddleware.unittest.js

fix allocation sizes in BinaryMiddleware

---

test/StatsTestCases.test.js

exclude ModuleProfile from snapshot as it's not deterministic

---

lib/Generator.js
lib/NormalModule.js
lib/asset/AssetGenerator.js
lib/asset/AssetModulesPlugin.js
lib/cache/IdleFileCachePlugin.js
test/watchCases/cache/asset-modules/0/file.txt
test/watchCases/cache/asset-modules/0/index.js
test/watchCases/cache/asset-modules/0/other.txt
test/watchCases/cache/asset-modules/1/file.txt
test/watchCases/cache/asset-modules/1/other.txt
types.d.ts

fixes #12580
bugfix
yes
no
nothing

fix caching of asset modules

---

lib/config/defaults.js
test/Defaults.unittest.js

fix infinite loop in defaulting

---

azure-pipelines.yml
test/cases/parsing/logical-assignment/module.js

fix test case
ci
yes
no
nothing

run tests on node 15

---

.github/workflows/test.yml

github actions

---

lib/FlagDependencyUsagePlugin.js
test/configCases/split-chunks/asnyc-entries/chunk.js
test/configCases/split-chunks/asnyc-entries/index.js
test/configCases/split-chunks/asnyc-entries/module.js
test/configCases/split-chunks/asnyc-entries/package.json
test/configCases/split-chunks/asnyc-entries/test.config.js
test/configCases/split-chunks/asnyc-entries/test.filter.js
test/configCases/split-chunks/asnyc-entries/webpack.config.js
test/configCases/split-chunks/asnyc-entries/worker.js

fixes #12646
bugfix
yes
no
nothing

enforce side-effects on async entries similar to normal entrypoints

---

lib/Compilation.js
test/configCases/errors/depend-on-error/errors.js
test/configCases/errors/depend-on-error/webpack.config.js

bugfix fixes #11740
yes
no
nothing

fix crash when all modules of an entrypoint fail resolving and another entrypoint dependOn it

---

examples/module/README.md
examples/module/example.js
examples/module/webpack.config.js
lib/ChunkGraph.js
lib/CodeGenerationResults.js
lib/ExportsInfo.js
lib/LibManifestPlugin.js
lib/Module.js
lib/dependencies/HarmonyExportImportedSpecifierDependency.js
lib/dependencies/HarmonyExportInitFragment.js
lib/javascript/JavascriptModulesPlugin.js
lib/library/AbstractLibraryPlugin.js
lib/library/AmdLibraryPlugin.js
lib/library/AssignLibraryPlugin.js
lib/library/EnableLibraryPlugin.js
lib/library/ExportPropertyLibraryPlugin.js
lib/library/JsonpLibraryPlugin.js
lib/library/ModuleLibraryPlugin.js
lib/library/SystemLibraryPlugin.js
lib/runtime/GetChunkFilenameRuntimeModule.js
lib/stats/DefaultStatsFactoryPlugin.js
lib/util/IterableHelpers.js
lib/util/LazyBucketSortedSet.js
lib/util/SetHelpers.js
test/__snapshots__/StatsTestCases.test.js.snap
types.d.ts

very basic experimental library module

---

test/configCases/resolve/only-module/a/1.js
test/configCases/resolve/only-module/b/2.js
test/configCases/resolve/only-module/index.js
test/configCases/resolve/only-module/webpack.config.js
types.d.ts

Add test 
test for  `onlyModule`: `Redirect only exact matching request.` option in resolve.alias
No
None

Add test for OnlyModule option in resolve.alias

---

lib/json/JsonGenerator.js
test/__snapshots__/StatsTestCases.test.js.snap

Fixes #12641.
An improvement: Reduced size of emitted inlined JSON.
No. Please let me know if it is worth adding tests for a change like this.
No.
Nothing. There is no change to any part of the webpack interface.

Use single-quoted string for marshalled JSON

---

lib/stats/DefaultStatsPrinterPlugin.js
test/__snapshots__/StatsTestCases.test.js.snap

fixes #12653
hint, dx
yes
no
nothing

hint about how to show child errors and warnings

---

lib/optimize/InnerGraph.js
test/configCases/inner-graph/issue-12669-mini/module.js
test/configCases/inner-graph/issue-12669-mini/webpack.config.js
test/configCases/inner-graph/issue-12669/module.js
test/configCases/inner-graph/issue-12669/webpack.config.js

fix #12669

---

lib/Compilation.js
test/configCases/worker/node-worker/index.js
test/configCases/worker/node-worker/test.config.js
test/configCases/worker/node-worker/webpack.config.js

fixes #12676
bugfix
yes
no
nothing

order runtime chunks correctly for hashing

---

lib/index.js
types.d.ts

Export the `MultiStats` type for use in TypeScript project:
```js
import type {MultiStats} from 'webpack'
// ...
compiler.run((err?: WebpackError, stats?: MultiStats) => {});
```
No, I think it's not needed.
Nope.
Nothing.

export MultiStats type

---

lib/javascript/CommonJsChunkFormatPlugin.js
lib/runtime/StartupChunkDependenciesPlugin.js
test/configCases/library/0-create-library/webpack.config.js
test/configCases/library/1-use-library/webpack.config.js

related to https://github.com/vercel/next.js/pull/22187
bugfix
yes
no
nothing

fix regression when combining library + runtimeChunk + node target

---

lib/optimize/ModuleConcatenationPlugin.js

performance
will be covered by benchmarking
no
nothing

improve performance of finding modules for concatenation

---

declarations/WebpackOptions.d.ts
lib/Compilation.js
lib/stats/DefaultStatsFactoryPlugin.js
schemas/WebpackOptions.json
test/__snapshots__/StatsTestCases.test.js.snap
test/statsCases/logging-debug/webpack.config.js
types.d.ts

debug logging should be included in stats even if stats.logging is false

---

lib/optimize/ModuleConcatenationPlugin.js
test/__snapshots__/StatsTestCases.test.js.snap

fix logger name

---

lib/Dependency.js
lib/ExportsInfo.js
lib/FlagDependencyExportsPlugin.js
lib/dependencies/HarmonyExportImportedSpecifierDependency.js
lib/util/SetHelpers.js
test/cases/side-effects/issue-12570-second-try/chunk.js
test/cases/side-effects/issue-12570-second-try/index.js
test/cases/side-effects/issue-12570-second-try/inner-module.js
test/cases/side-effects/issue-12570-second-try/inner-reexport-chain.js
test/cases/side-effects/issue-12570-second-try/inner-reexport.js
test/cases/side-effects/issue-12570-second-try/inner-reexport2.js
test/cases/side-effects/issue-12570-second-try/module.js
test/cases/side-effects/issue-12570-second-try/package.json
test/cases/side-effects/issue-12570-second-try/reexport.js
types.d.ts

unset targets when a harmony star reexport is hidden by another one

---

lib/WebpackOptionsApply.js

fix `experiments.lazyCompilation: true`

---

lib/CaseSensitiveModulesWarning.js
lib/ChunkGraph.js
lib/Module.js
lib/ModuleGraph.js
lib/ModuleGraphConnection.js
lib/async-modules/InferAsyncModulesPlugin.js
lib/ids/OccurrenceModuleIdsPlugin.js
lib/javascript/JavascriptModulesPlugin.js
lib/optimize/ModuleConcatenationPlugin.js
test/__snapshots__/StatsTestCases.test.js.snap
types.d.ts

performance
existing tests
no
nothing

improve performance of ModuleConcatenationPlugin

---

lib/Compilation.js
lib/optimize/ModuleConcatenationPlugin.js
lib/util/semver.js
test/ConfigTestCases.template.js
test/configCases/rebuild/finishModules/loader.js
test/configCases/rebuild/finishModules/webpack.config.js
test/configCases/rebuild/rebuildWithNewDependencies/loader.js
test/configCases/rebuild/rebuildWithNewDependencies/webpack.config.js

instead the code geneneration cache will cover everything
performance
yes
no
nothing

ensure all successful compiled modules are persistent cached

---

lib/optimize/ConcatenatedModule.js
test/cases/parsing/issue-12769/index.js
test/cases/parsing/issue-12769/module.js
test/cases/parsing/issue-12769/other.js

fixes #12769
bugfix
yes
no
nothing

fixes #12769

---

lib/MultiCompiler.js
lib/Watching.js
lib/node/NodeWatchFileSystem.js
lib/util/fs.js
test/MultiCompiler.test.js
types.d.ts

fix some incorrect properties accesses
fix some edge cases with MultiCompiler
fixes #12770
bugfix
partially yes
no
nothing

MultiCompiler Watching fixes

---

lib/WebpackOptionsApply.js
test/configCases/externals/prefer-provided-over-built-in/index.js
test/configCases/externals/prefer-provided-over-built-in/webpack.config.js

fix: prefer provided external over built-in

---

lib/library/ModuleLibraryPlugin.js

Fix a grammar problem to keep consistency with https://github.com/webpack/webpack/blob/master/lib/library/AmdLibraryPlugin.js#L59
No need.
Nope.
Nothing.

fix a grammar problem

---

schemas/WebpackOptions.json
schemas/plugins/container/ContainerPlugin.json
schemas/plugins/container/ModuleFederationPlugin.json

Right now it's possible to pass an empty array to `output.library` option:
```js
output: {
library: []
}
};
```
And it outputs some weird results under `development` mode, see https://codesandbox.io/s/webpack-forked-6vvtk?file=/dist/main.js:
> (undefined = typeof undefined === "undefined" ? {} : undefined) = __webpack_exports__;
And it throws error when running `production` mode:
```bash
webpack --mode production
assets by status 1.77 KiB [cached] 1 asset
runtime modules 670 bytes 3 modules
./src/index.js 37 bytes [built] [code generated]
ERROR in main.js from Terser
Invalid assignment [main.js:46,64]
at js_error (/sandbox/node_modules/terser/dist/bundle.min.js:548:11)
at croak …
```

fix LibraryName of empty array

---

lib/config/defaults.js
test/Defaults.unittest.js

fix array expansion when using "..."

---

lib/Dependency.js
lib/NormalModuleFactory.js
lib/RawModule.js
lib/dependencies/ModuleDependency.js
lib/dependencies/URLDependency.js
test/__snapshots__/ConfigCacheTestCases.test.js.snap
test/__snapshots__/ConfigTestCases.test.js.snap
test/configCases/asset-modules/ignore/index.js
test/configCases/asset-modules/ignore/webpack.config.js
types.d.ts

new URL() will use `"data:,"` when ignored
bugfix
yes
no
nothing

allow to define "ignored modules" per dependency

---

lib/ChunkGraph.js
lib/Compiler.js
lib/ContextModule.js
lib/DelegatedModule.js
lib/DllModule.js
lib/Module.js
lib/ModuleGraph.js
lib/NormalModule.js
lib/NormalModuleFactory.js
lib/optimize/ConcatenatedModule.js
lib/optimize/ModuleConcatenationPlugin.js
types.d.ts

fixes #12771
bugfix, memory leak
nope
no
nothing

cleanup modules after compilation to avoid leaking references when they are cached

---

lib/runtime/AutoPublicPathRuntimeModule.js
lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js
test/ConfigTestCases.template.js
test/HotTestCases.template.js
test/helpers/createFakeWorker.js

Fix https://github.com/webpack/webpack/issues/12577
fix
wip
No
None

fix: prefix public path in importScripts

---

lib/javascript/JavascriptModulesPlugin.js
lib/library/AbstractLibraryPlugin.js
lib/library/AssignLibraryPlugin.js
test/configCases/library/type-assign-properties/index.js
test/configCases/library/type-assign-properties/webpack.config.js
test/configCases/library/type-assign/index.js
test/configCases/library/type-assign/webpack.config.js
types.d.ts

closes https://github.com/webpack/webpack/issues/12851.
Not sure if it's the right fix, any suggestion welcomed.
Yes.
No.
Nothing.

Opt out of strict mode for some library types

---

lib/node/ReadFileChunkLoadingRuntimeModule.js
lib/node/RequireChunkLoadingRuntimeModule.js
lib/runtime/AutoPublicPathRuntimeModule.js
lib/util/identifier.js
lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js
test/configCases/entry/weird-names2/chunk.js
test/configCases/entry/weird-names2/index.js
test/configCases/entry/weird-names2/test.config.js
test/configCases/entry/weird-names2/webpack.config.js
test/identifier.unittest.js

allow to place runtime outside of the output path

---

lib/javascript/JavascriptModulesPlugin.js
test/configCases/library/type-assign/index.js
test/configCases/library/type-assign/module.js

Fix #12908
Not yet (how do I test this?)
No
Nothing

fix: fix an issue with an output commenting out bootstrap code

---

lib/Template.js
lib/javascript/ArrayPushCallbackChunkFormatPlugin.js
test/configCases/library/type-assign-properties/webpack.config.js
test/configCases/library/type-assign-runtime-chunk/index.js
test/configCases/library/type-assign-runtime-chunk/test.config.js
test/configCases/library/type-assign-runtime-chunk/webpack.config.js
types.d.ts

fix problem with strict mode for assigning libraries with separate runtime chunk

---

lib/MultiCompiler.js
test/MultiCompiler.test.js

fixes https://github.com/vercel/next.js/issues/23125
bugfix
yes
no
nothing

fix race condition in MultiCompiler queueing

---

examples/README.md

fix path to worker example

---

lib/NormalModule.js
test/cases/loaders/utils/index.js
test/cases/loaders/utils/loader.js

feature
yes
no
loader context has `utils: { contextify(context, absolutePath), absolutify(context, request) }`

offer contextify and absolutify in loader context as utils

---

lib/RecordIdsPlugin.js
lib/javascript/ArrayPushCallbackChunkFormatPlugin.js
lib/javascript/CommonJsChunkFormatPlugin.js
lib/javascript/StartupHelpers.js
test/__snapshots__/StatsTestCases.test.js.snap
test/watchCases/cache/new-split-chunk-entry-node/0/entry.js
test/watchCases/cache/new-split-chunk-entry-node/0/index.js
test/watchCases/cache/new-split-chunk-entry-node/0/module.js
test/watchCases/cache/new-split-chunk-entry-node/0/shared-dep.js
test/watchCases/cache/new-split-chunk-entry-node/0/shared.js
test/watchCases/cache/new-split-chunk-entry-node/1/module.js
test/watchCases/cache/new-split-chunk-entry-node/2/module.js
test/watchCases/cache/new-split-chunk-entry-node/3/entry.js
test/watchCases/cache/new-split-chunk-entry-node/4/module.js
test/watchCases/cache/new-split-chunk-entry-node/5/module.js
test/watchCases/cache/new-split-chunk-entry-node/webpack.config.js
test/watchCases/cache/new-split-chunk-entry-web/0/entry.js
test/watchCases/cache/new-split-chunk-entry-web/0/index.js
test/watchCases/cache/new-split-chunk-entry-web/0/module.js
test/watchCases/cache/new-split-chunk-entry-web/0/shared-dep.js
test/watchCases/cache/new-split-chunk-entry-web/0/shared.js
test/watchCases/cache/new-split-chunk-entry-web/1/module.js
test/watchCases/cache/new-split-chunk-entry-web/2/module.js
test/watchCases/cache/new-split-chunk-entry-web/3/entry.js
test/watchCases/cache/new-split-chunk-entry-web/4/module.js
test/watchCases/cache/new-split-chunk-entry-web/5/module.js
test/watchCases/cache/new-split-chunk-entry-web/webpack.config.js

* fix incorrect id assignment of record ids plugin
* this causes ids changing unnecessary
* fix library exports when using onChunks in entry
bugfix
yes
no
nothing

fix caching bug when split chunks of an entrypoint change and modules of the entrypoint stay equal

---

lib/NormalModule.js

improve error handling in beforeLoaders hook

---

lib/hmr/LazyCompilationPlugin.js
test/hotCases/lazy-compilation/simple/index.js
test/hotCases/lazy-compilation/simple/module.js

* allow `module.hot/import.meta.webpackHot.accept/decline` dependencies for lazy compilation
* fix crash using updating lazy compiled modules
bugfix, fixes #12941
yes
no
nothing

fix lazy compilation caching

---

examples/worker/build.js

bugfix for example. Currently, publicPath from config is ignored which leads to error when loading chunks inside the worker.

Fix worker example

---

examples/worker/README.md
examples/worker/example.js
lib/dependencies/WorkerDependency.js
lib/dependencies/WorkerPlugin.js

update worker example
bugfix, example
no
no
nothing

fix duplicate new URL and spacing for worker dependencies

---

lib/NormalModule.js

Ensure complete module data is restored from cache. This PR https://github.com/webpack/webpack/pull/12894 introduced an issue, where data stored in `factoryMeta` will be lost on incremental build (e.g. sideEffectsFree flag) that affects the code generation output. 
I could not find any existing test cases for the logic above. But let me know if this change requires any additional tests.
No
N/A

fix(NormalModule): call super to restore base module cache data

---

lib/FileSystemInfo.js

improve logging for resolving build dependencies

---

lib/util/deterministicGrouping.js
test/deterministicGrouping.unittest.js

fix some edge cases in deterministicGrouping and add more tests

---

lib/Dependency.js
lib/index.js
types.d.ts

Export two missing classes 
1. AsyncDependenciesBlock 
2. ModuleDependency
fix: https://github.com/webpack/webpack/issues/12967
No. couldn't find where to put them.
No
No documentation found for webpack exports

Export AsyncDependenciesBlock and ModuleDependency

---

lib/FileSystemInfo.js
lib/cache/PackFileCacheStrategy.js
test/fixtures/buildDependencies/node_modules/dependency-with-optional/package.json
test/fixtures/buildDependencies/run.js
types.d.ts

fix caching crash when using fsevents in build dependencies

---

lib/FileSystemInfo.js
test/BuildDependencies.test.js
test/fixtures/buildDependencies/node_modules/dep-with-exports/package.json
test/fixtures/buildDependencies/node_modules/dependency-with-exports/main.js
test/fixtures/buildDependencies/node_modules/dependency-with-exports/package.json
test/fixtures/buildDependencies/node_modules/require-dependency-with-exports/index.js
test/fixtures/buildDependencies/run.js

improve resolving of build dependencies when `exports` field is used

---

lib/util/runtime.js
test/configCases/side-effects/issue-13063/another.js
test/configCases/side-effects/issue-13063/test.config.js
test/configCases/side-effects/issue-13063/tst_examples_uiform.js
test/configCases/side-effects/issue-13063/tst_examples_uitable.js
test/configCases/side-effects/issue-13063/vendors/index.js
test/configCases/side-effects/issue-13063/vendors/select.js
test/configCases/side-effects/issue-13063/vendors/select2.js
test/configCases/side-effects/issue-13063/vendors/types.js
test/configCases/side-effects/issue-13063/vendors/uuid.js
test/configCases/side-effects/issue-13063/webpack.config.js

fixes #13063
bugfix
yes
no
nothing

fix subtraction of runtimes

---

lib/hmr/HotModuleReplacement.runtime.js
lib/hmr/JavascriptHotModuleReplacement.runtime.js
test/hotCases/runtime/root-error/errors1.js
test/hotCases/runtime/root-error/index.js
test/hotCases/runtime/root-error/webpack.config.js

ensure that entrypoints are always re-executed when updated

---

lib/Watching.js
test/MultiCompiler.test.js

make sure that invalid event is only reported once

---

lib/Compilation.js
lib/DefinePlugin.js
lib/Module.js
lib/NormalModule.js
test/watchCases/cache/add-defines/0/a.js
test/watchCases/cache/add-defines/0/b.js
test/watchCases/cache/add-defines/0/c.js
test/watchCases/cache/add-defines/0/index.js
test/watchCases/cache/add-defines/1/index.js
test/watchCases/cache/add-defines/2/index.js
test/watchCases/cache/add-defines/3/index.js
test/watchCases/cache/add-defines/webpack.config.js
types.d.ts

fixes https://github.com/vercel/next.js/issues/23901
bugfix
yes
no
nothing

DefinePlugin invalidates modules when new defines are added

---

lib/Compilation.js
lib/FlagDependencyExportsPlugin.js
lib/ModuleGraph.js
lib/dependencies/HarmonyExportDependencyParserPlugin.js
lib/dependencies/HarmonyExportImportedSpecifierDependency.js
lib/serialization/ObjectMiddleware.js
lib/util/WeakTupleMap.js
package.json
test/checkArrayExpectation.js
types.d.ts
yarn.lock

* add a cache in the ModuleGraph while this is uncached
* cache discovering of other star exports
* cache `getMode`
fixes #13107
performance
N/A
no
nothing

improve performance of `export *`

---

lib/Compilation.js
lib/RuntimePlugin.js
lib/node/CommonJsChunkLoadingPlugin.js
lib/node/ReadFileCompileAsyncWasmPlugin.js
lib/node/ReadFileCompileWasmPlugin.js
lib/runtime/StartupChunkDependenciesPlugin.js
lib/web/FetchCompileAsyncWasmPlugin.js
lib/web/FetchCompileWasmPlugin.js
lib/web/JsonpChunkLoadingPlugin.js
lib/webworker/ImportScriptsChunkLoadingPlugin.js

handle falsy entry options correctly

---

declarations/WebpackOptions.d.ts
schemas/WebpackOptions.json
test/__snapshots__/Cli.test.js.snap
types.d.ts

chore 
#9866
Update test snapshots
Nope
N/A

chore: update cache property descriptions

---

lib/ChunkGraph.js
test/configCases/split-chunks/runtime-chunk-node-13130/a.js
test/configCases/split-chunks/runtime-chunk-node-13130/b.js
test/configCases/split-chunks/runtime-chunk-node-13130/shared.js
test/configCases/split-chunks/runtime-chunk-node-13130/test.config.js
test/configCases/split-chunks/runtime-chunk-node-13130/webpack.config.js

fix #13130
bugfix
yes
no
nothing

fix #13130

---

lib/serialization/BinaryMiddleware.js

performance fix
n/a
no
nothing

fix performance regression

---

lib/node/NodeTargetPlugin.js

fixes https://github.com/webpack/enhanced-resolve/pull/286
bugfix
no
no
nothing

add pnpapi as builtin

---

lib/javascript/ArrayPushCallbackChunkFormatPlugin.js
lib/javascript/JavascriptModulesPlugin.js
lib/library/AmdLibraryPlugin.js
lib/web/JsonpChunkLoadingRuntimeModule.js
test/__snapshots__/StatsTestCases.test.js.snap
test/configCases/library/0-create-library/webpack.config.js
test/configCases/library/1-use-library/test.config.js
test/configCases/library/1-use-library/webpack.config.js

fixes #13165
bugfix
yes
no
nothing

fix returning exports from runtime for libraries

---

lib/Dependency.js
lib/dependencies/NullDependency.js
lib/util/AsyncQueue.js
lib/util/comparators.js
types.d.ts

improve performance for cache (de)serialization
performance
n/a
no
nothing

improve serialization of dependency locations

---

declarations.d.ts
lib/javascript/JavascriptParser.js
lib/optimize/InnerGraphPlugin.js
package.json
test/cases/parsing/es2020/index.js
test/cases/parsing/es2020/module.js
test/cases/parsing/es2020/test.filter.js
test/configCases/inner-graph/class/module.js
test/configCases/inner-graph/class/test.filter.js
test/configCases/inner-graph/class/webpack.config.js
test/helpers/supportsClassFields.js
types.d.ts
yarn.lock

add support for class fields

---

lib/Compilation.js

improve module dependency processing performance

---

.github/workflows/test.yml
azure-pipelines.yml
test/cases/parsing/bom/index.js
test/cases/wasm/table/index.js

run tests on Node.js 16

---

lib/NormalModuleFactory.js
test/configCases/errors/asset-options-validation/errors.js
test/configCases/errors/asset-options-validation/index.js
test/configCases/errors/asset-options-validation/text.txt
test/configCases/errors/asset-options-validation/webpack.config.js

catch errors thrown during parser/generation creation

---

lib/buildChunkGraph.js
test/configCases/entry/depend-on-advanced/other-vendors.js
test/configCases/entry/depend-on-advanced/page2.js
test/configCases/entry/depend-on-advanced/page3.js
test/configCases/entry/depend-on-advanced/test.config.js
test/configCases/entry/depend-on-advanced/webpack.config.js
test/configCases/entry/depend-on-bug/app.js
test/configCases/entry/depend-on-bug/node_modules/isomorphic-fetch.js
test/configCases/entry/depend-on-bug/page1.js
test/configCases/entry/depend-on-bug/test.config.js
test/configCases/entry/depend-on-bug/webpack.config.js

fix too many modules are included in chunks when using chained dependOn

---

lib/FileSystemInfo.js

Users confuse this message with a problem. But it's not a problem.
bugfix
no
no
nothing

make ESM tracking info message less verbose

---

.github/workflows/test.yml
.gitignore
appveyor.yml
azure-pipelines.yml
package.json
test/BuildDependencies.test.js
yarn.lock

fix coverage for child process

---

README.md

Docs
Fixes https://github.com/webpack/webpack/issues/13357
NA
No
Nothing

docs: remove traceur-loader

---

lib/MultiCompiler.js
lib/Watching.js
test/MultiCompiler.test.js

respect multi compiler `dependencies` and `parallelism` when using `invalidate`

---

lib/NormalModule.js
test/Compiler.test.js
test/WatchTestCases.test.js

fixes #13330

---

test/ProfilingPlugin.test.js

improve stability of ProfilingPlugin test

---

lib/Compiler.js
lib/NormalModule.js
lib/Watching.js
package.json
test/TestCases.template.js
test/WatchDetection.test.js
types.d.ts
yarn.lock

track changes and removals correctly during watching

---

lib/optimize/ConcatenatedModule.js
package.json
test/cases/parsing/class-properties/index.js
test/cases/parsing/class-properties/module.js
test/cases/parsing/class-properties/test.filter.js
yarn.lock

fixes #13371
bugfix
yes
no
nothing

add workaround for broken eslint-scope package regarding class field support

---

test/TestCases.template.js

increase timeout

---

lib/node/NodeEnvironmentPlugin.js
test/configCases/asset-modules/file-url/webpack.config.js

add fsStartTime for single runs

---

lib/HotModuleReplacementPlugin.js
test/HotTestCases.template.js
test/hotCases/update.js
test/hotCases/worker/remove-add-worker/compute.js
test/hotCases/worker/remove-add-worker/index.js
test/hotCases/worker/remove-add-worker/test.filter.js
test/hotCases/worker/remove-add-worker/worker.js

fixes https://github.com/webpack/webpack-dev-server/issues/3233
bugfix
yes
no
nothing

avoid generating hmr updates for previously not existing runtimes

---

test/helpers/createFakeWorker.js
test/hotCases/worker/move-between-runtime/chunk.js
test/hotCases/worker/move-between-runtime/chunkS.js
test/hotCases/worker/move-between-runtime/index.js
test/hotCases/worker/move-between-runtime/module.js
test/hotCases/worker/move-between-runtime/moduleA.js
test/hotCases/worker/move-between-runtime/moduleAs.js
test/hotCases/worker/move-between-runtime/moduleB.js
test/hotCases/worker/move-between-runtime/moduleBs.js
test/hotCases/worker/move-between-runtime/moduleS.js
test/hotCases/worker/move-between-runtime/test.filter.js
test/hotCases/worker/move-between-runtime/worker.js
test/hotCases/worker/move-between-runtime/workerA.js
test/hotCases/worker/move-between-runtime/workerB.js

fixes #12789
test case
yes
no
nothing

add test case for moving modules and chunks between runtimes

---

lib/ExportsInfo.js

increment index in sorting

---

bin/webpack.js

bugfix
tested manually
No
Nothing

fix: usage `npx webpack`

---

lib/Chunk.js
test/configCases/entry/depend-on-non-js/a.css
test/configCases/entry/depend-on-non-js/a.js
test/configCases/entry/depend-on-non-js/b.css
test/configCases/entry/depend-on-non-js/b.js
test/configCases/entry/depend-on-non-js/test.config.js
test/configCases/entry/depend-on-non-js/webpack.config.js

getAllInitialChunks really returns all of them

---

lib/serialization/PlainObjectSerializer.js

fixes #13588
bugfix, perf
no
no
nothing

reduce algorithmic complexity of the structure analysis for plain objects serialization

---

README.md

In general, we should capitalize the first word, all nouns, all verbs (even short ones, like is), all adjectives, and all proper nouns. That means you should lowercase articles, conjunctions, and prepositions.

[Documentation]capitalized first letter of sentence

---

lib/cli.js
test/__snapshots__/Cli.test.js.snap

Improve description to be more specific about which option configuration.
Yes, updated snapshot.
Maybe
Nothing

improve description for reset type flags

---

package.json
test/__snapshots__/StatsTestCases.test.js.snap
yarn.lock

Fix https://github.com/webpack/webpack/pull/13482
Fix https://github.com/webpack/webpack/pull/13377
update dep - `terser` & `terser-webpack-plugin`
Yes updated snapshots
No
Nothing

chore: update  `terser` and `terser-webpack-plugin`

---

lib/javascript/JavascriptParser.js
lib/optimize/InnerGraphPlugin.js
test/TestCasesProdGlobalUsed.test.js
test/cases/inner-graph/class-dynamic-props/index.js
test/cases/inner-graph/class-dynamic-props/module.js
test/cases/inner-graph/class-dynamic-props/test.filter.js
test/cases/inner-graph/class-dynamic-props/unused1.js
test/cases/inner-graph/class-dynamic-props/used1.js
test/cases/inner-graph/simple/module.js

fixes #13575
bugfix
yes
no
nothing

assign class property keys to the correct top level symbol

---

test/ConfigCacheTestCases.test.js
test/TestCasesCachePack.test.js

improve test suite performance

---

test/cases/wasm/v128/test.filter.js

@xtuc this test is now executed in node 16.4.0, but fails to compile with
`CompileError: WebAssembly.instantiate(): Compiling function #0 failed: memory`
test
test
no
nothing

disable test because it doesn't work

---

lib/hmr/lazyCompilationBackend.js
lib/optimize/ModuleConcatenationPlugin.js
test/ConfigTestCases.template.js
test/HotTestCases.template.js
test/helpers/createLazyTestEnv.js

also fix memory leaks in test suite
bugfix
no
no
nothing

improve disposing of lazy compilation backend server

---

examples/module-code-splitting/README.md
examples/module-worker/README.md
examples/module-worker/build.js
examples/module-worker/chat-module.js
examples/module-worker/chat-worker.js
examples/module-worker/example.js
examples/module-worker/fib-worker.js
examples/module-worker/fibonacci.js
examples/module-worker/index.html
examples/module-worker/template.md
examples/module-worker/webpack.config.js
examples/worker/README.md
lib/WebpackOptionsApply.js
lib/dependencies/WorkerPlugin.js
lib/esm/ModuleChunkLoadingRuntimeModule.js

improve module support for WebWorkers

---

lib/serialization/FileMiddleware.js

as slice doesn't work correctly in some environments for unknown reasons
bugfix
no
no
nothing

use Buffer.from instead of slice

---

lib/runtime/AsyncModuleRuntimeModule.js
test/__snapshots__/StatsTestCases.test.js.snap

**What existing problem does the pull request solve? 
some tools will check whether build assets conform to es5.
code style change
No need
No
No need

use es5 for async module runtime

---

lib/TemplatedPathPlugin.js
lib/serialization/BinaryMiddleware.js
lib/serialization/FileMiddleware.js
test/TestCases.template.js
test/cases/large/big-assets/generate-big-asset-loader.js
test/cases/large/big-assets/index.js
test/cases/large/big-assets/test.config.js
test/cases/large/big-assets/test.filter.js

reduce amount of buffer splitting for large cache files

---

package.json
yarn.lock

chore(deps): update `acorn`

---

lib/ExternalModule.js
test/configCases/externals/externals-system/index.js
test/configCases/externals/externals-system/reexport-external.js
test/configCases/externals/externals-system/test.config.js
test/configCases/externals/externals-system/webpack.config.js

fix #13667

---

test/Errors.test.js
test/PersistentCaching.test.js

fix CI performance issues

---

azure-pipelines.yml

set CI flag in azure pipelines

---

lib/json/JsonData.js
lib/json/JsonGenerator.js
lib/json/JsonParser.js
lib/util/internalSerializables.js

bugfix (avoid warning)
no
no
nothing

serialize json data as buffer and decode on demand

---

lib/ExternalModule.js
lib/optimize/ConcatenatedModule.js
lib/util/makeSerializable.js
test/ConfigTestCases.template.js
test/configCases/module/externals/imported.js
test/configCases/module/externals/index.js
test/configCases/module/externals/module.js
test/configCases/module/externals/test.config.js
test/configCases/module/externals/webpack.config.js

fix concatenation of module externals

---

package.json
yarn.lock

Revert "chore(deps-dev): bump husky from 6.0.0 to 7.0.1"

---

lib/ExternalModuleFactoryPlugin.js
test/configCases/externals/externals-in-commons-chunk/webpack.config.js

fix #13744
bugfix
yes
no
nothing

fix #13744

---

lib/SourceMapDevToolPlugin.js

fix: #13740 
no, I want to write a test case, but I don't know where to write it. Can you give me some advice? thank you
no
no

fix: sourceMapDevToolPlugin options test add cjs

---

lib/webpack.js

Just a small grammar typo fix.
No.
No.
Nothing.

fix a grammar typo

---

.github/workflows/test.yml
azure-pipelines.yml

rerun test suites once

---

lib/Template.js
lib/javascript/ArrayPushCallbackChunkFormatPlugin.js
lib/javascript/JavascriptModulesPlugin.js
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js
test/__snapshots__/StatsTestCases.basictest.js.snap
types.d.ts

generate "use strict" only when really needed

---

.github/workflows/test.yml

use `actions/setup-node@v2`
https://github.com/marketplace/actions/setup-node-js-environment
No
No
Nothing

ci: use `actions/setup-node@v2`

---

lib/dependencies/AMDRequireDependency.js
package.json
test/__snapshots__/StatsTestCases.basictest.js.snap
yarn.lock

improves performance
performance
no
no
nothing

update to webpack-sources version 3

---

package.json
test/__snapshots__/StatsTestCases.basictest.js.snap
yarn.lock

update webpack-sources to 3.1.1

---

hot/only-dev-server.js
hot/poll.js
hot/signal.js

Issue: https://github.com/webpack/webpack/issues/13876
bugfix
No
No
Nothing

fix hot/poll, hot/condition, hot/only-dev-server infinity recursion

---

package.json
yarn.lock

bugfix, performance
yes
no
nothing

upgrade webpack-sources to 3.2.0

---

lib/Compilation.js

performance, memory usage
no
no
nothing

limit the number of parallel generated chunks

---

hot/only-dev-server.js
hot/poll.js
hot/signal.js
lib/hmr/HotModuleReplacement.runtime.js

fix hmr check returning empty array

---

lib/optimize/SplitChunksPlugin.js

fix indeterminism with splitChunks.maxSize

---

lib/Compilation.js
test/configCases/parsing/optional/index.js
test/configCases/parsing/optional/warnings.js
test/configCases/parsing/optional/webpack.config.js

fixes #11594
bugfix
yes
no
nothing

optional modules will not fail the build when bail is set

---

lib/HotModuleReplacementPlugin.js

Typo fix in property name: `chunkHashs` -> `chunkHashes`
No
Potentially an internal breaking change to plugins.
Nothing, I don't think.

fix: chunkHashes typo

---

declarations/WebpackOptions.d.ts
declarations/plugins/schemes/HttpUriPlugin.d.ts
schemas/WebpackOptions.json
schemas/plugins/schemes/HttpUriPlugin.json
test/__snapshots__/Cli.test.js.snap
types.d.ts

Just a typo fix.
No need.
Nope.
Nothing.

fix a typo

---

cspell.json
lib/CompatibilityPlugin.js
lib/NormalModule.js
lib/Parser.js
lib/javascript/JavascriptParser.js
test/cases/parsing/hashbang/file.js
test/cases/parsing/hashbang/file.mjs
test/cases/parsing/hashbang/index.js
types.d.ts

implements https://github.com/tc39/proposal-hashbang
fixes https://github.com/vercel/next.js/issues/27806
feature
yes
no
nothing

handle hashbangs in javascript files

---

lib/serialization/BinaryMiddleware.js

improve allocations needed in serialization

---

README.md

Remove deprecated loaders from README
No
No
Nothing

docs: remove deprecated loaders

---

lib/RuntimeGlobals.js
lib/esm/ModuleChunkLoadingRuntimeModule.js
lib/node/ReadFileChunkLoadingRuntimeModule.js
lib/node/ReadFileCompileAsyncWasmPlugin.js
lib/node/ReadFileCompileWasmPlugin.js
lib/node/RequireChunkLoadingRuntimeModule.js
lib/wasm-async/AsyncWasmLoadingRuntimeModule.js
lib/wasm-sync/WasmChunkLoadingRuntimeModule.js
lib/web/FetchCompileAsyncWasmPlugin.js
lib/web/FetchCompileWasmPlugin.js
lib/web/JsonpChunkLoadingRuntimeModule.js
lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js
test/HotTestCases.template.js
test/Stats.test.js
test/__snapshots__/StatsTestCases.basictest.js.snap
test/configCases/library/0-create-library/webpack.config.js
test/hotCases/chunks/update-chunk-loading-runtime/chunk.js
test/hotCases/chunks/update-chunk-loading-runtime/index.js
test/hotCases/chunks/update-chunk-loading-runtime/node_modules/vendor.js
test/hotCases/chunks/update-chunk-loading-runtime/webpack.config.js
types.d.ts

ignore duplicate chunk loads
bugfix
yes
no
nothing

keep state of chunk loading during hmr updates

---

lib/FileSystemInfo.js
test/FileSystemInfo.unittest.js

fixes #14028
bugfix
yes
no
nothing

fix crash when trying to snapshot not existing directory

---

lib/EvalSourceMapDevToolPlugin.js
lib/NormalModule.js
lib/SourceMapDevToolPlugin.js
lib/optimize/ConcatenatedModule.js
lib/util/identifier.js
test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
test/__snapshots__/ConfigTestCases.basictest.js.snap
test/__snapshots__/StatsTestCases.basictest.js.snap
test/statsCases/context-independence/test.config.js
test/statsCases/context-independence/webpack.config.js

* ConcatenatedModule.identifier()
* NormalModule source urls
fixes #14014
bugfix
yes
no
nothing

make some things context-independent

---

lib/util/propertyAccess.js
package.json
test/__snapshots__/StatsTestCases.basictest.js.snap

fix(utils): avoid reserved property under ES

---

lib/Compiler.js
lib/Watching.js
test/MultiCompiler.test.js

do not shutdown cache when closing only the watching
bugfix
no
yes, but behavior was unintended and broken
nothing

close watching when closing compiler

---

lib/ChunkGraph.js
lib/Compilation.js
lib/HotModuleReplacementPlugin.js
lib/RuntimeModule.js
lib/runtime/GetChunkFilenameRuntimeModule.js
test/configCases/worker/custom-worker/webpack.config.js
test/configCases/worker/node-worker-hmr/index.js
test/configCases/worker/node-worker-hmr/module.js
test/configCases/worker/node-worker-hmr/test.config.js
test/configCases/worker/node-worker-hmr/test.filter.js
test/configCases/worker/node-worker-hmr/webpack.config.js
test/configCases/worker/node-worker-hmr/worker.js
test/configCases/worker/node-worker-named/webpack.config.js
test/configCases/worker/web-worker/webpack.config.js
test/configCases/worker/worker-contenthash/webpack.config.js
types.d.ts

upgrade filename runtime module to full hash module when referencing a full hash chunk

---

test/configCases/plugins/mini-css-extract-plugin/test.config.js
test/configCases/plugins/mini-css-extract-plugin/webpack.config.js

add mini-css import module test case

---

lib/ExternalModule.js
lib/InitFragment.js
lib/optimize/MangleExportsPlugin.js
lib/util/internalSerializables.js
test/ConfigTestCases.template.js
test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
test/__snapshots__/ConfigTestCases.basictest.js.snap
test/configCases/externals/concatenated-module/index.js
test/configCases/externals/concatenated-module/test.filter.js
test/configCases/externals/concatenated-module/webpack.config.js
test/helpers/asModule.js
types.d.ts

fix null module externals

---

.github/workflows/test.yml
azure-pipelines.yml

https://bugs.chromium.org/p/v8/issues/detail?id=12188
CI bugfix
CI
no
nothing

fix node.js because of v8 bug

---

lib/cache/PackFileCacheStrategy.js
lib/serialization/ObjectMiddleware.js
lib/util/serialization.js

split fresh packs by time
add comments
fix loosing cache
correctly store a lazy
performance
no
no
nothing

split fresh packs by time

---

lib/runtime/RelativeUrlRuntimeModule.js

remove unnecessary Object.assign

---

.github/workflows/test.yml
azure-pipelines.yml

Revert "fix node.js because of v8 bug"

---

lib/cache/PackFileCacheStrategy.js

bugfix fixes #14258 fixes #14250
no
no
nothing

allow process to exit and cancel timeout again

---

lib/FileSystemInfo.js

avoid allocations in SnapshotOptimization

---

lib/JavascriptMetaInfoPlugin.js
lib/index.js
lib/optimize/InnerGraph.js
test/configCases/inner-graph/eval-bailout/module.js
test/configCases/inner-graph/eval-bailout/webpack.config.js
types.d.ts

expose InnerGraph and runtime utils
feature
yes
no
nothing

avoid bailout of unused eval

---

lib/util/hash/xxhash64.js

faster utf-8 conversion for short strings

---

lib/serialization/BinaryMiddleware.js

performance
existing tests
no
nothing

write short strings more efficient to cache

---

lib/AsyncDependenciesBlock.js
lib/dependencies/CachedConstDependency.js
lib/dependencies/ConstDependency.js
lib/dependencies/JsonExportsDependency.js
lib/dependencies/ModuleDecoratorDependency.js
lib/dependencies/ProvidedDependency.js
lib/dependencies/PureExpressionDependency.js
lib/dependencies/RuntimeRequirementsDependency.js
test/__snapshots__/StatsTestCases.basictest.js.snap

cache computation of values passed for hashing

---

lib/Compilation.js
lib/Compiler.js
lib/ModuleFactory.js
lib/NormalModuleFactory.js
test/configCases/cache-dependencies/managed-items/webpack.config.js
test/watchCases/snapshot/unable-to-snapshot/webpack.config.js
types.d.ts

move unsafe cache from NormalModuleFactory to Compilation to skip more processing
performance
existing tests
no
nothing

improve unsafe cache performance

---

lib/Compilation.js
lib/Compiler.js
types.d.ts

* fix accidentically shared mem caches
* fix checking references when restoring mem caches
bugfix
no
no
nothing

experiments.cacheUnaffected bugfixes

---

lib/DefinePlugin.js
test/watchCases/cache/add-defines/3/index.js

performance, memory
yes
no
nothing

use a hash instead of a list to track DefinePlugin dependency

---

lib/DefinePlugin.js

give DefinePlugin a different key to avoid conflicting with different variants of it

---

lib/AsyncDependenciesBlock.js
lib/Chunk.js
lib/ChunkGraph.js
lib/DependencyTemplates.js
lib/DllModule.js
lib/ExportsInfo.js
lib/ExternalModule.js
lib/javascript/ArrayPushCallbackChunkFormatPlugin.js
test/__snapshots__/StatsTestCases.basictest.js.snap

chore: merge multi hash.update

---

lib/ExternalModule.js
test/watchCases/cache/unsafe-cache/0/index.js
test/watchCases/cache/unsafe-cache/0/proxy-module.js
test/watchCases/cache/unsafe-cache/1/changing-module.js
test/watchCases/cache/unsafe-cache/2/changing-module.js
test/watchCases/cache/unsafe-cache/webpack.config.js
types.d.ts

allow ExternalModules to be unsafe cached

---

lib/util/StringXor.js

```
1 strings: StringXor new is 49.1% faster than StringXor old (140.3873 vs 275.5549 for 524288x)
2 strings: StringXor new is 56.7% faster than StringXor old (170.9636 vs 395.1243 for 524288x)
4 strings: StringXor new is 64% faster than StringXor old (103.3419 vs 287.1386 for 262144x)
8 strings: StringXor new is 71.2% faster than StringXor old (135.1229 vs 468.574 for 262144x)
10 strings: StringXor new is 73.2% faster than StringXor old (153.0019 vs 570.01 for 262144x)
20 strings: StringXor new is 78% faster than StringXor old (111.073 vs 504.3386 for 131072x)
40 strings: StringXor new is 80.7% faster than StringXor old (184.13 vs 953.2954 for 131072x)
60 strings: StringXor new is 81.5% faster than StringXor old (130.0337 vs 703.0533 for 65536x)
80 strings: StringXor new is 82.3% faster …
```

faster StringXor

---

lib/optimize/SideEffectsFlagPlugin.js
test/WatchCacheUnaffectedTestCases.longtest.js

optimization.sideEffects is compatible with cacheUnaffected

---

lib/Compilation.js

bugfix cacheUnaffected

---

lib/Compilation.js
test/__snapshots__/StatsTestCases.basictest.js.snap

add timing to second affected module computation

---

lib/AsyncDependenciesBlock.js
lib/Compilation.js
lib/DependenciesBlock.js
lib/Dependency.js
lib/ModuleGraph.js
lib/buildChunkGraph.js
lib/logging/Logger.js
test/__snapshots__/StatsTestCases.basictest.js.snap
types.d.ts

performance, caching
existing tests
no
nothing

improve chunk graph creation performance

---

schemas/WebpackOptions.json
test/__snapshots__/Cli.test.js.snap

chore
CLI test snapshots are updated.
No
N/A

chore: update option descriptions

---

lib/dependencies/CommonJsFullRequireDependency.js
test/cases/parsing/issue-14610/index.js
test/cases/parsing/issue-14610/module.js

fix #14610

---

lib/cache/PackFileCacheStrategy.js

Fixes https://github.com/webpack/webpack/issues/14376
No
No
Nothing.

fix: improve logic to check if value is a `Promise`

---

yarn.lock

update babel dependencies

---

lib/util/hash/BatchedHash.js
lib/util/hash/wasm-hash.js
test/WasmHashes.unittest.js

fix BatchedHash correctly concatenating base64 strings
fix WashHash fallback for weird unicode chars
bugfix
yes
no
nothing

fix bugs with the new hashing implementation

---

lib/dependencies/CommonJsFullRequireDependency.js
test/cases/parsing/asi/index.js

fix #14662

---

lib/config/defaults.js
lib/config/normalization.js
lib/dependencies/HarmonyImportDependency.js
test/Defaults.unittest.js

make exportsPresence strict by default in future

---

lib/Compilation.js
test/watchCases/cache/changing-module-id/0/index.js
test/watchCases/cache/changing-module-id/0/unrelated.js
test/watchCases/cache/changing-module-id/1/other-layer.js
test/watchCases/cache/changing-module-id/webpack.config.js

that causes missing invalidation for modules when only the module id has changed
bugfix
yes
no
nothing

fix a bug with experiments.cacheUnaffected

---

.github/workflows/test.yml
appveyor.yml
azure-pipelines.yml
package.json

fixes #14668
min node.js version
yes
no
nothing

upgrade min node.js version

---

lib/config/defaults.js
test/Defaults.unittest.js

small fix
No, it affects only performance
no
nothing

fix regexp in managed paths

---

lib/serialization/FileMiddleware.js

use node14 buffer methods

---

lib/dependencies/CommonJsImportsParserPlugin.js
lib/dependencies/URLPlugin.js
test/configCases/parsing/issue-14720/index.js
test/configCases/parsing/issue-14720/module.js
test/configCases/parsing/issue-14720/webpack.config.js

fixes #14720
bugfix
TODO
no
nothing

attach require with property dependencies to the correct DependenciesBlock

---

lib/CleanPlugin.js
lib/util/fs.js
test/configCases/clean/link/index.js
test/configCases/clean/link/test.filter.js
test/configCases/clean/link/webpack.config.js
types.d.ts

bugfix, fixes https://github.com/webpack/webpack/issues/14700
Yes
No
No

fix: remove links in clean plugin

---

lib/FileSystemInfo.js
test/BuildDependencies.longtest.js
test/ConfigCacheTestCases.longtest.js
test/ConfigTestCases.template.js
test/configCases/cache-dependencies/managed-items-unsafe-cache/index.js
test/configCases/cache-dependencies/managed-items-unsafe-cache/loader.js
test/configCases/cache-dependencies/managed-items-unsafe-cache/node_modules/package/package.json
test/configCases/cache-dependencies/managed-items-unsafe-cache/webpack.config.js
test/configCases/cache-dependencies/managed-items/webpack.config.js
test/fixtures/buildDependencies/node_modules/dep#with#hash/package.json
test/fixtures/buildDependencies/node_modules/dep-with-exports/package.json
test/fixtures/buildDependencies/node_modules/dependency-with-exports/package.json
test/fixtures/buildDependencies/node_modules/dependency-with-optional/package.json
test/fixtures/buildDependencies/node_modules/require-dependency-with-exports/package.json
test/fixtures/buildDependencies/run.js
test/watchCases/cache/unsafe-cache-managed-paths/0/index.js
test/watchCases/cache/unsafe-cache-managed-paths/0/node_modules/package/index.js
test/watchCases/cache/unsafe-cache-managed-paths/0/node_modules/package/package.json
test/watchCases/cache/unsafe-cache-managed-paths/1/node_modules/package/index.js
test/watchCases/cache/unsafe-cache-managed-paths/1/node_modules/package/package.json
test/watchCases/cache/unsafe-cache-managed-paths/2/node_modules/package/index.js
test/watchCases/cache/unsafe-cache-managed-paths/2/node_modules/package/package.json
test/watchCases/cache/unsafe-cache-managed-paths/webpack.config.js

bugfix, fixes #14699
yes
no
nothing

fix unsafeCache with managedPaths

---

README.md

Remove travis-ci and appveyor badges as they are no longer used.
No
No
Nothing

docs: remove old badges from README

---

lib/FileSystemInfo.js
test/Watch.test.js
test/fixtures/watch/node_modules/inline-loader/index.js
test/fixtures/watch/node_modules/inline-loader/package.json
test/fixtures/watch/node_modules/nested-package1/package.json
test/fixtures/watch/node_modules/package/index.js
test/fixtures/watch/node_modules/package/node_modules/nested-package2/package.json
test/fixtures/watch/node_modules/package/package.json
test/fixtures/watch/node_modules/some-loader/index.js
test/fixtures/watch/node_modules/some-loader/package.json
test/fixtures/watch/src/index.js
test/fixtures/watch/src/local.js

fixes #14768
bugfix
yes
no
nothing

fix double compilation with managed paths

---

lib/javascript/JavascriptParser.js
test/cases/parsing/evaluate-nullish/index.js

fix evaluating tagged template

---

lib/javascript/JavascriptParser.js
test/cases/parsing/evaluate/index.js

feature
closes #12063 
yes
no
nothing

evaluate undefined to type "undefined"

---

lib/ExternalModule.js
lib/RuntimeTemplate.js
lib/javascript/ArrayPushCallbackChunkFormatPlugin.js
lib/library/AssignLibraryPlugin.js
lib/web/JsonpChunkLoadingRuntimeModule.js
lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js
test/configCases/issues/issue-12924/index.js
test/configCases/issues/issue-12924/one.js
test/configCases/issues/issue-12924/webpack.config.js
types.d.ts

use "safe" global object

---

lib/container/ContainerEntryModule.js

Reusing the `name` variable for sharing
refactoring

reuse name variable in share scope

---

lib/util/extractUrlAndGlobal.js
test/extractUrlAndGlobal.unittest.js

#13287
added pattern validation to the remotes object schema
not sure how to add test

feat: add validation to remotes

---

lib/stats/DefaultStatsPrinterPlugin.js

fixes #14678 
performance bugfix
no, tested with https://github.com/martinsp/webpack-printer-issue
no
nothing

fix regexp in DefaultStatsPrinterPlugin

---

lib/config/defaults.js
test/Defaults.unittest.js

feature
updated existing 
no
`experiments.futureDefaults` sets `options.hashDigestLength` to 16

set hashDigestLength=16 for futureDefaults

---

package.json
yarn.lock

bugfix
in watchpack
no
nothing

upgrade watchpack for bugfix

---

lib/asset/AssetGenerator.js

bugfix
No, it is just typo
No
No

fix: info merging for asset modules

---

lib/hmr/lazyCompilationBackend.js

fix #15120 
Small change, no test
No
No

fix: add CORS methods and headers for lazyCompilation

---

lib/web/JsonpChunkLoadingRuntimeModule.js
test/Stats.test.js
test/__snapshots__/StatsTestCases.basictest.js.snap

replace chunkIds[i] with chunkId in JsonpChunkLoadingRuntimeModule
no 
no 
nothing

replace chunkIds[i] with chunkId in JsonpChunkLoadingRuntimeModule

---

test/cases/large/big-assets/generate-big-asset-loader.js
test/cases/large/big-assets/index.js

improve test case to check correct data

---

lib/FileSystemInfo.js

fixes https://github.com/webpack/webpack/issues/14911
bugfix
no, I tried too long...
no
nothing

avoid reporting non-existant package.jsons as dependencies

---

examples/css/README.md
examples/css/index.html
lib/RuntimeGlobals.js
lib/css/CssGenerator.js
lib/css/CssLoadingRuntimeModule.js
lib/css/CssModulesPlugin.js
test/configCases/css/basic-initial-only/index.js
test/configCases/css/basic-initial-only/style-imported.css
test/configCases/css/basic-initial-only/style.css
test/configCases/css/basic-initial-only/test.config.js
test/configCases/css/basic-initial-only/webpack.config.js
types.d.ts

fix missing css runtime when only initial css is used

---

lib/stats/DefaultStatsFactoryPlugin.js
lib/stats/DefaultStatsPrinterPlugin.js
test/__snapshots__/StatsTestCases.basictest.js.snap
test/statsCases/all-stats/index.js
test/statsCases/all-stats/webpack.config.js
test/statsCases/asset/index.js
test/statsCases/asset/webpack.config.js

limit data url module name in stats printer

---

lib/dependencies/CreateScriptUrlDependency.js

bug fix https://github.com/webpack/webpack/issues/15153
No, we just do not `serialize`/`deserialize`
No
No

fix: cache for CreateScriptUrlDependency

---

lib/asset/AssetGenerator.js
test/configCases/asset-modules/data-url/index.js
test/configCases/asset-modules/data-url/loader.js
test/configCases/asset-modules/data-url/webpack.config.js
test/configCases/asset-modules/input-data-url-encoding/index.js

bugfix
Unfortunately, we cannot avoid encode data URI after loaders, loader can change content and encoding will be same, so we need to generate data URI from source again and we can't reuse `encodedContent`, bad - it generates more longer data URIs
Yes
No
No

fix: handle content from loaders

---

lib/ContextModule.js
test/ContextModule.unittest.js

Closes #15140
bugfix
yes
no
nothing

fix: context regex non-deterministic with |

---

lib/ContextModule.js
lib/NormalModule.js
lib/container/ContainerEntryModule.js
lib/container/FallbackModule.js
lib/container/RemoteModule.js
lib/sharing/ConsumeSharedModule.js
lib/sharing/ProvideSharedModule.js

change to naming modules with layers
no
no
nothing

Module.libIdent is scoped by the module layer if there is one

---

examples/css/README.md
lib/config/normalization.js
lib/css/CssLoadingRuntimeModule.js

bugfixes to css modules

---

lib/Compilation.js
lib/DependencyTemplates.js

provide hashFunction parameter to DependencyTemplates

---

lib/hmr/LazyCompilationPlugin.js
test/hotCases/lazy-compilation/simple/index.js
test/hotCases/lazy-compilation/unrelated/index.js
test/hotCases/lazy-compilation/unrelated/lazy.js
test/hotCases/lazy-compilation/unrelated/module.js
test/hotCases/lazy-compilation/unrelated/webpack.config.js

bugfix, fixes #15190
yes
no
nothing

fix HMR when experiments.lazyCompilation is enabled

---

lib/Compilation.js
types.d.ts

Add a missing overload signature for addChunkInGroup's typescript declaration.
N/A (unless the definitions are tested somewhere)
N/A
This is basically a documentation fix.

fix: revise call signature of addChunkInGroup

---

lib/RuntimeTemplate.js
lib/asset/AssetGenerator.js
lib/asset/RawDataUrlModule.js

makes deserialization cheaper
bugfix, fixes #15219
no
nothing
nothing

store url as Buffer to avoid serialization warnings

---

test/configCases/ignore/resource-and-context-contextmodule/test.js

Fixed typo.
`dont` -> `do not`
none
none
none

fix typo in  resource-and-context-contextmodule

---

lib/asset/AssetGenerator.js
lib/css/CssModulesPlugin.js
lib/javascript/JavascriptModulesPlugin.js
lib/util/nonNumericOnlyHash.js
test/nonNumericOnlyHash.unittest.js

fixes #15288 
partial
no
nothing

use nonNumericOnlyHash function for contentHash

---

lib/config/defaults.js
test/Defaults.unittest.js
test/configCases/output-module/check-defaults/errors.js
test/configCases/output-module/check-defaults/index.js
test/configCases/output-module/check-defaults/webpack.config.js

feature 
closes #15292 
yes 
no, update experimental feature
no

set output.environment.module=true when output.module enabled

---

lib/buildChunkGraph.js
test/configCases/chunk-graph/issue-15173/commonAsync/index.js
test/configCases/chunk-graph/issue-15173/commonSync/index.js
test/configCases/chunk-graph/issue-15173/entries/entryA.js
test/configCases/chunk-graph/issue-15173/entries/entryB.js
test/configCases/chunk-graph/issue-15173/featureA/index.js
test/configCases/chunk-graph/issue-15173/featureB/index.js
test/configCases/chunk-graph/issue-15173/featureC/index.js
test/configCases/chunk-graph/issue-15173/test.config.js
test/configCases/chunk-graph/issue-15173/webpack.config.js

fix #15173 
yes
No, just a bug fix.
Nothing.

fix: Merge avaiable modules correctly #15173

---

lib/dependencies/ContextElementDependency.js
test/ConfigCacheTestCases.longtest.js
test/ConfigTestCases.template.js

fixes #15177 
not yet
no
nothing

fix serialization in ContextElementDependency

---

lib/node/NodeTargetPlugin.js

fixes #15342
Adding util/types to nnode target - bug fix

fixes #15342 - add util/types to node target

---

lib/NormalModule.js
lib/NormalModuleFactory.js
types.d.ts

DX: add types
closes #15112 
no need
no
nothing

add NormalModuleFactory hooks types

---

lib/NodeStuffPlugin.js
test/configCases/web/node-source-global/index.js
test/configCases/web/node-source-global/test.config.js
test/configCases/web/node-source-global/webpack.config.js

disallow global renaming in NodeStuffPlugin

---

lib/esm/ModuleChunkLoadingRuntimeModule.js

use correct chunkgraph in runtime module

---

lib/dependencies/HarmonyExportInitFragment.js
test/configCases/issues/issue-11871-imports-order/a.js
test/configCases/issues/issue-11871-imports-order/index.js
test/configCases/issues/issue-11871-imports-order/webpack.config.js

fix imports order

---

module.d.ts

fix module types

---

lib/ProgressPlugin.js
test/ProgressPlugin.test.js

fix ProgressPlugin log

---

lib/dependencies/HarmonyAcceptImportDependency.js
test/configCases/issues/issue-14974/defer.js
test/configCases/issues/issue-14974/index.js
test/configCases/issues/issue-14974/test.filter.js
test/configCases/issues/issue-14974/tla.js
test/configCases/issues/issue-14974/webpack.config.js

fix HarmonyAcceptImportDependency

---

lib/CleanPlugin.js
test/HotModuleReplacementPlugin.test.js

keep hmr update with output.clean=true

---

lib/BannerPlugin.js
test/BannerPlugin.test.js

use cache in BannerPlugin

---

lib/Compilation.js
lib/ContextModule.js
lib/Module.js
test/__snapshots__/StatsTestCases.basictest.js.snap
test/configCases/source-map/context-module-source-path/foo/a.js
test/configCases/source-map/context-module-source-path/foo/b.js
test/configCases/source-map/context-module-source-path/index.js
test/configCases/source-map/context-module-source-path/webpack.config.js
types.d.ts

bug fix #15274 
yes
no
nothing

fix: use relative path in source map for context module

---

lib/esm/ModuleChunkLoadingPlugin.js

fix module chunk loading

---

lib/ConstPlugin.js
lib/dependencies/CommonJsExportsParserPlugin.js
lib/javascript/JavascriptParser.js
types.d.ts

bugfix/refactoring
`parser.evaluateExpression` always return `BasicEvaluatedExpression`
I think we don't need them
no
nothing

fix `parser.evaluteExpression` api

---

lib/library/UmdLibraryPlugin.js
test/ConfigTestCases.template.js
test/configCases/umd/issue-15545/index.js
test/configCases/umd/issue-15545/test.config.js
test/configCases/umd/issue-15545/webpack.config.js

support arrow function in umd

---

lib/ContextModule.js
test/cases/runtime/issue-15518/dynamic_a/module_a1.js
test/cases/runtime/issue-15518/index.js

fix allDeps list

---

lib/cache/PackFileCacheStrategy.js

developer experience
no
no
nothing

make cache warnings caused by build errors less verbose

---

lib/optimize/ModuleConcatenationPlugin.js

throw error when using module concatenation and cacheUnaffected

---

package.json
test/configCases/resolve/fallback/#/a.js
test/configCases/resolve/fallback/index.js
test/configCases/resolve/fallback/webpack.config.js
yarn.lock

upgrade enhanced-resolve version
yes
no
nothing

up enhanced-resolve

---

test/cases/large/big-assets/infrastructure-log.js

refactoring.
removing unused `infrastructure-log.js` (writing cache size > 2gb was fixed)
no need
no
nothing

remove infrastructure-log for big-assets test case

---

lib/Compiler.js
lib/DllReferencePlugin.js
lib/NormalModule.js
lib/json/JsonParser.js
package.json
test/__snapshots__/StatsTestCases.basictest.js.snap
yarn.lock

Close #15672
Dependency replacing
No
No
Nothing

chore(deps): replace `json-parse-better-errors` to `json-parse-even-better-errors`

---

test/configCases/assets/delete-asset/infrastructure-log.js
test/configCases/process-assets/html-plugin/infrastructure-log.js

refactoring
add comments regarding infrastructure logs in tests
yes
no
nothing

add comments regarding infrastructure logs in tests

---

lib/dependencies/HarmonyEvaluatedImportSpecifierDependency.js
test/cases/parsing/harmony-export-import-specifier/index.js

Fix `return"field"in Module` evaluated as `returntrue` #15759

---

lib/index.js
types.d.ts

Fixes #14858 : added `@typedef` for `PathData`
No, no tests are needed.
No.
Nothing.

Added @typedef for PathData

---

lib/Compilation.js

more informative error when emitting multiple assets

---

lib/sharing/ProvideSharedPlugin.js

refactor error message. related to https://github.com/webpack/webpack/issues/15864
no
no
nothing

more informative error in ProvideSharedPlugin

---

lib/runtime/AsyncModuleRuntimeModule.js
test/__snapshots__/StatsTestCases.basictest.js.snap
test/cases/async-modules/runtime-performance/async.js
test/cases/async-modules/runtime-performance/index.js
test/cases/async-modules/runtime-performance/loader.js

improve runtime code for async modules
bugfix
yes
no
nothing

fix quadratic evaluation performance of async modules

---

lib/optimize/ConcatenatedModule.js
test/configCases/concatenate-modules/side-effects/index.js
test/configCases/concatenate-modules/side-effects/node_modules/dep/a.js
test/configCases/concatenate-modules/side-effects/node_modules/dep/b.js
test/configCases/concatenate-modules/side-effects/node_modules/dep/c.js
test/configCases/concatenate-modules/side-effects/node_modules/dep/index.js
test/configCases/concatenate-modules/side-effects/node_modules/dep/order.js
test/configCases/concatenate-modules/side-effects/node_modules/dep/package.json
test/configCases/concatenate-modules/side-effects/webpack.config.js

add test case, fixes #15866 
yes
no
nothing

add concatenate modules side effects test case, fix imports order

---

lib/runtime/AsyncModuleRuntimeModule.js
test/__snapshots__/StatsTestCases.basictest.js.snap

remove unnecessary moduleId property on Promise

---

package.json
types.d.ts
yarn.lock

update deps
there are tests in enhanced-resolve
no
add `resolve.extensionAlias` which allows to alias extensions to new extensions (multiple alternatives).
Example
```
externsionAlias: {
".js": [".ts", ".js"],
".mjs": [".mts", ".mjs"]
}
```
It's an "alias" so not including the original extension will only alias the request to the new extension, which means the original extension is no longer used.

enhanced-resolve@5.10.0

---

package.json
yarn.lock

see: https://github.com/webpack/watchpack/pull/215
No
No

fix: hmr build twice

---

.github/workflows/test.yml

Update `checkout`, `setup-node`,`codecov`, and `cache` actions
No
No
Nothing

ci: update github actions

---

package.json

Added bugs field in package.json file
Not needed
NO
N/A

chore: add bugs field in package.json

---

lib/css/CssLoadingRuntimeModule.js
lib/runtime/LoadScriptRuntimeModule.js
lib/web/JsonpChunkLoadingRuntimeModule.js

feature
related to https://github.com/webpack/webpack/discussions/15629
no
no
nothing

set crossOrigin=use-credentials without origin check

---

README.md

Add previous-version: 5.72.1
Add new version: 5.73.0
I fixed the broken compatibility score badge.
I read the dependabot documentation.
In order to fix the existing broken badge, I applied dependabot's new method.
`https://api.dependabot.com/badges/compatibility_score?dependency-name=${name}&package-manager={package-manger}&previous-version=${previous}.1&new-version=${newversion}`
- name: webpack
- package-manger: npm_and_yarn
- pervious: 5.72.1 (latest old version)
- newversion: 5.73.0 (latest version)
Nope
Nope

Fix badge : compatibility score

---

declarations/WebpackOptions.d.ts
lib/config/defaults.js
lib/config/normalization.js
schemas/WebpackOptions.json
test/Defaults.unittest.js
types.d.ts

Fixes #15742.
bugfix
Yes.
No.
Nothing.

fix: allow normalised experiments css value to be false

---

lib/EvalSourceMapDevToolPlugin.js

Just add a jsdoc type comment.
No.
No.

chore: add jsdoc type comment for EvalSourceMapDevToolPlugin

---

lib/buildChunkGraph.js
test/__snapshots__/StatsTestCases.basictest.js.snap
test/statsCases/dynamic-chunk-name-error/entry-1.js
test/statsCases/dynamic-chunk-name-error/entry-3.js
test/statsCases/dynamic-chunk-name-error/webpack.config.js

Correct error with wrong chunkname

---

lib/EvalSourceMapDevToolPlugin.js
test/configCases/devtools/eval-nosources-source-map/index.js
test/configCases/devtools/eval-nosources-source-map/test.js
test/configCases/devtools/eval-nosources-source-map/webpack.config.js

fix: `devtool: 'eval-nosources-*'` still contains sourcesContent

---

.eslintrc.js

fix word spelling

---

lib/runtime/LoadScriptRuntimeModule.js
test/__snapshots__/StatsTestCases.basictest.js.snap

pretty
updated snapshots
no
nothing

fix semicolon position

---

package.json

chore(release): 5.76.0

---

lib/node/NodeTargetPlugin.js

Added `assert/strict` built-in

---

package.json

Chore and release
No need
No
No

chore(release): 5.76.1

---

.github/workflows/test.yml

this updates actions/cache github action to latest available version v3
N/A
No
Nothing

ci: update actions/cache to v3

---

lib/sharing/ConsumeSharedPlugin.js
test/configCases/sharing/consume-self-reference/index.js
test/configCases/sharing/consume-self-reference/node_modules/my-middleware/index.js
test/configCases/sharing/consume-self-reference/node_modules/my-middleware/package.json
test/configCases/sharing/consume-self-reference/node_modules/my-module/a.js
test/configCases/sharing/consume-self-reference/node_modules/my-module/b.js
test/configCases/sharing/consume-self-reference/node_modules/my-module/package.json
test/configCases/sharing/consume-self-reference/package.json
test/configCases/sharing/consume-self-reference/webpack.config.js

fix: handle package self-referencing in shared module

---

lib/sharing/ConsumeSharedRuntimeModule.js

It is bugfix.
If your shared module do not import all modules in main index.js file(use for tree shaking), fallback module infitity looping browser runtime.
I add check if module start inited, it fixed infinity looping.
fixes #16626
No
No
No needs to change the documentation

Fix consumes function

---

package.json
types.d.ts
yarn.lock

fixes #17446
No need
No
Update docs

fix: `Server` and `Dirent` types

---

.eslintignore
yarn.lock

Some of the examples is using outputModule, and `examples/**/dist/*.mjs` causes eslint failed when running `yarn fix`, this PR ignore those `*.mjs`
no need
no
none

chore: yarn fix failed in examples *.mjs

---

.github/workflows/test.yml

Use node.js LTS version for lint
Not needed
No
Nothing

ci: use node.js LTS version for lint

---

lib/config/defaults.js
test/Defaults.unittest.js
test/configCases/css/prefer-relative-css-import/bar.modules.css
test/configCases/css/prefer-relative-css-import/foo.css
test/configCases/css/prefer-relative-css-import/index.js
test/configCases/css/prefer-relative-css-import/node_modules/bar.modules.css/package.json
test/configCases/css/prefer-relative-css-import/node_modules/bar.modules.css/style.css
test/configCases/css/prefer-relative-css-import/node_modules/foo.css/package.json
test/configCases/css/prefer-relative-css-import/node_modules/foo.css/style.css
test/configCases/css/prefer-relative-css-import/style.less
test/configCases/css/prefer-relative-css-import/style.modules.less
test/configCases/css/prefer-relative-css-import/test.config.js
test/configCases/css/prefer-relative-css-import/webpack.config.js

fix #17569
added
Strictly this is a breaking change, but since experiments css is still experimental, this should be ok
none

fix: css-import should apply preferRelative

---

lib/dependencies/CommonJsImportsParserPlugin.js
lib/dependencies/WorkerPlugin.js
test/configCases/worker/issue-17489/index.js
test/configCases/worker/issue-17489/module.js
test/configCases/worker/issue-17489/test.config.js
test/configCases/worker/issue-17489/test.filter.js
test/configCases/worker/issue-17489/webpack.config.js
test/configCases/worker/issue-17489/worklet.js

fixes https://github.com/webpack/webpack/issues/17489
WIP
No
Nothing

fix: worklet detection in production mode

---

lib/optimize/InnerGraphPlugin.js
test/configCases/inner-graph/issue-17565/module.js
test/configCases/inner-graph/issue-17565/test.filter.js
test/configCases/inner-graph/issue-17565/webpack.config.js

bugfix
fixes https://github.com/webpack/webpack/issues/17565
fixes https://github.com/webpack/webpack/pull/17574
WIP
NO
No

fix: inner graph for classes

---

lib/APIPlugin.js
lib/Compilation.js
lib/ConditionalInitFragment.js
lib/DefinePlugin.js
lib/EvalSourceMapDevToolPlugin.js
lib/InitFragment.js
lib/NodeStuffPlugin.js
lib/Stats.js
lib/async-modules/AwaitDependenciesInitFragment.js
lib/dependencies/AMDDefineDependency.js
lib/dependencies/AMDDefineDependencyParserPlugin.js
lib/dependencies/AMDPlugin.js
lib/dependencies/AMDRequireArrayDependency.js
lib/dependencies/AMDRequireDependenciesBlockParserPlugin.js
lib/dependencies/AMDRequireDependency.js
lib/dependencies/AMDRequireItemDependency.js
lib/dependencies/ExternalModuleDependency.js
lib/dependencies/ExternalModuleInitFragment.js
lib/dependencies/HarmonyExportInitFragment.js
lib/dependencies/LocalModuleDependency.js
lib/dependencies/WorkerPlugin.js
lib/dependencies/getFunctionExpression.js
lib/javascript/JavascriptParser.js
lib/optimize/MangleExportsPlugin.js
lib/util/chainedImports.js
types.d.ts

More types for strict mode
No need
I want to say it is a bug fix
No

refactor(types): more

---

lib/util/comparators.js
test/compareStringsNumeric.unittest.js

Performance optimization impacting `MangleExportsPlugin` and the assignment of deterministic ids.
Reference implementation on a test build was spending ~730ms, most of which was in the evaluation of the RegExp `/(\d+)/`.
Post change takes ~43ms for the same build.
Yes.
No. Unit tests were added to ensure the behavior did not change.
No change.

Optimize compareStringsNumeric

---

examples/wasm-bindgen-esm/README.md
examples/wasm-complex/README.md
examples/wasm-simple/README.md
lib/wasm-async/AsyncWasmLoadingRuntimeModule.js
test/__snapshots__/StatsTestCases.basictest.js.snap

bugfix & enhancement
- Closes: #12259
I have updated the existing test cases.
No

fix: add fallback for MIME mismatch error in async wasm loading

---

lib/util/numberHash.js
test/Compiler.test.js
test/Errors.test.js
test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
test/__snapshots__/ConfigTestCases.basictest.js.snap
test/__snapshots__/StatsTestCases.basictest.js.snap
test/configCases/asset-emitted/normal/webpack.config.js
test/configCases/code-generation/re-export-namespace-concat/index.js
test/configCases/code-generation/re-export-namespace/index.js
test/configCases/css/css-modules-broken-keyframes/index.js
test/configCases/css/css-modules-in-node/index.js
test/configCases/css/css-modules/index.js
test/configCases/css/css-modules/test.config.js
test/configCases/css/large/index.js
test/configCases/custom-source-type/localization/index.js
test/configCases/mangle/mangle-with-object-prop/index.js

Performance improvement for `assignDeterministicIds` by using a faster non-cryptographic hash. Most use cases of this function apply to a range < 1024, so using the pseudo-128 bit hash that was previously in use is significant overkill. Still uses the FNV1a hash algorithm, but uses a closer approximation to the reference (differs only by masking at the end and handling large Unicode code points as UTF-16LE).
When the requested range fits within a 24-bit integer, uses 32-bit FNV-1a. Otherwise uses 64-bit FNV-1a.
The reason for this switch at 24-bit instead of 31-bit is to ensure that the bias towards the lower end of the range introduced by the final module operation is kept below 0.5%.
In local testing this improved performance of …

Optimize numberHash using 32-bit FNV1a for small ranges, 64-bit for larger

---

lib/config/browserslistTargetHandler.js

https://github.com/webpack/webpack/discussions/18022#discussioncomment-8310392
This is manual check, because we can't autotest it in real browsers, but verified manuallu and using caniuse
No
No

fix: async function support in browserslist

---

lib/runtime/AutoPublicPathRuntimeModule.js
test/Stats.test.js
test/__snapshots__/StatsTestCases.basictest.js.snap

bugfix
fixes https://github.com/webpack/webpack/pull/17860/
Technically we could use: `!/^h/.test(scriptUrl)`, but in some envs it is possible to register own URL schemas, I think that in reality this will never meet in life, but better to avoid such situations
No, manual test
No
No

fix: improve auto publicPath detection

---

lib/Compilation.js
lib/Stats.js
types.d.ts

fix: types for `Stats.toJson()` and `Stats.toString()`

---

lib/buildChunkGraph.js

performance bugfix
Leverages `BigInt` bitwise arithmetic to accelerate the set theory operations in `buildChunkGraph`, specifically for computing unions and intersections.
Before:
processChunKGroupsForMerging: 698ms
After:
processChunkGroupsFormmerging: too small to display
Unfortunately testing single bits at a time in `BigInt` is not a well-optimized scenario at present, so there is some potential optimization room there.
This is core functionality that is covered by most test cases.
No.
No documentation changes.

(perf) Simplify and optimize chunk graph creation

---

declarations/LoaderContext.d.ts
lib/ContextModule.js
lib/CssModule.js
lib/DelegatedModule.js
lib/DllModule.js
lib/ExternalModule.js
lib/Module.js
lib/MultiCompiler.js
lib/NormalModule.js
lib/NormalModuleFactory.js
lib/RawModule.js
lib/ResolverFactory.js
lib/RuntimeModule.js
lib/asset/RawDataUrlModule.js
lib/container/ContainerEntryModule.js
lib/container/FallbackModule.js
lib/container/RemoteModule.js
lib/dependencies/WorkerDependency.js
lib/dependencies/WorkerPlugin.js
lib/hmr/LazyCompilationPlugin.js
lib/optimize/ConcatenatedModule.js
lib/sharing/ConsumeSharedModule.js
lib/sharing/ProvideSharedModule.js
lib/util/memoize.js
lib/wasm-sync/WebAssemblyJavascriptGenerator.js
lib/webpack.js
types.d.ts

types
No need
No, better types
No

Refactor types for strict mode

---

lib/RuntimePlugin.js
lib/css/CssLoadingRuntimeModule.js
test/configCases/web/nonce/chunk.css
test/configCases/web/nonce/chunk.js
test/configCases/web/nonce/index.js
test/configCases/web/nonce/nonce.js
test/configCases/web/nonce/webpack.config.js

bugfix, port of https://github.com/webpack-contrib/mini-css-extract-plugin/pull/1083
Yes
No
Nothing

fix: support `__webpack_nonce__` for CSS chunks

---

lib/css/CssLoadingRuntimeModule.js
test/configCases/web/fetch-priority/index.js
test/configCases/web/fetch-priority/style-1.css
test/configCases/web/fetch-priority/style-2.css
test/configCases/web/fetch-priority/style.css
test/configCases/web/fetch-priority/webpack.config.js

fix: support `fetchPriority` for CSS chunks

---

lib/Dependency.js
lib/dependencies/CssUrlDependency.js
lib/dependencies/ModuleDependency.js
lib/dependencies/URLDependency.js
test/PersistentCaching.test.js

bugfix fixes https://github.com/webpack/webpack/discussions/18127
WIP
No
Nothing

fix: deserializer for ignored modules

---

lib/ResolverFactory.js
lib/util/cleverMerge.js
test/configCases/resolve/unsafe-cache-proxy/a/1.js
test/configCases/resolve/unsafe-cache-proxy/b/2.js
test/configCases/resolve/unsafe-cache-proxy/index.js
test/configCases/resolve/unsafe-cache-proxy/webpack.config.js

bugfix
fixes https://github.com/webpack/webpack/issues/18129
Yes
No
No

fix: allow `unsafeCache` to be a proxied object

---

lib/config/defaults.js
lib/config/normalization.js
test/Defaults.unittest.js

bugfix, fixes https://github.com/webpack/webpack/issues/18167
No
No
No

fix: normalize `snapshot.unmanagedPaths`

---

cspell.json
lib/APIPlugin.js
lib/LibManifestPlugin.js
lib/RuntimeTemplate.js
lib/javascript/JavascriptParserHelpers.js
lib/logging/Logger.js
lib/logging/createConsoleLogger.js
lib/node/NodeEnvironmentPlugin.js
lib/node/NodeWatchFileSystem.js
lib/node/nodeConsole.js
lib/rules/ObjectMatcherRulePlugin.js
lib/util/fs.js
package.json
test/configCases/types/filesystems/webpack.config.js
types.d.ts
yarn.lock

bugfix
fixes https://github.com/webpack/webpack/issues/12599
No
No, just fixes, all methods are optional
No

fix: `fs` types

---

lib/CleanPlugin.js
lib/Compilation.js
lib/Compiler.js
lib/ContextReplacementPlugin.js
lib/DllReferencePlugin.js
lib/NodeStuffPlugin.js
lib/NormalModuleReplacementPlugin.js
lib/SourceMapDevToolPlugin.js
lib/WebpackOptionsApply.js
types.d.ts

bugfix, all types for file system, no problems with types and fs anymore
The last thing is update @types/node to the latest version, will be done in another PR
No need
No

fix: all filesystem types

---

lib/ChunkGraph.js
lib/Compilation.js
lib/ModuleGraph.js
lib/TemplatedPathPlugin.js
lib/Watching.js
lib/WebpackError.js
lib/debug/ProfilingPlugin.js
lib/dependencies/HarmonyExportDependencyParserPlugin.js
lib/javascript/BasicEvaluatedExpression.js
lib/javascript/JavascriptParser.js
lib/optimize/ConcatenatedModule.js
lib/util/comparators.js
package.json
types.d.ts
yarn.lock

fixes https://github.com/webpack/webpack/pull/17557/
No need, just types
No
No

fix(types): watching and more

---

lib/css/CssLoadingRuntimeModule.js
lib/web/JsonpChunkLoadingRuntimeModule.js
test/configCases/web/prefetch-preload-module/chunk1-a.css
test/configCases/web/prefetch-preload-module/chunk1.css
test/configCases/web/prefetch-preload-module/chunk1.js
test/configCases/web/prefetch-preload-module/chunk2.css
test/configCases/web/prefetch-preload-module/index.mjs
test/configCases/web/prefetch-preload-module/webpack.config.js
test/configCases/web/prefetch-preload/chunk1-a.css
test/configCases/web/prefetch-preload/chunk1.css
test/configCases/web/prefetch-preload/chunk1.js
test/configCases/web/prefetch-preload/chunk2.css
test/configCases/web/prefetch-preload/index.js
test/configCases/web/prefetch-preload/webpack.config.js
test/helpers/FakeDocument.js

feat: support prefetch/preload for CSS

---

lib/Compilation.js
lib/Dependency.js
lib/EvalDevToolModulePlugin.js
lib/ExportsInfo.js
lib/ExternalModule.js
lib/FlagDependencyExportsPlugin.js
lib/HotModuleReplacementPlugin.js
lib/ModuleFilenameHelpers.js
lib/TemplatedPathPlugin.js
lib/library/UmdLibraryPlugin.js
lib/util/createHash.js
types.d.ts

bugfix, fix some types
No need
No
No

fix(types): fix some types

---

lib/index.js
types.d.ts

bugfix, export InputFileSystem and OutputFileSystem, so toolings like webpack-dev-middleware can provide an option to replace built-in filesystem
No
No
No

fix(types): export InputFileSystem and OutputFileSystem

---

lib/css/CssModulesPlugin.js
test/ConfigTestCases.template.js
test/configCases/css/basic-esm-target-node/index.js
test/configCases/css/basic-esm-target-node/style-imported.css
test/configCases/css/basic-esm-target-node/style.css
test/configCases/css/basic-esm-target-node/style2-imported.css
test/configCases/css/basic-esm-target-node/style2.css
test/configCases/css/basic-esm-target-node/webpack.config.js
test/configCases/css/basic-esm-target-web/index.js
test/configCases/css/basic-esm-target-web/style-imported.css
test/configCases/css/basic-esm-target-web/style.css
test/configCases/css/basic-esm-target-web/style2-imported.css
test/configCases/css/basic-esm-target-web/style2.css
test/configCases/css/basic-esm-target-web/test.config.js
test/configCases/css/basic-esm-target-web/webpack.config.js
test/configCases/css/prefetch-preload-module/chunk1-a.css
test/configCases/css/prefetch-preload-module/chunk1.css
test/configCases/css/prefetch-preload-module/chunk1.mjs
test/configCases/css/prefetch-preload-module/chunk2.css
test/configCases/css/prefetch-preload-module/chunk2.mjs
test/configCases/css/prefetch-preload-module/index.mjs
test/configCases/css/prefetch-preload-module/webpack.config.js
test/helpers/FakeDocument.js

bugfix, CSS works fine for module chunk format for web and node target (and other too)
WIP
No
No

fix: output CSS runtime when chunk format is module

---

lib/javascript/CommonJsChunkFormatPlugin.js

refactoring: A small optimization point, should be copied wrong? I accidentally found it by reading the code for another issure...
no
no

perf: change to the correct plugin name

---

cspell.json
lib/ChunkGraph.js
lib/ContextModule.js
lib/FileSystemInfo.js
types.d.ts

fix(types): context module types

---

lib/util/ArrayQueue.js

fixes #18294
No, we have a lot of test on `dequeue`, and there we just reuse this method, in our code we don't use iterator, but we can use in future
No
No

fix: ArrayQueue iterator

---

lib/ContextModule.js
test/cases/mjs/namespace-object-lazy/cjs-dynamic.js
test/cases/mjs/namespace-object-lazy/index.mjs
test/cases/mjs/non-mjs-namespace-object-lazy/cjs-dynamic.js
test/cases/mjs/non-mjs-namespace-object-lazy/index.js

fix: failed to resolve promise when eager import a dynamic cjs

---

.github/workflows/test.yml
test/configCases/externals/import-attributes/test.filter.js

ci: Node.js 22

---

lib/css/CssModulesPlugin.js
test/configCases/css/contenthash/async.css
test/configCases/css/contenthash/async.js
test/configCases/css/contenthash/index.js
test/configCases/css/contenthash/style.css
test/configCases/css/contenthash/test.config.js
test/configCases/css/contenthash/webpack.config.js

This is a bugfix for #18511 (fixes #18511). 
Guidance to where tests should be added needed. 
No.
No documentation needed.

fix: error with contenthash and css experiment

---

package.json
test/ConfigTestCases.template.js
test/SemVer.unittest.js
test/Validation.test.js
test/configCases/ecmaVersion/browserslist-missing/test.filter.js
test/configCases/output-module/check-defaults/test.filter.js
yarn.lock

fixes #18502
Also want to fix unstable CI (WIP)
No need
No
No

chore: deps update

---

lib/DefinePlugin.js

Fixes #18519 
Technically a bugfix but more like removing an annoying log.
~~This does not change any functionality and there is no test to check for verbosity of logs.~~ I was wrong. I am fixing related tests right now.
No.
Default logging behavior of DefinePlugin - but that is already not documented, so no new behavior from the perspective of documentation. It would definitely be nice to add that to the docs.

fix: Fixes #18519 - makes DefinePlugin quieter under default log level

---

lib/dependencies/HarmonyImportSpecifierDependency.js
test/configCases/mangle/mangle-with-destructuring-assignment/index.js
test/configCases/mangle/mangle-with-destructuring-assignment/module.js

fix: mangle destructuring default in namespace import

---

lib/css/CssExportsGenerator.js
lib/css/CssGenerator.js
lib/dependencies/CssExportDependency.js
lib/dependencies/CssLocalIdentifierDependency.js
lib/util/conventions.js
test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
test/__snapshots__/ConfigTestCases.basictest.js.snap
test/configCases/contenthash/css-generator-options/index.js
test/configCases/contenthash/css-generator-options/style.module.css
test/configCases/contenthash/css-generator-options/test.config.js
test/configCases/contenthash/css-generator-options/webpack.config.js
test/configCases/css/exports-convention-prod/index.js
test/configCases/css/exports-convention-prod/style.module.css
test/configCases/css/exports-convention-prod/test.config.js
test/configCases/css/exports-convention-prod/webpack.config.js

bugfix
- should generate different contenthash for different css generator options
- fix `getExports` for exportsConvention
Added
No
None

fix: contenthash for css generator options

---

.github/workflows/test.yml

ci: fix codecov

---

README.md
azure-pipelines.yml
test/configCases/cache-filesystem/multicompiler-mode-cache-3/webpack.config.js
test/configCases/cache-filesystem/multicompiler-mode-cache-4/webpack.config.js

ci: azure fix names

---

azure-pipelines.yml

ci, fix warning - https://dev.azure.com/webpack/webpack/_build/results?buildId=19467&view=results
No need
No
No

ci: fix azure warning

---

.github/workflows/dependency-review.yml
.github/workflows/test.yml
README.md
package.json
yarn.lock

fixes https://github.com/webpack/webpack/issues/18163, let's use github action to check licenses
No need
No
No need

ci: dependency review

---

test/watchCases/cache/max-generation/0/changing-file.js
test/watchCases/cache/max-generation/0/index.js
test/watchCases/cache/max-generation/1/changing-file.js
test/watchCases/cache/max-generation/2/changing-file.js
test/watchCases/cache/max-generation/webpack.config.js

test coverage stability
It is tests
No
No

test: coverage stability

---

lib/SourceMapDevToolPlugin.js
test/configCases/asset-modules/keep-source-maps/data/asset.css.map
test/configCases/asset-modules/keep-source-maps/index.js

bugfix, fixes https://github.com/webpack-contrib/sass-loader/issues/1222
Yes
No
No

fix: handle properly `data`/`http`/`https` protocols in source maps

---

test/StatsTestCases.basictest.js
test/__snapshots__/StatsTestCases.basictest.js.snap

avoid hash using for https://github.com/webpack/webpack/pull/18662
no need
No
No

test: avoid real hash using

---

package.json
yarn.lock

fixes https://github.com/webpack/webpack/issues/18666
No 
We don't it types from `@types/eslint-scope` in our generated types, so we can move it
No need

fix: move `@types/eslint-scope` to dev deps

---

lib/dependencies/HarmonyExportDependencyParserPlugin.js
lib/javascript/JavascriptParser.js
test/cases/parsing/harmony-export-import-specifier-asi/a.js
test/cases/parsing/harmony-export-import-specifier-asi/index.js
types.d.ts

bugfix
fixes https://github.com/webpack/webpack/pull/18665/
fixes https://github.com/webpack/webpack/issues/18663
Yes
No
No

fix: handle ASI for export named declarations

---

test/__snapshots__/StatsTestCases.basictest.js.snap
test/statsCases/name/webpack.config.js

test: name in multi compiler mode

---

lib/dependencies/HarmonyExportDependencyParserPlugin.js
test/cases/parsing/harmony-export-specifier-asi/a.js
test/cases/parsing/harmony-export-specifier-asi/index.js

bugfix
https://github.com/webpack/webpack/pull/18675#issuecomment-2291261117
Yes
No
No

fix: handle ASI for export declaration

---

lib/runtime/AutoPublicPathRuntimeModule.js
test/Stats.test.js
test/helpers/CurrentScript.js

bugfix and security
Added a comment + existing tests
No
No
/cc @hardfist @fi3ework @ahabhgk @JSerFeng rspack affected too https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_runtime/src/runtime_module/auto_public_path.rs#L91, if you need to demonstrate the problem, write to me personally (slack/telegram)

security: fix DOM clobbering in auto public path

---

lib/util/LazySet.js
lib/util/runtime.js
package.json
types.d.ts
yarn.lock

fixes https://github.com/webpack/webpack/pull/18751/
fixes https://github.com/webpack/webpack/issues/18748
No
No
No

fix: types for ts5.6

---

test/configCases/css/css-types/index.js
test/configCases/css/css-types/style.css
test/configCases/css/css-types/style1.local.css
test/configCases/css/css-types/style2.global.css
test/configCases/css/css-types/test.config.js
test/configCases/css/css-types/webpack.config.js

add css types test cases
yes
no
no

test: css types

---

lib/WebpackOptionsApply.js
lib/optimize/MergeDuplicateChunksPlugin.js
test/__snapshots__/StatsTestCases.basictest.js.snap
test/statsCases/split-chunks-dedup/index.js
test/statsCases/split-chunks-dedup/module.js
test/statsCases/split-chunks-dedup/node_modules/cell/index.js
test/statsCases/split-chunks-dedup/node_modules/cell/package.json
test/statsCases/split-chunks-dedup/node_modules/row/index.js
test/statsCases/split-chunks-dedup/node_modules/row/package.json
test/statsCases/split-chunks-dedup/node_modules/table/index.js
test/statsCases/split-chunks-dedup/node_modules/table/package.json
test/statsCases/split-chunks-dedup/node_modules/templater/index.js
test/statsCases/split-chunks-dedup/node_modules/templater/package.json
test/statsCases/split-chunks-dedup/package.json
test/statsCases/split-chunks-dedup/webpack.config.js

Fix: https://github.com/webpack/webpack/issues/18749
Bugfix
Yes
No
I think nothing

fix: add extra merge duplicates call after split chunks

---

lib/dependencies/CommonJsImportsParserPlugin.js
lib/javascript/JavascriptParser.js
package.json
test/cases/parsing/es2022/counter.js
test/cases/parsing/es2022/es2022.js
test/cases/parsing/es2022/in.js
test/cases/parsing/es2022/index.js
test/cases/parsing/es2022/name.js
test/cases/parsing/es2022/reexport.js
types.d.ts
yarn.lock

fix: correctly parsing `string` export and import

---

.github/workflows/test.yml

ci: fix nyc

---

lib/ProgressPlugin.js
lib/dependencies/LoaderPlugin.js
lib/util/AsyncQueue.js
test/watchCases/cache/loader-import-module-progress/0/a.generate-json.js
test/watchCases/cache/loader-import-module-progress/0/b.generate-json.js
test/watchCases/cache/loader-import-module-progress/0/imported.js
test/watchCases/cache/loader-import-module-progress/0/index.js
test/watchCases/cache/loader-import-module-progress/0/loader.js
test/watchCases/cache/loader-import-module-progress/0/unrelated.js
test/watchCases/cache/loader-import-module-progress/1/unrelated.js
test/watchCases/cache/loader-import-module-progress/webpack.config.js
test/watchCases/cache/loader-load-module-progress/0/imported.js
test/watchCases/cache/loader-load-module-progress/0/index.js
test/watchCases/cache/loader-load-module-progress/0/loader.js
test/watchCases/cache/loader-load-module-progress/0/mod.js
test/watchCases/cache/loader-load-module-progress/0/unrelated.js
test/watchCases/cache/loader-load-module-progress/1/unrelated.js
test/watchCases/cache/loader-load-module-progress/webpack.config.js
types.d.ts

fixes https://github.com/webpack/webpack/issues/14946
WIP
No
No

fix: avoid cache invalidation using `ProgressPlugin` and `importModule`

---

lib/Watching.js
lib/buildChunkGraph.js
lib/optimize/AggressiveSplittingPlugin.js
lib/optimize/ModuleConcatenationPlugin.js
lib/stats/DefaultStatsFactoryPlugin.js
lib/util/cleverMerge.js
lib/util/mergeScope.js

fix: types

---

lib/css/CssModulesPlugin.js
test/configCases/css/basic-dynamic-only/index.js
test/configCases/css/basic-dynamic-only/style-imported.css
test/configCases/css/basic-dynamic-only/style.css
test/configCases/css/basic-dynamic-only/webpack.config.js
test/configCases/css/basic-initial-only/index.js

fix: avoid extra runtime code for CSS

---

lib/RuntimePlugin.js
lib/runtime/GetChunkFilenameRuntimeModule.js
test/__snapshots__/StatsTestCases.basictest.js.snap
test/configCases/css/prefetch-preload-module-only-css/webpack.config.js
test/statsCases/split-chunks-dedup/webpack.config.js
types.d.ts

Fix avoid runtime

---

lib/config/defaults.js
lib/css/CssModulesPlugin.js
lib/css/CssParser.js
test/configCases/css/css-types/index.js
test/configCases/css/css-types/style3.auto.css
test/configCases/css/css-types/style4.modules.css
test/configCases/css/css-types/webpack.config.js

bugfix/feature 
Yes
Yes, but it is under `experiments`
Yes

Fix default

---

lib/css/walkCssTokens.js
test/__snapshots__/walkCssTokens.unittest.js.snap
test/configCases/css/parsing/cases/nesting.css
test/configCases/css/parsing/style.css

fix: parsing bad urls

---

lib/css/CssParser.js
lib/css/walkCssTokens.js
test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
test/__snapshots__/ConfigTestCases.basictest.js.snap
test/configCases/css/css-modules-no-space/index.js
test/configCases/css/css-modules-no-space/style.module.css
test/configCases/css/css-modules-no-space/use-style.js
test/configCases/css/css-modules-no-space/warnings.js
test/configCases/css/css-modules-no-space/webpack.config.js

fix: emit a warning on broken `:local` and `:global`

---

lib/css/CssModulesPlugin.js
lib/node/ReadFileCompileAsyncWasmPlugin.js
lib/node/ReadFileCompileWasmPlugin.js
lib/web/FetchCompileAsyncWasmPlugin.js
lib/web/FetchCompileWasmPlugin.js
test/configCases/css/async-chunk-node/index.js
test/configCases/css/async-chunk-node/style.css
test/configCases/css/async-chunk-node/webpack.config.js

fix(css): no extra runtime for node target

---

lib/css/CssParser.js
lib/dependencies/CssUrlDependency.js
test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
test/__snapshots__/ConfigTestCases.basictest.js.snap
test/configCases/css/urls/spacing.css

feat(css): `src()` support

---

lib/Compilation.js
lib/IgnorePlugin.js
lib/NormalModuleFactory.js
lib/javascript/JavascriptModulesPlugin.js
test/ConfigTestCases.template.js
test/configCases/asset-modules/only-entry/entry.css
test/configCases/asset-modules/only-entry/entry.js
test/configCases/asset-modules/only-entry/test.config.js
test/configCases/asset-modules/only-entry/test.js
test/configCases/asset-modules/only-entry/webpack.config.js
test/configCases/errors/multi-entry-missing-module/test.config.js
types.d.ts

bugfix
Yes
No, because we generate broken JS file before
No

fix: avoid generating extra js file when using asset module as entrypoint

---

lib/optimize/FlagIncludedChunksPlugin.js

bugfix, fixes https://github.com/webpack/webpack/issues/18837

fix: order of chunks ids

---

lib/schemes/DataUriPlugin.js
test/configCases/asset-modules/data-url/index.js

fix: handle DataURI without `base64` word

---

lib/css/CssModulesPlugin.js
lib/index.js
types.d.ts

feat: export CSS and ESM runtime modules

---

package.json

bugfix
fixes https://github.com/webpack/webpack/issues/18916
No
No
No

fix: add `@types/eslint-scope` to dependencies

---

lib/index.js
types.d.ts

fix: types regression in validate

---

.prettierignore
eslint.config.js
lib/asset/AssetModulesPlugin.js
test/ConfigTestCases.template.js
test/HotTestCases.template.js
test/TestCases.template.js
test/WatchTestCases.template.js
test/checkArrayExpectation.js
test/configCases/asset-modules/data-url-broken/errors.js
test/configCases/asset-modules/data-url-broken/index.js
test/configCases/asset-modules/data-url-broken/infrastructure-log.js
test/configCases/asset-modules/data-url-broken/webpack.config.js
test/configCases/cache-filesystem/multicompiler-mode-cache-1/test.filter.js
test/configCases/cache-filesystem/multicompiler-mode-cache-2/test.filter.js
test/configCases/cache-filesystem/multicompiler-mode-cache-3/test.filter.js
test/configCases/cache-filesystem/multicompiler-mode-cache-4/test.filter.js
test/configCases/cache-filesystem/multicompiler-mode-cache-5/test.filter.js
test/configCases/cache-filesystem/multicompiler-mode-cache-6/test.filter.js

fix: crash with filesystem cache and unknown scheme

---

lib/config/defaults.js
lib/dependencies/CssLocalIdentifierDependency.js
test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
test/__snapshots__/ConfigTestCases.basictest.js.snap
test/configCases/css/cjs-module-syntax/index.js
test/configCases/css/css-auto/index.js
test/configCases/css/css-types/index.js
test/configCases/css/default-exports-parser-options/index.js
test/configCases/css/exports-convention-prod/index.js
test/configCases/css/named-exports-parser-options/index.js
test/configCases/css/prefer-relative-css-import/index.js
test/configCases/css/prefer-relative/index.js
test/configCases/css/runtime-issue/entry1.js
test/configCases/css/runtime-issue/entry2.js

fix: don't add `[uniqueName]` to `localIdentName` when it is empty

---

test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
test/__snapshots__/ConfigTestCases.basictest.js.snap
test/configCases/css/css-modules/style.module.css

test: `var()` in CSS

---

lib/library/AssignLibraryPlugin.js
test/configCases/library/issue-18932/index.js
test/configCases/library/issue-18932/webpack.config.js

fixes https://github.com/webpack/webpack/issues/18932
Yes
No
No

fix: variable name conflict with concatenate and runtime code

---

lib/css/CssParser.js
lib/dependencies/CssIcssImportDependency.js
lib/dependencies/CssLocalIdentifierDependency.js
test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
test/__snapshots__/ConfigTestCases.basictest.js.snap
test/configCases/css/css-modules/style.module.css
test/configCases/css/css-modules/var-function-export.modules.css
test/configCases/css/css-modules/var-function.module.css

feature - https://github.com/webpack/webpack/issues/14893
```
var(xxx from "...")
var(xxx from global)
```
Yes
No
No

feat(css): composes custom properties

---

lib/css/walkCssTokens.js
test/__snapshots__/walkCssTokens.unittest.js.snap
test/configCases/css/parsing/cases/newline-windows.css
test/configCases/css/parsing/style.css

fix(css): parsing strings on Windows

---

lib/esm/ModuleChunkFormatPlugin.js
lib/esm/ModuleChunkLoadingRuntimeModule.js
test/configCases/library/issue-18951/index.js
test/configCases/library/issue-18951/test.config.js
test/configCases/library/issue-18951/webpack.config.js

fixes #18951
Yes
Potentially no, but if you want to use runtime generated by old versions of webpack with the current fix, they will not work
No

fix: collisions in ESM library

---

lib/config/defaults.js
lib/node/ReadFileCompileAsyncWasmPlugin.js
lib/wasm/EnableWasmLoadingPlugin.js
test/Defaults.unittest.js
test/configCases/wasm/async-node-module/index.js
test/configCases/wasm/async-node-module/module.js
test/configCases/wasm/async-node-module/test.config.js
test/configCases/wasm/async-node-module/test.filter.js
test/configCases/wasm/async-node-module/wasm.wat
test/configCases/wasm/async-node-module/webpack.config.js

bugfix - use always async loading when it `asyncWebAssembly` used
Yes
No
No

fix: wasm loading for async webassembly in node

---

lib/config/defaults.js
lib/wasm-async/AsyncWasmLoadingRuntimeModule.js
lib/wasm-async/UniversalCompileAsyncWasmPlugin.js
lib/wasm/EnableWasmLoadingPlugin.js
test/ConfigTestCases.template.js
test/configCases/wasm/universal/index.js
test/configCases/wasm/universal/module.js
test/configCases/wasm/universal/test.config.js
test/configCases/wasm/universal/test.filter.js
test/configCases/wasm/universal/wasm.wat
test/configCases/wasm/universal/webpack.config.js
test/helpers/supportsResponse.js

feature
Yes
No
Yes, but we should improve other things, will open later

feat: universal wasm loading for async wasm (only ES modules)

---

lib/wasm-async/AsyncWasmLoadingRuntimeModule.js
lib/wasm-async/UniversalCompileAsyncWasmPlugin.js
lib/wasm/EnableWasmLoadingPlugin.js

refactor: supports streaming for wasm universal

---

test/Queue.unittest.js

test: queue

---

lib/stats/DefaultStatsFactoryPlugin.js

Delete some unused statements in DefaultStatsFactoryPlugin.
not needed.
no.

fix: delete unused statements in DefaultStatsFactoryPlugin

---

lib/util/Queue.js
test/Queue.unittest.js

perf
Yes
No, it is a internal class
No

perf: a faster Queue implementation

---

.github/workflows/test.yml

ci, fixes https://github.com/webpack/webpack/pull/18891
No need
No
No

ci: test on 22 and 23 Node.js

---

lib/RuntimeTemplate.js
lib/config/defaults.js
lib/config/target.js
lib/css/CssLoadingRuntimeModule.js
lib/esm/ModuleChunkLoadingRuntimeModule.js
lib/wasm-async/UniversalCompileAsyncWasmPlugin.js
test/configCases/css/universal/index.js
test/configCases/css/universal/style.css
test/configCases/css/universal/style.modules.css
test/configCases/css/universal/style2.css
test/configCases/css/universal/style2.modules.css
test/configCases/css/universal/style3.modules.css
test/configCases/css/universal/test.config.js
test/configCases/css/universal/test.filter.js
test/configCases/css/universal/webpack.config.js
test/configCases/css/universal/worker.js
types.d.ts

feat: universal CSS target

---

lib/css/CssParser.js
lib/dependencies/CssLocalIdentifierDependency.js
test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
test/__snapshots__/ConfigTestCases.basictest.js.snap
test/configCases/css/escape-unescape/index.js
test/configCases/css/escape-unescape/style.modules.css
test/configCases/css/escape-unescape/test.config.js
test/configCases/css/escape-unescape/webpack.config.js
test/configCases/css/exports-convention/index.js

fix: css local escaping

---

lib/CssModule.js
lib/DependencyTemplate.js
lib/HotModuleReplacementPlugin.js
lib/Module.js
lib/css/CssGenerator.js
lib/css/CssLoadingRuntimeModule.js
lib/css/CssModulesPlugin.js
lib/dependencies/CssIcssExportDependency.js
lib/dependencies/CssIcssSymbolDependency.js
lib/dependencies/CssLocalIdentifierDependency.js
test/HotTestCases.template.js
test/hotCases/css/css-modules/index.js
test/hotCases/css/css-modules/style.module.css
test/hotCases/css/css-modules/style2.module.css
test/hotCases/css/css-modules/test.config.js
test/hotCases/css/css-modules/webpack.config.js
test/hotCases/css/fetch-priority/index.js
test/hotCases/css/fetch-priority/style.module.css
test/hotCases/css/fetch-priority/webpack.config.js
test/hotCases/css/vanilla/index.js
test/hotCases/css/vanilla/style.css
test/hotCases/css/vanilla/style2.css
test/hotCases/css/vanilla/test.config.js
test/hotCases/css/vanilla/webpack.config.js
types.d.ts

fixes https://github.com/webpack/webpack/issues/19011
WIP
No
No

refactor: CSS HMR

---

lib/css/CssParser.js
lib/dependencies/CssLocalIdentifierDependency.js

refactor: no extra work for CSS unescaping

---

package.json

fix: `package.json`

---

lib/hmr/HotModuleReplacementRuntimeModule.js

fixes https://github.com/webpack/webpack/pull/19030
No need
No
No

refactor: issue #19030

---

lib/util/Queue.js

perf: regression

---

lib/util/semver.js

fixes https://github.com/webpack/webpack/pull/19049
Existing
No
No

fix: mf parse range not compat with safari

---

lib/stats/DefaultStatsFactoryPlugin.js

This is just a small internal correction.
No. They are not needed
No.
Nothing.

chore: fixed incorrect typecast in `DefaultStatsFactoryPlugin`

---

README.md

This PR introduces a documentation update. It adds helpful resources to the README file for better understanding of Webpack.
Fixes #19090 
Not applicable. This change affects only the documentation and does not alter any code or functionality.
No, this PR does not introduce any breaking changes.
What needs to be documented once your changes are merged?
The added links to the README file:
Understanding Webpack - Video 1
Understanding Webpack - Video 2
These provide resources for developers to learn more about Webpack. No further documentation updates are needed as part of this change.

Improved readme.md by adding video links for understanding webpack

---

lib/Compilation.js

Roughly 5% of my team's watch-mode rebuilds is spent in the `assignDepths` function. This change reduces that to 3%
performance enhancement
Covered by existing unit tests for this function. Not a logic change.
No.
Performance only, no behavior change, so nothing.

(perf) optimize assign-depths

---

lib/Module.js
types.d.ts

Refer to https://github.com/webpack/webpack/discussions/19186
No need.
No.
No.

fix(types): correct BuildInfo and BuildMeta type definitions

---

eslint.config.js
lib/runtime/AutoPublicPathRuntimeModule.js
test/ConfigTestCases.template.js
test/Stats.test.js
test/__snapshots__/StatsTestCases.basictest.js.snap
test/configCases/worker/blob/index.js
test/configCases/worker/blob/module.js
test/configCases/worker/blob/test.filter.js
test/configCases/worker/blob/webpack.config.js
test/configCases/worker/blob/worker-wrapper.js
test/configCases/worker/blob/worker.js
test/helpers/createFakeWorker.js
test/helpers/supportsBlob.js

fixes https://github.com/webpack/webpack/issues/19057
Also now you can use our bundled code inside `Blob` and using `auto` public path with any problems
Yes
No
No need

fix: strip `blob:` protocol when public path is `auto`

---

lib/config/defaults.js
lib/css/CssLoadingRuntimeModule.js
lib/esm/ModuleChunkLoadingRuntimeModule.js
lib/web/JsonpChunkLoadingRuntimeModule.js
test/Defaults.unittest.js
test/configCases/output/charset/chunk1.css
test/configCases/output/charset/index.js
test/configCases/output/charset/test.config.js
test/configCases/output/charset/webpack.config.js
test/configCases/web/prefetch-preload-module/index.mjs
test/configCases/web/prefetch-preload/index.js

bugfix + don't insert charset for future default
Yes
No
Nothing

fix: respect `output.charset` everywhere

---

test/helpers/supportsBlob.js
test/helpers/supportsResponse.js

chore: typo

---

lib/esm/ModuleChunkFormatPlugin.js
lib/javascript/StartupHelpers.js
test/NodeTemplatePlugin.test.js
test/configCases/asset-modules/entry-with-runtimeChunk/entry.css
test/configCases/asset-modules/entry-with-runtimeChunk/entry.js
test/configCases/asset-modules/entry-with-runtimeChunk/test.config.js
test/configCases/asset-modules/entry-with-runtimeChunk/test.js
test/configCases/asset-modules/entry-with-runtimeChunk/webpack.config.js

Fixes https://github.com/webpack/webpack/issues/19169.
Yes
No
No

fix: runtime error when using asset module as entrypoint and runtimeChunk

---

README.md
cspell.json

Adds Sean as a tsc member
N/A
N/A
N/A

chore(docs): add sean larkin as a tsc member

---

test/configCases/library/cjs-static/index.js
test/configCases/library/cjs-static/webpack.config.js

Add test for https://github.com/webpack/webpack/pull/14998
Yes
No
No

test: commonjs-static

---

lib/NormalModuleFactory.js

We can ensure that the dependency definitely exists here.
No
No
No

refactor: remove unnecessary check in dependency type assignment

---

CONTRIBUTING.md
TESTING_DOCS.md
test/NodeTemplatePlugin.test.js

This PR updates the README to improve clarity, structure, and completeness. The changes include better formatting, additional instructions, and improved descriptions to help users understand the project more easily.
This update enhances the readability and usability of the testing folder, making it easier for contributors and users to get started with the project.

docs:Added TESTING_DOCS for better understanding of testing

---

lib/CleanPlugin.js
lib/stats/DefaultStatsPrinterPlugin.js
lib/stats/StatsPrinter.js
types.d.ts

Fix typo KnownStatsPrinterFormaters to KnownStatsPrinterFormatters

chore: Fix typo

---

test/helpers/captureStdio.js

test: fix import assertion

---

lib/webworker/ImportScriptsChunkLoadingPlugin.js
lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js
test/configCases/runtime/target-webworker-with-dynamic/async.js
test/configCases/runtime/target-webworker-with-dynamic/index.js
test/configCases/runtime/target-webworker-with-dynamic/test.config.js
test/configCases/runtime/target-webworker-with-dynamic/webpack.config.js
test/configCases/runtime/target-webworker/index.js
test/configCases/runtime/target-webworker/test.config.js
test/configCases/runtime/target-webworker/webpack.config.js

fix: entry module isn't executed when targeting webworker with a runtime chunk

---

lib/dependencies/WorkerDependency.js
lib/dependencies/WorkerPlugin.js
test/configCases/worker/self-import/index.js
test/configCases/worker/self-import/module.js
test/configCases/worker/self-import/test.config.js
test/configCases/worker/self-import/test.filter.js
test/configCases/worker/self-import/warnings.js
test/configCases/worker/self-import/webpack.config.js

Feature - https://github.com/webpack/webpack/issues/12638
There is a small bottleneck, when you use such syntax you will get a warning:
```
WARNING in [entry] [initial]
Circular dependency between chunks with runtime (main, test_js)
This prevents using hashes of each other and should be avoided.
```
it is not a critical problem and will be solved in future  
Yes
No
No

feat: handle `new Worker(import.meta.url)` and `new Worker(new URL(import.meta.url))` syntax

---

lib/asset/AssetGenerator.js
lib/asset/AssetModulesPlugin.js
test/configCases/asset-modules/errored/errors.js
test/configCases/asset-modules/errored/index.js
test/configCases/asset-modules/errored/infrastructure-log.js
test/configCases/asset-modules/errored/loader.js
test/configCases/asset-modules/errored/style.css
test/configCases/asset-modules/errored/test.config.js
test/configCases/asset-modules/errored/webpack.config.js

fixes https://github.com/webpack/webpack/issues/19251
fixes https://github.com/webpack/webpack/pull/19270
WIP
No
No

fix: use a valid output path for errored asset modules

---

lib/dependencies/HarmonyExportDependencyParserPlugin.js
test/configCases/loaders/import-attributes-and-reexport/a.js
test/configCases/loaders/import-attributes-and-reexport/b.js
test/configCases/loaders/import-attributes-and-reexport/c.js
test/configCases/loaders/import-attributes-and-reexport/index.js
test/configCases/loaders/import-attributes-and-reexport/test-loader.js
test/configCases/loaders/import-attributes-and-reexport/webpack.config.js

fixes https://github.com/webpack/webpack/issues/19284
Yes
No
Nothing

fix: do not duplicate modules with import attributes and reexport

---

.github/workflows/test.yml
eslint.config.mjs
lib/Compilation.js
lib/debug/ProfilingPlugin.js
lib/hmr/HotModuleReplacement.runtime.js
lib/hmr/JavascriptHotModuleReplacement.runtime.js
lib/javascript/JavascriptParser.js
lib/node/nodeConsole.js
lib/util/serialization.js
package.json
yarn.lock

chore - update eslint configuration/rules/versions
No need
No
Nothing

chore: eslint improvements

---

lib/optimize/SplitChunksPlugin.js

chore: fix lint

---

README.md

docs, fix my name in README
NA
No
Nothing

docs: fix typo in name

---

lib/Chunk.js
lib/Compilation.js
lib/Compiler.js
lib/EnvironmentPlugin.js
lib/ExportsInfo.js
lib/FileSystemInfo.js
lib/FlagDependencyExportsPlugin.js
lib/NormalModuleFactory.js
lib/cache/PackFileCacheStrategy.js
lib/dependencies/HarmonyExportImportedSpecifierDependency.js
lib/hmr/LazyCompilationPlugin.js
lib/javascript/JavascriptModulesPlugin.js
lib/javascript/JavascriptParser.js
lib/optimize/SplitChunksPlugin.js
lib/serialization/ObjectMiddleware.js
lib/stats/DefaultStatsFactoryPlugin.js
lib/util/cleverMerge.js
lib/util/concatenate.js
lib/util/deterministicGrouping.js
lib/util/registerExternalSerializer.js
lib/util/serialization.js
tsconfig.json
tsconfig.module.test.json
tsconfig.types.json
types.d.ts

bugfix - `strict` types
No need
No
No

fix: `strict` types

---

declarations.d.ts
declarations/WebpackOptions.d.ts
declarations/plugins/SourceMapDevToolPlugin.d.ts
eslint.config.mjs
lib/ChunkGraph.js
lib/Compilation.js
lib/DefinePlugin.js
lib/DependencyTemplates.js
lib/IgnorePlugin.js
lib/ModuleFilenameHelpers.js
lib/SourceMapDevToolPlugin.js
lib/Template.js
lib/TemplatedPathPlugin.js
lib/debug/ProfilingPlugin.js
lib/hmr/LazyCompilationPlugin.js
lib/index.js
lib/optimize/SplitChunksPlugin.js
lib/serialization/ObjectMiddleware.js
lib/stats/DefaultStatsFactoryPlugin.js
lib/util/SortableSet.js
lib/util/binarySearchBounds.js
lib/util/cleverMerge.js
lib/util/deprecation.js
lib/wasm-sync/WebAssemblyGenerator.js
lib/wasm-sync/WebAssemblyParser.js
schemas/WebpackOptions.json
schemas/plugins/SourceMapDevToolPlugin.json
types.d.ts

bugfix - types
No need
No
Nothing

fix: no `Function` types

---

.github/workflows/test.yml
declarations/WebpackOptions.d.ts
package.json
schemas/WebpackOptions.json
tsconfig.validation.json
types.d.ts
yarn.lock

chore
WIP, will be great to add a validation step in our CI and validate that our types are working with ts@5.7, ts@5.6, maybe less
No
No

chore: fix ts generation

---

lib/Dependency.js

This PR optimizes the loc object structure to ensure monomorphic inline caching (IC), improving performance by reducing hidden class changes. 
Previously, the loc object was dynamically shaped based on conditions, leading to polymorphic IC, which negatively impacted performance,
fixes https://github.com/webpack/webpack/issues/19315
Refactoring
No, existing test cases cover the functionality. No functional changes made..
No
No

fix : optimize loc for monomorphic inline caching

---

test/HotModuleReplacementPlugin.test.js

While running tests for HotModuleReplacementPlugin.test.js, a deprecation warning was shown, promoting to use fullhash as the placeholder against hash.
bugfix
NA
No
NA

fix: hash to fullhash

---

lib/optimize/SplitChunksPlugin.js
test/configCases/split-chunks/no-name/a.js
test/configCases/split-chunks/no-name/index.js
test/configCases/split-chunks/no-name/test.config.js
test/configCases/split-chunks/no-name/webpack.config.js
types.d.ts

fix(types): split chunks cached group

---

lib/javascript/JavascriptParser.js
test/__snapshots__/StatsTestCases.basictest.js.snap
test/statsCases/track-returned/index.js
test/statsCases/track-returned/test.config.js
test/statsCases/track-returned/used30.js
test/statsCases/track-returned/used31.js
test/statsCases/track-returned/used32.js
test/statsCases/track-returned/used33.js
test/statsCases/track-returned/used34.js
test/statsCases/track-returned/used35.js
test/statsCases/track-returned/used36.js
test/statsCases/track-returned/used37.js
test/statsCases/track-returned/used38.js
test/statsCases/track-returned/used39.js
test/statsCases/track-returned/used40.js
test/statsCases/track-returned/used41.js
test/statsCases/track-returned/used42.js
test/statsCases/track-returned/used43.js
test/statsCases/track-returned/used44.js
test/statsCases/track-returned/used45.js
test/statsCases/track-returned/used46.js
test/statsCases/track-returned/used47.js
test/statsCases/track-returned/used48.js
test/statsCases/track-returned/used49.js
test/statsCases/track-returned/used50.js
test/statsCases/track-returned/used51.js

fix: dead control flow more cases

---

lib/javascript/JavascriptParser.js
test/__snapshots__/StatsTestCases.basictest.js.snap
test/statsCases/track-returned/index.js
test/statsCases/track-returned/test.config.js
test/statsCases/track-returned/used70.js
test/statsCases/track-returned/used71.js
test/statsCases/track-returned/used72.js
test/statsCases/track-returned/used73.js
test/statsCases/track-returned/used74.js
test/statsCases/track-returned/used75.js
test/statsCases/track-returned/used76.js
test/statsCases/track-returned/used77.js
test/statsCases/track-returned/used78.js

https://github.com/webpack/webpack/issues/19394#issuecomment-2787389005
Yes
No
No

fix: terminated state for if/else

---

lib/javascript/JavascriptParser.js
test/__snapshots__/StatsTestCases.basictest.js.snap
test/statsCases/track-returned/index.js
test/statsCases/track-returned/test.config.js
types.d.ts

bugfix, but some things like improvements
https://github.com/webpack/webpack/issues/19394#issuecomment-2787667988
Yes, a lot of
No
No

Test terminated state

---

lib/library/ModuleLibraryPlugin.js
test/configCases/library/0-create-library/class-commonjs.js
test/configCases/library/0-create-library/class-esm.js
test/configCases/library/0-create-library/esm-with-commonjs.js
test/configCases/library/0-create-library/function-commonjs.js
test/configCases/library/0-create-library/function-esm.js
test/configCases/library/0-create-library/webpack.config.js
test/configCases/library/1-use-library/esm-with-commonjs.js
test/configCases/library/1-use-library/webpack.config.js

fixes https://github.com/webpack/webpack/issues/19423
Yes
No
No

fix: module library export generation when mixing commonjs and esm modules

---

codecov.yml

ci: remove `lintunit` project from coverage

---

.github/workflows/test.yml
README.md
codecov.yml

ci - better coverage of basic and types flags
No need
No
No

ci: improve codecov report

---

.github/workflows/test.yml
README.md
codecov.yml

ci: fix types coverage

---

lib/esm/ModuleChunkLoadingPlugin.js
lib/esm/ModuleChunkLoadingRuntimeModule.js
test/ConfigTestCases.template.js
test/configCases/output-module/public-path/chunk.js
test/configCases/output-module/public-path/chunk1.js
test/configCases/output-module/public-path/index.js
test/configCases/output-module/public-path/test.config.js
test/configCases/output-module/public-path/webpack.config.js

fixes https://github.com/webpack/webpack/issues/19432
Yes
No
Nothing

fix: respect public path for ES modules

---

CONTRIBUTING.md

Documentation update.
Not applicable – documentation-only change.
No.
No further documentation needed; this PR updates documentation.

update contributing.md to reflect current labels

---

test/hotCases/css/imported-css/test.filter.js
test/hotCases/css/single-css-entry/test.filter.js
test/hotCases/css/with-lazy-compilation/test.filter.js

🤦‍♂️ My apologies for skipping the test by mistake.
No
No
No

fix: skipping the `css` test

---

lib/cli.js
package.json
types.d.ts
yarn.lock

fixes https://github.com/webpack/webpack/pull/19445
No need
No
Nothing

fix: missing `@types/json-schema` in types

---

dependabot.yml

ci - update github actions too
No need
No
No

ci: update github action too

---

.github/workflows/examples.yml
.github/workflows/test.yml

ci: uses PAT token for benchmarks and enable examples

---

.github/workflows/test.yml
cspell.json
package.json
test/BenchmarkTestCases.benchmark.mjs
yarn.lock

ci - benchmarks, using `codspeed`
No need
No
No

ci: using `codspeed` for benchmarks

---

lib/Compilation.js

replace traditional for loops with for...of for better readability
refactoring
no
no

refactor: replace traditional for loops with for...of for better readability

---

lib/CacheFacade.js
lib/CssModule.js
lib/Dependency.js
lib/NormalModule.js
lib/NormalModuleFactory.js
lib/asset/AssetGenerator.js
lib/dependencies/CssUrlDependency.js
lib/dependencies/ModuleDependency.js
lib/dependencies/URLDependency.js
lib/optimize/SideEffectsFlagPlugin.js
lib/rules/RuleSetCompiler.js
lib/schemes/DataUriPlugin.js
lib/sharing/ProvideSharedPlugin.js
package.json
types.d.ts
yarn.lock

Fix some TODO types.
No need
No
No

fix: better types

---

lib/ChunkGraph.js
lib/FileSystemInfo.js

remove unnecessary continue statements in ChunkGraph and FileSystemInfo
refactor
no
no
no

refactor: remove unnecessary continue statements in ChunkGraph and FileSystemInfo

---

.github/workflows/test.yml

CI
Run tests on Node.js v24
No
Nothing

ci: add Node.js v24

---

lib/javascript/JavascriptParser.js
test/configCases/parsing/destructuring-namespace-import/index.js
test/configCases/parsing/destructuring-namespace-import/module.js
test/configCases/parsing/destructuring-namespace-import/webpack.config.js

fixes https://github.com/webpack/webpack/issues/19518
Yes
No
No

fix: destructuring namespace import with default

---

lib/javascript/JavascriptParser.js
test/configCases/parsing/destructuring-computed-property/index.js
test/configCases/parsing/destructuring-computed-property/module.js
test/configCases/parsing/destructuring-computed-property/webpack.config.js
test/configCases/parsing/destructuring-rest/index.js
test/configCases/parsing/destructuring-rest/module.js
test/configCases/parsing/destructuring-rest/webpack.config.js

bugfix, partially related to https://github.com/webpack/webpack/issues/19518
Yes
No
No

fix: destructuring with computed-property

---

eslint.config.mjs
test/NodeTemplatePlugin.test.js

chore: avoid eslint warning after running tests
No need
No
No

chore: avoid eslint warning after running tests

---

lib/ChunkGroup.js
lib/Compilation.js
lib/stats/DefaultStatsPrinterPlugin.js

chore: fix todo types

---

lib/asset/AssetGenerator.js
lib/asset/AssetSourceGenerator.js
test/hotCases/asset-modules-source/lazy-compilation/file.text
test/hotCases/asset-modules-source/lazy-compilation/index.js
test/hotCases/asset-modules-source/lazy-compilation/webpack.config.js

Fixes https://github.com/webpack/webpack/issues/19532.
Yes
No
No

fix: sourceTypes of asset module when lazy compilation

---

test/BenchmarkTestCases.benchmark.mjs

ci: benchmarks stability

---

lib/ConstPlugin.js
lib/dependencies/RequireEnsureDependenciesBlockParserPlugin.js
lib/javascript/JavascriptParser.js
test/configCases/parsing/dead-code-elimination-require-ensure/foo.js
test/configCases/parsing/dead-code-elimination-require-ensure/index.js
test/configCases/parsing/dead-code-elimination-require-ensure/webpack.config.js
test/configCases/parsing/dead-code-elimination/esm1.js
test/configCases/parsing/dead-code-elimination/esm2.js
test/configCases/parsing/dead-code-elimination/index.js
test/configCases/parsing/dead-code-elimination/test.config.js
test/configCases/parsing/dead-code-elimination/test.js
test/configCases/parsing/dead-code-elimination/webpack.config.js
test/configCases/parsing/issue-19514/index.js
test/configCases/parsing/issue-19514/webpack.config.js
test/configCases/parsing/issue-4857/index.js
types.d.ts

We have previously supported the elimination of unreachable (dead) branches in if statements in #6273. 
In this PR, we adopt the same approach to remove some dead statements when tracked completely return/throw statement, as implemented in #14357.
And it also fixes https://github.com/webpack/webpack/issues/19514.
Yes
No
No

fix: eliminate unused statements in certain scenarios

---

lib/url/URLExpressionParserPlugin.js

perf - cache `new URL()`, when we have `export new URL("./test.txt", import.meta.url);` we will call `evaluteExpression` three times, now we cache it
Existing
No
No

perf: cache new URL evaluate expression

---

declarations.d.ts
lib/Compilation.js
lib/Compiler.js
lib/ContextReplacementPlugin.js
lib/CssModule.js
lib/HotModuleReplacementPlugin.js
lib/NormalModuleFactory.js
lib/RecordIdsPlugin.js
lib/dependencies/AMDPlugin.js
lib/dependencies/AMDRequireDependenciesBlockParserPlugin.js
lib/dependencies/HarmonyExportImportedSpecifierDependency.js
lib/dependencies/HarmonyImportDependencyParserPlugin.js
lib/javascript/JavascriptParser.js
lib/optimize/AggressiveSplittingPlugin.js
test/JavascriptParser.unittest.js
test/cases/amd/define-amd/index.js
test/cases/amd/require-module-keywords/index.js
test/cases/amd/require-module-keywords/module.js
types.d.ts

refactor + fix typescript types + tests
Yes
No
No

fix: types and test

---

test/BenchmarkTestCases.benchmark.mjs
test/ProgressPlugin.test.js
test/checkArrayExpectation.js
test/configCases/output-module/iife-multiple-entry-modules/test.js

refactor test code for better readability
refactoring
no
no
no

test: refactor test code

---

test/WatchTestCases.template.js

We should clean the output directory before the second compilation starts. Otherwise, we will execute all output files generated from previous compilations, especially when they have different content hashes. This can lead to the execution of redundant files and also cause potential ESM errors.
For more details, I will outline the files in the output directory and the files being executed:
First Compilation:
```
Output files: 
- a.hash0.js
- b.hash0.js
Executed files: 
- a.hash0.js
- b.hash0.js
```
Second Compilation (when the b file remains unchanged):
```
Output files: 
- a.hash0.js
- a.hash1.js
- b.hash0.js
Executed files: 
- a.hash0.js
- a.hash1.js
- b.hash0.js
```
What we expected behavior in second compilation :
```
Output files: 
- …
```

test: refactor watchTestCase when ESM

---

lib/CleanPlugin.js
test/CleanPlugin.unittest.js

fix: CleanPlugin unlink same file twice

---

test/hotCases/esm-output/css-modules/index.js
test/hotCases/esm-output/split-chunks/index.js

Fixes: update test cases where tests ended before hot-update.js files were generated.
Yes
No
No

fix(test): update tests for ESM HMR

---

lib/CleanPlugin.js

fix: Unexpected Error Codes from fs.unlink on Windows

---

lib/HotModuleReplacementPlugin.js
lib/config/defaults.js
lib/esm/ModuleChunkLoadingRuntimeModule.js
test/Defaults.unittest.js

refactor: use import to load the HMR manifest to support all ESM environments

---

lib/esm/ModuleChunkLoadingRuntimeModule.js
lib/hmr/JavascriptHotModuleReplacementHelper.js
lib/node/ReadFileChunkLoadingRuntimeModule.js
lib/node/RequireChunkLoadingRuntimeModule.js
lib/web/JsonpChunkLoadingRuntimeModule.js
lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js

Extract duplicate HMR logic into `helper` module.
We currently rely on the `fetch` API to get the HMR manifest, limiting support to browser environments, so Improve the error message for better understanding.
Existing
No
Nothing

refactor: consolidate HMR code

---

lib/javascript/JavascriptGenerator.js

refactor: replace the implementation of magic_number

---

test/configCases/defer-import/async-in-graph/webpack.config.js
test/configCases/defer-import/comment-error/webpack.config.js
test/configCases/defer-import/defer-but-sync-order/webpack.config.js
test/configCases/defer-import/defer-runtime-concat-strict/webpack.config.js
test/configCases/defer-import/defer-runtime-concat/webpack.config.js
test/configCases/defer-import/defer-runtime-native-syntax/webpack.config.js
test/configCases/defer-import/defer-runtime-strict/webpack.config.js
test/configCases/defer-import/defer-runtime/webpack.config.js
test/configCases/defer-import/defer-then-non-defer/webpack.config.js
test/configCases/defer-import/defer-used-in-async/webpack.config.js
test/configCases/defer-import/syntax-error-if-experiment-not-enabled/webpack.config.js

tests fixes
these are tests
No
No

test: resolve optional chaining test todo

---

lib/library/AssignLibraryPlugin.js
test/configCases/library/issue-19664/index.js
test/configCases/library/issue-19664/webpack.config.js

Fixes https://github.com/webpack/webpack/issues/19664.
Yes
No
No

fix: lose closing brace when exports are unprovided

---

declarations.d.ts
lib/DllEntryPlugin.js
lib/DllPlugin.js
lib/ExternalModule.js
lib/Generator.js
lib/JavascriptMetaInfoPlugin.js
lib/LoaderOptionsPlugin.js
lib/Module.js
lib/MultiCompiler.js
lib/NormalModule.js
lib/NormalModuleFactory.js
lib/ProgressPlugin.js
lib/asset/AssetGenerator.js
lib/asset/AssetModulesPlugin.js
lib/cache/IdleFileCachePlugin.js
lib/cli.js
lib/css/CssModulesPlugin.js
lib/index.js
lib/util/create-schema-validation.js
test/Validation.test.js
test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
test/configCases/source-map/loader-source-map-string/index.js
test/configCases/source-map/loader-source-map-string/loader.js
test/configCases/source-map/loader-source-map-string/module.js
test/configCases/source-map/loader-source-map-string/webpack.config.js
test/configCases/source-map/loader-source-map/index.js
test/configCases/source-map/loader-source-map/loader.js
test/configCases/source-map/loader-source-map/module.js
test/configCases/source-map/loader-source-map/webpack.config.js
types.d.ts

fix types
Yes, for some cases
No
Nothing

Refactor resolve todo in types

---

eslint.config.mjs
examples/virtual-modules/README.md
examples/virtual-modules/build.js
examples/virtual-modules/code.js
examples/virtual-modules/example.js
examples/virtual-modules/routes/a.js
examples/virtual-modules/routes/b.js
examples/virtual-modules/template.md
examples/virtual-modules/test.filter.js
examples/virtual-modules/tsconfig.json
examples/virtual-modules/typescript.ts
examples/virtual-modules/webpack.config.js

just example
No need
No
Nothing

docs: added virtual modules examples

---

lib/Dependency.js
lib/IgnorePlugin.js
lib/Module.js
lib/RawModule.js
lib/dependencies/ModuleDependency.js
test/configCases/ignore/side-effects/ignored-module.js
test/configCases/ignore/side-effects/locales/a.js
test/configCases/ignore/side-effects/locales/b.js
test/configCases/ignore/side-effects/test.js
test/configCases/ignore/side-effects/webpack.config.js

close: #19670
a bugfix
Yes
No
Nothing

fix: tree-shaking unused `RawModule`

---

lib/NormalModuleFactory.js
lib/rules/RuleSetCompiler.js
lib/rules/UseEffectRulePlugin.js
lib/stats/DefaultStatsPresetPlugin.js
lib/stats/StatsFactory.js
lib/stats/StatsPrinter.js
lib/util/cleverMerge.js
types.d.ts

resolve TODO types
No need
No
Nothing

chore: fix types

---

.gitignore

doc: update .gitignore

---

lib/WebpackOptionsApply.js
lib/dependencies/HarmonyExportDependencyParserPlugin.js
lib/dependencies/HarmonyImportDependencyParserPlugin.js
lib/javascript/JavascriptParser.js
test/configCases/defer-import/syntax-error-if-experiment-not-enabled/errors.js
test/configCases/defer-import/syntax-error-if-experiment-not-enabled/index.js
test/configCases/defer-import/syntax-error-if-experiment-not-enabled/mod.js
test/configCases/defer-import/syntax-error-if-experiment-not-enabled/webpack.config.js
types.d.ts

Local testing only bring little performance improvements. But I believe the changes are more reasonable.
Existing
No
No

refactor: extend importPhasesPlugin only when enable deferImport

---

README.md

chore: remove the deprecated val-loader from the readme

---

lib/APIPlugin.js
lib/ExternalModule.js
lib/RuntimeTemplate.js
lib/node/ReadFileChunkLoadingRuntimeModule.js
lib/node/ReadFileCompileAsyncWasmPlugin.js
lib/node/ReadFileCompileWasmPlugin.js
lib/node/RequireChunkLoadingRuntimeModule.js
test/configCases/worker/node-worker-hmr/webpack.config.js
test/configCases/worker/node-worker-named/webpack.config.js
test/configCases/worker/node-worker/webpack.config.js
test/configCases/worker/worker-contenthash/webpack.config.js
test/hotCases/worker/move-between-runtime/webpack.config.js
test/hotCases/worker/remove-add-worker/webpack.config.js
test/hotCases/worker/update-in-worker/webpack.config.js
types.d.ts

fix: respect `node:` prefix everywhere

---

README.md

/cc @alexander-akait, @evenstensberg.
- Adds a new "Developer Tools" section under "Concepts" in the README. This section lists tools categorized for low-level developers _(e.g. maintainers, plugin authors, integration authors)_ working on webpack internals rather than end-users.
- As a starting point, the "Instrumentation" category introduces the [tapable-tracer](https://github.com/ertgl/tapable-tracer) package.
No tests added, as this is a documentation-only change.
No.

docs: add Developer Tools section to README, mentioning tapable-tracer

---

lib/FileSystemInfo.js
lib/css/CssGenerator.js
lib/util/magicComment.js

perf: avoid extra `require` in some places

---

lib/RuntimeGlobals.js
lib/esm/ModuleChunkFormatPlugin.js
lib/esm/ModuleChunkLoadingRuntimeModule.js
types.d.ts

refactoring: standardize ESM naming management
No
No
No

perf: standardize ESM naming management

---

lib/CleanPlugin.js
test/CleanPlugin.unittest.js

Fixes https://github.com/webpack/webpack/issues/19682#issuecomment-3117781427
No
No
No

fix: fix potential performance issue in CleanPlugin

---

lib/ModuleGraph.js

refactor: optimize connection lookup and add generic grouping
No
No
No

refactor: optimize connection lookup and add generic grouping

---

lib/serialization/FileMiddleware.js
lib/wasm-sync/WebAssemblyGenerator.js
package.json
yarn.lock

refactor - fix types to update typescript
No need
No
Nothing

refactor: fix types

---

lib/ChunkGraph.js
lib/Compilation.js
lib/node/RequireChunkLoadingRuntimeModule.js
lib/runtime/GetChunkFilenameRuntimeModule.js
test/configCases/node/issue-18409-2/common.js
test/configCases/node/issue-18409-2/index.js
test/configCases/node/issue-18409-2/separate.js
test/configCases/node/issue-18409-2/test.config.js
test/configCases/node/issue-18409-2/webpack.config.js
test/configCases/node/issue-18409/common.js
test/configCases/node/issue-18409/index.js
test/configCases/node/issue-18409/separate.js
test/configCases/node/issue-18409/test.config.js
test/configCases/node/issue-18409/webpack.config.js
types.d.ts

Fixes https://github.com/webpack/webpack/issues/18409
Yes
No
No

fix: fix GetChunkFilename failure caused by dependOn entry

---

lib/esm/ModuleChunkFormatPlugin.js
test/configCases/module/dependOn-entries/common.js
test/configCases/module/dependOn-entries/index.js
test/configCases/module/dependOn-entries/separate.js
test/configCases/module/dependOn-entries/test.config.js
test/configCases/module/dependOn-entries/webpack.config.js
test/configCases/module/dependOn-runtime-false/common.js
test/configCases/module/dependOn-runtime-false/index.js
test/configCases/module/dependOn-runtime-false/separate.js
test/configCases/module/dependOn-runtime-false/test.config.js
test/configCases/module/dependOn-runtime-false/webpack.config.js
test/configCases/module/dependOn-runtime-single/common.js
test/configCases/module/dependOn-runtime-single/index.js
test/configCases/module/dependOn-runtime-single/separate.js
test/configCases/module/dependOn-runtime-single/test.config.js
test/configCases/module/dependOn-runtime-single/webpack.config.js
test/configCases/module/entries-runtime-false/common.js
test/configCases/module/entries-runtime-false/index.js
test/configCases/module/entries-runtime-false/separate.js
test/configCases/module/entries-runtime-false/test.config.js
test/configCases/module/entries-runtime-false/webpack.config.js
test/configCases/module/entries-runtime-single/common.js
test/configCases/module/entries-runtime-single/index.js
test/configCases/module/entries-runtime-single/separate.js
test/configCases/module/entries-runtime-single/test.config.js
test/configCases/module/entries-runtime-single/webpack.config.js

bugfix the import of missing dependency chunks
Yes
No
No

fix(esm): fix the import of missing dependency chunks

---

lib/Compilation.js

Fixes https://github.com/webpack/webpack/actions/runs/16879234057/job/47810773366
No
No
No

fix: adjust the timing for adding Group when depending on runtimeChunk

---

test/configCases/library/0-create-library/adding-exports-cjs.js
test/configCases/library/0-create-library/exports-shortcut-cjs.js
test/configCases/library/0-create-library/overrides-exports-cjs.js
test/configCases/library/0-create-library/self-reference-cjs.js
test/configCases/library/0-create-library/webpack.config.js
test/configCases/library/1-use-library/esm-with-bundled-commonjs.js
test/configCases/library/1-use-library/webpack.config.js

Add more test case.
Yes, feel free to more requirement
No
No

test: more case about cjs bundle to esm lib

---

lib/ChunkGraph.js
lib/Compilation.js
lib/Entrypoint.js
lib/GraphHelpers.js
lib/runtime/GetChunkFilenameRuntimeModule.js
types.d.ts

refactor: restructure dependOn relationship retrieval
No
No
No

refactor: restructure dependOn relationship retrieval

---

lib/stats/DefaultStatsPrinterPlugin.js

refactor: update types

---

lib/javascript/JavascriptParser.js

refactor: fix types in javascript parser

---

README.md

fix(docs): mention correct project in the governance section

---

lib/Compilation.js

refactor: remove unused code

---

package.json
yarn.lock

Bump watchpack, fixes `EINVAL initial scan error` https://github.com/webpack/watchpack/issues/187#issuecomment-3239121009.
Existing
No
No

chore: bump watchpack

---

lib/NormalModule.js
lib/schemes/DataUriPlugin.js
lib/schemes/FileUriPlugin.js
lib/schemes/HttpUriPlugin.js
lib/util/extractSourceMap.js
test/configCases/source-map/extract-source-map/extract4.js
test/configCases/source-map/extract-source-map/lock-files/lock.json
test/configCases/source-map/extract-source-map/test4.js
test/configCases/source-map/extract-source-map/webpack.config.js
types.d.ts

feat: extractSourceMap supports HTTP URLs
Yes
No
No

feat: extractSourceMap supports HTTP URLs

---

lib/APIPlugin.js
lib/ExternalModule.js
lib/RuntimeTemplate.js
lib/asset/AssetGenerator.js
lib/asset/AssetSourceGenerator.js
lib/css/CssGenerator.js
lib/dependencies/HarmonyExportImportedSpecifierDependency.js
lib/json/JsonGenerator.js
lib/library/ModuleLibraryPlugin.js
test/configCases/externals/module-import/index.js
test/configCases/module/issue-17971/common.js
test/configCases/module/issue-17971/index.js
test/configCases/module/issue-17971/test.filter.js
test/configCases/module/issue-17971/webpack.config.js
types.d.ts

fixes https://github.com/webpack/webpack/issues/17971
Yes
No, but you can faced with a problem if you have defined `__WEBPACK_EXTERNAL_createRequire_require` variable, but using any `__WEBPACK__` variables inside your code is not safe at all
No

fix: issue 17971

---

test/watchCases/chunks/esm-async-chunks-hmr/0/index.js
test/watchCases/chunks/esm-async-chunks-hmr/1/dynamic-1.js
test/watchCases/chunks/node-async-chunks-hmr/0/index.js

test - avoid extra output in terminal
No need
No
Nothing

test: avoid extra output

---

lib/FileSystemInfo.js

refactor: fix merge

---

README.md
test/configCases/asset-modules/http-url/dev-defaults.webpack.lock.data/https_raw.githubusercontent.com/webpack_webpack_main_CODE_OF_CONDUCT_06e7b335922db99b918d.md
test/configCases/asset-modules/http-url/dev-defaults.webpack.lock.data/https_raw.githubusercontent.com/webpack_webpack_main_README_c9ec0fd496c92f077657.md
test/configCases/asset-modules/http-url/errors.webpack.lock
test/configCases/asset-modules/http-url/errors.webpack.lock.data/https_raw.githubusercontent.com/webpack_webpack_main_CODE_OF_CONDUCT_06e7b335922db99b918d.md
test/configCases/asset-modules/http-url/frozen-verify.webpack.lock
test/configCases/asset-modules/http-url/frozen-verify.webpack.lock.data/https_raw.githubusercontent.com/webpack_webpack_main_CODE_OF_CONDUCT_06e7b335922db99b918d.md
test/configCases/asset-modules/http-url/frozen-verify.webpack.lock.data/https_raw.githubusercontent.com/webpack_webpack_main_README_c9ec0fd496c92f077657.md
test/configCases/asset-modules/http-url/index.js
test/configCases/asset-modules/http-url/no-cache.webpack.lock
test/configCases/asset-modules/http-url/prod-defaults.webpack.lock
test/configCases/asset-modules/http-url/prod-defaults.webpack.lock.data/https_raw.githubusercontent.com/webpack_webpack_main_CODE_OF_CONDUCT_06e7b335922db99b918d.md
test/configCases/asset-modules/http-url/prod-defaults.webpack.lock.data/https_raw.githubusercontent.com/webpack_webpack_main_README_c9ec0fd496c92f077657.md

**Summary**
use markdown instead html
docs
No need
No
Nothing

docs: use markdown instead html

---

test/configCases/asset-modules/http-url/dev-defaults.webpack.lock.data/https_raw.githubusercontent.com/webpack_webpack_main_CODE_OF_CONDUCT_06e7b335922db99b918d.md
test/configCases/asset-modules/http-url/dev-defaults.webpack.lock.data/https_raw.githubusercontent.com/webpack_webpack_main_README_c9ec0fd496c92f077657.md
test/configCases/asset-modules/http-url/errors.webpack.lock
test/configCases/asset-modules/http-url/frozen-verify.webpack.lock
test/configCases/asset-modules/http-url/frozen-verify.webpack.lock.data/https_raw.githubusercontent.com/webpack_webpack_main_README_c9ec0fd496c92f077657.md
test/configCases/asset-modules/http-url/no-cache.webpack.lock
test/configCases/asset-modules/http-url/prod-defaults.webpack.lock
test/configCases/asset-modules/http-url/prod-defaults.webpack.lock.data/https_raw.githubusercontent.com/webpack_webpack_main_README_c9ec0fd496c92f077657.md

**Summary**
Fixes https://github.com/webpack/webpack/actions/runs/18043508600/job/51348453106.
After `SHA-512` hashing and Base64 encoding to `README.md` file, the result should be `0ZvAGT9BNo7wDRzhVolbFzyjKiO77AZnNMcuIrOFrk5DIlwLa0QTz48mERI9Z5KhoIIUBNIMMTi10ZI8aWeMnQ==`
Existing
No
No

fix: integrity in http-url test

---

test/configCases/parsing/bom/index.js
test/configCases/parsing/bom/test.config.js
test/configCases/parsing/bom/webpack.config.js
test/configCases/web/fetch-priority-2/index.js
test/configCases/web/fetch-priority/index.js
test/watchCases/cache/loader-import-module-progress/webpack.config.js
test/watchCases/cache/loader-load-module-progress/webpack.config.js

**Summary**
test stability
test
these are tests
No
Nothing

test: stability and avoid extra output

---

lib/library/SystemLibraryPlugin.js
test/configCases/library/0-create-library/commonjs.js
test/configCases/library/0-create-library/esm.js
test/configCases/library/0-create-library/webpack.config.js
test/configCases/library/1-systemjs-external-commonjs/system-external-commonjs.js
test/configCases/library/1-systemjs-external-commonjs/test.config.js
test/configCases/library/1-systemjs-external-commonjs/webpack.config.js
test/configCases/library/1-systemjs-external-esm/system-external-esm.js
test/configCases/library/1-systemjs-external-esm/test.config.js
test/configCases/library/1-systemjs-external-esm/webpack.config.js

**Summary**
fixes https://github.com/webpack/webpack/issues/19950
fixes https://github.com/webpack/webpack/pull/19975
bugfix
Yes
No
Nothing

test: system default export
