lib/Chunk.js
bugfix
No
**Summary**
Fix Chunk.prototype.entrypoints setter to use `setEntrypoints` instead of wrong `setBlocks` for compatibility.
No
=> Fix Chunk.prototype.entrypoints setter

schemas/WebpackOptions.json
Updated WebpackOptions documentation
I'm not sure where tests are for WebpackOptions. If there is one to update, I'll gladly add one.
**Summary**
The description for the `mode` option was copied from `amd`. This adds a clearer description instead of an unrelated one.
No
This fixes #6135
=> Add description for `mode` option. Fixes #6135

lib/HotModuleReplacementPlugin.js, lib/web/JsonpChunkTemplatePlugin.js, lib/web/JsonpHotUpdateChunkTemplatePlugin.js
refactoring
n/a
n/a
**Summary**
This PR updates the remaining plugins to use `Tapable#hooks` on templates.
It continues what has been done in #6101.
no
=> Use template hooks in plugins

test/configCases/target/web/webpack.config.js, test/configCases/target/webworker/webpack.config.js
=> Avoid minimizing target test cases

lib/Parser.js, lib/util/TrackingSet.js
Extracts the `TrackingSet` class from `Parser.js` into its own module.
**Summary**
@TheLarkInn suggested this class be extracted during the live stream tonight.
- Created `lib/util/TrackingSet.js`
No.
=> Extract TrackingSet class from the Parser.js module.

package.json, test/mocha.opts
bugfix
no
n/a
**Summary**
Without this, some tests ran with `--check-leaks` fail and hide other failures. This global binding is provided by `js-base64`.
no
=> Mark Base64 as global in mocha

lib/MultiModule.js, test/configCases/errors/multi-entry-missing-module/index.js, test/configCases/errors/multi-entry-missing-module/intentionally-missing-module.js, test/configCases/errors/multi-entry-missing-module/webpack.config.js
Use `WebpackMissingModule` instead of multiple strings.
No
**Summary**
Following a TODO item
no
=> Feature: Use WebpackMissingModule

examples/dll-app-and-vendor/1-app/README.md, examples/dll-app-and-vendor/1-app/example.html
=> Fix DLL example

lib/web/JsonpMainTemplatePlugin.js
Refactoring 
N/A
N/A
**Summary**
Update the calls in JsonpMainTemplatePlugin to use `.tap` instead of `.plugin`
Nope. 
=> feat(tapable): convert JsonpMainTemplatePlugin to use .tap

test/CachePlugin.unittest.js, test/SourceMapDevToolModuleOptionsPlugin.unittest.js
Cleanup: don't check plugins for apply function in tests, schema does the check for this.
It is tested in the validate options schema
**Summary**
Don't do redundant test checks
=> Don't check plugins for apply function in tests, schema does the check for this.

benchmark/benchmark.js, benchmark/createBenchmark.js, benchmark/createBenchmark/loadLoader.js, benchmark/createFixtures.js, benchmark/createFixtures2.js, benchmark/createTestCases.js
Refactor
**Summary**
Couple of files were not in-line with the others
Next branch doesnt have these refactored as well so i targeted `master`
=> refactor(es6): benchmark directory

lib/Compilation.js, yarn.lock
I replaced some let by const, removed some unecessary this bindings, rewrote the part with self by this with paying attention to keep the binding to this.
refactoring
Nope.
Even if it is minor refactoring ? Actuals tests shouldn't suffice ?
**Summary**
I'm planning to create a plugin, so I start reading the source code, and I found some minor refactoring possibilities that I did in the meantime
Nope !
=> Refresh code of Compilation.js

README.md
Added Awesome Typescript Loader to Readme :blush:
=> Added Awesome Typescript Loader to Readme

lib/NormalModuleFactory.js, test/Compiler.test.js, test/Stats.test.js, test/configCases/loaders/pre-post-loader/a.js, test/configCases/loaders/pre-post-loader/index.js, test/configCases/loaders/pre-post-loader/loader1.js, test/configCases/loaders/pre-post-loader/loader2.js, test/configCases/loaders/pre-post-loader/loader3.js, test/configCases/loaders/pre-post-loader/webpack.config.js
add more test cases
bugfix
yes
TODO
**Summary**
yes
=> `-!` keeps post loader instead of pre loader

test/Compiler.test.js
=> add test case for no emit in watch mode

lib/NormalModule.js
refactoring
no
n/a
**Summary**
Change arguments of `resolve` to remove a deprecation notice.
no
=> Fix Resolver#resolve deprecated call

CONTRIBUTING.md
**HERE:**
**added doc
see the end of
https://github.com/webpack/webpack/issues/6163**
not needed for doc
**Summary**
added doc
see the end of
https://github.com/webpack/webpack/issues/6163
=> Addition of documentation for CONTRIBUTING.md/Discussions

lib/HotModuleReplacementPlugin.js, test/configCases/loaders/hot-in-context/index.js, test/configCases/loaders/hot-in-context/loader.js, test/configCases/loaders/hot-in-context/webpack.config.js
feature
yes
TODO
**Summary**
fixes #5891
no
=> add `this.hot` flag to loader context

bin/webpack.js, package.json, yarn.lock
=> remove webpack-cli dependency

yarn.lock
deps
existing tests
n/a
**Summary**
no
=> update lockfile to latest compatible version

lib/BasicEvaluatedExpression.js, lib/Parser.js
refactoring
no
n/a
**Summary**
- Reduce polymorphic calls of `Parser` and `BasicEvaluatedExpression`
- Replace some closures by `for of` loops to limit GC
no
EDIT (sokra): yes, `BasicExpression.setXXX(null)` is no longer supported
The following changes speed up my builds from 5%.
=> Improve parser performances

lib/NoEmitOnErrorsPlugin.js, lib/Stats.js, test/README.md, test/Stats.unittest.js, test/StatsTestCases.test.js, test/binCases/errors/child-compilation-error/test.js, test/binCases/errors/child-compilation-error/webpack.config.js, test/statsCases/no-emit-on-errors-plugin-with-child-error/TestChildCompilationFailurePlugin.js, test/statsCases/no-emit-on-errors-plugin-with-child-error/expected.txt, test/statsCases/no-emit-on-errors-plugin-with-child-error/webpack.config.js
Currently `Stats.prototype.hasErrors()` and `Stats.prototype.hasWarnings()` will not check for errors in `compilation.children`.  If an error exists there, webpack will erroneously exit with status 0.
I am not sure if this is the preferred way to fix this, or if there is a better way to propagate the errors from the children into the parent compilation.  For instance, I don't think this will effect `NoEmitOnErrorsPlugin` behavior, but perhaps it should 🤔.  This at least appears to fix the exit code.
/cc @sokra @TheLarkInn @jschatz1
closes: #6174
=> Fix issue in which webpack exits with code 0 when errors exist in child compilations

lib/SourceMapDevToolPlugin.js
Displaying progress for SourceMapDevToolPlugin
Not yet
**Summary**
Fixes #6063 
No
=> Feature: SourceMapDevToolPlugin progress: wip

lib/optimize/RemoveParentModulesPlugin.js
refactoring
no
n/a
**Summary**
Using an iterative solution results in fewer memory used and better perf (~5% on my build). Since I don't have a repository with a lot of chunks, I can't run a stress test as described in #6248.
no
=> Optimize chunk traversal in RemoveParentModulesPlugin

lib/optimize/ConcatenatedModule.js, test/cases/json/import-by-name-with-concatenation/index.js, test/cases/json/import-with-default-with-concatenation/index.js, test/statsCases/parse-error/expected.txt
bugfix
yes
n/a
**Summary**
fix a bug with json modules in concatenated modules
no
=> fix a bug with json modules in concatenated modules

lib/ContextModule.js, lib/dependencies/WebpackMissingModule.js, test/WebpackMissingModule.unittest.js
refactoring
**Summary**
The small refactoring. It fixes duplicated semicolons in bundled files and slightly improves build performance.
No
=> Remove extra semicolons

.gitignore
bug
no
n/a
**Summary**
When running test cases `examples/*/js` directories are not always removed.
no
=> Ignore generated JS files examples/

test/ConfigTestCases.test.js, test/configCases/errors/multi-entry-missing-module/index.js
CI
yes
n/a
**Summary**
faster CI builds
no
=> disable minimizer for config test cases

lib/Parser.js
bugfix
no
n/a
**Summary**
The parser was creating hooks instead of reading them.
no
=> Fix parser hook retrieval

lib/util/Queue.js
performance bugfix
existing tests
n/a
**Summary**
Use nice SetIterator trick
no
=> ensure that items are not enqueued twice

.gitignore, test/Examples.test.js
examples, test
n/a
n/a
**Summary**
no
=> Examples write to dist

lib/optimize/CommonsChunkPlugin.js
=> feat: CommonsChunkPlugin indexOf -> includes

lib/Compilation.js, lib/FlagInitialModulesAsUsedPlugin.js, lib/HotModuleReplacementPlugin.js, lib/MultiCompiler.js, lib/RecordIdsPlugin.js, lib/Template.js, lib/optimize/CommonsChunkPlugin.js, lib/optimize/EnsureChunkConditionsPlugin.js
refactoring
no
n/a
**Summary**
Use `Map` or `Set` to replace `{}` in order to reduce polymorphism. 
no
=> Replace dictionaries by Map or Set

lib/BannerPlugin.js
refactoring
**Summary**
Remove needless `indexOf`
No
=> Minor optimize banner plugin

lib/NormalModuleFactory.js, lib/performance/SizeLimitsPlugin.js
Refactoring
**Summary**
Removed regexp if it possible. Used simple string compare instead.
Optimized `getEntrypointSize`. Used 1 `reduce` instead of long chains `filter-map-filter-map-reduce`.
No
=> Optimize regexp, getEntryPointsSize

test/statsCases/no-emit-on-errors-plugin-with-child-error/TestChildCompilationFailurePlugin.js
refactoring
no
n/a
**Summary**
Newly committed tests were not using `Tapable`.
no
=> Use tapable in Stat test cases

lib/Compilation.js, lib/HotModuleReplacementPlugin.js
refactoring
no
n/a
**Summary**
Replace `applyPlugins` by a hook call and deprecate it.
no
=> Use hooks instead of applyPlugins

lib/Chunk.js, test/Chunk.unittest.js, test/statsCases/async-commons-chunk-auto/expected.txt, test/statsCases/optimize-chunks/expected.txt, test/statsCases/scope-hoisting-multi/expected.txt, test/statsCases/split-chunks/expected.txt
**Summary**
Typo in `getNumberOfGroups`, leading to always return `undefined`
-  [x] No
=> fix(lib/Chunk): typo in `getNumberOfGroups` return value

lib/optimize/RuntimeChunkPlugin.js, lib/optimize/SplitChunksPlugin.js
=> run splitChunks and runtimeChunk only on main compiliation

lib/JavascriptGenerator.js, lib/JavascriptModulesPlugin.js, lib/JsonGenerator.js, lib/JsonModulesPlugin.js, lib/NormalModule.js, lib/NormalModuleFactory.js, lib/WebAssemblyGenerator.js, lib/WebAssemblyModulesPlugin.js, test/NormalModule.unittest.js
refactoring
existing tests
N/A
**Summary**
move source generation into separate module
allow to pass a Generator to NormalModule
change NormalModule constructor to options object
yes
cc @michael-ciniawsky
=> move source generation into separate module

README.md
Change to README.md
n/a
n/a
**Summary**
Previous link encourages users to use an unmaintained loader for polymer elements instead of a loader that is currently being maintained.
No
n/a
=> change polymer loader link

lib/ConstPlugin.js
Refactoring
No
n/a
**Summary**
Minor optimization
No
=> Remove needless includes

lib/EvalDevToolModuleTemplatePlugin.js, lib/EvalSourceMapDevToolModuleTemplatePlugin.js, lib/ModuleFilenameHelpers.js, lib/SourceMapDevToolPlugin.js, test/statsCases/chunks-development/expected.txt, test/statsCases/preset-normal-performance-ensure-filter-sourcemaps/expected.txt, test/statsCases/simple/expected.txt
feature removing
Not added, but modified
N/A
**Summary**
There wasn't good use case to include a footer in source maps, and it didn't work properly with some development tools (e.g. Chrome Devtools).
As far as I know, there weren't tools which used this feature, so it's not a breaking change.
=> Remove footer from source maps and eval

lib/optimize/SplitChunksPlugin.js, test/statsCases/async-commons-chunk-auto/expected.txt, test/statsCases/split-chunks-issue-6413/a.js, test/statsCases/split-chunks-issue-6413/b.js, test/statsCases/split-chunks-issue-6413/c.js, test/statsCases/split-chunks-issue-6413/common.js, test/statsCases/split-chunks-issue-6413/expected.txt, test/statsCases/split-chunks-issue-6413/index.js, test/statsCases/split-chunks-issue-6413/node_modules/x.js, test/statsCases/split-chunks-issue-6413/webpack.config.js, test/statsCases/split-chunks/expected.txt
=> fixes #6413

test/HotTestCases.test.js
bugfix
no
n/a
**Summary**
Timeout wasn't applied to dynamic tests resulting in random failures on the CI.
no
=> Set Hot test cases timeout to 5s

lib/Entrypoint.js
Refactoring
No
N/A
**Summary**
Used `for of` instead of classic `for`
No
=> Simplify for loop in EntryPoint.getFiles

lib/WebpackOptionsDefaulter.js
=> Revert "Wrap default entry property in array"

lib/RuntimeTemplate.js, lib/dependencies/HarmonyImportSpecifierDependency.js, test/cases/errors/crash-missing-import/a.js, test/cases/errors/crash-missing-import/errors.js, test/cases/errors/crash-missing-import/index.js
=> fix a crash with buildMeta of null

lib/WebpackOptionsApply.js, lib/WebpackOptionsDefaulter.js, schemas/WebpackOptions.json, test/TestCases.test.js
bugfix, typo
no
n/a
**Summary**
yes
=> fix typo: mergedDuplicateChunks -> mergeDuplicateChunks

.github/ISSUE_TEMPLATE.md
😲 
Typo
No
No
https://www.nytimes.com/2018/02/09/us/oxford-comma-maine.html
=> Added missing Serial Comma to issue template

lib/WebpackOptionsDefaulter.js, lib/optimize/SplitChunksPlugin.js, schemas/WebpackOptions.json, test/statsCases/async-commons-chunk-auto/expected.txt, test/statsCases/split-chunks-combinations/a.js, test/statsCases/split-chunks-combinations/b.js, test/statsCases/split-chunks-combinations/c.js, test/statsCases/split-chunks-combinations/d.js, test/statsCases/split-chunks-combinations/e.js, test/statsCases/split-chunks-combinations/expected.txt, test/statsCases/split-chunks-combinations/f.js, test/statsCases/split-chunks-combinations/index.js, test/statsCases/split-chunks-combinations/webpack.config.js, test/statsCases/split-chunks-prefer-bigger-splits/a.js, test/statsCases/split-chunks-prefer-bigger-splits/b.js, test/statsCases/split-chunks-prefer-bigger-splits/c.js, test/statsCases/split-chunks-prefer-bigger-splits/d.js, test/statsCases/split-chunks-prefer-bigger-splits/e.js, test/statsCases/split-chunks-prefer-bigger-splits/expected.txt, test/statsCases/split-chunks-prefer-bigger-splits/f.js, test/statsCases/split-chunks-prefer-bigger-splits/index.js, test/statsCases/split-chunks-prefer-bigger-splits/webpack.config.js, test/statsCases/split-chunks/expected.txt
bugfix
yes
n/a
**Summary**
improve chunk splitting by also trying to select combinations of module chunks
(limited by complexity)
fix size ordering (was reversed)
add chunk cound ordering
maybe a small one
=> improve chunk splitting

lib/Stats.js, lib/WebpackOptionsDefaulter.js, lib/optimize/SplitChunksPlugin.js, lib/util/SetHelpers.js, schemas/WebpackOptions.json, test/statsCases/aggressive-splitting-entry/expected.txt, test/statsCases/aggressive-splitting-on-demand/expected.txt, test/statsCases/async-commons-chunk-auto/expected.txt, test/statsCases/async-commons-chunk/expected.txt, test/statsCases/limit-chunk-count-plugin/expected.txt, test/statsCases/module-deduplication/expected.txt, test/statsCases/optimize-chunks/expected.txt, test/statsCases/split-chunks-combinations/a.js, test/statsCases/split-chunks-combinations/b.js, test/statsCases/split-chunks-combinations/c.js, test/statsCases/split-chunks-combinations/d.js, test/statsCases/split-chunks-combinations/e.js, test/statsCases/split-chunks-combinations/expected.txt, test/statsCases/split-chunks-combinations/f.js, test/statsCases/split-chunks-combinations/g.js, test/statsCases/split-chunks-combinations/index.js, test/statsCases/split-chunks-combinations/webpack.config.js, test/statsCases/split-chunks-combinations/x.js, test/statsCases/split-chunks-combinations/y.js, test/statsCases/split-chunks-issue-6413/expected.txt, test/statsCases/split-chunks-prefer-bigger-splits/expected.txt, test/statsCases/split-chunks/expected.txt
performance
yes
n/a
**Summary**
sort parents, children, siblings in stats 
improve way of getting combinations of chunks 
no
=> improve performance of chunk splitting combinations

test/TestCases.test.js
=> Use non-parallel minimizer for testing to make CI more stable

CONTRIBUTING.md
Fix typo
No
N / A
**Summary**
- Made "gitters" singular
- Reworded the "Discussions" section.
No
N / A
=> Fix typo and rewrite a sentence

open-bot.yaml
bot
no
n/a
**Summary**
Label "send a PR" issues
no
=> Label "send a PR" issues

package.json, yarn.lock
**Summary**
Same as https://github.com/webpack/webpack/pull/6533, ~~just launching the tests.~~ just noticed that tests are already on master.
=> Use wasm-dce to tree shake WASM - bump wasm-dce

schemas/plugins/BannerPlugin.json, schemas/plugins/DllPlugin.json, schemas/plugins/DllReferencePlugin.json, schemas/plugins/HashedModuleIdsPlugin.json, schemas/plugins/LoaderOptionsPlugin.json, schemas/plugins/SourceMapDevToolPlugin.json, schemas/plugins/WatchIgnorePlugin.json, schemas/plugins/debug/ProfilingPlugin.json, schemas/plugins/optimize/AggressiveSplittingPlugin.json, schemas/plugins/optimize/LimitChunkCountPlugin.json, schemas/plugins/optimize/MinChunkSizePlugin.json
**Summary**
Remove `ajv >= v3.0.0` (JSON Schema Draft 7) warnings about ignored schema id's
- Fixes #6499
=> fix(schemas/plugins): rm unnecessary `id`'s

schemas/WebpackOptions.json
bugfix
no
n/a
**Summary**
#6426
no
=> allow name: false for splitChunks

open-bot.yaml
=> only set labels for reviews by users with write permission

package.json, yarn.lock
dependencies
existing tests
N/A
**Summary**
yes
=> upgrade versions to stable versions

CONTRIBUTING.md
and fix case of Github to GitHub.
**Summary**
=> Add a hyperlink to create a new issue

examples/multiple-entry-points/README.md, examples/multiple-entry-points/template.md
Changed multiple-entry-points and changed unoptimized mode to development and re-build readme files..
**Summary**
Fixes #6528 
No
=> Fixed template.md and build-common.js

lib/Parser.js, test/Parser.unittest.js, test/cases/parsing/spread/a.js, test/cases/parsing/spread/index.js, test/cases/parsing/spread/module.js, test/cases/parsing/spread/test.filter.js, test/helpers/supportsSpread.js, yarn.lock
feature
yes
n/a
**Summary**
Update the `Parser` to suport ES2018 new features.
no
=> Update parser to support ES 2018

lib/Compilation.js
performance
N/A
N/A
**Summary**
refactor algorithm and use Set
no
=> optimize performance of assignDepth

lib/ContextModule.js, lib/RuntimeTemplate.js, test/cases/mjs/non-mjs-namespace-object-lazy/index.js, test/statsCases/aggressive-splitting-entry/expected.txt, test/statsCases/import-weak/expected.txt, test/statsCases/limit-chunk-count-plugin/expected.txt, test/statsCases/named-chunks-plugin-async/expected.txt
#6576
bugfix
yes
N/A
**Summary**
no
=> CJS fake namespace object contains exports now

lib/webpack.js
Feature : - Exports a version property in webpack
Not required, I guess
**Summary**
Fixes #6573 
No
Extract version from package.json and use it.
=> Added version to webpack's export property

lib/Parser.js, test/configCases/plugins/provide-plugin/index.js, test/configCases/plugins/provide-plugin/webpack.config.js
BugFix
Yes
N/A
**Summary**
Fixes #6526 
No
Now this expression have free property according to whether they are top level or not.
=> Fixed Parser so that this Expression can work with ProvidePlugin

lib/WebpackOptionsValidationError.js, test/Validation.test.js
bugfix
No, just edited already existing test.
**Summary**
It should fix #6605
No
=> Make error messages better

lib/WebAssemblyParser.js, package.json, yarn.lock
**Summary**
Updated to the major release.
Note that the project as been renamed to `webassemblyjs`, could you please rename the title of the PR?
=> refactor: use webassemblyjs tools

lib/JavascriptModulesPlugin.js, lib/webpack.js
feature
no
N/A
**Summary**
to allow to create non-bundle affecting modules
no
=> expose stuff and all non-bundle modules

package.json, yarn.lock
bugfix
no
n/a
**Summary**
`watchpack@1.5.0` ships fixes for macOS.
no
Fix #6550
=> Update watchpack to 1.5.0

test/Examples.test.js, test/HotTestCases.test.js
=> larger timeouts to make CI more stable

README.md
doc
no
n/a
**Summary**
Remove `CommonsChunkPlugin` link from `README`.
no
fix #6676
=> Remove CommonsChunkPlugin link

lib/node/NodeMainTemplatePlugin.js, test/configCases/async-commons-chunk/node/index.js, test/configCases/async-commons-chunk/node/modules/a.js, test/configCases/async-commons-chunk/node/modules/b.js, test/configCases/async-commons-chunk/node/modules/c.js, test/configCases/async-commons-chunk/node/webpack.config.js
bugfix
yes
n/a
**Summary**
fix #6681 
no
=> Escape chunk names on node

.eslintrc.js, test/.eslintrc.js
Build related change.
Not needed, build should still pass.
**Summary**
Only declare mocha environment inside test directory, for greater safety.
No.
=> Only declare mocha globals inside  dir

lib/HotModuleReplacement.runtime.js
a fix for #6733 reverting to ES5 in runtime code
=> reverting the HMR plugin runtime to use ES5

.editorconfig
".editorconfig" file simplified.
=> .editorconfig file simplified

lib/web/JsonpMainTemplatePlugin.js, test/statsCases/module-deduplication-named/expected.txt
refactoring
No
**Summary**
refactoring.
I tried to use webpack with [Google Apps Script](https://developers.google.com/apps-script/).
But, following error occurred on Google Apps Script .
```
Missing ; before statement.
```
No
=> Add end of statement semicolon

lib/WebpackOptionsDefaulter.js, test/configCases/target/electron-renderer/index.js, test/configCases/target/electron-renderer/node_modules/foo/browser.js, test/configCases/target/electron-renderer/node_modules/foo/main.js, test/configCases/target/electron-renderer/node_modules/foo/package.json, test/configCases/target/electron-renderer/webpack.config.js
bugfix
yes
n/a
**Summary**
Fixes #6811
no
=> Read 'browser' main field when target is 'electron-renderer'

lib/Chunk.js, lib/Compilation.js, lib/JavascriptModulesPlugin.js, lib/SourceMapDevToolPlugin.js, lib/TemplatedPathPlugin.js, lib/node/NodeMainTemplatePlugin.js, lib/web/JsonpMainTemplatePlugin.js, lib/webpack.js, lib/webworker/WebWorkerMainTemplatePlugin.js, test/ConfigTestCases.test.js, test/configCases/hash-length/output-filename/no-async.js, test/configCases/hash-length/output-filename/test.config.js, test/configCases/hash-length/output-filename/webpack.config.js
feature
a bit
TODO
**Summary**
add [contenthash] support
no
=> add [contenthash] support

CONTRIBUTING.md, _SETUP.md
Information on how to setup the local webpack repository was extracted into a separate `_SETUP.md` file.
A reference was added from the old location in `CONTRIBUTING.md`
No, because changes made only to .md file.
N/A 
**Summary**
Increase the visiblity of "How to correctly setup local webpack repository for testing".
Especially for people starting to contribute to webpack.
Bootstrap logic will be implemented in another PR, to prevent the need for a manual setup.
[Open issue](https://github.com/webpack/webpack/issues/6830)
No
=> Extracts setup instructions from Contributing.md into separate _Setup.md

lib/Module.js
Part of https://github.com/webpack/webpack/pull/6862
=> Initialize useSourceMap in Module

lib/Compiler.js
refactoring
n/a
no
**Summary**
As part of https://github.com/webpack/webpack/pull/6862 I'm fixing issues raised by TypeScript 
=> Remove extra argument passed to ContextModuleFactory in Compiler

lib/WebAssemblyParser.js
refactoring
no
no
**Summary**
As part of https://github.com/webpack/webpack/pull/6862 I'm proposing fixes to issues TypeScript compiler have found 
no
=> Remove extra argument from WebAssemblyImportDependency constructor call site

lib/optimize/SplitChunksPlugin.js, schemas/WebpackOptions.json, test/statsCases/split-chunks/expected.txt, test/statsCases/split-chunks/webpack.config.js
Feature
Yes
TODO, want to get some feedback first
**Summary**
This allowing picking particular chunks to be split, see #6717
No
=> Support selector function as optimization.splitChunks.chunks option

bin/webpack.js
bugfix
yes, manually
n/a
**Summary**
use shell mode for windows support
no
=> use shell mode for windows support

.eslintrc.js, buildin/.eslintrc, hot/.eslintrc, test/.eslintrc.js
Refactoring/cleanup.
Not needed.
N/A
**Summary**
Consolidate config in one file. Remove unneeded config in `hot` directory. Avoid using `.eslintrc` deprecated file format.
No
=> Consolidate eslint config

.gitignore, .npmrc
package-lock.json added to .gitignore
no
**Summary**
package-lock.json added to .gitignore
[Open issue](https://github.com/webpack/webpack/issues/6926)
no
=> package-lock.json added to .gitignore

lib/optimize/ConcatenatedModule.js, test/cases/scope-hoisting/renaming-4967/file1.js
performance
existing tests
n/a
**Summary**
avoid walking scopes multiple times for performance reasons
no
=> avoid walking scopes multiple times for performance reasons

lib/FunctionModulePlugin.js, lib/WebpackOptionsApply.js, lib/dependencies/HarmonyImportDependency.js, lib/dependencies/HarmonyImportSpecifierDependency.js, lib/dependencies/RequireEnsureDependenciesBlockParserPlugin.js
refactoring
no
n/a
**Summary**
Pass the correct number of arguments on plugins.
no
=> Use correct function arity

lib/Compilation.js, test/statsCases/aggressive-splitting-on-demand/expected.txt
bugfix
TODO
**Summary**
sort child compilations for consitent hash
fixes webpack-contrib/mini-css-extract-plugin#75
no
=> sort child compilations for consitent hash

lib/webworker/WebWorkerMainTemplatePlugin.js
=> #6971: Escape chunk names for webworkers

README.md
Saw this being used elsewhere, so updating here for consistency.
README copy update
=> Use Oxford comma

lib/Parser.js, test/configCases/parsing/harmony-this/abc.js, test/configCases/parsing/harmony-this/index.js
bugfix
yes
n/a
**Summary**
Scope depth was not correctly handled resulting in `this` being replaced by `undefined` when it should not.
no
fixes #6379
fixes #6967
=> Fix 'this' replacement for harmony modules

README.md
Just changing to reflect the current situation.
Bugfix.
Not needed.
**Summary**
Changing to reflect the current situation.
No.
=> Drop core team member

.istanbul.yml
Excludes files that aren't really part of code coverage from Istanbul instrumentatio
No.
**Summary**
https://github.com/webpack/webpack/pull/6487 has code coverage calculated as decreasing. Unfortunate.
No.
=> Excluded root-level files and .github from Istanbul

lib/Parser.js, lib/RuleSet.js, lib/dependencies/getFunctionExpression.js
refactoring
no
N/A
**Summary**
Reduce polymorphism by always returning objects with the same shape.
no
=> Always return object with the same shape to avoid polymorphism

lib/Compilation.js
refactoring
no
N/A
**Summary**
Since this code uses arrow functions, we don't need `_this` binding.
Moreover, it raises an error on TS compiler.
no
=> Remove unnecessary _this binding

lib/dependencies/AMDDefineDependency.js, lib/dependencies/AMDRequireDependenciesBlock.js
refactoring
no
N/A
**Summary**
Avoid potential deopt / polymorphism.
no
=> Define missing fields on AMD classes

lib/Stats.js, lib/WebpackOptionsValidationError.js
Refactor 
No
N/A
**Summary**
As part of https://github.com/webpack/webpack/pull/6862 I'm fixing issues that TypeScript has found. 
No
=> JSON and Date API usage fixes

lib/HotModuleReplacementPlugin.js
Refactor 
No
N/A
**Summary**
As part of #6862 I'm refactoring this for..in statement to be easier for TypeScript to understand. 
No
No reassigning numbers to strings is good for VMs expectations as well.
=> Avoid type mismatch assignment of number to string in HotModuleReplacementPlugin

lib/RuntimeTemplate.js
This expression always evaluates to true.
**Summary**
no
no
=> chore: rm useless checking

lib/dependencies/LoaderPlugin.js, lib/util/Semaphore.js, test/configCases/race-conditions/load-module/index.js, test/configCases/race-conditions/load-module/loader.js, test/configCases/race-conditions/load-module/module.js, test/configCases/race-conditions/load-module/webpack.config.js
bugfix
yes
n/a
**Summary**
fix race condition when using loadModule
change Semaphore to continue prefer acquire in the same tick
fixes #6836
fixes #6902
no
Original PR by @yakotika but branch was deleted
=> fix race condition when using loadModule

test/cases/parsing/comment-in-import/index.js
test
yes
N/A
**Summary**
random comments in import() should be allowed
no
=> add test case for comments in import()

lib/SizeFormatHelpers.js, test/SizeFormatHelpers.unittest.js
Avoids having `NaN undefined` in the chunk size.
before:
```
Hash: a767d25c0ab9f6137502
Version: webpack 4.3.0
Time: 351ms
Built at: 3/29/2018 2:57:47 PM
Asset           Size  Chunks             Chunk Names
bundle.js       6.33 KiB    main  [emitted]  main
0.bundle.js      462 bytes       0  [emitted]
c0a8be7a5c1867a7212e.module.wasm  NaN undefined       0  [emitted]
index.html      182 bytes          [emitted]
Entrypoint main = bundle.js
[./src/index.js] 90 bytes {main} [built]
[./src/test.wasm] 71 bytes {0} [built]
Child html-webpack-plugin for "index.html":
1 asset
Entrypoint undefined = index.html
[../../buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
+ 2 hidden modules
```
after:
```
Hash: 6d167786e870e3758cab …
```
=> SizeFormatHelpers: defend against invalid sizes

lib/Chunk.js, test/ConfigTestCases.test.js, test/configCases/split-chunks/runtime-chunk/a.js, test/configCases/split-chunks/runtime-chunk/b.js, test/configCases/split-chunks/runtime-chunk/test.config.js, test/configCases/split-chunks/runtime-chunk/webpack.config.js, test/helpers/FakeDocument.js
bugfix
yes
N/A
**Summary**
fixes #6931
no
=> fix bug which prevented some chunks to show up in Chunk.getAllAsyncChunks

lib/util/Queue.js
refactoring, typing
no
n/a
**Summary**
Add complete typing for `Queue`.
no
There is an issue with generics.
=> Add Queue typing

lib/util/identifier.js
Refactoring
N/A
N/A
**Summary**
This adds type support for util/identifier.js
No
=> refactor(types): add type comments for util/identifier

package.json, yarn.lock
Typing JSDocs
N/A
N/A
**Summary**
Update's the TS Nightly version to support `import()` types instead of mocking `typeofs` 
No
Unblocks #7031
=> chore(deps): update typescript nightly

SECURITY.md, package.json
docs
not required
not required
**Summary**
fixes #4599
no
=> docs: add `SECURITY.md`

declarations.d.ts, lib/Stats.js, lib/WebpackOptionsApply.js, lib/optimize/SplitChunksPlugin.js, test/Chunk.unittest.js, test/NullDependency.unittest.js, test/SourceMapDevToolModuleOptionsPlugin.unittest.js, yarn.lock
dependencies
existing tests
N/A
**Summary**
no
=> Upgrade dependencies in range

package.json, yarn.lock
Correctly handle custom sections
cc @sendilkumarn 
**Summary**
=> chore: bump webassemblyjs

.travis.yml
CI
Existing tests
N/A
**Summary**
No
=> Test with node.js 10

.travis.yml, appveyor.yml
=> disable gcov generation as it loops in the symlinks

lib/util/SetHelpers.js
Add JSDOC Typing
N/A
N/A
**Summary**
Add's type support via JSDOC's for SetHelpers. To make typing support a bit easier.
Nope
=> chore(types): add type support for SetHelpers

lib/Entrypoint.js
Typing JSDocs
N/A
N/A
**Summary**
This adds type support for Entrypoint Class including descriptions and memberof. 
No
=> types(entrypoint): add typeing support for Entrypoint

lib/NormalModule.js, test/NormalModule.unittest.js, test/__snapshots__/StatsTestCases.test.js.snap
performance
existing tests
**Summary**
cache source and meta hash
no
=> improve NormalModule performance

package.json, yarn.lock
Chore - Deps
N/A
N/A
**Summary**
This PR updates the nightly TypeScript version from last night. This allows us to properly define typedefs using object and properties. All fixes relevant to motivation can be found here: microsoft/typescript#23715
No
=> chore(deps): upgrade TS nightly, fixes from microsoft/typescript#23715

lib/Chunk.js, lib/util/SortableSet.js
Refactoring, Type Annotations
N/A
N/A
N/A
**Summary**
This adds more (but not complete) typing to Chunk.js. 
Chunk is one of many base Types that could value from being completely typed and referenced in other modules, etc. It is also heavily used across plugins in our ecosystem, and having these annotations will assist in authoring of plugins and other integrations. 
No
Also helped discover the following TypeScript bugs: 
- https://github.com/Microsoft/TypeScript/issues/23375
- https://github.com/Microsoft/TypeScript/issues/23384
- https://github.com/Microsoft/TypeScript/issues/23385
=> feat(chunk): add chunk typing support

.travis.yml, appveyor.yml
=> also run node.js 6 CI in worker pool

package.json
CI
yes
**Summary**
try to avoid hanging
no
=> add forceExit to jest config

lib/web/JsonpMainTemplatePlugin.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/split-chunks/runtime-chunk-no-async/index.js, test/configCases/split-chunks/runtime-chunk-no-async/test.config.js, test/configCases/split-chunks/runtime-chunk-no-async/webpack.config.js
bugfix
yes
N/A
**Summary**
fixes #7185
no
=> avoid injection jsonpScriptSrc function when not needed

lib/wasm/WasmMainTemplatePlugin.js, lib/wasm/WebAssemblyGenerator.js, lib/wasm/WebAssemblyJavascriptGenerator.js, package.json, test/cases/wasm/decoding/index.js, test/cases/wasm/table/index.js, yarn.lock
=> Few wasm fixes

lib/wasm/WebAssemblyGenerator.js, test/cases/wasm/table/index.js
**Summary**
The index in the export instruction was wrong.
=> Fix wasm transformation

lib/optimize/SplitChunksPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap
bugfix
existing tests
N/A
**Summary**
no
=> fix bug where splitChunks doesn't work

_SETUP.md
Docs/Readme's
N/A
N/A
**Summary**
This adds how to run the typechecker in the setup.md guide. 
Nope, just happy typecheckers
I love lamp.
=> docs(setup): add type checker commands on setup guide

package.json, yarn.lock
Build/Deps
N/A
N/A
**Summary**
Update nightly version of TypeScript, check if any errors. Add's fixes that are super valuable for typedefs like: https://github.com/Microsoft/TypeScript/issues/23692
N/A
=> chore(deps): ugrade nightly typescript version

package.json, yarn.lock
**Summary**
Closes https://github.com/webpack/webpack/issues/7229
=> bump webassemblyjs - license change

test/lint-mocha.opts, test/mocha.opts
cleaning
N/A
N/A
**Summary**
Some mocha related files were left after the jest migration.
This PR removes them.
no
=> Delete unused mocha config files

lib/Parser.js, test/configCases/parsing/harmony-this/index.js, test/configCases/parsing/harmony-this/issue-7213.js
bugfix
yes
N/A 
**Summary**
Top-level `this` detection was failing for IIFE.
Fix #7213 
no
=> Fix edge case when parsing top-level this on IIFE

.gitignore, package.json
dev performance
N/A
N/A
**Summary**
no
=> enable eslint caching

package.json, yarn.lock
Deps
N/A
N/A
**Summary**
This updates the typescript nightly build which adds multiple valuable fixes and enhancements for us like @callback support (microsoft/typescript#7515)
No.
=> chore(deps): upgrade typescript nightly

package.json, yarn.lock
**Summary**
Closes https://github.com/webpack/webpack/issues/7258
=> bump webassemblyjs

lib/optimize/RemoveEmptyChunksPlugin.js
refactoring
**Summary**
Optimized remove empty chunks. Previous solution used bad complexity (because indexOf in each iteration).
Simplified it with use 1 simple `for loop`.
No
=> Optimize RemoveEmptyChunksPlugin

bin/webpack.js, declarations.d.ts
feature
looks not required
not required
**Summary**
Allow install `webpack-command`
no
https://github.com/webpack-contrib/webpack-command
=> feat(cli): support `webpack-command`

declarations.d.ts, lib/wasm/WebAssemblyGenerator.js, package.json, yarn.lock
Addresses comments in https://github.com/webpack/webpack/pull/7275
=> bump webassembly and few fixes

lib/optimize/SplitChunksPlugin.js, test/ConfigTestCases.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/split-chunks/webpack.config.js
=> update combination when split fails because of max requests

examples/many-pages/README.md, examples/many-pages/build.js, examples/many-pages/node_modules/m1.js, examples/many-pages/node_modules/m2.js, examples/many-pages/node_modules/m3.js, examples/many-pages/node_modules/m4.js, examples/many-pages/node_modules/m5.js, examples/many-pages/node_modules/m6.js, examples/many-pages/node_modules/m7.js, examples/many-pages/node_modules/m8.js, examples/many-pages/pages/a.js, examples/many-pages/pages/b.js, examples/many-pages/pages/c.js, examples/many-pages/pages/d.js, examples/many-pages/pages/e.js, examples/many-pages/pages/f.js, examples/many-pages/pages/g.js, examples/many-pages/stuff/s1.js, examples/many-pages/stuff/s2.js, examples/many-pages/stuff/s3.js, examples/many-pages/stuff/s4.js, examples/many-pages/stuff/s5.js, examples/many-pages/stuff/s6.js, examples/many-pages/stuff/s7.js, examples/many-pages/stuff/s8.js, examples/many-pages/template.md, examples/many-pages/webpack.config.js
example
N/A
no
This example could be linked from the documentation page for optimization.splitChunks
=> add split chunks example

package.json, yarn.lock
This add's the newest TypeScript nightly. This add's a LOT of `@template` and `@callback` based bug fixes and enhancements
Chore/Deps
N/A
No
Nothing
=> chore(deps): update to latest typescript nightly

lib/compareLocations.js
=> Type compare locations

lib/ChunkRenderError.js
Typing for `ChunkRenderError`
yes
no
no
=> Add typing for ChunkRenderError

lib/Compilation.js, test/__snapshots__/StatsTestCases.test.js.snap, test/cases/chunks/import-circle/index.js, test/cases/chunks/import-circle/leftHelix.js, test/cases/chunks/import-circle/leftHelixPrime.js, test/cases/chunks/import-circle/rightHelix.js, test/cases/chunks/import-circle/rightHelixPrime.js
fixes #7363
fixes #7239
fixes #6587
bugfix
yes
no
nothing
=> fix problems with circular unneeded chunks

.travis.yml, appveyor.yml, package.json
=> speed up CI

lib/optimize/RuntimeChunkPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/runtime-chunk-issue-7382/e1.js, test/statsCases/runtime-chunk-issue-7382/e2.js, test/statsCases/runtime-chunk-issue-7382/webpack.config.js
fixes #7382
bugfix
yes
no
nothing
=> fix runtimeChunk generation in splitChunk edgecases

lib/RecordIdsPlugin.js, test/configCases/records/stable-sort/test.js, test/configCases/records/stable-sort/webpack.config.js
fixes #7382
bugfix
no
no
nothing
=> only record number ids

lib/Parser.js, test/cases/parsing/issue-7335/a.js, test/cases/parsing/issue-7335/index.js
fixes #7335 
bugfix
yes
no
nothing
=> fix argument TDZ and shadowing

lib/AsyncDependencyToInitialChunkError.js, lib/CaseSensitiveModulesWarning.js, lib/ModuleDependencyError.js, lib/WebpackError.js
JSDocs
N/A
N/A
**Summary**
This adds Types via JSDocs for WebpackError and a few subclasses. 
No, it shouldn't.
There are some adds here for TODO: any which I'd like to land anyways, (and then will shrink the size of some of my larger PR's after rebase.
=> chore(types): add basic type info for a few warning and errors

lib/AmdMainTemplatePlugin.js, lib/ExportPropertyMainTemplatePlugin.js, lib/LibraryTemplatePlugin.js, lib/SetVarMainTemplatePlugin.js, lib/UmdMainTemplatePlugin.js
typings
no
n/a
**Summary**
Add typings for library template plugins
no
=> Add typings for library template plugins

lib/FlagDependencyUsagePlugin.js, lib/RuntimeTemplate.js, lib/dependencies/HarmonyExportImportedSpecifierDependency.js, lib/dependencies/HarmonyImportDependency.js, lib/dependencies/HarmonyImportSideEffectDependency.js, lib/dependencies/HarmonyImportSpecifierDependency.js, lib/optimize/ConcatenatedModule.js, lib/optimize/SideEffectsFlagPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/side-effects-simple-unused/index.js, test/statsCases/side-effects-simple-unused/node_modules/pmodule/a.js, test/statsCases/side-effects-simple-unused/node_modules/pmodule/b.js, test/statsCases/side-effects-simple-unused/node_modules/pmodule/c.js, test/statsCases/side-effects-simple-unused/node_modules/pmodule/index.js, test/statsCases/side-effects-simple-unused/node_modules/pmodule/package.json, test/statsCases/side-effects-simple-unused/webpack.config.js, test/watchCases/side-effects/issue-7400/0/index.js, test/watchCases/side-effects/issue-7400/0/my-module/index.js, test/watchCases/side-effects/issue-7400/0/my-module/myFunction.js, test/watchCases/side-effects/issue-7400/0/my-module/package.json, test/watchCases/side-effects/issue-7400/0/require-me.js, test/watchCases/side-effects/issue-7400/1/index.js, test/watchCases/side-effects/issue-7400/webpack.config.js
fix bug where modules are incorrectly including in chunks
fixes #7400
bugfix
yes
yes, but its a bugfix
nothing
=> SideEffectsPlugin don't modify cache entries

lib/wasm/WasmMainTemplatePlugin.js, test/cases/wasm/imports-many-direct/index.js, test/cases/wasm/imports-many-direct/other1.wat, test/cases/wasm/imports-many-direct/other2.wat, test/cases/wasm/imports-many-direct/test.filter.js, test/cases/wasm/imports-many-direct/wasm.wat, test/cases/wasm/unused-export/index.js, test/cases/wasm/unused-export/module.js, test/cases/wasm/unused-export/test.filter.js, test/cases/wasm/unused-export/wasm.wat
=> fix a code generation bug and add test cases

lib/Stats.js, lib/optimize/ModuleConcatenationPlugin.js, lib/optimize/SideEffectsFlagPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/side-effects-issue-7428/components/package.json, test/statsCases/side-effects-issue-7428/components/src/CompAB/CompA.js, test/statsCases/side-effects-issue-7428/components/src/CompAB/CompB.js, test/statsCases/side-effects-issue-7428/components/src/CompAB/index.js, test/statsCases/side-effects-issue-7428/components/src/CompAB/utils.js, test/statsCases/side-effects-issue-7428/components/src/CompC/CompC.js, test/statsCases/side-effects-issue-7428/components/src/CompC/index.js, test/statsCases/side-effects-issue-7428/components/src/index.js, test/statsCases/side-effects-issue-7428/foo.js, test/statsCases/side-effects-issue-7428/main.js, test/statsCases/side-effects-issue-7428/webpack.config.js
also: show reason explanation in stats
fixes #7428
bugfix
yes
no
nothing
=> fixup reasons when redirecting dependencies for side-effects

declarations.d.ts, lib/ProgressPlugin.js, lib/SourceMapDevToolPlugin.js, package.json, test/BenchmarkTestCases.benchmark.js, test/Compiler-caching.test.js, yarn.lock
=> Update prettier to v1.13

lib/Template.js
=> fix incorrect substraction in numberToIdentifier

.editorconfig
There was a discrepancy between EditorConfig settings Prettier's ones.
tooling
no
no
nothing
=> Use same settings for editorconfig and prettier

lib/optimize/SideEffectsFlagPlugin.js
pref refactoring
no
no
nothing
=> more performant changing of reasons

lib/wasm/WebAssemblyGenerator.js
=> wasm: keep imports

lib/AsyncDependencyToInitialChunkError.js, lib/CaseSensitiveModulesWarning.js, lib/Compilation.js, lib/EntryModuleNotFoundError.js, lib/HarmonyLinkingError.js, lib/ModuleBuildError.js, lib/ModuleDependencyError.js, lib/ModuleDependencyWarning.js, lib/ModuleError.js, lib/ModuleNotFoundError.js, lib/ModuleParseError.js, lib/ModuleWarning.js, lib/ParserHelpers.js, lib/RemovedPluginError.js, lib/Stats.js, lib/UnsupportedFeatureWarning.js, lib/WebpackOptionsValidationError.js, lib/dependencies/AMDRequireDependenciesBlockParserPlugin.js, lib/dependencies/ImportParserPlugin.js, lib/dependencies/SystemPlugin.js, lib/performance/AssetsOverSizeLimitWarning.js, lib/performance/EntrypointsOverSizeLimitWarning.js, lib/performance/NoAsyncChunksWarning.js, lib/wasm/UnsupportedWebAssemblyFeatureError.js, test/ModuleDependencyError.unittest.js, test/Stats.unittest.js, test/__snapshots__/StatsTestCases.test.js.snap, test/cases/parsing/issue-2942/warnings.js
bugfix/cleanup
no
maybe a bugfix
nothing
=> Cleanup error location and origin information

lib/WebpackOptionsApply.js, lib/WebpackOptionsDefaulter.js, lib/node/ReadFileCompileWasmTemplatePlugin.js, lib/wasm/WasmMainTemplatePlugin.js, lib/wasm/WebAssemblyGenerator.js, lib/wasm/WebAssemblyModulesPlugin.js, lib/wasm/WebAssemblyUtils.js, lib/web/FetchCompileWasmTemplatePlugin.js, schemas/WebpackOptions.json, test/__snapshots__/StatsTestCases.test.js.snap
disable it by default (temporary)
bugfix
existing test
no
the option `optimization.mangleWasmImports`
=> allow to disable wasm import mangle

examples/dll-app-and-vendor/0-vendor/README.md, examples/dll-app-and-vendor/0-vendor/template.md
Fix typo in Documentation
https://github.com/webpack/webpack/pull/6906
Documentation
Tests aren't needed
No
nothing
=> Fixing grammar issues in webpack example #6906

lib/Parser.js, package.json, test/Parser.unittest.js, test/cases/parsing/optional-catch-binding/index.js, test/cases/parsing/optional-catch-binding/module.js, test/cases/parsing/optional-catch-binding/test.filter.js, test/helpers/supportsOptionalCatchBinding.js, yarn.lock
=> Add support for ECMAScript 2019

lib/WebpackOptionsApply.js
Small tweaks. Change some variable defined identifier `let` to `const`
No.
No.
No.
moved from #7488
=> change variable defined identifier let to const

lib/HotModuleReplacement.runtime.js, test/hotCases/runtime/bubble-async/file.js, test/hotCases/runtime/bubble-async/index.js, test/hotCases/runtime/bubble-async/parent-file.js
fixes #7477
bugfix
yes
no
nothing
=> add parents correctly when creating namespace objects

declarations.d.ts, lib/debug/ProfilingPlugin.js, package.json, yarn.lock
updating dependencies 
N/A
No
No
=> Update "chrome-trace-event" package and remove types

.github/ISSUE_TEMPLATE/Bug_report.md
Put it through grammarly and updated some instructions :ok_hand:
=> Update bug report issue template

lib/optimize/ConcatenatedModule.js, test/configCases/errors/self-reexport/a.js, test/configCases/errors/self-reexport/aa.js, test/configCases/errors/self-reexport/b.js, test/configCases/errors/self-reexport/bb.js, test/configCases/errors/self-reexport/c1.js, test/configCases/errors/self-reexport/c2.js, test/configCases/errors/self-reexport/cc.js, test/configCases/errors/self-reexport/errors.js, test/configCases/errors/self-reexport/index.js, test/configCases/errors/self-reexport/webpack.config.js
fixes #7547
error improvement
yes
no
nothing
=> improve error message for circular reexports

lib/CompatibilityPlugin.js
CompatibilityPlugin typings added
no
no
no
=> CompatabilityPlugin typings added

lib/ContextModule.js, lib/DelegatedModule.js, lib/DependenciesBlock.js, lib/Dependency.js, lib/FlagDependencyUsagePlugin.js, lib/dependencies/DependencyReference.js, lib/dependencies/HarmonyExportImportedSpecifierDependency.js, lib/dependencies/HarmonyImportDependency.js, lib/dependencies/HarmonyImportSpecifierDependency.js, lib/optimize/ConcatenatedModule.js, lib/optimize/ModuleConcatenationPlugin.js, test/cases/scope-hoisting/order-without-side-effects/a.js, test/cases/scope-hoisting/order-without-side-effects/b.js, test/cases/scope-hoisting/order-without-side-effects/index.js, test/cases/scope-hoisting/order-without-side-effects/package.json, test/cases/scope-hoisting/order-without-side-effects/tracker.js
=> add order to dependency reference

test/Compiler.test.js, test/fixtures/count-loader.js
=> add test case for #7533

lib/UseStrictPlugin.js
=> chore(types): UseStrictPlugin

lib/optimize/ConcatenatedModule.js, test/cases/side-effects/missing-module-7499/example/constants.js, test/cases/side-effects/missing-module-7499/example/index.js, test/cases/side-effects/missing-module-7499/example/package.json, test/cases/side-effects/missing-module-7499/index.js, test/cases/side-effects/missing-module-7499/lazy.js
fixes #7499 
bugfix
yes
no
nothing
=> fixes #7499

lib/IgnorePlugin.js
=> chore(types): IgnorePlugin

lib/WebpackOptionsDefaulter.js, lib/optimize/SplitChunksPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap
As per [card](https://github.com/webpack/webpack/projects/5#card-10750335), bumping defaults for `SplitChunksPlugin`
feature
N/A
Yes
Default values are not mentioned in docs.
=> chore(SplitChunksPlugin): update defaults

lib/web/JsonpChunkTemplatePlugin.js, test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/issue-7577/a.js, test/statsCases/issue-7577/b.js, test/statsCases/issue-7577/c.js, test/statsCases/issue-7577/node_modules/vendor.js, test/statsCases/issue-7577/webpack.config.js
fixes #7577
bugfix
yes
no
nothing
=> fixes #7577

open-bot.yaml
Decrease time until bot closes issues to 3 months
bot
no
no
nothing
=> Decrease time until bot closes issues to 3 months

examples/dll-app-and-vendor/0-vendor/README.md, examples/dll-app-and-vendor/0-vendor/template.md
Fix typo in Documentation 
Tests aren't needed
N/A
**Summary**
Clarifying spelling in webpack example
No
=> Fixing grammar issues in webpack example

package.json, yarn.lock
upgrade
N/A
no
You can now put absolute paths in `resolve.alias` keys.
=> upgrade enhanced-resolve

bin/webpack.js, lib/Chunk.js, lib/ChunkGroup.js, lib/Compilation.js, lib/ExtendedAPIPlugin.js, lib/ExternalModuleFactoryPlugin.js, lib/HotModuleReplacement.runtime.js, lib/RuleSet.js, lib/Stats.js, lib/UmdMainTemplatePlugin.js, lib/WebpackOptionsValidationError.js, lib/debug/ProfilingPlugin.js, lib/dependencies/AMDDefineDependencyParserPlugin.js, lib/dependencies/AMDRequireDependenciesBlockParserPlugin.js, lib/node/NodeMainTemplateAsync.runtime.js, lib/util/SetHelpers.js, lib/wasm/WasmMainTemplatePlugin.js, lib/wasm/WebAssemblyGenerator.js, lib/webpack.web.js
=> arrow functions, remove or improve eslint-disable comments

lib/Compilation.js
=> Fix @template syntax error in Compilation.js iterationOfArrayCallback

lib/dependencies/HarmonyExportImportedSpecifierDependency.js, test/cases/side-effects/order-issue-7665/index.js, test/cases/side-effects/order-issue-7665/module/a.js, test/cases/side-effects/order-issue-7665/module/b.js, test/cases/side-effects/order-issue-7665/module/index.js, test/cases/side-effects/order-issue-7665/module/package.json, test/cases/side-effects/order-issue-7665/tracker.js
fixes #7665
bugfix
yes
no
nothing
=> fixes order for reexported dependencies

lib/BannerPlugin.js, lib/EvalSourceMapDevToolPlugin.js, lib/SourceMapDevToolPlugin.js
Simplify the codebase by removing unneeded checks. They were adding extra noise.
refactoring
no
no, but it removes the errors
nothing
=> Remove extra arguments checks

lib/EnvironmentPlugin.js
Add a few type annotations to EnvironmentPlugin
Refactoring / Types 
N/A
N/A
N/A
=> chore(types): add types to EnvironmentPlugin

lib/Dependency.js
=> Deprecate Dependency.compare

_SETUP.md, examples/many-pages/README.md, examples/many-pages/template.md, examples/many-pages/webpack.config.js, lib/Chunk.js, lib/ChunkGroup.js, lib/Compilation.js, lib/Generator.js, lib/optimize/SplitChunksPlugin.js, lib/util/cachedMerge.js, lib/util/deterministicGrouping.js
=> all: typo fixes

lib/AutomaticPrefetchPlugin.js, lib/Chunk.js, lib/CommentCompilationWarning.js, lib/CompatibilityPlugin.js, lib/Entrypoint.js, lib/HotModuleReplacementPlugin.js, lib/IgnorePlugin.js, lib/UseStrictPlugin.js, lib/dependencies/SystemPlugin.js, lib/node/NodeMainTemplatePlugin.js, lib/node/NodeSourcePlugin.js, lib/wasm/WasmFinalizeExportsPlugin.js, lib/web/JsonpMainTemplatePlugin.js, lib/webworker/WebWorkerMainTemplatePlugin.js
=> Simplify imports

lib/ContextModule.js, lib/Dependency.js
=> make loc in context dependencies a correct object

lib/Stats.js, test/__snapshots__/StatsTestCases.test.js.snap
bugfix
existing tests
no
nothign
=> sort ids in Stats numerical

lib/Compilation.js
bugfix
existing tests
no
nothing
=> replace deprecated method

lib/optimize/SplitChunksPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap
bugfix
existing tests
no
nothing
=> copy chunk reason to maxSize parts

lib/Dependency.js, lib/SingleEntryPlugin.js, lib/dependencies/LoaderPlugin.js, lib/formatLocation.js
see also #7669
bugfix
no
no
nothing
=> add types and fix incorrect loc type

lib/ChunkTemplate.js, lib/Compilation.js, lib/DependenciesBlockVariable.js, lib/Dependency.js, lib/DependencyTemplates.js, lib/Generator.js, lib/MainTemplate.js, lib/NormalModule.js, lib/optimize/ConcatenatedModule.js, test/statsCases/define-plugin/webpack.config.js
refactoring
existing tests
yes
TODO
=> make DependencyTemplates a new class

schemas/WebpackOptions.json
Fixes the docs typo introduced in #7686.
N/A
No
Nothing
=> Correct moduleIds schema description

lib/Compilation.js, lib/optimize/EnsureChunkConditionsPlugin.js, lib/optimize/RemoveEmptyChunksPlugin.js, lib/optimize/RemoveParentModulesPlugin.js, lib/optimize/SplitChunksPlugin.js, test/StatsTestCases.test.js
remove
existing tests
yes
TODO
=> remove deprecated stuff

lib/Stats.js
config
no
yes
`source` now defaults to `false` for stats
=> Default 'source' to 'false' for stats

lib/Stats.js, test/__snapshots__/StatsTestCases.test.js.snap
=> fix sorting of reasons

lib/Chunk.js, lib/Compilation.js, lib/SizeFormatHelpers.js, lib/Stats.js, lib/dependencies/AMDDefineDependencyParserPlugin.js, lib/dependencies/AMDRequireDependenciesBlockParserPlugin.js, lib/dependencies/CommonJsRequireDependencyParserPlugin.js, lib/dependencies/LocalModulesHelpers.js, lib/optimize/EnsureChunkConditionsPlugin.js, lib/optimize/SplitChunksPlugin.js, lib/performance/AssetsOverSizeLimitWarning.js, lib/performance/EntrypointsOverSizeLimitWarning.js, test/LocalModulesHelpers.unittest.js, test/SizeFormatHelpers.unittest.js
Destructure helpers to improve readability
refactoring
no
no
nothing
=> Destructure helpers to improve readability

lib/Compilation.js, test/cases/chunks/nested-in-empty/b.js, test/cases/chunks/nested-in-empty/index.js
=> fix case where empty chunkgroups cause nested chunkgroups to vanish

lib/Template.js
=> Convert Template to ES6

test/ConfigTestCases.test.js, test/HotTestCases.test.js, test/TestCases.template.js, test/configCases/web/prefetch-preload/index.js, test/helpers/createLazyTestEnv.js
=> improve way of adding exported tests to test tree

test/README.md
Update jest snapshot-testing url.
=> Update Jest URL

lib/UnsupportedFeatureWarning.js
Add jsdoc types for UnsupportedFeatureWarning class
Refactoring
N/A
N/A
N/A
=> chore(types): add jsdoc types for UnsupportedFeatureWarning class

lib/Compilation.js, lib/Module.js, lib/ModuleDependencyError.js, lib/ModuleDependencyWarning.js, lib/Stats.js
refactor
N/A
yes
Module.issuer is now Module.getIssuer(ModuleGraph)
=> move Module.issuer into Module.getIssuer(moduleGraph)

lib/optimize/ConcatenatedModule.js
=> fixes #7887

lib/JavascriptModulesPlugin.js, test/configCases/contenthash/include-chunk-id/chunk.js, test/configCases/contenthash/include-chunk-id/index.js, test/configCases/contenthash/include-chunk-id/test.config.js, test/configCases/contenthash/include-chunk-id/webpack.config.js
fixes #7915
bugfix
yes
no
nothing
=> chunk ids contribute to contenthash for javascript

lib/optimize/ConcatenatedModule.js, test/configCases/scope-hoisting/export-global/index.js, test/configCases/scope-hoisting/export-global/module.js, test/configCases/scope-hoisting/export-global/module2.js, test/configCases/scope-hoisting/export-global/webpack.config.js
fixes #7905
bugfix
yes
no
nothing
=> fix exporting globals in scope-hoisted modules

lib/optimize/ConcatenatedModule.js, test/cases/scope-hoisting/issue-7930/export.js, test/cases/scope-hoisting/issue-7930/index.js, test/cases/scope-hoisting/issue-7930/module.js
=> fixes #7930

lib/AsyncDependenciesBlock.js, lib/Chunk.js, lib/ChunkGraph.js, lib/Compilation.js, lib/DelegatedModule.js, lib/DependenciesBlock.js, lib/DllModule.js, lib/ExternalModule.js, lib/Module.js, lib/NormalModule.js, lib/RawModule.js, lib/optimize/ConcatenatedModule.js
refactor
existing tests
yes
nothing
=> Use ChunkGraph instead of Compilation in updateHash

package.json, test/__snapshots__/StatsTestCases.test.js.snap, yarn.lock
=> Upgrade some dependencies

lib/Stats.js, lib/optimize/SplitChunksPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/split-chunks/entry-point-error/errors.js, test/configCases/split-chunks/entry-point-error/index.js, test/configCases/split-chunks/entry-point-error/module.js, test/configCases/split-chunks/entry-point-error/test.config.js, test/configCases/split-chunks/entry-point-error/webpack.config.js, test/statsCases/split-chunks/webpack.config.js
remove deprecated features
yes
yes
* Passing an entry name to `cacheGroup.test` is no longer allowed
* Using an name of an existing chunk is not longer allowed for `cacheGroup.name` (it will error)
=> emit error when splitChunks.name and entrypoint match

lib/ChunkGroup.js, lib/Compilation.js, lib/ids/ChunkModuleIdRangePlugin.js, lib/ids/HashedModuleIdsPlugin.js, lib/ids/NaturalModuleIdsPlugin.js, lib/ids/OccurrenceModuleIdsPlugin.js, lib/util/comparators.js, test/configCases/chunk-index/order-multiple-entries/webpack.config.js, test/statsCases/chunk-module-id-range/webpack.config.js
refactor
existing tests
no (but it deprecate something)
* `set/getModuleIndex` -> `set/getModulePreOrderIndex`
* `set/getModuleIndex2` -> `set/getModulePostOrderIndex`
=> rename index/index2 to pre/postOrderIndex

bin/webpack.js
fixes #7998
bugfix
no, there are to CLI tests here
no
nothing
=> Fix exit code when multiple CLIs are installed

lib/HotModuleReplacementPlugin.js, lib/MainTemplate.js, lib/dependencies/HarmonyImportDependencyParserPlugin.js, lib/node/NodeMainTemplatePlugin.js, lib/web/JsonpMainTemplatePlugin.js, lib/webworker/WebWorkerMainTemplatePlugin.js
⚠️ Disable whitespace diff for better review experience!
refactoring
no
yes
I don't if it is already documented but the API reference could outdated.
`MainTemplate.hooks.hotBootstrap` is replaced by `HotModuleReplacementPlugin.getMainTemplateHooks(mainTemplate).hotBootstrap`
=> Move HMR hotBoostrap hook

package.json, yarn.lock
deps
existing tests
no
nothing
=> Upgrade tapable version

lib/util/deprecation.js
=> make deprecations less noisy

lib/WebpackOptionsDefaulter.js
Fixes #8031.
@sokra Does this change need a test? If so then can you point me towards an existing test which I can copy/modify to test this new code?
=> Correctly set the 'browser' value for electron-renderer

declarations.d.ts, lib/Chunk.js, lib/HotUpdateChunk.js, lib/Module.js, lib/Template.js, lib/dependencies/WebAssemblyImportDependency.js
=> Some random types

package.json, yarn.lock
deps
existing tests
no
nothing
=> upgrade webpack-sources

azure-pipelines.yml
=> Fix handling of non-zero exit codes in azure

appveyor.yml
=> Reduce the appveyor CI tasks

yarn.lock
=> add integrity to lockfile (yarn version update)

schemas/ajv.absolutePath.js, test/Validation.test.js
Fixing a tiny typo in `schemas/ajv.absolutePath.js`.
Got this error thrown at me during a build.
A typo fix.
Updated the relevant test.
Someone could be relying on the specific error string, but I believe this doesn't qualify as breaking.
=> Fix 'contains' typo in error string.

lib/dependencies/HarmonyAcceptImportDependency.js, lib/dependencies/HarmonyDetectionParserPlugin.js, lib/dependencies/HarmonyExportDependencyParserPlugin.js, lib/dependencies/HarmonyExportImportedSpecifierDependency.js, lib/dependencies/HarmonyImportDependency.js, lib/dependencies/HarmonyImportDependencyParserPlugin.js, lib/dependencies/HarmonyImportSideEffectDependency.js, lib/dependencies/HarmonyImportSpecifierDependency.js
it's not serializable and not needed anyway
refactoring
existing test
yes
nothing
=> remove parserScope

lib/LibraryTemplatePlugin.js, test/configCases/library/array-global/index.js, test/configCases/library/array-global/webpack.config.js, test/configCases/library/array-window/index.js, test/configCases/library/array-window/webpack.config.js
bugfix for #8111 (and #8099)
yes
no
nothing
=> fix output for 'output.library: string[]' configuration

lib/MainTemplate.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/entry/issue-8110/a.js, test/configCases/entry/issue-8110/b.js, test/configCases/entry/issue-8110/c.js, test/configCases/entry/issue-8110/d.js, test/configCases/entry/issue-8110/webpack.config.js
=> fixes #8110

package.json, yarn.lock
```
package: update `coveralls` v2.11.2...v3.0.2
```
=> update coveralls reporter

lib/util/registerExternalSerializer.js
=> feat(registerExternalSerializer): add SourceMapSource support

lib/Cache.js, lib/Compilation.js, lib/cache/MemoryCachePlugin.js
refactoring
existing test
yes
Plugins can use the `compiler.cache` interface to store and restore things
=> refactor cache to be more generic and usable for other things

lib/wasm/WebAssemblyGenerator.js
The Buffer can be a slice of the underlying buffer
bugfix
revert
no
nothing
=> revert incorrect change

lib/AmdMainTemplatePlugin.js, lib/ExtendedAPIPlugin.js, lib/HotModuleReplacementPlugin.js, lib/JavascriptModulesPlugin.js, lib/MainTemplate.js, lib/SetVarMainTemplatePlugin.js, lib/TemplatedPathPlugin.js, lib/UmdMainTemplatePlugin.js, lib/web/JsonpExportMainTemplatePlugin.js, test/Errors.test.js, test/__snapshots__/StatsTestCases.test.js.snap
It's no longer needed, because we hash the runtime how
removal
no
yes
nothing
=> remove globalPath and useChunkHash feature

.travis.yml, appveyor.yml, codecov.yml, open-bot.yaml, package.json
=> CI: simplify travis

azure-pipelines.yml, package.json, test/helpers/createLazyTestEnv.js, yarn.lock
dep upgrade, CI
N/A
no
nothing
=> Upgrade jest and remove memory bug hack

.travis.yml, lib/Stats.js, lib/dependencies/WebAssemblyExportImportedDependency.js, lib/optimize/OccurrenceModuleOrderPlugin.js, lib/wasm/WebAssemblyJavascriptGenerator.js, lib/wasm/WebAssemblyParser.js, test/Compiler.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/cases/wasm/export-imported-global/index.js, test/cases/wasm/imported-global-preserve-ordering/index.js
We want to test against `WebAssembly.Global` which is available in Node 11.
This PR allows webpack to be tested against arbitrary Node nightly.
=> Node 12 in CI

test/cases/wasm/finalize-exports-issue-8261/node_modules/side-effect-free/module.wat
To fix @xtuc comment in previous PR: https://github.com/webpack/webpack/pull/8266/files/035ceb6b1b9b14fe7c3c0da2738cd5d5e2ecf24b#diff-373fad072502d91acb95b26d85c95b7e
minor readability improvement
It's test itself
No
Nothing
=> [Test] simplify .wat code for finalize-exports-issue-8261 test

lib/HotModuleReplacementPlugin.js, package.json, test/HotModuleReplacementPlugin.test.js
#8297 when entry name is a number 
like 
> entry: { '404' :  '404.js'}
HMR can't correct work;
bugfix, fixed #8297 
Yes
No
Nothing
=> @ fix 8297 issues

lib/dependencies/WebAssemblyExportImportedDependency.js, lib/util/comparators.js, lib/util/createHash.js
=> Some minor fixes and comments

lib/TemplatedPathPlugin.js, test/configCases/plugins/banner-plugin-hashing/index.js, test/configCases/plugins/banner-plugin-hashing/webpack.config.js
bugfixes, comments
no
no
already documented
=> minor fixes for #8109

declarations.d.ts, lib/APIPlugin.js, lib/ContextModule.js, lib/ExtendedAPIPlugin.js, lib/HotModuleReplacement.runtime.js, lib/HotModuleReplacementPlugin.js, lib/MainTemplate.js, lib/NodeStuffPlugin.js, lib/RequireJsStuffPlugin.js, lib/RuntimeGlobals.js, lib/RuntimeTemplate.js, lib/dependencies/CommonJsRequireDependencyParserPlugin.js, lib/dependencies/HarmonyExportImportedSpecifierDependency.js, lib/dependencies/HarmonyExportSpecifierDependency.js, lib/node/NodeMainTemplateAsync.runtime.js, lib/node/NodeMainTemplatePlugin.js, lib/optimize/ConcatenatedModule.js, lib/wasm/WasmMainTemplatePlugin.js, lib/wasm/WebAssemblyJavascriptGenerator.js, lib/web/FetchCompileWasmTemplatePlugin.js, lib/web/JsonpMainTemplate.runtime.js, lib/web/JsonpMainTemplatePlugin.js, lib/webworker/WebWorkerMainTemplate.runtime.js, lib/webworker/WebWorkerMainTemplatePlugin.js, test/cases/parsing/issue-758/index.js
refactoring
existing tests
no
nothing
=> refactor properties on __webpack_require__

lib/ProgressPlugin.js
=> show module count earlier when they are added to the queue

lib/Chunk.js, lib/ChunkGraph.js, lib/ChunkGroup.js, lib/Compilation.js, lib/Entrypoint.js
bugfix and types
no
no
nothing
=> Add missing types on chunk related classes

lib/performance/AssetsOverSizeLimitWarning.js, lib/performance/EntrypointsOverSizeLimitWarning.js, lib/performance/SizeLimitsPlugin.js
=> Add types to SizeLimitsPlugin

bin/webpack.js, lib/Compilation.js, lib/Compiler.js, lib/Stats.js, package.json, yarn.lock
- Update TypeScript
- Update Node.js typings
- Replace `Source#emitted` by a `WeakSet`
types and bugfix
no
no
nothing
=> Update TypeScript and fix raised errors

lib/Chunk.js
=> Fix a typo in Chunk#split jsdoc comment

lib/optimize/SplitChunksPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/split-chunks-max-size/webpack.config.js
fixes #8407
bugfix
yes
no
nothing
=> handle case when minSize > maxSize

lib/util/deterministicGrouping.js, test/__snapshots__/StatsTestCases.test.js.snap
fixes #8407
bugfix
no
no
nothing
=> prevent groups with size < minSize

lib/JsonParser.js, lib/NormalModule.js, lib/RequestShortener.js, lib/ResolverFactory.js, lib/dependencies/JsonExportsDependency.js, lib/util/StackedSetMap.js, lib/util/TrackingSet.js
- Add types to `TrackingSet` and `StackedMapSet`. This is required to stat typing the JS parser.
- Start typing the JSON parser
types
no
no
nothing
=> Preliminary work before typing the parsers

lib/FlagDependencyExportsPlugin.js, test/watchCases/parsing/reexport-chain/0/a.js, test/watchCases/parsing/reexport-chain/0/b.js, test/watchCases/parsing/reexport-chain/0/c.js, test/watchCases/parsing/reexport-chain/0/index.js, test/watchCases/parsing/reexport-chain/1/c.js, test/watchCases/parsing/reexport-chain/2/a.js, test/watchCases/parsing/reexport-chain/2/c.js, yarn.lock
Always update providedExports when they have dependencies
fixes #8455
bugfix
yes
no
nothing
=> fix a bug which causes incorrect providedExports for cached modules

buildin/system.js, lib/JavascriptParserHelpers.js, lib/RuntimeGlobals.js, lib/dependencies/ConstDependency.js, lib/dependencies/HarmonyTopLevelThisParserPlugin.js, lib/dependencies/SystemPlugin.js, lib/dependencies/SystemRuntimeModule.js
=> Use a runtime module to inject System polyfill

lib/webpack.js
refactoring
no
no
`AggressiveSplittingPlugin` is now deprecated
=> Deprecate AggressiveSplittingPlugin

package.json
=> Remove unneeded files from package.json#files

declarations/WebpackOptions.d.ts, lib/Compilation.js, lib/Compiler.js, lib/MultiCompiler.js, lib/MultiStats.js, lib/MultiWatching.js, lib/Stats.js, lib/Watching.js, lib/util/AsyncQueue.js, lib/webpack.js, schemas/WebpackOptions.json, test/Stats.unittest.js
=> Add compilers typings

lib/serialization/ObjectMiddleware.js, lib/util/serializer.js
allows to bundle webpack
bugfix
no
no
nothing
=> load internal serializers internally

lib/IgnorePlugin.js, test/configCases/errors/multi-entry-missing-module/webpack.config.js
fixes #8522
bugfix
yes
no
nothing
=> fix issue when contextRegExp is undefined

lib/IgnorePlugin.js, test/configCases/ignore/multiple-with-externals/ignored-module1.js, test/configCases/ignore/multiple-with-externals/ignored-module2.js, test/configCases/ignore/multiple-with-externals/normal-module.js, test/configCases/ignore/multiple-with-externals/test.js, test/configCases/ignore/multiple-with-externals/webpack.config.js
=> fixes #8538

declarations/WebpackOptions.d.ts, lib/stats/DefaultStatsFactoryPlugin.js, lib/stats/DefaultStatsPresetPlugin.js, lib/stats/DefaultStatsPrinterPlugin.js, schemas/WebpackOptions.json, test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/async-commons-chunk/webpack.config.js, test/statsCases/chunks-development/webpack.config.js, test/statsCases/chunks/webpack.config.js, test/statsCases/circular-correctness/webpack.config.js, test/statsCases/graph-correctness-entries/webpack.config.js, test/statsCases/graph-correctness-modules/webpack.config.js, test/statsCases/limit-chunk-count-plugin/webpack.config.js, test/statsCases/optimize-chunks/webpack.config.js, test/statsCases/prefetch-preload-mixed/webpack.config.js, test/statsCases/prefetch/webpack.config.js, test/statsCases/split-chunks-automatic-name/webpack.config.js, test/statsCases/split-chunks-combinations/webpack.config.js, test/statsCases/split-chunks-issue-6413/webpack.config.js, test/statsCases/split-chunks-issue-6696/webpack.config.js, test/statsCases/split-chunks-issue-7401/webpack.config.js, test/statsCases/split-chunks-max-size/webpack.config.js, test/statsCases/split-chunks-prefer-bigger-splits/webpack.config.js, test/statsCases/split-chunks/webpack.config.js
* add options to schema
* add `chunkRelations` option (off by default)
* fix a printed undefined
yes
yes, default changed
new stats option `chunkRelations` which displays chunk parents, children and siblings
=> improvements to stats

lib/ModuleNotFoundError.js, package.json, yarn.lock
```
remove package `vm-browserify`
```
Update vm-browserify
No
No
None
=> remove vm-browserify

lib/stats/DefaultStatsFactoryPlugin.js, lib/stats/DefaultStatsPresetPlugin.js, test/Stats.test.js
=> fix incorrect default for some options with all: false

lib/RuntimePlugin.js, lib/WebpackOptionsDefaulter.js
=> Use fullhash to avoid deprecation warning

lib/serialization/NullPrototypeObjectSerializer.js, lib/serialization/ObjectMiddleware.js, test/cases/loaders/emit-file/file.js, test/cases/loaders/emit-file/index.js, test/cases/loaders/emit-file/loader.js
=> allow serializing of objects with null prototype

test/Stats.test.js, test/fixtures/chunk-b.js
I added tests to show how `namedChunkGroups` option works and to try to find potential issues.
tests
well, yes 😅
no
nothing
=> Add namedChunkGroups tests

test/ProfilingPlugin.test.js
This PR tries to resolve the timeouts in the testsuite (see current CI status).
See https://travis-ci.org/webpack/webpack/jobs/474274728#L536-L538
Tests / CI
No
No
=> Increase Jest timeout for profiling plugin test

lib/WebpackOptionsDefaulter.js, test/configCases/parsing/harmony-global/webpack.config.js, test/configCases/target/strict-mode-global/webpack.config.js
bugfix
yes
yes
* node.global is now true by default again
=> Enable node.global by default

lib/Compilation.js, lib/Compiler.js, lib/ContextModuleFactory.js, lib/DefinePlugin.js, lib/DelegatedModuleFactoryPlugin.js, lib/DllModuleFactory.js, lib/DllReferencePlugin.js, lib/ExternalModuleFactoryPlugin.js, lib/FileSystemInfo.js, lib/FunctionModuleTemplatePlugin.js, lib/IgnorePlugin.js, lib/ModuleFactory.js, lib/NormalModule.js, lib/NormalModuleFactory.js, lib/NormalModuleReplacementPlugin.js, lib/NullFactory.js, lib/WatchIgnorePlugin.js, lib/Watching.js, lib/cache/ResolverCachePlugin.js, lib/node/NodeWatchFileSystem.js, lib/optimize/SideEffectsFlagPlugin.js, lib/util/AsyncQueue.js, package.json, test/StatsTestCases.test.js, test/TestCases.template.js, yarn.lock
updated watchpack. It now passes more info to webpack i. e. for missing files/directories.
refactoring, deps
existing tests
yes
* Removed `compilationParams.compilationDependencies`
* Plugins can add dependencies to the compilation by adding to `compilation.file/context/missingDependencies`
* Changed hooks in `NormalModuleFactory` from waterfall to bailing, changed and renamed hooks that return waterfall functions
* Changed WatchFileSystem interface
=> Performance fixes for next branch, watchpack update

lib/JavascriptParser.js, lib/util/AsyncQueue.js, test/cases/compile/long-module-chain/index.js, test/cases/compile/long-module-chain/module.js
=> add process.nextTick to avoid long recursion in callbacks

declarations.d.ts, lib/Compiler.js
cherry-picked from #8609
memory usage improvement
N/A
no
nothing
=> Change forEach to forEachLimit when emitting assets

declarations/WebpackOptions.d.ts, lib/Cache.js, lib/Compilation.js, lib/ContextModule.js, lib/DelegatedModuleFactoryPlugin.js, lib/DelegatedPlugin.js, lib/DllReferencePlugin.js, lib/LibManifestPlugin.js, lib/Module.js, lib/cache/FileCachePlugin.js, lib/cache/MemoryCachePlugin.js, lib/ids/IdHelpers.js, lib/ids/NamedChunkIdsPlugin.js, lib/ids/NamedModuleIdsPlugin.js, lib/optimize/ConcatenatedModule.js, lib/optimize/SplitChunksPlugin.js, lib/serialization/FileMiddleware.js, lib/serialization/ObjectMiddleware.js, lib/util/identifier.js, lib/util/serialization.js, package.json, schemas/WebpackOptions.json, yarn.lock
* log a warning when serialization fails
* make reading from file safer and handle unexpected end of file
* update webpack-sources for faster buffer() call
* + see below
performance, bugfix
existing tests
yes
* added `cache.idleTimeout`: Time in ms after which idle period the cache storing should happen (only for store: 'pack' or 'idle')
* defaults to 10s
* added `cache.idleTimeoutForInitialStore`: Time in ms after which idle period the initial cache storing should happen (only for store: 'pack' or 'idle')
* defaults to 0s
* removed `Cache.hooks.got`
* added argument to `Cache.hooks.get` …
=> Performance for caching

lib/NormalModule.js
fixup for #8651 
fixup
existing tests
no
nothing
=> add missing cache

lib/optimize/ConcatenatedModule.js, test/cases/scope-hoisting/esModule/index.js, test/cases/scope-hoisting/esModule/module.js, test/cases/scope-hoisting/esModule/other.js, test/configCases/scope-hoisting/esModule/index.js, test/configCases/scope-hoisting/esModule/module.js, test/configCases/scope-hoisting/esModule/other.js, test/configCases/scope-hoisting/esModule/webpack.config.js
=> fixes #8666

README.md
Make doc efficient to be used.
N/A
N/A
N/A
=> docs(README): add index

lib/Compilation.js, test/__snapshots__/StatsTestCases.test.js.snap
as reported in https://github.com/webpack/webpack/issues/8537#issuecomment-459313591 by @MhMadHamster
bugfix
existing tests
no
nothing
=> fix a bug which creates duplicate runtime modules for entrypoints sharing a runtime chunk

lib/dependencies/AMDDefineDependency.js, test/cases/amd/define-needs-module/index.js, test/cases/amd/define-needs-module/module.js
as reported here: https://github.com/webpack/webpack/issues/8537#issuecomment-452910985 by @MLoughry
bugfix
yes
no
nothing
=> add missing runtime requirement to AMD define

package.json, yarn.lock
=> update linting dependencies

package.json, yarn.lock
=> upgrade schema-utils to new major

.travis.yml
=> update node 12 nightly version

.prettierignore, test/BenchmarkTestCases.benchmark.js, test/Compiler.test.js, test/SourceMapDevToolModuleOptionsPlugin.unittest.js, test/Stats.unittest.js, test/configCases/errors/multi-entry-missing-module/webpack.config.js, test/configCases/optimization/minimizer/webpack.config.js, test/statsCases/split-chunks-max-size/webpack.config.js, test/watchCases/plugins/define-plugin/webpack.config.js
=> fix prettierignore file and run prettier

test/README.md
=> test: modify styles and typo of README

lib/APIPlugin.js, test/cases/parsing/typeof/index.js
=> fixes #8829

lib/Chunk.js
feature
don't need tests
no
no
Just modify `options` to default parameter to avoid error when use `chunk.size()` , like this:
this make writing plugins more convenience
=> feat(Chunk.js): :sparkles:  size fn: Modify options to default parameter

lib/optimize/SplitChunksPlugin.js, test/configCases/split-chunks/issue-8908/a.js, test/configCases/split-chunks/issue-8908/b.js, test/configCases/split-chunks/issue-8908/index.js, test/configCases/split-chunks/issue-8908/test.config.js, test/configCases/split-chunks/issue-8908/vendor/vendor-a.js, test/configCases/split-chunks/issue-8908/vendor/vendor-b.js, test/configCases/split-chunks/issue-8908/webpack.config.js
=> fixes #8908

lib/WebpackOptionsApply.js
Make lazy loading for modules at WebpackOptionApply.js, so that no extra memory is allocated.
For these changes they are not needed.
No.
Nothing.
=> Make lazy loading for modules at WebpackOptionApply.js

lib/FunctionModuleTemplatePlugin.js
Bugfix #8949 
No (Should we add performances tests for this kind of situation?)
No
Nothing
=> fixes #8949

yarn.lock
Tests can't be executed with the following error when using Node v11.11.0.
jest's issue is https://github.com/facebook/jest/issues/8069.
```
TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<process>'
```
no
no
N/A
=> [master]: update jest

lib/Parser.js, test/cases/parsing/issue-8874/index.js, test/cases/parsing/issue-8874/module.js, test/cases/parsing/issue-8874/moduleDefaultParameter.js, test/cases/parsing/issue-8874/moduleExportedFunctionExpression.js, test/cases/parsing/issue-8874/moduleExportedFunctionExpressionDefaultParameter.js, test/cases/parsing/issue-8874/someFunction.js
=> fixes #8874

test/README.md
modify JavaScript example in README
no
no
nothing special
=> test: modify JavaScript example in README

lib/ChunkGraph.js, lib/Template.js, lib/dependencies/HarmonyDetectionParserPlugin.js, lib/optimize/MangleExportsPlugin.js, lib/wasm/WebAssemblyUtils.js, open-bot.yaml, schemas/plugins/SourceMapDevToolPlugin.json, test/Template.unittest.js, test/numberHash.unittest.js
This pull request fixes a common misspelling across the webpack codebase.
This is a refactoring fix.
The necessary tests were updated.
=> correct spelling mistake, update identifer to identifier

lib/ChunkGraph.js
Just moved function `isAvailible` from 'inside method' to avoid each time creation new function.
Refactoring
No
No
None
=> Move isAvailible from method to module

declarations/WebpackOptions.d.ts, schemas/WebpackOptions.json
Fix grammar
Text change
no
no
nothing
=> fix(typo) remove redundant is

bin/webpack.js
Made string message to const, previously it was let.
Trying to improve the codebase.
refactoring
nopes
I don't think so.
Nothing
=> chore(bin):sets string messages to const

azure-pipelines.yml, test/cases/parsing/harmony-tdz/index.js
Add Node.js v12 because this version has already released.
nope
nope
N/A
=> chore(ci): add Node.js v12 to azure-pipelines

lib/Cache.js, lib/cache/BackgroundFileCachePlugin.js, lib/cache/IdleFileCachePlugin.js, lib/cache/InstantFileCachePlugin.js, lib/cache/MemoryCachePlugin.js, lib/index.js
refactoring
existing tests
yes
nothing
=> add stages for Cache plugins

lib/Chunk.js, lib/MainTemplate.js, lib/web/JsonpMainTemplatePlugin.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/web/prefetch-preload/index.js, test/configCases/web/prefetch-split-chunks/index.js, test/configCases/web/prefetch-split-chunks/public-path.js, test/configCases/web/prefetch-split-chunks/test.config.js, test/configCases/web/prefetch-split-chunks/webpack.config.js
delay prefetching until all initial code is evaluated
fixes #7744
bugfix
yes
no
prefetch will start after the initial code is evaluated
=> fix prefetching with runtime public path

open-bot.yaml
=> Join effort dependabot and webpack-bot

lib/CompatibilityPlugin.js, lib/JavascriptParser.js, lib/WebpackOptionsApply.js, lib/runtime/StartupChunkDependenciesPlugin.js, test/configCases/library/0-create-library/webpack.config.js, test/configCases/library/1-use-library/webpack.config.js
fixes #9154
allow nesting webpack bundles (rename inner `__webpack_require__`)
to allow testing this
yes
no
nothing
=> add sync mode for chunk dependency startup in sync node target

lib/CommonJsStuffPlugin.js, lib/NodeStuffPlugin.js, lib/WebpackOptionsApply.js, test/configCases/parsing/issue-9156/index.js, test/configCases/parsing/issue-9156/webpack.config.js
fixes #9156
bugfix
yes
no, it reverts one
nothing
=> node: false should not disable CommonJs features

lib/FunctionModuleTemplatePlugin.js, lib/node/ReadFileCompileWasmPlugin.js, lib/wasm/WasmChunkLoadingRuntimeModule.js, lib/web/FetchCompileWasmPlugin.js
refactoring, bugfix
no
no
nothing
=> fix some minor things

declarations/WebpackOptions.d.ts, lib/Chunk.js, lib/ChunkGraph.js, lib/JavascriptModulesPlugin.js, lib/node/NodeTemplatePlugin.js, lib/node/ReadFileChunkLoadingRuntimeModule.js, lib/node/RequireChunkLoadingRuntimeModule.js, lib/util/compileBooleanMatcher.js, lib/web/JsonpChunkLoadingRuntimeModule.js, schemas/WebpackOptions.json, test/ConfigTestCases.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/compileBooleanMatcher.unittest.js, test/configCases/custom-source-type/localization/content.loc, test/configCases/custom-source-type/localization/content2.loc, test/configCases/custom-source-type/localization/index.js, test/configCases/custom-source-type/localization/normal.js, test/configCases/custom-source-type/localization/normal2.js, test/configCases/custom-source-type/localization/webpack.config.js
allow custom module types in rules
allow configCases to access stats
features
yes
yes
nothing
=> don't emit and load JS files for chunks without JS modules

declarations/WebpackOptions.d.ts, lib/WebpackOptionsValidationError.js, schemas/WebpackOptions.json, test/Validation.test.js
improvement of errors
yes
no
nothing
=> improve validation errors and tests

lib/WebpackOptionsDefaulter.js, test/TestCases.template.js, test/configCases/plugins/progress-plugin/index.js, test/configCases/plugins/progress-plugin/webpack.config.js
defaults change
no
yes
`node.__filename`, `node.__dirname` and `node.global` defaults to `false` in node.js targets
=> disable node stuff in node targets

lib/optimize/ConcatenatedModule.js, test/cases/scope-hoisting/side-effects-9159/index.js, test/cases/scope-hoisting/side-effects-9159/package/index.js, test/cases/scope-hoisting/side-effects-9159/package/module.js, test/cases/scope-hoisting/side-effects-9159/package/package.json, test/cases/scope-hoisting/side-effects-9159/reexport.js
fixes #9159
bugfix
yes
no
nothing
=> fix concatenated version of reexport dependency for sideEffects

lib/HotModuleReplacement.runtime.js, test/hotCases/recover/recover-after-removal-self-accepted/index.js, test/hotCases/recover/recover-after-removal-self-accepted/inner.js, test/hotCases/recover/recover-after-removal-self-accepted/module.js
fixes #9198
bugfix
yes
no
nothing
=> fix rejection when removing and readding self-accepted module

declarations/WebpackOptions.d.ts, lib/NormalModuleFactory.js, lib/WebpackOptionsDefaulter.js, schemas/WebpackOptions.json, test/TestCases.template.js, test/Validation.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/mjs/esm-by-default/index.js, test/configCases/mjs/esm-by-default/index.mjs, test/configCases/mjs/esm-by-default/webpack.config.js
feature
yes
yes
* New `experiments` config root option
* Lists experimental features
* Experimental features here have relaxed SemVer. They may have breaking changes in minor versions.
* When using fix webpack version to minor i. e. => `~5.4.3` instead of `^5.4.3` or use a lockfile.
* New `experiments.mjs` option which enabled `.mjs` support
=> add experiments.mjs config option

lib/optimize/SplitChunksPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/split-chunks-keep-remaining-size/c.js
bugfix
yes
yes
`minRemainingSize` is only active when a single chunk remains
=> disable splitChunks.minRemainingSize for multiple selected chunks

lib/Dependency.js, lib/FlagDependencyExportsPlugin.js, lib/dependencies/HarmonyExportImportedSpecifierDependency.js, lib/dependencies/HarmonyImportDependency.js, lib/dependencies/HarmonyImportSpecifierDependency.js, lib/dependencies/HarmonyModulesPlugin.js, lib/dependencies/ImportPlugin.js, lib/dependencies/StaticExportsDependency.js, lib/dependencies/SystemPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap, test/cases/json/import-by-name-with-concatenation/warnings.js, test/cases/json/import-by-name/warnings.js, test/cases/mjs/cjs-import-default/errors.js, test/cases/parsing/harmony-info/warnings.js, test/cases/scope-hoisting/json-reexport-6700/warnings.js, test/configCases/split-chunks/module-type-filter/index.js
fixes #9246
spec alignment
yes
yes
Only the default export of JSON modules can be used without warning
=> Add warnings for non-default imports from json modules

lib/dependencies/HarmonyExportImportedSpecifierDependency.js, lib/dependencies/HarmonyImportSpecifierDependency.js, test/cases/mjs/cjs-import-default/errors.js
=> fix(mjs): remove harmony unused build errors

hot/dev-server.js, hot/log.js, hot/only-dev-server.js, hot/poll.js, hot/signal.js
in Firefox stack doesn't include the message
fixes #6589
bugfix
no
no
nothing
=> fix error message and stack in Firefox

lib/Parser.js, test/cases/parsing/block-scopes/index.js, test/cases/parsing/block-scopes/module.js
fixes #9253
fixes #9183
bugfix
yes
bugfix
nothing
=> handle block scopes correctly

test/TestCases.template.js
=> shorter timeouts for cached builds

declarations/plugins/IgnorePlugin.d.ts, lib/AsyncDependenciesBlock.js, lib/AsyncDependencyToInitialChunkError.js, lib/Chunk.js, lib/ChunkGroup.js, lib/ChunkTemplate.js, lib/Compilation.js, lib/ContextModule.js, lib/Dependency.js, lib/ExternalModule.js, lib/HotModuleReplacementPlugin.js, lib/IgnorePlugin.js, lib/SourceMapDevToolPlugin.js, lib/SystemMainTemplatePlugin.js, lib/dependencies/ContextDependency.js, lib/dependencies/ContextDependencyHelpers.js, lib/dependencies/ImportDependenciesBlock.js, lib/dependencies/ImportParserPlugin.js, lib/optimize/SplitChunksPlugin.js, lib/rules/UseEffectRulePlugin.js, lib/stats/DefaultStatsFactoryPlugin.js, lib/util/deprecation.js, lib/wasm/WebAssemblyGenerator.js, package.json, schemas/plugins/IgnorePlugin.json, test/Examples.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/ignore/checkContext/webpack.config.js
refactoring
existing test
yes
* IgnorePlugins `checkContext` was removed
* Chunk.files is now a Set
=> add more types and fix/remove TODOs

.travis.yml, appveyor.yml, azure-pipelines.yml
run on nightly node.js 13
CI
CI
no
nothing
=> node.js 12 is latest now

lib/optimize/EnsureChunkConditionsPlugin.js
This PR removes an unused check for `changed` beause this is always `false` as it seems and never executed.
Bugfix
No
No
=> fix: remove unused check for changed which always evaluates to false

lib/dependencies/HarmonyExportImportedSpecifierDependency.js, lib/optimize/SplitChunksPlugin.js, lib/stats/DefaultStatsPrinterPlugin.js
This PR removes duplicate code blocks in a condition and in a few switch-case statements.
Bugfix
No
No
=> fix: remove duplicate code blocks in condition and switch-case

lib/DelegatedModuleFactoryPlugin.js
There is a duplicate boolean check for `request` whcih can be removed.
Bugfix
No
No
=> fix: remove redundant boolean check of request variable

lib/optimize/SplitChunksPlugin.js, test/configCases/split-chunks/reuse-chunk-name/b.js, test/configCases/split-chunks/reuse-chunk-name/c.js, test/configCases/split-chunks/reuse-chunk-name/index.js, test/configCases/split-chunks/reuse-chunk-name/test.config.js, test/configCases/split-chunks/reuse-chunk-name/webpack.config.js
fixes #9288
bugfix
yes
no
nothing
=> fix chunk name reuse in SplitChunks

lib/OptionsDefaulter.js
https://github.com/webpack/webpack/issues/3277
documentation
No
No
Nothing  🤗
=> refactor(esdoc): OptionsDefaulter

declarations/WebpackOptions.d.ts, lib/Chunk.js, lib/optimize/SplitChunksPlugin.js, lib/runtime/GetChunkFilenameRuntimeModule.js, schemas/WebpackOptions.json, test/Validation.test.js, test/configCases/split-chunks/custom-filename-function/a.js, test/configCases/split-chunks/custom-filename-function/b.js, test/configCases/split-chunks/custom-filename-function/test.config.js, test/configCases/split-chunks/custom-filename-function/webpack.config.js
fixes #9296
bugfix
yes
no
`splitChunks.filename` also supports functions like `output.filename`
=> allow filename as function at more places

CONTRIBUTING.md
The Webpack documentation website has a **ton** of open issues. Linking to it in the Webpack CONTRIBUTING.md file will help interested individuals find a way to help out. I noticed earlier today that the two weren't linked and thought I'd get everyone's thoughts on whether this is a good thing to do or not.
Docs update
N/A
No
Nothing
=> docs: Update CONTRIBUTING.md with current documentation issues location

README.md
This PR updates the outdated URLs of the links to the plugins and loaders.
documentation
N/A
N/A
N/A
=> docs(README): update URLs of plugins and loaders

.eslintrc.js, package.json
This PR removes the references to the `buildin` folder which was removed in the `next` branch.
chore
N/A
N/A
N/A
=> chore: remove references to buildin folder

open-bot.yaml
This PR fixes a small typo in the open-bot texts.
bugfix
No
No
=> fix: small typo in open-bot config

declarations/WebpackOptions.d.ts, schemas/WebpackOptions.json, test/Validation.test.js
fixes #9320
feature.  `realResource` parameter added to `RuleSetRule`
No
No
`Rule.realResource` parameter, I think it's a part of this doc page https://webpack.js.org/configuration/module/
=> add realResource parameter to RuleSetRule

declarations/WebpackOptions.d.ts, package.json, schemas/WebpackOptions.json, test/configCases/ignore/false-alias/ignored-module.js, test/configCases/ignore/false-alias/normal-module.js, test/configCases/ignore/false-alias/test.js, test/configCases/ignore/false-alias/webpack.config.js, test/configCases/resolve/multi-alias/a/1.js, test/configCases/resolve/multi-alias/b/2.js, test/configCases/resolve/multi-alias/index.js, test/configCases/resolve/multi-alias/webpack.config.js, yarn.lock
feature
yes
no
`resolve.alias` now supports:
* false: to ignore a module (replaced with empty module)
* array of strings: to offer multiple alternatives with are tried. Makes most sense when different subpaths.
=> add alias to false (ignore) and alias to array

.eslintrc.js, lib/OptionsDefaulter.js, lib/Template.js, lib/util/createHash.js, lib/util/objectToMap.js, lib/wasm/WebAssemblyGenerator.js, package.json, yarn.lock
Enforcing rule `jsdoc/require-hyphen-before-param-description`
https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-require-hyphen-before-param-description
feature
No
No
Nothing
=> enforce eslint require-hyphen-before-param-description

lib/Compilation.js, lib/optimize/SplitChunksPlugin.js, package.json, yarn.lock
=> avoiding v8 deopts

lib/SourceMapDevToolPlugin.js
https://github.com/webpack/webpack/issues/3277
documentation
No
No
Nothing
=> esdoc(SourceMapDevToolPlugin): add some esdoc definitions

examples/README.md, examples/typescript/README.md, examples/typescript/build.js, examples/typescript/example.js, examples/typescript/index.ts, examples/typescript/template.md, examples/typescript/tsconfig.json, examples/typescript/webpack.config.js, package.json, yarn.lock
close #9275 
Because there is no typescript example.
no, because example.
no
no, because it is added in exmaple/README with this PR.
=> add TypeScript example

codecov.yml, package.json, tooling/type-coverage.js, yarn.lock
This PR allows to run `yarn type-report` to get a type coverage report.
contributing
N/A
no
nothing
=> add type coverage report

lib/rules/RuleSetCompiler.js, test/configCases/rule-set/undefined-values/index.js, test/configCases/rule-set/undefined-values/webpack.config.js
see regression https://github.com/webpack/webpack/issues/8537#issuecomment-508451734
bugfix
yes
no
nothing
=> skip over undefined properties in rules

declarations/WebpackOptions.d.ts, schemas/WebpackOptions.json
https://github.com/webpack/webpack/issues/9404
fix webpack options
No
Yes, changed 2 optional parameters
`ResolveOptions.alias`
=> fix ResolveOptions.alias

.eslintrc.js, declarations/WebpackOptions.d.ts, lib/AbstractMethodError.js, lib/Compilation.js, lib/HashedModuleIdsPlugin.js, lib/JavascriptModulesPlugin.js, lib/ModuleFilenameHelpers.js, lib/NamedModulesPlugin.js, lib/NormalModule.js, lib/util/createHash.js, schemas/WebpackOptions.json, test/AbstractMethodError.unittest.js
https://github.com/webpack/webpack/issues/9196
esdoc
No
No
Nothing
=> esdoc(createHash)

lib/stats/DefaultStatsPrinterPlugin.js, test/StatsTestCases.test.js, test/__snapshots__/StatsTestCases.test.js.snap
improve tests for timings
see https://twitter.com/srl295/status/1149775046329737220
performance
yes
a really small one, printing of time differs a little bit
nothing
=> improve performance of date time formating

lib/FileSystemInfo.js, lib/cache/ResolverCachePlugin.js, lib/util/findGraphRoots.js, tooling/type-coverage.js
=> adding some random types

declarations/WebpackOptions.d.ts, lib/Compilation.js, lib/Template.js, schemas/WebpackOptions.json, test/configCases/asset-modules/assetModuleFilename/index.js, test/configCases/asset-modules/assetModuleFilename/webpack.config.js
Add `name` option of file-loader to `assetModuleFilename` as a Function.
feature
yep
no
assetModuleFilename
=> feat(assetModule): add function type to assetModuleFilename

lib/ProgressPlugin.js, lib/SourceMapDevToolPlugin.js
#9460
performance
existing tests
no
nothing
=> fix low hanging performance problems with ProgressPlugin

lib/ChunkGroup.js, lib/ProgressPlugin.js, lib/SourceMapDevToolPlugin.js, lib/stats/DefaultStatsFactoryPlugin.js, lib/stats/StatsFactory.js, lib/stats/StatsPrinter.js, lib/util/createHash.js
performance
existing tests
yes
nothing
=> fix low hanging webpack 5 performance problems

lib/Chunk.js, lib/Compilation.js, lib/WebpackOptionsApply.js, lib/WebpackOptionsDefaulter.js, lib/cache/IdleFileCachePlugin.js, lib/dependencies/HarmonyImportSpecifierDependency.js, lib/util/deprecation.js, test/__snapshots__/StatsTestCases.test.js.snap
performance
existing tests
no
default for `cache.idleTimeout` is now 60s
=> Fix low hanging webpack 5 performance issues

lib/Compiler.js, lib/Watching.js, lib/cache/ResolverCachePlugin.js, lib/optimize/SplitChunksPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap
logging
yes
no
Enable `stats.loggingDebug: /webpack/` to get core logging.
=> add more timestamp logging to some core parts

lib/Compilation.js, lib/ProgressPlugin.js
=> improve progress plugin performance and display

lib/Compilation.js, lib/stats/DefaultStatsFactoryPlugin.js, lib/stats/DefaultStatsPresetPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap
* add back `stats.cachedAssets`
* fix stats option processing for objects with prototype chain
bugfixes
no
no
nothing
=> fix two minor bugs in webpack 5

lib/Compilation.js
When I read the buildModule logic, I found the logic `record the building time in currentProfile` is duplicate in buildModule's callback and the afterBuild method. So I create this pull request.Just a little
change.
refactoring
no
no
no
=> the duplicate logic in buildModule callback and afterBuild

lib/optimize/ConcatenatedModule.js, test/cases/scope-hoisting/this-in-import/cjs.js, test/cases/scope-hoisting/this-in-import/index.js, test/cases/scope-hoisting/this-in-import/module.js
fixes #9500
bugfix
yes
no
nothing
=> track callContext in ConcatenatedModule

lib/SystemMainTemplatePlugin.js, test/configCases/target/system-named-assets-path/index.js, test/configCases/target/system-named-assets-path/test.config.js, test/configCases/target/system-named-assets-path/webpack.config.js
Standard library name definition
Yep, simply resolve test
I think No
I think No
=> Support for standard naming behavior output:library:"system"

lib/Compiler.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/asset-emitted/futureEmitAssets/index.js, test/configCases/asset-emitted/futureEmitAssets/webpack.config.js, test/configCases/asset-emitted/normal/index.js, test/configCases/asset-emitted/normal/webpack.config.js
Fixes #9299 
bugfix
Nope 
Nope
N/A
=> chore: Makes it easier to access contents of emitted assets

lib/Compiler.js, lib/MultiCompiler.js, lib/ProgressPlugin.js, lib/Stats.js, lib/logging/Logger.js, lib/logging/createConsoleLogger.js, lib/logging/runtime.js, lib/logging/truncateArgs.js, lib/node/NodeEnvironmentPlugin.js, lib/node/nodeConsole.js, test/Compiler.test.js, test/ProgressPlugin.test.js, test/StatsTestCases.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/helpers/LogTestPlugin.js, test/helpers/captureStdio.js, test/statsCases/logging/webpack.config.js, test/statsCases/preset-detailed/webpack.config.js, test/statsCases/preset-errors-only-error/webpack.config.js, test/statsCases/preset-errors-warnings/webpack.config.js, test/statsCases/preset-minimal/webpack.config.js, test/statsCases/preset-none/webpack.config.js, test/statsCases/preset-normal/webpack.config.js, test/statsCases/preset-verbose/webpack.config.js
* Colors
* ProgressPlugin uses infrastructureLogger
* improved formatting of logging output (aligned)
* tests
logging, feature, bugfix
yes
no
* Logger API:
* `Logger.status` writes a temporary message (writing a new one override the last one)
=> Improve infrastructure logging

lib/logging/truncateArgs.js, test/ProgressPlugin.test.js
=> fix 100% progress output

lib/node/nodeConsole.js, test/ProgressPlugin.test.js
fixes #9511
bugfix
yes
no
nothing
=> make status logging 1 char shorter

package.json, yarn.lock
dependencies
existing tests
no
nothing
=> upgrade find-cache-dir

package.json, test/__snapshots__/StatsTestCases.test.js.snap, test/cases/loaders/context/index.js, test/cases/loaders/less-loader/index.js, test/cases/loaders/raw-loader/index.js, yarn.lock
dependencies
existing tests
no
nothing
=> upgrade raw-loader

package.json, yarn.lock
dependencies
existing tests
no
nothing
=> Upgrade eslint-scope

package.json, yarn.lock
dependencies
existing tests
no
nothing
=> Upgrade less-loader

test/Stats.test.js, test/__snapshots__/StatsTestCases.test.js.snap, yarn.lock
deps
existing tests
no
nothing
=> update non-jest dependencies in range

package.json, yarn.lock
dependencies
existing tests
no
nothing
=> Upgrade some jest dependencies in range

package.json, yarn.lock
dependencies
existing tests
no
nothing
=> Ugrade jest-junit

examples/README.md
Added TOC to the docs.
N/A
N/A
Added TOC
=> [Docs]: Added TOC

lib/ChunkGroup.js, lib/Entrypoint.js
Fixes include:-
- typo fixes
- grammatical corrections
refactoring
N/A
Nope
N/A
=> chore: Minor typographical fixes

declarations/WebpackOptions.d.ts, examples/persistent-caching/README.md, examples/persistent-caching/webpack.config.js, lib/WebpackOptionsApply.js, lib/cache/PackFileCacheStrategy.js, lib/cache/SeparateFilesCacheStrategy.js, lib/util/makeSerializable.js, schemas/WebpackOptions.json, test/TestCases.template.js
refactoring
no
yes
* remove cache.loglevel
=> replace logging in persistent caching with infrastructure logger

lib/BannerPlugin.js
=> chore: Minor refactor

lib/JavascriptParser.js, lib/dependencies/ImportParserPlugin.js, lib/dependencies/SystemPlugin.js, package.json, test/JavascriptParser.unittest.js, yarn.lock
deps
exisiting tests
yes, AST change
nothing
=> upgrade acorn to 7

lib/wasm/WebAssemblyGenerator.js
Minor typographical fixes
N/A
N/A
N/A
=> chore(WebAssemblyGenerator): Minor typographical fixes

lib/wasm/WebAssemblyGenerator.js
=> chore(WebAssemblyGenerator): Added type metadata

lib/wasm/WebAssemblyGenerator.js
=> chore: Minor grammatical correction

README.md
<h2>Fixed a grammatical error</h2>
It appears that the verb <strong>improve</strong> should be in the <strong>to-infinitive</strong> form.
Hence, I corrected it by adding <strong>to</strong> before the verb <strong>improve</strong>.
Thanks a lot!!
=> Fixed a grammatical error.

lib/JavascriptParser.js, lib/dependencies/HarmonyImportDependencyParserPlugin.js, lib/dependencies/HarmonyImportSpecifierDependency.js, lib/optimize/ConcatenatedModule.js, test/cases/parsing/harmony-this/abc.js, test/cases/parsing/harmony-this/index.js, test/cases/parsing/harmony-this/new.js, test/cases/parsing/harmony/index.js, test/configCases/parsing/harmony-this-concat/index.js, test/configCases/parsing/harmony-this/index.js
#9615
improvement
yes
no
nothing
=> detect ASI and generate more efficient code when no semicolon need to be inserted

lib/Parser.js
Fix the typo.
No, it's not needed.
No.
Nothing.
=> Fix the typo in Parser.js

lib/optimize/InnerGraphPlugin.js, test/cases/inner-graph/pure-in-removed/import-module.js, test/cases/inner-graph/pure-in-removed/index.js, test/cases/inner-graph/pure-in-removed/module.js
=> avoid adding dependencies in pre walk, branch might be skipped

lib/FileSystemInfo.js, test/fixtures/buildDependencies/run.js
=> Fixes to managed paths and build dependencies

lib/JavascriptParser.js, lib/optimize/InnerGraphPlugin.js, test/cases/inner-graph/try-globals/import-module.js, test/cases/inner-graph/try-globals/index.js, test/cases/inner-graph/try-globals/module.js
it also fixes scoping in try catch blocks
bugfix
yes
no
nothing
=> only handle defined variables as pure expressions

lib/SourceMapDevToolPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap
improvement
existing tests
yes
nothing
cc @evilebottnawi
=> SourceMapDevTool applies to all assets and adds auxiliary files to chunks

lib/Compilation.js, test/configCases/emit-asset/different-source/index.js, test/configCases/emit-asset/different-source/test1.txt, test/configCases/emit-asset/different-source/test2.txt, test/configCases/emit-asset/different-source/warnings.js, test/configCases/emit-asset/different-source/webpack.config.js, test/configCases/emit-asset/equal-source/index.js, test/configCases/emit-asset/equal-source/test1.txt, test/configCases/emit-asset/equal-source/test2.txt, test/configCases/emit-asset/equal-source/webpack.config.js
check source content to when comparing assets for warning
bugfix
fixes #9692, fixes #9693, fixes #9694
yes
no
nothing
=> make multiple assets to the same filename a warning

lib/performance/SizeLimitsPlugin.js
Related: https://github.com/vuejs/vue-cli/issues/4572
Bugfix
Not sure how to get a minimum reproduction of this case but it's an emergency fix.
No
N/A
=> fix: check for asset nullity before fileFilter

lib/logging/Logger.js
See [this comment](https://github.com/microsoft/TypeScript/pull/33411#discussion_r324371317) - the type is incorrect for what's desired here.
Types changes.
=> Fix `LogTypeEnum` typedef

lib/HotModuleReplacementPlugin.js, test/hotCases/child-compiler/issue-9706/file.js, test/hotCases/child-compiler/issue-9706/index.js, test/hotCases/child-compiler/issue-9706/report-child-assets-loader.js
fixes #9706
bugfix
yes
I don't think so, but there might be some weird use cases that are affected...
nothing
=> HMR plugin should only affect the root compilation

lib/Chunk.js, lib/optimize/LimitChunkCountPlugin.js, lib/util/LazyBucketSortedSet.js
- Prepare chunk compares to avoid comparing chunks over and over
- Uses bucket sort to improve sorting performance
- Try to process multiple chunk merges in a single run when possible
fixes #9703
performance
existing tests
no
nothing
=> Improve performance of LimitChunkCountPlugin a lot

lib/WebpackOptionsValidationError.js, schemas/WebpackOptions.json, test/Schemas.lint.js, test/Validation.test.js
This is a potential config error
fixes #9722
validation
yes
yes, but only when a user made a potential config error
nothing
=> disallow shorthand cache groups syntax with cache group named test

_SETUP.md
add `_SETUP.md` update example use
Yes
No
Nothing
=> docs(_SETUP.md): add update example use

lib/optimize/InnerGraphPlugin.js, test/cases/inner-graph/circular/chunk.js, test/cases/inner-graph/circular/index.js, test/cases/inner-graph/circular/inner.js, test/cases/inner-graph/circular/module.js, test/cases/inner-graph/pure-in-removed/import-module.js, test/cases/inner-graph/simple/index.js, test/cases/inner-graph/simple/inner.js, test/cases/inner-graph/simple/module.js, test/cases/inner-graph/static-of-class/chunk.js, test/cases/inner-graph/static-of-class/import-module.js, test/cases/inner-graph/static-of-class/index.js, test/cases/inner-graph/static-of-class/module-unused.js, test/cases/inner-graph/static-of-class/module-used.js, test/cases/inner-graph/static-of-class/other/module-unused.js, test/cases/inner-graph/static-of-class/other/module-used.js, test/cases/inner-graph/static-of-class/other/package.json, test/cases/inner-graph/switch/chunk.js, test/cases/inner-graph/switch/import-module.js, test/cases/inner-graph/switch/index.js, test/cases/inner-graph/switch/module.js, test/cases/inner-graph/switch/some-module.js
=> fix handling of circular references in the inner graph

lib/optimize/InnerGraphPlugin.js, test/cases/inner-graph/circular2/index.js, test/cases/inner-graph/circular2/module.js, test/fixtures/temp-watch-1569996664301/bundle.js
=> fix infinite loop on circular inner graph references

lib/RequestShortener.js, test/RequestShortener.unittest.js
Fix https://github.com/webpack/webpack/issues/9764
bugfix
No
=> Fix incorrect path cropping in RequestShortener

lib/ProgressPlugin.js, lib/stats/DefaultStatsFactoryPlugin.js, lib/stats/DefaultStatsPresetPlugin.js, lib/stats/DefaultStatsPrinterPlugin.js, test/ProgressPlugin.test.js, test/Stats.test.js, test/__snapshots__/StatsTestCases.test.js.snap
DX
yes updated the snapshots
yes
* New options: `stats.ids`, `stats.chunkModulesSort`, `stats.chunkRootModulesSort`, `stats.nestedModulesSort`
=> improve developer experience

lib/util/internalSerializables.js, lib/util/serialization.js, tooling/format-file-header.js
this allows ncc to upgrade
refactoring
existing tests
no
nothing
=> avoid a dynamic require in lib/util/serialization

lib/JavascriptParser.js, test/cases/parsing/issue-9817/index.js, test/cases/parsing/issue-9817/langs/en.js, test/cases/parsing/issue-9817/lo.js
fixes #9817
bugfix
yes
no
nothing
=> set wrapped inner expression in concat parsing

lib/JavascriptParser.js, package.json, yarn.lock
https://github.com/webpack/webpack/issues/9196
types
No
No
Nothing
=> add types to JavascriptParser

.travis.yml, appveyor.yml
=> Merge v4.41.2 into master

lib/Chunk.js, lib/Compilation.js, lib/JavascriptModulesPlugin.js, lib/Template.js, lib/asset/AssetModulesPlugin.js, lib/ids/IdHelpers.js, lib/stats/DefaultStatsFactoryPlugin.js, lib/wasm-async/AsyncWebAssemblyModulesPlugin.js, lib/wasm/WasmChunkLoadingRuntimeModule.js, lib/wasm/WebAssemblyModulesPlugin.js, test/StatsTestCases.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/dll-plugin-entry/1-use-dll/index.js, test/configCases/dll-plugin/1-use-dll/index.js, test/configCases/dll-plugin/2-use-dll-without-scope/index.js, test/configCases/errors/self-reexport/errors.js, test/statsCases/named-chunks-plugin-async/webpack.config.js
sort modules by identifier in output file, that's better for gzip
bugfix, optimization
existing
no
nothing
=> fix badly chosen max fill rate for deterministic

CONTRIBUTING.md, README.md
Replaced HTTP links to HTTPS links for consistency
Refactor HTTP links in some Markdown files to HTTPS :)
I don't think changes to Markdown files need tests? If I'm wrong please guide me on how to write one :sweat_smile:
No, it's just minor changes.
Nothing that I know of, since it's just minor Markdown changes.
=> Replace HTTP with HTTPS in README.md and CONTRIBUTING.md

open-bot.yaml
=> allow bot to handle backporting requests

lib/FileSystemInfo.js
types and code explanation
no
no
nothing
=> types(FileSystemInfo): minor types and code explanation

lib/DependencyTemplate.js, lib/Generator.js, lib/Module.js, lib/ModuleFactory.js, lib/RuntimeModule.js
refactoring. Instead of custom errors use AbstractMethodError
No
No
Nothing
=> Use AbstractMethodError all over the project

declarations/plugins/optimize/LimitChunkCountPlugin.d.ts, lib/optimize/LimitChunkCountPlugin.js, schemas/plugins/optimize/LimitChunkCountPlugin.json
fixes #9734
bugfix, refactoring
No
Yes, it disallow optional parameter
I think [this page](https://webpack.js.org/plugins/limit-chunk-count-plugin/) must be changes regarding to this changes
=> fix: Limit chunk count plugin

azure-pipelines.yml, package.json
deps
CI
yes
min node.js version is 10.16.3
=> increase minimum node.js version to 10

lib/buildChunkGraph.js
Add variables description for #9749 and remove unnecessary checks
No
No
Nothing
=> add description of module indexes and remove unnecessary checks 

package.json, test/Stats.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/plugins/terser-plugin/webpack.config.js, yarn.lock
deps
existing tests
yes
nothing
=> upgrade terser-webpack-plugin

lib/WebpackOptionsDefaulter.js, package.json, test/__snapshots__/StatsTestCases.test.js.snap, yarn.lock
- No need options for `terser-webpack-plugin`
- No deprecation warnings 
refactor
existing tests
No
=> chore(deps): update `terser-webpack-plugin`

lib/FileSystemInfo.js
performance
existing tests
no
nothing
=> improve performance for snapshot validation for repeated snapshots

lib/ChunkGraph.js, lib/Compilation.js, lib/FlagDependencyExportsPlugin.js, lib/ids/IdHelpers.js, lib/util/LazySet.js
* flatten LazySet before merging to find duplicate inner Sets
* return early in `avoidNumber` when string can't be a number
* improved assignDepth performance by iterating ModuleGraph instead of dependencies
* hoist comparators
* inline cache ChunkGraph attached data access
performance
existing tests
no
nothing
=> Smaller performance improvements

lib/node/NodeWatchFileSystem.js, package.json, yarn.lock
performance
existing tests
Yes, FileSystemInfo.addFile/ContextTimestamps may take ownership of the passed Map
nothing
=> Performance of watcher

lib/web/JsonpChunkLoadingRuntimeModule.js, lib/web/JsonpTemplatePlugin.js, test/Stats.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/web/retry-failed-import/chunk.js, test/configCases/web/retry-failed-import/index.js, test/configCases/web/retry-failed-import/webpack.config.js
=> fix problem with retrying import()

lib/javascript/JavascriptParser.js, test/cases/parsing/import-define/index.js, test/cases/parsing/import-define/module.js
=> fix bug where importing variables with special free names is broken

declarations/WebpackOptions.d.ts, lib/Compilation.js, lib/Compiler.js, lib/FileSystemInfo.js, lib/WebpackOptionsDefaulter.js, lib/cache/ResolverCachePlugin.js, lib/serialization/BinaryMiddleware.js, lib/serialization/ObjectMiddleware.js, lib/stats/DefaultStatsFactoryPlugin.js, lib/stats/DefaultStatsPrinterPlugin.js, lib/util/LazySet.js, lib/util/fs.js, lib/util/internalSerializables.js, schemas/WebpackOptions.json, test/Compiler-caching.test.js, test/Compiler.test.js, test/Errors.test.js, test/Stats.test.js, test/StatsTestCases.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/aggressive-splitting-entry/webpack.config.js, test/statsCases/filter-warnings/webpack.config.js, test/statsCases/runtime-chunk-integration/webpack.config.js
* add logging to FileSystemInfo to print out which file caused snapshot invalidation
* use LazySet in ResolverCachePlugin
* do not emit immutable files when this file already exists on disk
* do not emit files if the same file with the same content already exists on disk
performance
existing tests
yes
OutputFileSystem also need `stat` and `readFile` to check for existing files
* webpack may not write output files when file already exists on disk with the same content
=> Many small performance improvements

test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/commons-plugin-issue-4980/webpack.config.js
=> improve test stability

test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/define-plugin/webpack.config.js, test/statsCases/limit-chunk-count-plugin/webpack.config.js, test/statsCases/named-chunk-groups/webpack.config.js, test/statsCases/preset-mixed-array/webpack.config.js, test/statsCases/preset-none-array/webpack.config.js, test/statsCases/scope-hoisting-multi/webpack.config.js, test/statsCases/split-chunks/webpack.config.js
=> avoid writing to same filename in array config

declarations/plugins/ProgressPlugin.d.ts, lib/ProgressPlugin.js, lib/util/AsyncQueue.js, schemas/plugins/ProgressPlugin.json, test/ProgressPlugin.test.js
* fix bug causing ProgressPlugin to write to often to stderr
* show queued dependencies in progress
* replace process.nextTick with setImmediate in queue processing to keep event loop looping
bugfix, performance
yes
yes, progress plugin shows different info now
nothing
=> Performance and ProgressPlugin

lib/ExternalModuleFactoryPlugin.js
Hoist RegExp literal outside of potential loops or logic checks.
refactoring
N/A
NO
N/A
=> feat(perf): hoist regexp literal

package.json
https://github.com/npm/cli/pull/273
More funding infromation
not required
No
Nothing
=> chore: add funding field to `package.json`

azure-pipelines.yml
Features:
- use `latest` os for better compatibility with development environments (developers other use latest versions)
- test on node@13
Also we can try to setup cache for yarn https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops, it should be give small speedup for CI, i can improve that if you approve
improve CI
not required
No
Nothing
=> ci: improve

lib/Cache.js, lib/Compilation.js, lib/ProgressPlugin.js, lib/SourceMapDevToolPlugin.js, lib/cache/MemoryCachePlugin.js, lib/cache/PackFileCacheStrategy.js, lib/cache/getLazyHashedEtag.js, test/ProgressPlugin.test.js
=> feat: support caching in SourceMapDevToolPlugin

azure-pipelines.yml
Cache for azure pipelines
CI improvement
Not required
No
Nothing
=> ci: azure-pipelines cache

lib/cache/ResolverCachePlugin.js, lib/serialization/ObjectMiddleware.js, lib/util/registerExternalSerializer.js, package.json, yarn.lock
* faster object type lookup during deserialization
* fix cacheWithContext inversion
* more space-efficient ReplaceSource serialization
* upgrade webpack-sources to get rid of large string warnings for source maps
performance
existing tests
no
nothing
=> Performance

lib/Chunk.js, lib/ChunkGraph.js, lib/FileSystemInfo.js, lib/ModuleGraph.js, lib/RuntimePlugin.js, lib/util/internalSerializables.js, test/__snapshots__/StatsTestCases.test.js.snap
=> Bugfixes from beta feedback

lib/WebpackOptionsDefaulter.js, test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/split-chunks-chunk-name/index.js, test/statsCases/split-chunks-chunk-name/node_modules/a.js, test/statsCases/split-chunks-chunk-name/node_modules/b.js, test/statsCases/split-chunks-chunk-name/node_modules/c.js, test/statsCases/split-chunks-chunk-name/webpack.config.js
this allows the user to specify chunk names
bugfix
yes
yes
nothing
=> allow default vendors splitChunk setting to reuse existing chunks

lib/NormalModuleFactory.js
Refactoring to getting cache for generator/parser in module/factory
No
No
Nothing
=> Improve getting generator/parse cache in module factory

lib/ContextModule.js, lib/Module.js, lib/ModuleGraph.js, lib/NormalModule.js, lib/RuntimeTemplate.js, lib/dependencies/HarmonyExportImportedSpecifierDependency.js, lib/dependencies/HarmonyImportDependency.js, lib/json/JsonParser.js, lib/optimize/ConcatenatedModule.js, test/cases/mjs/namespace-object-lazy/index.mjs
* rename exportsType named to default
* generate correct fake namespace object for `default` exportsType when in strict ESM
* Generator.generate may return null
* types for NormalModule constructor
refactor/rename
existing tests
yes
nothing
=> Rename exportsType "named" -> "default"

lib/ChunkGraph.js, lib/asset/AssetModulesPlugin.js, lib/javascript/JavascriptModulesPlugin.js
refactor, performance
existing tests
no
nothing
=> offer cached methods to get chunk modules by source type

package.json, setup/setup.js
Just an change to the setup.js File! as I was working in it ! I saw one of the anonymous function has an useless variable!
Code-Enhancement
=> Setup.js Extra Variables

declarations.d.ts, declarations/WebpackOptions.d.ts, lib/Compilation.js, lib/MultiCompiler.js, lib/NormalModuleFactory.js, lib/hmr/HotModuleReplacement.runtime.js, lib/hmr/JavascriptHotModuleReplacement.runtime.js, lib/wasm/WebAssemblyGenerator.js, lib/webpack.js, schemas/WebpackOptions.json
=> improve types

lib/Template.js, test/Stats.test.js, test/__snapshots__/StatsTestCases.test.js.snap
improvement
existing tests
no
nothing
=> generate arrow functions to wrap runtime modules

package.json, yarn.lock
dependency update, this update includes a security fix for https://github.com/advisories/GHSA-h9rv-jmmf-4pgx
no
no
nothing
=> Fix regular expressions Cross-Site Scripting (XSS) vulnerability

package.json
fixes #10008
chore
no required
No
Nothing
=> chore: `funding` field

examples/persistent-caching/README.md, examples/persistent-caching/example.js, examples/persistent-caching/template.md, lib/Compilation.js, lib/ModuleStoreError.js, lib/optimize/ConcatenatedModule.js, lib/optimize/ModuleConcatenationPlugin.js, lib/util/internalSerializables.js, package.json, test/TestCasesCachePack.test.js, test/__snapshots__/StatsTestCases.test.js.snap, yarn.lock
Persistent cache for concat modules
Closes [this card](https://github.com/webpack/webpack/projects/5#card-28793535)
refactoring
no need
no
no
=> persistent cache for concat modules

lib/wasm/WebAssemblyModulesPlugin.js
fixes #9859 
chore
Existing test
No
Nothing
=> Backport lazy require webassemblyjs using modules to webpack-4

lib/optimize/SideEffectsFlagPlugin.js, test/cases/side-effects/wrong-module-10146/index.js, test/cases/side-effects/wrong-module-10146/module/A/A.js, test/cases/side-effects/wrong-module-10146/module/A/index.js, test/cases/side-effects/wrong-module-10146/module/index.js, test/cases/side-effects/wrong-module-10146/module/package.json
This PR fixes #10144 
bugfix
Yes.
No
=> fix: bundle wrong modules

lib/EvalDevToolModulePlugin.js, lib/EvalSourceMapDevToolPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap
closes [this](https://github.com/webpack/webpack/projects/5#card-28518989) card
no
no
no
=> Add comments to bundle to explain why eval is used for devtool

lib/RuntimeGlobals.js, lib/WebpackOptionsApply.js, lib/prefetch/ChunkPrefetchFunctionRuntimeModule.js, lib/prefetch/ChunkPrefetchPreloadPlugin.js, lib/prefetch/ChunkPrefetchStartupRuntimeModule.js, lib/prefetch/ChunkPrefetchTriggerRuntimeModule.js, lib/web/JsonpChunkLoadingRuntimeModule.js, lib/web/JsonpTemplatePlugin.js, test/__snapshots__/StatsTestCases.test.js.snap
refactoring
existing tests
yes
nothing
=> refactor chunk prefetching/preloading into separate plugin and runtime modules

lib/javascript/JavascriptModulesPlugin.js
=> cache module wrappers in memory

lib/ProgressPlugin.js, package.json, yarn.lock
`--progress --profile` reports timings per plugin or step reported by plugin now
Example:
```
<i> [webpack.Progress] 62ms finish module graph FlagDependencyExportsPlugin
<i> [webpack.Progress] 94ms (-62ms) finish module graph
<i> [webpack.Progress] 47ms chunk graph
<i> [webpack.Progress] 46ms chunk optimization SplitChunksPlugin
<i> [webpack.Progress] 16ms after module and chunk tree optimization
<i> [webpack.Progress] 16ms module id optimization
<i> [webpack.Progress] 109ms module hashing
<i> [webpack.Progress] 292ms code generation
<i> [webpack.Progress] 29ms runtime requirements
<i> [webpack.Progress] 30ms hashing
<i> [webpack.Progress] 148ms chunk assets processing
<w> [webpack.Progress] 2414ms finish assets SourceMapDevToolPlugin abc-38821e3894b8a1d85749.js
<w> [webpack.Progress] …
```
=> improved progress and progress profiling

lib/asset/AssetGenerator.js, test/configCases/asset-modules/opus/errors.js, test/configCases/asset-modules/opus/index.js, test/configCases/asset-modules/opus/webpack.config.js
=> show error when mimetype is missing

lib/dependencies/CommonJsImportsParserPlugin.js, test/cases/cjs-tree-shaking/parsing/index.js, test/cases/cjs-tree-shaking/parsing/module.js, test/cases/cjs-tree-shaking/parsing/nested-require.js
=> fix parsing of requires in requires

lib/optimize/ConcatenatedModule.js, test/configCases/concatenate-modules/rename-10168/A.js, test/configCases/concatenate-modules/rename-10168/B.js, test/configCases/concatenate-modules/rename-10168/C.js, test/configCases/concatenate-modules/rename-10168/D.js, test/configCases/concatenate-modules/rename-10168/E.js, test/configCases/concatenate-modules/rename-10168/all.js, test/configCases/concatenate-modules/rename-10168/index.js, test/configCases/concatenate-modules/rename-10168/webpack.config.js
more detailed tracking of conflicted references
to avoid renaming variables when possible
fixes #10168
improvement
yes
no
nothing
=> improve renaming of variables in concatenated modules

lib/EvalSourceMapDevToolModuleTemplatePlugin.js, lib/SourceMapDevToolPlugin.js, lib/util/identifier.js, package.json, test/StatsTestCases.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/source-map/relative-source-maps-by-loader/index.js, test/configCases/source-map/relative-source-maps-by-loader/loader-no-source-root.js, test/configCases/source-map/relative-source-maps-by-loader/loader-pre-relative.js, test/configCases/source-map/relative-source-maps-by-loader/loader-source-root-2-slash.js, test/configCases/source-map/relative-source-maps-by-loader/loader-source-root-slash.js, test/configCases/source-map/relative-source-maps-by-loader/loader-source-root-source-slash.js, test/configCases/source-map/relative-source-maps-by-loader/loader-source-root.js, test/configCases/source-map/relative-source-maps-by-loader/webpack.config.js, test/statsCases/context-independence/a/chunk.js, test/statsCases/context-independence/a/index.js, test/statsCases/context-independence/a/module.js, test/statsCases/context-independence/b/chunk.js, test/statsCases/context-independence/b/index.js, test/statsCases/context-independence/b/module.js, test/statsCases/context-independence/test.config.js, test/statsCases/context-independence/webpack.config.js, yarn.lock
feature (backported)
yes
no
nothing
=> handle `webpack://` prefix in SourceMap sources

lib/NormalModule.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/source-map/relative-source-maps-by-loader/index.js, test/configCases/source-map/relative-source-maps-by-loader/loader-no-source-root.js, test/configCases/source-map/relative-source-maps-by-loader/loader-pre-relative.js, test/configCases/source-map/relative-source-maps-by-loader/loader-source-root-2-slash.js, test/configCases/source-map/relative-source-maps-by-loader/loader-source-root-slash.js, test/configCases/source-map/relative-source-maps-by-loader/loader-source-root-source-slash.js, test/configCases/source-map/relative-source-maps-by-loader/loader-source-root.js, test/configCases/source-map/relative-source-maps-by-loader/webpack.config.js
=> handle sourceRoot during source map contextify

lib/FlagDependencyExportsPlugin.js, test/hotCases/determinism/issue-10174/deps/a.js, test/hotCases/determinism/issue-10174/deps/b.js, test/hotCases/determinism/issue-10174/deps/c.js, test/hotCases/determinism/issue-10174/hot.js, test/hotCases/determinism/issue-10174/index.js
fixes #10174
bugfix
yes
no
nothing
=> make order of exports in providedExports deterministic

lib/dependencies/HarmonyExportImportedSpecifierDependency.js, test/HotTestCases.template.js, test/hotCases/determinism/issue-10174/deps/a.js, test/hotCases/determinism/issue-10174/deps/b.js, test/hotCases/determinism/issue-10174/deps/c.js, test/hotCases/determinism/issue-10174/hot.js, test/hotCases/determinism/issue-10174/index.js
fixes #10174
bugfix
yes
no
nothing
=> make order of exports determinism for hashing

lib/Watching.js
=> Method name fix

lib/dependencies/HarmonyImportDependency.js, test/TestCases.template.js, test/cases/async-modules/top-level-await-import-async/index.js, test/cases/async-modules/top-level-await-import-async/module.js, test/cases/async-modules/top-level-await-import-async/reexport.js
fixes #10194
bugfix
yes
no
nothing
=> generate await code for import without await too

declarations/plugins/DllPlugin.d.ts, lib/DllPlugin.js, schemas/plugins/DllPlugin.json, test/configCases/dll-plugin-entry/0-create-dll/webpack.config.js, test/configCases/dll-plugin/0-create-dll/webpack.config.js
change
yes
yes, entryOnly is now true by default
DllPlugin entryOnly is now true by default
=> change DllPlugin entryOnly default to true

lib/buildChunkGraph.js, test/cases/wasm/global-refs-imported-global/index.js, test/configCases/chunk-index/order-multiple-entries/webpack.config.js
Fixes include:-
- Typo fixes
- Grammatical corrections
refactoring
N/A
Nope
N/A
=> fix(chore): Minor typographical fixes

lib/ProgressPlugin.js, lib/SourceMapDevToolPlugin.js
refactoring
No needed
No
Nothing
=> Minor fix: redundant default parameters

lib/cache/IdleFileCachePlugin.js
Eliminates a race condition
bugfix
no
no
nothing
=> make sure only a single strategy method is invoked at a time

test/hotCases/harmony/auto-import-default/index.js, test/hotCases/harmony/auto-import/index.js
=> chore(test/hotCases): Minor grammatical fixes 

lib/DelegatedModuleFactoryPlugin.js
- Make use of Array and object destructuring possibilities.
- Use `startsWith()` over `indexOf()`.
- Use template literals.
Nope
Nope
N/A
=> chore(DelegatedModuleFactoryPlugin): Minor code refactor

package.json, yarn.lock
bugfix
existing tests
no
nothing
=> upgrade watchpack

lib/HotModuleReplacementPlugin.js, test/hotCases/numeric-ids/add-remove-chunks/chunk.js, test/hotCases/numeric-ids/add-remove-chunks/chunk2.js, test/hotCases/numeric-ids/add-remove-chunks/file.js, test/hotCases/numeric-ids/add-remove-chunks/index.js, test/hotCases/numeric-ids/add-remove-chunks/module.js, test/hotCases/numeric-ids/production/file.js, test/hotCases/numeric-ids/production/index.js, test/hotCases/numeric-ids/production/webpack.config.js
=> use correct string or number form of chunk id in HMR

lib/Compiler.js, lib/NormalModule.js, lib/RequestShortener.js, lib/optimize/ConcatenatedModule.js, lib/optimize/SplitChunksPlugin.js, lib/stats/DefaultStatsPresetPlugin.js, lib/util/identifier.js, test/Errors.test.js, test/RequestShortener.unittest.js
improve caching of contextify and RequestShortener
feature
no
yes stats output changed
nothing
=> remove special request shortening logic, instead normal relative paths

lib/Watching.js
Bugfix : #10071 
Credits : @simonhowey
No
No
Nothing
=> Fix:10071 - Accept watchOptions.aggregateTimeout be 0

lib/ContextModule.js
=> chore(ContextModule): Fixed minor typos

lib/NormalModule.js
=> chore(NormalModule): refactor code adhering to ES6 semantics

lib/Chunk.js, lib/Compiler.js, lib/ContextModule.js, lib/ContextModuleFactory.js, lib/EnvironmentPlugin.js, lib/ErrorHelpers.js, lib/EvalSourceMapDevToolPlugin.js, lib/LibManifestPlugin.js, lib/MultiStats.js, lib/ProgressPlugin.js, lib/Template.js, lib/WebpackError.js, lib/buildChunkGraph.js, lib/dependencies/RequireContextPlugin.js, lib/ids/OccurrenceModuleIdsPlugin.js, lib/logging/truncateArgs.js, lib/optimize/AggressiveSplittingPlugin.js, lib/optimize/ConcatenatedModule.js, lib/optimize/MinChunkSizePlugin.js, lib/optimize/SplitChunksPlugin.js, lib/performance/SizeLimitsPlugin.js, lib/serialization/Serializer.js, lib/stats/DefaultStatsFactoryPlugin.js, lib/wasm/WebAssemblyGenerator.js, test/Errors.test.js
cleanup, code readablility
existing tests
no
nothing
=> remove Array.prototype.reduce calls to simplify code

lib/Chunk.js
=> fix(Chunk.js): rephrase JSDoc method signature info

lib/FlagUsingEvalPlugin.js, lib/dependencies/HarmonyExportDependencyParserPlugin.js, lib/dependencies/HarmonyImportDependencyParserPlugin.js, lib/optimize/InnerGraph.js, lib/optimize/InnerGraphPlugin.js
=> decouple inner-graph and parser state

lib/ConstPlugin.js, lib/javascript/JavascriptParser.js, test/Compiler.test.js, test/fixtures/asmjs.js
fixes #10283
This PR basically disables the ConstPlugin in asm.js functions.
Yes, but it might not be the best place for it, please let me know if there is a better place.
It should not cause any compatibility problems.
Probably nothing.
=> do not evaluate constants in asm.js, fix IIFE mode detection

lib/dependencies/HarmonyExportDependencyParserPlugin.js, lib/dependencies/HarmonyImportDependencyParserPlugin.js, lib/optimize/InnerGraph.js, lib/optimize/InnerGraphPlugin.js
=> Incapsulate inner graph logic

lib/optimize/ConcatenatedModule.js, test/cases/scope-hoisting/issue-10308/commonjs.js, test/cases/scope-hoisting/issue-10308/external.js, test/cases/scope-hoisting/issue-10308/index.js, test/cases/scope-hoisting/issue-10308/root.js
fixes #10308
bugfix
yes
no
nothing
=> fix bug with renaming of variables in concatenated modules

lib/ChunkGraph.js, lib/Compilation.js, lib/ContextModule.js, lib/DelegatedModule.js, lib/DllModule.js, lib/ExternalModule.js, lib/FileSystemInfo.js, lib/Module.js, lib/NormalModule.js, lib/buildChunkGraph.js, lib/cache/PackFileCacheStrategy.js
performance
existing tests
no
nothing
=> Performance improvements of cache builds

lib/WebpackOptionsDefaulter.js, test/WebpackOptionsDefaulter.unittest.js, test/__snapshots__/StatsTestCases.test.js.snap, test/cases/inner-graph/circular/index.js, test/cases/inner-graph/simple/index.js, test/cases/parsing/harmony-deep-exports/index.js
change
existing tests
yes
TODO
=> enable optimization.sideEffects, innerGraph and usedExports by default

lib/Compilation.js, lib/FlagDependencyExportsPlugin.js, lib/FlagDependencyUsagePlugin.js, lib/ModuleGraphConnection.js, lib/cache/PackFileCacheStrategy.js, lib/dependencies/HarmonyImportSideEffectDependency.js, lib/logging/Logger.js, lib/optimize/InnerGraphPlugin.js, lib/optimize/SideEffectsFlagPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap
performance, logging
existing tests
no
nothing
=> Performance and time logging

declarations/WebpackOptions.d.ts, lib/FileSystemInfo.js, lib/buildChunkGraph.js, lib/optimize/SplitChunksPlugin.js, schemas/WebpackOptions.json, test/__snapshots__/StatsTestCases.test.js.snap, test/statsCases/optimize-chunks/webpack.config.js
* Snapshots dedupe themselve during capturing
* chunk graph building avoids copying availableModules much longer (more lazy)
* Use bigint for faster chunk key
performance
existing tests
no
nothing
=> Performance improvement

lib/serialization/FileMiddleware.js
add format information, minor code refactoring
no
no
nothing
=> refactor(FileMiddleware): add format information, minor code refactoring

lib/javascript/JavascriptParser.js
=> chore(JavascriptParser.js): Minor enhancements

lib/dependencies/HarmonyImportDependencyParserPlugin.js, lib/dependencies/PureExpressionDependency.js, lib/optimize/InnerGraph.js, lib/optimize/InnerGraphPlugin.js
refactoring
It's about [this](https://github.com/webpack/webpack/projects/5#card-30668313) card
no
no
no
=> Usage callbacks on inner graph

lib/serialization/BinaryMiddleware.js
=> refactor BinaryMiddleware

lib/Chunk.js
refactoring
no
yes, removeGroup and addGroup have no longer return values
nothing
=> refactor(Chunk): use only delete method instead of `has`,`delete` chain

declarations.d.ts
=> Fix branding guide violation

lib/DefinePlugin.js
Fix to Branding guide violation
Not Required
No
No explicit documentation required to explain changes
=> Fix branding violation

lib/NormalModule.js
Minor code refactor
Not needed
No
None
=> Minor code refactoring to use destructuring

examples/asset-advanced/README.md, examples/asset-advanced/template.md
Some english changes to improve readme
=> Minor grammatical fix

lib/cache/ResolverCachePlugin.js
=> Branding guide violation

declarations.d.ts
The motivation of this PR is to complete the TODO in the following code:
https://github.com/webpack/webpack/blob/master/declarations.d.ts#L10-L17
Now that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38753
has been merged, it makes sense to do this.
refactor
No
I'm not too sure about this. Hopefully someone with more context can help shed some light on this.
I don't think this should require any doc updates
=> remove unnecessary ts def

declarations.d.ts, lib/config/defaults.js
feature
yes manually
no
We support yarn 2 for persistent caching
=> improve caching support for PnP version 3 (yarn 2 berry)

azure-pipelines.yml, declarations/WebpackOptions.d.ts, lib/config/normalization.js, lib/validateSchema.js, schemas/WebpackOptions.json, test/Defaults.unittest.js, test/Validation.test.js
* remove serve property from options
* Add "did you mean" to schema validation for common errors
feature, removal
yes
yes
`serve` property do no longer exist in configuration
=> improve schema and validation

lib/ModuleInfoHeaderPlugin.js, lib/dependencies/HarmonyExportImportedSpecifierDependency.js, lib/dependencies/HarmonyExportInitFragment.js, lib/dependencies/HarmonyExportSpecifierDependency.js, lib/optimize/ConcatenatedModule.js, test/__snapshots__/StatsTestCases.test.js.snap, test/cases/scope-hoisting/circular-root-export/external-ref.js, test/cases/scope-hoisting/circular-root-export/external.js, test/cases/scope-hoisting/circular-root-export/index.js, test/cases/scope-hoisting/circular-root-export/module.js, test/cases/scope-hoisting/circular-root-export/root-ref.js, test/cases/scope-hoisting/circular-root-export/root.js, test/cases/scope-hoisting/issue-10409/a.js, test/cases/scope-hoisting/issue-10409/b.js, test/cases/scope-hoisting/issue-10409/c.js, test/cases/scope-hoisting/issue-10409/cts.js, test/cases/scope-hoisting/issue-10409/index.js, test/cases/scope-hoisting/issue-10409/main.js
=> hoist exports to the top of a concatenated module

lib/optimize/ConcatenatedModule.js, test/__snapshots__/StatsTestCases.test.js.snap, test/cases/errors/harmony-import-missing2/a.js, test/cases/errors/harmony-import-missing2/errors.js, test/cases/errors/harmony-import-missing2/index.js, test/cases/errors/harmony-import-missing2/module1.js, test/cases/errors/harmony-import-missing2/module2.js
fixes some problems introduced by #10426
fixes #10409 for webpack 5
bugfix
yes
no
nothing
=> improve exports hoisting in concatenated modules

lib/asset/AssetGenerator.js, package.json, yarn.lock
refactoring, I think we can use the `mime-types` package directly, without extra packages like `mime` https://github.com/broofa/node-mime, webpack-dev-middleware also migrate on the `mime-types` package. It is also supported by `jshttp` so it should be always up to date.
Existing tests
No
Nothing
=> refactor: migrate on `mime-types`

declarations/plugins/ContainerPlugin.d.ts, lib/container/ContainerEntryDependency.js, lib/container/ContainerEntryModule.js, lib/container/ContainerEntryModuleFactory.js, lib/container/ContainerExposedDependency.js, lib/container/ContainerPlugin.js, lib/container/parseOptions.js, lib/util/internalSerializables.js, schemas/plugins/ContainerPlugin.json, test/configCases/container/container-entry/index.js, test/configCases/container/container-entry/test.js, test/configCases/container/container-entry/test2.js, test/configCases/container/container-entry/webpack.config.js
add a container plugin which enables other Webpack containers to consume modules from remote builds at runtime
```js
new ContainerPlugin({
name: 'website2',
library: 'website2',
filename: 'remoteEntry.js',
libraryTarget: 'global',
shared: {
react: 'react',
},
expose: {
Title: './src/Title',
},
})
```
=> Add ContainerPlugin

declarations/plugins/ContainerPlugin.d.ts, lib/container/ContainerPlugin.js, schemas/plugins/ContainerPlugin.json, test/configCases/container/container-entry/index.js, test/configCases/container/container-entry/webpack.config.js, tooling/format-schemas.js
=> use new library system for ContainerPlugin

declarations/plugins/ContainerReferencePlugin.d.ts, lib/container/ContainerReferencePlugin.js, schemas/plugins/ContainerReferencePlugin.json
Adding schema validation for container reference plugin.
Fulfills todo on #10439 
feature
no
no
no
=> ContainerReferencePlugin options validation

lib/container/ContainerEntryModule.js, lib/container/ContainerPlugin.js, lib/container/ContainerReferencePlugin.js, lib/container/OverridablesPlugin.js, test/configCases/container/container-entry-overridables/index.js, test/configCases/container/container-entry-overridables/test.js, test/configCases/container/container-entry-overridables/value.js, test/configCases/container/container-entry-overridables/webpack.config.js
=> add overridables to ContainerPlugin

lib/container/ContainerEntryDependency.js, lib/container/ContainerExposedDependency.js, lib/container/ContainerReferencePlugin.js, lib/container/ModuleFederationPlugin.js, lib/container/RemoteOverrideDependency.js, lib/container/RemoteOverrideModule.js, lib/util/internalSerializables.js, test/configCases/container/0-container-full/App.js, test/configCases/container/0-container-full/ComponentA.js, test/configCases/container/0-container-full/index.js, test/configCases/container/0-container-full/node_modules/react.js, test/configCases/container/0-container-full/upgrade-react.js, test/configCases/container/0-container-full/webpack.config.js, test/configCases/container/1-container-full/App.js, test/configCases/container/1-container-full/ComponentB.js, test/configCases/container/1-container-full/index.js, test/configCases/container/1-container-full/node_modules/react.js, test/configCases/container/1-container-full/upgrade-react.js, test/configCases/container/1-container-full/webpack.config.js
=> Add ModuleFederationPlugin

examples/asset-simple/README.md, examples/asset-simple/template.md, examples/chunkhash/README.md, examples/chunkhash/template.md, examples/code-splitting-harmony/README.md, examples/code-splitting-harmony/template.md, examples/code-splitting-native-import-context-filter/README.md, examples/code-splitting-native-import-context-filter/template.md
=> docs(examples): Grammatical fix

lib/APIPlugin.js
=> chore(APIPlugin): Minor typographical fix

lib/APIPlugin.js, lib/container/ContainerEntryModule.js, lib/container/OverridablesPlugin.js, lib/container/RemoteOverrideModule.js, test/configCases/container/1-container-full/ComponentC.js, test/configCases/container/2-container-full/App.js, test/configCases/container/2-container-full/ComponentB.js, test/configCases/container/2-container-full/index.js, test/configCases/container/2-container-full/node_modules/react.js, test/configCases/container/2-container-full/upgrade-react.js, test/configCases/container/2-container-full/webpack.config.js
* json stringify for string module ids
* update formating of container entry
* show container entry and remove override in SourceMap
* move `__webpack_override__` to OverridablesPlugin
* add resolve dependencies to compilation
yes
no
nothing yet
=> add support for nested containers, cleanup, bugfixes

examples/code-splitting-specify-chunk-name/README.md, examples/code-splitting-specify-chunk-name/template.md, examples/code-splitting/README.md, examples/code-splitting/template.md, examples/commonjs/README.md, examples/commonjs/template.md, examples/custom-json-modules/README.md, examples/custom-json-modules/template.md
=> docs(example): fix grammatical errors

README.md
Fixes #10513  
Improving Documentation
N/A
N/A
N/A
=> docs(readme): Inserting Angular Logo in Readme.md

lib/AbstractMethodError.js, lib/ContextModule.js, lib/DelegatedModule.js, lib/DllModule.js, lib/ExternalModule.js, lib/FileSystemInfo.js, lib/Module.js, lib/NormalModule.js, lib/RawModule.js, lib/ResolverFactory.js, lib/RuntimeModule.js, lib/Template.js, lib/Watching.js, lib/cache/IdleFileCachePlugin.js, lib/cache/PackFileCacheStrategy.js, lib/library/AssignLibraryPlugin.js, lib/logging/createConsoleLogger.js, lib/optimize/ConcatenatedModule.js, lib/optimize/LimitChunkCountPlugin.js, lib/rules/RuleSetCompiler.js, lib/stats/DefaultStatsPrinterPlugin.js, test/configCases/concatenate-modules/rename-10168/index.js
Fixes #10525 , fixed all typos.
NA
No
Nothing
=> chore: fix typos across the project

README.md
=> chore(readme): remove Architects.io

examples/dll-entry-only/README.md, examples/dll-entry-only/template.md, examples/externals/README.md, examples/externals/template.md
=> docs(examples): grammar fixes 

CODE_OF_CONDUCT.md, test/README.md
typo fixes in test/readme.md, updates code of conduct link in CODE_OF_CONDUCT.md
not required
no
nothing
=> chore: fix typos, add code of conduct link

README.md
=> docs(README): update browser-field spec link

declarations/WebpackOptions.d.ts, schemas/WebpackOptions.json
bugfix #10552 
No
Yes
Remove test/include/exclude from condition in docs
https://webpack.js.org/configuration/module/#condition
=> fix(#10552) remove test/include/exclude from rule set conditions

test/Dependencies.lint.js
test metadata update
N/A
Nope
Nothing
=> chore: rephrase test descriptions

CONTRIBUTING.md
Enhancement in `CONTRIBUTING.md` .
NA
No
Nothing
=> docs: enhance CONTRIBUTING.md

CONTRIBUTING.md, README.md, _SETUP.md, open-bot.yaml, package.json
Enhancement.
- Prettier is already installed and configured.
- extended its configuration to format markdown.
- added script to lint-stage as well to ensure md remains `pretty`
NA
NO
Nothing
=> chore: extend prettier configuration for markdown

README.md
=> docs(readme): hyperlinking in special thanks section

README.md
Enhancement in docs.
Added reference to `CONTRIBUTING.md`, helpful especially for new Contributors to help them started. 
NA
NO
NA
=> docs(README): add link to CONTRIBUTING.md

lib/buildChunkGraph.js
For now it's a bit difficult to understand code of buildChunkGraph. I'm trying to introduce minor code/comments modifications for better understanding.
refactoring
no
no
nothing
=> buildChunkGraph code clarification

examples/many-pages/README.md, examples/many-pages/template.md, examples/mixed/README.md, examples/mixed/template.md, examples/multi-part-library/README.md, examples/multi-part-library/template.md, examples/multiple-entry-points/README.md, examples/multiple-entry-points/template.md
=> docs: improve examples

examples/extra-async-chunk/README.md, examples/extra-async-chunk/template.md, examples/harmony-interop/example.js, examples/harmony-unused/README.md, examples/harmony-unused/template.md, examples/http2-aggressive-splitting/README.md, examples/http2-aggressive-splitting/template.md
=> docs: Grammatical fixes in examples

azure-pipelines.yml
=> fix vm images in azure

_SETUP.md
fix
currently, the document says to run `yarn pretty` to format the code but the `pretty` script is not present in `package.json`
NA
NO
Nothing.
=> docs(SETUP): fix code formatting command

lib/dependencies/AMDRequireItemDependency.js, lib/dependencies/ContextElementDependency.js, lib/dependencies/ImportEagerDependency.js, lib/dependencies/ImportWeakDependency.js, lib/dependencies/ModuleHotAcceptDependency.js, lib/dependencies/ModuleHotDeclineDependency.js, lib/dependencies/ProvidedDependency.js, lib/dependencies/RequireIncludeDependency.js, lib/dependencies/RequireResolveDependency.js
minor refactoring
Remove serialization properties that already (de)serialized in `super.(de)serialize`, see https://github.com/webpack/webpack/blob/master/lib/dependencies/ModuleDependency.js
No
this PR introduce a breaking change to latest beta
Nothing
=> remove extra serialization

declarations/WebpackOptions.d.ts, schemas/WebpackOptions.json, test/__snapshots__/Cli.test.js.snap
=> fix: correct managedPaths description

declarations/plugins/DllReferencePlugin.d.ts, schemas/plugins/DllReferencePlugin.json
Closes #10699 
Bugfix
No
No
Nothing
=> Fix DllReferencePlugin schema

test/ProgressPlugin.test.js
Added test for a custom handler for `progressPlugin` 
Tests
Yes
No
None
=> test: added custom handler progressPlugin tests

lib/index.js, test/configCases/optimization/chunk/files/file1.js, test/configCases/optimization/chunk/index.js, test/configCases/optimization/chunk/webpack.config.js, types.d.ts
Fixes #10608
bugfix
N/A,
integration tests are already added
no
no
=> fix: exporting deterministicChinkIdPlugin as ids (fixes #10608)

package.json
=> do not publish declarations to npm

azure-pipelines.yml
Node.js v14 was out so we need to add v14 to CI and remove v13.
See https://nodejs.org/en/blog/release/v14.0.0/
CI
Nope
Nope
N/A
=> ci: add Node@14 to azure-pipelines and remove v13

lib/ModuleProfile.js, lib/ProgressPlugin.js
=> ignore some timing-depend code parts for coverage

lib/RecordIdsPlugin.js, test/HotTestCases.template.js, test/__snapshots__/ConfigTestCases.test.js.snap, test/hotCases/chunks/split-chunks/index.js, test/hotCases/chunks/split-chunks/node_modules/vendor.js, test/hotCases/chunks/split-chunks/webpack.config.js
fixes #10762
bugfix
yes
no
nothing
=> record chunk ids for unnamed chunks in the entrypoint chunk group

test/ProgressPlugin.test.js
=> be less strict about test timing

yarn.lock
=> upgrade dependency for security reasons

lib/ProgressPlugin.js, test/ProgressPlugin.test.js
fixes #9714 
added four more compiler hooks to progress plugin
yes
no
no
=> chore: added more  compiler hooks progress

lib/APIPlugin.js, lib/ChunkGraph.js, lib/Compilation.js, lib/HotModuleReplacementPlugin.js, lib/hmr/HotModuleReplacement.runtime.js, lib/hmr/JavascriptHotModuleReplacement.runtime.js, lib/javascript/JavascriptModulesPlugin.js, test/StatsTestCases.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/helpers/captureStdio.js, test/hotCases/hashing/full-hash-main/index.js, test/hotCases/hashing/full-hash-main/module.js, test/hotCases/hashing/full-hash-main/thing.js, test/hotCases/hashing/full-hash-main/webpack.config.js, types.d.ts
fixes issue in https://github.com/webpack/webpack/issues/9802#issuecomment-601911417 by @CruelSilence
bugfix
yes
no
nothing
=> use the full hash on modules that need the full hash of the compilation

lib/container/OverridablesPlugin.js, lib/container/OverridablesRuntimeModule.js, test/configCases/container/exposed-overridables/App.js, test/configCases/container/exposed-overridables/Button.js, test/configCases/container/exposed-overridables/index.js, test/configCases/container/exposed-overridables/node_modules/react.js, test/configCases/container/exposed-overridables/webpack.config.js
fixes this problem https://github.com/webpack/webpack/issues/10352#issuecomment-622149436
bugfix
yes
no
nothing
=> fix missing overridables runtime when no import() is used at all

lib/Compilation.js, lib/ModuleGraph.js, types.d.ts
=> remove logic to finish modules in module graph

test/hotCases/harmony/auto-reexport/file.js, test/hotCases/harmony/auto-reexport/index.js, test/hotCases/harmony/auto-reexport/reexport.js
=> add test case for accepting an reexported value

lib/dependencies/HarmonyExportDependencyParserPlugin.js, lib/dependencies/HarmonyExportExpressionDependency.js, lib/optimize/ConcatenatedModule.js, test/cases/parsing/harmony-export-hoist/bar.js, test/cases/parsing/harmony-export-hoist/class-no-name.js, test/cases/parsing/harmony-export-hoist/class-with-name.js, test/cases/parsing/harmony-export-hoist/class-with-super-no-name.js, test/cases/parsing/harmony-export-hoist/class-with-super-with-name.js, test/cases/parsing/harmony-export-hoist/foo.js, test/cases/parsing/harmony-export-hoist/func-no-args-no-name.js, test/cases/parsing/harmony-export-hoist/func-no-args-with-name.js, test/cases/parsing/harmony-export-hoist/func-with-args-no-name.js, test/cases/parsing/harmony-export-hoist/func-with-args-with-name.js, test/cases/parsing/harmony-export-hoist/get-class-no-name.js, test/cases/parsing/harmony-export-hoist/get-class-with-name.js, test/cases/parsing/harmony-export-hoist/get-class-with-super-no-name.js, test/cases/parsing/harmony-export-hoist/get-class-with-super-with-name.js, test/cases/parsing/harmony-export-hoist/get-func-no-args-no-name.js, test/cases/parsing/harmony-export-hoist/get-func-no-args-with-name.js, test/cases/parsing/harmony-export-hoist/get-func-with-args-no-name.js, test/cases/parsing/harmony-export-hoist/get-func-with-args-with-name.js, test/cases/parsing/harmony-export-hoist/index.js
fixes #10870
bugfix
yes
no
nothing
=> keep function declarations when using export default

lib/container/ContainerReferencePlugin.js, test/configCases/container/container-entry/index.js, test/configCases/container/container-entry/main.js, test/configCases/container/container-entry/webpack.config.js, test/configCases/container/container-reference/module.js
feature
yes
no
``` js
exposes: {
"": "./index"
}
```
and `import main from "container"`
=> allow to expose and consume an index module from containers

test/cases/side-effects/dynamic-reexports/checked-export/dynamic.js, test/cases/side-effects/dynamic-reexports/checked-export/index.js, test/cases/side-effects/dynamic-reexports/checked-export/module.js, test/cases/side-effects/dynamic-reexports/direct-export/dynamic.js, test/cases/side-effects/dynamic-reexports/direct-export/index.js, test/cases/side-effects/dynamic-reexports/direct-export/module.js, test/cases/side-effects/dynamic-reexports/index.js
=> add more test cases for dynamic reexports

package.json, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/code-generation/harmony-pure-default/deprecations.js, test/configCases/plugins/terser-plugin/deprecations.js, test/configCases/scope-hoisting/harmony-pure-default/deprecations.js, test/configCases/source-map/sources-array-production/deprecations.js, test/statsCases/warnings-terser/webpack.config.js, yarn.lock
fixes #10941 fixes #10940
Update deps
No need
Yes, minimize options have some changes
=> chore: update terser-webpack-plugin

examples/top-level-await/README.md, examples/top-level-await/template.md, examples/wasm-simple/README.md, examples/wasm-simple/template.md
=> docs: improve documentation of examples

lib/FileSystemInfo.js
fix missing startTime in deduped snapshots
fixes #10966
bugfix
no, too difficult, race conditions
no
nothing
=> fix lost file timestamps due to snapshot deduplication

lib/Stats.js
Fix Stats method typings.
No need.
Not at all.
Maybe nothing.
=> Fix mistaken typings.

lib/BannerPlugin.js
Remove some unnecessary code in `BannerPlugin`.
Tests pass.
=> BannerPlugin: remove unnecessary code

lib/Compilation.js, types.d.ts
Correct a grammatical error in the description.
A documentation improvement.
Unnecessary.
No.
Nothing.
=> chore(Compilation EntryData includeDependencies):

lib/hmr/JavascriptHotModuleReplacement.runtime.js, test/hotCases/runtime/self-accept-factory/a.js, test/hotCases/runtime/self-accept-factory/b.js, test/hotCases/runtime/self-accept-factory/hot.js, test/hotCases/runtime/self-accept-factory/index.js
Hello,
I met a strange error when working with HMR and `react-hot-loader`, here's the screenshot:
maybe related to https://github.com/webpack/webpack-dev-server/issues/2231.
---
I've searched almost the possibility across `react-hot-loader`, `webpack-dev-middleware` and `webpack-hot-middleware`, or even I used Koa in the wrong way. I excluded most of the customization, finally I guess this is an implicit bug when mixing `webpack@^5` and `react-hot-loader`.
I skipped creating an issue but a pull request, hope that won't let you feel bad (ノω・。)
Also more informations.
https://github.com/shirohana/webpack-react-hmr-undefined
```
"babel-loader": "^8.1.0"
"react-hot-loader": "^4.12.21"
"webpack": "^5.0.0-beta.17"
"webpack-dev-middleware": "^4.0.0-rc.1"
"webpack-hot-middleware": "^2.25.0"
``` …
=> fix(hmr): Prevent retrieving properties in undefined object in jsHMR

lib/runtime/LoadScriptRuntimeModule.js, test/Stats.test.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/web/attach-existing/index.js, test/configCases/web/attach-existing/webpack.config.js
bugfix
yes
yes
* `data-webpack` has `output.uniqueName` + `:` as prefix
=> avoid collision in `data-webpack` by adding the uniqueName

lib/container/ContainerEntryDependency.js, lib/container/FallbackDependency.js, lib/sharing/ConsumeSharedFallbackDependency.js, lib/sharing/ConsumeSharedModule.js, lib/sharing/ConsumeSharedPlugin.js, lib/sharing/ProvideForSharedDependency.js, lib/sharing/ProvideSharedDependency.js, lib/sharing/ProvideSharedModule.js, lib/sharing/ProvideSharedModuleFactory.js, lib/sharing/ProvideSharedPlugin.js, lib/util/internalSerializables.js
=> rename module federation classes for be more specific

declarations/WebpackOptions.d.ts, lib/NormalModule.js, lib/NormalModuleFactory.js, lib/config/defaults.js, lib/util/DataURI.js, schemas/WebpackOptions.json, test/Defaults.unittest.js, test/Validation.test.js, test/__snapshots__/Cli.test.js.snap, test/cases/resolving/data-uri/index.js, test/cases/resolving/data-uri/module-with-imports.js, types.d.ts
Implement feature from #9445
feature
Yes
No
Ability to import from data URI.
=> Implement Data URI imports

lib/stats/DefaultStatsPrinterPlugin.js
=> join asset info flags correctly

examples/module-federation/README.md, examples/module-federation/index.html, test/configCases/container/container-entry-overridables/index.js
=> fix: some typos

lib/RuntimeGlobals.js, lib/WebpackOptionsApply.js, lib/node/NodeTemplatePlugin.js, lib/node/ReadFileChunkLoadingRuntimeModule.js, lib/node/RequireChunkLoadingRuntimeModule.js, lib/runtime/StartupChunkDependenciesPlugin.js, lib/runtime/StartupChunkDependenciesRuntimeModule.js, lib/runtime/StartupEntrypointRuntimeModule.js, lib/webworker/WebWorkerTemplatePlugin.js, test/configCases/split-chunks/runtime-chunk-async-node/a.js, test/configCases/split-chunks/runtime-chunk-async-node/b.js, test/configCases/split-chunks/runtime-chunk-async-node/c.js, test/configCases/split-chunks/runtime-chunk-async-node/shared.js, test/configCases/split-chunks/runtime-chunk-async-node/test.config.js, test/configCases/split-chunks/runtime-chunk-async-node/webpack.config.js, test/configCases/split-chunks/runtime-chunk-node/a.js, test/configCases/split-chunks/runtime-chunk-node/b.js, test/configCases/split-chunks/runtime-chunk-node/c.js, test/configCases/split-chunks/runtime-chunk-node/shared.js, test/configCases/split-chunks/runtime-chunk-node/test.config.js, test/configCases/split-chunks/runtime-chunk-node/webpack.config.js, types.d.ts
also fixes a incorrect relative path
bugfix
yes
only compared to prev betas.
for custom targets using NodeTemplatePlugin or WebWorkerTemplatePlugin, this uses StartupChunkDependenciesPlugin by default.
nothing
=> allow runtimeChunk with node targets

declarations/WebpackOptions.d.ts, lib/config/defaults.js, lib/config/normalization.js, lib/runtime/LoadScriptRuntimeModule.js, lib/web/JsonpTemplatePlugin.js, schemas/WebpackOptions.json, test/Defaults.unittest.js, test/__snapshots__/Cli.test.js.snap, types.d.ts
Closes [this](https://github.com/webpack/webpack/projects/5#card-39537013) card
refactoring
just updated snapshots
no, the option was introduced in webpack 5
about the option
=> rename jsonScriptType to scriptType

examples/module-federation/README.md, lib/Compilation.js, lib/runtime/LoadScriptRuntimeModule.js, lib/sharing/ShareRuntimeModule.js, lib/util/comparators.js, test/Stats.test.js, test/__snapshots__/StatsTestCases.test.js.snap, types.d.ts
bugfix
no, too difficult
no
nothing
=> A few little bugfixes to Module Federation

lib/MainTemplate.js, lib/Module.js, lib/RuntimeModule.js, lib/RuntimePlugin.js, lib/Template.js, lib/runtime/CompatRuntimeModule.js, types.d.ts
=> fix compat bugs

lib/Compiler.js, test/configCases/errors/case-emit/errors.js, test/configCases/errors/case-emit/webpack.config.js
=> add error when trying to write assets that only differ in casing

lib/Compiler.js, lib/MultiCompiler.js, lib/WatchIgnorePlugin.js, lib/node/NodeWatchFileSystem.js, lib/util/fs.js, test/MultiCompiler.test.js, test/PersistentCaching.test.js, types.d.ts
Avoid using real watchers in MultiWatching test case
add watchFileSystem to MultiCompiler and typings
fix timeout in PersistentCaching test
Trying to fix flanky coverage in CI
CI, typings
its test code
no
nothing
=> CI stability

azure-pipelines.yml
=> reorder azure pipeline to run slower tests first

lib/cache/ResolverCachePlugin.js, test/WatchTestCases.test.js, test/watchCases/snapshot/unable-to-snapshot/0/index.js, test/watchCases/snapshot/unable-to-snapshot/0/node_modules/package/changing-file.js, test/watchCases/snapshot/unable-to-snapshot/0/node_modules/package/index.js, test/watchCases/snapshot/unable-to-snapshot/1/node_modules/package/changing-file.js, test/watchCases/snapshot/unable-to-snapshot/2/node_modules/package/changing-file.js, test/watchCases/snapshot/unable-to-snapshot/webpack.config.js
fixes #10830
bugfix
yes
no
nothing
=> handle case when no snapshot can be created in ResolverCachePlugin

lib/cli.js, test/Cli.test.js
bugfix
Resolve #11129 
yes
no
nothing
=> fix(cli): improve processing of number type arguments

lib/config/defaults.js, lib/dependencies/ExportsInfoDependency.js, test/Defaults.unittest.js, test/__snapshots__/StatsTestCases.test.js.snap, test/cases/chunks/inline-options/index.js, test/cases/inner-graph/circular/index.js, test/cases/inner-graph/export-default-named/index.js, test/cases/inner-graph/extend-class/index.js, test/cases/inner-graph/extend-class2/index.js, test/cases/inner-graph/reexport-namespace-and-default/index.js, test/cases/inner-graph/simple/index.js, test/cases/parsing/harmony-deep-exports/index.js, test/cases/parsing/harmony-export-import-specifier/index.js, test/cases/side-effects/dynamic-reexports/dedupe-target-with-side/a.js, test/hotCases/unexpected-invalidation/used-exports/index.js, test/hotCases/unexpected-invalidation/used-exports/module.js, test/hotCases/unexpected-invalidation/used-exports/subject.js
... to prevent unexpected changes to module
change
yes
yes
nothing
=> disable used exports optimization in development

lib/Module.js, lib/dependencies/HarmonyImportDependency.js, test/hotCases/recover/recover-after-loader-error/warnings1.js, test/hotCases/recover/recover-after-parsing-error/warnings1.js, test/watchCases/recover-from-error/parse-failed-esm/0/errors.js, test/watchCases/recover-from-error/parse-failed-esm/0/index.js, test/watchCases/recover-from-error/parse-failed-esm/0/node_modules/some-module/index.js, test/watchCases/recover-from-error/parse-failed-esm/0/node_modules/test-module/index.js, test/watchCases/recover-from-error/parse-failed-esm/1/node_modules/some-module/index.js, test/watchCases/recover-from-error/parse-failed-esm/2/errors.js, test/watchCases/recover-from-error/parse-failed-esm/2/node_modules/some-module/index.js, test/watchCases/recover-from-error/parse-failed-esm/3/node_modules/some-module/index.js, types.d.ts
=> ignore linking errors when the imported module has errors

CONTRIBUTING.md
Docs, grammar fix
NA
No
Nothing
=> docs: fix grammar

lib/Watching.js, test/WatchClose.test.js
https://github.com/webpack/webpack/issues/11007
yes
no
no
=> fix: multiple calls close watcher

lib/Compiler.js, lib/MultiCompiler.js, lib/Watching.js, test/Compiler.test.js, types.d.ts
=> call invalid hook also when manually invalidating watching

test/watchCases/simple/production/0/changing-file.js, test/watchCases/simple/production/0/changing-module.js, test/watchCases/simple/production/0/index.js, test/watchCases/simple/production/1/changing-file.js, test/watchCases/simple/production/1/changing-module.js, test/watchCases/simple/production/2/changing-file.js, test/watchCases/simple/production/2/changing-module.js, test/watchCases/simple/production/webpack.config.js
=> add test case for watching in production

test/WatchTestCases.test.js
=> watch test cases: close correctly, increase timeout

lib/config/normalization.js
Feel free to close it if I was wrong.
bugfix.
I was trying to set `externalsType` to `script` and found I got `var` instead. The option is filtered in [lib/config/normalization.js](https://github.com/webpack/webpack/blob/c9104c8196f09fa9331b95f2bb8978f4b9ed365a/lib/config/normalization.js#L144) file, which means it will always fall back on https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L178.
No
No
Nothing
=> normalize externalsType

test/TestCases.template.js
=> avoid using deprecated config in test cases

.github/ISSUE_TEMPLATE/Feature_request.md
chore, grammar fix
NA
no
nothing
=> fix: feature_request template

lib/stats/DefaultStatsPrinterPlugin.js
=> fix digits output of timestamp at 10 o'clock

test/cases/side-effects/dynamic-reexports/dynamic-reexport-default/dynamic.js, test/cases/side-effects/dynamic-reexports/dynamic-reexport-default/index.js, test/cases/side-effects/dynamic-reexports/index.js, test/cases/side-effects/dynamic-reexports/warnings.js
=> add test case for bug in webpack 4

lib/Compilation.js, lib/optimize/RuntimeChunkPlugin.js, test/__snapshots__/StatsTestCases.test.js.snap, test/configCases/errors/depend-on-and-runtime/errors.js, test/configCases/errors/depend-on-and-runtime/webpack.config.js, test/statsCases/runtime-chunk-integration/f.js, test/statsCases/runtime-chunk-integration/main2.js, test/statsCases/runtime-chunk-integration/main3.js, test/statsCases/runtime-chunk-integration/webpack.config.js
DX
yes
no
* `runtime` and `dependOn` can be specified both on a single entry
* `dependOn` must not be circular
* `runtime` must not point to an existing entrypoint name
=> add useful error messages for runtime and dependsOn

lib/Compilation.js, lib/Compiler.js, lib/MultiWatching.js, lib/NormalModule.js, lib/ProgressPlugin.js, lib/Watching.js, lib/cache/IdleFileCachePlugin.js, test/ProgressPlugin.test.js, test/configCases/plugins/progress-plugin/index.js, types.d.ts
improve progress output
improvement
yes
yes
nothing
=> do cache related tasks after calling handler in watching

declarations/WebpackOptions.d.ts, lib/Compilation.js, lib/SourceMapDevToolPlugin.js, lib/stats/DefaultStatsFactoryPlugin.js, lib/stats/DefaultStatsPresetPlugin.js, lib/stats/DefaultStatsPrinterPlugin.js, schemas/WebpackOptions.json, test/Stats.test.js, test/__snapshots__/Cli.test.js.snap, test/__snapshots__/StatsTestCases.test.js.snap, test/helpers/captureStdio.js, test/statsCases/context-independence/webpack.config.js, test/statsCases/related-assets/chunk-style.css, test/statsCases/related-assets/chunk.js, test/statsCases/related-assets/index.js, test/statsCases/related-assets/style.css, test/statsCases/related-assets/webpack.config.js, types.d.ts
* add related info to asset info
* display assets in stats in a list instead of a table
* group related assets below the parent asset
feature
yes
yes, stats output and format changed
* `stats.relatedAssets` allow to show related assets (they are hidden by default)
=> Related assets

lib/dependencies/RequireContextPlugin.js, test/configCases/context-replacement/e/index.js, test/configCases/context-replacement/e/webpack.config.js
=> avoid removing relative path for absolute module directories in context
