lib/Compiler.js
test/Compiler.test.js

When the `output.filename` contains directory and file (for example `build\assets\js\app.js`), the compilation under Windows will fail with "Path does not exist" error. That happens because the compiler expects UNIX slash (`/`) in the path, and gets Windows slash (`\`) instead.
The [test](https://github.com/corporateanon/webpack/commit/65079e966c69858cdd57d0c34d69a5152c14d0bf), added in this PR, will fail (under Windows only) when run without the fix.

Compiler fails under Windows

---

lib/EnvPlugin.js
lib/webpack.js
test/configCases/plugins/env-plugin/index.js
test/configCases/plugins/env-plugin/warnings.js
test/configCases/plugins/env-plugin/webpack.config.js

This adds a convenience plugin that uses `DefinePlugin` to import environment variables. It also warns if you've forgotten to define a variable.
Example:
**app.js**
```javascript
if (process.env.NODE_ENV === 'production') {
// Do something only in production mode
}
```
**webpack.config.js**
```javascript
var webpack = require('webpack')
// ...
plugins: [
new webpack.EnvPlugin('NODE_ENV', 'API_URL')
]
}
```
This will output the following warning:
```
[EnvPlugin] Warning: API_URL environment variable is undefined.
```
And result in the following javascript output:
```javascript
if (('production') === 'production') {
// Do something only in production mode
}
```

Added EnvPlugin.

---

lib/AsyncDependenciesBlock.js

It looks like you forgot the rename the chunk property to chunks in the disconnect implementation which lead to build failures in watch mode for me.

Fix error in watch mode

---

lib/WebpackOptionsDefaulter.js
lib/node/NodeSourcePlugin.js
test/ConfigTestCases.test.js
test/configCases/target/web/index.js
test/configCases/target/web/webpack.config.js

As discussed in #419
Btw: Why is the console shim deactivated by default?

Add node-independent shim for global setImmediate()

---

lib/dependencies/AMDDefineDependencyParserPlugin.js
lib/dependencies/LocalModulesHelpers.js
test/cases/parsing/local-modules/index.js

This implements the minimum necessary to pass the tests I sent in for #727, allowing `getLocalModule` to optionally take a namedModule in the case of such AMD defines. Let me know if you have any better ideas for getting the name of the module into the helper, or if there's a better approach for determining if we should resolve the module relatively.
Thanks again for webpack!
Will

Resolves #727: Resolve AMD module dependencies relative to named modules being defined

---

bin/webpack.js
package.json

This solution still supports "--colors" and "--no-colors" for overriding the detected ability.
see https://github.com/sindresorhus/supports-color

Use "supports-color" to detect if terminal supports colors

---

lib/optimize/UglifyJsPlugin.js

Print out err.msg if it's available. Previously these error messages were ignored and it printed unhelpful "undefined"
Errors of this type are created here: https://github.com/mishoo/UglifyJS2/blob/master/lib/utils.js#L84
I had a situation where I was getting an error output like this:
```
ERROR in jsx.js from UglifyJs
undefined
```
After this change the error is:
```
ERROR in jsx.js from UglifyJs
`inline_scripts` is not a supported option
```
The error was a typo in the option. It is supposed to be `inline_script`, not `inline_scripts`. See appsforartists/ambidex#9

Show error messages from UglifyJs

---

lib/MainTemplate.js

This fixes #789. However, @sokra mentioned that dependencies should just be bundled together instead of trying to concat bundles.

Added semicolon after output

---

lib/Stats.js

* abbreviate bytes with appropriate multiples
Before merging see https://github.com/webpack/webpack/issues/741#issuecomment-77099289. Thanks!
``` bash
Hash: cfa436b4ea300482822c
Version: webpack 1.7.1
Time: 5542ms
Asset     Size  Chunks             Chunk Names
7ad17c6085dee9a33787bac28fb23d46.eot  20.3 kB          [emitted]
68ed1dac06bf0409c18ae7bc62889170.woff  23.3 kB          [emitted]
e49d52e74b7689a0727def99da31f3eb.ttf  41.3 kB          [emitted]
32941d6330044744c02493835b799e90.svg  62.9 kB          [emitted]
bundle.js  1.16 MB       0  [emitted]  main
[206] ../webpack/buildin/amd-define.js 84 bytes {0} [built]
+ 219 hidden modules
```
Resolves #741

Alternative improve size output readability

---

lib/WatchIgnorePlugin.js
lib/webpack.js
test/configCases/plugins/watch-ignore-plugin/index.js
test/configCases/plugins/watch-ignore-plugin/webpack.config.js

See https://github.com/webpack/webpack-dev-server/issues/112. @sokra already wrote a plugin for this, but it was never added to the repository.
Usage like:
``` js
var path = require("path");
var WatchIgnorePlugin = require("webpack").WatchIgnorePlugin;
{
plugins: [
new WatchIgnorePlugin([
path.resolve(__dirname, './ignore-more/'),
]),
],
}
```
If this is good to merge, I'll update the documentation after it's in master.

Add and expose WatchIgnorePlugin

---

lib/optimize/DedupePlugin.js

Using the DedupePlugin together with the core-js polyfill caused IE8 to fail with the message "Object doesn't support this property or method", because the `for...in` includes properties from the prototype chain of the polyfilled Array object. Using a regular `for` loop fixes this.

check hasOwnProperty when looping over modules

---

CONTRIBUTING.md
README.md

All righty y'all https://github.com/webpack/webpack/issues/908
See how the readme looks on my fork: https://github.com/JonDum/webpack
I had the idea of adding some of the loaders to the readme because it gives a good idea about the types of things webpack can do, but I think there might be too many now haha.
There's still also the issue of organizing and tagging Issues as they come in.

Spruce up README and add CONTRIBUTING

---

lib/ModuleFilenameHelpers.js
lib/SourceMapDevToolPlugin.js
lib/optimize/UglifyJsPlugin.js
test/configCases/source-map/exclude-chunks-source-map/index.js
test/configCases/source-map/exclude-chunks-source-map/test.js
test/configCases/source-map/exclude-chunks-source-map/vendors.js
test/configCases/source-map/exclude-chunks-source-map/webpack.config.js

per @gaearon suggestion, see issue #650 raised by @davidtheclark: "The problem with this is that the vendor file can get pretty big, and its gigantic sourcemap then severely slows down dev tool initialization on page reload. I would much prefer to only have a sourcemap for my app chunk (and not to have a sourcemap for my vendor chunk)."
This is a first stab at the corresponding ```exclude``` options.
Note that it might get tedious to have to explicitly instantiate ```SourceMapDevToolPlugin```, maybe a more global option such ```as output.sourceMapExcludeChunks``` could be introduced as well.
```
plugins: [
new webpack.SourceMapDevToolPlugin({
filename: "[file].map",
excludeChunks: ["vendors"]
})
```

First stab at SourceMapDevToolPlugin exclude option

---

bin/convert-argv.js
package.json

This is a possible solution for #475.
Support for `*.coffee` configuration files is implemented using [node-interpret](https://github.com/tkellen/node-interpret).
Other formats work as well:
```
webpack --config webpack.config.coffee
webpack --config webpack.config.json
```
P.S. Are there any tests to cover CLI?

Use node-interpret to import configuration in various formats.

---

README.md

It was coincidentally just above the invitation to correct any spelling mistakes.

Fix spelling of "loader"

---

bin/convert-argv.js

Finally decided to bite the bullet and implement this, based off of node-liftoff's require code. Addresses #475 #949.
Any compile-to-js language in [node-interpret](https://github.com/tkellen/node-interpret) is pulled into your project automatically. This means `.coffee`, `.json`, `.babel.js`, etc. are all supported out of the box. 
I tested this on a local repo of mine and seems to work. @sokra would love some feedback.

Automatically pull in webpack.config files written in compile-to-js langs

---

lib/SourceMapDevToolPlugin.js

This fixes [webpack/extract-text-webpack-plugin#61](https://github.com/webpack/extract-text-webpack-plugin/issues/61) with the method recommended by @sokra. Currently the workaround requires not using `devtool: 'sourcemap'` and doing this instead:
```javascript
plugins: [
new webpack.SourceMapDevToolPlugin({
test:      /\.(js|css)($|\?)/i,
filename: '[file].map'
})
]
```
The change doesn't affect JS source mapping.

Allow CSS source maps by default

---

lib/JsonpMainTemplatePlugin.js
lib/WebpackOptionsDefaulter.js

We are facing the problem, that our tracking of javascript errors currently is not working, due to CORS restrictions. This is because we load our chunks from a cdn domain and not the pages current domain.
This can easily be fixed by adding the crossorigin attribute to the script tags, but we can't do that for the tags which are injected by webpack.
https://developer.mozilla.org/de/docs/Web/HTML/Element/script#attr-crossorigin
In this PR we added a new configuration option which can be set to one of the two valid options for the crossorigin attribute ('anonymous' or 'use-credentials')(by default false). If present the crossorigin attribute will be added to the injected script tag.
There are still some questions for this PR, which we are not sure about.
* the location of config option may …

Possibility to load chunks with crossorigin

---

bin/webpack.js

This fixes a bug where the CLI would simply ignore the `options.watchOptions Object` of a `webpack.config.js` file.
I suppose this got lost in 89058a2c4a32a2ec31c88acb3789c4f9eda58db1.

Fix CLI ignores watchOptions

---

package.json

License as array is deprecated as of `npm@2.10.0`.
https://github.com/npm/npm/pull/8179

Update License in package.json

---

lib/optimize/CommonsChunkPlugin.js

Currently, map is being called to extract sizes then reduce is called on that; so 2 iterations through the array. It is possible to solve this with only reduce: 1 iteration. reallyUsedModules probably won't ever be big enough for this to matter, so it comes down to readability.
I think doing a once-and-done reduce could be an improvement here. What do you guys think?

Small refactor for getting size

---

test/Integration.test.js

Implementing actual async after-resolve handlers causes the _currentPluginApply field to become corrupted.
Failing test pull request.

Add test failure for after-resolve async

---

lib/FunctionModuleTemplatePlugin.js

In order to avoid conflicts with the `__webpack_require__` variable when dealing with externals (#1054), I thought we could just not provide the `__webpack_require__` argument to external modules since, from my understanding, they would never call it anyways.
That way, external modules would end up looking like:
```js
/* 3 */
/***/ function(module, exports) {
module.exports = require("react");
/***/ },
```
and when they are rewritten in the outer bundle, they would end up like:
```js
/* 3 */
/***/ function(module, exports) {
module.exports = __webpack_require__(11);
/***/ },
```
Where `__webpack_require__` would correctly reference the `__webpack_require__` from the outer bundle and not the inner bundle like it does now.
This is just my initial attempt at a fix for #1054. What are your …

Don't provide __webpack_require__ argument to external modules

---

bin/webpack.js

Fixed typo in bin/webpack.js. Should be straightforward.

Error.stackTrackLimit -> stackTraceLimit

---

lib/Chunk.js

Same small refactor as a [previous pull](https://github.com/webpack/webpack/commit/7edffc381d5aa97c3969d6b38761bd92c94b9f95). Does one ```reduce``` iteration instead of a ```map``` -> ```reduce```

Refactor size method for Chunks

---

README.md

Only made 1 type of change:
1) Changed all instances of "javascript" to "JavaScript" to match consistency in rest of README.md
No other changes were made.

Add consistent casing for JavaScript

---

lib/Stats.js
test/Stats.test.js

We have plugins we use that were thowing errors that were strings. However the errors reporrted were 
`Error undefined` which was little to no help. Now we actually get the error reporting we need.
Stats now error reporting catches string errors. Some plugins appear to not obey the rules on error reporting. However this makes debuging a nightmare for users. Therefore the string should be allowed.

Stats.js formatError supports string errors

---

bin/convert-argv.js

Currently, every user that uses the ```--optimize-min-chunk-size``` option gets an error because it requires ```LimitChunkSizePlugin```.
There doesn't seem to be a ```LimitChunkSizePlugin```. So this pull request fixes that by making the assumption that webpack actually wants to use ```MinChunkSizePlugin``` instead of the nowhere-to-be-found ```LimitChunkSizePlugin```.

Fix optimize-min-chunk-size option for CLI

---

lib/optimize/AggressiveMergingPlugin.js
lib/optimize/LimitChunkCountPlugin.js
lib/optimize/MinChunkSizePlugin.js
lib/optimize/OccurrenceOrderPlugin.js
test/Integration.test.js
test/NodeTemplatePlugin.test.js
test/browsertest/library2config.coffee

Throw errors if users don't pass in the correct type of argument to the plugin instead of leaving them in the dark. 
For OccurenceOrderPlugin, passing in no arguments should still work just in case there are people currently using it without arguments.

Add argument error handling for optimization plugins

---

bin/convert-argv.js

When using babel in your webpack.config, the config should be named ```webpack.config.babel.js```. Webpack can find it and works fine by default. However if one uses ```webpack --config webpack.config.babel.js``` it fails for invalid extension interpretation. This causes problem when using multiple webpack configs. I sort the extension array in order to exam ```.babel.js``` earlier than ```.js```

fix config extension interpretation for .babel.js

---

bin/convert-argv.js

--output-pathinfo maps to output.pathinfo, however, output.filename is set
by --output-file instead of --output-filename.
Added the new argument while keeping the old one for compability.

Added --output-filename to be consistent with naming conventions

---

.gitignore

A small change that avoid commiting an `npm-debug.log` file when for example the command `npm run eslint` fails

feat(app): Git ignore *.log files

---

lib/ModuleFilenameHelpers.js
test/configCases/filename-template/module-filename-template/index.js
test/configCases/filename-template/module-filename-template/webpack.config.js

Usage example
webpack.config.js
```js
entry: 'main.js',
output: {
filename : 'bundle.js',
devtoolModuleFilenameTemplate: function(info) {
// info is an objet which has the following properties:
// - identifier
// - shortIdentifier
// - resource
// - resourcePath
// - absoluteResourcePath
// - allLoaders
// - query
// - moduleId
// - hash
return info.resourcePath;
}
}
};
```

feat(app): devtool(Fallback)ModuleFilenameTemplate can now also be defined as function

---

bin/convert-argv.js

This commit bumped up interpret version to 0.6:
https://github.com/webpack/webpack/commit/bf3ea10f3cc988c78627498f81a188f796329e82#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R11
Because interpret changed the structure from 0.5 to 0.6 it made webpack stop working for me with webpack.config.coffee so I fixed the code that uses the interpret to behave in accordance to https://github.com/tkellen/js-interpret#how-to-use-it for version 0.6
Please accept the request quickly as the only thing I did to encounter the error was to install nodejs, webpack and coffee-script on clean machine and attempt to get something very basic working.
The bug also affects not only the people that like their webpack.config in different flavors of coffescript but also typescript, babel.js and jsx as you can infer from …

Adjust to use of interpret module version 0.6

---

.travis.yml

The build is currently failing on `iojs@3.0.0` (see wadey/node-microtime#33), but I think it highlighted that we didn't test "older" versions of `iojs`.
This change also does not explicitly state `latest`, but will always test the newest (old behavior for `iojs`, new for `node`). This means adding an entry for it when a new version is released.

Test on multiple io.js's

---

CONTRIBUTING.md
README.md
bin/webpack.js
lib/MovedToPluginWarningPlugin.js
lib/optimize/AggressiveMergingPlugin.js
lib/optimize/LimitChunkCountPlugin.js
lib/optimize/MinChunkSizePlugin.js
lib/optimize/OccurrenceOrderPlugin.js
package.json

Updated to use secure links.
The only insecure link left is the one on the GitHub repository link field. An admin has to change that. The link field is right beside the repository description.

Use secure links.

---

lib/UmdMainTemplatePlugin.js

see: https://github.com/umdjs/umd/pull/34
> Without this, the factory may be scanned for additional dependencies matching the literal string require("module-id"), which is not correct. See https://github.com/amdjs/amdjs-api/wiki/AMD#simplified-commonjs-wrapping-.

define call should include empty dependencies list

---

lib/Compilation.js
lib/Compiler.js
lib/ContextModuleFactory.js
lib/DllModuleFactory.js
lib/MultiCompiler.js
lib/MultiModuleFactory.js
lib/NormalModuleFactory.js
lib/Parser.js
lib/Template.js

At the moment any subclass that inherits from Tapable is reported as Tapable rather than the subclass itself and this makes it hard to debug the code. Here is an example setup that demonstrates the problem:
```javascript
function Tapable() {}
function Compiler() {
Tapable.call(this);
}
Compiler.prototype = Object.create(Tapable.prototype);
```
Now, if we ask an instance of Compiler what its constructor is, then we will get `Tapable` rather than `Compiler`:
```javascript
new Compiler().constructor; // function Tapable() { ... }
```
The problem stems from overwriting Compiler's prototype object and the way to fix is to set the constructor manually:
```javascript
Compiler.prototype.constructor = Compiler;
new Compiler().constructor; // function Compiler() { ... }
```
By having the correct …

Report constructor correctly when inheriting from Tapable

---

lib/LibraryTemplatePlugin.js
lib/UmdMainTemplatePlugin.js
lib/WebpackOptionsApply.js
test/configCases/target/umd-named-define/index.js
test/configCases/target/umd-named-define/webpack.config.js

In the AMD target the AMD module gets named, but in the UMD target its
is always anonymous, even if `library` is set in the config.
This patch names the AMD module if `library` is set.
See the discussion in the referenced issue to see the background for
this change.
If its a multi part library it uses the last key in the same was as it
does with the exports hash part of the UMD declaration. Is this the best
solution?
Resolves webpack/issues/989

Name AMD module in UMD target if library is set

---

bin/config-optimist.js
bin/convert-argv.js
bin/webpack.js

This will send the proper exit signal when stdin closed for #1308 
I would like to automatically run `webpack --watch` as part of my application but, when it shuts down, the webpack process persists and continues running. I have observed that my application does close STDIN, however, `webpack --watch` is not currently checking if STDIN was closed or not.

Send `exit(0)` when stdin closed.

---

bin/config-optimist.js

If you have multiple webpack configuration files then each of your scripts ends up requiring that you specify a config file, so having a shorthand for it is nice and convenient.

Add -c config alias to the CLI

---

lib/WebpackOptionsApply.js

Currently, doing `require('browser-image')` in an Electron app fails. Fortunately, this was really easy to fix.
https://github.com/atom/electron/blob/master/docs/api/native-image.md

Add native-image plugin to electron target

---

lib/optimize/UglifyJsPlugin.js

After some investigation of #1486, I came across some non-deterministic behavior from UglifyJS. That issue is well presented in https://github.com/mishoo/UglifyJS2/issues/219 and explained in https://github.com/mishoo/UglifyJS2/issues/229, and ultimately fixed via https://github.com/mishoo/UglifyJS2/commit/d0689c81bb859ac78a966c526073dcc50a8ccde9. Because UglifyJsPlugin duplicates minification logic, it hasn't picked up this change.
I'm unable to create this issue with a simple example, but within a larger project, I was able to verify this change fixes the issue, at least across ~10 builds. I think this is relatively safe to add regardless.

Reset uglify's base54 counters for each file

---

package.json

Fix #1104
There were some issues with Uglify and sourcemaps. They bumped their version of their dependency of  the `source-map` package, and this fixed the issue.

Update uglify-js to v2.5.0

---

hot/dev-server.js
hot/emitter.js
hot/only-dev-server.js
lib/webworker/WebWorkerHotUpdateChunkTemplatePlugin.js
lib/webworker/WebWorkerMainTemplate.runtime.js
lib/webworker/WebWorkerMainTemplatePlugin.js
lib/webworker/WebWorkerTemplatePlugin.js

This is the same as #1521, now merging into the `webpack-2` branch since this includes breaking changes (i.e. the removal of `window.addEventListener`).

Allow hot module replacement in "webworker" targets

---

lib/WebpackOptionsApply.js

See this [commit](https://github.com/atom/electron/commit/4ccb0cccf39e8831608483bf1d9dc50df2647ff6).
The `web-view` has been renamed to `web-frame`.

Fix module of electron target: web-view -> web-frame

---

examples/README.md

addresses second suggestion of #1350. Thanks!

added explicit step to run npm install when building an example

---

lib/Stats.js
test/Stats.test.js
test/statsCases/color-disabled/expected.txt
test/statsCases/color-disabled/webpack.config.js
test/statsCases/color-enabled-custom/expected.txt
test/statsCases/color-enabled-custom/webpack.config.js
test/statsCases/color-enabled/expected.txt
test/statsCases/color-enabled/webpack.config.js

Default colors may not look good with some terminal color settings, so this patch allows to setup stats colors explicitly:
```
var config = {
stats: {
colors: {
yellow: '\u001b[33m',
green: '\u001b[32m'
}
}
}
```
`colors: true` will use default colors.

Configurable stats colors

---

bin/config-optimist.js

The `-c` and `-h` aliases were already used by `--colors` and `--help`, respectively. Adding `-c` to `config` doesn't do anything, since it was already defined later and adding `-h` to `hot` broke `help`.
I probably would've left -c for config, as that felt the most natural, but it existed for colors first...

Removes duplicate aliases

---

lib/NodeStuffPlugin.js

If `context` and `moduleJsPath` were not in the same driver, an error like `Cannot resolve "file" or "directory" ./C:/xxx` will be throw.
So, when moduleJsPath is an absolute windows path, just keep it absolute.

Fix windows cross driver path not found issue

---

lib/WebpackOptionsDefaulter.js

The [documentation](https://webpack.github.io/docs/configuration.html#resolve-unsafecache) states that default of the `unsafeCache` option is an empty array, when in fact there is no default at all.
I'm guessing the `fastUnsafe` option actually should be `unsafeCache` as I can't find any other occurance of `fastUnsafe` in the whole project.

Fix unsafeCache default option

---

lib/JsonpMainTemplate.runtime.js
lib/JsonpMainTemplatePlugin.js
lib/webworker/WebWorkerMainTemplate.runtime.js
lib/webworker/WebWorkerMainTemplatePlugin.js

The way that the hot loader is included in a bundle breaks in Java 8's
Nashorn engine, because of a missing semicolon. This change introduces
a placeholder value that can be correctly substituted when building
a bundle, but is otherwise inert.
Note that I don't particularly like this change, so if there's a better
fix, I'd like to hear about it.

Fix hot loader compatibility with Java8 Nashorn

---

bin/convert-argv.js
lib/ProgressPlugin.js

Default handler moved from CLI args parser to plugin itself.
Now you can use ProgressPlugin in JS API without specifying handler.
Resolves webpack/webpack#1000

JS API: ProgressPlugin default handler

---

lib/RequestShortener.js

With some loaders (specifically with babel) under Windows the file names
in the source map already come converted to forward slashes. This is
incompatible with RequestShortener so that the source map paths are not
shortened to a relative path. This change makes RequestShortener tolerant
to such cases while preserving existing behaviour.
Fixes #1770

Fix Windows filename backslash incompatibility

---

examples/common-chunk-and-vendor-chunk/README.md
examples/common-chunk-and-vendor-chunk/build.js
examples/common-chunk-and-vendor-chunk/pageA.js
examples/common-chunk-and-vendor-chunk/pageB.js
examples/common-chunk-and-vendor-chunk/pageC.js
examples/common-chunk-and-vendor-chunk/template.md
examples/common-chunk-and-vendor-chunk/utility1.js
examples/common-chunk-and-vendor-chunk/utility2.js
examples/common-chunk-and-vendor-chunk/utility3.js
examples/common-chunk-and-vendor-chunk/vendor1.js
examples/common-chunk-and-vendor-chunk/vendor2.js
examples/common-chunk-and-vendor-chunk/webpack.config.js

I recently came across a scenario where I wanted webpack to create an explicit vendor bundle, a bundle with all code common to our entry points, and a bundle for each entry point. I knew it was possible but there were no examples close to what we needed. After a lot of trial and error I finally figured out a way to do it and I wanted to share. This example shows how I was able to do it using the `CommonsChunkPlugin `.
If this example isn't quite up to standards, please let me know and I'll be happy to fix any issues. Or, if a very similar example already exists, I can close this as well.
Thanks for the awesome tool. :+1:

Common and vendor chunk example

---

README.md

Update Copyright notice to include 2016. #2

---

lib/JsonpMainTemplatePlugin.js

This adds a new plugin hook that allows adding additional attributes to dynamically created script tags.
@sokra for discussion:
- `webpack-subresource-integrity` would need the following contract for the `jsonp-script` hook: that there is a variable named `script` in scope, bound to the newly created script element, and a variable `chunkId` bound to the respective chunk ID. Can this be codified somehow, or can you think of an alternate approach that doesn't require the plugin code to rely on well-known variable names? 
- I haven't found tests for e.g. the `require-ensure` plugin hook. Do we need to add tests for the `jsonp-script` hook? If so, where would they go?

[WIP] Hooks for subresource integrity

---

lib/EvalDevToolModuleTemplatePlugin.js
lib/WebpackOptionsApply.js

When using `devtool: 'eval-source-map'`, if a source file's last non-empty line is a comment:
``` js
const a = 123
console.log(a)
// test
```
The parser treats it and the source map comment as one single comment and causing the source map to fail. For example, when the above file is loaded with `babel-loader` it ends up showing the log to be from a VM script which is the babel-generated code instead of the source:
Even if the source file contains newlines at end of file, it seems to get trimmed, so adding the newline in the `eval-source-map` plugin seems to be the way to fix it.

fix eval-source-map failing when source ends with comment

---

lib/EvalSourceMapDevToolModuleTemplatePlugin.js

There's about 90+ lint warnings, a lot of which can be solved by moving the variable declaration outside of the `if` like this. Do you want me to go through and fix the rest?

Fix one lint warning

---

lib/LoadersList.js
test/LoaderList.test.js

Currently if user accidentally uses `'loaders'` instead of `'loader'` a very unhelpful `r.forEach is not a function` is thrown.
This commit will throw a helpful error if user uses `loaders` but does not specify an array as he should.

Support loader/loaders with string/array notation

---

lib/RequestShortener.js

With some loaders (specifically with babel) under Windows the file names
in the source map already come converted to forward slashes. This is
incompatible with RequestShortener so that the source map paths are not
shortened to a relative path. This change makes RequestShortener tolerant
to such cases while preserving existing behaviour.
Fixes #1770

Backport: Fix Windows filename backslash incompatibility

---

lib/optimize/CommonsChunkPlugin.js

The error message previously was cryptic, this should help when people transition to webpack2

Use better error message for when given multiple args for CommonChunks Plugin

---

lib/optimize/UglifyJsPlugin.js

Use the following config:
```js
{
plugins: [
new webpack.optimize.UglifyJsPlugin({
mangle: {
props: {
regex: /_$/
},
},
}),
]
}
```
This PR fixes #1983

Fix #1983 : Object properties can be mangle now.

---

lib/Template.js
test/Template.test.js

Template numberToIdentifer produces duplicate identifiers for some values, causing issues when exporting such as 'Cannot redefine property: x';
18 = 25 = s
19 = 26 = t
20 = 27 = u
21 = 28 = v
22 = 29 = w
23 = 30 = x
24 = 31 = y
Fixed up logic and added a test to ensure no duplicates or non identifiers

fix numberToIdentifer so it cant output duplicates

---

.travis.yml

Io.js has been merged back into node, and some tests are failing on iojs-2

Drop io.js from travis

---

lib/EvalSourceMapDevToolModuleTemplatePlugin.js

`source-map` defaults to `//#` here https://github.com/webpack/webpack/blob/master/lib/SourceMapDevToolPlugin.js#L22 but it looks like `eval-source-map` got missed.

Use //# as the default sourceMappingURL format for eval-source-map

---

.travis.yml

iojs is not LTS, so no real need to test on it now that node has merged back.
https://github.com/nodejs/LTS

Test on LTS release of node

---

lib/dependencies/HarmonyExportSpecifierDependency.js
test/cases/compile/issue2221/exportvar.js
test/cases/compile/issue2221/index.js

Add a newline prefix to the code generated for non-immutable harmony exports. This
resolves a case where export statements without a trailing semicolon would cause
webpack to generate a bundle with invalid syntax.

Fix issue #2221 by adding a newline character to generated code

---

lib/Compiler.js

Fixes #2021 
Just a small non-breaking change so it's possible to write simple plugin like this:
compiler.plugin('invalid', function(fileName, changeTime) {
console.log('changed file:', fileName, 'at', changeTime);
});

Pass changed file into `invalid` plugin hook

---

lib/WebpackOptionsApply.js

This commit only be merged into master (2.x). I think it's worth in 1.x, too!

make `electron-main` and `electron-renderer` targets works in 1.x

---

README.md

Updated readme so that CommonJS modules link (which is currently 404'd), points to the CommonJS.org's wiki page.

Fix for #2176. Replaced documentation link for CommonJS to Wiki Page.

---

lib/optimize/CommonsChunkPlugin.js

I introduced the `CommonsChunkPlugin` and experienced some slowdown in my build process. This isn't much, but in my build it was about `75ms` worth of time. Basically this just bypasses calculating `reallyUsedModules` if `minChunks === Infinity`.

CommonsChunkPlugin: skip commonModules calculation if minChunks===Infinity

---

lib/webpack.js

Previously, webpack did not call `MultiCompiler#watch` when passing an array of compiler options. This happened because it was testing for `options.watch` which, when passing an array, is `undefined`. 
With this PR, it checks if any of the passed options has the `watch` flag set to `true`.

:bug: Fix `watch` option recognition with multiple compilers

---

lib/SourceMapDevToolPlugin.js
lib/WebpackOptionsApply.js
test/configCases/source-map/nosources/index.js
test/configCases/source-map/nosources/test.js
test/configCases/source-map/nosources/webpack.config.js

Also available as "nosources" in devtool option.
I'm not aware of any bad side-effects - sourcemaps still work as expected, both minified and normal.
Would solve this issue: https://github.com/webpack/webpack/issues/2034

Option noSources that removes sourcesContent from sourcemaps

---

README.md

I noticed that the URL for Google Web Toolkit's code splitting documentation has changed, and it's a really interesting document so I thought I'd update it.

Updated broken GWT code splitting link

---

bin/webpack.js

the CLI wasn't processing stats presets (added in #1323) and was throwing
```sh
webpack/bin/webpack.js:63
var outputOptions = Object.create(options.stats || firstOptions.stats || {});
^
TypeError: Object prototype may only be an Object or null
```
First PR here and couldn't find a contributor guide, so let me know if you need me to fix/add something =)

Adds stats presets support to the CLI

---

lib/Compiler.js

Replace Object.create() with assign() from object-assign.
Fixes #1354

Copy watchOptions properly in Compiler.js

---

lib/webpack.js

The `ResolverPlugin` was removed in 461c49ab6636e5272362a28a6694d1c626227b05, so accessing it on the `webpack` object now throws an error `Cannot find module './ResolverPlugin'`.

Remove export of ResolverPlugin which no longer exists

---

lib/ModuleFilenameHelpers.js

Using `/*` as comment delimiters allows request names to terminate a comment early, like in https://github.com/carteb/carte-blanche/pull/262.

Prevent request names from breaking comments

---

hot/only-dev-server.js

It had not been updated to webpack 2's Promise ways, so the callback
never happened, as `hotApply` ignored the second argument.

Fix only-dev-server.js's module.hot.apply call

---

hot/only-dev-server.js

If a previous update fails or aborts, the webpackHotUpdate handler stops
calling check(). This is fine in dev-server.js, as any failure will
cause a window.location.reload() anyway, but only-dev-server.js will
complain once and then silently not work anymore.
Sample session output:
```
2016-06-16 12:49:11.698 client:28 [WDS] App updated. Recompiling...
2016-06-16 12:49:13.241 client:95 [WDS] App hot update...
2016-06-16 12:49:13.241 only-dev-server.js:58 [HMR] Checking for updates on the server...
2016-06-16 12:49:13.257 only-dev-server.js:34 [HMR] Cannot apply update. Need to do a full reload!
2016-06-16 12:49:13.257 only-dev-server.js:35 [HMR] Error: Aborted because 274 is not accepted (used by 794)
2016-06-16 12:49:18.780 client:28 [WDS] App updated. Recompiling...
2016-06-16 …
```

only-dev-server: Remind user that hot updates stopped

---

bin/config-optimist.js
bin/config-yargs.js
bin/convert-argv.js

Wasn't supported so far, so I went ahead and added support for it.
I'm not sure if the API is the way you want it though, I wasn't sure how to let people enter an array from the CLI. I made it so we split at "," so usage of this option would look like this:
```Sh
$ webpack --resolve-extensions '.js,.es6'
```
Which will set `resolve.extensions` to `[".js", ".es6"]`. (I also account for whitespace, so `".js, .es6"` also works)
Closes #1447

Add --resolve-extensions support to CLI

---

lib/ContextModule.js

Per #2490, chunks of dynamic System.import dependencies are not re-emitted on hot reload.
Per webpack/extract-text-webpack-plugin#188, the plugin fails because it cannot find the non re-emitted chunk.
The chunks are now emitted when a reload occurs, fixing #2490 and webpack/extract-text-webpack-plugin#188.

Fix issue with async dynamic System.import dependencies not being re-emitted

---

bin/webpack.js

Ref #766
Looks like this when starting webpack with `--watch` (in this case the `i18n` example):
```Sh
➜  webpack git:(log-watching) ✗ ./bin/webpack.js examples/i18n/example.js examples/i18n/build.js --watch
Webpack is watching the files…
Hash: 98c6d507a15cefd64224
Version: webpack 2.1.0-beta.14
Time: 74ms
Asset     Size  Chunks             Chunk Names
build.js  2.09 kB       0  [emitted]  main
[0] (webpack)/examples/i18n/example.js 64 bytes {0} [built]
```

Add log when in watch mode

---

bin/webpack.js

**What is the current behavior?** https://github.com/webpack/webpack/issues/2786
```
webpack --colors
Unknown argument: colors
```
`webpack --colors` === `webpack --color`

supports-color --colors support

---

package.json

No nsp checks currently executed
- nsp checks are executed in the `postcover` script after linting, a failure returns an exit(1) and fails the build.
**Travis output**
* Impact: Failing security check fails the Travis run in postcover.
* Migration path for existing applications: N/A
* Github Issue(s) this is regarding: #2795
- Adds nsp devDependency
- Execute nsp check in `postcover` script
**Question**
IMO a failure for nsp would be a failure that you would …

chore(security): Enables nsp checks

---

hot/only-dev-server.js

The module.hot.apply promise chain was not correctly merged into the module.hot.check() chain.

Add missing return

---

lib/optimize/UglifyJsPlugin.js

When an error occurs during minification of a source-mapped file, the error message indicates the name, line and column of the original file containing the error.
Sometimes the error is the result of an issue with transpilation. In order to ease debugging, the error message is extended with the name, line number and column at which the parsing error occurred in the transpiled file as well.

Log original and mapped filename+line+column on uglify error

---

lib/Compilation.js

Setting _this to null to workaround a bug in V8 that keeps Compilation object alive and makes node run out of memory: https://bugs.chromium.org/p/chromium/issues/detail?id=612191
This usually happens when there's at least one module that shows an error or warning.

Fixing memory leak causing node go out of memory

---

lib/Parser.js
test/Parser.test.js

**What is the current behavior?**
The comments from parsing done by `acorn` are thrown away / ignored.
We keep the comments and pass them along to the `'program'` plugin hook as a second, optional parameter, after the AST. This allows external plugins to make use of the comments contained within the files without re-parsing each file.
Question @TheLarkInn: where should the docs be updated / added?

Keep the parsed comments along with the AST

---

lib/webworker/WebWorkerMainTemplate.runtime.js

`Cannot call method .then() on undefined` when using hot module replacement with a build that has a target of "webworker" because of this line in the `HotModuleReplacement.runtime` ...
https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacement.runtime.js#L170
...which uses Promises, but the `WebWorkerMainTemplate.runtime` was never converted from the old callback-based API:
https://github.com/webpack/webpack/blob/master/lib/webworker/WebWorkerMainTemplate.runtime.js#L16
Switches `WebWorkerMainTemplate.runtime` to a Promises API; no …

fix: Convert webworker template runtime to be Promise-based API

---

.editorconfig
bin/convert-argv.js
examples/web-worker/webpack.config.js
lib/WebpackOptionsValidationError.js
lib/validateWebpackOptions.js
lib/webpack.js
package.json
schemas/webpackOptionsSchema.json
test/Examples.test.js
test/HotTestCases.test.js

Validation is limited to a simple condition:
```js
if(!options.entry && !options.plugins) {
throw new Error("Passed 'options' object does not look like a valid webpack configuration");
}
```
Validation logic is expressed using `./schemas/webpackOptionsSchema.json` JSON schema.
* Impact:
An error is thrown when an unknown configuration is encountered in webpack options object.
This error might appear now because previously unknown configuration was ignored.
* Migration path for …

Use JSON schema to validate webpack config (fixes #2971)

---

bin/convert-argv.js

Running `webpack --config "file1.js" --config "file2.js"` throws a syntax error. #2835 
Running `webpack --config "file1.js" --config "file1.js"` will trigger the MultiCompiler, the same behavior as exporting an array of config objects in a config file.
* Impact:

Support multiple config compiler flags (#2835)

---

.editorconfig
package.json

Currently someone can add files that are not respecting the `.editorconfig` configurations.
The goal in this PR is add standard validation in files, based in `.editorconfig` default configurations. So the build should failure if someone change/add files without respect the current configuration.
This PR doesn't have breaking changes.

Adding file standard validation in repository

---

README.md

Docs
Deprecated readme link (https://github.com/MoOx/cssnext-loader)
Updated to new link (https://github.com/MoOx/postcss-cssnext)
* Impact:

Docs - update deprecated cssnext link

---

bin/config-yargs.js
bin/webpack.js

As discussed in #3015, `--progress` is shared between webpack and WDS.
This is inconsistent, because parsing of this flag happens in `bin/webpack.js` (not accesible by WDS).
Therefore, `--progress` should also be defined in `bin/webpack.js`.
`--progress` is now only defined in the webpack-specific config.
* Impact: WDS needs to be updated.
* Migration path for existing applications: Not relevant, since it's an internal detail …

Moving parsing of the `progress` flag to webpack specific bin

---

schemas/webpackOptionsSchema.json

Any `{ node: { fs: 'empty' } }` will not allow Webpack to run
Any `{ node: { fs: 'empty' } }` will run as it did in beta.22
* Impact:
Support for empty was broken through the schema, so I've added it back. This is exactly why Webpack should only be warning and not throwing errors as I now need to lock down to a version before …

Adds empty into schema for node

---

package.json

Raising so it won't be forgotten, since #3060 was closed for some reason.

Update loader utils dependency to fix #3060

---

lib/NodeStuffPlugin.js
lib/NormalModuleFactory.js
lib/node/NodeSourcePlugin.js

- [ x] Bugfix
**What is the current behavior?**
Issue #3041. With node 0.12.x it fails with
```
/node_modules/webpack/lib/NormalModuleFactory.js:217
return callback(null, Object.assign({}, item, {
^
TypeError: undefined is not a function
```

replaced calls to Object.assign with objectAssign to support node 0.12.x

---

lib/Compilation.js
lib/Compiler.js

No new behavior.
Some segments of code in `lib/Compiler.js` and `lib/Compilation.js` have significant levels of callback nesting, and each callback must bind to `this` to be able to access the Compiler API. This is hazardous and difficult to maintain; it is better to alias `this` to another variable.

reduce fn.bind(this) usage by aliasing `this` to `self`

---

package.json

Node.js >=0.6 is supported according to the `package.json`.
Node.js >= 0.12 is supported. On Slack it was discussed that we should only support active LTS releases.
* Impact: If the user is running a Node.js version older then 0.12, webpack can break.
* Migration path for existing applications: Update Node.js to at least 0.12 
//cc @NekR @danez

Bump required node version to 0.12, the last supported LTS

---

lib/Parser.js
test/Parser.test.js

Now that webpack uses a version of acorn that can parse async/await, enable it (with the appropriate ecmaVersion) and use it to parse.
The main caveat I can think of is that there are new early errors added in ES2016 (e.g. `'use strict'` in the body of functions with complex parameter list).
Fixes #2872.
I am not sure how "sound" this is in case webpack wants to do something special when the call is wrapped in an await, but that is a much bigger refactoring than just accepting and detecting the expressions.

Add async/await support to Parser

---

bin/config-yargs.js
bin/convert-argv.js

If you execute `webpack -v` or `webpack --version`, the help menu is shown. 
If you execute `webpack -v` or `webpack --version`, only the webpack version will show.
This worked before the optimist -> yargs migration, but was not migrated properly.
I also removed some legacy code from before the yargs migration that would show the help menu, but this code was never used.
After this is merged, I will also fix this in webpack-dev-server.

Fix using --version and -v

---

lib/WebpackOptionsValidationError.js
lib/validateWebpackOptions.js
package.json
schemas/webpackOptionsSchema.json
test/Validation.test.js

See #3231. tl;dr - when an option in the scheme uses `instanceof`, all values for that option were always accepted regardless of incorrect type.
It will give a proper error when an option that uses `instanceof` contains an invalid value.
Fixes #3231

Fix validation schema accepting invalid values when `instanceof` is used

---

test/cases/parsing/issue-2895/test.filter.js
test/helpers/supportsBlockScoping.js

Should skip the test in Node 0.12, which doesn't support const.

Add a filter to issue-2895

---

lib/Parser.js
test/cases/parsing/issue-3238/index.js
test/cases/parsing/issue-3238/test.filter.js
test/helpers/supportsIteratorDestructuring.js

This fixes the Parser trying to access the tree of an empty pattern, which is `null`. This is valid syntax, and is useful for skipping iterator elements; `function second ([, x]) { return x }` will skip the first element of any iterator (including an array) and return the second.
I had some trouble with writing the tests; as you will be able to see from the CI results, the Uglify tests (and tests on node <= 4) will fail. `"$(npm bin)"/mocha --harmony --check-leaks -g 'normal.*issue-3238'`, however, passes on node >= 5.
Not sure how I could write a test for this that would only be evaluated on engines (or settings) where it would be supported... because Uglify is an ES5 parser, it's not possible to make this test pass on it other than by using es2015 transforms, which defeats the point of …

Fix issue #3238

---

test/TestCases.test.js

When a TestCase case is skipped, add a mocha output entry indicating it is skipped.
Before (`mocha --harmony --check-leaks -g TestCases`):
```
5855 passing (2m)
32 pending
```
After:
```
5855 passing (2m)
57 pending
```

Log filtered test cases as skipped

---

schemas/webpackOptionsSchema.json

Schema validation of `noParse` breaks with multiple RegExps as of beta26.
`noParse` validation no longer breaks.
Fixes #3284
Note: this should technically be possible to use, but
`uniqueItems` is broken in ajv; see
https://github.com/epoberezkin/ajv/issues/342
Regardless it is better to fix this bug, and there is technically
no reason why identical noParse RegExps are wrong, just superflous.

fix(schema): Remove `uniqueItems: true` from `noParse`

---

lib/NormalModuleFactory.js
test/cases/resolving/issue-2986/errors.js
test/cases/resolving/issue-2986/index.js
test/cases/resolving/issue-2986/node_modules/any-loader.js

``` js
require("any!./file");
```
``` text
(webpack)/test/cases/resolving/issue-2986/index.js
Module not found: Error: Can't resolve 'any' in '...'
```
``` text
(webpack)/test/cases/resolving/issue-2986/index.js
Module not found: Error: Can't resolve 'any' in '...'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
You need to specify 'any-loader' instead of 'any'.
```
Related to #2986

Display a note about the breaking change when forgot the -loader prefix

---

lib/NormalModuleFactory.js

Print `BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders."`
Print `BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders."`
* Impact:
`-loader` is a suffix, not a prefix. A prefix goes at the beginning of a word, and a suffix goes at the end.

Update `-loader`error message

---

bin/convert-argv.js
test/browsertest/build.js
test/browsertest/lib/index.web.js
test/browsertest/library2config.coffee

`--module-bind abc` uses loader `abc` for `*.abc`
`--module-bind abc` uses loader `abc-loader` for `*.abc`
* Impact: `--module-bind` now works again
* Migration path for existing applications: none

`--module-bind` automatically appends `-loader`

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

With the current issue template, people often won't know what to remove exactly.
Also, the first lines are basically shouting at you TO NOT CREATE AN ISSUE IF YOU HAVE A QUESTION. This is okay, but this scares / confuses people (myself included 😱 ). Unfortunately, many people are still asking questions here.
The current PR template has about the same problem; people don't know what to remove. The checkboxes are confusing in the overview, since it makes it seem like the PR is in progress.
The new template asks real questions to the user, making it …

Make issue template easier to understand

---

schemas/webpackOptionsSchema.json

Bugfix
Nope
Nope
**Summary**
With the schema validation, something like this was marked as invalid (#3299):
```js
externals: [
{
a: false,
b: true
},
]
```
But this [is supported](https://github.com/webpack/webpack/blob/master/lib/ExternalModuleFactoryPlugin.js#L25-L26).
No
It fixes #3299.

Allow use of booleans in the `externals` option

---

.eslintrc
bin/webpack.js
lib/AsyncDependenciesBlock.js
lib/ContextReplacementPlugin.js
lib/FlagDependencyExportsPlugin.js
lib/WebpackOptionsValidationError.js
lib/dependencies/HarmonyExportImportedSpecifierDependency.js

This adds some extra rules to the eslint config.
All code already passes the rules, with only very few places that were an exception, so they either disabled the lint rule for the specific line or were fixed.
Other potential rules:
* `"quotes": [2, "double", "avoid-escape"]`: many places that don't follow it, but seems to be the convention
* `"semi": 2`: idem
* `"comma-dangle": [2, "only-multiline"]`: requires eslint upgrade

More eslint rules

---

lib/Parser.js
lib/dependencies/ContextDependencyHelpers.js

Fixes lint errors caused by a combination of different PRs
Alternatively, could disable the valid-jsdoc check. The JSDoc is mostly intended for VS Code autocompletion (the typescript server can use jsdoc as type annotations).

Add descriptions for valid JSDoc

---

lib/APIPlugin.js
lib/JsonpMainTemplatePlugin.js
lib/MainTemplate.js
test/cases/nonce/set-nonce/index.js
test/statsCases/aggressive-splitting-on-demand/expected.txt
test/statsCases/chunks/expected.txt
test/statsCases/optimize-chunks/expected.txt
test/statsCases/preset-verbose/expected.txt

#455
Currently, webpack does provide a way to add nonces to scripts. Given that the future of CSP could be a more nonce-based approach, having support for nonces is increasingly important. 
https://research.google.com/pubs/pub45542.html
When user specifies webpack_nonce, a nonce is added to all loaded scripts. Because nonces are generally different on each page load, the nonce is specified in the entry file, not in the config file, similarly to a public path not known ahead of time.
If this PR contains …

added nonce capability

---

lib/NormalModuleFactory.js
lib/RuleSet.js
test/configCases/loaders/remaining-request/index.js
test/configCases/loaders/remaining-request/loader1.js
test/configCases/loaders/remaining-request/loader2.js
test/configCases/loaders/remaining-request/webpack.config.js

bugfix
yes
N/A
**Summary**
pitching loaders get the `remainingRequest` passed. As this is a string complex options doesn't get passed. Instead the `ident` is passed. This PR fixes the conversion from ident back to complex options.
no, it's a bugfix

fixes a bug in which complex options are not passed through chain

---

lib/Stats.js
test/statsCases/exclude-with-loader/a.txt
test/statsCases/exclude-with-loader/exclude/b.txt
test/statsCases/exclude-with-loader/expected.txt
test/statsCases/exclude-with-loader/index.js
test/statsCases/exclude-with-loader/webpack.config.js

Currently, if loader implementation path matches filter, all modules loaded with it will be under "hidden modules" in stats output.
bugfix
yes
not relevant
**Summary**
As the original issue author noted
> This makes it almost impossible to hide node_modules without hiding your application as well.
no
Fix #1159

Unhide own modules when loader path matches exclude filter

---

lib/dependencies/DepBlockHelpers.js
test/cases/compile/require-context/index.js
test/configCases/async-commons-chunk/require-context/a.js
test/configCases/async-commons-chunk/require-context/b.js
test/configCases/async-commons-chunk/require-context/index.js
test/configCases/async-commons-chunk/require-context/webpack.config.js

Fix lost context when invoking AMD require.  For example:
```
require(['foo', 'bar'], function(foo, bar) {
this.something();   // Error, this points to global scope!!!
}.bind(this));
```
No
N/A
**Summary**
Allow code that attempts to pass context to require callback to work with Webpack.
No
I assumed the the webpack-1 branch was for ongoing 1.x development.  Please let me know if I need to submit this PR to a different branch.

Fix lost context when invoking require()

---

lib/optimize/CommonsChunkPlugin.js

refactoring
No
N/A
**Summary**
* `async` became a keyword ( ES2017 ).
* `var async = ...` broken syntax highlight (on editor, on github).
* Original code(async as a variable) work fine, but make little confuse.
* I try to change variable to `asyncFlag` but `async` option accept string. I choose name `asyncOption`
No

change internal async variable name (CommonsChunkPlugin)

---

lib/Module.js
lib/RecordIdsPlugin.js
test/RecordIdsPlugin.test.js

All module identifiers are relativized on every incremental build (issue #3073).
Relative identifiers get cached on module instances so only changed modules need to call the expensive `makeRelative` function on each build.
- Impact:
- Migration path for existing applications: 
- Github Issue(s) this is regarding:

Cache portable id to avoid expensive function call

---

lib/FunctionModuleTemplatePlugin.js
lib/UseStrictPlugin.js
lib/dependencies/HarmonyImportDependencyParserPlugin.js
test/configCases/code-generation/use-strict/harmony-with-strict.js
test/configCases/code-generation/use-strict/harmony-with-strict2.js
test/configCases/code-generation/use-strict/harmony-with-strict3.js
test/configCases/code-generation/use-strict/harmony-without-strict.js
test/configCases/code-generation/use-strict/harmony-without-strict2.js
test/configCases/code-generation/use-strict/index.js
test/configCases/code-generation/use-strict/webpack.config.js
test/statsCases/tree-shaking/expected.txt

Sort of bug fix
No
**Summary**
This fixes a problem where webpack rendered modules with two "use strict" statements at the beginning
No

Fix double "use strict"

---

README.md

bugfix
yes. sure.
**Summary**
update readme.md, fix html-webpack-plugin link address conflict with html-loader
no
html-webpack-plugin address is conflict with html-loader. when click html-webpack-plugin anchor, it use html-loader address.
so rename html to html-plugin.

fix html-webpack-plugin link address

---

lib/optimize/UglifyJsPlugin.js
test/configCases/plugins/uglifyjs-plugin/ie8.js
test/configCases/plugins/uglifyjs-plugin/index.js
test/configCases/plugins/uglifyjs-plugin/webpack.config.js

Because `options.mangle` was not passed to `ast.figure_out_scope`, `screw_ie8` was not getting passed and ie8 was breaking. I ended up realizing this was the problem after https://github.com/mishoo/UglifyJS2/pull/1344 was merged to fix Uglify's tests. According to uglify's `node.js` file, they pass mangle options (as of https://github.com/mishoo/UglifyJS2/issues/219) so I added that to this plugin as well.
Yes, tests were added to verify that `screw_ie8` was passed along. The tests were derived from the uglify2 tests.
**Summary**
Since the mangle options were not passed, uglify was mangling the function parameters and causing IE8 to break (see …

Pass mangle options to ast.figure_out_scope in uglify

---

lib/ProvidePlugin.js

the named identifier for the scopedName is already set in line 35.
Probably because line 35 was at some point lifted to where it is now.
Merely a cleanup of a duplicate line of code.
**Summary**
Cleanup of duplicate line of code.
No

delete duplicate of line 35

---

lib/dependencies/getFunctionExpression.js
package.json
test/cases/parsing/chunks/index.js
test/cases/parsing/chunks/test.filter.js
test/configCases/target/node-dynamic-import/dir/one.js
test/configCases/target/node-dynamic-import/dir/three.js
test/configCases/target/node-dynamic-import/dir/two.js
test/configCases/target/node-dynamic-import/dir2/one.js
test/configCases/target/node-dynamic-import/dir2/three.js
test/configCases/target/node-dynamic-import/dir2/two.js
test/configCases/target/node-dynamic-import/index.js
test/configCases/target/node-dynamic-import/two.js
test/configCases/target/node-dynamic-import/webpack.config.js

Bugfix. Fixes #959 
* `require.ensure` was erroring when passing arrow function as callback. 
* bumped uglify-js patch level deps
* add node target cases for `import()`
Yes 
N/A
**Summary**
No

fix(require.ensure): add ArrowFunctionExpression support: Fixes #959

---

lib/JsonpMainTemplatePlugin.js
test/statsCases/aggressive-splitting-on-demand/expected.txt
test/statsCases/chunks/expected.txt
test/statsCases/optimize-chunks/expected.txt
test/statsCases/preset-verbose/expected.txt

Appending chunk loading script moved to the end of the function.
Because of unexpected behavior in some cases IE can execute `script` synchronously regardless `async` flag. We need to setup all needed callbacks before appending script to the DOM. It make `jsonp` callback ready to process even synchronous chunk code. 
Issue https://github.com/webpack/webpack/issues/2506

Fix chunk loading in Internet Explorer.

---

test/ConfigTestCases.test.js
test/configCases/dll-plugin/1-use-dll/webpack.config.js
test/configCases/target/node-dynamic-import/test.filter.js
test/helpers/supportsArrowFunctionExpression.js

Bugfix
N/A
N/A
**Summary**
Filters ES6 features so arrow functions don't fail node 0.12 builds on travis. 
No
Fixes #3552

fix(test): Filter ES6 features from node v0.12. Fixes #3552

---

lib/validateSchema.js

Only adds the keyword "instanceof" to Ajv instance (it is the only one used in options schema), rather than all keywords defined in [ajv-keywords](https://github.com/epoberezkin/ajv-keywords) package.
It is already covered, actually less code from ajv-keywords is used.
N/A
**Summary**
It removes the warning (#3562).
No

fix(warning): only use keyword instanceof, fixes #3562

---

CONTRIBUTING.md
test/README.md
test/TestCases.test.js

This PR adds a README.md inside of our test suite.
Repo Documentation
N/A
**Summary**
People seem to not quite yet understand how to add tests and work through the test suite in the webpack code. I think a small rundown will benefit the quality of tests and PR's submitted.

chore(test): Add README.me, CONTRIBUTOR update

---

lib/ProgressPlugin.js

Bugfix.
No. Do I really need to?
N/A
**Summary**
Fixes bug #3591.
No.
The code was erasing (actually: moving the caret back for) too many characters
because the number of characters to move back was being overwritten
too early.
The bug manifests itself only in Windows Command Prompt via npm script
and only when webpack is run in conjunction with other npm scripts. Linux
terminal is also affected, but apparently is more graceful (doesn't allow the
backspace character to jump to the previous terminal line).

Fix progress indicator erasing too many characters. Fixes #3591

---

lib/Compilation.js

the ChunkTemplate contructor only expects one parameter, therefore it seams unnecessary that `this.mainTemplate` is passed
remove superfluous code
**Summary**
passing the main template as a second parameter to the ChunkTemplate is superfluous as the ChunkTempalte only expects one parameter.
No

remove second param to `ChunkTemplate` constructor

---

lib/dependencies/HarmonyExportImportedSpecifierDependency.js
test/cases/parsing/harmony-commonjs/b.js
test/cases/parsing/harmony-commonjs/c.js
test/cases/parsing/harmony-commonjs/c2.js
test/cases/parsing/harmony-commonjs/d.js
test/cases/parsing/harmony-commonjs/index.js

bugfix
yes
N/A
**Summary**
generate a conditional reexport when exports of a module are unknown. Previously a conditional reexport was only generated when the imported module is a non-harmony module.
no

fixes #3584

---

lib/WebpackOptionsDefaulter.js
test/fixtures/temp-1000/file.js
test/fixtures/temp-1000/file2.js
test/statsCases/performance-no-async-chunks-shown/webpack.config.js
test/statsCases/preset-normal-performance-ensure-filter-sourcemaps/webpack.config.js
test/statsCases/preset-normal-performance/webpack.config.js

Feature/Bugfix
Updated existing tests to meet changes needs.
Will need to create issue. 
**Summary**
Performance Hint warnings and errors will be now opt-in. However, the `[big]` entity will now show by default. Currently there is _no_ way in webpack to discern one env from another for developers, therefore its too difficult to control or _determine_ what env a user might be in and when to intelligently display perf hints. 
As much as an organization we want to do our part and encourage users to be aware of the sizes of their web application bundles that they are emitting, the feedback that we have gotten is that for this to be a opt-out, it needs to have …

feat(performancebudgets): set warnings in console off by default

---

.eslintrc
.travis.yml
ci/travis-install.sh

Refactoring, feature, build change.
None needed yet until we define style guide for es6/eslint. 
**Summary**
Node LTE for 0.12 is done at end of year. Since we will not publish another release till after EOY, then it's safe to drop 0.12 support now. This way, contributors can start submitting PR's for using Spread, Class, let, const, etc. 
Only for Node 0.12 users. Migration path would be to use a supported version of NodeJS 4+. 

ci(travis): Drop NodeJS 0.12 support officially & remove from CI Matrix

---

lib/ProvidePlugin.js
test/configCases/plugins/provide-plugin/ddd.js
test/configCases/plugins/provide-plugin/index.js
test/configCases/plugins/provide-plugin/webpack.config.js

Feature
Yes
N/A
**Summary**
Implements the feature request in #2864
The ProvidePlugin could previously only provide top-level (default) exports.  This adds support for providing named exports as well.  The existing API stays the same for default exports.  To provide named exports, the API can also accept an array as `["./module", "property"]`
```js
new ProvidePlugin({
foobar: ["./foo", "bar"]
})
```
foo.js:
```js
bar: "baz"
}
```
```js
console.log(foobar) // "baz"
```
No

ProvidePlugin: support properties from modules. Closes #2864

---

package.json

With the introduction of ES6(-lite) code into `master`, webpack is no longer runnable by node 0.12.
Went with 4.2.3 minimum as it fixes a v8 JSON-related issue.
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#2015-12-04-version-423-argon-lts-rvagg
4.1.0 would be the minimum otherwise as it fixes an important ES6 bug.
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#4.1.0

Update minimum engines

---

.gitignore
lib/NoEmitOnErrorsPlugin.js
lib/webpack.js
test/Errors.test.js
test/fixtures/errors/no-errors-deprecate.js
test/fixtures/temp-cache-fixture/a.js
test/fixtures/temp-cache-fixture/c.js

It moves current NoErrorsPlugin functionality to a more accurately named NoEmitOnErrorsPlugin.
I did.
**Summary**
I saw an issue filed https://github.com/webpack/webpack/issues/3179.
I also think that the new plugin name will make things less confusing for users, ultimately resulting in less open issues. The deprecation warning also helps ease the transition.
It does not. It does provide a warning however that in the future there might be a breaking change coming.
My first contribution - hopefully first of many. I want to acquire innate knowledge of _THE_ best build tool ever and what better way to do it then start off with some bugs / …

No errors plugin deprecate

---

lib/IgnorePlugin.js

N/A
**Summary**
Refactors the IgnorePlugin to an ES6 class. Never contributed before, trying to get into the webpack codebase and understand it a bit more so this seemed like a good place to start. Let me know if I missed anything!
Nope

refactor(es6): refactor IgnorePlugin to ES6 class

---

lib/FunctionModuleTemplatePlugin.js
test/statsCases/aggressive-splitting-entry/expected.txt
test/statsCases/aggressive-splitting-on-demand/expected.txt
test/statsCases/chunks/expected.txt
test/statsCases/max-modules-default/expected.txt
test/statsCases/max-modules/expected.txt
test/statsCases/optimize-chunks/expected.txt
test/statsCases/performance-disabled/expected.txt
test/statsCases/performance-error/expected.txt
test/statsCases/performance-no-hints/expected.txt
test/statsCases/preset-normal-performance-ensure-filter-sourcemaps/expected.txt
test/statsCases/preset-normal-performance/expected.txt
test/statsCases/preset-verbose/expected.txt
test/statsCases/tree-shaking/expected.txt

Feature
N/A
**Summary**
All browser engines currently can be signaled to lazy parse code by wrapping iife's with parents. After speaking with @fhinkel and a few other members of the V8 team, we were recommended that we use this heuristic technique. The change is very minimal in that in converts the output template to go from: 
```
/***/ function(module, exports, __webpack_require__) {
var add = __webpack_require__(/*! ./math */ 1).add;
exports.increment = function(val) {
return add(val, 1);
};
/***/ },
```
to 
```
/***/ (function(module, exports, __webpack_require__) {
var add = __webpack_require__(/*! ./math */ 1).add;
exports.increment = function(val) { …
```

feat(moduletemplate): Wrap function module template wrappers with parens

---

lib/HashedModuleIdsPlugin.js

Refactoring
No functionality was changed, tested in my project (webpack@2.2.0-rc.3)
N/A
**Summary**
Upgrade HashedModuleIdsPlugin to es6.
Nope

refactor(es6): Upgrade HashedModuleIdsPlugin to es6

---

test/Compiler-caching.test.js
test/Compiler.test.js
test/Errors.test.js
test/Integration.test.js
test/NodeTemplatePlugin.test.js
test/Stats.test.js
test/cases/chunks/named-chunks/index.js
test/cases/parsing/template-string/cjs.js
test/configCases/source-map/exclude-chunks-source-map/index.js
test/configCases/target/buffer-default/index.js
test/configCases/target/buffer/index.js
test/configCases/target/web/index.js
test/configCases/target/webworker/index.js

Test bugfix
N/A
**Summary**
`should` type checks need to be called to error if the type check fails. Without calling, the test essentially has an empty body and will pass regardless.
Change made using find/replace in sublime
- Find: `(\.be\.[^(;]+);`
- Replace: `\1();`
No
None

Update missing should type check calls

---

test/SourceMapDevToolModuleOptionsPlugin.test.js
test/helpers/applyPluginWithOptions.js

Add tests for SourceMapDevToolModuleOptionsPlugin
N/A
**Summary**
Based on the coveralls report, the `SourceMapDevToolModuleOptionsPlugin` file has 68% test coverage. There is no `SourceMapDevToolModuleOptionsPlugin` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9491731/source?filename=lib%2FSourceMapDevToolModuleOptionsPlugin.js
No
This PR introduces a helper function for testing plugins. The new function, `applyPluginWithOptions`, allows the plugin logic to be called with different options, and then …

Add tests for SourceMapDevToolModuleOptionsPlugin

---

package.json
test/WebWorkerHotUpdateChunkTemplatePlugin.test.js
yarn.lock

Add tests for webworkerhotupdatechunktemplateplugin
N/A
**Summary**
Based on the coveralls report, the `webworkerhotupdatechunktemplateplugin` file has 41% test coverage. There is no `webworkerhotupdatechunktemplateplugin` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9491731/source?filename=lib%2Fwebworker%2FWebWorkerHotUpdateChunkTemplatePlugin.js
No
This PR is branched off PR #3684, which introduces the `applyPluginWithOptions` helper function. This helper has been used for testing this plugin too. …

Add webworkerhotupdatechunktemplateplugin tests

---

test/RequireJsStuffPlugin.test.js
test/helpers/PluginEnvironment.js
test/helpers/applyPluginWithOptions.js

Add tests for RequireJsStuffPlugin
N/A
**Summary**
Based on the coveralls report, the `RequireJsStuffPlugin` file has 82% test coverage. There is no `RequireJsStuffPlugin` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9498425/source?filename=lib%2FRequireJsStuffPlugin.js
This plugin, although a higher percentage test coverage than other files, was taken on as an example of how to test nested event bindings. This PR extracts the `PluginEnvironment` helper into a separate file, and makes use of it in order to capture internal event handlers for testing.
**Does this PR …

Add tests for RequireJsStuffPlugin

---

test/JsonpHotUpdateChunkTemplatePlugin.test.js
test/NodeHotUpdateChunkTemplatePlugin.test.js

Add tests for two HotUpdateChunkTemplate plugins
N/A
**Summary**
Based on the coveralls report, the `JsonpHotUpdateChunkTemplatePlugin` file has 75% test coverage. 
https://coveralls.io/builds/9498055/source?filename=lib%2FJsonpHotUpdateChunkTemplatePlugin.js
Based on the coveralls report, the `NodeHotUpdateChunkTemplatePlugin` file has 73% test coverage. 
https://coveralls.io/builds/9498425/source?filename=lib%2Fnode%2FNodeHotUpdateChunkTemplatePlugin.js
There are no `JsonpHotUpdateChunkTemplatePlugin` or `NodeHotUpdateChunkTemplatePlugin` specific test files - these are added in this PR and aim to achieve 100% test coverage.
**Does …

Add hotupdatechunktemplateplugin tests

---

lib/dependencies/AMDDefineDependency.js

refactor
N/A
**Summary**
upgrade AMDDefineDependency and AMDDefineDependencyTemplate to es6
No

refactor amd-define dependency to es6

---

test/CaseSensitiveModulesWarning.test.js

Add tests for CaseSensitiveModulesWarning
N/A
**Summary**
Based on the coveralls report, the `CaseSensitiveModulesWarning` file has 18% test coverage. There is no `CaseSensitiveModulesWarning` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9506896/source?filename=lib%2FCaseSensitiveModulesWarning.js
No
The coverage of this file appears to depend on whether it is called in other tests (in other builds it has a coverage of 95%) - https://coveralls.io/builds/9506579/source?filename=lib%2FCaseSensitiveModul …

Add tests for CaseSensitiveModulesWarning

---

test/RequireJsStuffPlugin.test.js

bugfix
Its a test itself
**Summary**
There appears to be a global leak in the RequireJsStuff test
No
**Other**
moved to es6 while i was at it

Fix global leak in requirejsstuff test

---

lib/dependencies/HarmonyExportImportedSpecifierDependency.js

refactor
N/A
**Summary**
upgrade HarmonyExportImportedSpecifierDependency and HarmonyExportImportedSpecifierDependencyTemplate to es6
No

Refactor harmony export import specifier dependency to es6

---

lib/dependencies/HarmonyExportSpecifierDependency.js

refactor
N/A
**Summary**
upgrade HarmonyExportSpecifierDependency and HarmonyExportSpecifierDependencyTemplate to es6
No

refactor HarmonyExportSpecifierDependency to es6

---

lib/MultiCompiler.js
test/WatchTestCases.test.js
test/watchCases/simple/multi-compiler/0/changing-file.js
test/watchCases/simple/multi-compiler/0/index.js
test/watchCases/simple/multi-compiler/0/static-file.js
test/watchCases/simple/multi-compiler/1/changing-file.js
test/watchCases/simple/multi-compiler/webpack.config.js

bugfix
yes
**Summary**
Multi configuration watch is reporting stale stats for configurations that were not changed
no
There is some quirk about running watch tests on Windows/Linux. Change event doesn't fire. It is only observable when MultiCompilation is in use (probably because it uses parallel watchpacks). It is mitigated by adding small delay before changing the files, which is also part of this PR.

Fix multiconfig watch

---

lib/Compilation.js

all tests are passing
**Summary**
Refactoring to ES2015/6
No

refactor(ES6): upgrade Compilation to ES6

---

lib/DependenciesBlockVariable.js
test/DependenciesBlockVariable.test.js

refactor, all existing tests pass. By the way, I'm adding some missed tests for `DependenciesBlockVariable`
N/A
**Summary**
Nope

refactor(DependenciesBlockVariable): upgrade to ES6

---

lib/DllEntryPlugin.js
lib/dependencies/DllEntryDependency.js

refactor
N/A
**Summary**
upgrade DllEntryDependency to es6
No
is the removal of the "type" attribute/param ok?

Refactor dll entry dependency to es6

---

lib/EntryOptionPlugin.js

Refactors `EntryOptionPlugin` to ES2015
No - but no new functionality.
**Summary**
Help the ES2015 migration efforts and record a video on contributing to Webpack :)

Refactor `EntryOptionPlugin` to ES2015 class

---

lib/Compilation.js
test/WatchTestCases.test.js
test/statsCases/separate-css-bundle/expected.txt
test/watchCases/plugins/extract-text-plugin/0/index.js
test/watchCases/plugins/extract-text-plugin/1/style.css
test/watchCases/plugins/extract-text-plugin/webpack.config.js

Without it, child compilations like those added by "extract-text-webpack-plugin" are not included in stats hash and aren't properly displayed on change.
bugfix
yes
**Summary**
Child compilations should affect parent hash.
This bug affects at least extract-text-webpack-plugin. Since child compilation does not affect parent hash, [this](https://github.com/webpack/webpack/blob/7327ee608a040ec784cc251663be85c2aedac44c/bin/webpack.js#L332) code hides the output.
no
Causes https://github.com/webpack/extract-text-webpack-plugin/issues/307

Include child compilation hash into parent hash computation

---

bin/config-yargs.js
bin/webpack.js

PR introduces timestamps on builds and a save option in watch mode to allow a new build to refresh regardless of change. #1499 & #1992 
No
Probably not

Timestamp & Save flag

---

test/statsCases/performance-error/expected.txt
test/statsCases/performance-no-async-chunks-shown/expected.txt
test/statsCases/preset-normal-performance-ensure-filter-sourcemaps/expected.txt
test/statsCases/preset-normal-performance/expected.txt

A rogue extra line ending was breaking stats. This has been fixed now.

fix(tests): fix line endings which broke master statsCases

---

lib/MultiCompiler.js
lib/MultiStats.js
lib/MultiWatching.js
test/MultiCompiler.test.js
test/MultiStats.test.js
test/MultiWatching.test.js

Add tests for MultiCompiler
This PR is only tests, with some code split out
N/A
**Summary**
Based on the coveralls report, the `MultiCompiler` file has 86% test coverage (previously 66% when picked up). There is no `MultiCompiler` specific test file - this is added in this PR as well as splitting out `MultiWatching` and `MultiStats` into separate files for testing, and aims to achieve 100% test coverage.
https://coveralls.io/builds/9547012/source?filename=lib%2FMultiCompiler.js
No
None

Add tests for MultiCompiler

---

lib/dependencies/HarmonyAcceptDependency.js
lib/dependencies/HarmonyAcceptImportDependency.js
lib/dependencies/HarmonyImportDependency.js

refactor
N/A
**Summary**
upgrade HarmonyImportDependency and HarmonyAcceptImportDependency to es6
No
amend usage of HarmonyAcceptImportDependency in HarmonyAcceptDependency

Refactor harmony import and harmony accept import dependency to es6

---

test/LibraryTemplatePlugin.test.js
test/helpers/applyPluginWithOptions.js

Add tests for LibraryTemplatePlugin
N/A
**Summary**
Based on the coveralls report, the `LibraryTemplatePlugin` file has 70% test coverage. There is no `LibraryTemplatePlugin` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9566761/source?filename=lib%2FLibraryTemplatePlugin.js
No
The `applyPluginWithOptions` helper function has been extended to allow multiple arguments which will all be passed into the plugin on instantiation. This is a backwards compatible change.

Add tests for LibraryTemplatePlugin

---

test/AmdMainTemplatePlugin.test.js
test/JsonpExportMainTemplatePlugin.test.js
test/helpers/TemplatePluginEnvironment.js

Add tests for two MainTemplate plugins
N/A
**Summary**
Based on the coveralls report, the `AmdMainTemplatePlugin` file has 14% test coverage.
https://coveralls.io/builds/9568353/source?filename=lib%2FAmdMainTemplatePlugin.js
Based on the coveralls report, the `JsonpExportMainTemplatePlugin` file has 23% test coverage.
https://coveralls.io/builds/9568353/source?filename=lib%2FJsonpExportMainTemplatePlugin.js
There are no `AmdMainTemplatePlugin` or `JsonpExportMainTemplatePlugin` specific test files - these are added in this PR and aim to achieve 100% test coverage.
No …

Add maintemplateplugin tests

---

test/NodeWatchFileSystem.test.js

Like the title says, bump up the test cov.
A tiny contribution to => https://github.com/webpack/webpack/issues/3716
bumps up the test cov for `NodeWatchFileSystem`
They are **just** tests :smile: 
**Summary**
Adds a handful of more tests to `NodeWatchFileSystem` to bump up the test coverage.
Nope

Bump up test coverage on NodeWatchFileSystem test

---

test/CachePlugin.test.js
test/helpers/applyPluginWithOptions.js

Add tests for CachePlugin
N/A
**Summary**
Based on the coveralls report, the `CachePlugin` file has 84% test coverage. There is no `CachePlugin` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9567491/source?filename=lib%2FCachePlugin.js
No
The coverage of this file appears to depend on whether it is called in other tests (in other builds it has a coverage of 86%) - https://coveralls.io/builds/9568583/source?filename=lib%2FCachePlugin.js
The `applyPluginWithOptions` helper function has been update to …

Add tests for CachePlugin

---

lib/dependencies/AMDRequireDependenciesBlock.js

refactoring, ES5 => ES6
No behavioural changes in functions, so all tests should pass
N/A
**Summary**
Upgrade the MovedToPluginWarningPlugin to ES6
NO

refactoring AMDRequireDependenciesBlock to es6 syntax

---

lib/node/NodeHotUpdateChunkTemplatePlugin.js

No, all existing tests pass
If relevant, link to documentation update:
N/A
Summary
upgraded NodeHotUpdateChunkTemplatePlugin to ES6
No

refactor(ES6): upgrade NodeHotUpdateChunkTemplatePlugin to ES6

---

lib/Dependency.js

refactor
N/A
**Summary**
upgrade Dependency.js to es6
No
**Other**
Dont expose compareLocations as Dependency attribute anymore as its only used internally anyways

refactor Dependency.js to es6

---

lib/APIPlugin.js
lib/DefinePlugin.js
lib/ExtendedAPIPlugin.js
lib/HotModuleReplacementPlugin.js
lib/NodeStuffPlugin.js
lib/ParserHelpers.js
lib/ProvidePlugin.js
lib/dependencies/AMDPlugin.js
lib/dependencies/CommonJsPlugin.js
lib/dependencies/RequireEnsurePlugin.js
lib/dependencies/RequireIncludePlugin.js
lib/dependencies/SystemPlugin.js
lib/node/NodeSourcePlugin.js

refactoring
Is covered by existing tests
N/A
**Summary**
While doing my refactorings to es6 i noticed that certain calls to the parser repeat themselves over several modules. 
First I tried to pull them as a whole into a helper function but then realized that for now a more atomic approach should probably be more reasonable, as it removes the sideeffects and makes it reusable throughout the code.
For me the these helper functions abstract a lot of the clutter away and make the code more readable as I can see with one glimpse what is happening.
No
If this approach is "ok" I would love to …

Extract to parser helpers

---

test/checkArrayExpectation.js

currently if you "break" warnings you have no idea which ones where supposed to show
or which module actually failed.
better test hint
N/A
**Summary**
When breaking something on the expected warnings (as in they are not shown anymore) there is no way to figure out which files failed. This at least hints the file that was checked.
NO

give hint what warnings were expected and which file

---

lib/ModuleDependencyError.js
lib/ModuleDependencyWarning.js
lib/dependencies/CommonJsInHarmonyWarning.js
lib/formatLocation.js
test/cases/parsing/harmony-commonjs-error/correct-module.js
test/cases/parsing/harmony-commonjs-error/errors.js
test/cases/parsing/harmony-commonjs-error/index.js
test/cases/parsing/harmony-commonjs-error/wrong-module.js
test/formatLocation.test.js

bugfix, tests
yes
N/A
**Summary**
fixes and tests for #3755

fixes and tests for #3755

---

test/WarnCaseSensitiveModulesPlugin.test.js

Add tests for WarnCaseSensitiveModulesPlugin
N/A
**Summary**
Based on the coveralls report, the `WarnCaseSensitiveModulesPlugin` file has 86% test coverage. There is no `WarnCaseSensitiveModulesPlugin` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9590222/source?filename=lib%2FWarnCaseSensitiveModulesPlugin.js
No
The coverage of this file appears to depend on whether it is called in other tests (in other builds it has a coverage of 100%) - https://coveralls.io/builds/9584589/source?filename=lib%2FWarnC …

Add tests for WarnCaseSensitiveModulesPlugin

---

test/NodeWatchFileSystem.test.js

Run quick NodeWatchFileSystem tests 
This PR is only changes tests
N/A
**Summary**
The `NodeWatchFileSystem` file has tests which are not run as part of the CI run as they are behind `NO_WATCH_TESTS` flag. However, error tests (added as part of #3837) are very fast and increase the reported test coverage. This PR moves these out of the `NO_WATCH_TESTS` flag to be included in the test coverage report.
No
None

Run quick NodeWatchFileSystem tests as part of test run

---

lib/CaseSensitiveModulesWarning.js
test/CaseSensitiveModulesWarning.test.js

refactor to es2015
Tests for the class already present
**Summary**
Refactor the function into an es2015 class
No

Convert CaseSensitiveModulesWarning to es2015

---

lib/dependencies/NullDependency.js
yarn.lock

Removes the useless constructor from `NullDependency`.
No.
**Summary**
```
constructor() {
super();
}
```
doesn't do anything.  There's even an [eslint rule](http://eslint.org/docs/rules/no-useless-constructor) about it.
No.

Remove useless constructor from 'NullDependency'.

---

lib/Compilation.js

Fix (maybe?)
N/A
N/A
**Summary**
updating `chunkHash.update(outputOptions.hashSalt);` with the salt instead of repeatedly the `hash` might fix so far unknown "bugs".
Should not.

Salt chunk hash instead of main hash in loop

---

bin/convert-argv.js
test/binCases/plugins/uglifyjsplugin-empty-args/index.js
test/binCases/plugins/uglifyjsplugin-empty-args/test.js
test/binCases/plugins/uglifyjsplugin-empty-args/test.opts
test/binCases/plugins/uglifyjsplugin-empty-args/webpack.config.js

bugfix
I didn't see any existing CLI tests, so no.
**Summary**
UglifyJsPlugin checks `typeof options !== "object"`, which doesn't work as expected with `null` since its type is `"object"`. https://github.com/webpack/webpack/blob/a1dca894d9a04f55529e4b7c44dcabe2c1b439a1/lib/optimize/UglifyJsPlugin.js#L16
See https://github.com/webpack/webpack/commit/48e17ab308a996928c965c7f29a07735af1b9391#commitcomment-20424582
No

Support UglifyJsPlugin with no arguments in CLI --plugin

---

buildin/return-require.js

Delete dead file
N/A
N/A
**Summary**
buildin/return-require.js has no user anymore and can probably be deleted?
I would think no.

remove buildin/return-require as it has no user (apparently)

---

bin/webpack.js
test/binCases/stats/single-config/test.js
test/binCases/stats/single-config/webpack.config.js

Bugfix for #3946 - all `stats` options provided at Webpack config are being ignored.
It surprises me that such bug is passing existent tests.
N/A
**Summary**
#3946 - stats options being ignored.
No.
The whole issue is quite simple.
I have examined the commit which introduced the bug:
- https://github.com/webpack/webpack/pull/3524/files
Please pay attention at the changes for `lib/MultiStats.js`. There, the lines from 33 to 35 are preventing the bug. I just did the same to `lib/Stats.js`.

Fixes #3946 (stats options being ignored)

---

lib/NormalModule.js
test/configCases/parsing/harmony-global/index.js
test/configCases/parsing/harmony-global/module.js
test/configCases/parsing/harmony-global/module1.js
test/configCases/parsing/harmony-global/webpack.config.js

Bugfix.
N/A
N/A
**Summary**
Patches issue discovered in RC5. exportArguments should be tried first before "exports".
No
Fixes #3917

fix(nmf): Fix exports for var injection to include free glob export or args

---

.travis.yml
bin/webpack.js
lib/Compiler.js
lib/EvalSourceMapDevToolModuleTemplatePlugin.js
lib/LibManifestPlugin.js
lib/SourceMapDevToolPlugin.js
package.json
yarn.lock

Bugfix
N/A
N/A
**Summary**
Because AWS Lambda (see #3984) is only supporting node 4.3 😦 as their max version, this PR rollsback use of `Buffer.from` in favor of the cross version supported `new Buffer`. It is deprecated for the future, but currently, warnings nor errors will emit from use of `new Buffer` even in Node 7@latest. To ensure that this is testing accurately, I've bumped our CI version for node down to 4.3 on travis as well and updated the engine field in our `package.json`
No
Fixed #3984

fix(node): rollback changes of Buffer.from to new Buffer()

---

lib/ChunkTemplate.js
lib/HotUpdateChunkTemplate.js
lib/MainTemplate.js
lib/Template.js

Subclasses include `MainTemplate`, `ChunkTemplate` and
`HotUpdateChunkTemplate`.
Refactor to ES2015.
Tests already present.
**Summary**
Move few files to ES2015.
No.

Convert Template and subclasses to ES2015

---

lib/FlagInitialModulesAsUsedPlugin.js

N/A
**Summary**
Refactor the FlagInitialModulesAsUsedPlugin to an ES6 class
N/A

refactor(es6) upgrade FlagInitialModulesAsUsedPlugin to ES6 class

---

test/ModuleDependencyError.test.js

Add tests for ModuleDependencyError
N/A
**Summary**
Based on the coveralls report, the `ModuleDependencyError` file has 20% test coverage. There is no `ModuleDependencyError` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9689291/source?filename=lib%2FModuleDependencyError.js
No
None

Add tests for ModuleDependencyError

---

lib/compareLocations.js
test/compareLocations.test.js

refactor/fix
yes, adjusted
N/A
**Summary**
What the `compareLocations` function compares are `SourceLocation` objects
or strings(based on current usage). There is no case to assume the input
are position objects. Therefore, remove the useless and unreasonable
code.
Relatively, update the tests to indicate the actual usage.
Not in this repo/on Github. (Not sure if someone misuse it somewhere else)

fix: remove unreasonable comparelocation logic and update test cases

---

test/NullDependency.test.js

Add tests for NullDependency
N/A
**Summary**
Based on the coveralls report, the `NullDependency` file has 80% test coverage. There is no `NullDependency` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9689291/source?filename=lib%2Fdependencies%2FNullDependency.js
No
None

Add tests for NullDependency

---

bin/webpack.js

bugfix
N/A
N/A
**Summary**
fixes #3054 
finishes up of jam removal that was done in `4c7c9290966599dfb81651f87f030fda591ea7a9`
No (i guess)

remove leftovers of jam already removed in 4c7c9290966599dfb81651f87f030fda591ea7a9

---

lib/optimize/AggressiveSplittingPlugin.js

```js
if(chunkModuleNames.length < splitData.modules)
=> 
if(chunkModuleNames.length < splitData.modules.length)
```
The tests pass
N/A

fix AggressiveSplittingPlugin logical bug

---

lib/NormalModuleFactory.js

Add link to migrating guide when omitting the '-loader' suffix.

NormalModuleFactory: link to doc in error message

---

lib/dependencies/WebpackMissingModule.js

Remove unused function in [WebpackMissingModule](https://github.com/webpack/webpack/blob/master/lib/dependencies/WebpackMissingModule.js)
No test needed
**Summary**
Deleted the `moduleMetaInfo` function in [WebpackMissingModule](https://github.com/webpack/webpack/blob/master/lib/dependencies/WebpackMissingModule.js), as part of the effort to increase test coverage (https://github.com/webpack/webpack/issues/3716). That function was only used in `LabeledModuleDependency`, a file that was deleted in https://github.com/webpack/webpack/commit/a14e563f67292cf2bdfe28b01abd8cb5fee1e20e
No

WebpackMissingModule: remove unused function

---

lib/optimize/UglifyJsPlugin.js
test/UglifyJsPlugin.test.js
test/statsCases/warnings-uglifyjs/a.js
test/statsCases/warnings-uglifyjs/expected.txt
test/statsCases/warnings-uglifyjs/index.js
test/statsCases/warnings-uglifyjs/webpack.config.js

feature
yes
N/A
**Summary**
fixes #1496 by adding a `warningsFilter` function to options for the UglifyJsPlugin that decides which warnings should be shown
No
The test setup for uglifyJs is a bit messy so i just hacked in two tests. I didnt feel like making sense out of it.

Allow to supress uglifyjs warnings

---

lib/JsonpMainTemplatePlugin.js

It fixes a grammatical issue in a comment.
No. I really hope that modifying a comment will not have any side effects.
N/A
**Summary**
The indirect article "an" should only be used with nouns that begin with a vowel. (some dialects of English also permit the usage of "an" with words that begin with a vowel *sound* or with an 'h'; however, neither of these cases is relevant to this discussion) The word "Promise" does not begin with a vowel, so it should use the indirect article "a" instead of "an".
No?
I mean, this *would* change the hash of a bundled file, which could result in unnecessarily invalidating caches, …

Fix typo in comment.

---

lib/optimize/UglifyJsPlugin.js
test/UglifyJsPlugin.test.js
test/configCases/plugins/uglifyjs-plugin/extract.js
test/configCases/plugins/uglifyjs-plugin/index.js
test/configCases/plugins/uglifyjs-plugin/webpack.config.js

feature in `UglifyJsPlugin`
yes
Not yet, I will create a documentation PR if you agree with this feature
**Summary**
License comments use up a lot of space, especially when using many small libraries with large license blocks. With this addition, you can extract all license comments to a separate file and remove them from the bundle files. A small banner points to the file containing all license information such that the user can find it if needed.
No
This PR adds a new option `extractComments` to the UglifyJsPlugin.
It can be omitted, then the behavior does not change, or it can be:
- …

UglifyJsPlugin: extract comments to separate file

---

lib/CaseSensitiveModulesWarning.js
lib/ChunkRenderError.js
lib/EntryModuleNotFoundError.js
lib/ModuleBuildError.js
lib/ModuleDependencyError.js
lib/ModuleDependencyWarning.js
lib/ModuleError.js
lib/ModuleNotFoundError.js
lib/ModuleParseError.js
lib/ModuleWarning.js
lib/UnsupportedFeatureWarning.js
lib/WebpackOptionsValidationError.js
lib/dependencies/CriticalDependencyWarning.js
lib/performance/AssetsOverSizeLimitWarning.js
lib/performance/EntrypointsOverSizeLimitWarning.js
lib/performance/NoAsyncChunksWarning.js

So at the moment, when there is a validation error, it only outputs the stack trace, and not the actual error message. Simple reproduction:
```js
const webpack = require('webpack')
webpack({ foo: 'bar' })
```
If you run this, you'll see that the stack trace shows up, but not the actual error message, which is pretty unfortunate.
```
[...]/webpack/lib/webpack.js:19
throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
^
Error
at webpack ([..]/webpack/lib/webpack.js:19:9)
at Object.<anonymous> ([...]/test.js:3:1)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.runMain (module.js:605:10)
at run …
```

Fix Error Formatting Issue

---

lib/dependencies/CommonJsPlugin.js
lib/optimize/CommonsChunkPlugin.js

bugfix
N/A
N/A
**Summary**
In node v4 a `for(const foo of bar)` loop is not correctly evaluated:
Actual:
```
> for(const x of [1,2,3]) {console.log(x)}
1
1
1
undefined
```
expected: 
```
> for(let x of [1,2,3]) {console.log(x)}
1
2
3
```
No

node v4 fails to reassignes const in for-of loops properly

---

lib/NormalModuleFactory.js

A small change that passes the result of running `Resolver.resolve` up through the plugin chain a bit farther.
One reason for this is that it gives compilation plugins access to all the resolved module metadata, like descriptionFileData and allows greater coordination between resolvers and the overall compilation. I think this should enable some more interesting use-cases. such as pruning and optimizing the dependency graph based on package metadata (like semver) instead of just module source hashes. 
Overall doing optimization based on package data has never been a good fit for webpack core, but this should allow others to add stuff on top to suit more personal or specific use cases.

Add resolver result to module callback

---

lib/dependencies/HarmonyModulesHelpers.js
test/HarmonyModulesHelpers.test.js

Adding missed tests for `HarmonyModulesHelpers` library dependency
N/A
**Summary**
Nope

refactor(HarmonyModulesHelpers): upgrade to ES6

---

buildin/system.js
lib/dependencies/SystemPlugin.js

bugfix
Not yet, need to check if this is the way to go
N/A
**Summary**
Instead of evaluating `System` to `{}` this injects a `System` "polyfill"
No
PTAL @sokra @ljharb
i copy & pasted the `buildExpression` might need to want to extract that to parserHelpers if this approach is deemed to be "ok"
fixes #4329

add "buildin" system.js and inject as dependency instead of evaluating to raw object

---

lib/WebpackOptionsDefaulter.js
lib/dependencies/HarmonyImportDependencyParserPlugin.js
lib/dependencies/HarmonyImportSpecifierDependency.js
lib/dependencies/HarmonyModulesPlugin.js
schemas/webpackOptionsSchema.json
test/configCases/compiletime/error-not-found/errors.js
test/configCases/compiletime/error-not-found/index.js
test/configCases/compiletime/error-not-found/stub.js
test/configCases/compiletime/error-not-found/webpack.config.js
test/configCases/compiletime/warn-not-found/index.js
test/configCases/compiletime/warn-not-found/stub.js
test/configCases/compiletime/warn-not-found/warnings.js

feature (bugfix)
Resolves https://github.com/webpack/webpack/issues/4347
Yes 🎉 
Needs written.
**Summary**
This adds support for strict export presence so that a missing export becomes a compile error.
No. It probably should be switched to `true` by default in 3.0 though.

Add strictExportPresence option

---

lib/Compilation.js

bugfix: `hash-for-chunk` is called without a chunk
I didn't see any tests for things like `hash-for-chunk`. I'm happy to add one if someone points me in the right direction.
**Summary**
The [`ChunkHash#updateHashForChunk`](https://github.com/webpack/webpack/blob/343cdc73101d7f91bd3d1bfb3d43fd98434e16b0/lib/ChunkTemplate.js#L32) method accepts a `chunk` parameter, but [`Compilation`](https://github.com/webpack/webpack/blob/343cdc73101d7f91bd3d1bfb3d43fd98434e16b0/lib/Compilation.js#L1128) doesn't pass it. This means that `hash-for-chunk` plugins are called without a chunk.
No

pass chunk to updateHashForChunk

---

buildin/system.js
lib/ParserHelpers.js
lib/dependencies/SystemPlugin.js
lib/node/NodeSourcePlugin.js
test/cases/parsing/issue-2942/index.js
test/cases/parsing/typeof/index.js

followup on #4356
see there for detailed description

Fixup system - follow up on #4356

---

lib/Compiler.js
lib/MultiCompiler.js
lib/MultiWatching.js
test/MultiCompiler.test.js
test/MultiWatching.test.js
test/WatchTestCases.test.js
test/WatcherEvents.test.js

This is a PR for https://github.com/webpack/webpack/issues/4405.
---
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
The only way to know when the watcher stops watching is if you add a callback to `watcher.close()`. If I don't have access to the watcher (e.g. `hot-dev-middleware` created it and I no longer have access to the middleware), then I have no way of knowing that the watcher stopped.
**What is the expected behavior?**
There's already a `watch-run` event.
I would like `webpack.plugin('watch-close', () => console.log('watching closed'))` to be emitted when the watcher has closed and compilation is `done`. 
https://github.com/webpack/webpack/blob/479a0a4b7b22ed9c65c2f3c472a1be56db5ee0f0/lib/Compiler.js#L135
**If this is a feature …

emit watch-close event when watcher closes

---

lib/optimize/FlagIncludedChunksPlugin.js
test/statsCases/commons-chunk-min-size-0/expected.txt

refactoring/bugfix
Amended existing tests
N/A
**Summary**
This prevents chunks without modules to be "integrated" into other chunks as its assumed they are a subset of those, even if they are completly unrelated.
A typical case would be the manifest-chunk that itself does not contain anything, and therefor is added to all other chunks as a dependency.
In the case described in #4438 that leads to unnecessary hash changes between builds.
I am however not aware of any implications of the change, or if the addition of empty-module-chunks is actually an expected behaviour?
Not really
fixes …

Do not merge empty chunks

---

lib/EnvironmentPlugin.js
test/configCases/plugins/environment-plugin/errors.js
test/configCases/plugins/environment-plugin/index.js
test/configCases/plugins/environment-plugin/webpack.config.js

Bugfix in EnvironmentPlugin
Yes
**Summary**
When defining empty environment variables, node reports `process.env.EMPTY === ''`.
```bash
> EMPTY= node -e 'console.log(JSON.stringify(process.env.EMPTY))'
""
```
However, when trying to pass this environment variable into a bundle with EnvironmentPlugin,
it becomes `undefined` with the following warning:
```
EnvironmentPlugin - EMPTY environment variable is undefined.
You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.
```
This PR removes the warning and passes the empty string into the bundle as expected.
It only changes …

EnvironmentPlugin: Support empty env variables

---

lib/Parser.js
package.json

Acorn 5.0.0 introduces a breaking change to conform to what other ESTree-compatible parsers are doing for `export default` declarations (see https://github.com/ternjs/acorn/issues/512). This means that `FunctionDeclaration` and `ClassDeclaration` nodes are no longer guaranteed to have an `id` property. This patch updates the version of the acorn dependency and fixes the code where it assumed such a property is never null.
I was not able to run the tests on my machine (clone, npm install, npm test produced a `Cannot find module 'webpack/lib/Chunk'` error), so I'm hoping the CI will run them for me.

Upgrade to Acorn 5.0.0

---

lib/Compilation.js
test/Chunk.test.js

Test improvement, feature addition
Changes are so small they do not require additional coverage.
**Summary**
I'm using `addEntry` in one of my plugins, and need to be able to get an ID for the module after it has been added, which the `debugId` works quite well for. So this PR passes the module back from the `addEntry` callback, which seems much more reasonable than passing undefined.
While I was looking into `debugId` I noticed that while these ids start from `1000` in the code and only increment, the test verifies that they are over 100, which doesn't really do much, so I updated this to be more accurate.
Nope!

Two small things ✨

---

lib/JsonpMainTemplatePlugin.js

should not call method slice on [object object] #1912
N/A
**Summary**
Fix the code used by webpack2

IE8 for-in, skip prototype property.

---

lib/optimize/CommonsChunkPlugin.js

bugfix
N/A
N/A
**Summary**
fixes the issue mentioned in #4598
No
Not sure why the logic ever was changed or who would do this.
*insert cone of shame image here*

reuse logic as used in 2.2.1 to check what chunks should get their runtime extracted

---

lib/ProgressPlugin.js

refactoring bugfix
no
**Summary**
This PR fixes a ES6 refactoring error caused by 3e22f61bf1ebd04ad052cfb64fd62990a657ec6e
no
[arrow functions does not bind it's own arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)

Fix ProgressPlugin for multi compiler caused by ES6 refactoring

---

lib/NormalModuleFactory.js
test/statsCases/resolve-plugin-context/ResolvePackageFromRootPlugin.js
test/statsCases/resolve-plugin-context/expected.txt
test/statsCases/resolve-plugin-context/index.js
test/statsCases/resolve-plugin-context/node_modules/abc/index.js
test/statsCases/resolve-plugin-context/node_modules/abc/node_modules/xyz/package.json
test/statsCases/resolve-plugin-context/node_modules/abc/package.json
test/statsCases/resolve-plugin-context/node_modules/def/index.js
test/statsCases/resolve-plugin-context/node_modules/def/node_modules/xyz/package.json
test/statsCases/resolve-plugin-context/node_modules/def/package.json
test/statsCases/resolve-plugin-context/node_modules/xyz/package.json
test/statsCases/resolve-plugin-context/package.json
test/statsCases/resolve-plugin-context/webpack.config.js

bugfix
yes
**Summary**
Brings the old behaviour back that was removed in da29d21ae44056ccbd525282300df7184e922d97. This allows us to write custom resolvers that need access to the issuer of a dependency like shown in https://github.com/webpack/webpack/issues/985#issuecomment-260230782
I created a test case within the statsCases with a simplified version of @niieani's plugin to avoid future regressions. 
Possibly, but this will not break existing code. Basically this replaces an empty object with an populated object.

Provide context to resolve again

---

lib/HotModuleReplacement.runtime.js
test/configCases/commons-chunk-plugin/hot-multi/common.js
test/configCases/commons-chunk-plugin/hot-multi/first.js
test/configCases/commons-chunk-plugin/hot-multi/second.js
test/configCases/commons-chunk-plugin/hot-multi/shared.js
test/configCases/commons-chunk-plugin/hot-multi/test.config.js
test/configCases/commons-chunk-plugin/hot-multi/vendor.js
test/configCases/commons-chunk-plugin/hot-multi/webpack.config.js

Bugfix for HMR
Yes, added a test case which reproduces the issue if the fix is not in place. The test case requires using `CommonsChunkPlugin` and multiple entries, but there could be a simpler test case.
**Summary**
When a main module is loaded after a module which is already loaded, the main module should still be marked as a main module, but the current logic causes a main module to be marked a not a main module in this case, which causes issues with HMR. When an incorrectly marked main module is replaced, the current HMR logic will process the update and mark the module as accepted even though it was not.
To fix this issue, this change handles that case by making sure that `hotMainModule` is always …

Fix hot module main flag for hot module replacement

---

lib/NormalModule.js
test/NormalModule.test.js

refactoring
Yes
N/A
**Summary**
I use `_source` property in my [Webpack Runtime Analyzer](https://github.com/smelukov/webpack-runtime-analyzer), but `_source` does not seem a `public` property
I expect to have `someModule.originalSource()` that uses `_source` property.
More details in https://github.com/webpack/webpack/issues/4526
No

Add originalSource method to NormalModule

---

lib/CaseSensitiveModulesWarning.js
lib/ChunkRenderError.js
lib/EntryModuleNotFoundError.js
lib/ModuleBuildError.js
lib/ModuleDependencyError.js
lib/ModuleDependencyWarning.js
lib/ModuleError.js
lib/ModuleNotFoundError.js
lib/ModuleParseError.js
lib/ModuleWarning.js
lib/NormalModule.js
lib/UnsupportedFeatureWarning.js
lib/WebpackError.js
lib/WebpackOptionsValidationError.js
lib/dependencies/CriticalDependencyWarning.js
lib/performance/AssetsOverSizeLimitWarning.js
lib/performance/EntrypointsOverSizeLimitWarning.js
lib/performance/NoAsyncChunksWarning.js
test/WebpackError.test.js

Refactor which introduces new feature.
Yes. Three additional tests have been added.
Currently no PR for documentation exists. Upon review, node api documentation regarding error handling could be altered to show simplified logging approach:
```
if (err) {
return console.error(err);
}
```
**Summary**
Currently the process to log errors is unnecessarily tedious:
```
if (err) {
console.error(err.stack || err);
if (err.details) {
console.error(err.details);
}
return;
}
```
Behind the scenes `console.error` utilizes `util.inspect` to determine how to transform the passed arguments into a string. If the passed argument contains an `inspect` method, …

Webpack error

---

lib/DependenciesBlock.js
lib/Module.js
test/NormalModule.test.js

Refactoring of Webpack Core
Yes
**Summary**
More ES6 code in Webpack Core (`DependenciesBlock` and `Module`)
Inspired #4099
No

ES6 refactoring in DependenciesBlock and Module

---

lib/AsyncDependenciesBlock.js
lib/HotModuleReplacement.runtime.js
lib/HotModuleReplacementPlugin.js
lib/JsonpMainTemplatePlugin.js
lib/NamedChunksPlugin.js
lib/dependencies/DepBlockHelpers.js
lib/optimize/AggressiveSplittingPlugin.js
lib/webpack.js
test/TestCases.test.js
test/statsCases/named-chunks-plugin-async/entry.js
test/statsCases/named-chunks-plugin-async/expected.txt
test/statsCases/named-chunks-plugin-async/modules/a.js
test/statsCases/named-chunks-plugin-async/modules/b.js
test/statsCases/named-chunks-plugin-async/webpack.config.js
test/statsCases/named-chunks-plugin/entry.js
test/statsCases/named-chunks-plugin/expected.txt
test/statsCases/named-chunks-plugin/modules/a.js
test/statsCases/named-chunks-plugin/modules/b.js
test/statsCases/named-chunks-plugin/modules/c.js
test/statsCases/named-chunks-plugin/webpack.config.js

**What kind of change does this PR**
feature
TBD
TBD
**Summary**
based on the work of #3436
Allow chunk ids to be a string, provide NamedChunksPlugin that accepts a `name resolver` function to resolve chunks into names.
This would also allow things like #2682
No
Happy to add proper testing once its ok to go this direction @sokra

Named chunks plugin

---

lib/NormalModuleFactory.js

Refactoring of Webpack Core
No, all current tests still pass
**Summary**
More ES6 code in Webpack Core (`NormalModuleFactory`)
Inspired #4099
No

ES6 refactoring in NormalModuleFactory

---

lib/MultiCompiler.js
lib/webpack.js
test/MultiCompiler.test.js

Fixes https://github.com/webpack/webpack/issues/4156
Updated existing tests which checked for the previous (broken) behavior. Let me know if this is sufficient or you'd like more.
N/A that I'm aware of, but let me know if I'm missing something and happy to update.
**Summary**
Previously, MultiCompiler.watch would apply the watchOptions only from the first set of options to all compilers, regardless of how many options with watchOptions were passed. This changes MultiCompiler to correctly treat those options as an array and apply the relevant watchOptions to each compiler.
Possibly... if someone was depending on …

Update MultiCompiler and lib/webpack to better support multiple watchOptions

---

lib/removeAndDo.js
test/removeAndDo.test.js

ES5 => ES6 refactor and  increasing unit test code coverage
N/A
**Summary**
Helping in part of the ES6 refactor and adding missed unit tests
Nope

refactor(removeAndDo): upgrading to ES6

---

lib/RecordIdsPlugin.js
lib/optimize/AggressiveSplittingPlugin.js
lib/util/identifier.js
test/RecordIdsPlugin.test.js
test/util/identifier.test.js

refactoring
Yes
N/A
**Summary**
Replacement  for #4148 maybe this is good enough performance wise.
Speeds up unifies the `makeRelative` methods used in AggressiveSplittingPlugin and RecordIdsPlugin
No

unify makeRelative method

---

lib/HotModuleReplacement.runtime.js
lib/dependencies/RequireEnsureDependenciesBlock.js
lib/dependencies/RequireEnsureDependenciesBlockParserPlugin.js
lib/dependencies/RequireEnsureDependency.js
test/cases/chunks/named-chunks/index.js
test/cases/parsing/issue-758/errors.js
test/cases/parsing/issue-758/file.js
test/cases/parsing/issue-758/index.js
test/cases/parsing/issue-758/throwing.js

Fixes https://github.com/webpack/webpack/issues/758 by adding support for an error handling callback to require.ensure
Yes, tests added in `test/cases/parsing/issue-758`
These were borrowed/adapted from https://github.com/webpack/webpack/pull/3247.
**Summary**
System.import already supports error callbacks, but require.ensure is still useful for a couple of reasons:
1) Supports chunk naming (https://github.com/webpack/webpack/issues/3132)
2) Supports recursive code splitting (https://github.com/webpack/webpack/issues/3364#issuecomment-273983958)
No. require.ensure still supports chunk naming with the old 3 …

Add error callback support to require.ensure

---

test/ContextDependencyTemplateAsId.test.js

Add tests for ContextDependencyTemplateAsId
N/A
**Summary**
Based on the coveralls report, the `ContextDependencyTemplateAsId` file has 79% test coverage. There is no `ContextDependencyTemplateAsId` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9993625/source?filename=lib%2Fdependencies%2FContextDependencyTemplateAsId.js
No
None

Add tests for ContextDependencyTemplateAsId

---

schemas/webpackOptionsSchema.json

Bugfix: the [output.hashSalt option](https://webpack.js.org/configuration/output/#output-hashsalt) was not actually usable as it was not in the schema.

fix missing `hashSalt` from options schema

---

lib/WebpackOptionsApply.js

This change is splitting `sourceMappingURL` to `source" + "MappingURL` in order to avoid syntax errors caused by babel when importing webpack in code that is transpiled by babel. This workaround was suggested in https://github.com/babel/babel/issues/4012 and this issue is an upstream to https://github.com/electron/electron-compilers/issues/67 and https://github.com/electron/electron-compile/issues/210 .
Apart from a small syntax change there are no changes to the functionality, no breaking changes and no other changes.

Split sourceMappingURL string

---

test/configCases/plugins/provide-plugin/harmony.js
test/configCases/plugins/provide-plugin/index.js
test/configCases/plugins/provide-plugin/webpack.config.js

failing unit test for an unexpected behaviour
this is a unit test
related: https://github.com/webpack/webpack.js.org/pull/1080
**Summary**
This PR introduces a failing unit test for the usage of ProvidePlugin together with an ES2015 module. For importing the default export of an ES2015 module, I can `import 'module'`. Counter-intuitively, this does not hold when using the `ProvidePlugin`: By default, it corresponds to the `import * from 'module'`.
The test `(es2015).should.be.eql("ECMAScript 2015");` in the PR fails with:
```
2) ConfigTestCases plugins provide-plugin should provide ES2015 modules:
AssertionError: expected Object {
default: 'ECMAScript …
```

ProvidePlugin: add test case for ES2015 modules

---

.eslintrc.js

update linting for destructuring and latest node
uses .js rather than .eslintrc file
pulls in rules from
https://github.com/webpack/webpack-cli/pull/46/files#diff-df39304d828831c44a2b9f38cd45289cR40
adds spacing for this

update node linting

---

lib/LibManifestPlugin.js

feature/refactoring
No. As far as I have seen this doesn't affect how the generated `manifest.json` file is tested.
N/A
**Summary**
This disables the JSON pretty print of the - through `DLLPlugin` generated - `manifest.json` file for smaller file size as suggested here https://github.com/webpack/webpack/issues/4477.
No, unless somebody heavily relies on the pretty printed `manifest.json` file.
In case this becomes a breaking change, we could add an option for this as it was suggested in the linked issue.
N/A

Disable manifest.json pretty print

---

lib/Compilation.js
lib/Compiler.js
lib/ContextModule.js
lib/DelegatedModule.js
lib/ExternalModule.js
lib/NormalModule.js
lib/ProgressPlugin.js
lib/RawModule.js

Slightly improved performance.
Nope. But if you insist I could write some test on equivalence between `Date.now()`, `+new Date()` and `new Date().getTime()`.
No documentation update since it is internal minor change.
**Summary**
Use `Date.now()` for slightly better performance since we don't do any manipulation on the created `Date` instance.
Nope.
Crystal clear.

Perf/use Date.now() instead of +new Date()/new Date().getTime()

---

lib/Compiler.js

#3934 introduced a bug as the title says, this fixes that.
No, any pointer to where add this test too? It seems there are no tests for the watcher handler being called correctly with `err`.
**Summary**
This should land ASAP because currently webpack is broken for errors in some plugins.
No.
None.

Fix _done function not dealing with compilation being undefined

---

lib/Compilation.js
lib/Compiler.js

bugfix
no
N/A
**Summary**
fixes #2777
creating a child compiler now assigns correct cache and records
compiler name is made relative
yes
This is a breaking change because plugins or loader could rely on this incorrect behavior
When using child compilations plugins and loaders should use a unique compiler name or use a consistent order

assign correct records and cache to child compilations

---

lib/AsyncDependenciesBlock.js
lib/Chunk.js
lib/FlagInitialModulesAsUsedPlugin.js
lib/HotModuleReplacementPlugin.js
lib/HotUpdateChunkTemplate.js
lib/LibManifestPlugin.js
lib/Stats.js
lib/Template.js
lib/UmdMainTemplatePlugin.js
lib/optimize/AggressiveSplittingPlugin.js
lib/optimize/CommonsChunkPlugin.js
lib/optimize/EnsureChunkConditionsPlugin.js
lib/optimize/FlagIncludedChunksPlugin.js
lib/optimize/MergeDuplicateChunksPlugin.js
lib/optimize/OccurrenceOrderPlugin.js
lib/optimize/RemoveParentModulesPlugin.js
test/Chunk.test.js
test/statsCases/aggressive-splitting-on-demand/expected.txt
test/statsCases/named-chunks-plugin-async/webpack.config.js

refactoring
existing tests
N/A
**Summary**
Use a Set to store modules in a chunk
yes

Use a Set to store modules in a chunk

---

lib/optimize/ConcatenatedModule.js

This code was being generated, which uses a missing variable:
```
/***/ (function(module, __webpack_exports__, __webpack_require__) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```
The outputted error:
```
main.bundle.js:73 Uncaught ReferenceError: exports is not defined
at Object../src/app/app.component.ts ./src/app/app.module.ts ./src/environments/environment.ts ./src/main.ts (main.bundle.js:73)
at __webpack_require__ (bootstrap bd9f482…:56)
at Object.0 (main.ts:11)
at __webpack_require__ (bootstrap bd9f482…:56)
at webpackJsonpCallback (bootstrap bd9f482…:25)
at main.bundle.js:1
```
/cc @thelarkinn @sokra
Bugfix …

Fix exports argument in ConcatenatedModule

---

package.json
test/configCases/plugins/uglifyjs-plugin/index.js
test/statsCases/filter-warnings/expected.txt
test/statsCases/warnings-uglifyjs/expected.txt
yarn.lock

Just requiring a newer version of uglify js that includes a bugfix https://github.com/mishoo/UglifyJS2/issues/1964
No code changes were made.
**Summary**
There was a bug in earlier versions of uglify where the reduce_vars option (which is on by default) was causing some changes to the global RegExp prototype in certain scenarios (such as if babel-polyfill is included). This could break methods like string.split when using node 6 or chrome 51.
No

require a newer version of uglify that fixes a bug with regexp

---

lib/FunctionModuleTemplatePlugin.js

feature/bugfix
No (it's just an info description change and the description wasn't tested anyway)
**Summary**
Closes #4877
No
This change makes most of examples a bit inaccurate (they show old info description). I can alter examples if needed.

change description when no static exports found

---

lib/JsonpMainTemplatePlugin.js
lib/webworker/WebWorkerMainTemplatePlugin.js
test/WebWorkerMainTemplatePlugin.test.js
test/statsCases/commons-chunk-min-size-0/expected.txt
test/statsCases/limit-chunk-count-plugin/expected.txt

bugfix
no
n/a
**Summary**
Use Promise only when chunk load is triggered
don't use it in initialisation
fixes #4916
no

Use Promise only when chunk load is triggered

---

hot/only-dev-server.js

More a feature. Just print an ignored error.
no...
**Summary**
There's an error but I can't see the error due to the try/catch thing
no.

show error when hotOnly HMR fails

---

hot/dev-server.js
hot/log-apply-result.js
hot/log.js
hot/only-dev-server.js
hot/poll.js
hot/signal.js

This is a proof of concept that offers a solution for the HMR logging issue described in https://github.com/webpack/webpack-dev-server/pull/925: 
> There is a long standing issue with the HMR logging in the browser console, which cannot be turned off.
It is based on that PR, but falls back gracefully on webpack-dev-server versions without that PR applied.
This is a bugfix.
No, as this is a proof of concept, I'll add tests if this passes reviews.
N/A
**Summary**
The issue is `webpack-dev-server` related and is detailed in https://github.com/webpack/webpack-dev-server/pull/925.
As this is a proof of concept, it only changes `dev-server.js`, if this passes …

Moved HMR logging to a module, added possibility to set log level.

---

lib/optimize/CommonsChunkPlugin.js
package.json
test/configCases/async-commons-chunk/existing-name/a.js
test/configCases/async-commons-chunk/existing-name/b.js
test/configCases/async-commons-chunk/existing-name/c.js
test/configCases/async-commons-chunk/existing-name/index.js
test/configCases/async-commons-chunk/existing-name/webpack.config.js
yarn.lock

bugfix
Added a ConfigCase to that fails without the fix to prevent future regressions.
**Summary**
When using CommonsChunkPlugin to create async chunks, its currently possible to introduce duplicate chunk blocks.
I found this when I noticed this in the output of my build:
```
Promise.all/* require.ensure */([__webpack_require__.e("main"), __webpack_require__.e("main"), __webpack_require__.e("main")])..
```
The setup I had that reproduced this issue involves the following normal chunks
1. main
2. main + some extra code
3. main + some extra code + all my code
Using the CommonsChunks I basically wanted the chunks to be:
1. main
2. some extra code (with main being an async chunk)
3. rest of my code (with 2 …

CommonsChunkPlugin can cause duplicate chunk blocks

---

lib/node/NodeSourcePlugin.js
schemas/webpackOptionsSchema.json
test/configCases/parsing/node-source-plugin-off/index.js
test/configCases/parsing/node-source-plugin-off/webpack.config.js
test/configCases/parsing/node-source-plugin/index.js
test/configCases/parsing/node-source-plugin/webpack.config.js

Allow a new value `false` for the `node` option to turn off the `NodeSourcePlugin` completely.  
**Summary**
As requested here https://github.com/webpack/webpack/issues/4976, it is desired to have a simple way to turn off `NodeSourcePlugin` completely to avoid any unintentional code to pull in node compatible code for the browser.  Since the plugin supports the `node` option but doesn't have an easy and simple way for turning it off, this PR updates to support that.
No

Support turn off  NodeSourcePlugin with false option

---

lib/Module.js
lib/ModuleReason.js
test/ModuleReason.test.js

Following the previous conversions of modules and chunks to Sets, this converts reasons' chunks to `Sets`.
On a webpack run of a proviate codebase I maintain, this causes time for `rewriteChunkInReasons` to go from `904ms` to `91ms`, although I think this number fluctuates depending on whether I use the debugger or not.
It's overall effect on ApplpyPluginsBailResult1 is below:
Adding more tests vs. #5019 showing that the `Set` approach with deprecated getter fallback is faster than the Map approach employed in #5019

use Set for ModuleReason chunk rewriting

---

lib/RuleSet.js

refactoring
not needed
n/a
**Summary**
It's preferred to use const instead of let, if you don't reassign a variable.
It suggests to other developers that the binding between an identifier's name, and a value/reference will not change.
n/a

Refactor: use const for non reassignable identifier

---

lib/optimize/ConcatenatedModule.js
test/statsCases/scope-hoisting-multi/expected.txt

refactoring
N/A
N/A
**Summary**
Remove dead code and reduce iteration on ConcatModule creation
No

Remove duplicate code

---

lib/RawModule.js
test/RawModule.test.js

bugfix
yes
**Summary** 
`RawModule.updateHash` does not include its own `sourceStr`, leading to hash collisions between different modules. This appears to be a regression introduced in https://github.com/webpack/webpack/commit/5b094c0b5e4e47adccccccdcdc1703db18d85c74
This PR adds an `updateHash` method to RawModule, fixing https://github.com/webpack/webpack/issues/5070
No

fix RawModule hashing

---

package.json
yarn.lock

[uglifyjs-webpack-plugin@v0.4.6](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases/tag/v0.4.6
) update peerDependencies with webpack v3.0.0, but there is another PR #5010, remove uglifyjs-webpack-plugin from the webpack core. Is `uglifyjs-webpack-plugin` a breaking change in v3? Or it will be removed at v4?

update uglifyjs-webpack-plugin to v0.4.6 to support webpack 3

---

lib/node/NodeMainTemplatePlugin.js
lib/webworker/WebWorkerMainTemplatePlugin.js
test/NodeTemplatePlugin.test.js

ES6 refactoring
No
N/A
**Summary**
Convert codebase to ES6. #4099 
No
My first commit to webpack 🤓

ES6 refactor lib/node/NodeMainTemplatePlugin.js

---

lib/Chunk.js
lib/Module.js
lib/optimize/ConcatenatedModule.js
lib/util/SortableSet.js
test/SortableSet.test.js
test/statsCases/scope-hoisting-multi/expected.txt

feature
tested through existing code
N/A
**Summary**
Introduce a "SortableSet" Collection that abstracts the sorting out of the responsibility of Module/Chunk
No
Per default `_chunks` are flagged as sorted in Module, however, this only holds true as they are initialized empty. 
Concatenated Module, however, has initial modules and therefore is not guaranteed to be ordered, the flags should, therefore, be false. Using SortedSet fixes this as a side effect.

Sortable set

---

lib/ContextModuleFactory.js
lib/JsonpMainTemplate.runtime.js

Es6 refactor in /lib folder
No
N/A
**Summary**
The Refactoring makes the code more consistent to the ES6 standards. issue #4099
No
Thanks for the review.

Es6 refactor in /lib folder

---

lib/BasicEvaluatedExpression.js
lib/Parser.js
test/configCases/plugins/define-plugin/index.js

bugfix
yes
N/A
**Summary**
fix #5100
no

accept truthy/falsy value for not

---

lib/optimize/ConcatenatedModule.js

bugfix
No
**Summary**
Current ConcatenatedModule implementation doesn't preserve assets from modules. So those modules will be missing on final emit result. This pull request implements merging assets from modules and save it in generated ConcatenatedModule instance.
no

Preserve assets from concatenated module

---

lib/optimize/ConcatenatedModule.js
test/watchCases/plugins/module-concatenation-plugin/0/bar/a.js
test/watchCases/plugins/module-concatenation-plugin/0/bar/abc.js
test/watchCases/plugins/module-concatenation-plugin/0/bar/b.js
test/watchCases/plugins/module-concatenation-plugin/0/bar/c.js
test/watchCases/plugins/module-concatenation-plugin/0/foo/0.js
test/watchCases/plugins/module-concatenation-plugin/0/index.js
test/watchCases/plugins/module-concatenation-plugin/1/bar/b.js
test/watchCases/plugins/module-concatenation-plugin/1/foo/1.js
test/watchCases/plugins/module-concatenation-plugin/2/bar/c.js
test/watchCases/plugins/module-concatenation-plugin/2/foo/2.js
test/watchCases/plugins/module-concatenation-plugin/webpack.config.js

bugfix #5132 
Yes
N/A
**Summary**
#5132 
As ModuleConcatenationPlugin removes the concatenated modules from a
compilation, the file and context dependencies of those modules needs
to be stored in the ConcatenatedModule for webpack to be able to watch
those paths.
No

Include module file and context dependencies in ConcatenatedModule

---

README.md

The component-webpack-plugin is not maintained. This commit remove the
mention of it from the readme.
Removing component-webpack-plugin from the readme.
No. Only readme changes.
**Summary**
A unmaintained plugin should not be one of the first thing a user reads in the readme. There are plenty of useful and maintained plugins that can be showcased in the readme.
No.

Remove unmaintained plugin from README

---

lib/dependencies/HarmonyModulesHelpers.js

ES6 Refactor of dependencies/HarmonyModuleHelpers.js
Tests were already written.
**Summary**
ES6 Refactor of dependencies/HarmonyModuleHelpers.js as per issue: https://github.com/webpack/webpack/issues/4099

4099 ES6 refactor of dependencies/HarmonyModuleHelpers

---

lib/AmdMainTemplatePlugin.js
test/AmdMainTemplatePlugin.test.js

Replaces deprecated usage of Chunk.modules.
No interface or functional changes.
No documentation update.
**Summary**
Using output: libraryTarget: "amd" causes a deprecation warning. This appears to cause build failures in some circumstances. This change replaces the deprecated property use with an undeprecated method cal which contains the exact same functinality.
No.

Replace deprecated Chunk.modules usage

---

lib/Parser.js
test/Parser.test.js
test/configCases/plugins/provide-plugin/index.js

bugfix
Yes
N/A
**Summary**
This is for fixing #5067.
ProvidePlugin supports replacing IIFE argument's property with resolved modules, but not `this`'s. This PR makes it available.
For example, for code
```
(function(){
window.export = this.jQuery;
}).call(window);
```
config 
```
new webpack.ProvidePlugin({
'window.jQuery': 'jquery',
})
```
will replace the `jQuery` with resolved one.
No
This PR only handles `iife.call()` or `iife.bind()` style call of IIFE, not 
1. The simple `iife()` style as it has more complicated `this` resolving rules (environment, strict mode or not).
2. `.apply`
3. …

[Parser] Support rename this's property for IIFE

---

lib/WebpackOptionsDefaulter.js
package.json
schemas/webpackOptionsSchema.json
yarn.lock

Fixes https://github.com/webpack/webpack/issues/4863
The CI builds will fail because they're pointing to my fork of enhanced-resolve, so this is just an RFC showing how we'd use https://github.com/webpack/enhanced-resolve/pull/92 to address the issue at hand.
In the future, we can even make resolve or resolveLoader plugins specify whether they need `context` and we can make the `cacheWithContext` check smarter.

RFC: Ignore context in resolve caching when resolve or resolveLoader plugins are provided.

---

README.md

README removes jscs-loader as it is marked as abandoned 10 days ago: https://github.com/unindented/jscs-loader
No
**Summary**
I was looking for a linter and found an abandoned project linked via the README.
No

Remove jscs-loader from README as it is abandoned

---

lib/HotModuleReplacementPlugin.js

ES6 Refactor of HotModuleReplacementPlugin
Tests were already written.
**Summary**
Issue:
https://github.com/webpack/webpack/issues/4099
Still working on this PR but I'm a bit stuck and looking for any advice. I managed to fix a lot of the broken tests as a result of the refactor, except for the last few that all seem to stem from the same problem. 
All of the broken tests say something along the lines of "TestCases all-combined chunks .... should compile", along with red text underneath:
Unexpected token: keyword (const) [bundle.js:218,16]
I tried changing everything from const to let just to see how it would go, but then it had issues in the same test file with 'chunkId'.
Does …

4099 ES6 Refactor lib/HotModuleReplacementPlugin

---

bin/convert-argv.js
lib/prepareOptions.js
test/ConfigTestCases.test.js
test/configCases/simple/multi-compiler-functions-export/index.js
test/configCases/simple/multi-compiler-functions-export/webpack.config.js
test/configCases/simple/multi-compiler-functions/index.js
test/configCases/simple/multi-compiler-functions/webpack.config.js

feature
Yes, but let me know if inadequate.
No documentation updates yet, but can provide. Arguably, [the docs already imply that multiple functions are supported](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations).
**Summary**
We already support configurations arrays for the multi-compiler, and configurations as functions in the singular case, but they don't seem to work together - until now.
No.
Feel free to ask.

feat: support config functions with multi-compiler

---

lib/Chunk.js

bugfix
No.
N/A
**Summary**
Added `sortModules` method to `Chunk` class.
`extract-text-webpack-plugin` is emitting extracted css in the incorrect order in which modules are imported due to `Chunk._modules` being converted from an `Array` to a `Set` in `webpack@3`
- https://github.com/webpack/webpack/issues/5204
- https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/548
No.

added sortModules method to Chunk class

---

lib/RequestShortener.js

Minor Refactor  
N/A
N/A
N/A
**Summary**
This hoists RegExp literals inside of request shortener. This should reduce the amount of references created as RequestShortener is instantiated heavily throughout webpack dependencyTemplates and moduleTemplates.

feat(perf): Hoist RegExp literals in RequestShortener

---

lib/Compiler.js
test/Compiler.test.js
test/NodeWatchFileSystem.test.js

ES6 Refactor of lib/Compiler.js module
Yes
**Summary**
Refactored the lib/Compiler.js module to use ES6 as per issue: https://github.com/webpack/webpack/issues/4099
**Other Notes**
I'm also trying to refactor the lib/HotModuleReplacementPlugin and I'm getting a feeling that that file was not meant to be touched because the error messages there are odd. Should I just stop work on that module or is that one meant to be ES6-ified too?
Edit: 
Local test suite passed but the checks failed when I pushed. Closed to let others know I am not currently working on this.
edit2:
Tried it again and tests seem to pass now but the test coverage dropped??
edit3:
Added some tests

4099 ES6 Refactor lib/Compiler.js

---

lib/Parser.js
test/Parser.test.js
test/configCases/plugins/provide-plugin/index.js

bugfix
yes
none
**Summary**
This change is a successor/supplementary/bugfix of #5076, which supports rename `this's property for IIFE for one level `.call`. This PR makes that available for arbitrary level.
For example, #5076 makes this available:
with config
```javascript
new webpack.ProvidePlugin({
'window.jQuery': 'jquery',
})
```
code with one level `.call`
```javascript
(function () {
window.export = this.jQuery;
}).call(window);
```
will replace the `jQuery` with resolved one.
but code with two level `.call`
```javascript
(function () {
(function () {
window.export = this.jQuery;
}).call(this);
}).call(window);
```
`jQuery` would not be replaced. …

[Parser] support rename `this` in `.call(this)` inside arbitrary level `.call` for IIFE

---

.travis.yml
appveyor.yml
ci/travis-install.sh
circle.yml
input.js
lib/EvalSourceMapDevToolModuleTemplatePlugin.js
lib/SourceMapDevToolPlugin.js
package.json
schemas/webpackOptionsSchema.json
test/configCases/source-map/source-map-filename-contenthash/index.js
test/configCases/source-map/source-map-filename-contenthash/webpack.config.js
yarn.lock

backport of bugfixs
N/A
N/A
**Summary**
Not everyone can update to webpack 3 yet.
These user should get the performance improvements and bugfixes made in webpack 3 too.
This doesn't include all improvements and fixes but hey...
The PR also includes CI updates from webpack 3.
no

Backport performance improvements and devtool fixes to webpack 2

---

lib/Compiler.js

Fixed the typo that causes the following error:
*TypeError: this.compiler.compiler is not a function*
everytime after server side hot-reloading and emitting `additional-pass` event.

Fix typo that causes "TypeError: this.compiler.compiler is not a function

---

lib/Compilation.js
lib/NormalModule.js
lib/optimize/ConcatenatedModule.js

performance bugfix
existing tests
N/A
**Summary**
store hash in depndencyTemplates Map instead of comparing identify
This restores original performance on incremental builds
fixes #5289
fixes #5277
a little bit

Restore webpack 2 performance for partial build

---

lib/HotModuleReplacement.runtime.js

Bugfix
**Description**
This bugfix wrap deferred object in Promise to mark it as a well-handled Promise to avoid triggering uncaught exception warning in Chrome, and fixes #5175.
See discussion on the Chrome tracker, https://bugs.chromium.org/p/chromium/issues/detail?id=465666
Inline comment added with reference to the Chrome issue for future references. I don't know if this is an established webpack pattern. 
Credits goes to @sokra  + @B-Reif for the actual code change.
**Validation**
Validated the change in Chrome DevTools and VS Code with Chrome debugger.

Fix uncaught exception warning for HMR updates in Chrome #5175

---

bin/config-yargs.js

Yargs.alias only takes 2 arguments, not 3, this fixes `webpack/bin/config-yargs` using it wrongly.
This should fix the following problem: https://github.com/webpack/webpack-dev-server/issues/983
N/A
https://github.com/yargs/yargs/blob/master/docs/api.md#aliaskey-alias
**Summary**
Fixes https://github.com/webpack/webpack-dev-server/issues/983
Not as far as I know.

Yargs.alias does not take 3 argument, only 2

---

lib/optimize/AggressiveSplittingPlugin.js
lib/util/identifier.js

AggressiveSplittingPlugin asks for relative paths for each (module,chunk) pair for every time it is run (which is a lot if it does multiple splits). On the example in the [webpack stress test](https://github.com/asolove/webpack-stress-test), just looking up relative paths was most of the time in the profile.
This PR adds a manual memoization to the relative path lookup. On the webpack stress test, this reduces the run time from ~60s to ~12s on my machine.
In Slack, there was discussion of two other solutions to this, which are not in this PR:
1. We could actually fix the logic in AggressiveSplittingPlugin. Right now, the plugin re-runs all of its logic every time it makes a split, so if it ends up making N splits, the time required actually grows O(n^2). This should still be done, but it …

[Perf] Memoize relative paths to speed up builds

---

lib/NormalModule.js
lib/optimize/ChunkModuleIdRangePlugin.js

light refactoring
existing tests
n/a
**Summary**
1. Moved usage of `[].concat` to `Array.prototype.concat` to remove the extra array allocation.
2. Collapsed some cases where array iterations could be successfully reduced
no
n/a

refactor: reduce array allocations, remove some excess iterations

---

lib/SourceMapDevToolPlugin.js
yarn.lock

refactoring
using existing tests
n/a
**Summary**
This piece of code was very complicated and hard to read due to all the chaining. It seemed like a good use case for a `reduce` instead of all extra array iterations.
no
n/a

refactor: collapse several array iterators into a single reduce

---

lib/Parser.js
lib/RecordIdsPlugin.js
lib/Stats.js

performance refactoring
existing tests
N/A
**Summary**
unshift -> push
a minimal bugfix in the parser to make it consistent 
no

rewrite code which uses unshift to push

---

bin/config-optimist.js
bin/config-yargs.js
bin/convert-argv.js
test/binCases/config-name/found-many/index.js
test/binCases/config-name/found-many/index2.js
test/binCases/config-name/found-many/test.js
test/binCases/config-name/found-many/test.opts
test/binCases/config-name/found-many/webpack.config.js
test/binCases/config-name/found-one/index.js
test/binCases/config-name/found-one/index2.js
test/binCases/config-name/found-one/test.js
test/binCases/config-name/found-one/test.opts
test/binCases/config-name/found-one/webpack.config.js
test/binCases/config-name/not-found/test.js
test/binCases/config-name/not-found/test.opts
test/binCases/config-name/not-found/webpack.config.js

feature
yes
**Summary**
Adds an option to specify a named configuration to use with multiple configs. 
Implements #2821
no
This option has no effect on single configurations. 
All configurations with a matching name in a multi-config will be compiled.

Add CLI option for selecting a named config from a multi-config

---

lib/optimize/ModuleConcatenationPlugin.js
test/configCases/scope-hoisting/dll-plugin/index.js
test/configCases/scope-hoisting/dll-plugin/webpack.config.js

bugfix
yes
n/a
**Summary**
fixes #5095
no

Make sure it's a real module when choosing for ModuleConcatenation

---

test/cases/parsing/inject-free-vars/index.js

This is just uncommenting a test that was disabled ~4 years ago. Running the test locally seems to work, so I imagine that this was fixed and never revisited.
I found this by looking at the oldest open issue - https://github.com/webpack/webpack/issues/171

[tests] Uncomment inject-free-vars test.

---

examples/scope-hoisting/README.md
lib/optimize/ConcatenatedModule.js
lib/optimize/ModuleConcatenationPlugin.js
test/cases/scope-hoisting/circular-namespace-object/index.js
test/cases/scope-hoisting/circular-namespace-object/module.js
test/cases/scope-hoisting/circular-namespace-object/module2.js
test/cases/scope-hoisting/import-order/commonjs.js
test/cases/scope-hoisting/import-order/index.js
test/cases/scope-hoisting/import-order/module.js
test/cases/scope-hoisting/import-order/tracker.js
test/cases/scope-hoisting/issue-5096/b.js
test/cases/scope-hoisting/issue-5096/index.js
test/cases/scope-hoisting/issue-5443/index.js
test/cases/scope-hoisting/issue-5443/module.js
test/cases/scope-hoisting/issue-5443/reexport.js
test/cases/scope-hoisting/name-conflicts/index.js
test/cases/scope-hoisting/name-conflicts/module.js
test/statsCases/scope-hoisting-multi/expected.txt

refactoring + bugfix
yes
N/A
**Summary**
fixes #5443 
fixes #5288
calls will have the correct this context even with scope hoisting
no

Refactoring Scope Hoisting for correct order and more efficient commonjs interop

---

lib/EntryOptionPlugin.js

What:
Move the function from within the function def to outside, to no longer depend
on function level scope values and instead pass the arguments
explicitly.
Impact:
This is a NOOP change, and only helps improve readability
Test plan:
`yarn test`

Remove function redeclaration.

---

lib/Compilation.js
lib/Compiler.js
lib/ContextModuleFactory.js
lib/Parser.js
lib/UmdMainTemplatePlugin.js

#**What kind of change does this PR introduce?**
Refactoring
Not applicable.  
**Summary**
Related to https://github.com/webpack/webpack/pull/5495
Convert `bind(this)` instances to arrow functions where applicable.  Some binds are in classes and class properties & fields are not supported yet.  
No

Convert .bind(this) to arrow functions

---

lib/Compilation.js

Refactoring
Minor refactor. Not applicable?
**Summary**
Convert function to arrow function, removing the need to bind.
no

Convert errorAndCallback ternary to arrow function

---

lib/optimize/ConcatenatedModule.js

Bugfix
I just return an ability to have access to `ConcatenatedModule.modules`.
**Summary**
Related issue #5477 
No

fix: restore backwards compatibility of ConcatenatedModule (fixes #5477)

---

lib/optimize/ModuleConcatenationPlugin.js
test/HotTestCases.test.js
test/hotCases/concat/reload-external/a.js
test/hotCases/concat/reload-external/b.js
test/hotCases/concat/reload-external/index.js
test/hotCases/concat/reload-external/module.js
test/hotCases/concat/reload-external/webpack.config.js

bugfix
yes
N/A
**Summary**
fixes #5504
no

Disallow Scope Hoisting when using HMR

---

lib/Module.js
lib/optimize/EnsureChunkConditionsPlugin.js
lib/optimize/ModuleConcatenationPlugin.js

bugfix
no, wasn't able to construct a test case.
N/A
**Summary**
EnsureChunkConditionsPlugins didn't update the `_chunks` list of the moved module. This lead to incorrect filled cache in RemoveParentModulesPlugin which incorrectly removed modules from chunks.
fixes #5527
no

Ensure that graph structure stay consistent

---

bin/config-yargs.js
bin/convert-argv.js

bugfix
**Summary**
The document say `--watch-poll` option can determine "The polling interval for watching (also enable polling)". But the previous implement only accept boolean value and no way to set the interval.
This patch try to fix this problem by allow number input like this: `--watch-poll=100`.
This patch also try to keep the original behavior not be changed as much as possible. So `--watch-poll` and `--watch-poll=true` are still acceptable (enable the polling ability).
But still has one incompatible change: original `--watch-poll=` mean disable polling but after this fix it mean enable polling. It's due to `yargs` can not differentiate the different between `--watch-poll` and
`--watch-poll=` when using string type option. So no way …

fix: cli --watch-poll not accept number correctly

---

README.md

URL in README 
Not testable change in this case.
http://www.gwtproject.org/
**Summary**
Problem here is those who interested in GWT can guided to none active archive of google code webpage instead of official website. 
No.

Update GWT's site to official website URL

---

lib/Module.js

Ref: #5562
Fixes #5562.
No - will amend later with tests, first time w/Webpack tests and it's a bit overwhelming at the moment to get a hang of them.
**Summary**
See #5562: ModuleConcatenationPlugin errors snowball over time in incremental builds because this array is not cleared. After a while, the process will crash with an out of memory error.
No.

fix: Clear optimization bailouts on module.disconnect

---

README.md

README bugfix
**Summary**
https://github.com/webpack/webpack/pull/5558 introduced a duplicate link to the GWT project that this PR removes again

README: Fix duplicate GWT link

---

lib/NormalModule.js
test/NormalModule.test.js

When passing a path as part of a loader query string the contextify function incorrectly modifies the query string paths, most notably converting windows separators. The change ensures only the main path is contextified.
Yes
N/A
**Summary**
Fixes: #5411
Possibly if anyone is relying on query string paths to be contextified

Prevent NormalModule contextify from contextifying query parameters

---

lib/SourceMapDevToolPlugin.js
lib/dependencies/HarmonyModulesHelpers.js

Optimization via refactor of 3 `for...of` statements into `for` statements.
Existing test should break if the replacement is incorrect.
**Summary**
According to https://github.com/GoogleChrome/devtools-docs/issues/53#issuecomment-319107156, use of `for...of` statements will cause a deopt in some versions of v8 such as the one used in `node@v6.11.1`, which is still LTS.
In a my particular case these two changes reduced 1.6 seconds in a big rebuild.
No.
Here are two `.cpuprofile` files showing the effect of these changes:
- before: https://drive.google.com/file/d/0B06an8Bxmi7UZFJXOEU1cld5Q0k/view?usp=sharing
- after: …

fix: replace for..of to prevent v8 deoptimization

---

lib/Parser.js
lib/dependencies/AMDDefineDependencyParserPlugin.js
lib/dependencies/CommonJsPlugin.js
lib/dependencies/HarmonyExportDependencyParserPlugin.js
lib/dependencies/HarmonyImportDependencyParserPlugin.js
lib/util/StackedSetMap.js
test/Parser.test.js
yarn.lock

performance
existing tests
N/A
**Summary**
Parser.definitions and Parser.renames are using Maps now
Yes
My first try was using `Set` for definitions, but this was slow because it's often copied for a nested scope. Because of this I implemented `StackedSetMap` which is a stacked versions of `Set` and `Map`. It keeps a stack of parent scope sets/maps to avoid copying. Asking the `StackedSetMap` for a value asks all maps in the stack for the value, starting with the top-most one. A found value is "cached" in the top-most map of the stack. Deleting is implemented as set to the default value in …

Parser performance improvements

---

bin/convert-argv.js
test/binCases/configFile/plugins-presedence/index.js
test/binCases/configFile/plugins-presedence/ok.js
test/binCases/configFile/plugins-presedence/test.js
test/binCases/configFile/plugins-presedence/test.opts
test/binCases/configFile/plugins-presedence/webpack.config.js

closes #4260
Gives plugins presedence over webpack config file when defined through the CLI
Unsure how to test this, but feel free til suggest. Will add if relevant
**Summary**

prepend plugins instead of append when defined through CLI

---

lib/DelegatedModule.js
lib/ExternalModule.js
test/DelegatedModule.test.js
test/ExternalModule.test.js
test/statsCases/external/expected.txt

bugfix
Yes. Also confirm that the added test will fail without this change.
N/A
**Summary**
Fixes #5684 (please see that issue for detailed information and a reproducable case)
Hash of DelegatedModule changed, so users of DllReferencePlugin should expect the compilation/chunk hash to change.
N/A

Fix #5684 DelegatedModule does not updateHash with its parameters

---

lib/JsonpMainTemplate.runtime.js
lib/JsonpMainTemplatePlugin.js
test/statsCases/aggressive-splitting-on-demand/expected.txt
test/statsCases/chunks/expected.txt
test/statsCases/commons-chunk-min-size-0/expected.txt
test/statsCases/commons-plugin-issue-4980/expected.txt
test/statsCases/import-weak/expected.txt
test/statsCases/limit-chunk-count-plugin/expected.txt
test/statsCases/named-chunks-plugin-async/expected.txt
test/statsCases/named-chunks-plugin/expected.txt
test/statsCases/optimize-chunks/expected.txt
test/statsCases/preset-detailed/expected.txt
test/statsCases/preset-normal/expected.txt
test/statsCases/preset-verbose/expected.txt

Cleanup/simplification
N/A
**Summary**
Remove `.type = 'text/javascript'` and `.async = true` on script-inserted elements as they are redundant. `'text/javascript'` is the default type for all `script` elements, and all script-inserted elements are `async` by default.

Remove redundant `.type="text/javascript"` and `.async=true`

---

lib/JsonpMainTemplate.runtime.js
lib/JsonpMainTemplatePlugin.js

Bugfix - or a feature, depending on your point of view.
I didn't see any tests asserting this behavior; however, I ran the change on my own applications and found that it fixed the React 16 errors we were seeing (https://facebook.github.io/react/docs/cross-origin-errors.html)
**Summary**
Also adds the `crossOrigin` attribute to hot-reloaded chunks if `output.crossOriginLoading` is set.
Related: #988
Useful especially for hot-reloaded React 16 apps so that the global
onerror handler can render error boundaries properly.
No breaking change - dev only.

Also add script.crossOrigin for hot-reloaded chunks

---

lib/dependencies/AMDRequireArrayDependency.js
test/cases/amd/namedModules/index.js
test/cases/amd/namedModulesConstArrayDep/index.js

**What kind of change does this PR introduce?** Bug fix
**Did you add tests for your changes?** Yes
**If relevant, link to documentation update:** N/A
**Summary** Fix failure to load named modules (AMD) when using constArray dependencies.
**Does this PR introduce a breaking change?** No
**Other information** Wasn't sure about the location of the unit tests.  Let me know if you want them moved.

Fail to load named modules when using ConstArray dependencies

---

lib/dependencies/AMDDefineDependencyParserPlugin.js

**What kind of change does this PR introduce?** Enhance code reusability
**Did you add tests for your changes?** This change does not affect test coverage
**If relevant, link to documentation update:** N/A
**Summary** Enables reuse of "call define" processing by subclasses that need to override define dependency object creation.
**Does this PR introduce a breaking change?** No

Make define dependency object creation overridable.

---

lib/UmdMainTemplatePlugin.js
test/configCases/externals/non-umd-externals-umd/index.js
test/configCases/externals/non-umd-externals-umd/test.config.js
test/configCases/externals/non-umd-externals-umd/webpack.config.js
test/configCases/externals/non-umd-externals-umd2/index.js
test/configCases/externals/non-umd-externals-umd2/test.config.js
test/configCases/externals/non-umd-externals-umd2/webpack.config.js

Depending on if the issue I raised can be considered a bug, this is either a bugfix or a feature 😃
This change should remove `require`/`define` statements, whose output does not end up being used when using non-UMD externals (such as `var`) as seen in the diff here: https://github.com/NMinhNguyen/webpack-umd-with-var-externals-example/commit/f0126c58e1e7e0b5d096eed9ab613024d7ce9b8b
No, ~~as there weren't any existing tests for `UmdMainTemplatePlugin`~~, but I'm happy to add them if necessary - I realise this is quite an important part of the code. All existing tests pass though.
Update: I was looking for a `UmdMainTemplatePlugin.test.js` file but I now realise this code is actually tested via …

Only use UMD or UMD2 externals for UMD libraryTarget. Resolve #5766

---

examples/common-chunk-grandchildren/README.md
examples/common-chunk-grandchildren/build.js
examples/common-chunk-grandchildren/example.js
examples/common-chunk-grandchildren/pageA.js
examples/common-chunk-grandchildren/pageB.js
examples/common-chunk-grandchildren/pageC.js
examples/common-chunk-grandchildren/reusableComponent.js
examples/common-chunk-grandchildren/template.md
examples/common-chunk-grandchildren/webpack.config.js
examples/template-common.js
lib/optimize/CommonsChunkPlugin.js
test/configCases/commons-chunk-plugin/move-to-grandparent/index.js
test/configCases/commons-chunk-plugin/move-to-grandparent/pageA.js
test/configCases/commons-chunk-plugin/move-to-grandparent/pageB.js
test/configCases/commons-chunk-plugin/move-to-grandparent/pageC.js
test/configCases/commons-chunk-plugin/move-to-grandparent/reusableComponent.js
test/configCases/commons-chunk-plugin/move-to-grandparent/second.js
test/configCases/commons-chunk-plugin/move-to-grandparent/test.config.js
test/configCases/commons-chunk-plugin/move-to-grandparent/webpack.config.js

Feature
Yes
https://github.com/webpack/webpack.js.org/pull/1625
**Summary**
If you use the CommonsChunkPlugin with the children flag enabled it currently only cares about direct children. This change makes it so it cares about all children that are not required from somewhere else than the common chunk.
https://github.com/webpack/webpack/issues/3981
If the config deepChildren isn't set the behavior stays the same as before, it only changes if the flag gets set.
Thanks to Florian Scholz (ArcEglos) for doing all the work.
https://github.com/webpack/webpack/pull/4255

Added deepChildren support from ArcEglos' pull request

---

lib/dependencies/AMDRequireContextDependency.js
lib/dependencies/CommonJsRequireContextDependency.js
lib/dependencies/ContextDependency.js
lib/dependencies/ImportContextDependency.js
lib/dependencies/RequireResolveContextDependency.js
test/cases/context/issue-5750/index.js
test/cases/context/issue-5750/warnings.js

Fix for #5750. Adds a warning if the g or y regex flag is passed to a context, and causes the context to become empty.
~No.~ Yes.
No new documentation. The error message copy is "Contexts can't use RegExps with the 'g' or 'y' flags."
**Summary**
Using the g or y flags causes files to be missing from a context. See #5750.
Previously, using the g flag could output garbage, now it always outputs a warning and an empty context.
Nope

Fix for #5750 - Refuse to use regexes with g or y flags in contexts

---

lib/ContextExclusionPlugin.js
lib/ContextModuleFactory.js
lib/webpack.js
test/configCases/context-exclusion/simple/index.js
test/configCases/context-exclusion/simple/some-dir/check-here/check-here/file.js
test/configCases/context-exclusion/simple/some-dir/check-here/dont-check-here/file.js
test/configCases/context-exclusion/simple/some-dir/check-here/file.js
test/configCases/context-exclusion/simple/some-dir/dont-check-here/file.js
test/configCases/context-exclusion/simple/some-dir/dont.js
test/configCases/context-exclusion/simple/some-dir/file.js
test/configCases/context-exclusion/simple/webpack.config.js

feature/fix
Yes
N/A
**Summary**
There are a couple of reasons this could be helpfull:
1) If a context points to a folder with potentially many files the current process can be quite inefficient - also a "positive" matching as could be doable with `ContextReplacementPlugin` is not always possible. This helps speed up the build-time and allows for negative matching.
2) Webpack fails to detect symlinks in node_modules and having a context pointing to local linked package that contains node_modules can lead to endless loops, this can simply be prevented with this plugin by excluding `node_modules`.
3) The ContextReplacementPlugin covers too much to stuff this …

Allow negative early bail for context

---

lib/ExternalModule.js
test/ExternalModule.test.js

When `this.optional` is not set, undefined must be coerced to `false`.
Bugfix
Yes
**Summary**
See #5806 
No

Fix #5806, TypeError on ExternalModule hash.update

---

lib/ContextModuleFactory.js
test/ContextModuleFactory.test.js

Bugfix for #5794
Yup
Nope
**Summary**
When --watch triggers a rebuild due to a delete/rename/move on Windows, it's possible for the `fs.readdir` call in `ContextModuleFactory.resolveDependencies` to return the file that was just removed. Then it tries to do `fs.stat` on the file, which fails. So it should ignore those errors.
Nope
Nope

Fix #5794 by ignoring ENOENT errors in ContextModuleFactory.addDependencies

---

schemas/webpackOptionsSchema.json
test/Validation.test.js
test/statsCases/module-deduplication-named/webpack.config.js
test/statsCases/module-deduplication/webpack.config.js

- Updates webpackOptionsSchema "stats" object to include "additionalProperties: false"
- Adds missing stats options
- Adds test for ensuring new stats options fail the schema check (if not included)
Fix/Test Update
Yes - I've added a Validation test for the `stats` object and it's use of `additionalProperties: false`
N/A
**Summary**
Update based on @sokra's comment on #5811 ([here](https://github.com/webpack/webpack/pull/5811#issuecomment-336397137)). This adds a test that ensures validation will fail for the `stats` object if there are properties found in the configuration and _not_ in the schema …

[fix] webpackOptionsSchema

---

test/statsCases/module-deduplication-named/expected.txt
test/statsCases/module-deduplication-named/webpack.config.js
test/statsCases/module-deduplication/expected.txt
test/statsCases/module-deduplication/webpack.config.js

- Uses `timings: false` for module-deduplication tests and updates expected output.
Test update based on feedback in #5825 (https://github.com/webpack/webpack/pull/5825#discussion_r144687411) 
Updated existing.

[tests] statsCases/module-deduplication

---

lib/Compiler.js

Bugfix, watch-run event hook param should be `compiler`, but the param is `Watching` instance now
No, I think there is no need for tests.
**Summary**
watch-run params error.
The watch-run event params: from watching to compiler

fix: watch-run params should be compiler

---

schemas/webpackOptionsSchema.json

Related to #5841 and #5840 
This one is undocumented, but technically a valid option. (https://github.com/webpack/webpack/blob/master/lib/Stats.js#L85)
bugfix
No
https://github.com/webpack/webpack.js.org/pull/1652

adds stats.all option the the webpackOptionsSchema

---

.eslintrc.js
.travis.yml
circle.yml
package.json
test/configCases/extract-text/issue-14/index.js
test/mocha.opts
yarn.lock

Refactor, feature.
N/A
**Summary**
This PR: 
* updates minimum NodeJS Requirements to 6.11.5
* updates node-eslint-plugin to check against package.json "engines" property
* update engines prop in package.json
* update all dependencies to install latest minor and patch level changes
Since we are dropping node 4 support in webpack v4, this is being applied against the next branch.
Yes.
This is a hard requirement for webpack/webpack#next branch (and eventually master) to drop node 4 as LTS has ended for it. 

chore(deps): update all minor and patch deps, remove lint errors

---

lib/ContextModule.js
lib/ContextModuleFactory.js
lib/ContextReplacementPlugin.js
test/cases/parsing/context/index.js
test/cases/parsing/context/loaders/queryloader.js
test/configCases/context-replacement/d/index.js
test/configCases/context-replacement/d/modules/a.js
test/configCases/context-replacement/d/queryloader.js
test/configCases/context-replacement/d/webpack.config.js

Adds support for resource queries in context dependencies.
Yes
N/A
**Summary**
Some loaders require resource query for proper usage, and cannot be used at all with context dependencies.
No, it only affects code that adds a resource query to a context, which currently does not work at all.
Fixes #5730

Support resourceQuery in context dependencies.

---

lib/dependencies/AMDDefineDependency.js
lib/dependencies/AMDDefineDependencyParserPlugin.js
lib/dependencies/AMDRequireDependency.js
test/cases/parsing/extract-amd.nominimize/a.js
test/cases/parsing/extract-amd.nominimize/amdmodule.js
test/cases/parsing/extract-amd.nominimize/c.js
test/cases/parsing/extract-amd.nominimize/circular.js
test/cases/parsing/extract-amd.nominimize/constructor.js
test/cases/parsing/extract-amd.nominimize/d.js
test/cases/parsing/extract-amd.nominimize/index.js
test/cases/parsing/extract-amd.nominimize/optional.js
test/cases/parsing/extract-amd.nominimize/templates/a.js
test/cases/parsing/extract-amd.nominimize/templates/b.js
test/cases/parsing/extract-amd.nominimize/templates/c.js
test/cases/parsing/extract-amd.nominimize/test.filter.js
test/cases/parsing/extract-amd.nominimize/warnings.js
test/cases/parsing/extract-amd/index.js

bugfix
Yes tests have been added.
N/A
**Summary**
This is a bugfix for https://github.com/webpack/webpack/issues/5916
AMD define with arrow function was not including dependencies.
```js
define((require) => { ... });
```
No.

Handle amd define with arrow function

---

lib/optimize/ConcatenatedModule.js

Memory usage optimization.
I couldn't find a test for module names, it doesn't seem like it is tested currently.
**Summary**
See https://github.com/webpack/webpack/issues/5992#issuecomment-346384896 for rationale.
Fixes #5992
No.

Use shorter identifier for ConcatenatedModules

---

lib/Compiler.js

fix parser.apply.apply instead of parser.apply in lib/Compiler.js
related to https://github.com/webpack/webpack/pull/5985
**Summary**
No

fix: Compiler parser.apply.apply misssing bug

---

lib/WebpackOptionsDefaulter.js
lib/dependencies/HarmonyDetectionParserPlugin.js
lib/dependencies/HarmonyExportDependencyParserPlugin.js
lib/dependencies/HarmonyExportImportedSpecifierDependency.js
lib/dependencies/HarmonyImportDependency.js
lib/dependencies/HarmonyImportSpecifierDependency.js
lib/dependencies/HarmonyModulesPlugin.js
lib/optimize/ConcatenatedModule.js
test/cases/mjs/cjs-import-default/cjs.js
test/cases/mjs/cjs-import-default/errors.js
test/cases/mjs/cjs-import-default/index.mjs
test/cases/mjs/cjs-import-default/reexport.mjs
test/cases/mjs/need-extension/errors.js
test/cases/mjs/need-extension/index.js
test/cases/mjs/need-extension/module.js
test/cases/mjs/need-extension/module.mjs
test/cases/mjs/need-extension/test.mjs

feature
yes
n/a
**Summary**
process imports from mjs to non-esm correctly 
give nice error messages when importing non-esm the wrong way
It also disallows using namespace object from non-esm modules
fixes #5686
yes

 process imports from mjs to non-esm correctly

---

lib/optimize/ConcatenatedModule.js

Optimization
No
**Summary**
This was implemented in #5997 to fix some memory issues, but I think we
can make this a little more efficient. By using a single forEach instead
of a map, filter, and join, we avoid unnecessary array creations and
iterations.
No

Simplify identifier creation in ConcatenatedModules

---

lib/JsonpMainTemplatePlugin.js
lib/webworker/WebWorkerMainTemplatePlugin.js
test/WebWorkerMainTemplatePlugin.unittest.js

It's a bug fix.
Update test.
N/A
**Summary**
We notice a bug in webpack HMR during our spike on creating es6 bundles.
Bug:
- `bootstrap` dev bundle containes a `this` no longer bound to `window`, so it was undefined.
Fix:
- Use `window` instead of `this` in both scripts templates.
This bug was identifed in #5776
No.
Fix #5776
Made with @osirisxxl

[fix] error on HMR with es6 bundles

---

examples/README.md

This started out as pure-module, but was moved without
this link being updated.

Fix link to side-effects example

---

test/helpers/PluginEnvironment.js

Feature / bugfix
No
**Summary**
While converting some plugins to `Tapable` I noticed that the tests started to fail since `PluginEnvironment` does not correctly mock what is passed to `Plugin#apply()`. Some test cases use `PluginEnvironment` to monitor plugins' actions. Before this change, it only mocked `.plugin()` which is not enough to test plugins written using `Tapable#hooks`.
This implementation uses a `Proxy` to trap hook calls and log them as events.
```js
class SomePlugin {
apply(compiler) {
compiler.hooks.afterCompile.tap("SomePlugin", handler)
//       ^^^^^ ^^^^^^^^^^^^ ^^^
//         |         |       logs { name: "after-compile", handler }
//    this is now    |
//      a Proxy     fake …
```

Improve `PluginEnvironment` helper to support tapable's hooks

---

schemas/webpackOptionsSchema.json

A bugfix to permit the valid use of the `ident` property described [here]() in `Rule.use`. This was identified as part of #6080.
I don't think this requires any tests but please let me know if it does.
None required, this brings webpack in line with it's existing documentation.
**Summary**
See #6080.
No
Thank you for reviewing, and let me know if this isn't the right solution or there are any changes required.

Add ident to the list of permissible properties for Rule.use

---

lib/MainTemplate.js

Fix #6082
Refactoring
No, only manual testing. 
Unit/integration tests were not testing the hash.
#6082 
**Summary**
Before this change, a hash was appended to `webpack:///webpack/bootstrap`
and appeared in source maps' `sources`.
```js
// before
{"version":3,"sources":["webpack:///webpack/bootstrap a0df2f8d793658baad72",…
// now
{"version":3,"sources":["webpack:///webpack/bootstrap",…
```
Yes
Fixes #6082 
> @sokra 
> Send a PR to remove this hash in the next branch. It's not needed anyway...

Remove `webpack/bootstrap` hash in source map

---

lib/LibManifestPlugin.js

Refactor
N/A
N/A
**Summary**
This upgrades LibManifestPlugin to Tapable v1 and also changes new Buffer to Buffer.from() (which is deprecated in Node 6. 
Nope!

feat(tapable): upgrade LibManifestPlugin to Tapable v1

---

test/configCases/loaders/remaining-request/webpack.config.js

Bugfix
This updates an existing test.
This is some follow-on work from #6089. See [here](https://github.com/webpack/webpack/pull/6089#issuecomment-350196066) for context.
**Summary**
Moves the `ident` property to the correct location.
No

Fix ident config position

---

lib/WebpackOptionsDefaulter.js

Performance
**Summary**
With the addition of `modes` Webpack now runs uglify by default which is currently initialized with the `sourcemap` option only. Given we are trying to simplify the onboarding, imo it makes sense to leverage the caching / threading in the uglify plugin to improve build performance ( see below )
No
```
const path = require('path');
const webpack = require('webpack');
entry: './index.js',
mode: 'production',
output: {
path: path.resolve(__dirname, './dist'),
filename: 'bundle.js',
},
plugins: [
new webpack.optimize.ModuleConcatenationPlugin(),
],
}; …
```

perf: Enables uglify cache in prod mode

---

lib/APIPlugin.js
lib/DefinePlugin.js
lib/ExtendedAPIPlugin.js
lib/HotModuleReplacementPlugin.js
lib/NodeStuffPlugin.js
lib/ParserHelpers.js
lib/ProvidePlugin.js
lib/RequireJsStuffPlugin.js
lib/dependencies/AMDPlugin.js
lib/dependencies/CommonJsPlugin.js
lib/dependencies/CommonJsRequireDependencyParserPlugin.js
lib/dependencies/RequireEnsurePlugin.js
lib/dependencies/RequireIncludePlugin.js
lib/dependencies/SystemPlugin.js

refactoring
n/a
n/a
**Summary**
`Tapable`'s hooks are not bound to the parser instance. Without this change, the following would throw a `TypeError`:
```js
ParserHelpers.expressionIsUnsupported(parser, name + " is not supported.")
```
This PR modifies the `Parser` helpers to not rely on `this`.
no
An alternative approach could have been used using `.bind(parser)`:
```js
ParserHelpers.expressionIsUnsupported(name + " is not supporte.").bind(parser)
```

Update Parser helpers to be compatible with hooks

---

lib/NodeStuffPlugin.js
lib/optimize/ModuleConcatenationPlugin.js
test/statsCases/scope-hoisting-bailouts/cjs.js
test/statsCases/scope-hoisting-bailouts/entry.js
test/statsCases/scope-hoisting-bailouts/eval.js
test/statsCases/scope-hoisting-bailouts/expected.txt
test/statsCases/scope-hoisting-bailouts/index.js
test/statsCases/scope-hoisting-bailouts/injected-vars.js
test/statsCases/scope-hoisting-bailouts/module-id.js
test/statsCases/scope-hoisting-bailouts/module-loaded.js
test/statsCases/scope-hoisting-bailouts/ref-from-cjs.js
test/statsCases/scope-hoisting-bailouts/webpack.config.js
test/statsCases/separate-css-bundle/expected.txt

bugfix. fixes #6017 
yes
n/a
**Summary**
This PR allows `ModuleConcatenationPlugin` to bail out when a module uses `module.id` or `module.loaded` since these expressions are no longer relevant after concatenation.
Files:
```js
// a.js (entry)
import b from "./b.js"
console.log(b)
```
```js
// b.js
export default module.id
```
Output:
```
❯ yarn webpack --config bailout-id/config.js --display-optimization-bailout
yarn run v1.3.2
$ /Users/fc/webpack/node_modules/.bin/webpack --config bailout-id/config.js --display-optimization-bailout
Hash: d3abb67758605db0eb26
Version: webpack 4.0.0-alpha.1
Time: 159ms
Asset      Size  Chunks             Chunk Names
out.js …
```

Bail out concatenation if module uses module.id or module.loaded

---

test/WatchDetection.test.js
test/WatchTestCases.test.js
test/WatcherEvents.test.js

test changes
no
n/a
**Summary**
Allow _watcher_-related integration tests to be skipped.
This was already possible in unit tests:
https://github.com/webpack/webpack/blob/0c4d69b7c63f3dfa2b25faaed3ada84e9e9f8fbc/test/NodeWatchFileSystem.unittest.js#L49-L52
no

Allow watch tests to be skip

---

lib/APIPlugin.js
lib/CompatibilityPlugin.js
lib/ConstPlugin.js
lib/DefinePlugin.js
lib/ExtendedAPIPlugin.js
lib/HotModuleReplacementPlugin.js
lib/NodeStuffPlugin.js
lib/Parser.js
lib/RequireJsStuffPlugin.js
lib/dependencies/AMDDefineDependencyParserPlugin.js
lib/dependencies/AMDPlugin.js
lib/dependencies/AMDRequireDependenciesBlockParserPlugin.js
lib/dependencies/CommonJsPlugin.js
lib/dependencies/CommonJsRequireDependencyParserPlugin.js
lib/dependencies/HarmonyDetectionParserPlugin.js
lib/dependencies/HarmonyExportDependencyParserPlugin.js
lib/dependencies/HarmonyImportDependencyParserPlugin.js
lib/dependencies/ImportParserPlugin.js
lib/dependencies/RequireContextDependencyParserPlugin.js
lib/dependencies/RequireEnsureDependenciesBlockParserPlugin.js
lib/dependencies/RequireEnsurePlugin.js
lib/dependencies/RequireIncludeDependencyParserPlugin.js
lib/dependencies/RequireIncludePlugin.js
lib/dependencies/RequireResolveDependencyParserPlugin.js
lib/dependencies/SystemPlugin.js
lib/node/NodeSourcePlugin.js
lib/optimize/ModuleConcatenationPlugin.js

refactoring
no
n/a
**Summary**
Replace deprecated `Tapable#plugin` calls by `Hook#tap` calls.
After this PR, almost all `plugin` calls would be replaced! 🎉
no

Use Parser#hooks instead of Tapable#plugin

---

lib/NormalModuleFactory.js
test/configCases/loaders/generate-ident/index.js
test/configCases/loaders/generate-ident/webpack.config.js

I came across a bug when chaining multiple (more than 2) pitching loaders. It appears that the loader `ident` property specified in the remaining request string was not being copied from one loader to the next, so any non-serializable loader options were lost along the way.
bugfix
Yes
N/A
**Summary**
This bug occurs when a remaining request containing non-serializable options is passed through multiple pitching loaders before arriving at the final loader. When the final loader runs, any non-serializable options have been lost.
Example:
webpack.config.js:
```javascript
entry: `./index.js`,
module: {
rules: [
{
include: …
```

Maintain ident when chaining pitching loaders

---

test/Chunk.unittest.js
test/ModuleReason.unittest.js

refactoring
no
n/a
**Summary**
- `Chunk.unittest.js` was using `Chunk#parents`. Use `Chunk#setParents()` instead.
- `ModuleReason.unittest.js` was testing a deprecated API
no

Don't use deprecate APIs in unit tests

---

lib/TemplatedPathPlugin.js
schemas/webpackOptionsSchema.json
test/Validation.test.js
test/configCases/output/function/a.js
test/configCases/output/function/b.js
test/configCases/output/function/test.config.js
test/configCases/output/function/webpack.config.js
test/configCases/output/string/a.js
test/configCases/output/string/test.config.js
test/configCases/output/string/webpack.config.js

feature
Yes, a config test for when `output.filename` is a string and when it's a function.
https://github.com/webpack/webpack.js.org/pull/1751
**Summary**
Any config property that accepts a templated string (e.g. '[name].js')
can now accept a function that returns a templated string.
```
{
output: {
filename: () => '[name].js'
}
}
```
Closes #6098 
no

support functions for templated string config properties

---

lib/ContextModuleFactory.js
lib/NormalModuleFactory.js
test/statsCases/resolve-plugin-context/ResolvePackageFromRootPlugin.js

refactoring
no
n/a
**Summary**
This PR addresses some deprecations of `enhanced-resolve`. Thus the tests are less verbose.
- First argument of `Resolver#doResolve` is now a Hook
- Fourth argument of `Resolver#resolve` is now `resolveContext`. `callback` is the fifth.

Do not use deprecated features of enhanced-resolve

---

bin/webpack.js

bugfix
No. It's hard to write test and maybe it is not necessary.
**Summary**
1. According to Node.js document, it is not correct to write something like
```
console.log('hello, world');
process.exit()
```
https://nodejs.org/dist/latest-v9.x/docs/api/process.html#process_process_exit_code
> Rather than calling process.exit() directly, the code should set the process.exitCode and allow the process to exit naturally by avoiding scheduling any additional work for the event loop:
2. There is an issue https://github.com/webpack-contrib/sass-loader/issues/523 fixed by this pull request.
The issue is that Node.js doesn't exit itself after the `process.exit(1)` in line 367 of `webpack.js`.
Some callbacks of …

Fix webpack hanging under certain circumstance, use process.exitCode instead of process.exit in compilerCallback

---

lib/Compiler.js
lib/Watching.js
test/Compiler.test.js

refactoring
no
n/a
**Summary**
`Compiler` and `Watching` were defined in the same file. Move `Watching` to its own file so it uses the same _file architecture_ as `MultiCompiler`.
Kinda. I removed `Compiler.Watching` binding.

Move Watching to its own file

---

hot/signal.js

It fixes `bluebird` warning _"a promise was created in a handler but was not returned from it"_ 
No.
N/A
**Summary**
This PR fixes #6206, which properly details the issue.
No.
N/A

Fix bluebird warning in hot/signal

---

lib/Parser.js
test/Parser.unittest.js
test/cases/parsing/class/index.js
test/cases/parsing/class/module.js
test/cases/parsing/pattern-in-for/index.js
test/cases/parsing/pattern-in-for/module.js

refactoring, perf
no
n/a
**Summary**
Replace dynamic calls to `walk*` and `prewalk*` by static calls. Here below is the time spent by webpack building itself, prior and after the change:
Before:
```
❯ time node build_webpack.js
node build_webpack.js  7.75s user 0.54s system 115% cpu 7.189 total
```
After:
```
❯ time node build_webpack.js
node build_webpack.js  7.04s user 0.54s system 115% cpu 6.587 total
```
I did 10 runs before and 10 after. I took the median time. The best time before this change was never faster than the worst.
no

Make walk/prewalk calls static

---

lib/debug/ProfilingPlugin.js
package.json
yarn.lock

Add the ability to dump a profile from the profiling plugin.
For now this dumps to events.log but this is very much only a spike

Initial spike for dumping a profile

---

lib/JsonpMainTemplatePlugin.js
lib/WebpackOptionsDefaulter.js
schemas/webpackOptionsSchema.json

This PR introduces a new output option `jsonpScriptType`, which allows us to customize the `type` attribute of the script tag the webpack runtime adds to the DOM. 
With this PR, we can add `outputOptions : { jsonpScriptType : 'module' }` to have the runtime load async chunks using `<script type="module" src="myAsyncChunk.js" />`. The default option is `text/javascript`, so this is fully backwards compatible.
I couldn't find any tests for `JsonpMainTemplatePlugin.js`, any guidance on where/how to add integration tests for this particular feature would be helpful and I'll do the same.
Docs PR - https://github.com/webpack/webpack.js.org/pull/1770
**Summary** …

add support for new output option jsonpScriptType

---

lib/Chunk.js
lib/MainTemplate.js
test/statsCases/commons-chunk-min-size-0/expected.txt
test/statsCases/commons-plugin-issue-4980/expected.txt
test/statsCases/named-chunks-plugin/expected.txt

PR for #6239 
- updated the `getChunkMaps` of `Chunk `to include only non-initial (previous was non-runtime) chunk.
- update `MainTemplate` to only generate `require-enusure` method if there are non initial chunks. This is checked using `getChunkMaps`
WIP
If other plugins use the `getChunkMaps` method it could break things

WIP: Fix: require-ensure should not include initial chunks

---

lib/debug/ProfilingPlugin.js
package.json
yarn.lock

Using the v8 profiler + user timing api + a sprinkling of chrome dev tools specific trace events (thx @paulirish) we can understand the overhead of each plugin in context with the sampling CPU profiler.
This new profiling mode 🔓  unlocks the ability for both webpack core team + plugin authors to easily profile their code from within a normal webpack build flow 🐐 
---- details -----
This required a minor change to v8-profiler to use high res timestamps so that we could be aligned with the usertiming timestamps
https://github.com/samccone/v8-profiler/commit/55b9bd1578d6851d2becc969e3b3bf745b6ea45f#diff-89f966fa209341af28fef997db40999eL82
Another change was also made to the trace lib to enable us to buffer up multiple events and then manually flush the events at the end to ensure that we did …

🐌 Add combined CPU profile + user timing api to profiling plugin 🐙🌛

---

lib/debug/ProfilingPlugin.js
package.json
yarn.lock

This make the profiling plugin node 8.x+ only, but drops a native
dependency which is a win.

Remove native module dep for profiling plugin.

---

lib/debug/ProfilingPlugin.js

Instead do not record the CPU profile but still record the usertiming.
This provides a nice fallback to users instead of a runtime error :( 🕺

When a user is already using --inspect and we are unable to create a session do not fail

---

lib/ConstPlugin.js
lib/Parser.js
lib/UseStrictPlugin.js
lib/dependencies/HarmonyDetectionParserPlugin.js
test/configCases/parsing/issue-4857/index.js
test/configCases/parsing/issue-4857/webpack.config.js

bugfix
yes
n/a
**Summary**
Webpack does not transpile unreachable branches leaving `import` expressions
in the code. This PR modifies `ConstPlugin` to remove the unreachable branch.
Before:
```js
if (true) { 1 } else { import("a") }
if (false) { import("a") } else { 1 }
true ? 1 : import("a");
false ? import("a") : 1;
```
After:
```js
if (true) { 1 } else {}
if (false) {} else { 1 }
true ? 1 : null;
false ? null : 1;
```
no
Fixes #4857.
Fixes #5663.

Eliminate unreachable branches

---

lib/util/SortableSet.js

refactor
no
n/a
**Summary**
`SortableSet` can reuse its `Map` instances to reduce its memory consumption.
no

Reduce SortableSet memory consumption

---

lib/Parser.js

bugfix
no
n/a
**Summary**
Prior this change, the `VariableDeclaration` nodes were not properly walked. The `kind` property was read on the `VariableDeclarator` instead of the parent node.
Sorry for the diff but git decided to go this way.
no

Fix VariableDeclaration visitors

---

lib/debug/ProfilingPlugin.js
test/ProfilingPlugin.test.js

* Add configurable option for where the log file is written to.
* Test basic booting of the plugin
* Test profiler adapter to make sure it falls back correctly when we have no inspect module or are unable to start an inspect session.

Add test coverage for profiling plugin.

---

lib/debug/ProfilingPlugin.js

Make sure to pass the custom dump path to the tracer when a user passes a custom outPath.

Convert from using null => undefined in plugin.

---

lib/Parser.js
lib/dependencies/HarmonyModulesPlugin.js
lib/dependencies/HarmonyTopLevelThisParserPlugin.js
test/configCases/parsing/harmony-this/abc.js
test/configCases/parsing/harmony-this/index.js

bugfix
yes
n/a
**Summary**
Rewrite `this` to `undefined` in Harmony modules to be [spec-compliant](https://tc39.github.io/ecma262/#sec-module-environment-records-getthisbinding).
> **8.1.1.5.4 `GetThisBinding()`**
> 1. Return `undefined`.
```js
// in
console.log(this, this.exports);
export default this;
// out
console.log(undefined, undefined.exports);
export default undefined;
```
Fixes #5074 
Yes if a module was relying on this broken behavior.

Rewrite top level `this` to `undefined` in Harmony modules

---

examples/dll-app-and-vendor/0-vendor/README.md
examples/dll-app-and-vendor/0-vendor/template.md
lib/NoModeWarning.js
test/statsCases/no-emit-on-errors-plugin-with-child-error/expected.txt

So hours later I'm no closer to figuring out why ts-loader is hanging with webpack 4 alpha 4 post `after-compile`. :sob:
But I found a typo!  Small victories :smile:
Fixes typo.
No - but I don't think there's a test that covers the typo.
Really kinda doubt it.
Wish `ts-loader` worked with webpack 4.  Huh.  Bygones

Fix typo in NoModeWarning.js

---

lib/dependencies/ImportParserPlugin.js
lib/dependencies/SystemPlugin.js
lib/node/NodeMainTemplatePlugin.js
test/Parser.unittest.js
test/browsertest/lib/index.web.js
test/cases/chunks/import-context/index.js
test/cases/chunks/import/index.js
test/cases/parsing/typeof/index.js
test/configCases/parsing/system.import/index.js
test/configCases/parsing/system.import/module.js
test/configCases/parsing/system.import/warnings.js
test/configCases/parsing/system.import/webpack.config.js
test/configCases/target/node-dynamic-import/index.js
test/hotCases/chunks/accept-system-import/index.js
test/hotCases/chunks/dynamic-system-import/index.js
test/hotCases/chunks/system-import/index.js
test/hotCases/runtime/dispose-removed-chunk/module.js

refactor
yes
TODO since the parser options are updated.
**Summary**
`System.import` is deprecated since version [2.1.0-beta.28](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.28). ~~This PR disables `System.import` by default. Previously its support was opt-in. In order to enable it, the parser option `system` must be enabled:~~
This PR introduce a new warning if `System.import()` is used. The plugin can be toggled using a `parser` option:
```js
module: {
rules: [
{
test: /\.js$/,
parser: {
system: true // no warning
}
}
],
}
```
Possible `system` values:
- `default`: Consider `System.import()` as `import()`. Emit a warning if …

Disable System.import parser plugin by default

---

lib/Parser.js
package.json
yarn.lock

bugfix
no
n/a
**Summary**
Before this PR, webpack was mainly using `acorn@4` because `acorn-dynamic-import` was pulling its own version. This PR forces the resolution of v5. However, after updating `acorn` some tests were failing. The `Parser` had to be updated.
no

Use acorn v5

---

lib/debug/ProfilingPlugin.js
lib/webpack.js
package.json
test/ProfilingPlugin.unittest.js
test/configCases/plugins/profiling-plugin/index.js
test/configCases/plugins/profiling-plugin/webpack.config.js
yarn.lock

This PR is the culmination of a few weeks of work
https://github.com/webpack/webpack/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Asamccone
It adds the ability for any webpack 4 build to dump a profile that can be viewed in chrome dev tools.
It includes a high level user timing recording that annotate each plugin as well as a CPU profile (when > node 8 and the user is not using --inspect)
This makes it easy for end users to identify what plugins are in their critical path as well as helping to identify what is actually taking up the majority of the CPU time.

Add profiling plugin to webpack

---

lib/JavascriptModulesPlugin.js
lib/NormalModuleFactory.js
lib/Parser.js
lib/optimize/ConcatenatedModule.js

refactoring
no
n/a
**Summary**
The `Parser` was not consistently handling the source type it was working on. If the code is parsed as a script (likely because it is using `with` and triggered a parse error), `evaluate` calls were parsed as a `module`.
No

Refactor how source type is handled by the parser

---

test/statsCases/no-emit-on-errors-plugin-with-child-error/TestChildCompilationFailurePlugin.js

refactoring
no
n/a
**Summary**
Don't use `Tapable#apply`.
no

Remove deprecated apply call

---

lib/BannerPlugin.js
lib/Chunk.js
lib/FlagInitialModulesAsUsedPlugin.js
lib/LibManifestPlugin.js
lib/Stats.js
lib/TemplatedPathPlugin.js
lib/node/ReadFileCompileWasmMainTemplatePlugin.js
lib/optimize/AggressiveMergingPlugin.js
lib/optimize/MergeDuplicateChunksPlugin.js
lib/optimize/OccurrenceOrderPlugin.js
lib/optimize/SplitChunksPlugin.js
lib/performance/SizeLimitsPlugin.js
lib/wasm/WasmModuleTemplatePlugin.js
lib/web/FetchCompileWasmMainTemplatePlugin.js
test/Chunk.unittest.js
test/statsCases/async-commons-chunk-auto/expected.txt
test/statsCases/limit-chunk-count-plugin/expected.txt
test/statsCases/split-chunks/expected.txt

bugfix
no and I feel bad about this
N/A
**Summary**
split Chunk.isInitial into isOnlyInitial and canBeInitial
remove includeInitial argument of getChunk(Module)Maps
yes

split Chunk.isInitial into isOnlyInitial and canBeInitial

---

lib/Compiler.js
lib/EvalSourceMapDevToolModuleTemplatePlugin.js
lib/NormalModule.js
lib/SourceMapDevToolPlugin.js
lib/optimize/ConcatenatedModule.js

refactoring
no
n/a
**Summary**
`new Buffer` is deprecated and can be replaced by `Buffer.from` since webpack does not support node v4.
no

Use Buffer.from instead of new Buffer

---

lib/Chunk.js
lib/Compilation.js
lib/HotModuleReplacementPlugin.js
lib/LibManifestPlugin.js
lib/Module.js
lib/ModuleFilenameHelpers.js
lib/Stats.js
lib/optimize/OccurrenceOrderPlugin.js
test/statsCases/named-chunks-plugin-async/webpack.config.js

refactoring
no
TODO
**Summary**
`forEach*` and `map*` methods are not needed and add complexity to webpack. Since these modules could be replaced by `Array.from()`, there are safe to deprecate.
no

Deprecate forEach* and map* methods

---

lib/CachePlugin.js
lib/Compiler.js
lib/ContextModule.js
lib/NormalModule.js
lib/WatchIgnorePlugin.js
lib/node/NodeWatchFileSystem.js
lib/util/objectToMap.js
test/NodeWatchFileSystem.unittest.js
test/NormalModule.unittest.js
test/objectToMap.unittest.js

refactoring
modified existing unit tests
n/a
**Summary**
This change satisfies https://github.com/webpack/webpack/issues/6234 which desires to change the timestamp caches from plain objects to the ES6 Map type to avoid deopts, since v8 expects things to be added to Maps but objects are only fast if properties aren't added dynamically after initial assignment.
I think yes if anything is downstream is using `compiler.fileTimestamps` or `compiler.contextTimestamps`.

perf: refactor various timestamp caches into ES6 Maps

---

lib/Chunk.js
lib/Compilation.js
lib/Compiler.js
lib/ContextModule.js
lib/Module.js
lib/ModuleReason.js
lib/util/StackedSetMap.js

refactoring
no
TODO
**Summary**
Remove APIs that were deprecated in v3:
- `Chunk.modules`
- `Module.chunks`
- `ModuleReason.chunks`
- `Compiler.parser`
I added a comment above the deprecated APIs in v4 to be easily identified when v5 development will start.
yes

Remove v3 deprecated APIs

---

lib/ChunkTemplate.js
lib/JavascriptModulesPlugin.js
lib/MainTemplate.js
lib/WebAssemblyModulesPlugin.js

refactor
existing tests
N/A
**Summary**
make render manifest extensible
move JS and WASM specific template stuff into plugins
no
This will be useful for adding custom module types or the extract-text-webpack-plugin
cc @michael-ciniawsky

make render manifest extensible

---

lib/Parser.js
test/configCases/parsing/harmony-this/abc.js
test/configCases/parsing/harmony-this/index.js

bugfix
yes
n/a
**Summary**
Due to a scope issue, some `this` statement were wrongly erased.
no
This change also paves the road to class properties.
Fixes #6379

Exit top level scope when traversing Class nodes

---

lib/optimize/ConcatenatedModule.js
test/cases/scope-hoisting/issue-6407/import-one.js
test/cases/scope-hoisting/issue-6407/import-two.js
test/cases/scope-hoisting/issue-6407/index.js

bugfix
yes
N/A
**Summary**
When importing multiple files with default exports, arrays with empty values and functions with the same name, the ConcatenatedModule will throw an error.
See issue #6407 for details.
Fixes #6407, #5415
Ref https://github.com/angular/angular/issues/21809
No

fix(ConcatenatedModule): don't throw on arrays with empty values

---

lib/debug/ProfilingPlugin.js

This was forcing the timestamp of the last trace to be the last event
in the JSON trace, and thus breaking the CPU profile.
Instead manually exclude this plugin from being traced to avoid this
issue.
--
reported here
https://twitter.com/probablyup/status/957436506263744513

Manually exclude internal tap of plugin.

---

lib/debug/ProfilingPlugin.js
test/configCases/plugins/profiling-plugin/index.js
test/configCases/plugins/profiling-plugin/test.json

Bugfix
Yes
N/A
**Summary**
Added check for the "hooks" property on instances passed into the `interceptAllHooksFor` function to avoid a TypeError thrown importing JSON files when using the ProfilePlugin. 
Rather than doing the check in the previous function on the stack, I have just wrapped the body of `interceptAllHooksFor` with an `if` statement as it is much simpler and a bit cleaner because it only requires one check on the passed in `instance` variable. However if the extra function call being pushed on to the stack is an issue, I can update this PR to remove that `if` statement and include the extra checks in the calling function. 
See …

fixed error with importing JSON with ProfilingPlugin

---

package.json
yarn.lock

- updates to `ajv@6.1.0`
- updates to `ajv-keywords@3.1.0` (required for _better_ validation in webpack/webpack-cli#240)
dependency version bump (`ajv` and `ajv-keywords`)
No.
N/A
**Summary**
webpack/webpack-cli#240 adds some basic configuration type validation using `webpack/validateSchema` (`ajv` powered). 
It seems the "cleanest" way to validate `Promise`-type configurations, would be to use `ajv-keyword`'s `"instanceof": "Promise"`, this was only added to the `3.x` release which has a dependency on `ajv@6`.
Current tests (validations) are still passing with this update – `ajv`'s changelog from `5.2-6` doesn't suggest any breaking changes based on …

update ajv + ajv-keywords

---

lib/ContextModule.js
lib/DelegatedModule.js
lib/DllModule.js
lib/ExternalModule.js
lib/Module.js
lib/MultiModule.js
lib/NormalModule.js
lib/RawModule.js
lib/optimize/ConcatenatedModule.js

refactoring
no
n/a
**Summary**
When extending `Module`, `context` is now defined as a constructor argument.
no

Pass 'context' as constructor argument

---

lib/Stats.js
schemas/WebpackOptions.json
test/Stats.unittest.js
test/statsCases/simple-more-info/webpack.config.js

This PR adds a feature to include the output path in the Stats object.
Added a test on the `toJson` function of `Stats` to confirm the output is expected and includes the newly added `outputPath` field.
https://github.com/webpack/webpack.js.org/pull/1807
**Summary**
Open issue: https://github.com/webpack/webpack/issues/6373
Having the output path in the Stats object is particularly useful when the stats file is emitted and you'd like to do analysis of the emitted files given the stats file.
For example, when using a tool like [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer), it currently requires a second option to pass the …

Expose output path in Stats object

---

lib/EnvironmentPlugin.js
lib/node/NodeTargetPlugin.js

Future-proofing / being a good OSS citizen.
No, but Webpack doesn’t seem to test current verions of Node in CI right now anyway.
Once Node 9 or above is in there, this is going to be tested automatically.
N/A
**Summary**
`process.binding()` is not a public API, and should
not be used.
Luckily, Node recently introduced an API that does
exactly what Webpack needs:
https://nodejs.org/api/modules.html#modules_module_builtinmodules
So use that instead and keep the old path as a fallback.
No.
Nope. :)

Avoid relying on Node’s internals

---

lib/Compiler.js
lib/Watching.js

It makes the `done` compiler hook async.
Not yet, not sure what to add.
**Summary**
To be able to track our build time, I want my CI to send timings via HTTP to a server. Today this does not seem possible, as the only hook where I can get these timings is the `done` hook, but it is synchronous, and thus making async HTTP requests in it is not possible.
Not sure yet.

Transform done hook into async

---

lib/optimize/SplitChunksPlugin.js
test/statsCases/split-chunks/expected.txt
test/statsCases/split-chunks/webpack.config.js

bugfix
yes
n/a
**Summary**
If a filename is longer than 255 characters an `ENAMETOOLONG` error is raised. This PR truncates the chunk name generated by `SplitChunksPlugin` to 200 characters and happens a unique identifier after to avoid conflicts.
no
This is more a patch than a proper fix. Ideally webpack should never generate a long filename. However, changing the way filenames are handled is a lot more complex.
Fixes #6426

Truncate generated chunk name if too long

---

lib/WebpackOptionsApply.js
lib/WebpackOptionsDefaulter.js
lib/optimize/RuntimeChunkPlugin.js
schemas/WebpackOptions.json
test/statsCases/runtime-chunk-single/e1.js
test/statsCases/runtime-chunk-single/e2.js
test/statsCases/runtime-chunk-single/expected.txt
test/statsCases/runtime-chunk-single/webpack.config.js
test/statsCases/runtime-chunk/e1.js
test/statsCases/runtime-chunk/e2.js
test/statsCases/runtime-chunk/expected.txt
test/statsCases/runtime-chunk/webpack.config.js

Add config option `optimization.runtimeChunk: 'single'` to generate a single runtime chunk for all entrypoints instead of each entrypoint getting their own runtime.
Basic tests for the existence of runtime files, nothing that tests that the contents of the runtime file are generated correctly.
**Summary**
My company's webpack setup involves including multiple entrypoint files on a page, so adding a separate runtime chunk for each entrypoint results in too many parallel loading chunks.
See @sokra's comment in the alpha.5 issue: https://github.com/webpack/webpack/issues/6357#issuecomment-360435877
No, just a new …

Add "single" option to RuntimeChunkPlugin

---

lib/WebpackOptionsDefaulter.js

This makes webpack-serve happier.
Bugfox
None needed? 
N/A - yet.
**Summary**
So webpack-serve can append hot scripts and dev-server scripts without a user needing to create a config. 
No

Wrap default entry property in array

---

lib/EvalSourceMapDevToolModuleTemplatePlugin.js
test/configCases/source-map/exclude-modules-source-map/index.js
test/configCases/source-map/exclude-modules-source-map/test1.js
test/configCases/source-map/exclude-modules-source-map/test2.js
test/configCases/source-map/exclude-modules-source-map/webpack.config.js

Feature. 
yes
It's weird, the documentation contains this, see https://webpack.js.org/plugins/eval-source-map-dev-tool-plugin/, but when I run the new unit test I added, it fails... which indicates that maybe the docs were mistakenly added??? Unless I am missing something.
**Summary**
Adding ability to filter which modules get sourcemapped when using EvalSourceMapDevToolPlugin.
See: https://github.com/webpack/webpack/issues/6450
This is useful to filter out stuff you don't care about or stuff that's very large and screws up with devtools.
no

EvalSourceMapDevToolPlugin: add ability to filter modules

---

lib/WebpackOptionsDefaulter.js

bugfix
n/a
**Summary**
By default we have decided to set mode: production, however we forgot to set nodeEnv to "production". This makes libraries like React and Vue OOB using no mode, look more bloated then they are.
No

Set nodeEnv to default to "production"

---

lib/WebpackOptionsApply.js

Add built-in `original-fs` module to externals for Electron build targets
no
**Summary**
Fixes #6504 
no
I did sort the deps alphabetically in addition to adding `original-fs`

Bugfix #6504: add `original-fs` to externals for electron targets

---

package.json
yarn.lock

Fixes the parsing of the start section in WASM
**Summary**
Fixes the parsing of the start section in WASM

chore: bump webassembly-interpreter

---

lib/optimize/ModuleConcatenationPlugin.js

bugfix / performance improvement
No
N/A
**Summary**
In our large Angular 5 project (~3400 modules) ModuleConcatenationPlugin is now taking 60% of the build time in webpack 4.
Webpack is spending 869499ms in 'chunk modules optimization' within ModuleConcatenationPlugin.
Most of this time is consumed in 2 nested for-of loops in the ModuleConcatenationPlugin. By changing the for-of loops to standard for loops we have reduced the time we spend in ModuleConcatenationPlugin from 14 minutes 29 seconds to 2 minutes 35 seconds.
No
Node: 8.9.3
Webpack: 4.0.1 and 4.0.0
Windows 10
During our prod …

improve performance of ModuleConcatenationPlugin for loop

---

lib/WebpackOptionsDefaulter.js

fixes #6614 
sets default to allow for source maps w/ mode: production
no
no
**Summary**
See #6614 
no

defaults: set source map option for UglifyJs to true if SourceMapDevToolPlugin exists

---

lib/WebpackOptionsValidationError.js

bugfix
I've edited existing test.
N/A
**Summary**
Version in message was hardcoded, I replaced it with the one present in `package.json`.
Fixes #6605 
No
Disable prettier on those lines because introduce like break around variable. See:
https://github.com/prettier/prettier/issues/1893
https://github.com/prettier/prettier/issues/3368

Fix version in configuration error messages

---

lib/Stats.js

refactor
nope. Made this change on Github, hoping no tests fail 🙂 
**Summary**
This format looks better, at least with Norwegian locale.
```js
new Date().toLocaleDateString("nb-NO");
// "5.3.2018"
new Date().toLocaleDateString("nb-NO", { day: "2-digit", month: "2-digit", year: "numeric" });
// "05.03.2018"
```
Without this change: 
Shouldn't 🤞 

Use 2-digit format for day and month in "built at" output

---

lib/debug/ProfilingPlugin.js

bugfix
No reliable way to test this, since this depends on the order the OS flushes data to the FS. I've tested in place where this race condition was being triggered and it works. Actually, this was causing flakiness of the profiling-plugin ConfigCases test, so that should be fixed.
N/A
**Summary**
Fixes a race-condition where `events.json` might not yet be available immediately after compilation.
No.

fix(ProfilingPlugin): complete after the writeStream had finished flushing the data to the filesystem

---

open-bot.yaml

Readability change for @webpack-bot errors logs.
No
**Summary**
@webpack-bot is posting large tests errors logs in PRs creating large webpages with long scrolls, this make it harder to have meaningful conversations in PR.
This PR encapsulates those logs in a `<details>` tag (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) which is support by GitHub markdown.
With this change large logs will be collapsed by default unless you click on it.
Before
After
Collapsed by default
After clicking on `Details`

bot: Encapsulate output logs in details tag

---

lib/Stats.js
schemas/WebpackOptions.json

feature request
no
n/a
**Summary**
Addresses #6726. Now `exclude` and `excludeModules` can accept boolean values. Eg. use `excludeModules: false` to disable filtering.
no

fix: make excludeModules accept booleans

---

lib/Compiler.js
lib/ConcurrentCompilationError.js
lib/MultiCompiler.js
lib/MultiWatching.js
lib/Watching.js
test/Compiler.test.js
test/MultiCompiler.test.js

improve DX by explicit error messages
yes
N/A
**Summary**
If webpack somehow starts in a synchronous manner like:
``` js
compiler.run();
compiler.run();
// or
compiler.run()
compiler.watch()
// or
const compiler = webpack({}, () => {})
compiler.run()
```
it will produce wierd and syntactically wrong code.
This PR add some flag to check if compiler in running state and prevent any starts until it done.
no
Related to #6667

Prevent webpack from running twice at a time

---

open-bot.yaml

Fix for bug introduce in https://github.com/webpack/webpack/pull/6713
No, but tested that this formatting actually works in https://github.com/montogeek/webpack-dev-middleware-bug/pull/1#issuecomment-373100450
**Summary**
It looks like Markdown code formatting inside `<details>` tag needs an empty line above it to correctly format code.
Before this change
After this change
No

bot: Fix Markdown format for output logs

---

lib/dependencies/AMDDefineDependencyParserPlugin.js
lib/dependencies/AMDRequireDependenciesBlockParserPlugin.js

**What kind of change does this PR introduce?** 
Structural (non-functional) changes to the AMD parser modules that restore extensibility which was lost in the v4 upgrade
No.  Not needed.  No functional changes.
N/A
**Summary**
Prior to V4, code reuse in the AMD parser modules could be achieved through the use of the `call require:amd:array`, `call require:amd:item`, `call define:amd:array` and `call define:amd:item` plugin events.  These events were removed in V4, with no alternative to facilitate reuse of parser code by plugins.  This PR restores extensibility through the use of class inheritance (a cleaner approach for the use case).  The extensibility is needed by …

Make AMD parser modules extensible again

---

lib/web/JsonpMainTemplatePlugin.js
test/statsCases/import-context-filter/expected.txt
test/statsCases/module-deduplication-named/expected.txt

Converts miliseconds provided bia outputOptions configuration option into seconds for web script attribute `timeout`.
No
**Summary**
Fixes #5964
No

fix(bug) #5964 convert MS into S for scripts timeout attr

---

lib/SourceMapDevToolPlugin.js
lib/debug/ProfilingPlugin.js
test/configCases/source-map/source-map-with-profiling-plugin/index.js
test/configCases/source-map/source-map-with-profiling-plugin/test.js
test/configCases/source-map/source-map-with-profiling-plugin/webpack.config.js

bugfix
yes, for `configCases`
N/A
**Summary**
Fixes #6779
no

fix: Chunks is not iterable when using source maps with ProfilingPlugin

---

package.json
yarn.lock

bugfix
no
n/a
**Summary**
When running unit tests there is a deprecation notice.
This PR bumps uglify plugin to remove this warning.
no

Bump UglifyJSPlugin to remove Tapable warning

---

lib/webpack.js

refactoring
no
n/a
**Summary**
~~`Reflect.defineProperty` is more meaningful than `Object.defineProperty`. Internally `Reflect.dP` performs less checks than `Object.dP`.~~
Use `Object.defineProperty`
no

Use 'Reflect.defineProperty' instead of 'Object.defineProperty'

---

lib/WebpackOptionsDefaulter.js
test/configCases/source-map/object-as-output-library/index.js
test/configCases/source-map/object-as-output-library/webpack.config.js

Fixes https://github.com/webpack/webpack/issues/6843
Yes
N/A
**Summary**
Fixes bug when using an Object as config.output.library with devTool: 'source-map'
No
I am not 100% certain that my approach to setting devtoolNamespace to the output.library.root is correct, but I don't know enough about devtoolNamespace to have a better idea of what to use. Note that in the docs, it also specifies that the Object should be allowed to have Array values, which this PR does not support. That would have to be added later.

Add handling for devtool source-map with library specified as Object

---

README.md

docs
n/a
It's README.md
**Summary**
I was confused because of this, but @TheLarkInn pointed me to the [branding guidelines](https://webpack.js.org/branding/).
No
I like turtles

fix capitalization of project name in README.md

---

lib/OptionsDefaulter.js

code clean up
N/A
N/A
**Summary**
As part of https://github.com/webpack/webpack/pull/6862 I'm fixing issues TypeScript has found 
No

Remove extraneous argument from setOptions call sites in OptionsDefaulter

---

lib/Dependency.js

Related to https://github.com/webpack/webpack/pull/6862
This change is being proposed based on [this comment](https://github.com/webpack/webpack/pull/6869#discussion_r177343671) that says Webpack prefers initializing possible members in classes

Initialize loc member in Dependency

---

lib/NoModeWarning.js
test/statsCases/no-emit-on-errors-plugin-with-child-error/expected.txt

Improvement to the warning shown in terminal when no mode option was set.
No.
**Summary**
The message that we are showing to users when the `mode` option is not set is a little confusing. First of all, we are not communicating that we are defaulting to `production`, something which actually caused confusion while writing docs when contributors wanted to come up with what was the default using this message as source of truth: https://github.com/webpack/webpack.js.org/pull/1940
No
I didn't add any test because I don't see the specific value of it for this specific case, but if you think …

fix: better no mode warning message

---

lib/JavascriptModulesPlugin.js

refactor
no
no
**Summary**
As part of https://github.com/webpack/webpack/pull/6862 I'm proposing fixes that TypeScript have found 
no

Remove extra argument passed to JavascriptGenerator constructor

---

lib/Compilation.js

Related to https://github.com/webpack/webpack/pull/6862
@sokra you mentioned this is broken but I'm not sure removing the argument is the right change

Initialize compilationDependencies in Compilation as undefined

---

lib/performance/SizeLimitsPlugin.js

refactori
no
n/a
**Summary**
As part of https://github.com/webpack/webpack/pull/6862 I'm fixing issues TypeScript has found 

Remove extra argument passed to getEntrypointSize in SizeLimitsPlugin

---

lib/Stats.js

refactor
n/a
**Summary**
As part of https://github.com/webpack/webpack/pull/6862 this change adds initializers to Stats class 

Initialize start and end time as undefined in Stats

---

lib/Compilation.js
lib/ContextModule.js
lib/HotUpdateChunkTemplate.js
lib/Module.js
lib/NormalModule.js

features and bugfixes
no, existing tests
n/a
**Summary**
incremental build was broken for mini-css-extract-plugin, because modules cannot be updated.
adding `Module.updateCacheModule` allows this.
HMR chunk creation crashes because it misses the filter for `Module.source`
no

fixes for mini-css-extract-plugin

---

lib/Compilation.js

refactor
no
**Summary**
`this.fileTimestamps && this.contextTimestamps` is always falsy in `Compilation`. I looked into Tapable too and those don't exist there either. I see `fileTimestamps` in `Compiler` class. Is that related?
Related to https://github.com/webpack/webpack/pull/6862

Initialize fileTimestamps and contextTimestamps in Compilation

---

lib/Compiler.js
lib/JavascriptGenerator.js
lib/Parser.js
lib/ProgressPlugin.js
lib/Template.js
lib/WebpackOptionsValidationError.js
lib/dependencies/AMDDefineDependencyParserPlugin.js
lib/dependencies/AMDRequireDependenciesBlockParserPlugin.js
test/Validation.test.js
test/browsertest/build.js
test/cases/parsing/extract-require/index.js
test/cases/parsing/hot-api/index.js

refactoring
no
n/a
**Summary**
While searching through the codebase for `...` I hit a lot of comments and messages containing these characters. I think using an ellipsis instead is more readable.
Previously:
```
- configuration.plugins[0] should be one of these:
object { apply, ... } | function
-> Plugin of type object or instanceof Function
Details:
```
Now:
```
- configuration.plugins[0] should be one of these:
object { apply, … } | function
-> Plugin of type object or instanceof Function
Details:
```
no, unless some code relies on error messages.

Use ellipsis instead of '...'

---

lib/ContextModule.js
lib/MultiModule.js

Performance. Cache module identifier after first call.
No
N/A
**Summary**
In some plugins we have sort modules function like this:
```js
// From SplitChunksPlugin
const sortByIdentifier = (a, b) => {
if (a.identifier() > b.identifier()) return 1;
if (a.identifier() < b.identifier()) return -1;
return 0;
};
```
Method `identifier()` can be run many times while sorting. Each call `identifier()` calculates identifier from options. We can cache it to avoid repeated calculate.
No

Save identifier module after first getting

---

lib/WebpackOptionsDefaulter.js
schemas/WebpackOptions.json

Fixes #6639 
no
**Summary**
For technically reasons chunkFilename can't be a function. This PR disabling it on the the schema level.
no

fix(bug): chunkFilename as function doesn't work

---

lib/Dependency.js
lib/dependencies/DelegatedExportsDependency.js
lib/dependencies/DependencyReference.js
lib/dependencies/HarmonyExportImportedSpecifierDependency.js
lib/dependencies/HarmonyImportDependency.js
lib/dependencies/HarmonyImportSpecifierDependency.js
lib/dependencies/RequireIncludeDependency.js
lib/dependencies/WebAssemblyImportDependency.js

refactoring
no
n/a
**Summary**
Use a class instead of an object to ensure that references share the same hidden class. This change should avoid potential deopts.
no

Use a class for dependency references

---

lib/dependencies/HarmonyExportImportedSpecifierDependency.js

refactoring
no
N/A 
**Summary**
This change make `getReference` monomorphic since `getMode` will always return an `ExportMode`. By doing this, all modes share the same shape.
no

Change internal representation of harmony export modes

---

lib/Stats.js
test/Stats.unittest.js

bugfix
yes
**Summary**
fix the error message like below.
```
[now]
ERROR in ./node_modules/ts-loader!./node_modules/tslint-loader!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue
[i want]
ERROR in ./src/app.vue
```
no
webpack emits the error message when using loader in options like below.
```js
// webpack.config.js
module: {
rules: [{
test: /\.vue$/,
use: [{
loader: 'vue-loader',
options: {
loaders: {
ts: 'ts-loader',
},
},
}]
}]
}
```

emit correct path when using loader in options

---

lib/NormalModuleFactory.js
lib/dependencies/AMDDefineDependencyParserPlugin.js
lib/dependencies/DelegatedExportsDependency.js
lib/dependencies/HarmonyExportExpressionDependency.js
lib/dependencies/HarmonyExportImportedSpecifierDependency.js
lib/dependencies/HarmonyExportSpecifierDependency.js
lib/dependencies/JsonExportsDependency.js

refactoring
no
n/a
**Summary**
`getExports` was returning 2 types of shape which could force its caller to deopt.
This also was the case for `identToLoaderRequest`
no

Use a single object shape for dependency exports

---

lib/node/NodeMainTemplateAsync.runtime.js

Refactor
No
N/A
**Summary**
Existing code is technically correct. The API has changed in Node 8 and higher to accept an option hash but kept backward compatibility. Using the new API will make TypeScript happy at #6862 and make it easier to add more options in the future. 
No
At the same time I'm trying to update DT to understand old API usages as well:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24798

Pass file name as part of options hash to vm.runInThisContext

---

lib/Stats.js
test/statsCases/tree-shaking/expected.txt

bugfix
yes
n/a
**Summary**
Change stats wording when all exports are used:
```diff
Entrypoint main = bundle.js
[0] ./a.js 13 bytes {0} [built]
[exports: a]
-    [only some exports used: a]
+    [all exports used]
```
no
Fixes #6995

Change stats wording when all exports are used

---

lib/dependencies/AMDDefineDependencyParserPlugin.js
lib/dependencies/AMDRequireDependenciesBlockParserPlugin.js

refactoring
no
N/A
**Summary**
`LocalModuleDependency` constructor arity is 3.
With this PR, the 3 arguments are always passed.
no

Force LocalModuleDependency arity to 3

---

lib/util/cachedMerge.js

refactoring
no
N/A
**Summary**
`cachedMerge` is only called with 2 two arguments. It doesn't need to recursive.
no

Simplify cachedMerge

---

lib/EvalDevToolModuleTemplatePlugin.js
lib/EvalSourceMapDevToolModuleTemplatePlugin.js

refactoring
no
N/A
**Summary**
Avoid a potential deopt on `EvalSourceMapDevToolModuleTemplatePlugin` by replacing the cache key by a `WeakMap`.
no

Avoid deopt when cache is set in EvalSourceMapDevToolModuleTemplatePlugin

---

lib/Compilation.js
lib/Compiler.js
lib/dependencies/HarmonyImportSpecifierDependency.js

refactor
no
n/a
**Summary**
As part of https://github.com/webpack/webpack/pull/6862 I'm adding class member initializers for properties that were added to class instances 

Add missing class member initializations found by TypeScript

---

lib/WebpackError.js
test/RemovedPlugins.unittest.js

Refactor
No
N/A
**Summary**
As part of https://github.com/webpack/webpack/pull/6862 I'm refactoring the base error class to initialize the `details` member so TypeScript is happy about this class 
No

Refactor WebpackError to initialize details as undefined

---

lib/optimize/ChunkModuleIdRangePlugin.js
test/statsCases/chunk-module-id-range/a.js
test/statsCases/chunk-module-id-range/b.js
test/statsCases/chunk-module-id-range/c.js
test/statsCases/chunk-module-id-range/d.js
test/statsCases/chunk-module-id-range/e.js
test/statsCases/chunk-module-id-range/expected.txt
test/statsCases/chunk-module-id-range/f.js
test/statsCases/chunk-module-id-range/main1.js
test/statsCases/chunk-module-id-range/main2.js
test/statsCases/chunk-module-id-range/webpack.config.js

bugfix
yes
N/A
**Summary**
Because of the arrow function `this` was no longer referencing the `compilation` which was a bug. Since there is no test or documentation about this plugin, I don't know to create a good test case for this. Is this plugin still relevant?
no

Use compilation instead of this in ChunkModuleIdRangePlugin

---

lib/WebpackOptionsDefaulter.js

Fixes the default value of the `output.globalObject` config and restores old behavior for `node-webkit` targets.
**Summary**
The default value of `output.globalObject` is currently set to `global` instead of `window`. This can break NW.js applications when the application window reloads.
Fixes #7043
I couldn't find any existing tests for this specific config and didn't have time learning how to add new ones.
This config option seems to be undocumented and was just briefly mentioned in the 4.0.0 changelog.
No.

Fix output.globalObject value in node-webkit

---

lib/HotModuleReplacementPlugin.js
test/hotCases/define/issue-6962/a.js
test/hotCases/define/issue-6962/index.js
test/hotCases/define/issue-6962/module.js
test/hotCases/define/issue-6962/webpack.config.js

addresses #6919
bugfix
yes
N/A
**Summary**
#6919 
Not to any external interface

hot.accept tap interceptor returns T/F based on the number of args

---

lib/WebpackOptionsDefaulter.js
test/cases/chunks/runtime/test.filter.js

bugfix
yes
N/A
**Summary**
we forgot to clone the `optimization` config in the Defaulter
no
problem found in #6565

Clone optimization config in Defaulter

---

package.json
yarn.lock

Update dependencies
N/A
N/A
**Summary**
This PR updates the TypeScript nightly dependency for blocking `import("./module")` support for commonJS module and class types. 
The updated version would be `2.9.0-dev.20180421`
No, this is only for the build step, however this was failing locally. I will use this PR as a way to report this failure upstream (so lets wait on actually merging this). 
https://github.com/Microsoft/TypeScript/issues/23588 Upstream issue I've submitted for when this PR fails.

chore(pkg): update typescript nightly to Version 2.9.0-dev.20180421

---

lib/node/ReadFileCompileWasmTemplatePlugin.js
lib/wasm/WasmMainTemplatePlugin.js
lib/wasm/WebAssemblyJavascriptGenerator.js
lib/web/FetchCompileWasmTemplatePlugin.js

feature
existing tests
N/A
**Summary**
better runtime performance when loading memory-sharing wasm modules.
no

Use compile/compileStreaming when importObject is a Promise

---

lib/Chunk.js
lib/optimize/RuntimeChunkPlugin.js
test/statsCases/runtime-chunk-integration/b.js
test/statsCases/runtime-chunk-integration/c.js
test/statsCases/runtime-chunk-integration/d.js
test/statsCases/runtime-chunk-integration/expected.txt
test/statsCases/runtime-chunk-integration/f.js
test/statsCases/runtime-chunk-integration/main1.js
test/statsCases/runtime-chunk-integration/webpack.config.js

bugfix
yes
**Summary**
fixed bug where sometimes the runtime would not be present on output
i don't think so, more likely improves compatibility with webpack 3
Hello webpack team
I found a bug where sometimes the runtime would not be present on output
I encountered it by using:
- `optimization.runtimeChunk: true`
- `webpack.optimize.MinChunkSizePlugin`
- Dinamic imports
It seems the runtime chunk would get integrated into one of the asyncChunks, and after integration i would get removed from the chunk graph, causing it's `EntryPoint.runtimeChunk` to be a chunk thats not longer on the Graph.
Why is it getting integrated? Well is small …

fix bug where sometimes the runtime would not be present on output

---

lib/optimize/ConcatenatedModule.js
test/WatchTestCases.test.js
test/watchCases/scope-hoisting/caching-inner-source/0/index.js
test/watchCases/scope-hoisting/caching-inner-source/0/inner.js
test/watchCases/scope-hoisting/caching-inner-source/0/inner1.js
test/watchCases/scope-hoisting/caching-inner-source/0/inner2.js
test/watchCases/scope-hoisting/caching-inner-source/0/module.js
test/watchCases/scope-hoisting/caching-inner-source/1/inner1.js
test/watchCases/scope-hoisting/caching-inner-source/webpack.config.js

Bugfix.
When the moduleSet for a given concatenated module changed, the source for the embedded modules would not necessarily, which lead to caching mismatch between the source and the modulesWithInfo structure.
Fixes #6168

Invalidate concatenated module on dep change

---

yarn.lock

bugfix
no
n/a
**Summary**
This PR bumps `upath` because the version 1.0.4 wasn't compatible with node 10:
```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```
Solved by version 1.0.5.
no

Bump upath to version 1.0.5

---

lib/DependenciesBlock.js
lib/GraphHelpers.js

Type Annotations
N/A
N/A
**Summary**
This PR adds Type Support for GraphHelpers via JSDoc Annotations
NO!
I thought it was strange that `DependenciesBlock` class now has the option to have a `ChunkGroup` tied to it? Should this actually fall to a subclass?

chore(types): add types to GraphHelpers

---

package.json
yarn.lock

Fixes module name decoding in custom name section
**Summary**
The Rust folks had a regression with the v4.8.0.
I added support for module name decoding in the custom name section.

Bump webassemblyjs

---

yarn.lock

security fix
no
n/a
**Summary**
There is a security issue with `deep-extend` package which is a dependency of `rc`.
Further details on https://nodesecurity.io/advisories/612
no
Fixes #7255

Update rc and deep-extend

---

test/README.md

This documentation still referenced Mocha, but tests were converted to
Jest. This is just a documentation update.

Update test readme for Jest

---

schemas/WebpackOptions.json
test/configCases/library/umd-array/index.js
test/configCases/library/umd-array/webpack.config.js
test/configCases/library/umd/webpack.config.js

bugfix
configCases
N/A
**Summary**
Closes #7176
No

fix: allow array of strings for `output.library.root`

---

lib/BannerPlugin.js
schemas/plugins/BannerPlugin.json
test/configCases/plugins/banner-plugin/index.js
test/configCases/plugins/banner-plugin/webpack.config.js

feature
yes
TODO if the feature is merged.
**Summary**
Allow banner to be specified as a function.
Exposed variables are:
- compilation's hash
- chunk object
- filename
- basename
- query
Fixes #7269
no

Allow banner to be specified as a function

---

examples/code-splitted-require.context-amd/README.md
examples/code-splitted-require.context/README.md
examples/code-splitting-harmony/README.md
examples/code-splitting-native-import-context-filter/README.md
examples/code-splitting-native-import-context/README.md
examples/code-splitting-specify-chunk-name/README.md
examples/hybrid-routing/README.md
examples/mixed/README.md
examples/require.context/README.md
examples/web-worker/README.md
lib/ContextModule.js
lib/RuntimeTemplate.js
lib/dependencies/WebpackMissingModule.js
test/ExternalModule.unittest.js
test/WebpackMissingModule.unittest.js
test/cases/parsing/issue-2641/index.js
test/cases/parsing/issue-758/index.js
test/configCases/context-exclusion/simple/index.js
test/configCases/errors/multi-entry-missing-module/index.js

bugfix/refactor
I made relevant changes to the existing tests already testing this.
N/a
**Summary**
The `Cannot find module` error message coming from `require` is not consistent across this project, and it unnecessarily doesn't match NodeJS' message. I have tested NodeJS 4, 6, 8, and 9 and all gave the message `Cannot find module 'module-name'`, while webpack (in *some* locations) gives `Cannot find module "module-name".` (with double quotes and a period). This makes it hard to recognize the missing module from the error, especially for a dependency (that doesn't know if the code is getting webpacked).
Solves #7238 
**Does this PR introduce a breaking …

Align 'Cannot find module' message with native NodeJS

---

README.md

docs change
No
No
**Summary**
This simple doc PR updates the _Support_ section of the `./README.md` to include a brief description about the reference of _webpack 1_ docs, a link to old [wiki](https://github.com/webpack/docs/wiki/contents) and _small disclaimer_  about the deprecated, unsupported _webpack 1_
This PR resolves #6390.
No
This PR content is also based on the analysis of [webpack/webpack.js.org##1823](https://github.com/webpack/webpack.js.org/issues/1823). In the issue [webpack/webpack.js.org##1823](https://github.com/webpack/webpack.js.org/issues/1823), it mentioned about:
> …

Add Brief Description & Link To Webpack 1 "Old" Wiki In README => Support Section

---

schemas/WebpackOptions.json
test/Validation.test.js

Allow to specify `serve` property in webpack configurations. This is used to configure [webpack-serve](https://github.com/webpack-contrib/webpack-serve).
Fixes #7306 
bugfix
No, adapted tests.
No, but a new config options is available
The `serve` property should be listed under https://webpack.js.org/configuration/ and documented there.

Allow serve property in webpack configuration

---

test/cases/parsing/issue-7318/index.js
test/cases/parsing/issue-7318/typeof.js

Add a test to ensure that `typeof` without semicolon does not output invalid code:
```js
typeof 1
module.exports = 2
```
I cannot reproduce the issue on webpack 3 or webpack 4.
Fix #7318 
tests
yes
no
n/a

Add a test to check typeof transformation

---

README.md

This adds a new column to display the npm install size of each npm package.
This solves the problem of not knowing how large a package is before it is installed.
Related: https://github.com/webpack-contrib/webpack-command/pull/9
**What kind of change does this PR introduce?** Add new Column "Install Size" in README.md 
**Did you add tests for your changes?** No
**Does this PR introduce a breaking change?** No
**What needs to be documented once your changes are merged?** None

Add badges to display install size

---

lib/Compiler.js
lib/DllReferencePlugin.js
lib/JsonParser.js
package.json
yarn.lock

Use [`json-parse-better-errors`](https://github.com/zkat/json-parse-better-errors) to parse JSON files. This package enhances the `SyntaxError` to provide friendlier error messages.
Fix #7297
feature
no
no
nothing

Improve JSON parse error

---

declarations.d.ts
lib/wasm/WebAssemblyGenerator.js
package.json
test/cases/wasm/imports-multiple/module.js
yarn.lock

Few wasm fixes

---

lib/SourceMapDevToolPlugin.js

`SourceMapDevToolPlugin` was mutating asset objects. This PR uses `WeakMap` to cache source map data and avoid the mutations (and de-opt).
refactoring
no
no
nothing

Use WeakMaps instead of mutating assets in SourceMapDevToolPlugin

---

lib/RecordIdsPlugin.js
test/configCases/records/stable-sort/test.js
test/configCases/records/stable-sort/webpack.config.js

Hi there,
We version-control our webpack records, and I kept seeing the `usedIds` array changing its order, especially when doing a mix of development and production builds.
This change sorts the array to keep it stable.
Feature
Yes
No
Nothing

Sort the usedIds array in records

---

lib/NormalModuleFactory.js

`NormalModuleFactory` was mutating dependency objects if the `unsafeCache` option was set. This PR uses a `WeakMap` to cache dependencies and avoid the mutation (and de-opt).
refactoring
no
no
nothing

Use a WeakMap instead of mutating objects in NMF

---

examples/dll-entry-only/README.md
examples/dll-entry-only/a.js
examples/dll-entry-only/b.js
examples/dll-entry-only/build.js
examples/dll-entry-only/cjs.js
examples/dll-entry-only/example.js
examples/dll-entry-only/template.md
examples/dll-entry-only/webpack.config.js
lib/DllPlugin.js
lib/LibManifestPlugin.js
schemas/plugins/DllPlugin.json
test/configCases/dll-plugin-entry/0-create-dll/dep.js
test/configCases/dll-plugin-entry/0-create-dll/dep2.js
test/configCases/dll-plugin-entry/0-create-dll/index.js
test/configCases/dll-plugin-entry/0-create-dll/test.config.js
test/configCases/dll-plugin-entry/0-create-dll/webpack.config.js
test/configCases/dll-plugin-entry/1-use-dll/index.js
test/configCases/dll-plugin-entry/1-use-dll/webpack.config.js
test/configCases/dll-plugin-entry/2-error-non-entry/errors.js
test/configCases/dll-plugin-entry/2-error-non-entry/index.js
test/configCases/dll-plugin-entry/2-error-non-entry/webpack.config.js

As discussed in #7333, this change introduces a new `entryOnly` flag to the `DllPlugin` options which limits the exposed modules to only those configured as entry points. This allows module concatenation and dead code removal optimizations to take place.
feature
Yes
No
`entryOnly` option in `DllPlugin`

feat: support tree shaking in DllPlugin

---

.prettierignore
package.json

enhancement
no
n/a
**Summary**
Adds `.prettierignore` to prevent IDEs plugins from autoformatting wrong files (eg. JSON files or some test related files).
no
Tested in Atom (`prettier-atom` plugin). Feedback from other IDEs is highly appreciated.

enhancement: add .prettierignore file

---

examples/README.md

docs change
No
No
**Summary**
Running `node cd examples/commonjs && node ./build.js` without `webpack-cli` installed will get hang.
The culprit is that webpack expects a stdin user input of whether to install webpack-cli or not. However, as examples/build-common uses `child_process.exec` to execute `webpack`, the user will not be prompted for any questions since the stdin is not piped and the stdout will be pass to parent process only after the child process exits. We can keep build-common simple by instructing devs to install webpack-cli before they build examples.
Also rewrite the install step using yarn since we use yarn in webpack.
**Does this PR …

docs(examples): add yarn add webpack-cli step

---

lib/web/JsonpMainTemplatePlugin.js
test/__snapshots__/StatsTestCases.test.js.snap

**Issue Reference**
fixes #7263 
Call the method `onScriptComplete` after its declaration as there should ben an error of references under Friefox 40, when it has been declared inside a conditon block, rather than the top block inside a function.
No needs.
Solve the problem under Firefox 40.
No needs.

fix: unsupported function defined inside a condition block. #7263

---

lib/optimize/ModuleConcatenationPlugin.js
test/cases/optimize/side-effects-scope-hoisting/index.js

fixes #7443
bugfix
yes
no
nothing

rewrite module reference correctly after replacing ConcatenatedModule

---

lib/ProgressPlugin.js

With this change, plugins which tap into the `afterEmit` hook can use the context function `reportProgress` to show their progress. This is useful for plugins like cdn-upload-webpack-plugin, which will be able to report its progress, e.g.
```
98% CdnUploadPlugin …: creating Azure blob container 'files'
98% CdnUploadPlugin …ting blobs under 'files/my/test/folder'
98% CdnUploadPlugin upload: found 2 blobs
98% CdnUploadPlugin …ting 2 blobs under files/my/test/folder
98% CdnUploadPlugin … (1/2) 'files/my/test/folder/bundle.js'
98% CdnUploadPlugin …(2/2) 'files/my/test/folder/index.html'
98% CdnUploadPlugin upload: uploaded 2 assets
98% CdnUploadPlugin upload: pruned 0 extraneous assets
```
https://github.com/elliottsj/cdn-upload-webpack-plugin/blob/09ffeae20345d451895234e10d07df26dcb8a04d/src/ …

Allow afterEmit plugins to use `reportProgress`

---

declarations.d.ts
lib/dependencies/WebAssemblyExportImportedDependency.js
lib/wasm/WebAssemblyGenerator.js
lib/wasm/WebAssemblyJavascriptGenerator.js
lib/wasm/WebAssemblyModulesPlugin.js
lib/wasm/WebAssemblyParser.js
test/cases/wasm/export-imported-global/env.js
test/cases/wasm/export-imported-global/index.js
test/cases/wasm/export-imported-global/module.js
test/cases/wasm/export-imported-global/module.wat
test/cases/wasm/export-imported-global/test.filter.js

 handle reexported wasm globals

---

lib/WebpackOptionsDefaulter.js
test/configCases/issues/issue-7470/index.js
test/configCases/issues/issue-7470/webpack.config.js

When `mode` is set to `none`, `process.env.NODE_ENV` is also set to `none` which could be confusing (see #7470). Changing this behavior would be a breaking change.
This PR adds a `TODO` note and test cases to document the future change.
test
yes
no
nothing

Add a test case about nodeEnv

---

lib/NormalModule.js
lib/NormalModuleFactory.js
lib/RequestShortener.js
lib/RuleSet.js
test/NormalModule.unittest.js
test/cases/wasm/two-files-loader/index.js
test/cases/wasm/two-files-loader/src/wasm.dat
test/cases/wasm/two-files-loader/test.filter.js
test/cases/wasm/two-files-loader/wrapper-loader.js
test/cases/wasm/two-files-loader/wrapper-loader2.js

Match rules with custom resource name
Also use this name as rule.issuer or splitChunks test
Show nicely in stats
cc @xtuc (holyc-loader)
cc @yyx990803 (vue-loader)
This is interesting for you.
feature
yes
no
For loader authors:
A new inline request syntax is available. Prefixing `<match-resource>!=!` to a request will set the `matchResource` for this request. (A relative `matchResource` will resolve relative to the current context of the containing module.)
When a `matchResource` is set, it will be used to match with the `module.rules` instead of the original resource. This can be useful if …

Add matchResource feature (for loaders)

---

lib/Chunk.js
lib/ChunkGroup.js

In Typescript 2.9 and earlier, Typescript allowed braces around the name introduced by the `@template` tag, even though this syntax is non-standard. In 3.0, Typescript introduces a more complex `@template` syntax that uses braces for specifying the constraint of a type parameter:
```js
/**
* @template {Constraint} T -- By analogy with param syntax:
* @param {T} name
*/
function f(name) { ... }
```
That means that the syntax `/** @template {T} */` will be illegal because it specifies the template's constraint but not the type parameter name. This PR fixes the uses of the `@template` tag ahead of Typescript 3.0 (as well as typescript@next as of June 5).

Fix template tag syntax

---

test/cases/parsing/issue-5889/index.js
test/cases/parsing/issue-5889/module.js

Add a test case to validate `require` truthiness. This PR only adds a test to ensure that #5889 is no longer an issue.
Fixes #5889
Fixes #5209
test
yes
no
nothing

Ensure `require` is truthy

---

test/cases/chunks/issue-5153/index.js
test/cases/chunks/issue-5153/module.js

Add a test to ensure that #5153 has been fixed.
Fixes #5153
test
yes
no
nothing

Ensure static and dynamic imports use the same binding

---

lib/AutomaticPrefetchPlugin.js

AutomaticPrefetchPlugin typings added
no
no
no

AutomaticPrefetchPlugin typings

---

lib/CommentCompilationWarning.js
lib/Dependency.js

CommentCompilationWarning typings
no
no
no

CommentCompilationWarning typings

---

examples/README.md

**Motivation:**
* Examples documentation is outdated.
* There was an attempt(#7398) to resolve this issue(#7222) by @UiCandy but things seem to have gotten stale due to his inactivity.
* Additionally it seems that @UiCandy overlooked [few other dead links](https://github.com/webpack/webpack/tree/master/examples#css-bundle) (Css Bundle Section links).
Docs change only.
No tests since these are purely docs changes.
No.
Nothing.

Remove dead links from /examples README.md.

---

lib/webworker/WebWorkerMainTemplatePlugin.js
test/configCases/issues/issue-7563/index.js
test/configCases/issues/issue-7563/one.js
test/configCases/issues/issue-7563/test.config.js
test/configCases/issues/issue-7563/webpack.config.js

Previously, not all path variables were implemented when doing dynamic imports and targeting webworker. See #7563.
A bugfix. WebWorkerMainTemplatePlugin.js was missing some required chunk attributes.
Yes. Though I do have questions about the test framework. I'll post those as a separate comment.
No. Prior to this commit, unsupported path variables would either throw at compile time or produce unexpected import paths at runtime.
No new documentation needed.

Implement all path variables for webworker dynamic imports

---

lib/debug/ProfilingPlugin.js

Based on some digging in this git history for the profiling plugin it looks like this commit exacerbated the issue:
883088e
Note, we are calling end() and then writeStream right after we call flush on the trace object
https://github.com/samccone/chrome-trace-event/blob/64b514e9bd364ca5b6df3c0fb121ba0d3b239cc2/lib/trace-event.ts#L123
The trace object is only calling _push to the writable stream but in no way ensuring that all data that has been pushed has actually been written to the output stream sooo we find ourselves encounter 🐎 [race] conditions.
Fixes #7450
bugfix
no
no
nothing

Fix race condition in profiling plugin.

---

lib/JsonGenerator.js

Bugfix https://github.com/webpack/webpack/issues/7082
**Summary**
Invalid JSON file causes webpack to abnormally exit. Look at the issue https://github.com/webpack/webpack/issues/7082 for further details
**Does this PR introduce a breaking change?** 
No

Fix - Exits abruptly when invalid JSON
