webpack/webpack

- .editorconfig
[This](http://editorconfig.org/) helps contributors keep consistent with the project style. For now it's just tabs, but it helped with my latest PR :smile:
> Add .editorconfig for contributors

- hot/dev-server.js
- hot/only-dev-server.js
Also added periods to the disabled messages, since the rest of the messages have them.
> Fix typo in hot plugins: "Propably" => "Probably"

- lib/Compiler.js
https://github.com/webpack/webpack/issues/769#issuecomment-73615872
> make Watching.close callback optional

- lib/webpack.js
> Export EvalSoureMapDevToolPlugin

- lib/CompatibilityPlugin.js
Just a couple of typos and minor grammar issues.
> Improve critical dependency warning text

- lib/optimize/MinChunkSizePlugin.js
combinations.length may become 0 after filter
> fix length judgment in MinChunkSizePlugin

- .travis.yml
- package.json
Somewhat shorter scripts, and a little DRYer
> Cleanup npm scripts

- .travis.yml
Giving Io.js build a new try.
Ref #1007
> Build with Io.js on Travis

- lib/BannerPlugin.js
- test/configCases/plugins/banner-plugin/index.js
- test/configCases/plugins/banner-plugin/test.js
- test/configCases/plugins/banner-plugin/vendors.js
- test/configCases/plugins/banner-plugin/webpack.config.js
This PR adds the ability to specify chunks to include/exclude when running the BannerPlugin
> Include/exclude filtering in BannerPlugin

- README.md
- examples/commonjs/README.md
- examples/commonjs/template.md
- examples/externals/README.md
- examples/externals/template.md
Various typos I ran into when reading
> Typo fixes in README and template.md

- lib/JsonpMainTemplate.runtime.js
This addresses https://github.com/webpack/webpack/pull/861#commitcomment-11679863.
> Make hotDownloadManifest return a promise

- README.md
Add badges to the README
it will look like that:
> feat(app): Add badges to REAMDE.md

- package.json
Hello,
here is pullrequest to fix dependencies for npm@3.0.0.
https://github.com/npm/npm/releases/tag/v3.0.0
> npm: fixed dependency for npm@3.0.0

- lib/NormalModule.js
See https://github.com/webpack/source-map-loader/pull/3
> Expose the compiler's input filesystem to loaders.

- lib/optimize/UglifyJsPlugin.js
- test/configCases/plugins/uglifyjs-plugin/index.js
- test/configCases/plugins/uglifyjs-plugin/test.js
- test/configCases/plugins/uglifyjs-plugin/vendors.js
- test/configCases/plugins/uglifyjs-plugin/webpack.config.js
Fixes https://github.com/webpack/webpack/issues/324
> Stronger check and override of comments in UglifyJsPlugin options

- package.json
Needed to fix a security issue in uglify-js
https://github.com/mishoo/UglifyJS2/issues/751
https://zyan.scripts.mit.edu/blog/backdooring-js/
> Update uglify-js dependency to v2.4.24

- bin/convert-argv.js
> CLI: Complain more clearly when output filename is missing

- lib/ModuleFilenameHelpers.js
> Fix fail when undefined module is coming to footer generator

- lib/NodeStuffPlugin.js
> Fix the absolute path used in NodeStuffPlugin

- package.json
Related issue: https://github.com/mishoo/UglifyJS2/issues/861
> Run away from buggy UglifyJS 2.5.0

- lib/WebpackOptionsApply.js
Not sure if everything done right. please check, thanks!
> `electron-main` and `electron-renderer` targets

- README.md
This is already said in just the previous paragraph.
> Remove duplicate sentence in README.md

- lib/EvalSourceMapDevToolModuleTemplatePlugin.js
- lib/SourceMapDevToolPlugin.js
> Set charset as 'utf-8' in sourcemap plugin

- test/cases/parsing/harmony/index.js
- test/cases/parsing/harmony/node_modules/abc.js
Sorry for it taking a while but finally managed to set up an example for https://github.com/webpack/webpack/issues/1794
> Failing test on named * export

- LICENSE
> Update Copyright notice to include 2016.

- .eslintrc
- bin/convert-argv.js
- lib/HotModuleReplacement.runtime.js
- lib/ModuleFilenameHelpers.js
- lib/Parser.js
- lib/SourceMapDevToolPlugin.js
- lib/Stats.js
- lib/UmdMainTemplatePlugin.js
- lib/WebpackOptionsApply.js
- lib/dependencies/AMDRequireDependenciesBlockParserPlugin.js
- lib/dependencies/ContextDependencyHelpers.js
- lib/dependencies/LabeledModuleDependencyParserPlugin.js
- lib/dependencies/ModuleDependencyTemplateAsId.js
- lib/dependencies/ModuleDependencyTemplateAsRequireId.js
- lib/optimize/AggressiveMergingPlugin.js
- lib/optimize/DedupePlugin.js
- lib/optimize/UglifyJsPlugin.js
Every file change is pretty straightforward, except for `lib/HotModuleReplacement.runtime.js` which just takes a little extra time to stare at.
> Fix no-redeclare in code and switch to error mode

- README.md
This readme contains an impressive number of badges! You should be proud and show off how many you have by using another badge \o/
> README.md: add badge count badge

- lib/HotModuleReplacement.runtime.js
> Check for (g/s)etter support, not Object.defineProperty

- lib/LibManifestPlugin.js
- test/configCases/plugins/lib-manifest-plugin/a.js
- test/configCases/plugins/lib-manifest-plugin/index.js
- test/configCases/plugins/lib-manifest-plugin/webpack.config.js
Fixes #2106 
I just cherry-picked https://github.com/webpack/webpack/commit/d883923da1b7fd5f7ef29a6b36357115488030c2
> Backport #1764

- .gitignore
now more and more people use webstrom or idea,please add this ..
> ignore idea config

- README.md
http://survivejs.com/blog/survivejs-webpack-100/
_Disclosure_: I've worked with [Juho before](https://github.com/jsdelivr/api/graphs/contributors).  But frankly, I lost track of him; & found his blog via Google search, so he knows nothing about this PR before now.
> + survivejs-webpack book link

- bin/webpack.js
Fixes https://github.com/webpack/webpack/issues/1455
> Fix error on empty array config

- lib/MainTemplate.js
> Fix missing __webpack_require__.oe()

- README.md
> Fix small typos in Readme

- lib/AsyncDependenciesBlock.js
- lib/CaseSensitiveModulesWarning.js
- lib/ChunkRenderError.js
- lib/ChunkTemplate.js
- lib/ContextModule.js
- lib/CriticalDependenciesWarning.js
- lib/DelegatedModule.js
- lib/DllModule.js
- lib/EntryModuleNotFoundError.js
- lib/ExternalModule.js
- lib/HotUpdateChunkTemplate.js
- lib/MainTemplate.js
- lib/ModuleBuildError.js
- lib/ModuleError.js
- lib/ModuleNotFoundError.js
- lib/ModuleParseError.js
- lib/ModuleTemplate.js
- lib/ModuleWarning.js
- lib/MultiModule.js
- lib/NormalModule.js
- lib/RawModule.js
- lib/UnsupportedFeatureWarning.js
- lib/WebpackOptionsApply.js
- lib/dependencies/AMDRequireDependenciesBlock.js
- lib/dependencies/RequireEnsureDependenciesBlock.js
- lib/dependencies/SystemImportDependenciesBlock.js
As i walk through the source, i've tried to trace the webpack running stack.
Then, i find the missing constructors result in uncleasr stack and create a patch
for them.
> add missing constructors for all classes needed

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR adds github issue templating and pull request templating.
> chore(github) Added github issue and pull request templates.

- .eslintrc
- hot/dev-server.js
- hot/only-dev-server.js
- hot/poll.js
- hot/signal.js
- lib/NormalModule.js
- lib/Parser.js
- lib/Template.js
- lib/optimize/RemoveParentModulesPlugin.js
- package.json
The plugin threw an error on me when I was testing syntax errors. I don't know why you went with nodeca to begin with, but it hasn't been updated since 2014, so I'm guessing those reasons are invalid 😄 
I just ran `npm run lint -- --fix` to fix the issues reported
> Use eslint's indent rule

- lib/webpack.js
> fix: fix typo in error message

- lib/BannerPlugin.js
Since Chunk.initial is now removed, use isInitial()
> [BannerPlugin] change chunk.initial to chunk.isInitial()

- appveyor.yml
These are the same node versions tested in travis
> Added appveyor support for modern node versions

- lib/Compilation.js
> Fix compilation not to store dependency warnings in modules

- bin/config-yargs.js
- bin/convert-argv.js
Prints error, no configuration file.
Prints version number.
* Impact:
[Feature Request #2930](https://github.com/webpack/webpack/issues/2930)
> Adding option ( -v or --version ) to print version.

- package.json
Fixes https://github.com/webpack/webpack/pull/2974#issuecomment-248010754
> Add schemas to package.json files

- package.json
See #3011, code mangling doesn't work.
Manging works with new uglify-js.
> Update uglify-js dep

- schemas/webpackOptionsSchema.json
Fixes https://github.com/webpack/webpack/issues/3019#issuecomment-248218429
> Use anyOf in place of oneOf where intended

- lib/WebpackOptionsValidationError.js
- test/Validation.test.js
The message incorrectly states that the plugins options is an object.
The message states that the plugins options is an array.
* Impact:
> Fix plugin typos in options validation

- schemas/webpackOptionsSchema.json
* Impact:
Added missing properties/options for `schema.json`. Discussed [here](https://github.com/webpack/webpack/pull/3094). Thanks @Kovensky for pointing it out.
1. Additional options for `target`. [Code](https://github.com/webpack/webpack/blob/e896d14/lib/WebpackOptionsApply.js#L71-L182)
2. Added `console` and `Buffer` …
> Schema: Added missing properties

- .travis.yml
> feat(travis): cache directory for yarn and npm

- .travis.yml
- appveyor.yml
This removes the unsupported Node v5 and removes a duplicate Node 6 run from Travis.
> feat(travis): reduce node runs

- .travis.yml
- package.json
- test/mocha.opts
While looking at the travis-ci results I noticed there was a ton of noise (lots of data on passing tests). This PR uses the min reporter to only show failing tests.
> feat(test) use min reporter to show only failing tests (reduce noise)

- package.json
No new behavior.
Added a missing space in `package.json`.
> replace missing space in package.json

- .eslintrc
**What is the current behavior?**
eslint may proceed to parent directories to look for more `.eslintrc`s.
By adding `"root": true`, we can explicitly terminate config resolution and prevent eslint from doing unexpected things.
> add "root": true to .eslintrc

- lib/RuleSet.js
- test/RuleSet.test.js
See #3156 
See #3156 . Reported error gives more context, showing offending condition.
* Impact:
> feat(ruleset): show context in error when `exclude` holds undefined item

- test/cases/parsing/harmony-export-precedence/a.js
https://github.com/webpack/webpack/issues/1792
The test case for harmony-export-precedence has illegal syntax.
no syntax error
> fix the illegal syntax in a module for test

- .travis.yml
- ci/travis-install.sh
Currently we are only testing against node 6 and 4. 
Now that node 7 is current and we have agreed to support node 0.12 still, we should add those tests back onto travis. 
* Impact: Low to None
* Migration path for existing applications: N/A
* Github Issue(s) this is regarding: (Core team meeting discussion).
> chore(test): add node 7, and 0.12 to travis

- lib/RuleSet.js
> fixed 'beautify-lint' errors in 'lib/RuleSet.js'

- bin/convert-argv.js
- hot/poll.js
- hot/signal.js
- lib/NormalModule.js
- lib/ProgressPlugin.js
**Comments**
Changing function declarations `function fnName() {};` to named function expression `var fnName = function fnName() {};`
- Impact:
- Migration path for existing applications: 
- Github Issue(s) this is regarding:
> fix 'no-inner-declarations' warnings

- lib/Compilation.js
- lib/ExternalModuleFactoryPlugin.js
- lib/HotModuleReplacement.runtime.js
- lib/OptionsDefaulter.js
- lib/optimize/AggressiveSplittingPlugin.js
**Comments**
I have extracted the functions outside `for` loop, let me know if you have any different thought on naming the functions.
- Impact:
- Migration path for existing applications: 
- Github Issue(s) this is regarding:
> fix 'no-loop-func' warnings

- test/Template.test.js
- [] Docs have been added / updated (for bug fixes / features)
- [] Bugfix
- [] Refactoring (no functional changes, no api changes)
Current behavior has a typo in an unused required variable.
The behavior is the same except the required `should` variable is now used.
* Impact:
The `should` variable might not be needed.
> update test to fix typo

- examples/web-worker/README.md
Accidentally introduced with #3102
> Fix git conflict in examples/web-worker/README.md

- lib/Stats.js
- lib/performance/EmittedAssetSizeLimitPlugin.js
- schemas/webpackOptionsSchema.json
Pulling in @vigneshshanmugam 's additions to this feature branch.
> Custom stats

- .travis.yml
OSX is not tested on CI
OSX is tested on CI, but optional
> reenable osx build

- lib/Parser.js
- test/cases/parsing/issue-3273/file.js
- test/cases/parsing/issue-3273/index.js
- test/cases/parsing/issue-3273/test.filter.js
- test/helpers/supportsObjectDestructuring.js
> support desctruction for variable declaration

- lib/dependencies/HarmonyImportDependencyParserPlugin.js
- test/cases/parsing/issue-3116/file.js
- test/cases/parsing/issue-3116/file2.js
- test/cases/parsing/issue-3116/index.js
> fixes indexed import

- lib/node/NodeSourcePlugin.js
Not sure how to proper test&document this change, help me improvement please if they are necessary for this PR.
#2215
Generated require calls is relative paths now.
> Change absolute path returned by getPathToModule() to relative path

- appveyor.yml
- package.json
appveyor often failed with memory issues
It works better
> [WIP] fix the appveyor build

- test/configCases/plugins/define-plugin/index.js
- test/configCases/plugins/define-plugin/webpack.config.js
> add test cases for #3235

- lib/MainTemplate.js
- lib/WebpackOptionsDefaulter.js
- schemas/webpackOptionsSchema.json
- test/configCases/runtime/opt-in-finally/exception.js
- test/configCases/runtime/opt-in-finally/index.js
- test/configCases/runtime/opt-in-finally/webpack.config.js
see #1729
`output.strictModuleExceptionHandling = true` allows to opt-in into the correct behavior (which is slower)
> added strictModuleExceptionHandling option

- lib/HotModuleReplacement.runtime.js
> fixes #3159

- lib/node/NodeSourcePlugin.js
- package.json
- test/configCases/target/web/index.js
bugfix
yes
not relevant
**Summary**
fix webpack for some changes in shims
yes
> don't shim shims and update node-libs

- README.md
Readme Change
No
**Summary**
Add more backer slots so they appear.
Nope
Added more backer slots. We are at 92 backers and counting.
> chore(readme) add more backer 'slots'

- .editorconfig
- .travis.yml
- package.json
build related (CI)
**Summary**
There are now separate travis jobs for linting and testing.
Node.js 4 has made non-optional
> split linting and testing into travis jobs

- lib/NormalModuleFactory.js
- lib/RuleSet.js
- schemas/webpackOptionsSchema.json
- test/Validation.test.js
- test/configCases/rule-set/custom/a.js
- test/configCases/rule-set/custom/b.js
- test/configCases/rule-set/custom/call-a.js
- test/configCases/rule-set/custom/index.js
- test/configCases/rule-set/custom/loader.js
- test/configCases/rule-set/custom/webpack.config.js
- test/configCases/rule-set/query/a.js
- test/configCases/rule-set/query/index.js
- test/configCases/rule-set/query/loader.js
- test/configCases/rule-set/query/webpack.config.js
feature
yes
not yet
**Summary**
Allows matching on query and adds support for custom data to loader transformation
no
added function use to schema
> added resourceQuery condition

- bin/webpack.js
bugfix
no
N/A
**Summary**
see #3379
no
> fixes typo, fixes #3379

- .github/PULL_REQUEST_TEMPLATE.md
documentation
no
yes
**Summary**
make clear that tests are mandatory
> add some note to the PR template

- lib/dependencies/HarmonyExportDependencyParserPlugin.js
- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- test/cases/parsing/harmony-import-export-order/a.js
- test/cases/parsing/harmony-import-export-order/b.js
- test/cases/parsing/harmony-import-export-order/c.js
- test/cases/parsing/harmony-import-export-order/index.js
- test/cases/parsing/harmony-import-export-order/tracker.js
bugfix
yes
N/A
**Summary**
see #3382
no
fixes #3382
> insert import and exports in order

- lib/BasicEvaluatedExpression.js
- lib/Parser.js
- package.json
bugifx
yes
N/A
**Summary**
fixes the beautify CI
no
> fixes beautify task

- lib/optimize/CommonsChunkPlugin.js
refactoring 
No
N/A
**Summary**
Collect CommonsChunkPlugin's deprecation notice available options
No
> Fill available params on CommonsChunkPlugin deprecation notice 

- lib/dependencies/HarmonyCompatiblilityDependency.js
- lib/dependencies/HarmonyExportDependencyParserPlugin.js
- lib/dependencies/HarmonyModulesPlugin.js
- test/cases/parsing/harmony-commonjs/a.js
- test/cases/parsing/harmony-commonjs/index.js
- test/statsCases/tree-shaking/expected.txt
**Summary**
see #3168
fixes #3268
> fixes using webpack harmony modules from babel

- lib/WebpackOptionsValidationError.js
- lib/validateSchema.js
- schemas/webpackOptionsSchema.json
- test/Validation.test.js
improvement
yes
n/a
**Summary**
Display nested validation messages for anyOf/oneOf rules as details.
Nest validation errors correctly
no
> Improve validation errors

- bin/webpack.js
bugfix
no (there is no test infrastructure for CLI tests)
N/A
**Summary**
exit the process if a fatal error happens (even in watch mode)
no
fixes #3464
> exit correctly when a fatal error happens

- lib/NormalModuleFactory.js
- test/ConfigTestCases.test.js
- test/configCases/loaders/issue-3320/index.js
- test/configCases/loaders/issue-3320/node_modules/any-loader.js
- test/configCases/loaders/issue-3320/webpack.config.js
Feature/Bugfixish
Yes
N/A
**Summary**
Fixes #3320
No
> feature(alias): allow loader query to be used for aliased loader

- test/cases/errors/loader-error-warning/error-loader.js
- test/cases/errors/loader-error-warning/errors.js
- test/cases/errors/loader-error-warning/index.js
- test/cases/errors/loader-error-warning/warning-loader.js
- test/cases/errors/loader-error-warning/warnings.js
test
yes
N/A
**Summary**
add test case for emitError and emitWarning
no
> add test case for emitError and emitWarning

- lib/optimize/CommonsChunkPlugin.js
- test/configCases/externals/externals-in-commons-chunk/index.js
- test/configCases/externals/externals-in-commons-chunk/other.js
- test/configCases/externals/externals-in-commons-chunk/test.config.js
- test/configCases/externals/externals-in-commons-chunk/webpack.config.js
bugfix
yes
N/A
**Summary**
CommonChunkPlugin now respects chunk conditions
no
> check chunk condition before moving into commons chunk

- lib/NormalModule.js
- test/Compiler-caching.test.js
- test/Compiler.test.js
- test/HotTestCases.test.js
- test/hotCases/recover/recover-after-loader-error/a.js
- test/hotCases/recover/recover-after-loader-error/errors1.js
- test/hotCases/recover/recover-after-loader-error/index.js
- test/hotCases/recover/recover-after-loader-error/loader.js
bugfix
yes
n/a
**Summary**
fixes #3500
no
> fixes an error where errors are not cleared in cached module

- lib/NormalModule.js
- test/WatchTestCases.test.js
- test/watchCases/parsing/caching-harmony/0/changing-module.js
- test/watchCases/parsing/caching-harmony/0/index.js
- test/watchCases/parsing/caching-harmony/0/module.js
- test/watchCases/parsing/caching-harmony/1/changing-module.js
- test/watchCases/parsing/switching-harmony/0/cc.js
- test/watchCases/parsing/switching-harmony/0/ch.js
- test/watchCases/parsing/switching-harmony/0/hc.js
- test/watchCases/parsing/switching-harmony/0/hh.js
- test/watchCases/parsing/switching-harmony/0/index.js
- test/watchCases/parsing/switching-harmony/1/cc.js
- test/watchCases/parsing/switching-harmony/1/ch.js
- test/watchCases/parsing/switching-harmony/1/hc.js
- test/watchCases/parsing/switching-harmony/1/hh.js
- test/watchCases/simple/simple/0/changing-file.js
- test/watchCases/simple/simple/0/index.js
- test/watchCases/simple/simple/1/changing-file.js
- test/watchCases/simple/simple/2/changing-file.js
test infrastructure
yes
n/a
**Summary**
adds infrastructure for watch tests and some basic tests
no
> add infrastructure for watch tests

- test/TestCases.test.js
- test/cases/errors/case-sensistive/index.js
- test/cases/errors/case-sensistive/test.filter.js
- test/cases/errors/case-sensistive/warnings.js
test
yes
N/A
**Summary**
improve code coverage
no
> add test case for case sensitive module warning

- README.md
> Fix html plugin version badge

- bin/webpack.js
- lib/Compilation.js
- lib/Module.js
- lib/Stats.js
- test/Stats.test.js
- test/browsertest/build.js
- test/statsCases/max-modules-default/a.js
- test/statsCases/max-modules-default/b.js
- test/statsCases/max-modules-default/c.js
- test/statsCases/max-modules-default/expected.txt
- test/statsCases/max-modules-default/index.js
- test/statsCases/max-modules-default/webpack.config.js
- test/statsCases/max-modules/a.js
- test/statsCases/max-modules/b.js
- test/statsCases/max-modules/c.js
- test/statsCases/max-modules/expected.txt
- test/statsCases/max-modules/index.js
- test/statsCases/max-modules/webpack.config.js
- test/statsCases/preset-normal-performance-ensure-filter-sourcemaps/expected.txt
- test/statsCases/preset-verbose/expected.txt
feature
yes
not yet
**Summary**
add depth to module
add depth to stats
fix stats spacing (fixes #3541)
add maxModules to stats, default to 15 (fixes #3540)
yes, output is different
> update to stats output

- lib/WebpackOptionsApply.js
- lib/WebpackOptionsDefaulter.js
- lib/webpack.js
- test/Compiler-caching.test.js
- test/Compiler.test.js
- test/WatchTestCases.test.js
- test/configCases/plugins/watch-ignore-plugin/index.js
- test/watchCases/plugins/watch-ignore-plugin/0/a.js
- test/watchCases/plugins/watch-ignore-plugin/0/file.js
- test/watchCases/plugins/watch-ignore-plugin/0/index.js
- test/watchCases/plugins/watch-ignore-plugin/1/a.js
- test/watchCases/plugins/watch-ignore-plugin/1/file.js
- test/watchCases/plugins/watch-ignore-plugin/2/a.js
- test/watchCases/plugins/watch-ignore-plugin/2/file.js
- test/watchCases/plugins/watch-ignore-plugin/webpack.config.js
test
it's a test
n/a
**Summary**
small fix and test case for the watch-ignore-plugin
no, it's a fix
> watch ignore plugin

- test/Compiler-caching.test.js
test
no
n/a
**Summary**
disables the flanky test for now.
no
> disable flanky test

- lib/RuleSet.js
- schemas/webpackOptionsSchema.json
- test/RuleSet.test.js
- test/configCases/rule-set/simple-use-fn-array/a.js
- test/configCases/rule-set/simple-use-fn-array/ab.js
- test/configCases/rule-set/simple-use-fn-array/b.js
- test/configCases/rule-set/simple-use-fn-array/c.js
- test/configCases/rule-set/simple-use-fn-array/index.js
- test/configCases/rule-set/simple-use-fn-array/loader.js
- test/configCases/rule-set/simple-use-fn-array/webpack.config.js
Bugfix
Yes 
**Summary**
Fixes #3484
No
> fix(RuleSet): normalize mixed use array and function

- lib/RuleSet.js
bugfix
no, too difficult (no test infrastructure)
n/a
**Summary**
add error when using `options/query` without `loader` in rule.
no
> add error for #3556, add recommendations for errors

- lib/Template.js
refactoring
there are tests in place, this is just a refactoring
**Summary**
I am currently reading large parts of the webpack source to get a better understanding what is happening and I kind of tripped over this method here. This refactoring is by all means not necessary, I just felt reading the Method took me longer than necessary, especially `AZ2_COUNT` and `Z2_CODE` feel unnecessary and making it harder to read. 
No, its a refactoring
I guess it makes it a little easier to read, if that is reason enough.
> simplify numberToIdentifer method

- test/configCases/no-parse/module.exports/index.js
- test/configCases/no-parse/module.exports/not-parsed-a.js
- test/configCases/no-parse/module.exports/not-parsed-b.js
- test/configCases/no-parse/module.exports/webpack.config.js
tests
yes
N/A
**Summary**
add two test cases for not parsed modules
no
> add noParse test cases

- lib/performance/SizeLimitsPlugin.js
- test/configCases/issues/issue-3596/b.js
- test/configCases/issues/issue-3596/index.js
- test/configCases/issues/issue-3596/webpack.config.js
bugfix
yes
N/A
**Summary**
see #3596
no
> fixes #3596

- lib/Compiler.js
- lib/NodeStuffPlugin.js
- lib/NormalModuleFactory.js
- lib/WebpackOptionsApply.js
- lib/node/NodeSourcePlugin.js
- package.json
- test/cases/loaders/issue-2299/loader/index.js
Refactor
Should be covered by existing tests: if not, please let me know what's worth testing.
N/A
**Summary**
#3607 for context.
Breaking for node 0.12, but support has been removed. So no.
Please let me know if there's anything I've overlooked here.
> Replace object-assign polyfill with native method

- package.json
Dependency upgrade
N/A
N/A
**Summary**
memory-fs has gotten a couple of performance related changes and many bugfixes.
No.
> Upgrade memory-fs dependency

- lib/ArrayMap.js
- test/fixtures/temp-1000/file.js
- test/fixtures/temp-1000/file2.js
refactoring
N/A
**Summary**
Update ArrayMap to es2015.
No
> refactor(ArrayMap): update ArrayMap to es2015 class

- lib/NamedModulesPlugin.js
Refactor
Existing Tests Pass
N/A
**Summary**
Upgrade NamedModulesPlugin to es6.
Nada nada limonada.
> refactor(es6): Upgrade NamedModulesPlugin to es6

- lib/NewWatchingPlugin.js
Refactor plugin from es5=>es6
Existing tests.
N/A
**Summary**
Refactored plugin to use es6 class syntax.
No
> refactor(es6): Upgrade NewWatchingPlugin to es6

- lib/ExternalsPlugin.js
Refactor
Existing Tests Pass
N/A
**Summary**
Upgrade ExternalsPlugin to es2015.
No
> refactor(es6): Upgrade ExternalsPlugin to es6

- lib/ModuleReason.js
- lib/ModuleTemplate.js
Refactor
Existing tests passed
N/A
**Summary**
Refactor ModuleReason and ModuleTemplate to ES2015 syntax.
It better not.
> refactor(es6): Upgrade ModuleReason and ModuleTemplate to es6

- lib/DllModuleFactory.js
Refactoring (es5=>es6)
Existing tests passing.
N/A
**Summary**
Update DllModuleFactory to es6
No
> refactor(es6): Upgrade DllModuleFactory to es6

- lib/Entrypoint.js
Refactor
Existing Tests are Passing 🍾 
N/A 
**Summary**
Upgrade Entrypoint to es6 😍 
Nopers!
> refactor(es6): Upgrade Entrypoint to es6

- lib/UseStrictPlugin.js
- package.json
- test/fixtures/temp-1000/file.js
- test/fixtures/temp-1000/file2.js
Refactor
N/A
**Summary**
Updates UseStrictPlugin to ES6 class. Refactoring only.
Nope
> refactor(es6): Update UseStrictPlugin to es6 class [WIP] 

- lib/DllEntryPlugin.js
updates DllEntryPlugin to es2015
No
**Summary**
No
> refactor(es6): update DllEntryPlugin to es2015

- lib/EnvironmentPlugin.js
N/A
**Summary**
Refactors the IgnorePlugin to an ES6 class. First time contributor 😃 
Nope
> refactor(es6): refactor EnvironmentPlugin to ES6 class

- lib/AmdMainTemplatePlugin.js
refactoring
No
N/A
**Summary**
Update AmdMainTemplatePlugin to es2015.
No
> refactor(AmdMainTemplatePlugin): update AmdMainTemplatePlugin to es2015

- lib/CachePlugin.js
coverage
N/A
N/A
**Summary**
ingore flacky function from code coverage
no
> ingore flacky function from code coverage

- package.json
Dependency update
N/A
N/A
**Summary**
watchpack 1.2.0 fixes a couple of long outstanding issues in watchpack, so we should force that it gets installed.
No
> Update watchpack dependency

- lib/DefinePlugin.js
Refactor
Existing tests should cover this refactor
**Summary**
Nope
> refactor(es6): Update DefinePlugin to es2015

- test/ArrayMap.test.js
Add tests for ArrayMap
None
**Summary**
Based on the coveralls report, the ArrayMap file has 52% test coverage. There is no ArrayMap specific test file - this is added in this PR and aims to achieve 100% test coverage for this.
https://coveralls.io/builds/9479622/source?filename=lib%2FArrayMap.js
No
This is my first webpack PR - let me know if there's anything missing.
> Add tests for ArrayMap

- lib/DelegatedPlugin.js
N/A
**Summary**
Refactors the DelegatedPlugin to an ES6 class.
Nope
> refactor(es6): Update DelegatedPlugin to es6

- lib/webpack.web.js
Refactor
N/A
**Summary**
update lib/webpack.web.js to ES6
No
> refactor(es6): Upgrade lib/webpack.web.js to es6

- lib/AbstractPlugin.js
Refactor
N/A
**Summary**
update AbstractPlugin to ES6
No
> refactor(es6): Upgrade AbstractPlugin to es6

- test/compareLocations.test.js
Add tests for compareLocations
N/A
**Summary**
Based on the coveralls report, the compareLocations file has 74% test coverage. There is no compareLocations specific test file - this is added in this PR and aims to achieve 100% test coverage for this.
https://coveralls.io/builds/9483896/source?filename=lib%2FcompareLocations.js
No
None
> Add tests for compareLocations

- lib/FunctionModuleTemplatePlugin.js
- test/statsCases/chunks/expected.txt
- test/statsCases/define-plugin/expected.txt
- test/statsCases/preset-verbose/expected.txt
Feature
No, just updated existing expected output.
**Summary**
This back-ports c7b06ad617e7a3ea1d554214509d368c456996bb to `webpack-1` based on [the Twitter thread](https://twitter.com/TheLarkInn/status/815230804729196544) for the original PR (#3658).
No
This is my first webpack PR, so please let me know if there's anything I need to fix!
> feat(moduletemplate): Wrap function module template wrappers with parens

- lib/webpack.js
Refactor
N/A
**Summary**
update lib/webpack.js to ES6
No
> refactor(es6): Upgrade lib/webpack.js to es6

- lib/ChunkRenderError.js
> refactor(ChunkRenderError): upgrade to ES6

- lib/OptionsDefaulter.js
- lib/WebpackOptionsDefaulter.js
N/A
**Summary**
Just a new part of the ES6 refactor 
Nope
> refactor(es6): upgrade (Webpack)OptionsDefaulter to ES6

- lib/APIPlugin.js
> refactor(ES6): upgrade APIPlugin to ES6

- lib/BasicEvaluatedExpression.js
> refactor(ES6): upgrade BasicEvaluatedExpression to ES6

- lib/CachePlugin.js
Refactor
N/A
**Summary**
update CachePlugin to ES6
No
> refactor(es6): Upgrade CachePlugin to es6

- lib/ModuleError.js
> refactor(ModuleError): upgrade to ES6

- lib/dependencies/UnsupportedDependency.js
refactor
N/A
**Summary**
upgrade UnsupportedDependency and UnsupportedDependencyTemplate to es6
No
> refactor unsupported dependency to es6

- lib/dependencies/AMDRequireDependency.js
refactor
N/A
**Summary**
upgrade AMDRequireDependency and AMDRequireDependencyTemplate to es6
No
> refactor amd-require dependency to es6

- lib/performance/AssetsOverSizeLimitWarning.js
- lib/performance/EntrypointsOverSizeLimitWarning.js
- lib/performance/NoAsyncChunksWarning.js
- lib/performance/SizeLimitsPlugin.js
- yarn.lock
Refactoring.
No.
If relevant, link to documentation update:
Summary
Updated `SizeLimitPlugin` for `node@4.0.0` syntax.
No.
> Updated `SizeLimitsPlugin`.

- lib/AutomaticPrefetchPlugin.js
Refactor
N/A
**Summary**
update AutomaticPrefetchPlugin to ES6
No
> refactor(es6): Upgrade AutomaticPrefetchPlugin to es6

- lib/dependencies/ConstDependency.js
refactor
N/A
**Summary**
upgrade ConstDependency to es6
No
> refactor const dependency to es6

- lib/dependencies/LocalModuleDependency.js
refactor
N/A
**Summary**
upgrade LocalModuleDependency and LocalModuleDependencyTemplate to es6
No
> refactor localmodule dependency to es6

- lib/dependencies/RequireResolveHeaderDependency.js
refactor
N/A
**Summary**
upgrade RequireResolveHeaderDependency and RequireResolveHeaderDependencyTemplate to es6
No
> refactor requireresolveheader dependency to es6

- lib/dependencies/RequireHeaderDependency.js
refactor
N/A
**Summary**
upgrade RequireHeaderDependency and RequireHeaderDependencyTemplate to es6
No
> refactor requireheader dependency to es6

- lib/dependencies/HarmonyExportHeaderDependency.js
refactor
N/A
**Summary**
upgrade HarmonyExportHeaderDependency and HarmonyExportHeaderDependencyTemplate to es6
No
> refactor harmonyExportHeaderDependency to es6

- lib/SingleEntryPlugin.js
- test/configCases/entry/single-entry-point/single-entry-point.js
- test/configCases/entry/single-entry-point/webpack.config.js
Refactoring and an added unit test
Yes.
**Summary**
ES6 adaption for SingleEntryPlugin and no unit test from what I saw.
Nopers
> es5->es6 refactoring of SingleEntryPlugin

- lib/LoaderOptionsPlugin.js
Not
**Summary**
Refactors the LoaderOptionsPlugin to an ES6 class. First time contributor 🎉
Not
> refactor(es6): refactor LoaderOptionsPlugin to ES6 class

- lib/dependencies/HarmonyCompatiblilityDependency.js
refactor
N/A
**Summary**
upgrade HarmonyCompatibilityDependency and HarmonyCompatibilityDependencyTemplate to es6
No
> refactor harmonyCompatibilityDependency to es6

- lib/WebpackOptionsValidationError.js
- schemas/webpackOptionsSchema.json
- test/Validation.test.js
bugfix
Added one test
N/A
**Summary**
#3534 The PR prevents users from having empty entries for bundles in the configuration file.
No
> Added better validation for entry in option schema

- lib/optimize/UglifyJsPlugin.js
N/A, refactor. Existing test suite passes
N/A
**Summary**
Refactor the UglifyJSPlugin to an ES6 class. 
Nope
> refactor(es6): upgrade UglifyJSPlugin to ES6

- lib/WatchIgnorePlugin.js
- test/watchCases/plugins/watch-ignore-plugin/0/foo/0.js
- test/watchCases/plugins/watch-ignore-plugin/0/index.js
- test/watchCases/plugins/watch-ignore-plugin/1/foo/1.js
- test/watchCases/plugins/watch-ignore-plugin/2/foo/2.js
- test/watchCases/plugins/watch-ignore-plugin/webpack.config.js
Refactor
Existing tests are passing
N/A
**Summary**
Upgrade WatchEntryPoint to es6
No
> Upgrade WatchIgnorePlugin to es6

- test/watchCases/parsing/caching-harmony/0/index.js
bugfix
no, the fix is _in_ the test
**Summary**
The assertions weren't actually executed 
no
> Fix switch statement wrongly assuming WATCH_STEP is an integer number

- lib/optimize/ChunkModuleIdRangePlugin.js
N/A
**Summary**
Helps in refactoring the code base to ES6
No
> refactor(ES6): upgrade ChunkModuleIdRangePlugin to ES6

- lib/Chunk.js
- test/Chunk.test.js
> refactor(Chunk): upgrade to ES6

- lib/dependencies/RequireEnsureDependency.js
refactor
N/A
**Summary**
upgrade RequireEnsureDependency and RequireEnsureDependencyTemplate to es6
No
> refactor requireensure dependency to es6

- lib/dependencies/HarmonyExportExpressionDependency.js
refactor
N/A
**Summary**
upgrade HarmonyExportExpressionDependency and HarmonyExportExpressionDependencyTemplate to es6
No
> refactor harmonyExportExpressionDependency to es6

- lib/WebpackOptionsValidationError.js
> refactor(WebpackOptionsValidationError): upgrade to ES6

- lib/UnsupportedFeatureWarning.js
> refactor(ES6): upgrade UnsupportedFeatureWarning to ES6

- lib/Stats.js
> refactor(ES6): upgrade Stats to ES6

- lib/SourceMapDevToolModuleOptionsPlugin.js
> refactor(ES6): upgrade SourceMapDevToolModuleOptionsPlugin to ES6

- lib/SetVarMainTemplatePlugin.js
> refactor(ES6): upgrade SetVarMainTemplatePlugin to ES6

- lib/optimize/RemoveParentModulesPlugin.js
refactor ES5 => ES6
No
N/A
**Summary**
Upgrade RemoveParentModulesPlugin to ES6
No
> refactor(ES6): upgrade RemoveParentModulesPlugin to ES6

- lib/dependencies/HarmonyImportSpecifierDependency.js
refactor
N/A
**Summary**
upgrade HarmonyImportSpecifierDependency and HarmonyImportSpecifierDependencyTemplate to es6
No
> refactor HarmonyImportSpecifierDependency to es6

- lib/optimize/AggressiveSplittingPlugin.js
N/A
**Summary**
Refactor aggressive splitting plugin to use ES6 syntax
No
> refactor(ES6): upgrade AggressiveSplittingPlugin to ES6

- lib/optimize/AggressiveMergingPlugin.js
refactor,  ES5 => ES6
No, existing tests pass
N/A
**Summary**
Upgrade the AggressiveMergingPlugin to ES6 syntax
No
> refactor(ES6): upgrade AggressiveMergingPlugin to ES6

- lib/optimize/DedupePlugin.js
N/A
**Summary**
upgraded DedupePlugin to ES6
No
> refactor(ES6): upgrade DedupePlugin to ES6

- lib/optimize/EnsureChunkConditionsPlugin.js
N/A
**Summary**
Upgrade the EnsureChunkConditionsPlugin to ES6
No
> refactor(ES6): upgrade EnsureChunkConditionsPlugin to ES6

- lib/optimize/FlagIncludedChunksPlugin.js
N/A
**Summary**
Upgrade the FlagIncludedChunksPlugin to ES6
No
> refactor(ES6): upgraded FlagIncludedChunksPlugin to ES6

- lib/optimize/LimitChunkCountPlugin.js
N/A
**Summary**
Upgrade the LimitChunkCountPlugin to ES6
No
> refactor(ES6): upgraded LimitChunkCountPlugin to ES6

- lib/optimize/MergeDuplicateChunksPlugin.js
- lib/optimize/MinChunkSizePlugin.js
N/A
**Summary**
Upgrade the MinChunkSizePlugin to ES6
No
> refactor(ES6): upgrade MinChunkSizePlugin to ES6

- lib/DllPlugin.js
all tests are passing
**Summary**
Refactoring to ES2015/6
No
> refactor(ES6): upgrade DllPlugin to ES6

- lib/DllModule.js
all tests are passing
**Summary**
Refactoring to ES2015/6
No
> refactor(ES6): upgrade DllModule to ES6

- lib/dependencies/MultiEntryDependency.js
refactor
N/A
**Summary**
upgrade MultiEntryDependency to es6
No
> refactor MultiEntryDependency to es6

- lib/optimize/RemoveEmptyChunksPlugin.js
N/A
**Summary**
Upgrade the RemoveEmptyChunksPlugin to ES6
No
> refactor(ES6) upgrade RemoveEmptyChunksPlugin to ES6

- bin/webpack.js
Bugfix
I didn't see any tests for the CLI. I'm not sure how to add a test for this.
**Summary**
Fix #3759. Exit with code 1 when the configuration promise is rejected.
It seems unlikely that anyone was relying on this behavior, but it does mean that builds that previously appeared to succeed will result in errors.
> Exit with error when config promise is rejected

- lib/dependencies/SingleEntryDependency.js
refactor
N/A
**Summary**
upgrade SingleEntryDependency to es6
No
> refactor SingleEntryDependency to es6

- lib/web/WebEnvironmentPlugin.js
refactor. ES5 => ES6
No.
Current tests should pass.
N/A
**Summary**
upgrade WebEnvironmentPlugin to es6
No.
> refactor(WebEnvironmentPlugin): upgrade to ES6

- lib/dependencies/ModuleHotDeclineDependency.js
refactor
N/A
**Summary**
upgrade ModuleHotDeclineDependency to es6
No
> refactor ModuleHotDeclineDependency to es6

- lib/optimize/OccurrenceOrderPlugin.js
N/A
**Summary**
Upgrade the OccurrenceOrderPlugin to ES6
No
> refactor(ES6): upgrade OccurrenceOrderPlugin to ES6

- lib/optimize/MergeDuplicateChunksPlugin.js
N/A
**Summary**
Upgrade the MergeDuplicateChunksPlugin to ES6
No
> refactor(ES6): upgrade MergeDuplicateChunksPlugin to ES6

- lib/dependencies/AMDRequireArrayDependency.js
refactor
N/A
**Summary**
upgrade AMDRequireArrayDependency and AMDRequireArrayDependencyTemplate to es6
No
> Refactor AMDRequireArrayDependency to es6

- lib/dependencies/ContextElementDependency.js
refactor
N/A
**Summary**
upgrade ContextElementDependency to es6
No
> refactor of ContextElementDependency to es6

- lib/dependencies/DelegatedSourceDependency.js
refactor
N/A
**Summary**
upgrade DelegatedSourceDependency to es6
No
> refactor of DelegatedSourceDependency to es6

- lib/dependencies/RequireResolveDependency.js
refactor
N/A
**Summary**
upgrade RequireResolveDependency to es6
No
> refactor RequireResolveDependency to es6

- lib/dependencies/LoaderDependency.js
refactor
N/A
**Summary**
upgrade LoaderDependency to es6
No
> refactor LoaderDependency to es6

- lib/dependencies/ModuleHotAcceptDependency.js
refactor
N/A
**Summary**
upgrade ModuleHotAcceptDependency to es6
No
> refactor ModuleHotAcceptDependency to es6

- lib/node/NodeEnvironmentPlugin.js
No, all existing tests pass
If relevant, link to documentation update:
N/A
Summary
upgraded NodeEnvironmentPlugin to ES6
No
> refactor(ES6): upgrade NodeEnvironmentPlugin to ES6

- lib/DllReferencePlugin.js
Not
**Summary**
Refactors the DllReferencePlugin to an ES6 class
Not
> refactor(es6) upgrade DllReferencePlugin to ES6 class

- lib/MovedToPluginWarningPlugin.js
refactoring, ES5 => ES6
No behavioural changes in functions, so all tests should pass
N/A
**Summary**
Upgrade the MovedToPluginWarningPlugin to ES6
No
> Refactor MovedToPluginWarningPlugin to es6

- lib/dependencies/PrefetchDependency.js
refactor
N/A
**Summary**
upgrade PrefetchDependency to es6
No
> refactor PrefetchDependency to es6

- lib/dependencies/RequireIncludeDependency.js
refactor
N/A
**Summary**
upgrade RequireIncludeDependency to es6
No
> refactor of RequireIncludeDependency to es6

- lib/TemplatedPathPlugin.js
> refactor(TemplatedPathPlugin): upgrade to ES6

- lib/dependencies/ImportDependency.js
refactor
N/A
**Summary**
upgrade ImportDependency to es6
No
> Refactor import dependency to es6

- lib/JsonpExportMainTemplatePlugin.js
ES5 => ES6 refactor.
No.
Current tests should pass.
N/A
**Summary**
Upgrade JsonpExportMainTemplatePlugin to es6
No.
> refactor(JsonpExportMainTemplatePlugin): upgrade to ES6

- lib/dependencies/AMDRequireContextDependency.js
refactoring, ES5 to ES6 
No, All Current test case passing 
**Summary**
refactor lib/AMDRequireContextDependency: upgrade to ES6
No
> refactor lib/AMDRequireContextDependency: upgrade to ES6

- appveyor.yml
CI
yes
N/A
**Summary**
better appveyor script
no
> better appveyor script

- test/RawModule.test.js
Bugfix/Tests
Changes _are_ in the tests
N/A
**Summary**
Currently new PR's are failing due to an overly precise build test (https://travis-ci.org/webpack/webpack/jobs/189517362). This mitigates that.
> fix(tests): use less strict raw module time

- lib/dependencies/AMDRequireItemDependency.js
refactor
N/A
**Summary**
upgrade AMDRequireItemDependency to es6
No
> refactor of AMDRequireItemDependency to es6

- lib/RequireJsStuffPlugin.js
Refactor to from ES5 => ES6.
Covered by existing tests.
**Summary**
Wanted to contribute, so here is a small update to refactor from ES5 => ES6.
Nope.
Let me know if there is more refactoring that can be done here.
> refactor of RequireJsStuffPlugin to es6

- lib/MultiEntryPlugin.js
refactor(es6): Upgrade MultiEntryPlugin to ES6 :tada: :tada:
Existing Tests Look pretty darn good. 🍾 
N/A
> refactor(es6): Upgrade MultiEntryPlugin to ES6 

- lib/dependencies/CommonJsRequireDependency.js
refactor
N/A
**Summary**
upgrade CommonJsRequireDependency to es6
No
> refactor of CommonJsRequireDependency to es6

- lib/dependencies/RequireEnsureItemDependency.js
refactor
N/A
**Summary**
upgrade RequireEnsureItemDependency to es6
No
> refactor of RequireEnsureItemDependency to es6

- lib/dependencies/RequireContextDependency.js
refactor
N/A
**Summary**
upgrade RequireContextDependency to es6
No
> refactor of RequireContextDependency to es6

- lib/dependencies/RequireResolveContextDependency.js
refactor
N/A
**Summary**
upgrade RequireResolveContextDependency to es6
No
> refactor of RequireResolveContextDependency to es6

- lib/dependencies/ImportContextDependency.js
refactor
N/A
**Summary**
upgrade ImportContextDependency to es6
No
> refactor of ImportContextDependency to es6

- lib/dependencies/ImportDependenciesBlock.js
refactoring, ES5 => ES6
No behavioural changes in functions, so all tests should pass
N/A
**Summary**
Upgrade the ImportDependenciesBlock to ES6
NO
> refactor ImportDependenciesBlock to es6 syntax

- lib/dependencies/ModuleDependency.js
refactor
N/A
**Summary**
upgrade ModuleDependency to es6
No
we are getting closer :)
this PR relies on the follwing PRs to be merged:
> Refactor module dependency to es6

- lib/dependencies/ContextDependency.js
refactor
N/A
**Summary**
upgrade ContextDependency to es6
No
Depends on:
> refactor of ContextDependency to es6

- lib/dependencies/RequireEnsureDependenciesBlock.js
refactoring, ES5 => ES6
No behavioural changes in functions, so all tests should pass
N/A
**Summary**
Upgrade the RequireEnsureDependenciesBlock to ES6
NO
> refactor RequireEnsureDependenciesBlock to es6 syntax

- circle.yml
CI (Extra Infra)
N/A
N/A
**Summary**
This change adds a third testing platform: CircleCI. It is extremely simple and supports some testing parallelism. 
No
> ci(test): Add circle ci as third CI/CD Pipeline

- lib/ConstPlugin.js
> refactor(ConstPlugin): upgrade to ES6

- lib/JsonpHotUpdateChunkTemplatePlugin.js
> refactor(JsonpHotUpdateChunkTemplatePlugin): upgrade to ES6

- lib/Parser.js
- lib/compareLocations.js
- lib/dependencies/HarmonyExportDependencyParserPlugin.js
- test/cases/parsing/issue-3769/a.js
- test/cases/parsing/issue-3769/b.js
- test/cases/parsing/issue-3769/c.js
- test/cases/parsing/issue-3769/cjs.js
- test/cases/parsing/issue-3769/d.js
- test/cases/parsing/issue-3769/imported.js
- test/cases/parsing/issue-3769/index.js
- test/cases/parsing/issue-3769/module.js
bugfix
yes
N/A
**Summary**
fix for #3769
make dependency order stable, by adding an index to equal locations.
no
> make harmony order stable

- lib/ModuleWarning.js
> refactor(ModuleWarning): upgrade to ES6

- lib/Compilation.js
refactoe
No
N/A
**Summary**
minor cleanup
No
> Minor things

- test/HotUpdateChunkTemplate.test.js
Add tests for HotUpdateChunkTemplate
N/A
**Summary**
Based on the coveralls report, the `HotUpdateChunkTemplate` file has 80% test coverage. There is no `HotUpdateChunkTemplate` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9590525/source?filename=lib%2FHotUpdateChunkTemplate.js
No
None
> Add tests for HotUpdateChunkTemplate

- lib/Compilation.js
comments
No
N/A
**Summary**
I did not understand why this sort is needed, and guess this comment may help the next person reading along these lines :).
No
> add comments to clarify why a sort is needed here.

- bin/config-yargs.js
- bin/webpack.js
- test/binCases/stats/single-config/test.js
> Revert "Timestamp & Save flag"

- .travis.yml
CI
N/A
N/A
**Summary**
test fewer OSX builds as they are slow and block the other builds.
Build only PRs and master branch.
no
> faster travis builds

- .github/ISSUE_TEMPLATE.md
> add more notes to issue template

- package.json
bugfix
n/a
N/A
**Summary**
update the engine field
yes
> update engine support for node

- package.json
- test/cases/parsing/issue-3964/index.js
- test/cases/parsing/issue-3964/module.js
- test/cases/parsing/issue-3964/x.js
bugfix
yes
N/A
**Summary**
see #3964
no
> fix for #3964 and tests

- appveyor.yml
CI
N/A
N/A
**Summary**
only build master branch, like travis
no
> build only master branch for higher CI performance

- buildin/harmony-module.js
- buildin/module.js
refactoring
No
N/A
**Summary**
Remove specified defaults. Save you some bytes that made your website load so slow :trollface: .
No
see defaults: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Adding_properties_and_default_values
> remove defaults values to shave a few bytes

- bin/webpack.js
- test/BinTestCases.test.js
- test/binCases/watch/multi-config/index.js
- test/binCases/watch/multi-config/index2.js
- test/binCases/watch/multi-config/test.js
- test/binCases/watch/multi-config/webpack.config.js
- test/binCases/watch/single-config/test.js
- test/binCases/watch/single-config/webpack.config.js
Bug
Yes, I added tests.
[issue 2664](https://github.com/webpack/webpack/issues/2664)
> Fix watch when config is an array of objects

- lib/Parser.js
- test/cases/parsing/harmony-commonjs/e.js
- test/cases/parsing/harmony-commonjs/index.js
- test/cases/parsing/harmony-commonjs/reexport.js
bugfix
yes
N/A
**Summary**
hoist exports declarations too
fixes #3972
no
> hoist exports declarations too

- .travis.yml
- appveyor.yml
- package.json
- test/BenchmarkTestCases.benchmark.js
- test/benchmarkCases/lodash/webpack.config.js
- test/benchmarkCases/many-chunks/a.js
- test/benchmarkCases/many-chunks/b.js
- test/benchmarkCases/many-chunks/c.js
- test/benchmarkCases/many-chunks/index.js
- test/benchmarkCases/many-chunks/webpack.config.js
- test/benchmarkCases/react/webpack.config.js
CI benchmarking
N/A
N/A
**Summary**
add a benchmarking system which benchmarks PR against the base and the last published version.
no
> add benchmarking system

- lib/JsonpTemplatePlugin.js
N/A
**Summary**
upgrade JsonpTemplatePlugin to ES6
N/A
> refactor(es6) upgrade JsonpTemplatePlugin to ES6 class

- lib/EvalSourceMapDevToolPlugin.js
N/A
**Summary**
upgrade EvalSourceMapDevToolPlugin to ES6
N/A
> refactor(es6) upgrade EvalSourceMapDevToolPlugin to ES6 class

- lib/NormalModuleReplacementPlugin.js
N/A
**Summary**
upgrade NormalModuleReplacementPlugin to ES6
N/A
> refactor(es6) upgrade NormalModuleReplacementPlugin to ES6 class

- lib/MultiWatching.js
N/A
**Summary**
upgrade MultiWatching to ES6
N/A
> refactor(es6) upgrade MultiWatching to ES6 class

- lib/webworker/WebWorkerHotUpdateChunkTemplatePlugin.js
N/A
**Summary**
upgrade WebWorkerHotUpdateChunkTemplatePlugin to ES6
No
> refactor(ES6): upgrade WebWorkerHotUpdateChunkTemplatePlugin to ES6

- lib/dependencies/RequireResolveDependencyParserPlugin.js
N/A
**Summary**
upgrade RequireResolveDependencyParserPlugin to ES6
No
> refactor(ES6): upgrade RequireResolveDependencyParserPlugin to ES6

- lib/dependencies/RequireIncludePlugin.js
N/A
**Summary**
upgrade RequireIncludePlugin to ES6
No
> refactor(ES6): upgrade RequireIncludePlugin to ES6

- lib/dependencies/RequireContextPlugin.js
N/A
**Summary**
upgrade RequireContextPlugin to ES6
No
> refactor(ES6): upgrade RequireContextPlugin to ES6

- lib/dependencies/RequireEnsurePlugin.js
N/A
**Summary**
upgrade RequireEnsurePlugin to ES6
No
> refactor(ES6): upgrade RequireEnsurePlugin to ES6

- test/configCases/devtools/harmony-eval-source-map/index.js
- test/configCases/devtools/harmony-eval-source-map/webpack.config.js
- test/configCases/devtools/harmony-eval/index.js
- test/configCases/devtools/harmony-eval/webpack.config.js
test
yes
N/A
**Summary**
add tests
no
> add tests for harmony with devtools

- lib/dependencies/LocalModule.js
N/A
**Summary**
upgrade LocalModule to ES6
No
> refactor(ES6): upgrade LocalModule to ES6

- lib/FunctionModulePlugin.js
Not
**Summary**
Refactor the FunctionModulePlugin to an ES6 class
Not
> refactor(es6) upgrade FunctionModulePlugin to ES6 class

- test/WebEnvironmentPlugin.test.js
tests
N/A
**Summary**
The goal of this PR is add tests for `WebEnvironmentPlugin` class.
We don't have any breaking changes
> test(WebEnvironmentPlugin): adding missed test

- lib/node/NodeTargetPlugin.js
> refactor(NodeTargetPlugin): upgrade to ES6

- lib/dependencies/HarmonyCompatibilityDependency.js
- lib/dependencies/HarmonyDetectionParserPlugin.js
- lib/dependencies/HarmonyModulesPlugin.js
bugfix
No
**Summary**
Fixes https://github.com/webpack/webpack/issues/4060
No
> Rename class HarmonyCompatiblilityDependency to HarmonyCompatibilityDependency

- test/WebWorkerChunkTemplatePlugin.test.js
Tests for WebWorkerChunkTemplatePlugin
This PR has only tests
N/A
**Summary**
I tried to add tests for [WebWorkerChunkTemplatePlugin](https://github.com/webpack/webpack/blob/master/lib/webworker/WebWorkerChunkTemplatePlugin.js) by looking at [WebWorkerHotUpdateChunkTemplatePlugin.test.js](https://github.com/webpack/webpack/blob/master/test/WebWorkerHotUpdateChunkTemplatePlugin.test.js)
No
> Added tests for WebWorkerChunkTemplatePlugin

- test/formatLocation.test.js
N/A
**Summary**
Refactor formatLocation.test.js to ES6
No
> refactor(ES6): formatLocation.test.js

- test/CachePlugin.test.js
N/A
**Summary**
Refactor CachePlugin.test.js to ES6
No
> refactor(ES6): CachePlugin.test.js

- test/compareLocations.test.js
N/A
**Summary**
Refactor compareLocations.test.js to ES6
No
> refactor(ES6): compareLocations.test.js

- test/WebWorkerMainTemplatePlugin.test.js
Add tests for WebWorkerMainTemplatePlugin
N/A
**Summary**
Based on the coveralls report, the `WebWorkerMainTemplatePlugin` file has 75% test coverage. There is no `WebWorkerMainTemplatePlugin` specific test file - this is added in this PR and aims to achieve 100% test coverage.
https://coveralls.io/builds/9590525/source?filename=lib%2Fwebworker%2FWebWorkerMainTemplatePlugin.js
No
None
> Add tests for WebWorkerMainTemplatePlugin

- lib/validateSchema.js
- test/README.md
- test/Validation.test.js
refactor and documentation
current tests pass
N/A
**Summary**
refactor validateSchema and Validation.test to ES2015
update documentation to use yarn instead of npm and clarify steps needed to start testing
No
> refactor validateSchema and Validation.test to ES2015

- lib/RequestShortener.js
refactor (es5 => es6) 
refactor, existing tests pass
N/A
**Summary**
refactor :all_the_things:
Nope
> refactor(es6): upgrade RequestShortner to ES6

- lib/LoaderTargetPlugin.js
N/A
**Summary**
upgrade LoaderTargetPlugin to es6
N/A
> refactor(es6) upgrade LoaderTargetPlugin to ES6 class

- lib/dependencies/HarmonyModulesPlugin.js
N/A
**Summary**
upgrade HarmonyModulesPlugin to ES6
No
> refactor(ES6): upgrade HarmonyModulesPlugin to ES6

- test/configCases/hash-length/output-filename/test.config.js
- test/configCases/hash-length/output-filename/webpack.config.js
It adds tests for `lib/node/NodeMainTemplatePlugin.js` as described in issue #3716.
Only tests.
**Summary**
This PR increases the coverage for NodeMainTemplatePlugin.js above 80%. It also adds tests for chunk filename length, in addition to the existing filename length tests. This PR was inspired by #3716.
No.
> Add more tests for lib/node/NodeMainTemplatePlugin.js

- .travis.yml
CI
N/A
N/A
**Summary**
benchmarking on travis is to unstable for now
No
> Allow failure on travis for benchmark 

- test/AmdMainTemplatePlugin.test.js
N/A
**Summary**
Refactor AmdMainTemplatePlugin.test.js to ES6
No
> refactor(ES6): AmdMainTemplatePlugin.test.js

- lib/AsyncDependenciesBlock.js
* refactoring, ES5 => ES6
* replace trailing ',' from chunks ids string passed to `hash()` function in `updateHash()`, if any.
All tests are passing.
N/A
**Summary**
Upgrade the AsyncDependenciesBlock to ES6
NO
> refactor AsyncDependenciesBlock to es6 syntax

- lib/dependencies/CommonJsRequireDependencyParserPlugin.js
N/A
**Summary**
upgrade CommonJsRequireDependencyParserPlugin to ES6
No
> refactor(ES6): upgrade CommonJsRequireDependencyParserPlugin to ES6

- test/CaseSensitiveModulesWarning.test.js
N/A
**Summary**
Refactor CaseSensitiveModulesWarning.test.js to ES6
No
> refactor(ES6): CaseSensitiveModulesWarning.test.js

- lib/dependencies/ImportPlugin.js
N/A
**Summary**
upgrade ImportPlugin to ES6
No
> refactor(ES6): upgrade ImportPlugin to ES6

- test/Compiler-caching.test.js
N/A
**Summary**
Refactor Compiler-caching.test.js to ES6
No
> refactor(ES6): Compiler-caching.test.js

- test/ConfigTestCases.test.js
N/A
**Summary**
Refactor ConfigTestCases.test.js to ES6
No
> refactor(ES6): ConfigTestCases.test.js

- lib/NoEmitOnErrorsPlugin.js
N/A
**Summary**
upgrade NoEmitOnErrorsPlugin to es6
N/A
> refactor(es6) upgrade NoEmitOnErrorsPlugin to ES6 class

- lib/dependencies/AMDPlugin.js
N/A
**Summary**
upgrade AMDPlugin to ES6
No
> refactor(ES6): upgrade AMDPlugin to ES6

- README.md
Clean up minor issues in readme.
N/A
N/A
**Summary**
- Fix links for all plugins / loaders to now route to the proper library and not the image in github.
- Fix alignment in the `Core Team` table
N/A
//cc @TheLarkInn
> docs(readme): fix image urls and core table alignment

- lib/node/NodeWatchFileSystem.js
> refactor(NodeWatchFileSystem): upgrade to ES6

- lib/dependencies/WebpackMissingModule.js
refactor
N/A
**Summary**
upgrade WebpackMissingModule to es6
No
> refactor of WebpackMissingModule to es6

- test/mocha.opts
> Revert "chore(test): skip failure for global var in macaddress"

- lib/dependencies/ImportParserPlugin.js
N/A
**Summary**
upgrade ImportParserPlugin to ES6
No
> refactor(ES6): upgrade ImportParserPlugin to ES6

- lib/dependencies/ModuleDependencyTemplateAsId.js
N/A
**Summary**
upgrade ModuleDependencyTemplateAsId to ES6
No
> refactor(ES6): upgrade ModuleDependencyTemplateAsId to ES6

- lib/dependencies/ModuleDependencyTemplateAsRequireId.js
N/A
**Summary**
upgrade ModuleDependencyTemplateAsRequireId to ES6
No
> refactor(ES6): upgrade ModuleDependencyTemplateAsRequireId to ES6

- lib/DefinePlugin.js
- test/configCases/plugins/define-plugin/index.js
bugfix
yes
N/A
**Summary**
[issue 4000](https://github.com/webpack/webpack/issues/4000#issuecomment-273479707)
> fix DefinePlugin stringifyObj bug

- lib/Compilation.js
- lib/Parser.js
- lib/optimize/RemoveParentModulesPlugin.js
Refactoring
N/A
Summary
Rewrote frequently used forEach and no optimal structure
No
> Optimize Compilation, Parse, RemoveParentModulesPlugin for each to loop and more

- test/WebWorkerHotUpdateChunkTemplatePlugin.test.js
N/A
**Summary**
Refactor WebWorkerHotUpdateChunkTemplatePlugin.test.js to ES6
No
> refactor(ES6): WebWorkerHotUpdateChunkTemplatePlugin.test.js

- test/Errors.test.js
N/A
**Summary**
Refactor Errors.test.js to ES6
No
> refacotr(ES6): Errors.test.js

- lib/FlagDependencyExportsPlugin.js
N/A
**Summary**
upgrade FlagDependencyExportsPlugin to ES6
No
> refactor(ES6): upgrade FlagDependencyExportsPlugin to ES6

- lib/NormalModuleFactory.js
- lib/RuleSet.js
- package.json
- test/RuleSet.test.js
- test/configCases/loaders/generate-ident/index.js
- test/configCases/loaders/generate-ident/loader1.js
- test/configCases/loaders/generate-ident/loader2.js
- test/configCases/loaders/generate-ident/webpack.config.js
feature
yes
not yet
**Summary**
pass ident outside of options object
commit based on work from @timse #4073
no
> generate loader ident automatically

- lib/CompatibilityPlugin.js
N/A
**Summary**
upgrade the CompatibilityPlugin to ES6 
No
> refactor(ES6): upgrade CompatibilityPlugin to ES6

- lib/EvalDevToolModulePlugin.js
All testing tests pass
N/A
**Summary**
upgrade EvalDevToolModuleTemplatePlugin to es6
reopen PR #3870 
N/A
> refactor(es6) upgrade EvalDevToolModuleTemplatePlugin to ES6 class

- test/RequireJsStuffPlugin.test.js
N/A
**Summary**
Refactor RequireJsStuffPlugin.test.js to ES6
No
> refactor(ES6): RequireJsStuffPlugin.test.js

- test/SourceMapDevToolModuleOptionsPlugin.test.js
N/A
**Summary**
Refactor SourceMapDevToolModuleOptionsPlugin.test.js to ES6
No
> refactor(ES6): SourceMapDevToolModuleOptionsPlugin.test.js

- test/Template.test.js
N/A
**Summary**
Refactor Template.test.js to ES6
No
> refactor(ES6): Template.test.js

- test/RecordIdsPlugin.test.js
N/A
**Summary**
Refactor RecordIdsPlugin.test.js to ES6
No
> refactor(ES6): RecordIdsPlugin.test.js

- lib/dependencies/CommonJsPlugin.js
N/A
**Summary**
upgrade CommonJsPlugin to ES6
No
> refactor(ES6): upgrade CommonJsPlugin to ES6

- README.md
Minor documentation fix in README.md
No. I performed a manual  functional test. Link was 404 before, it  works now.
**Summary**
The links to the Vue framework loader's (Loads and compiles Vue Components) Github page was incorrect and leading to a 404.  I felt motivated to try and help by fixing this issue quickly. 
Nope.
Hope this helps.
> Fix link to Vue framework

- test/UglifyJsPlugin.test.js
Tests for UglifyJsPlugin
That's all I did
-nil-
**Summary**
Sets UglifyJsPlugin's coverage to above 80% as mentioned in #3716.
No
> Add test for UglifyJsPlugin

- lib/dependencies/CriticalDependencyWarning.js
> refactor(CriticalDependencyWarning): upgrade to ES6

- lib/DelegatedModuleFactoryPlugin.js
- test/configCases/dll-plugin/0-create-dll/g-loader.js
- test/configCases/dll-plugin/0-create-dll/g.abc.js
- test/configCases/dll-plugin/0-create-dll/webpack.config.js
- test/configCases/dll-plugin/1-use-dll/index.js
- test/configCases/dll-plugin/1-use-dll/webpack.config.js
- test/configCases/dll-plugin/2-use-dll-without-scope/index.js
- test/configCases/dll-plugin/2-use-dll-without-scope/webpack.config.js
bugfix
yes
n/a
**Summary**
fixes a bug with disallows exact match in dll
no
> allow exact match without extension in dll

- lib/optimize/OccurrenceOrderPlugin.js
- test/statsCases/external/expected.txt
- test/statsCases/optimize-chunks/expected.txt
- test/statsCases/separate-css-bundle/expected.txt
- test/statsCases/tree-shaking/expected.txt
bugfix
yes
n/a
**Summary**
return was missing in function
no
> fixes a bug in OccurrenceOrderPlugin

- lib/CaseSensitiveModulesWarning.js
coverage CI fix
N/A
N/A
**Summary**
Ignore sorting because it's non-deterministic
no
> Ignore sorting because it's non-deterministic

- test/statsCases/limit-chunk-count-plugin/a.js
- test/statsCases/limit-chunk-count-plugin/b.js
- test/statsCases/limit-chunk-count-plugin/c.js
- test/statsCases/limit-chunk-count-plugin/d.js
- test/statsCases/limit-chunk-count-plugin/e.js
- test/statsCases/limit-chunk-count-plugin/expected.txt
- test/statsCases/limit-chunk-count-plugin/index.js
- test/statsCases/limit-chunk-count-plugin/webpack.config.js
test
yes
N/A
**Summary**
add limit chunk count plugin test
no
> add limit chunk count plugin test

- lib/node/NodeOutputFileSystem.js
> refactor(NodeOutputFileSystem): upgrade to ES6

- lib/dependencies/LoaderPlugin.js
N/A
**Summary**
upgrade LoaderPlugin to ES6
No
> refactor(ES6): upgrade LoaderPlugin to ES6

- test/Chunk.test.js
N/A
**Summary**
Refactor Chunk.test.js to ES6
No
> refactor(ES6): Chunk.test.js

- test/HotUpdateChunkTemplate.test.js
N/A
**Summary**
Refactor HotUpdateChunkTemplate.test.js to ES6
No
> refactor(ES6): HotUpdateChunkTemplate.test.js

- test/Integration.test.js
N/A
**Summary**
Refactor Integration.test.js to ES6
No
> refactor(ES6): Integration.test.js

- test/JsonpHotUpdateChunkTemplatePlugin.test.js
N/A
**Summary**
Refactor JsonpHotUpdateChunkTemplatePlugin.test.js to ES6
No
> refactor(ES6): JsonpHotUpdateChunkTemplatePlugin.test.js

- test/MultiCompiler.test.js
N/A
**Summary**
Refactor MultiCompiler.test.js to ES6
No
> refactor(ES6): MultiCompiler.test.js

- test/MultiStats.test.js
N/A
**Summary**
Refactor MultiStats.test.js to ES6
No
> refactor(ES6): MultiStats.test.js

- test/MultiWatching.test.js
N/A
**Summary**
Refactor MultiWatching.test.js to ES6
No
> refactor(ES6): MultiWatching.test.js

- test/NodeTemplatePlugin.test.js
N/A
**Summary**
Refactor NodeTemplatePlugin.test.js to ES6
No
> refactor(ES6): NodeTemplatePlugin.test.js

- lib/NoErrorsPlugin.js
N/A
**Summary**
upgrade NoErrorsPlugin to ES6
N/A
> refactor(es6) upgrade NoErrorsPlugin to ES6 class

- test/TestCases.test.js
N/A
**Summary**
Refactor TestCases.test.js to ES6
No
> refactor(ES6): TestCases.test.js

- test/WarnCaseSensitiveModulesPlugin.test.js
N/A
**Summary**
Refactor WarnCaseSensitiveModulesPlugin.test.js to ES6
No
> refactor(ES6): WarnCaseSensitiveModulesPlugin.test.js

- test/WatchDetection.test.js
N/A
**Summary**
Refactor WatchDetection.test.js to ES6
No
> refactor(ES6): WatchDetection.test.js

- test/WatchTestCases.test.js
N/A
**Summary**
Refactor WatchTestCases.test.js to ES6
No
> refactor(ES6): WatchTestCases.test.js

- lib/ModuleBuildError.js
> refactor(ModuleBuildError): upgrade to ES6

- test/Parser.test.js
N/A
**Summary**
Refactor Parser.test.js to ES6
No
> refactor(ES6): Parser.test.js

- test/configCases/plugins/environment-plugin/errors.js
- test/configCases/plugins/environment-plugin/index.js
- test/configCases/plugins/environment-plugin/webpack.config.js
Improve test coverage.
Yes
https://github.com/webpack/webpack/issues/3716
**Summary**
Added tests for the `EnvironmentPlugin` to improve test coverage of this class to 100%.
Improved how the regular expressions of the test's expected errors are defined. Before this change, every time a new environment variable or webpack configuration was added, several errors would need to be added. With this change it should be much easier and less error-prone to add more tests.
No
My first PR 🎉  I'm happy to contribute with this awesome tool 😃
> Test - improve EnvironmentPlugin code coverage

- lib/dependencies/HarmonyExportExpressionDependency.js
- test/cases/parsing/issue-4179/index.js
- test/cases/parsing/issue-4179/module.js
- test/configCases/code-generation/use-strict/index.js
bugfix
yes
N/A
**Summary**
see #4179 add brakets
no
> fixes #4179

- CONTRIBUTING.md
- README.md
- bin/webpack.js
- lib/MovedToPluginWarningPlugin.js
- lib/optimize/AggressiveMergingPlugin.js
- lib/optimize/LimitChunkCountPlugin.js
- lib/optimize/MinChunkSizePlugin.js
- lib/optimize/OccurrenceOrderPlugin.js
Replaces webpack.github.io links with links to the new documentation.
> Link documentation to webpack.js.org

- lib/EvalDevToolModuleTemplatePlugin.js
N/A
**Summary**
Nope
restored from #4098
> refactor(EvalDevToolModuleTemplatePlugin): upgrade to ES6

- lib/WebpackOptionsValidationError.js
- lib/validateSchema.js
- lib/webpack.js
- schemas/ajv.absolutePath.js
- schemas/webpackOptionsSchema.json
- test/Compiler-caching.test.js
- test/Compiler.test.js
- test/Validation.test.js
feature
N/A
N/A
**Summary**
fixes #899
blantantly stolen from @mxstbr PR #2698
and updated to the latest version of webpack. 
Hope this gets through before conflicts :)
No
> fail if the given context is not absolute

- test/Validation.test.js
N/A
**Summary**
Refactor Validation.test.js to ES6
No
> refactor(ES6): Validation.test.js

- test/Examples.test.js
N/A
**Summary**
Refactor Examples.test.js to ES6
No
> refactor(ES6): Examples.test.js

- lib/ModuleNotFoundError.js
N/A
**Summary**
upgrade ModuleNotFoundError to es6
N/A
> refactor(es6) upgrade ModuleNotFoundError to ES6 class

- bin/convert-argv.js
bugfix
no, too difficult
N/A
**Summary**
make CLI passed arguments absolute, so they don't fail on validation
no
> make CLI passed arguments absolute

- examples/chunkhash/README.md
- examples/chunkhash/example.js
- examples/code-splitting-harmony/README.md
- examples/code-splitting-harmony/example.js
- examples/code-splitting-harmony/template.md
- examples/code-splitting-native-import-context/README.md
- examples/harmony/README.md
- examples/harmony/example.js
> Use import() instead of System.import in examples

- test/WebEnvironmentPlugin.test.js
N/A
**Summary**
Refactor WebEnvironmentPlugin.test.js to ES6
No
> refactor(ES6): WebEnvironmentPlugin.test.js

- examples/code-splitting-harmony/README.md
- examples/code-splitting-native-import-context/README.md
- lib/dependencies/ImportContextDependency.js
> Fix name of contexts created using `import()`

- lib/optimize/MinChunkSizePlugin.js
This PR is only for fixing a spelling mistake in the MinChunkSizePlugin :)
> fix spelling error in MinChunkSizePlugin

- lib/Chunk.js
- lib/Module.js
- lib/removeAndDo.js
- test/Chunk.test.js
refactoring
N/A
N/A
**Summary**
Remove some superfluous code and simplify the code a bit to understand whats happening.
Hope this holds true generally and not just for me :)
No
> Cleanup chunk

- schemas/webpackOptionsSchema.json
> Add more granular schema for stats in options schema

- lib/Parser.js
- test/benchmarkCases/large-ast/index.js
- test/benchmarkCases/large-ast/index2.js
- test/benchmarkCases/large-ast/webpack.config.js
- yarn.lock
Refactoring
N/A
**Summary**
Convert multiple forEach statements to for loops. Should yield some strong wins on benchmarking tests
No
Upon doing `yarn` some patch updates came in on install. Thus the yarn update is included but not relevant.
> feat(parser) optimize parse for each to loop

- examples/code-splitted-css-bundle/webpack.config.js
- examples/css-bundle/webpack.config.js
- examples/multiple-entry-points-commons-chunk-css-bundle/webpack.config.js
- test/HotTestCases.test.js
- test/statsCases/separate-css-bundle/webpack.config.js
- yarn.lock
test and dependency update
N/A
N/A
**Summary**
update
no
> updated api for extract-text-webpack-plugin

- lib/NormalModule.js
- test/NormalModule.test.js
refactor
N/A
N/A
**Summary**
refactor NormalModule to es6
No
Some refactorings to split up bigger method bodies in smaller ones. (to make it easier to read for stupid people like me :D )
> Refactor NormalModule to es6

- test/ModuleDependencyError.test.js
- test/NullDependency.test.js
Refactor, ES5 => ES6
N/A
**Summary**
Refactor ModuleDependencyError.test.js
No
> Refactor(ES6): ModuleDependencyError.test.js

- test/NullDependency.test.js
N/A
**Summary**
Refactor NullDependency.test.js to ES6
No
> refactor(ES6):NullDependency.test.js

- lib/RuleSet.js
Refactor
N/A
N/A
**Summary**
Refactors 'lib/RuleSet.js' to es6
No
No
> migrate 'lib/RuleSet.js' to es6

- lib/webworker/WebWorkerChunkTemplatePlugin.js
linting
N/A
**Summary**
No
NIL
> refactor(ES6): WebWorkerChunkPluginTemplate migration

- test/ContextReplacementPlugin.test.js
**Summary**
Increased coverage for ContextReplacementPlugin for the issue  https://github.com/webpack/webpack/issues/3716
No
> Increased coverage on ContextReplacementPlugin

- lib/webworker/WebWorkerMainTemplatePlugin.js
- lib/webworker/WebWorkerTemplatePlugin.js
linting
N/A
**Summary**
No
NIL
> refactor(es6) Webworker module

- lib/MultiModuleFactory.js
Refactor, ES5 => ES6
N/A
N/A
**Summary**
Refactor MultiModuleFactory.js
No
> Refactor(ES6): MultiModuleFactory.js

- lib/RecordIdsPlugin.js
- lib/SizeFormatHelpers.js
- lib/WebpackOptionsApply.js
linting
N/A
**Summary**
No
NIL
> Refactor(ES6) WebpackOptionsApply / sizeFormatHelpers / RecordsIdsPlugin

- lib/webworker/WebWorkerMainTemplatePlugin.js
- lib/webworker/WebWorkerTemplatePlugin.js
linting
N/A
**Summary**
No
NIL
> Refactor webworker var -> const changes

- lib/FunctionModuleTemplatePlugin.js
linting
N/A
**Summary**
No
NIL
> refactor(es6): FunctionModuleTemplatePlugin

- lib/AmdMainTemplatePlugin.js
- lib/ExternalModule.js
- lib/UmdMainTemplatePlugin.js
- lib/dependencies/WebpackMissingModule.js
- test/AmdMainTemplatePlugin.test.js
- test/ExternalModule.test.js
refactor
N/A
N/A
**Summary**
refactor external module to esnext
No
> Refactor externalmodule to es6

- lib/Compilation.js
- lib/Compiler.js
- lib/NormalModuleFactory.js
- lib/RuleSet.js
- schemas/webpackOptionsSchema.json
- test/Validation.test.js
- test/configCases/rule-set/compiler/a.js
- test/configCases/rule-set/compiler/b.js
- test/configCases/rule-set/compiler/index.js
- test/configCases/rule-set/compiler/loader.js
- test/configCases/rule-set/compiler/webpack.config.js
feature
not yet (TODO)
not yet (TODO)
**Summary**
allow to apply plugins to child compiler
allow to match on compiler name in rules
see also #4177
no
> child compiler features

- lib/NullFactory.js
- lib/OptionsApply.js
- lib/ProgressPlugin.js
- lib/ProvidePlugin.js
linting
N/A
**Summary**
No
NIL
> Refactor(ES6): Provide/ Progress Plugin / Options Apply / Null Factory

- lib/EvalSourceMapDevToolModuleTemplatePlugin.js
linting
N/A
**Summary**
No
NIL
> Refactor(ES6): EvalSourceMapDevToolModuleTemplatePlugin

- lib/optimize/CommonsChunkPlugin.js
- test/statsCases/commons-chunk-min-size-0/entry-1.js
- test/statsCases/commons-chunk-min-size-0/expected.txt
- test/statsCases/commons-chunk-min-size-0/modules/a.js
- test/statsCases/commons-chunk-min-size-0/modules/b.js
- test/statsCases/commons-chunk-min-size-0/modules/c.js
- test/statsCases/commons-chunk-min-size-0/modules/d.js
- test/statsCases/commons-chunk-min-size-0/modules/e.js
- test/statsCases/commons-chunk-min-size-0/modules/f.js
- test/statsCases/commons-chunk-min-size-0/webpack.config.js
- test/statsCases/commons-chunk-min-size-Infinity/entry-1.js
- test/statsCases/commons-chunk-min-size-Infinity/expected.txt
- test/statsCases/commons-chunk-min-size-Infinity/modules/a.js
- test/statsCases/commons-chunk-min-size-Infinity/modules/b.js
- test/statsCases/commons-chunk-min-size-Infinity/modules/c.js
- test/statsCases/commons-chunk-min-size-Infinity/modules/d.js
- test/statsCases/commons-chunk-min-size-Infinity/modules/e.js
- test/statsCases/commons-chunk-min-size-Infinity/modules/f.js
- test/statsCases/commons-chunk-min-size-Infinity/webpack.config.js
refactor
N/A
N/A
**Summary**
split up commons chunk plugin in smaller readable chunks
No
should `reallyUsedChunks` be used here: https://github.com/webpack/webpack/pull/4310/commits/77df15529805737d8f4653e5f991dc7523b389d9#diff-1f5e5440c51d8accc603eb6f399cf08bR324 ? 
@sokra
> Cleanup commons chunk plugin

- .travis.yml
- appveyor.yml
CI
N/A
N/A
**Summary**
benchmarking is too unstable
disable it for now, wait for bench.ci
no
> disable benchmarking

- test/NodeWatchFileSystem.test.js
- test/statsCases/separate-css-bundle/expected.txt
- yarn.lock
> update yarn lockfile

- lib/Parser.js
- test/cases/parsing/issue-4357/a.js
- test/cases/parsing/issue-4357/b.js
- test/cases/parsing/issue-4357/index.js
- test/cases/parsing/issue-4357/test.filter.js
- test/helpers/supportsObjectDestructuring.js
bugfix
yes
N/A
**Summary**
see #4357
no
> walk variable patterns for parsed stuff

- bin/config-optimist.js
- examples/README.md
- test/browsertest/middlewareTest.js
clean up
N/A
N/A
**Summary**
cleans up leftovers of the labeled module
No
fixes #4354
> remove labeled modules leftovers

- lib/LibraryTemplatePlugin.js
Refactor `libraryTemplatePlugin` to ES2015
No change in logic, tests passed locally.
**Summary**
Motivation is to move to es2015 class.
No breaking changes.
> refactor libraryTemplatePlugin to es2015 class

- lib/ExtendedAPIPlugin.js
Refactor
N/A - no new functionality.
N/A
**Summary**
Refactor `ExtendedAPIPlugin.js` to ES 2015.
No
> Refactor ExtendedAPIPlugin in ES6

- lib/dependencies/LocalModulesHelpers.js
- test/LocalModulesHelpers.test.js
> refactor(LocalModulesHelpers): upgrade to ES6

- test/HotTestCases.test.js
N/A
**Summary**
Refactor HotTestCases.test.js to ES6
No
> refactor(ES6): HotTestCases.test.js

- test/JsonpExportMainTemplatePlugin.test.js
N/A
**Summary**
Refactor JsonpExportMainTemplatePlugin.test.js to ES6
No
> refactor(ES6): JsonpExportMainTemplatePlugin.test.js

- test/RawModule.test.js
N/A
**Summary**
Refactor RawModule.test.js to ES6
No
> refactor(ES6): RawModule.test.js

- test/NodeHotUpdateChunkTemplatePlugin.test.js
N/A
**Summary**
Refactor NodeHotUpdateChunkTemplatePlugin.test.js to ES6
No
> refactor(ES6): NodeHotUpdateChunkTemplatePlugin.test.js

- lib/ContextModule.js
refactor context module to esnext
N/A
N/A
**Summary**
refactor context module to esnext and split up in smaller methods to make it easier to reason about.
No
> Refactor contextmodule to es6

- test/RuleSet.test.js
N/A
**Summary**
Refactor RuleSet.test.js to ES6
No
> refactor(ES6): RuleSet.test.js

- lib/DelegatedModuleFactoryPlugin.js
linting
N/A
**Summary**
No
NIL
> Refactor(ES6): DelegatedModuleFactoryPlugin

- lib/AmdMainTemplatePlugin.js
- lib/BasicEvaluatedExpression.js
- lib/Chunk.js
- lib/Compilation.js
refactoring
I didn't add new test cases. All existing tests are passed.
N/A
**Summary**
In shortly, consistent code base. I've updated variable declarations according to ES6. Related issue is #4099.
It doesn't introduce any breaking change.
I've worked on these files;
lib/AmdMainTemplatePlugin.js
lib/BasicEvaluatedExpression.js
lib/Chunk.js
lib/Compilation.js
> Update variable declarations

- test/DependenciesBlockVariable.test.js
N/A
**Summary**
Refactor DependenciesBlockVariable.test.js to ES6
No
> refactor(ES6): DependenciesBlockVariable.test.js

- test/HotModuleReplacementPlugin.test.js
N/A
**Summary**
Refactor HotModuleReplacementPlugin.test.js to ES6
No
> refactor(ES6): HotModuleReplacementPlugin.test.js

- lib/AsyncDependenciesBlock.js
- lib/dependencies/AMDDefineDependencyParserPlugin.js
N/A
**Summary**
upgrade AMDDefineDependencyParserPlugin to ES6
No
> refactor(ES6): upgrade AMDDefineDependencyParserPlugin to ES6

- README.md
readme
N/A
N/A
**Summary**
add other sponsors and backers
no
> add other sponsors and backers

- lib/ContextReplacementPlugin.js
Refactoring
No added tests, all current tests still pass.
N/A
**Summary**
Updates to make the codebase a bit more consistent with ES6 standards. This is based on issue https://github.com/webpack/webpack/issues/4099
No breaking changes.
First PR to webpack 🎉
> ES6ify the ContextReplacementPlugin

- lib/MultiModule.js
> refactor(MultiModule): upgrade to ES6

- test/WebpackMissingModule.test.js
Unit tests and increase code coverage
N/A
**Summary**
Adding missed unit tests
Nope
> test(WebpackMissingModule): adding unit tests

- lib/MultiStats.js
- test/MultiStats.test.js
Refactor code to es2015
no logic change - run the tests locally and passed.
**Summary**
I extend MultiStats from Stats to resolve the usage of toString - hopefully thats accepted solution.
no
> refactor MultiStats to es2015

- lib/FlagDependencyExportsPlugin.js
refactoring
N/A
N/A
**Summary**
reduces time spent in `FlagDependencyExportsPlugin` by roughly 97%
No
fixes #4478
probably not the nicest code, but the whole `FlagDependencyExportsPlugin` needs a proper refactor i guess
> Improve performance flag dependency exports plugin

- README.md
> [DO NOT MERGE] add ag-grid banner to readme

- README.md
> Use ts-loader instead of deprecated typescript-loader in Readme.md

- lib/JsonpMainTemplatePlugin.js
- test/statsCases/aggressive-splitting-on-demand/expected.txt
- test/statsCases/chunks/expected.txt
- test/statsCases/commons-chunk-min-size-0/expected.txt
- test/statsCases/limit-chunk-count-plugin/expected.txt
- test/statsCases/optimize-chunks/expected.txt
- test/statsCases/preset-verbose/expected.txt
bugfix
no, we have no IE in CI
N/A
**Summary**
IE executes script very early when cached
fixes #4472
no
> install Promise early in chunk cache

- lib/optimize/MinChunkSizePlugin.js
- test/configCases/plugins/min-chunk-size/a.js
- test/configCases/plugins/min-chunk-size/b.js
- test/configCases/plugins/min-chunk-size/index.js
- test/configCases/plugins/min-chunk-size/webpack.config.js
bugfix
yes
N/A
**Summary**
fix #4532
no
> fix bug in MinChunkSizePlugin

- schemas/ajv.absolutePath.js
- test/Validation.test.js
> fix extra newline in validation

- README.md
Fixed the broken URL to the Traceur repo.
Not applicable.
Not applicable.
**Summary**
Minor README bugfix.
No.
None.
> Fixed link to the Traceur repo in README

- lib/ErrorHelpers.js
- lib/ModuleBuildError.js
- lib/ModuleError.js
- lib/ModuleWarning.js
- lib/NormalModule.js
- test/cases/errors/loader-error-warning/errors.js
- test/cases/errors/loader-error-warning/warnings.js
bugfix and feature
yes
N/A
**Summary**
add stack to non-Error error emitted
add info about emitting an Error
no
> add stack to non-Error error emitted

- package.json
- yarn.lock
bugfix
yes
N/A
**Summary**
see #4550
no
> update webpack-sources dependency to avoid performance issue

- schemas/ajv.absolutePath.js
No there seems to be no test case  in `Validation.test.js`
**Summary**
My motivation is to give people the opportunity to experience webpack on Windows aswell 😛 :D 
#4530, #4549, #4552
No
Closes #4530, #4549, #4552
> fix(schema/absolutePaths): make absolute paths case insensitive

- lib/WebpackOptionsValidationError.js
- test/Validation.test.js
developer xp
yes
N/A
**Summary**
fixes #4551
thanks to @actuallymentor
no
> Suggest course of action

- package.json
- yarn.lock
bugfix
yes
N/A
**Summary**
dep update
no
> update webpack-sources dependency to fix a bug

- lib/EntryModuleNotFoundError.js
Refactor
No added tests, all current tests still pass.
N/A
**Summary**
Updates to make the codebase a bit more consistent with ES6 standards. This is based on issue #4099
No breaking changes.
Right before I went to open this PR, I saw that this had been opened, but still needed some work: https://github.com/webpack/webpack/pull/4361
I wasn't sure what the usual etiquette for this would be - should I assume this file to already have been worked on and close this PR? Or offer to help with the other PR?
Additionally, would it help if I added a comment here …
> ES6ify EntryModuleNotFoundError

- README.md
It just adds the riot webpack loader link to the readme file
No why should I? :D 
naa
**Summary**
As I already said before it just add the riot.js webpack loader link to the readme file nothing more nothing less
I guess not, unless webpack relies somewhere on its own `readme.md` file
Peace and love and keep up this awesome project
> Add the riot official webpack loader

- lib/DelegatedModule.js
ES6 Refactor
No added tests, all current tests still pass.
N/A
**Summary**
Updates to make the codebase a bit more consistent with ES6 standards. This is based on issue #4099 
No breaking changes.
There's also this PR open https://github.com/webpack/webpack/pull/4345, though I'm not sure if it's still being worked on.
> ES6 refactor of DelegatedModule

- lib/Stats.js
- schemas/webpackOptionsSchema.json
- test/statsCases/filter-warnings/a.js
- test/statsCases/filter-warnings/expected.txt
- test/statsCases/filter-warnings/index.js
- test/statsCases/filter-warnings/webpack.config.js
feature
Yes
TBD
**Summary**
Allows to filter which warnings are to be shown.
No
fixes #4263
> Add suppress warnings functionality

- lib/NormalModuleFactory.js
- lib/RecordIdsPlugin.js
- test/RecordIdsPlugin.test.js
- test/configCases/records/issue-2991/pkgs/somepackage/package.json
- test/configCases/records/issue-2991/test.js
- test/configCases/records/issue-2991/webpack.config.js
bugfix
Yes
N/A
**Summary**
Based on #3147 which seams to not get updated, fixes #2991
No?
is it ok to add a plugin to the webpack config in the test, to create that case? @sokra 
Using webpack.IgnorePlugin or the lake wouldnt trigger a record entry.
> Make ignored relative

- lib/ExtendedAPIPlugin.js
- test/configCases/parsing/extended-api/index.js
- test/configCases/parsing/extended-api/webpack.config.js
Feature
No. There are currently no tests for this plugin and I'm not comfortable enough with this project to write them from scratch. I could use some help on this point.
**Summary**
Make ExtendedAPIPlugin expose `chunkname`, same way as `hash`.
Should not.
> Feature: Make ExtendedAPIPlugin expose chunkname.

- .editorconfig
- open-bot.yaml
bot
a bit
N/A
**Summary**
see comments
no
> Improved bot

- lib/JsonpMainTemplatePlugin.js
- lib/ModuleFilenameHelpers.js
- lib/NodeStuffPlugin.js
linting
N/A
**Summary**
No
NIL
> Refactor NodestuffPlugin / JsonpMainTemplatePlugin / ModuleFilenameHelpers

- examples/build-common.js
- examples/chunkhash/README.md
- examples/template-common.js
documnetation fix in example
no
N/A
**Summary**
fixes #4396
no
> generate correct chunkhash configuration in example

- lib/MainTemplate.js
Just a cosmetic change here, starting small. Hope to be able to make larger contributions down the line! No breaking here, no tests needed.
> Template strings in MainTemplate file

- lib/SourceMapDevToolPlugin.js
bugfix
TODO
N/A
**Summary**
see #4086
no
> fixes #4086

- open-bot.yaml
bot
no
no
**Summary**
try to make the bot less spammy
no
> minor fixes in bot configuration

- open-bot.yaml
bot
no
no
**Summary**
add "PR: conflict" when pull request is in conflicted state
no
> add "PR: conflict" when pull request is in conflicted state

- lib/dependencies/ContextDependencyHelpers.js
> refactor(ES6): contextDependencyHelper

- open-bot.yaml
After discussion with @sokra.
Bot tweak.
No.
**Summary**
> More fair bot message

- lib/AutomaticPrefetchPlugin.js
- lib/CachePlugin.js
- lib/Compilation.js
- lib/ContextModuleFactory.js
- lib/LibManifestPlugin.js
- lib/MultiCompiler.js
- lib/MultiWatching.js
- lib/NormalModuleFactory.js
- test/BenchmarkTestCases.benchmark.js
> refactor(es6): LibManifestPlugin

- open-bot.yaml
bot
no
no
**Summary**
report CI also for appveyor
merge rules
more detailed message for missing tests
remove other labels on conflict
less thanks messages
reorder rules, remove sokra rule
no
> fixes to the bot

- test/Compiler-caching.test.js
test
yes
n/a
**Summary**
add timeout to test to make it stable
see #3545 
no
> make flanky test stable

- test/WebWorkerMainTemplatePlugin.test.js
> refactoring WebWorkerMainTemplatePlugin.test.js to ES6

- test/checkArrayExpectation.js
> Refactor CheckArrayExpectation to ES6

- test/Compiler-caching.test.js
Reverts webpack/webpack#3547
It's not stable...
> Revert "make flanky test stable"

- test/identifier.test.js
test bugfix
its a test
N/A
**Summary**
fixes wrongly introduced tests in #4646 
no
PTAL @sokra
> move and fix tests

- lib/util/identifier.js
- test/identifier.test.js
follow up
N/A
N/A
**Summary**
fixates the expected paths, making sure it looks the same for all OS
No
follow up on #4654
> make paths for records agnostic of OS

- open-bot.yaml
bot
N/A
N/A
**Summary**
add move command for issues
add detailed travis report
no
> move command and travis report

- open-bot.yaml
bot
yes
N/A
**Summary**
bug in move script
no
> fix bot script

- open-bot.yaml
bot
no
N/A
**Summary**
fix espacing when moving issue
no
> fix espacing when moving issue

- test/Stats.test.js
continuation
Yes
N/A
**Summary**
continuation of #4048
No
> Refactor test stats

- test/Stats.test.js
N/A
**Summary**
Refactor Stats.test.js to ES6
No
> refactor(ES6): Stats.test.js

- lib/IgnorePlugin.js
- test/configCases/ignore/only-resource-context/src/ignored-module.js
- test/configCases/ignore/only-resource-context/src/normal-module.js
- test/configCases/ignore/only-resource-context/test.js
- test/configCases/ignore/only-resource-context/webpack.config.js
- test/configCases/ignore/only-resource/ignored-module.js
- test/configCases/ignore/only-resource/normal-module.js
- test/configCases/ignore/only-resource/test.js
- test/configCases/ignore/only-resource/webpack.config.js
- test/configCases/ignore/resource-and-context-contextmodule/folder-a/ignored-module.js
- test/configCases/ignore/resource-and-context-contextmodule/folder-a/normal-module.js
- test/configCases/ignore/resource-and-context-contextmodule/folder-b/ignored-module.js
- test/configCases/ignore/resource-and-context-contextmodule/folder-b/normal-module.js
- test/configCases/ignore/resource-and-context-contextmodule/folder-b/only-context-match-require.js
- test/configCases/ignore/resource-and-context-contextmodule/folder-b/only-context-match.js
- test/configCases/ignore/resource-and-context-contextmodule/test.js
- test/configCases/ignore/resource-and-context-contextmodule/webpack.config.js
- test/configCases/ignore/resource-and-context/folder-a/ignored-module.js
- test/configCases/ignore/resource-and-context/folder-a/normal-module.js
- test/configCases/ignore/resource-and-context/folder-b/ignored-module.js
- test/configCases/ignore/resource-and-context/folder-b/normal-module.js
- test/configCases/ignore/resource-and-context/folder-b/only-context-match-require.js
- test/configCases/ignore/resource-and-context/folder-b/only-context-match.js
- test/configCases/ignore/resource-and-context/test.js
- test/configCases/ignore/resource-and-context/webpack.config.js
bugfix
Yes
N/A
**Summary**
based on #4418 adds tests, little refactor.
No
Github doesnt allow me to add to this PR, nor to open a PR against the existing PR. :(
> Ignore plugin hotfix - continuation of 4418

- benchmark/createFixtures2.js
- test/BinTestCases.test.js
- test/cases/chunks/runtime/index.js
- test/cases/loaders/issue-2299/loader/index.js
refactoring
No
N/A
**Summary**
rename variables from `async` to future proof names
No
based on review feedback from #3166
> Rename async for future compatibility

- lib/Parser.js
Refactoring of Webpack Core
No, all current tests still pass
**Summary**
More ES6 code in Webpack Core (`Parser`)
Inspired #4099
No
> ES6 refactoring in Parser

- lib/SourceMapDevToolPlugin.js
N/A
**Summary**
Nope
Ping @sokra @TheLarkInn
> refactor(SourceMapDevToolPlugin): upgrade to ES6

- lib/Parser.js
bugfix
no
N/A
**Summary**
fixes misstake while es6 refactoring
add support for other variable declarations
no (it reverts a previous one
> parser refactoring bugfix

- examples/source-map/README.md
- examples/source-map/build.js
- examples/source-map/example.coffee
- examples/source-map/template.md
- examples/source-map/webpack.config.js
Add example
n/a
n/a (is part of documentation)
**Summary**
This increases the understanding of devtool/source-maps. Some relevant documentation issues: https://github.com/webpack/webpack.js.org/issues/273, https://github.com/webpack/webpack.js.org/issues/971
No
> Add example demonstrating all source-map variants

- lib/Parser.js
- test/Parser.test.js
- test/cases/parsing/class/a.js
- test/cases/parsing/class/index.js
- test/cases/parsing/class/module.js
- test/cases/parsing/class/test.filter.js
tests + bugfix
yes
N/A
**Summary**
more tests
no
> add test cases and fix a bug

- lib/Parser.js
- test/Parser.test.js
- test/cases/parsing/issue-4608-1/index.js
- test/cases/parsing/issue-4608-2/index.js
- test/cases/parsing/issue-4608-2/test.filter.js
- test/cases/parsing/issue-4608/index.js
- test/helpers/supportsForOf.js
bugfix
yes
N/A
**Summary**
fixes #4608
I hope no
> add parser prewalking to capture scope

- lib/APIPlugin.js
- lib/ChunkTemplate.js
- lib/Compiler.js
- lib/Dependency.js
- lib/FlagDependencyUsagePlugin.js
- lib/ModuleFilenameHelpers.js
- lib/SetVarMainTemplatePlugin.js
- lib/SourceMapDevToolPlugin.js
- lib/Stats.js
- lib/TemplatedPathPlugin.js
- lib/WebpackOptionsApply.js
- lib/dependencies/AMDPlugin.js
- lib/dependencies/HarmonyExportDependencyParserPlugin.js
refactoring
No
No
**Summary**
From https://github.com/ts-webpack/webpack, it reports a bunch of errors by the typescript type system.
There includes unmatched type errors and unresolved properties errors.
Also, when I'm improving the typings of webpack, I find out some typos and unused codes.
So, i pick out those problems worth fixing, fix it and make this PR.
Nope
> [Refactor] clean the code

- lib/Parser.js
- test/cases/parsing/issue-4709/index.js
bugfix
yes
N/A
**Summary**
fixes #4709
no
> prewalk a function declaration

- README.md
Documentation changes
- Improves sentence structure
N/A
N/A
**Summary**
This PR makes a small change to the documentation under [other backers and sponsors](https://github.com/webpack/webpack#other-backers-and-sponsors). Small sentence restructuring that improves the readability of the sentence, and IMO, conveys the message better.
No
> Improve sentence structure. Closes #4724.

- examples/common-chunk-and-vendor-chunk/README.md
- examples/common-chunk-and-vendor-chunk/template.md
Fix indentations in documentation of examples.
N/A.
N/A
**Summary**
The indentation is wrong, making it difficult to read.
No
> Fix indentation

- lib/DelegatedModule.js
bugfix
no
N/A
**Summary**
add missing semicolon
no
> add missing semicolon

- lib/formatLocation.js
N/A
**Summary**
Nope
Ping @sokra @TheLarkInn
> refactor(formatLocation): upgrade to ES6

- lib/Compilation.js
- lib/Compiler.js
based off of #3933 but could be made independent.
refactoring
No
N/A
**Summary**
Simplify the _done method of Watching in Compiler
No
> Refactor _done of Watching in compiler

- lib/IgnorePlugin.js
typo fix
No
**Summary**
Fixes a typo in IgnorePlugin. Stumbled upon it while I was debugging this issue https://github.com/webpack/webpack/issues/4721.
No
> Fix typo in IgnorePlugin

- test/configCases/commons-chunk-plugin/move-entry/a.js
- test/configCases/commons-chunk-plugin/move-entry/index.js
- test/configCases/commons-chunk-plugin/move-entry/test.config.js
- test/configCases/commons-chunk-plugin/move-entry/webpack.config.js
testcase
yes
N/A
**Summary**
see also #4795
no
> add testcase for moving entry modules into the commons chunk

- lib/optimize/CommonsChunkPlugin.js
- test/configCases/commons-chunk-plugin/extract-async-from-entry/index.js
- test/configCases/commons-chunk-plugin/extract-async-from-entry/test.config.js
- test/configCases/commons-chunk-plugin/extract-async-from-entry/webpack.config.js
bugfix
yes
N/A
**Summary**
fixes #4795
no
> CommonsChunkPlugin in async mode doesn't select initial chunks

- lib/dependencies/HarmonyCompatibilityDependency.js
- lib/dependencies/HarmonyExportDependencyParserPlugin.js
- test/cases/parsing/harmony-export-hoist/bar.js
- test/cases/parsing/harmony-export-hoist/foo.js
- test/cases/parsing/harmony-export-hoist/index.js
bugfix
yes
N/A
**Summary**
fixes #4753
no
> hoist exports

- lib/node/NodeSourcePlugin.js
ES6 Refactor
No
N/A
**Summary**
The Refactoring makes the code more consistent to the ES6 standards. issue #4099
No
It's my first Contribution to Webpack. Maybe this little fun hack helps other people to find es5 code https://github.com/Orlandster98/es5-finder
You can just change the path or es5 and es6 keywords in the code.
> ES6 refactor of NodeSourcePlugin

- lib/JsonpMainTemplatePlugin.js
- lib/WebpackOptionsDefaulter.js
- schemas/webpackOptionsSchema.json
feature
No tests for options, except schema
In progress
**Summary**
User has no ability to configure chunkLoadTimeout option, since it's missed in schema
No
> make chunkLoadTimeout option configurable

- appveyor.yml
CI
The CI will do
N/A
**Summary**
yarn link fails with weird error, but will works
no
> Workaround for weird yarn link behavior

- examples/common-chunk-and-vendor-chunk/README.md
- examples/common-chunk-and-vendor-chunk/template.md
Typo fix
No, readme changes only
**Summary**
Fix typo in `examples/common-chunk-and-vendor-chunk/README.md`
"it it" => "it in"
No
> Typo in examples common chunk

- lib/Compilation.js
- lib/Module.js
- lib/ModuleFilenameHelpers.js
- lib/Stats.js
- lib/optimize/OccurrenceOrderPlugin.js
- lib/optimize/RemoveParentModulesPlugin.js
performance refactoring
yes
N/A
**Summary**
changes array to Set when appropriate for performance
yes
> Performance by using Set instead of Arrays

- examples/chunkhash/README.md
- examples/chunkhash/template.md
typo fix
No, only changes `README.md` and `template.md`
**Summary**
Change `archieved` to `achieved` in `examples/chunkhash/template.md` and `examples/chunkhash/README.md`
No
> archieved —> achieved

- lib/Chunk.js
- lib/Compilation.js
- lib/HotModuleReplacementPlugin.js
- lib/LibManifestPlugin.js
- lib/Module.js
- lib/Stats.js
- lib/UmdMainTemplatePlugin.js
- lib/optimize/AggressiveSplittingPlugin.js
- lib/optimize/CommonsChunkPlugin.js
- lib/optimize/FlagIncludedChunksPlugin.js
code improvements
no
n/a
**Summary**
from review by @Kovensky
no
> improve a few issues in next branch

- lib/Parser.js
- test/cases/parsing/issue-3273/index.js
- test/cases/parsing/issue-4870/file.js
- test/cases/parsing/issue-4870/index.js
- test/cases/parsing/issue-4870/test.filter.js
bugfix
yes
N/A
**Summary**
fixes #4870
no
> support destructing on assignment

- lib/dependencies/RequireEnsureDependenciesBlock.js
- test/cases/chunks/var-inject-error-handler/index.js
> fix variable injection in require.ensure

- test/browsertest/lib/index.web.js
- test/cases/parsing/harmony-commonjs-mix/module1.js
- test/cases/parsing/issue-3917/index.js
bugfix
test changes
N/A
**Summary**
fix browsertests
no
> fix browsertests

- lib/HotModuleReplacement.runtime.js
- lib/HotModuleReplacementPlugin.js
- lib/JsonpMainTemplate.runtime.js
- lib/webworker/WebWorkerMainTemplate.runtime.js
- test/WebWorkerMainTemplatePlugin.test.js
Feature
Changed existed one
N/A
**Summary**
Trying to solve this https://github.com/webpack/webpack/issues/1700
Nope
> Make HMR request timeout configurable

- appveyor.yml
- ci/travis-install.sh
CI
yes
N/A
**Summary**
CI fails if yarn.lock was not updated by PR
no
> use frozen lockfile to fail on outdated yarn.lock

- yarn.lock
CI
yes
N/A
**Summary**
yarn upgrade
no
> upgrade yarn lock

- package.json
- yarn.lock
CI
CI
N/A
**Summary**
update dependencies
no
> update ajv dependency

- test/WatcherEvents.test.js
> add timeout and code style

- bin/webpack.js
- lib/FunctionModuleTemplatePlugin.js
- lib/Module.js
- lib/ProgressPlugin.js
- lib/Stats.js
- lib/optimize/ConcatenatedModule.js
- lib/optimize/ModuleConcatenationPlugin.js
- schemas/webpackOptionsSchema.json
- test/Stats.test.js
- test/cases/scope-hoisting/intra-references/a.js
- test/cases/scope-hoisting/intra-references/b.js
- test/cases/scope-hoisting/intra-references/c.js
- test/cases/scope-hoisting/intra-references/index.js
yes
N/A
**Summary**
fix issues with scope hoisting
report optimization bailout reasons
maybe
> Scope Hoisting Part 2

- lib/optimize/ConcatenatedModule.js
- test/cases/scope-hoisting/renaming-4967/file1.js
- test/cases/scope-hoisting/renaming-4967/index.js
- test/cases/scope-hoisting/renaming-4967/module.js
bugfix
yes
N/A
**Summary**
detect conflicts with other variables
no
> detect conflicts with other variables

- package.json
yes
N/A
**Summary**
more memory for the tests
> more memory for the tests

- package.json
CI
CI
N/A
**Summary**
mocha doesn't support the underscored argument
no
> fix issue with mocha

- lib/optimize/AggressiveMergingPlugin.js
Hey, this change was suggested by @sokra and solves my issues with child compliers. I'm not sure if there is a reason it wasn't committed or upstreamed already. Getting this merged soon would be great. Thanks
> Upstream changes to fix child compiler modules

- lib/Chunk.js
- lib/optimize/EnsureChunkConditionsPlugin.js
- lib/optimize/MergeDuplicateChunksPlugin.js
refactoring
no new tests
N/A
**Summary**
use Map and move stuff
no
> optimize optimization plugins

- lib/optimize/AggressiveSplittingPlugin.js
bugfix
no
N/A
**Summary**
https://github.com/jantimon/html-webpack-plugin/pull/670#issuecomment-301484908
no
> followup from #4968

- lib/WebpackOptionsApply.js
- lib/WebpackOptionsDefaulter.js
- lib/dependencies/RequireContextPlugin.js
- test/cases/context/issue-3873/index.js
- test/cases/context/issue-3873/module/index.js
bugfix
yes
N/A
**Summary**
allow context to resolve to index.js files
fixes #3873
no
> allow context to resolve to index.js files

- lib/BasicEvaluatedExpression.js
- lib/DefinePlugin.js
- lib/HotModuleReplacementPlugin.js
- lib/NodeStuffPlugin.js
- lib/ParserHelpers.js
- lib/dependencies/AMDPlugin.js
- lib/dependencies/CommonJsPlugin.js
- test/cases/parsing/issue-4596/index.js
bugfix
yes
N/A
**Summary**
evaluate some identifiers to truthy values
fixes #4596
no
> evaluate some identifiers to truthy values

- lib/Module.js
- test/statsCases/commons-plugin-issue-4980/constants.js
- test/statsCases/commons-plugin-issue-4980/entry-1.js
- test/statsCases/commons-plugin-issue-4980/entry-2.js
- test/statsCases/commons-plugin-issue-4980/expected.txt
- test/statsCases/commons-plugin-issue-4980/submodule-a.js
- test/statsCases/commons-plugin-issue-4980/submodule-b.js
- test/statsCases/commons-plugin-issue-4980/submodule-c.js
- test/statsCases/commons-plugin-issue-4980/webpack.config.js
bug fix for https://github.com/webpack/webpack/issues/4980,
most likely also fix for https://github.com/webpack/webpack/issues/4846 (need to test it)
yes
No
No
> changing importing order for named and default exports affects common chunk chunkhash

- lib/SourceMapDevToolPlugin.js
- test/configCases/source-map/source-map-filename-contenthash/index.js
- test/configCases/source-map/source-map-filename-contenthash/webpack.config.js
Feature
Yes
Replaces https://github.com/webpack/webpack/pull/4137
**Summary**
The PR is based on a useful feature introduced by the aforementioned PR, but that PR was not updated to address PR concerns. I am trying to finish the work started.
No breaking changes. Only augmentation.
Tried to [contact author](https://github.com/uncleyo/webpack/pull/1) of [original PR](https://github.com/webpack/webpack/pull/4137) but no response. I prefer to get this in sooner than later.
> Cache bust source map fixup

- lib/NormalModule.js
- schemas/webpackOptionsSchema.json
- test/configCases/no-parse/module.exports/webpack.config.js
- test/configCases/no-parse/no-parse-function/index.js
- test/configCases/no-parse/no-parse-function/not-parsed-a.js
- test/configCases/no-parse/no-parse-function/not-parsed-b.js
- test/configCases/no-parse/no-parse-function/webpack.config.js
> Adding function support to noParse

- lib/SourceMapDevToolPlugin.js
bugfix
no
N/A
**Summary**
fixup for source-map contenthash
no
> fixup for source-map contenthash

- lib/optimize/ConcatenatedModule.js
> libIdent should be rootModule

- bin/webpack.js
bugfix
no
N/A
**Summary**
fix issue with --display-modules and --optimization-bailout
was merged incorrectly
no
> fix issue with --display-modules and --optimization-bailout

- lib/optimize/ConcatenatedModule.js
- test/cases/scope-hoisting/inside-class/first.js
- test/cases/scope-hoisting/inside-class/index.js
- test/cases/scope-hoisting/inside-class/second.js
- test/cases/scope-hoisting/inside-class/test.filter.js
bugfix
yes
N/A
**Summary**
class inner scopes are also renamed
no
> fixes #5000

- lib/Module.js
bugfix
no
N/A
**Summary**
this is undefined in arrow function
no
> fixes incorrect deprecation

- examples/scope-hoisting/README.md
- lib/optimize/ConcatenatedModule.js
- test/cases/scope-hoisting/issue-5020-minimal/index.js
- test/cases/scope-hoisting/issue-5020-minimal/src/icon/index.js
- test/cases/scope-hoisting/issue-5020-minimal/src/icon/svg/index.js
- test/cases/scope-hoisting/issue-5020-minimal/src/icon/svg/svg1.js
- test/cases/scope-hoisting/issue-5020-minimal/src/index.js
- test/cases/scope-hoisting/issue-5020/index.js
- test/cases/scope-hoisting/issue-5020/src/icon/index.js
- test/cases/scope-hoisting/issue-5020/src/icon/svg/index.js
- test/cases/scope-hoisting/issue-5020/src/icon/svg/svg1.js
- test/cases/scope-hoisting/issue-5020/src/icon/svg/svg2.js
- test/cases/scope-hoisting/issue-5020/src/icon1/index.js
- test/cases/scope-hoisting/issue-5020/src/icon1/svg/index.js
- test/cases/scope-hoisting/issue-5020/src/icon1/svg/svg1.js
- test/cases/scope-hoisting/issue-5020/src/icon1/svg/svg2.js
- test/cases/scope-hoisting/issue-5020/src/index.js
bugfix
yes
N/A
**Summary**
see #5020
no
> Bugfix scope hoisting ns object

- lib/Stats.js
> default chunk modules in Stats to true

- lib/EvalSourceMapDevToolModuleTemplatePlugin.js
bugfix/workaround
no
N/A
**Summary**
breakpoints now work fine
no
> chrome workaround for eval-source-maps

- lib/Compilation.js
optimization
existing tests
N/A
**Summary**
parent-child-dependencies are more optimized
no
> avoid creating recursive chunk references

- lib/optimize/CommonsChunkPlugin.js
> add special case for async without name

- bin/webpack.js
- examples/build-common.js
> minor fixes

- lib/optimize/ConcatenatedModule.js
- test/cases/scope-hoisting/renaming-shorthand-5027/file1.js
- test/cases/scope-hoisting/renaming-shorthand-5027/file2.js
- test/cases/scope-hoisting/renaming-shorthand-5027/file3.js
- test/cases/scope-hoisting/renaming-shorthand-5027/file4.js
- test/cases/scope-hoisting/renaming-shorthand-5027/index.js
- test/cases/scope-hoisting/renaming-shorthand-5027/module.js
- test/cases/scope-hoisting/renaming-shorthand-5027/test.filter.js
bugfix
yes
N/A
**Summary**
fixes #5027
no
> rename shorthand properties correctly

- lib/dependencies/ImportPlugin.js
If I am wrong, please let me know.
slightly adjust how to resolve normalModuleFactory variable.
Sorry, no
No
**Summary**
reduce the code size 😉
No
Thanks
> use the declared normalModuleFactory variable

- lib/MultiCompiler.js
Refactoring 'lib/MultiCompiler.js' to use ES6 syntax
Tests were already written for MultiCompiler. Changes added with no breaking tests.
**Summary**
As per issue:
https://github.com/webpack/webpack/issues/4099
I refactored the MultiCompiler module to use ES6 syntax while following the linter and style guide.
> 4099_ES6 refactor lib/MultiCompiler.js

- lib/Compilation.js
- lib/FlagDependencyExportsPlugin.js
- lib/Module.js
- lib/Stats.js
- lib/optimize/ModuleConcatenationPlugin.js
- test/statsCases/scope-hoisting-multi/common.js
- test/statsCases/scope-hoisting-multi/common2.js
- test/statsCases/scope-hoisting-multi/common_lazy.js
- test/statsCases/scope-hoisting-multi/common_lazy_shared.js
- test/statsCases/scope-hoisting-multi/expected.txt
- test/statsCases/scope-hoisting-multi/first.js
- test/statsCases/scope-hoisting-multi/lazy_first.js
- test/statsCases/scope-hoisting-multi/lazy_second.js
- test/statsCases/scope-hoisting-multi/lazy_shared.js
- test/statsCases/scope-hoisting-multi/module_first.js
- test/statsCases/scope-hoisting-multi/second.js
- test/statsCases/scope-hoisting-multi/vendor.js
- test/statsCases/scope-hoisting-multi/webpack.config.js
- test/statsCases/tree-shaking/expected.txt
refactoring
yes
N/A
**Summary**
Allow scope hoisting to process modules in multiple chunks
no
> Allow scope hoisting to process modules in multiple chunks

- README.md
README
N/A
N/A
**Summary**
I had received some excellent anonymous feedback that had much to say about some pieces of our readme in the contributing section. I think we need "approachability to start from zero". Some of these simple wording changes I believe will make a huge difference.
NO
N/A
> Changing readme voice to align with comm direction

- .travis.yml
CI
yes
N/A
**Summary**
OSX test on node.js 8
no
> OSX test on node.js 8

- lib/Compilation.js
- lib/Module.js
cleanup
Yes
N/A
**Summary**
module.lastId appears to be unused
No - except it's vital for some third party things out there.
> remove "lastId" as there is no usecase

- lib/optimize/ConcatenatedModule.js
error reporting
no
N/A
**Summary**
> better error message for missing internal names

- lib/WebpackOptionsApply.js
uses a known string value instead of duplicate string
These changes don't affect testing
N/A
**Summary**
Looks better, might save a future bug, matches surrounding code style.
No.
> not using duplicate strings where it is easy to do so

- lib/dependencies/DepBlockHelpers.js
ES6 refactor of dependencies/DepBlockHelpers.js
Tests already written.
**Summary**
ES6 refactor as per issue https://github.com/webpack/webpack/issues/4099.
> Issue #4099: ES6 Refactor for depdendencies/DepBlockHelpers.js

- README.md
Readme bugfix
Yes.
https://github.com/webpack/webpack/issues/5156
No
> README.md bugfix(re pr for: https://github.com/webpack/webpack/pull/5159)

- lib/webworker/WebWorkerChunkTemplatePlugin.js
Refactoring
No
**Summary**
Just a quick refactoring for ES6 whole refactor
No 
> Changed statement 'var' to 'const'

- lib/RequireJsStuffPlugin.js
- lib/dependencies/CommonJsPlugin.js
- test/RequireJsStuffPlugin.test.js
- test/cases/parsing/requirejs/index.js
- test/cases/parsing/typeof/index.js
bugfix
yes
N/A
**Summary**
fixes #5198
no
> emit correct code for typeof require.resolve(Weak), require and requirejs.onError

- lib/optimize/ConcatenatedModule.js
- test/statsCases/scope-hoisting-multi/expected.txt
bugfix
only manual
N/A
**Summary**
fixes #5184
no
> add hash method to concatenated module

- test/configCases/plugins/define-plugin/index.js
testcase
yes
n/a
**Summary**
testcase for #5215
no
> add test case

- lib/dependencies/HarmonyImportDependencyParserPlugin.js
- lib/optimize/ConcatenatedModule.js
- test/cases/parsing/harmony-this/abc.js
- test/cases/parsing/harmony-this/index.js
- test/cases/parsing/harmony-this/new.js
- test/configCases/parsing/harmony-this-concat/abc.js
- test/configCases/parsing/harmony-this-concat/index.js
- test/configCases/parsing/harmony-this-concat/new.js
- test/configCases/parsing/harmony-this-concat/webpack.config.js
- test/configCases/scope-hoisting/strictThisContextOnImports/index.js
- test/configCases/scope-hoisting/strictThisContextOnImports/module.js
- test/configCases/scope-hoisting/strictThisContextOnImports/webpack.config.js
bugfix
yes
N/A
**Summary**
Call imports with the correct context.
Parse arguments of an import call.
Support strictThisContextOnImports in ConcatenatedModules
fixes #5246
fixes #5135
fixes #5111
yes, but a bugfix
> Fixes for import call context

- hot/log-apply-result.js
- hot/log.js
bugfix
No. I didn't see any tests for the HMR client.
**Summary**
Remove loader information from the updated modules HMR log message. Fixes #4452
no
> hide loaders in HMR log message

- lib/node/NodeWatchFileSystem.js
- package.json
- test/WatchTestCases.test.js
- test/watchCases/recover-from-error/missing-module/0/errors.js
- test/watchCases/recover-from-error/missing-module/0/index.js
- test/watchCases/recover-from-error/missing-module/1/node_modules/some-module/index.js
- yarn.lock
bugfix
yes
N/A
**Summary**
update to fixed watchpack version
allow missing items to be files or directories
no
> watch missing directories

- lib/optimize/AggressiveSplittingPlugin.js
performance
existing tests
N/A
**Summary**
hoist expensive calculations
no
> performance improvements and comments

- lib/optimize/ConcatenatedModule.js
- test/cases/scope-hoisting/issue-5314/index.js
- test/cases/scope-hoisting/issue-5314/module.js
bugfix
yes
N/A
**Summary**
allow to use default export of root module in concatenated module in inner modules
better error messages when parsing fails
fixes #5314
#5304
no
> bugfix for missing internal name in Scope Hoisting

- test/binCases/module/module-bind/post-loader.js
- test/binCases/module/module-bind/pre-loader.js
test
yes
N/A
**Summary**
fix for line endings on windows
#5346
no
> fix for line endings on windows

- lib/optimize/AggressiveMergingPlugin.js
refactoring
existing tests
N/A
**Summary**
array -> object
no
> aggressive-merging-plugin: refactor for more readability

- package.json
- yarn.lock
deps upgrade
existing tests
N/A
**Summary**
no
> upgrade yargs

- package.json
- yarn.lock
deps upgrade
existing tests
N/A
**Summary**
no
> upgrade file-loader

- package.json
- yarn.lock
deps upgrade
existing tests
N/A
**Summary**
no
> upgrade i18n-webpack-plugin

- package.json
- yarn.lock
dependencies upgrade
existing tests
N/A
**Summary**
no
> upgrade supports-color

- lib/Stats.js
- package.json
- test/HotTestCases.test.js
- test/statsCases/separate-css-bundle/expected.txt
- test/statsCases/separate-css-bundle/webpack.config.js
- test/watchCases/plugins/extract-text-plugin/webpack.config.js
- yarn.lock
deps upgrade
existing tests
N/A
**Summary**
upgrade extract-text-webpack-plugin
no
> upgrade extract-text-webpack-plugin

- test/statsCases/separate-css-bundle/expected.txt
- yarn.lock
deps update
existing tests
n/a
**Summary**
no
> update all dependencies to latest compatible version

- benchmark/createBenchmark.js
- benchmark/createBenchmark/entry.js
- benchmark/createBenchmark/loadLoader.js
- benchmark/createTestCases.js
- lib/webpack.js
benchmark
N/A
N/A
**Summary**
refactor webpack to be webpackable
add a single file benchmark 
no
> Add benchmark

- lib/DelegatedModule.js
- lib/DelegatedPlugin.js
- lib/DllReferencePlugin.js
- lib/dependencies/DelegatedExportsDependency.js
- test/WatchTestCases.test.js
- test/watchCases/plugins/dll-reference-plugin/1/index.js
- test/watchCases/plugins/dll-reference-plugin/2/index.js
- test/watchCases/plugins/dll-reference-plugin/webpack.config.js
bugfix
yes
N/A
**Summary**
integrate the delegated module better into the exports flagging process
fixes #5374
no
> integrate the delegated module better into the exports flagging process

- examples/build-common.js
- examples/buildAll.js
- examples/examples.js
- test/Examples.test.js
example/refactor
yes
N/A
**Summary**
no
> Refactor example scripts and test to allow nested folders

- examples/dll-app-and-vendor/0-vendor/README.md
- examples/dll-app-and-vendor/0-vendor/build.js
- examples/dll-app-and-vendor/0-vendor/js/vendor-manifest.json
- examples/dll-app-and-vendor/0-vendor/js/vendor.js
- examples/dll-app-and-vendor/0-vendor/template.md
- examples/dll-app-and-vendor/0-vendor/webpack.config.js
- examples/dll-app-and-vendor/1-app/README.md
- examples/dll-app-and-vendor/1-app/build.js
- examples/dll-app-and-vendor/1-app/example-app.js
- examples/dll-app-and-vendor/1-app/example.html
- examples/dll-app-and-vendor/1-app/js/app.js
- examples/dll-app-and-vendor/1-app/template.md
- examples/dll-app-and-vendor/1-app/webpack.config.js
- examples/dll-app-and-vendor/README.md
- examples/dll-app-and-vendor/node_modules/example-vendor.js
example
yes
N/A
**Summary**
add dll-app-and-vendor example
no
> add dll-app-and-vendor example by @aretecode

- lib/optimize/CommonsChunkPlugin.js
- test/configCases/async-commons-chunk/all-selected/a.js
- test/configCases/async-commons-chunk/all-selected/b.js
- test/configCases/async-commons-chunk/all-selected/c.js
- test/configCases/async-commons-chunk/all-selected/index.js
- test/configCases/async-commons-chunk/all-selected/webpack.config.js
- test/statsCases/async-commons-chunk-all-selected/a.js
- test/statsCases/async-commons-chunk-all-selected/b.js
- test/statsCases/async-commons-chunk-all-selected/c.js
- test/statsCases/async-commons-chunk-all-selected/expected.txt
- test/statsCases/async-commons-chunk-all-selected/index.js
- test/statsCases/async-commons-chunk-all-selected/webpack.config.js
- test/statsCases/async-commons-chunk/a.js
- test/statsCases/async-commons-chunk/b.js
- test/statsCases/async-commons-chunk/c.js
- test/statsCases/async-commons-chunk/expected.txt
- test/statsCases/async-commons-chunk/index.js
- test/statsCases/async-commons-chunk/webpack.config.js
bugfix
yes
N/A
**Summary**
fix a bug that prevented the automatic chunk selection to select initial chunks
fixes #5145
fixes #5386
fixes #5285
fixes #5109
no
> fix async CCP without name

- README.md
Grammar fix for README support section
N/A (documentation)
N/A (README update)
**Summary**
Fixes grammar in support section of readme, for clarity of meaning of sentence.
N/A
> fix grammar in support section of readme

- lib/Stats.js
- schemas/webpackOptionsSchema.json
- test/statsCases/exclude-with-loader/exclude/c.json
- test/statsCases/exclude-with-loader/expected.txt
- test/statsCases/exclude-with-loader/index.js
- test/statsCases/exclude-with-loader/webpack.config.js
feature
yes
N/A
**Summary**
I tried to address this issue #5333 by adding "excludeAssets" to Stats.
no
Could someone please provide me an idea, how to add this to the documentation for stats?
> Add new option "excludeAssets" to Stats

- test/binCases/errors/parse/test.js
test bugfix
n/a
n/a
**Summary**
n/a
no
> remove console.log statement

- lib/Stats.js
- test/statsCases/tree-shaking/expected.txt
bugfix
yes
N/A
**Summary**
stats string fix
no
> display better message, instead of empty list

- README.md
Bugfix and change
No, can't.
View demo at: https://github.com/pierreneter-repositories/webpack/tree/README.md
**Summary**
Redesign the top of /README.md and fix some wrongs in this.
> Redesign top of /README.md and fix some wrongs in there.

- bin/config-yargs.js
bugfix
no - no need for them
**Summary**
More info can be found here: https://github.com/webpack/webpack/issues/5451
no
Really trivial change - just fixed typo in documentation
> Fixed bug in --resolve-extensions parameter documentation

- lib/optimize/ConcatenatedModule.js
- test/configCases/scope-hoisting/named-modules/index.js
- test/configCases/scope-hoisting/named-modules/module.js
- test/configCases/scope-hoisting/named-modules/module2.js
- test/configCases/scope-hoisting/named-modules/webpack.config.js
bugfix
yes
N/A
**Summary**
stringify id
no
> fix invalid generated code with scope hoisting and non-number ids

- package.json
Add's a new npm script: `npm run fix` to autofix eslint issues
**Summary**
https://twitter.com/samccone/status/895074832013864962
> add fix command for eslint

- lib/EntryOptionPlugin.js
Refactoring EntryOptionPlugin.js
This is refactoring. So we don't need to add new tests.
**Summary**
I fixed indent and remove unneeded else statement
No, it doesn't
> Refactor "EntryOptionPlugin.js"

- open-bot.yaml
bot
no
N/A
**Summary**
Wait for CI not pending until reporting CI status
no
> Wait for CI not pending until reporting CI status

- open-bot.yaml
bot
yes, manually
N/A
**Summary**
mark and close inactive issues after half a year
no
> mark and close inactive issues after half a year

- lib/optimize/ConcatenatedModule.js
- test/cases/scope-hoisting/issue-5481/cjs.js
- test/cases/scope-hoisting/issue-5481/index.js
- test/cases/scope-hoisting/issue-5481/module.js
bugfix
yes
N/A
**Summary**
fixes #5481
no
> also generate a new identifier for interop name

- lib/HotModuleReplacement.runtime.js
- test/hotCases/runtime/circular/a.js
- test/hotCases/runtime/circular/b.js
- test/hotCases/runtime/circular/index.js
bugfix
yes
N/A
**Summary**
avoid calling accept handler on disposed modules
fixes #2387
fixes #5498
no
> avoid calling accept handler on disposed modules

- examples/pure-module/README.md
- examples/pure-module/template.md
mostly copyediting for grammar and tone
Purely doc changes
No tests, just a doc change
**Summary**
rewrite README.md a bit to make it clearer.
No breaking changes
None
> rewrite README.md a bit to make it clearer

- lib/Compilation.js
- lib/util/Semaphore.js
- schemas/webpackOptionsSchema.json
- test/Validation.test.js
feature, performance
no
TODO
**Summary**
Limit the number of parallel processed modules
fixes #3164
fixes #3166
no
> Limit the number of parallel processed modules

- lib/optimize/ConcatenatedModule.js
- test/hotCases/concat/reload-compat-flag/a.js
- test/hotCases/concat/reload-compat-flag/index.js
- test/hotCases/concat/reload-compat-flag/module.js
- test/hotCases/concat/reload-compat-flag/webpack.config.js
bugfix
yes
N/A
**Summary**
fixes #5510
no
> set compatiblity flag correctly even after incremental build

- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
Refactoring
No
**Summary**
Refactor/simplify getReference() in HarmonyExportImportedSpecifierDependency.js. 
Reused checks extracted to consts.
No
> refactor/simplify getReference() in HarmonyExportImportedSpecifierDependency.js

- lib/Template.js
- test/Template.test.js
Refactoring
Yes for Template Path
**Summary**
This PR just hoists some of the Regular Expressions and give them some names (I think) are accurate. The RegExp's inside of the Template are not clear what they are entirely trying to accomplish (especially as they are chained together).
No
> feat(template): cleanup template a bit, add a test for toPath

- lib/HotModuleReplacement.runtime.js
typo in api
no
https://github.com/webpack/webpack.js.org/pull/1562
**Summary**
fix a typo
no
> fix typo in HMR API

- lib/optimize/ConcatenatedModule.js
- test/cases/scope-hoisting/async-keyword-5615/async.js
- test/cases/scope-hoisting/async-keyword-5615/index.js
- test/cases/scope-hoisting/require-root-5604/index.js
- test/cases/scope-hoisting/require-root-5604/module.js
bugfix
yes
N/A
**Summary**
handle inner non-harmony dependencies correctly in ConcatenatedModule
add async as keyword
fixes #5604
fixes #5615
no
> handle inner non-harmony dependencies correctly in ConcatenatedModule

- lib/dependencies/HarmonyImportDependencyParserPlugin.js
- test/cases/parsing/issue-5624/index.js
- test/cases/parsing/issue-5624/module.js
- test/configCases/parsing/issue-5624/index.js
- test/configCases/parsing/issue-5624/module.js
- test/configCases/parsing/issue-5624/webpack.config.js
bugfix
yes
N/A
**Summary**
see #5624
no
> fixes #5624

- lib/OptionsDefaulter.js
- lib/WebpackOptionsDefaulter.js
- lib/webpack.js
- test/configCases/defaulter/immutable-config/index.js
- test/configCases/defaulter/immutable-config/webpack.config.js
bugifx
yes
N/A
**Summary**
clone options and don't modify them
fixes #5628
yes, but not activated yet.
> clone options and don't modify them

- .travis.yml
- ci/travis-install.sh
- package.json
CI
CI
N/A
**Summary**
update to newer travis image
no
> update to newer travis image

- .eslintrc.js
Dev UX
N/A
N/A
**Summary**
remove duplicate configuration item
N/A
> chore(eslint): remove duplicate configuration item

- lib/webpack.web.js
Just remove one line of useless code.
No new tests added.
**Summary**
Nope.
> remove one line of useless code

- bin/convert-argv.js
> Fix: incorrect comparing to undefined.

- lib/Chunk.js
- lib/Compilation.js
- lib/RecordIdsPlugin.js
- lib/Stats.js
- lib/optimize/AggressiveMergingPlugin.js
- lib/optimize/CommonsChunkPlugin.js
- lib/optimize/EnsureChunkConditionsPlugin.js
- lib/optimize/OccurrenceOrderPlugin.js
- lib/optimize/RemoveParentModulesPlugin.js
- lib/util/SortableSet.js
refactor to Sets
existing tests
N/A
**Summary**
yes
> Use SortableSets for Chunk.parents/blocks

- lib/FunctionModuleTemplatePlugin.js
bugfix
no
N/A
**Summary**
generate better comments for no used/provided exports
no
> generate better comments for no used/provided exports

- test/cases/chunks/circular-correctness/index.js
- test/cases/chunks/circular-correctness/module-a.js
- test/cases/chunks/circular-correctness/module-a2.js
- test/cases/chunks/circular-correctness/module-b.js
- test/cases/chunks/circular-correctness/module-b2.js
- test/cases/chunks/circular-correctness/module-c.js
- test/cases/chunks/circular-correctness/module-x.js
- test/statsCases/circular-correctness/expected.txt
- test/statsCases/circular-correctness/index.js
- test/statsCases/circular-correctness/module-a.js
- test/statsCases/circular-correctness/module-b.js
- test/statsCases/circular-correctness/module-c.js
- test/statsCases/circular-correctness/webpack.config.js
tests
yes
N/A
**Summary**
tests for #5785 and #5786 
no
> add two tests for circular correctness of the chunk graph

- lib/Compilation.js
- test/statsCases/graph-correctness-entries/e1.js
- test/statsCases/graph-correctness-entries/e2.js
- test/statsCases/graph-correctness-entries/expected.txt
- test/statsCases/graph-correctness-entries/module-a.js
- test/statsCases/graph-correctness-entries/module-b.js
- test/statsCases/graph-correctness-entries/module-c.js
- test/statsCases/graph-correctness-entries/webpack.config.js
> fix graph correctness with multiple entries

- lib/Compilation.js
- test/statsCases/graph-correctness-modules/e1.js
- test/statsCases/graph-correctness-modules/e2.js
- test/statsCases/graph-correctness-modules/expected.txt
- test/statsCases/graph-correctness-modules/module-a.js
- test/statsCases/graph-correctness-modules/module-b.js
- test/statsCases/graph-correctness-modules/module-c.js
- test/statsCases/graph-correctness-modules/module-x.js
- test/statsCases/graph-correctness-modules/webpack.config.js
bugfix
yes
N/A
**Summary**
another testcase and bugfix from last PR
no
> bugfix and test for graph correctness

- lib/Compilation.js
- test/ConfigTestCases.test.js
- test/configCases/errors/import-missing/errors.js
- test/configCases/errors/import-missing/index.js
- test/configCases/errors/import-missing/webpack.config.js
bugfix
yes
N/A
**Summary**
fixes #5787
no
> prevent crashing when error out early in bail mode

- lib/Compilation.js
- test/configCases/performance/many-async-imports/index.js
- test/configCases/performance/many-async-imports/leaf.js
- test/configCases/performance/many-async-imports/reexport.loader.js
- test/configCases/performance/many-async-imports/start.js
- test/configCases/performance/many-async-imports/test.config.js
- test/configCases/performance/many-async-imports/test.filter.js
- test/configCases/performance/many-async-imports/webpack.config.js
- test/statsCases/optimize-chunks/expected.txt
refactoring for performance
yes
see source code
**Summary**
Refactor algorithm to traverse less nodes, more efficient datastructures, better detection of circles.
fixes #5785
no
@kenotron could you check if this fulfills your performance needs?
> improve chunk graph building performance

- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- lib/optimize/ConcatenatedModule.js
- test/cases/errors/harmony-import-missing/a.js
- test/cases/errors/harmony-import-missing/errors.js
- test/cases/errors/harmony-import-missing/index.js
- test/cases/errors/harmony-import-missing/module.js
> fix crashes when imported module fails compiling

- test/configCases/performance/many-async-imports/test.filter.js
- test/configCases/performance/many-exports/test.filter.js
these versions are too slow
CI
na
na
**Summary**
no
> Exclude testing in older versions

- lib/Chunk.js
- test/statsCases/limit-chunk-count-plugin/expected.txt
- test/statsCases/module-deduplication/expected.txt
- test/statsCases/named-chunks-plugin-async/expected.txt
- test/statsCases/optimize-chunks/expected.txt
bugfix
existing tests
N/A
**Summary**
generate more stable bundle, even when this is only a comment
no
> set chunk reasons symmetrical

- lib/MultiCompiler.js
- test/MultiCompiler.test.js
bugfix
yes
**Summary**
Generates a friendly error message if there are problems with compiler dependencies in a multi-config. 
Currently these throw unhelpful runtime errors. Fixes #5414
no
> Compiler dependency error

- lib/AsyncDependencyToInitialChunkWarning.js
- lib/Compilation.js
- lib/Stats.js
- test/cases/chunks/weird-reference-to-entry/index.js
- test/cases/chunks/weird-reference-to-entry/module-a.js
- test/cases/chunks/weird-reference-to-entry/warnings.js
bugfix with warning
yes
N/A
**Summary**
fixes #5832
no
> fix behavior and add a warning when trying to load an initial chunk on demand

- schemas/webpackOptionsSchema.json
bugfix
no
N/A
**Summary**
fixes #5839
no
> add missing stats keys

- lib/NormalModule.js
- lib/Parser.js
- test/cases/parsing/precreated-ast/ast-loader.js
- test/cases/parsing/precreated-ast/index.js
- test/cases/parsing/precreated-ast/module.js
- test/cases/parsing/precreated-ast/ok.js
- test/cases/parsing/precreated-ast/wrong.js
feature
yes
**Summary**
allow to pass AST directly from loaders to webpack
no
> allow to pass AST directly from loaders to webpack

- lib/Chunk.js
- lib/Module.js
- lib/util/SortableSet.js
refactor caching
existing tests
N/A
**Summary**
more caching -> performance
yes
> allow caching in sortable set and use it

- lib/RuleSet.js
- test/configCases/rule-set/simple-use-array-fn/a.js
- test/configCases/rule-set/simple-use-array-fn/ab.js
- test/configCases/rule-set/simple-use-array-fn/b.js
- test/configCases/rule-set/simple-use-array-fn/c.js
- test/configCases/rule-set/simple-use-array-fn/index.js
- test/configCases/rule-set/simple-use-array-fn/loader.js
- test/configCases/rule-set/simple-use-array-fn/webpack.config.js
bugfix
yes
N/A
**Summary**
allow to pass functions to rules.use and return arrays
no
> allow to pass functions to rules.use and return arrays

- bin/webpack.js
- test/Validation.test.js
- test/binCases/errors/validation/test.js
- test/binCases/errors/validation/webpack.config.js
**Summary**
One less `require()` call
> refactor(bin/webpack): use `err.name` for error handling

- lib/Compilation.js
- lib/DllModuleFactory.js
- lib/ExternalsPlugin.js
- lib/FlagDependencyUsagePlugin.js
- lib/OptionsDefaulter.js
- lib/dependencies/HarmonyDetectionParserPlugin.js
- lib/dependencies/HarmonyImportDependency.js
- lib/dependencies/LocalModulesHelpers.js
refactoring
**Summary**
There are some var references which can be replaced with ES6's const and lets.
No
> ES5 var to let and const

- lib/Template.js
feature
no
N/A
**Summary**
better mangling for export names
DLLs are outdated.
> generate shorter export names when using many exports

- examples/README.md
bugfix
yes
**Summary**
fix typo
no
> fix typo&& wrong links in examples/README.md

- test/configCases/context-replacement/d/queryloader.js
testcase
yes
N/A
**Summary**
fix testcase for windows-style paths
no
> fix testcase for windows-style paths

- lib/Compilation.js
- lib/Compiler.js
- lib/ContextModule.js
- lib/ContextModuleFactory.js
- lib/Module.js
- lib/NormalModule.js
- lib/NormalModuleFactory.js
- lib/ResolverFactory.js
- lib/WebpackOptionsApply.js
- lib/WebpackOptionsDefaulter.js
- lib/dependencies/AMDPlugin.js
- lib/node/NodeSourcePlugin.js
- lib/util/cachedMerge.js
- schemas/webpackOptionsSchema.json
- test/Validation.test.js
- test/configCases/rule-set/resolve-options/a.js
- test/configCases/rule-set/resolve-options/b.js
- test/configCases/rule-set/resolve-options/index.js
- test/configCases/rule-set/resolve-options/ok.js
- test/configCases/rule-set/resolve-options/webpack.config.js
- test/configCases/rule-set/resolve-options/wrong.js
feature
yes
TODO
**Summary**
Allow to override resolve configuration
yes
> Allow to override resolve configuration

- test/Schemas.lint.js
linting bugfixes
no
N/A
**Summary**
fix an issue with schemas in subdirectories
allow id property
no
> fix an issue with schemas in subdirectories

- lib/Compilation.js
- lib/Dependency.js
- lib/dependencies/ContextDependency.js
- lib/dependencies/LoaderPlugin.js
- lib/dependencies/ModuleDependency.js
- lib/dependencies/NullDependency.js
- lib/optimize/ModuleConcatenationPlugin.js
- lib/util/StackedSetMap.js
- test/NullDependency.unittest.js
performance
existing tests
N/A
**Summary**
Use StackedSetMap for better performance in ModuleConcatenationPlugin
replace isEqualResource with more performance implementation 
yes
> Performance improvements

- lib/DllReferencePlugin.js
bugfix
no
n/a
**Summary**
use type from manifest in DllReferencePlugin
no
> use type from manifest

- lib/WebpackOptionsDefaulter.js
feature
TODO
n/a
**Summary**
add wasm extensions as default
yes
> add wasm extensions as default

- lib/Compilation.js
- lib/dependencies/HarmonyAcceptImportDependency.js
- lib/dependencies/HarmonyImportDependency.js
- test/hotCases/harmony/auto-import-default/file.js
- test/hotCases/harmony/auto-import-default/index.js
- test/hotCases/harmony/auto-import-default/out/bundle.js
bugfix
not really
n/a
**Summary**
fix weak status of harmony accept dependency
add test case for accepting default import
no
> fix weak status of harmony accept dependency

- lib/HotModuleReplacementPlugin.js
bugfix
no
n/a
**Summary**
fix increasing delay with multiStep HMR
no
> fix increasing delay with multiStep HMR

- lib/WebpackOptionsDefaulter.js
- test/cases/mjs/need-extension/errors.js
- test/cases/mjs/need-extension/index.js
- test/cases/mjs/need-extension/module.js
- test/cases/mjs/need-extension/module.mjs
- test/cases/mjs/need-extension/test.mjs
bugfix
yes
n/a
**Summary**
mjs can't import modules without extension
yes
> mjs can't import modules without extension

- lib/Compilation.js
- lib/HashedModuleIdsPlugin.js
- lib/HotModuleReplacementPlugin.js
- lib/ModuleFilenameHelpers.js
- lib/NormalModule.js
- lib/SourceMapDevToolPlugin.js
- lib/optimize/ConcatenatedModule.js
- lib/util/createHash.js
try to avoid calling hash.update with short strings
refactor, performance
existing tests
n/a
**Summary**
aggregate all crypto hash usages into util/createHash
try to avoid calling hash.update with short strings
no
> util/createHash, call hash.update in bulks

- lib/optimize/MergeDuplicateChunksPlugin.js
performance
existing tests
n/a
**Summary**
use a faster merge duplicate chunks algorithm
no
> use a faster merge duplicate chunks algorithm

- yarn.lock
> upgrade webpack-sources in lockfile

- lib/webpack.js
- schemas/webpackOptionsSchema.json
- test/Validation.test.js
Schema validation for `options.plugins`.
Ensure `apply` method is available on the plugin.
Fixes #6003 
Fixes #2217
Yes
**Summary**
"Hard to debug TypeError: arguments[i].apply is not a function " 
no
> Lookup the provided plugins on the options, throw for invalid arguments.

- package.json
- schemas/WebpackOptions.json
- test/TestCases.test.js
- yarn.lock
Upgrade enhanced-resolve
existing tests
n/a
**Summary**
yes
> Upgrade enhanced-resolve version

- schemas/webpackOptionsSchema.json
> Add missing watchOptions properties to schema

- lib/ContextModule.js
- lib/dependencies/ImportDependency.js
- test/cases/mjs/namespace-object-lazy/dir-cjs/null.js
- test/cases/mjs/namespace-object-lazy/dir-mixed/null.js
- test/cases/mjs/namespace-object-lazy/index.mjs
- test/cases/mjs/non-mjs-namespace-object-lazy/dir-cjs/null.js
- test/cases/mjs/non-mjs-namespace-object-lazy/dir-mixed/null.js
- test/cases/mjs/non-mjs-namespace-object-lazy/index.js
- test/statsCases/import-weak/expected.txt
- test/statsCases/limit-chunk-count-plugin/expected.txt
- test/statsCases/named-chunks-plugin-async/expected.txt
bugfix
yes
n/a
**Summary**
null would crash
no
> fix non-harmony import() handling for `null`

- lib/dependencies/RequireIncludeDependency.js
- test/statsCases/tree-shaking/expected.txt
- test/statsCases/tree-shaking/index.js
- test/statsCases/tree-shaking/require.include.js
bugfix
yes
n/a
**Summary**
see also #6023
no
> allow tree-shaking for require.include

- lib/Parser.js
- test/Parser.unittest.js
Improves Parser to recognize 'new Foo(...)' type expressions
Yes
**Summary**
Please see #6054 
No
> Improve Parser to recognize 'new Foo(...)' type expressions

- lib/DynamicEntryPlugin.js
- lib/EntryOptionPlugin.js
- lib/MultiEntryPlugin.js
- lib/SingleEntryPlugin.js
Refactoring
None needed
N/A
**Summary**
Upgrade (Single|Multi|Dynamic)EntryPlugin to use Tapable v1 API. 
No
I think Beautify is going to be mad.
> feat(tapable): upgrade Single|Multi|DynamicEntryPlugin to tapable v1

- lib/ChunkTemplate.js
- lib/ExtendedAPIPlugin.js
- lib/HotModuleReplacementPlugin.js
- lib/HotUpdateChunkTemplate.js
- lib/MainTemplate.js
- lib/ModuleTemplate.js
- lib/Template.js
- lib/node/NodeMainTemplatePlugin.js
- lib/node/ReadFileCompileWasmMainTemplatePlugin.js
- lib/web/FetchCompileWasmMainTemplatePlugin.js
- lib/web/JsonpMainTemplatePlugin.js
- lib/webworker/WebWorkerMainTemplatePlugin.js
refactoring
existing test
n/a
**Summary**
make all methods on Template static
yes
It's weird currently
> make all methods on Template static

- package.json
- yarn.lock
dependencies upgrade
existing tests
n/a
**Summary**
yes
> upgrade tapable

- lib/APIPlugin.js
- lib/DefinePlugin.js
- lib/ExtendedAPIPlugin.js
- lib/HotModuleReplacementPlugin.js
- lib/NodeStuffPlugin.js
- lib/ParserHelpers.js
- lib/RequireJsStuffPlugin.js
- lib/dependencies/CommonJsRequireDependencyParserPlugin.js
- lib/dependencies/ConstDependency.js
- test/statsCases/define-plugin/expected.txt
improvement
existing tests
n/a
**Summary**
fixes #5707
yes
> remove `__webpack_require__` requirement from some ConstDependencies

- lib/ProgressPlugin.js
- test/configCases/plugins/progress-plugin/data.js
- test/configCases/plugins/progress-plugin/index.js
- test/configCases/plugins/progress-plugin/webpack.config.js
feature
TODO
n/a
**Summary**
no
> improve ProgressPlugin

- lib/optimize/ConcatenatedModule.js
- test/statsCases/commons-plugin-issue-4980/expected.txt
- test/statsCases/parse-error/expected.txt
optimization
existing tests
n/a
**Summary**
use __webpack_require__.r
no
> shorter code in concatenated module

- bin/webpack.js
- package.json
feature, dependenices
manually
TODO
**Summary**
webpack-cli dependency -> devDependency
yes
cc @ev1stensberg
> remove dependencies, ask for installing webpack-cli when using the CLI
