- lib/WebpackOptionsDefaulter.js
- test/configCases/issues/issue-7470/index.js
When `mode=none`, `nodeEnv` optimization is now disabled.
refactoring
yes
yes
`mode=none` now sets `optimization.nodeEnv=false`
> Do not set nodeEnv when 'mode=none'

- lib/Chunk.js
- lib/ChunkGroup.js
- lib/Compilation.js
Remove some useless checks on `ChunkGroup` because:
- `#options` is always set in `constructor`
- `#addOptions(…)` and `#compareTo(…)` is set in the prototype
refactoring
no
kinda
nothing
> Remove useless checks on ChunkGroup

- bin/webpack.js
Rather than require()-ing the "main" module in webpack-cli/
webpack-command, require() the "bin" module.
This avoids the issue described in
https://github.com/webpack-contrib/webpack-command/pull/30
where installing packages in this order results in no output from
./node_modules/.bin/webpack:
$ npm install webpack-command
$ npm install webpack
$ ./node_modules/.bin/webpack
~~Note: the [read-package-json](https://github.com/npm/read-package-json) package is by npm, and helps to normalize the shape of the `pkg.bin` object (since the [`"bin"` field in package.json](https://docs.npmjs.com/files/package.json#bin) can be either a string or an object).~~
Bug fix
No. I could not find an existing test suite for …
> require() webpack-cli/webpack-command's bin module

- _SETUP.md
- package.json
This PR adds a very simple update-snapshot script. This enables a contributor to run:
```bash
yarn test:update-snapshots
```
I also updated the SETUP.md guide to reflect this change. 
Build related change
N/A
N/A
N/A
> chore(pgk): add update-snapshot script for all tests

- lib/Compilation.js
- test/configCases/wasm/identical/index.js
- test/configCases/wasm/identical/module.js
- test/configCases/wasm/identical/test.filter.js
- test/configCases/wasm/identical/wasm.wat
- test/configCases/wasm/identical/webpack.config.js
fixes webpack-contrib/mini-css-extract-plugin#190
fixes webpack-contrib/mini-css-extract-plugin#194
bugfix
yes
no
nothing
> allow emitting to the same filename when hash matches

- lib/WebpackOptionsDefaulter.js
- lib/optimize/SplitChunksPlugin.js
- schemas/WebpackOptions.json
- test/__snapshots__/StatsTestCases.test.js.snap
* rename optimization.splitChunks.cacheGroups.vendors -> defaultVendors
* add automaticNamePrefix option
* allow automaticNameDelimiter on cacheGroup level
rename, feature
existing tests
yes
see above
> rename optimization.splitChunks.cacheGroups.vendors -> defaultVendors

- lib/optimize/SplitChunksPlugin.js
fixes #6929
memory leak fix
no
no
nothing
> make the cache a WeakMap to not leak memory

- lib/debug/ProfilingPlugin.js
Fixes #7654
This fixes the node 6 warning I was seeing (see issue #7654).  I'm not sure if there's a way to clean up the readable stream in node 6.
Prevents calling a method that doesn't exist in node 6
No.  I tested manually by running this code against my codebase in node 6 (before and after making the change)
I hope not.
I don't think anything really needs to be documented.  This just prevents a warning from showing up in node 6.
> prevent UnhandledPromiseRejectionWarning in node 6

- lib/web/JsonpMainTemplatePlugin.js
Refactor `JsonpMainTemplatePlugin` plugin to change how hooks are installed into `MainTemplate`.
cc @jantimon
refactoring
no
yes
Maybe `JsonpMainTemplatePlugin.hooks`.
> Use JsonpMainTemplatePlugin.hooks instead of MainTemplate#hooks

- lib/HotModuleReplacementPlugin.js
- lib/dependencies/HarmonyImportDependencyParserPlugin.js
Refactor HMR plugin to change how hooks are installed.
refactoring
already tested
yes
Currently HMR hooks are not documented. If some day they are, then it must uses `HotModuleReplacementPlugin.hooks(parser)`.
> Refactor HMR hooks

- lib/WebpackOptionsApply.js
Currently it is not possible to use WebAssembly modules when target is set to `electron-renderer`. This pull request adds support for it. See #7677.
This PR adds a feature.
No.
No.
I couldn't find much documentation on WebAssembly modules, so I don't think there is a place where this change can be documented before there is more documentation.
> Added support for WebAssembly modules when target is set to `electron-renderer`

- lib/WebpackOptionsDefaulter.js
- test/configCases/source-map/array-as-output-library-in-object-output/index.js
- test/configCases/source-map/array-as-output-library-in-object-output/webpack.config.js
When using the following configuration:
```javascript
devtool: "source-map",
output: {
library: {
root: ["Foo", "[name]"],
amd: "[name]",
commonjs: "[name]"
},
libraryTarget: "umd"
}
};
``` 
Devtool throws the following error:
```
ValidationError: SourceMap DevTool Plugin Invalid Options
options.namespace should be string
```
This PR fixes this issue.
Fixes the bug by recursively checking if the value iss an array or a string.
Tests were added
No breaking change
Bug fix, no need to change documentation.
> devtool and output.library.root as array throws an error

- hot/dev-server.js
- hot/only-dev-server.js
- hot/poll.js
- hot/signal.js
group arguments of operator or (||)
otherwise, nonempty string is always true
```js
const err = {message: 'some message'}
> 'HMR: ' + err.stack || err.message
<- HMR: undefined
> 'HMR: ' + (err.stack || err.message)
<- HMR: some message
```
tiny bugfix
nope
nope
nothing
> fix(hot): log messages

- lib/Compilation.js
- lib/WebpackOptionsApply.js
- lib/WebpackOptionsDefaulter.js
- lib/optimize/NaturalChunkOrderPlugin.js
- lib/optimize/OccurrenceChunkOrderPlugin.js
- lib/optimize/OccurrenceModuleOrderPlugin.js
- lib/optimize/OccurrenceOrderPlugin.js
- lib/webpack.js
- schemas/WebpackOptions.json
- schemas/plugins/optimize/OccurrenceOrderChunkIdsPlugin.json
- schemas/plugins/optimize/OccurrenceOrderModuleIdsPlugin.json
- test/__snapshots__/StatsTestCases.test.js.snap
add new options moduleIds and chunkIds
deprecate namedModules, hashedModuleIds, namedChunks
add a lot of TODOs for webpack 5
split OccurenceOrderPlugin into separate plugins for modules and chunks
add NaturalChunkOrderPlugin and enable it in development
feature and bugfix
no
no
new options moduleIds and chunkIds (see schema for description)
Define the algorithm to choose module ids
natural: numeric ids in order for usage
named: readable ids for better debugging
hashed: short hashes as ids for better long term caching
size: numeric ids focused on minimal initial download size
total-size: numeric …
> add new options moduleIds and chunkIds

- declarations.d.ts
- lib/DelegatedModuleFactoryPlugin.js
I’d like to open the discussion on whether `.mjs` was omitted here for a reason or just as an oversight. 
Add `.mjs` to default `DelegatedModule` `options.extensions`
> Add .mjs to default DelegatedModule options.extensions

- lib/WebpackOptionsDefaulter.js
- lib/optimize/SplitChunksPlugin.js
- schemas/WebpackOptions.json
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/split-chunks-automatic-name/a.js
- test/statsCases/split-chunks-automatic-name/b.js
- test/statsCases/split-chunks-automatic-name/c.js
- test/statsCases/split-chunks-automatic-name/d.js
- test/statsCases/split-chunks-automatic-name/e.js
- test/statsCases/split-chunks-automatic-name/f.js
- test/statsCases/split-chunks-automatic-name/index.js
- test/statsCases/split-chunks-automatic-name/node_modules/x.js
- test/statsCases/split-chunks-automatic-name/node_modules/y.js
- test/statsCases/split-chunks-automatic-name/node_modules/z.js
- test/statsCases/split-chunks-automatic-name/webpack.config.js
add automaticNamePrefix option
allow automaticNameDelimiter on cacheGroup level
fix wrong priority handling when merging multiple cache groups by name
feature + bugfix
yes
no
automaticNamePrefix was added
automaticNameDelimiter is now possible on cache group level
automaticNamePrefix specifies the name prefix used when using `name: true` to automatically create a name. By default the cache group key is used.
> automaticNamePrefix and name merging bugfix

- schemas/WebpackOptions.json
feature
yes
no
I figure we could change this part a little bit:
```
The encoding to use when generating the hash, defaults to 'hex'. All encodings from Node.JS' hash.digest are supported. Using 'base64' for filenames might be problematic since it has the character / in its alphabet. Likewise 'latin1' could contain any character.
```
=>
```
The encoding to use when generating the hash, defaults to 'hex'. All encodings from Node.JS' `hash.digest()` are supported by default. Using 'base64' or 'latin1' for filenames might be problematic since it has the character / in its alphabet. 
When you are …
```
> Relaxed type check for hashDigest to allow other non NodeJS-native digest methods e.g. base62.

- README.md
I replaced `extract-text-webpack-plugin` with `mini-css-extract-plugin` since webpack v4 the `extract-text-webpack-plugin` should not be used for css. It is confusing to the end user to have `extract-text-webpack-plugin` on the `README.md` that relates to v4.
Documentation
N/A
No
N/A
> Add mini-css-extract-plugin instead of extract-text-webpack-plugin

- package.json
- yarn.lock
Bump `eslint-scope` to the latest version so webpack would benefit from future improvements and bugfixes.
no
no
nothinf
> Use v4 of eslint-scope

- lib/optimize/OccurrenceChunkOrderPlugin.js
- lib/optimize/OccurrenceModuleOrderPlugin.js
- lib/optimize/OccurrenceOrderPlugin.js
- test/Compiler.test.js
- test/HotModuleReplacementPlugin.test.js
- test/StatsTestCases.test.js
- test/__snapshots__/ConfigTestCases.test.js.snap
- test/__snapshots__/StatsTestCases.test.js.snap
- test/configCases/chunk-index/order-multiple-entries/webpack.config.js
- test/configCases/code-generation/use-strict/index.js
- test/configCases/hash-length/output-filename/test.config.js
- test/configCases/plugins/banner-plugin/index.js
- test/configCases/plugins/banner-plugin/webpack.config.js
remove enforced additional occurrence order plugin from test cases
make test cases more independent of module/chunk order/ids
The OccurrenceOrderPlugin should keep original order when occurrence count is equal, but instead it used the inverted order. This is now fixed.
Also the duplicate OccurrenceOrderPlugin in the StatsTestCases was removed.
bugfix, test update
existing tests
no
nothing
> fix order of occurrence order plugin

- lib/NodeStuffPlugin.js
- lib/dependencies/CommonJsRequireDependencyParserPlugin.js
- test/Errors.test.js
- test/cases/parsing/issue-7728/a.js
- test/cases/parsing/issue-7728/index.js
- test/fixtures/errors/module.parent.require.js
- test/fixtures/errors/require.main.require.js
- Resolve module.require dependencies
- Add require.main.require and module.parent.require as unsupported
Issue #7728: Detect module.require dependency 
Parser enhancement
Yes
No
1. Webpack can detect and resolve module.require
2. Webpack does not support require.main.require and module.parent.require
> Handle module.require, require.main.require, and module.parent.require

- lib/DllReferencePlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/dll-reference-plugin-issue-7624-error/entry.js
- test/statsCases/dll-reference-plugin-issue-7624-error/webpack.config.js
- test/statsCases/dll-reference-plugin-issue-7624/entry.js
- test/statsCases/dll-reference-plugin-issue-7624/non-blank-manifest.json
- test/statsCases/dll-reference-plugin-issue-7624/webpack.config.js
Fixes #7624.
If the DLL manifest file is blank (as experienced in #7624), or malformed in some way, parsing it will throw an error and, if left uncaught, will kill the process if webpack is in watch mode.
To prevent this, I've added a try/catch block around the JSON parsing. If an error occurs, it's fed into the compilation's errors so that the compilation fails, but the process (and the webpack compiler) continues to run.
Bugfix.
Yes.
No.
None.
> Catch errors while parsing DLL manifest

- lib/Dependency.js
- lib/dependencies/DelegatedExportsDependency.js
- lib/dependencies/DependencyReference.js
- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- lib/dependencies/HarmonyImportDependency.js
- lib/dependencies/HarmonyImportSpecifierDependency.js
- lib/dependencies/RequireIncludeDependency.js
- lib/dependencies/WebAssemblyExportImportedDependency.js
- lib/dependencies/WebAssemblyImportDependency.js
- lib/optimize/ConcatenatedModule.js
- lib/optimize/SideEffectsFlagPlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/configCases/deep-scope-analysis/remove-export-scope-hoisting/webpack.config.js
- test/configCases/deep-scope-analysis/remove-export/webpack.config.js
- test/statsCases/side-effects-simple-unused/webpack.config.js
`DependencyReference#module` is now dynamic
refactoring
yes
no, `DependencyReference` is an internal helper
nothing
> Make DependencyReference dynamic

- lib/ChunkTemplate.js
- lib/Compilation.js
- lib/Compiler.js
- lib/ContextModuleFactory.js
- lib/DllModuleFactory.js
- lib/HotUpdateChunkTemplate.js
- lib/JavascriptParser.js
- lib/MainTemplate.js
- lib/ModuleTemplate.js
- lib/MultiCompiler.js
- lib/MultiModuleFactory.js
- lib/NormalModuleFactory.js
- lib/ResolverFactory.js
- lib/wasm/WebAssemblyParser.js
**Note:** there is no speed penalty introduced by `Object.freeze`
This PR is a follow up of:
- #7672
- #7672
refactoring
no
yes
hooks are no longer extensible. Use a `WeakMap` to add custom hooks.
> Freeze hooks to prevent deopts

- lib/WatchIgnorePlugin.js
Refactoring.
Not necessary .
No.
Nothing.
> Refactor define before use class

- lib/HotModuleReplacementPlugin.js
The `compilation.hook.chunkAsset` hook expects 2 parameters, not three.
Bugfix
No
It depends from what perspective you look, it shows one of the problems with manual semantic versioning. The commit that introduced this behavior would not have been flagged as a breaking change, but it was a breaking change. Changing it back is a bug fix, but it also is a breaking change. At this point in time people might depend on the 'bad' behavior and changing it will break their code.
So, it's up to the maintainers to determine if this is classified as breaking change.
Not sure if there is a place in the …
> Fix chunkAsset hook call in HotModuleReplacementPlugin - fixes #7828

- test/README.md
- Document Update
Their Homepage URL might be migrated.
Current writing URL was redirecting(with 301), therefore I was updated  to least URL.
Thanks👏
> Update Jest Homepage URL

- lib/dependencies/ContextDependencyHelpers.js
- lib/dependencies/ContextDependencyTemplateAsId.js
- lib/dependencies/ContextDependencyTemplateAsRequireCall.js
- test/cases/parsing/issue-7778/a.js
- test/cases/parsing/issue-7778/abc.js
- test/cases/parsing/issue-7778/index.js
Will hopefully end up fixing a bug where queryStrings are affecting the way imports are treated  
https://github.com/webpack/webpack/issues/7778
(bugfix) Although currently just adds a failing test case, I think the problem lies somewhere inside ImportParserPlugin -> ContextDependencyHelpers but thats as far as I've gotten. Any help would be greatly appreciated
Yes (hopefully they are fine)
No
It will hopefully correct existing documented functionality
> fixes 7778: query string in dynamic import()

- lib/Compilation.js
- lib/DelegatedModule.js
- lib/ModuleGraph.js
- lib/ModuleGraphConnection.js
- lib/NodeStuffPlugin.js
- lib/dependencies/DelegatedExportsDependency.js
- lib/dependencies/HarmonyAcceptImportDependency.js
- lib/dependencies/HarmonyCompatibilityDependency.js
- lib/dependencies/HarmonyDetectionParserPlugin.js
- lib/dependencies/HarmonyExportDependencyParserPlugin.js
- lib/dependencies/HarmonyExportExpressionDependency.js
- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- lib/dependencies/HarmonyExportSpecifierDependency.js
- lib/dependencies/HarmonyImportDependency.js
- lib/dependencies/HarmonyImportDependencyParserPlugin.js
- lib/dependencies/HarmonyImportSideEffectDependency.js
- lib/dependencies/HarmonyImportSpecifierDependency.js
- lib/dependencies/ImportDependenciesBlock.js
- lib/dependencies/ImportDependency.js
- lib/dependencies/ImportEagerDependency.js
- lib/dependencies/ImportParserPlugin.js
- lib/dependencies/ImportWeakDependency.js
- lib/dependencies/ModuleDecoratorDependency.js
- lib/optimize/ConcatenatedModule.js
refactor
existing tests
yes
Some dependencies had `originModule` constructor argument and property. This is no longer the case. One can ask the ModuleGraph for the (origin) module via `getParentModule`.
> remove originModule from Dependencies and add parent module to ModuleGraph

- lib/Stats.js
- schemas/WebpackOptions.json
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/concat-and-sideeffects/webpack.config.js
- test/statsCases/scope-hoisting-bailouts/webpack.config.js
- test/statsCases/scope-hoisting-multi/webpack.config.js
- test/statsCases/side-effects-issue-7428/webpack.config.js
- test/statsCases/side-effects-simple-unused/webpack.config.js
A module is an _orphan_ if it is not included in any chunk. Orphans modules are now hidden by default in `Stats`.
feature
yes
yes
New stats option `orphanModules`, defaults to `false`.
> Hide orphan modules in Stats

- lib/Chunk.js
Refactoring
No
No
Minor changes in `compareTo` method.
Moved `sort()` after size checking to avoid needless sorting if sizes are different.
Also similar changes inside while loop to avoid needless `b.next()`
> Avoid needless sort in Chunk compare

- lib/ProgressPlugin.js
`…` is causing terminals like git bash on windows to output unnecessary spaces
- Fixes #7274 
- Fixes #7979 
a bugfix
no
no
nothing
> solving outputing unnecessary spaces

- bin/webpack.js
refactoring
no required
no
no
After merge need patch release and we archived `webpack-command`
> refactor: remove `webpack-command` from CLIs

- azure-pipelines.yml
- test/statsCases/define-plugin/webpack.config.js
> add windows to the azure pipeline

- README.md
ref: http://sassnotsass.com/
Fix a typo on the `README.md` file.
Not necessary.
No breaking change.
No update required.
> docs(readme.styling): write correctly sass

- lib/ChunkTemplate.js
- lib/Compilation.js
- lib/JavascriptModulesPlugin.js
- lib/MainTemplate.js
- lib/node/NodeMainTemplatePlugin.js
- lib/wasm/WasmMainTemplatePlugin.js
- lib/web/JsonpMainTemplatePlugin.js
- lib/webworker/WebWorkerMainTemplatePlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
instead of trying to calculate it
from inputs
fixes #8027
fixes #7984
bugfix
existing tests
no
nothing
> hash content of bootstrap code

- lib/node/NodeMainTemplatePlugin.js
closes #8032.
For `async-node` target, it creates template to resolve path to chunk bundles via string concat, ends up creating slash-mixed paths on windows platform, fail to some tools like vs code resolves correct sources. This PR updates template to use `path.resolve` instead to have platform agnostic path resolving behavior. `getAssetPath` still generates using fixed separator in slashes, but let it just correctly resovled via `path.resolve` directly instead of trying to make changes to those logics.
- manually verified behavior, bit unsure where would be best to add test cases for this.
No.
> fix(nodemaintemplate): resolve async chunk path platform agnostic

- lib/SourceMapDevToolPlugin.js
- test/ConfigTestCases.test.js
- test/configCases/source-map/default-filename-extensions-css/index.js
- test/configCases/source-map/default-filename-extensions-css/test.js
- test/configCases/source-map/default-filename-extensions-css/webpack.config.js
- test/configCases/source-map/default-filename-extensions-js/index.js
- test/configCases/source-map/default-filename-extensions-js/test.js
- test/configCases/source-map/default-filename-extensions-js/webpack.config.js
- test/configCases/source-map/default-filename-extensions-mjs/index.js
- test/configCases/source-map/default-filename-extensions-mjs/test.js
- test/configCases/source-map/default-filename-extensions-mjs/webpack.config.js
Fixes: https://github.com/webpack/webpack/issues/7927.
I didn't see any tests for the existing behavior in [`test/SourceMapDevToolModuleOptionsPlugin.unittest.js`](https://github.com/webpack/webpack/blob/v4.17.1/test/SourceMapDevToolModuleOptionsPlugin.unittest.js), so I wasn't sure how best to add tests for this. Let me know if you think it needs tests.
Nope.
/cc @mathiasbynens as FYI.
> Add sourcemap support for .mjs output files

- lib/WebpackOptionsApply.js
- lib/ids/DeterministicModuleIdsPlugin.js
- lib/webpack.js
- schemas/WebpackOptions.json
- test/TestCasesDevtoolEvalDeterministicModuleIds.test.js
- test/configCases/hash-length/deterministic-module-ids/files/file1.js
- test/configCases/hash-length/deterministic-module-ids/files/file10.js
- test/configCases/hash-length/deterministic-module-ids/files/file11.js
- test/configCases/hash-length/deterministic-module-ids/files/file12.js
- test/configCases/hash-length/deterministic-module-ids/files/file13.js
- test/configCases/hash-length/deterministic-module-ids/files/file14.js
- test/configCases/hash-length/deterministic-module-ids/files/file15.js
- test/configCases/hash-length/deterministic-module-ids/files/file2.js
- test/configCases/hash-length/deterministic-module-ids/files/file3.js
- test/configCases/hash-length/deterministic-module-ids/files/file4.js
- test/configCases/hash-length/deterministic-module-ids/files/file5.js
- test/configCases/hash-length/deterministic-module-ids/files/file6.js
- test/configCases/hash-length/deterministic-module-ids/files/file7.js
- test/configCases/hash-length/deterministic-module-ids/files/file8.js
- test/configCases/hash-length/deterministic-module-ids/files/file9.js
- test/configCases/hash-length/deterministic-module-ids/index.js
- test/configCases/hash-length/deterministic-module-ids/webpack.config.js
feature
yes
no
`opimization.moduleIds: "deterministic"`
module names are hashed into small numeric values. This is useful for long term caching, but still results in small bundles compared to `"hashed"`. Length of the numeric value is chosen to fill a maximum of 80% of the id space. By default a minimum length of 3 digits is used. Use the `webpack.ids.DeterministicModuleIdsPlugin` (+ `optimization.moduleIds: false`) for more options.
> add moduleIds deterministic for simpler long term caching

- README.md
This proposes a status badge in the README.md for the Azure Pipelines CI build.
> Add a status badge for the azure pipelines CI build

- lib/Compilation.js
- test/configCases/errors/exception-in-chunk-renderer/errors.js
- test/configCases/errors/exception-in-chunk-renderer/index.js
- test/configCases/errors/exception-in-chunk-renderer/webpack.config.js
Prior to 4.19.0, exceptions thrown by plugins that hooked any of the bootstrap rendering events (e.g. `beforeStartup`, `requireEnsure`, etc.) were caught and the error message was added to `compilation.errors`.  This occurred because compilation.createChunkAssets() has a try/catch block that catches and processes exceptions thrown by the renderers.
Starting with 4.19.0, the bootstrap rendering code is now also called via compilation.createHash().  Any exceptions thrown by the rendering code from this call are not caught and the exceptions propagates up to node and the application is terminated.
This pr adds exception handling code to compilation.createHash() that is similar to what compilation.createChunkAssets() does so that  exceptions thrown by bootstrap rendering code will be handled …
> Uncaught exception from renderers

- lib/optimize/ConcatenatedModule.js
- test/configCases/scope-hoisting/harmony-pure-default/index.js
- test/configCases/scope-hoisting/harmony-pure-default/module1.js
- test/configCases/scope-hoisting/harmony-pure-default/module2.js
- test/configCases/scope-hoisting/harmony-pure-default/module3.js
- test/configCases/scope-hoisting/harmony-pure-default/module4.js
- test/configCases/scope-hoisting/harmony-pure-default/webpack.config.js
> fixes #8085

- test/configCases/target/amd-unnamed/index.js
While working on #8093, I noticed that the "should name define" test for unnamed AMD library target output was tautological, in that the test was matching a string against itself. Changing the test to use a regexp makes it actually test what it tries to test.
Yes?
No.
Nothing.
> Fix the "should name define" test in configCases/target/amd-unnamed

- declarations/WebpackOptions.d.ts
- declarations/plugins/DllReferencePlugin.d.ts
- lib/AmdMainTemplatePlugin.js
- lib/ExternalModule.js
- lib/LibraryTemplatePlugin.js
- schemas/WebpackOptions.json
- schemas/plugins/DllReferencePlugin.json
- test/configCases/target/amd-require/index.js
- test/configCases/target/amd-require/webpack.config.js
This is a partial fix for #8079.
This PR adds `"amd-require"` as a new library target. The target is otherwise the same as `"amd"`, except that it uses `require()` as a wrapper instead of `define()`. The specification for this API is [here](https://github.com/amdjs/amdjs-api/blob/master/require.md).
Specifically, we're using the global `require(dependencies, factory)` form, which will resolve the dependencies, and then immediately call the factory function with them as parameters. The library name is ignored in this case.
The rationale for including this target is that it enables compiling an immediately executed module that has AMD dependencies, which has not been previously possible with Webpack. As is, AMD dependencies are only resolved …
> Add "amd-require" libraryTarget, resulting in a require() wrapper

- lib/web/JsonpMainTemplate.runtime.js
- lib/web/JsonpMainTemplatePlugin.js
The variable `$crossOriginLoading$` looks like it's not used and static analysis will suggest removing it.
It was introduced in commit 6aa31547531d51b317c4b318ec214de9bf183099 from PR #988. 
A comment from @Aladdin-ADD makes me believe I'm not the only one who thought this variable was unused.
Code cleanup. I refactored the code a bit to avoid this confusion (I hope) for future users reading the code. The default value of `script.crossOrigin` is null so this will assign crossOrigin to the value specified or null if nothing was specified.
No, the behavior is unaffected.
No
Nothing, no change to …
> Refactor usage of $crossOriginLoading$

- lib/Compilation.js
Addresses concerns in #8126 by attempting to implement suggestions from @sokra to optimize `Compilation.processDependenciesBlocksForChunkGroups`.
1. Filter the dependencies without modules within the for loop, rather than using `.filter()` to allocate a new array (lines 1870-1879)
2. Re-use availableModule sets that only have one entry, rather than copying them (lines 1844 and 1900)
3. Avoid expensive `areModulesAvailable()` call when a chunk has already survived a filter. (lines 1818-1823).
I've probably mangled sokra's ideas beyond recognition, but opening this PR so he can more easily comment on what I should do. Currently, I'm not actually seeing perf improvements from these changes.
Performance improvement (without any intended …
> Make changes suggested by @sokra to optimize chunk graph generation

- .travis.yml
- appveyor.yml
- azure-pipelines.yml
- package.json
- yarn.lock
Reverts webpack/webpack#8120
It's too silent and missing the summary, which is displayed by the bot in the comment
> Revert "Re-enable jest-silent-reporter #hacktoberfest"

- declarations/WebpackOptions.d.ts
- lib/WarnDeprecatedOptionPlugin.js
- lib/WebpackOptionsApply.js
- schemas/WebpackOptions.json
- test/configCases/code-generation/require-context-id/warnings.js
- test/configCases/delegated-hash/simple/warnings.js
- test/configCases/dll-plugin/3-use-dll-with-hashid/warnings.js
- test/configCases/optimization/hashed-module-ids/warnings.js
Deprecate `moduleIds=hashed` in favor of `moduleIds=deterministic`.
Also remove `moduleIds=total-size`.
feature
yes
yes
- `optimization.moduleIds=total-size` has been removed
- `optimization.moduleIds=hashed` is deprecated. Use `deterministic` instead.
> Remove moduleIds=total-size and deprecate moduleIds=hashed

- lib/ChunkGroup.js
Also remove useless `TODO` comment.
refactoring
no
no (unless someone is using private fields)
nothing
> Rename index/index2 to pre/postOrderIndices

- test/cases/wasm/export-imported-global/index.js
- test/cases/wasm/imported-global-preserve-ordering/index.js
The current version of the WebAssembly JS API specification [1]
exports globals as WebAssembly.Global, rather than as Numbers. This
version of the API is shipped in Chrome 69 and Firefox 62, and is
also seen in Node 11 nightly builds.
This patch updates webpack's tests to permit either the new API or
the old one, for exports of WebAssembly Globals. One of the affected
tests passes on Node 11 (where it previously failed), and the other
fails for unrelated reasons (possibly related to [2]).
Fixes #8145
[1] https://webassembly.github.io/spec/js-api/index.html
[2] https://github.com/webpack/webpack/pull/7467/files#r223454525
Permit either the old (Number) or the new (WebAssembly.Global) behavior for exported globals.
**Did you add tests for your …
> Update tests for new WebAssembly.Global API

- .travis.yml
- lib/Chunk.js
- lib/Compilation.js
- lib/Entrypoint.js
- lib/Stats.js
- lib/optimize/LimitChunkCountPlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/setupTestFramework.js
> fix some compilation stablility issues

- lib/Compilation.js
performance
existing tests
no
nothing
> Optimize chunk graph algorithm

- lib/Compiler.js
- lib/Watching.js
- test/Compiler.test.js
Add an `watchMode` flag in `Compiler`. It closes #3460.
In `Compiler.js`, added `watchMode` boolean, that is set as `true` in `Watching.js`.
Yes
No
> Adding watchMode flag in compiler

- lib/Chunk.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/limit-chunk-count-plugin/index.js
This PR changes the behavior of `Chunk#integrate` to prefer chunks with an entry module when picking a name. If none have an entry module, the old algorithm is used instead, where the chunk with the shortest name is picked.
See #7516 for the bug report.
This change is a bugfix.
I could not find tests related to this change. Do you want me to add them?
This PR introduces a breaking change by changing the behavior of `Chunk#integrate`. Projects, plugins and internal code relying on the fact that the shortest name is picked when integrating two chunks may break. However, I think more people are affected by the current behavior.
**What needs to be documented …
> Prefer chunks with entry module when picking name (#7516)

- lib/Compiler.js
- lib/WatchIgnorePlugin.js
- lib/Watching.js
- lib/node/NodeWatchFileSystem.js
- test/RemoveFiles.test.js
- Fixes #5072
That watchRun now exposes removed files.
> feat(Compiler): Add file removal tracking in watch-run

- lib/DefinePlugin.js
- test/watchCases/plugins/define-plugin/0/index.js
- test/watchCases/plugins/define-plugin/0/module3.js
- test/watchCases/plugins/define-plugin/webpack.config.js
when `fileDependecies` arg on `runtimeValue` is `true`
closes #7717
yes
no
Some info about `runtimeValue`
> DefinePlugin: reevaluate runtime values on watch mode

- declarations/WebpackOptions.d.ts
- lib/cache/FileCachePlugin.js
- lib/serialization/FileMiddleware.js
- lib/serialization/MapObjectSerializer.js
- lib/serialization/ObjectMiddleware.js
- lib/util/makeSerializable.js
- schemas/WebpackOptions.json
- test/TestCases.template.js
- test/TestCasesCacheInstant.test.js
- test/TestCasesCachePack.test.js
- test/setupTestFramework.js
feature
yes
no
`cache.store: "pack"` was added. This mode stores all cache entries in a single file, including garbage collection for old entries.
* 😄 Less filesystem access
* 😄 Faster, as all cache entries are deserialized at once
* 😄 Smaller data, as deduplication happens between cache entries
* 😄 Handles small cache entries have less overhead compared to separate files
* Especially relevant when the resolver cache is added
* 😄 Has Garbage Collection (entries are removed after 2 days unused)
* Need to add option for that
* 😢 Unnecessary cache entries are deserialized and serialized until …
> add pack store mode for filesystem cache

- lib/DefinePlugin.js
- test/configCases/plugins/define-plugin/index.js
- test/configCases/plugins/define-plugin/webpack.config.js
PR #6793 added the ability for DefinePlugin to use function that return values.
This PR just add the ability to these functions to access the module being parsed (see #8301).
eg.
```
webpack.DefinePlugin.runtimeValue(module => module.resource ....)
```
issue #8301
It adds a `module` an argument to fct in DefinePlugin.runtimeValue(fct)
yes
no
About the additional `module` argument
> add module argument to DefinePlugin.runtimeValue functions

- declarations/WebpackOptions.d.ts
- lib/NormalModuleFactory.js
- lib/ResolverFactory.js
- lib/WebpackOptionsApply.js
- lib/WebpackOptionsDefaulter.js
- lib/cache/FileCachePlugin.js
- lib/cache/ResolverCachePlugin.js
- schemas/WebpackOptions.json
Replaces the unsafe resolver cache with a safe (re-validated) resolver cache which uses the (persistent) caching infrastructure.
As this stores many small cache entries it should be used with packed filesystem store mode. #8272 
feature
existing tests
yes
nothing
> add safe (persistent) resolver cache

- declarations/plugins/DllPlugin.d.ts
- lib/DllPlugin.js
- lib/LibManifestPlugin.js
- schemas/plugins/DllPlugin.json
- test/configCases/dll-plugin-format/0-create-dll/dep.js
- test/configCases/dll-plugin-format/0-create-dll/index.js
- test/configCases/dll-plugin-format/0-create-dll/test.config.js
- test/configCases/dll-plugin-format/0-create-dll/utility.js
- test/configCases/dll-plugin-format/0-create-dll/webpack.config.js
Adding a feature (option) for DLL Plugin to format manifest json output file.
I assume no tests are required.
This doesn't introduce a breaking change.
1. Change documentation for DLL Plugin and add a new option called "format" and it's use.
I will make a change to the documentation, to add format options in DLL Plugin documentation.
This Pr is for the issue #7992.
> Adding format option for Dll Plugin to get a formatted manifest json. #7992

- lib/WebpackOptionsDefaulter.js
- test/Compiler.test.js
- test/__snapshots__/ConfigTestCases.test.js.snap
- test/__snapshots__/StatsTestCases.test.js.snap
closes #8268
just updated snapshots
no (?)
about `optimization.moduleIds`
> Set deterministic module ids in prod by default

- lib/ProvidePlugin.js
- test/configCases/plugins/provide-plugin/foo.mjs
- test/configCases/plugins/provide-plugin/index.js
- test/configCases/plugins/provide-plugin/webpack.config.js
#7032
bugfix
updated a test case.
not sure, I guess no. 😄 
> fix: disable ProvidePlugin for javascript/esm (fixes #7032)

- declarations/plugins/BannerPlugin.d.ts
- lib/BannerPlugin.js
- lib/Compilation.js
- lib/JavascriptModulesPlugin.js
- lib/LibManifestPlugin.js
- lib/SourceMapDevToolPlugin.js
- lib/TemplatedPathPlugin.js
- lib/WebpackOptionsDefaulter.js
- lib/wasm/WebAssemblyModulesPlugin.js
- schemas/plugins/BannerPlugin.json
Needed for #6446
Existing tests (Could need additional tests for `module` context, better done in #6446)
**`webpack.config.js`**
```js
const config = {
output: {
filename: '[name].[contenthash].js' // e.g bundle.68545679.js
webassemblyFilename: '[name].[hash].[ext]' // e.g module.43875468.wasm
}
}
```
```js
const file = Object {
path: data.filename || "",
ext: extname(data.filename),
base: basename(data.filename),
name: file.base.replace(file.ext, ""),
query: ""
}
```
|Name|Replacer|
|:----:|:--------:|
|`[id]`|`chunk.id`|
|**`[ext]`**|**`file.ext`**|
|`[name]`|`chunk.id\|chunk.name`| …
> refactor(TemplatedPathPlugin): split placeholder context (`chunk|module`)

- azure-pipelines.yml
- package.json
> move azure specific commands to azure-pipelines.yml

- lib/BasicEvaluatedExpression.js
- lib/Parser.js
- lib/dependencies/ContextDependencyHelpers.js
- test/configCases/plugins/define-plugin/index.js
- test/configCases/plugins/define-plugin/webpack.config.js
> Bugfix for #8293

- test/configCases/plugins/define-plugin/index.js
- test/configCases/plugins/define-plugin/webpack.config.js
this highlights issue #8293
no
nothing
> test for #8293

- lib/DependencyTemplate.js
- lib/JavascriptGenerator.js
- lib/dependencies/CachedConstDependency.js
- lib/dependencies/HarmonyAcceptImportDependency.js
- lib/dependencies/HarmonyCompatibilityDependency.js
- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- lib/dependencies/HarmonyExportSpecifierDependency.js
- lib/dependencies/HarmonyImportDependency.js
- lib/dependencies/HarmonyImportSideEffectDependency.js
- lib/dependencies/ModuleDecoratorDependency.js
- lib/dependencies/ProvidedDependency.js
- lib/optimize/ConcatenatedModule.js
- test/HotModuleReplacementPlugin.test.js
Refactor getInitFragments to a property in templateContext and apply method
Having only a single method in DependencyTemplate makes it easier to override
refactor
existing test
yes, but with compat layer
DependencyTemplate.getInitFragments no longer exist and was replaced with a `initFragments` argument in the DependencyTemplate.apply method
> Refactor getInitFragments

- buildin/global.js
If use CSP (without `unsafe-eval`), both `new Function` and `eval` will be forbidden, so `eval` part is just dead code.
The only possibility `eval` part would run was `new Function('return this')()` return a falsy value, but it never possible as the spec (Is there any old engine violate this? Never heard about that.)
This pr also add `new` keyword to make the code a little bit explicit.
clean unuseful code
no need
no
no need
> Drop unuseful `eval` call

- lib/util/deterministicGrouping.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/split-chunks-max-size/webpack.config.js
fixes #8407
bugfix
yes
no
nothing
> while grouping nodes include at least one node on each side

- lib/ProgressPlugin.js
- lib/SourceMapDevToolPlugin.js
- test/configCases/plugins/progress-plugin/webpack.config.js
`ProgressPlugin` uses `Tap.context` to expose `reportProgress` which is unnecessary. This PR removes `Tap.context` usage in favor of a `WeakMap`.
While this API is not as convenient as the previous one, it ensures that webpack no longer rely on `Tap.context` and demonstrates that the previous API could be achieved in user-land.
refactoring
already exists
yes
`context.reportProgress` is no longer available. It has been replaced by `ProgressPlugin.getReporter(compilation)`
> Remove context usage in ProgressPlugin

- declarations/WebpackOptions.d.ts
- lib/webpack.js
- schemas/WebpackOptions.json
> Hello, here's a small change ...
/lib/webpack.js (now)
```
if (typeof plugin === "function") {
plugin.apply(compiler);  // missing parameter
} else {
plugin.apply(compiler);
}
```
/lib/webpack.js (after)
```
if (typeof plugin === "function") {
plugin.apply(null, [compiler]); // yes
} else {
plugin.apply(compiler);
}
```
/declarations/WebpackOptions.d.ts
```
type WebpackPluginFunction = (
compiler: import("../lib/Compiler")
) => void;
```
a bugfix
> fix parameter missing  when plugin type is a funtion

- lib/Chunk.js
Cache `this.hasRuntime()`, `otherChunk.hasRuntime()` in variable. Because in some cases these methods call twice.
Refactoring
No
No
No
> Cache hasRunstime in chunk

- lib/optimize/MinMaxSizeWarning.js
- lib/optimize/SplitChunksPlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/split-chunks-max-size/webpack.config.js
enforce now works as documented
emit warning for minSize > maxSize configuration
performance improvements
bugfix when multiple cacheGroups have the same name
fixes #8407
bugfix
yes
yes, but a bugfix
`enforce` now works as documented.
> Tells webpack to ignore splitChunks.minSize, splitChunks.maxSize, splitChunks.minChunks, splitChunks.maxAsyncRequests and splitChunks.maxInitialRequests options and always create chunks for this cache group.
But there is a little error in the documentation as `splitChunks.maxSize` is not ignored.
Tells webpack to ignore splitChunks.minSize, splitChunks.minChunks, …
> enforce doesn't affect minSize for maxSize

- lib/NormalModule.js
- lib/ResolverFactory.js
- test/cases/loaders/resolve/index.js
- test/cases/loaders/resolve/loader.js
with allows to pass options
feature
yes
no
new `getResolve` method in loader context. An optional `options` object is merged with the original resolve options in the current module. For performance reasons try to pass the same object identity for every call.
``` js
getResolve(options?: Object) => ResolveFunction
ResolveFunction = (context: string, request: string, callback: ResolveCallback) => void
ResolveFunction = (context: string, request: string) => Promise<string>
ResolveCallback = (err?: Error, path?: string, data?: Object) => void
```
> add getResolve method to loader context

- lib/DelegatedModuleFactoryPlugin.js
- lib/WebpackOptionsDefaulter.js
Fixes #8445
Bugfix
No, not sure what kind of test should I add
No
https://github.com/webpack/webpack.js.org/blob/master/src/content/configuration/resolve.md#resolveextensions
> fix: `.wasm` extension should have lower priority when resolving modules

- lib/optimize/SplitChunksPlugin.js
- test/statsCases/split-chunks-automatic-name/webpack.config.js
Partial revert "enforce doesn't affect minSize for maxSize" #8451 
bugfix
yes
It reverts an accidental breaking introduces by #8451
The splitChunks.enforce documentation is incorrect.
It should be stated that `enforce` sets `minChunks: 1`, `minSize: 0` and `maxInitial/AsyncRequests: Infinity`, but it's supported that this can be overriden by the same property on the cacheGroup
> enforce should not prevent using `minChunks` etc. on cacheGroup

- lib/web/JsonpMainTemplate.runtime.js
- lib/web/JsonpMainTemplatePlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
Instead of `document.getElementsByTagName('head')[0]` we can use `document.head`. It works in IE9.
https://developer.mozilla.org/ru/docs/Web/API/Document/head
Refactoring
No
It doesn't work in IE8.
> Use document.head instead of getElementsByTagName('head')

- lib/MultiCompiler.js
- lib/WebpackOptionsApply.js
- lib/index.js
- lib/webpack.js
- package.json
- test/BenchmarkTestCases.benchmark.js
- test/Compiler-caching.test.js
- test/Compiler.test.js
- test/ConfigTestCases.test.js
- test/Errors.test.js
- test/Examples.test.js
- test/HotModuleReplacementPlugin.test.js
- test/HotTestCases.template.js
- test/MultiCompiler.test.js
- test/NodeTemplatePlugin.test.js
- test/ProgressPlugin.test.js
- test/RemoveFiles.test.js
- test/Stats.test.js
- test/StatsTestCases.test.js
- test/TestCases.template.js
- test/TestCasesAllCombined.test.js
- test/TestCasesHot.test.js
- test/TestCasesHotMultiStep.test.js
- test/Validation.test.js
- test/WatchDetection.test.js
- test/WatchTestCases.test.js
- test/WatcherEvents.test.js
- Removes `Compiler#dependencies` in favor of `MultiCompiler#setDependencies`
- Renames `lib/webpack.js` into `lib/index.js`
- Moves `webpack` function into `lib/webpack.js`
- Refactors `webpack` to better handle multi-options
refactoring
no
yes
`Compiler#dependencies` has been removed.
> Refactor webpack main

- package.json
- yarn.lock
`webpack/hot/emitter.js` requires `events`.
This package used to be polyfilled automatically.
Now it requires the dependency to be manually installed.
bugfix
no
no
nothing
> Add 'events' dependency

- lib/ids/IdHelpers.js
I just optimized code which gets digits. `match` with `regexp + join` is not fast solution. I rewrote it without using RegExp and temporary arrays.
I tested speed of changed part of function https://jsperf.com/webpack-gethashnumber
Refactoring
No
No
> Optimize getHashNumber

- lib/ExternalModuleFactoryPlugin.js
to be more extensible in future
#8527
refactor
no
yes, externals function signature changed
passing a function to `externals` has now this signature:
`({ context, request }, callback)`
> Change signature of externals function to an object

- examples/http2-aggressive-splitting/template.md
This is done via the template.md file which is used to build README.md
Documentation revisions only.
> Fix minor typos, improve clarity of README

- lib/MultiStats.js
- test/MultiStats.test.js
While attempting to upgrade a plugin to support v5 tests started failing, due to [a test that called toJson on stats returned from a multi-target build](https://github.com/jahredhope/html-render-webpack-plugin/blob/master/tests/test-cases/webpack-stats/src/render.js#L2).
This issue is only available in the alpha branch so I haven't raised an issue. See comment in v5 alpha branch feedback.
Issue: https://github.com/webpack/webpack/issues/8537#issuecomment-450118762
This change will allow consumers to call toJson and toString safely without any additional options. There is no change when options are passed in.
This is a bug fix to address an unreleased regression. Related change: https://github.com/webpack/webpack/commit/123b0a64e78d154e4c326c8 …
> Allow MultiStats to be called with no options

- test/HotTestCases.template.js
- test/NodeTemplatePlugin.test.js
- test/configCases/hash-length/output-filename/webpack.config.js
- test/configCases/issues/issue-7563/webpack.config.js
- test/configCases/plugins/banner-plugin-hashing/index.js
- test/configCases/plugins/banner-plugin-hashing/webpack.config.js
- test/configCases/plugins/lib-manifest-plugin/webpack.config.js
- test/hotPlayground/webpack.config.js
Some tests were using `hash` instead of `fullhash`.
remove some deprecation notices from the tests
no
no
nothing
> Use fullhash instead of hash in tests

- package.json
- test/__snapshots__/StatsTestCases.test.js.snap
- yarn.lock
This PR updates terser to `^1.2.1` to remove deprecation notices.
fix
no
no
nothing
> Update terser to make it compatible with v5

- lib/debug/ProfilingPlugin.js
- test/ProfilingPlugin.test.js
- test/ProfilingPlugin.unittest.js
This is a fix for the below issue. Profiling plugin will create a folder based on the output path, if it doesn't exists.
https://github.com/webpack/webpack/issues/8503
bugfix
Yes, i have added a test for checking if folder is getting created in the provided path.
No
No documentation needed.
> Fixed error in Profiling Plugin, if given folder path doesn't exist.

- test/configCases/optimization/minimizer/index.js
- test/configCases/optimization/minimizer/webpack.config.js
As discussed offline with @sokra, this is a fix for when you provide a function entry for `optimization.minimizer` config.
bugfix (related: https://github.com/webpack/webpack/pull/8405)
No, should i?
No
Done: https://github.com/webpack/webpack.js.org/pull/2743
> fix when minimizer is fn

- lib/web/JsonpChunkLoadingRuntimeModule.js
- test/__snapshots__/StatsTestCases.test.js.snap
This fixes a bug in the v5 branch of webpack. Before this change, the code emitted when prefetching chunks from the runtime chunk had two errors:
1. It didn't join the mapped array into a string, so extraneous `,` characters were added that did not parse.
2. It didn't wrap the chunk names in quotes; as such, they were treated as undefined identifiers.
Bug fix (see https://github.com/webpack/webpack/issues/8537#issuecomment-450979354)
Not yet. I'm unsure how to add tests that simply verify that emitted Javascript parses, which would have caught this issue.
No
Nothing; this is a bugfix;
> Fix emit for prefetching chunks from runtime chunk

- lib/dependencies/HarmonyDetectionParserPlugin.js
As discussed offline with @sokra, this change is meant to allow faster statement type lookup's. Based on https://jsperf.com/exact-pattern-vs-dot-star/1
perf
N/A
No
N/A
> perf: use faster statement type check

- lib/WebpackOptionsValidationError.js
- lib/util/createHash.js
I added second argument(limit) for string `split` to performance reason.
Refactoring
No
No
> Use limit for string split

- lib/serialization/FileMiddleware.js
On a large project with resolver cache enabled the total size of all serialized chunks in `FileMiddleware:: serialize` can reach hundreds of megabytes (~800 MB in our case). `Buffer.concat` call [here](https://github.com/webpack/webpack/blob/next/lib/serialization/FileMiddleware.js#L299) duplicates this data. [Node source for a reference](https://github.com/nodejs/node/blob/master/lib/buffer.js#L467).
This PR changes `FileMiddleware` to use node.js streams for writing the data into the file without concatenation.
Performance improvement
Existing `TestCasesCachePack`/`TestCasesCacheInstant` should cover it
No
**What needs to be documented once your changes …
> Improve memory consumption of file serialization middleware

- lib/WebpackOptionsDefaulter.js
It's not possible for a `.json` file to be a [valid loader](https://github.com/webpack/loader-runner/blob/master/lib/loadLoader.js#L29). This change aims to make the default config reflect this fact.
config defaults improvement
N/A
No.
is this needed?
> New resolveLoader.extensions defaults

- declarations/WebpackOptions.d.ts
- lib/Compilation.js
- lib/Compiler.js
- lib/Stats.js
- schemas/WebpackOptions.json
add a new version of emitting assets which allows to free memory of Sources with the trade-off of disallowing reading asset content after emitting
It also uses Source.buffer when available.
memory
no (it will be tested in the next branch, when it's on by default)
no
New option `output.futureEmitAssets` allows to opt-in to the new way of emitting assets which allows to free memory of Sources with the trade-off of disallowing reading asset content after emitting
> add output.futureEmitAssets

- declarations/WebpackOptions.d.ts
- lib/Compilation.js
- lib/FlagDependencyExportsPlugin.js
- lib/FlagDependencyUsagePlugin.js
- lib/FlagInitialModulesAsUsedPlugin.js
- lib/FunctionModuleTemplatePlugin.js
- lib/LibManifestPlugin.js
- lib/Module.js
- lib/ModuleGraph.js
- lib/WebpackOptionsApply.js
- lib/WebpackOptionsDefaulter.js
- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- lib/dependencies/RequireIncludeDependency.js
- lib/optimize/ConcatenatedModule.js
- lib/optimize/MangleExportsPlugin.js
- lib/optimize/ModuleConcatenationPlugin.js
- lib/optimize/SideEffectsFlagPlugin.js
- lib/wasm/WasmFinalizeExportsPlugin.js
- schemas/WebpackOptions.json
- test/TestCases.template.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/configCases/deep-scope-analysis/remove-export-scope-hoisting/webpack.config.js
- test/configCases/deep-scope-analysis/remove-export/webpack.config.js
New `ExportsInfo` object in `ModuleGraph` tracks all info regarding exports.
refactoring
existing tests
yes
`module` argument of `getDependencyReference` was removed
It's possible to get the module of a dependency with `ModuleGraph.getParentModule` so this is not needed.
Removing it reduces complexity of other code
new option `optimization.mangleExports` allows to enable/disable export mangling
By default it's only enabled in production mode.
> refactoring of used and provided exports

- lib/NodeStuffPlugin.js
- test/configCases/runtime/invalid-esm-export/esm-export.js
- test/configCases/runtime/invalid-esm-export/esm-import-cjs-export.js
- test/configCases/runtime/invalid-esm-export/index.js
- test/configCases/runtime/invalid-esm-export/webpack.config.js
Consider the following invalid es module:
```js
import foo from 'foo';
module.exports = 'bar';
```
Obviously this is wrong... However, you will only learn of this breaking at runtime.
Since there is an import declaration - when type is `javascript/auto` webpack will determine ESM. Though, the cjs export is obviously incorrect and will definitely break at runtime.
The problem is this error is cryptic/a byproduct of the actual issue: `Cannot assign to read only property 'exports' of object '#<Object>`.
This pr aims to improve this error message.
small refactor, i guess?
Yes
No
N/A
> Improve error report of invalid esm export

- lib/ContextModule.js
- lib/MainTemplate.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/cases/chunks/import-context-exist-chunk/dir-initial-with-fake-map/initialModule.js
- test/cases/chunks/import-context-exist-chunk/dir-initial-with-fake-map/initialModule2.js
- test/cases/chunks/import-context-exist-chunk/dir-initial/initialModule.js
- test/cases/chunks/import-context-exist-chunk/index.js
Fix #8626.
This bug exists in webpack 4. but v5 doesn't(seems disappeared after refactoring). 
bugfix
yes
no
nothing.
> Fix: Add missed __webpack_require__.e while importing exist module with context

- lib/WebpackOptionsApply.js
Instead of requiring plugins at the top of the file, they are required right before their instantiation. This can help shrink bootup cost as not all plugins will need to be required.
Refactoring/Performance tweak
N/A
No
N/A
> Only Require Plugins When Needed

- declarations/WebpackOptions.d.ts
- lib/WebpackOptionsApply.js
- schemas/WebpackOptions.json
- test/configCases/amd/disabled/index.js
- test/configCases/amd/disabled/webpack.config.js
As discussed with @sokra:
Introduces a new value `false` for `options.amd` that disables AMD support completely.
This would mainly be useful in for example ncc, Next.js etc where it’s either fully commonjs/esmodules (ncc) or fully esmodules (Next.js)
Feature
Still have to add one 👍
No
https://webpack.js.org/configuration/other-options/#amd
- The `amd` value can be set to `false` which will disable webpack's AMD support.
> Allow options.amd to disable AMDPlugin/RequireJsStuffPlugin

- lib/WebpackOptionsDefaulter.js
- package.json
- yarn.lock
This is a small PR in order to use the same behaviour to calculate the default cache dir on webpack that we are already using into the loaders. It was discussed here https://github.com/webpack-contrib/cache-loader/pull/64
/CC @evilebottnawi
> Use find-cache-dir in order to calculate the webpack default cache directory

- yarn.lock
Tests can't be executed with the following error when using Node v11.11.0.
jest's issue is https://github.com/facebook/jest/issues/8069.
```
TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<process>'
```
no
no
N/A
> [next]: update jest

- test/TestCases.template.js
Currently, we have the following warning so we fix it.
```
A "describe" callback must not return a value.
Returning a value from "describe" will fail the test in a future version of Jest.
62 |                                                const filterPath = path.join(testDirectory, "test.filter.js");
63 |                                                if (fs.existsSync(filterPath) && !require(filterPath)(config)) {
> 64 |                                                        describe.skip(test, () => it("filtered"));
|                                                                 ^
65 |                                                        return false;
66 |                                                }
67 |                                                return true;
at …
```
> test(TestCases): don't return a value at `describe.skip` and `it`

- bin/webpack.js
refactoring
no
no
N/A because webpack-command is already depricated.
```sh
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
- webpack-cli (https://github.com/webpack/webpack-cli)
The original webpack full-featured CLI.
We will use "yarn" to install the CLI via "yarn add -D".
Do you want to install 'webpack-cli' (yes/no): 
```
```sh
CLI for webpack must be installed.
webpack-cli (https://github.com/webpack/webpack-cli)
We will use "yarn" to install the CLI via "yarn add -D".
Do you want to install 'webpack-cli' (yes/no): 
```
> fix(bin): remove webpack-command

- lib/Compilation.js
- lib/Compiler.js
- test/configCases/finish-modules/simple/index.js
- test/configCases/finish-modules/simple/webpack.config.js
I am working on a new webpack plugin that requires access to the full module graph after the first pass. The plugin may trigger rebuilds, which could result in more modules being added to the graph — this work needs to occur before the `seal` phase begins.
Currently, `finishModules` fires at the correct time, but as `rebuild` is an async process, I can't tell webpack to wait for the rebuild before the sealing phase begins. The proposed solution is to make `finishModules` into an async hook, which **I've noticed is already the case in webpack v5**.
Ideally I'd like to release the plugin as soon as possible and have it be backwards compatible with webpack v4 for consumers.
This is a new backwards compatible feature.
**Did you add tests for …
> Convert finishModules hook to be an AsyncSeries

- declarations.d.ts
TS 3.5 and above have WebAssembly types, so the ambient declaration in declarations.d.ts needs to be compatible with that declaration. The previous declaration, `declare const`, was not. This PR changes it to `declare namespace`.
Fixes #9021
Fixes type declarations.
The build is the test. If the PR builds, the change is backward compatible.
No.
Nothing, unless you think of d.ts as documentation for humans.
> Update WebAssembly declaration

- declarations/WebpackOptions.d.ts
- lib/ExternalModule.js
- lib/LibraryTemplatePlugin.js
- lib/SystemMainTemplatePlugin.js
- schemas/WebpackOptions.json
- test/ConfigTestCases.test.js
- test/configCases/externals/externals-system/index.js
- test/configCases/externals/externals-system/test.config.js
- test/configCases/externals/externals-system/webpack.config.js
- test/configCases/target/system-export/index.js
- test/configCases/target/system-export/test.config.js
- test/configCases/target/system-export/webpack.config.js
- test/configCases/target/system-named/index.js
- test/configCases/target/system-named/test.config.js
- test/configCases/target/system-named/webpack.config.js
- test/configCases/target/system-unnamed/index.js
- test/configCases/target/system-unnamed/test.config.js
- test/configCases/target/system-unnamed/webpack.config.js
- test/helpers/fakeSystem.js
Resolves #8833. cc @sokra @guybedford
A new feature
Yes
No -- completely new feature
We'll need to update the [output.libraryTarget docs](https://webpack.js.org/configuration/output/#outputlibrarytarget) to indicate that `"system"` is now a valid output option.
> Adding support for output.libraryTarget "system"

- lib/NoModeWarning.js
- test/__snapshots__/StatsTestCases.test.js.snap
We had moved the page from /concepts to /configuration
Update copy
no
no
no
> Update link in warning

- declarations/WebpackOptions.d.ts
- lib/Stats.js
- schemas/WebpackOptions.json
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/preset-errors-warnings/webpack.config.js
I've noticed that I often need just see warnings and errors since during rapid development I don't really need to see the modules stats. So I tend to write the same code every time and it would be nice to be able to just provide an "errors-warnings" preset to save space and improve readability.
Extension to the existing stats preset.
Tests added.
No, this is a just an extension which will not break anything
The following page will need to be updated with additional stats preset option: https://webpack.js.org/configuration/stats/
> Preset option for errors & warnings only

- README.md
README.md references a link returning a 404 response code.  
Referenced URL returns 404: [https://webpack.js.org/get-started/](https://webpack.js.org/get-started/)
Updated to: [https://webpack.js.org/guides/getting-started](https://webpack.js.org/guides/getting-started)
> Updated Invalid URL Reference: "Getting Started"

- lib/Parser.js
- test/Parser.unittest.js
Fixes #9055, and possibly others, I investigated after having that issue
`enterObjectPattern` assumed all object property nodes had a value, which is not true for the `RestElement` node type, which has `argument` instead which contains the `Identifier`.
This meant that identifiers introduced by object pattern rest elements were not recognized as a variable declaration within the current scope, hence the identifier introduced by an import statement in the outer scope being used in #9055
> fix(parser): Rest element identifiers in object patterns not added to defined variables of scope

- declarations/WebpackOptions.d.ts
- lib/ContextModule.js
- lib/DelegatedModule.js
- lib/DllModule.js
- lib/ExternalModule.js
- lib/Module.js
- lib/NormalModule.js
- lib/RawModule.js
- lib/RuntimeModule.js
- lib/WebpackOptionsDefaulter.js
- lib/optimize/ConcatenatedModule.js
- lib/optimize/SplitChunksPlugin.js
- schemas/WebpackOptions.json
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/named-chunk-groups/a.js
- test/statsCases/named-chunk-groups/b.js
- test/statsCases/split-chunks-keep-remaining-size/a.js
- test/statsCases/split-chunks-keep-remaining-size/b.js
- test/statsCases/split-chunks-keep-remaining-size/c.js
- test/statsCases/split-chunks-keep-remaining-size/index.js
- test/statsCases/split-chunks-keep-remaining-size/shared.js
- test/statsCases/split-chunks-keep-remaining-size/webpack.config.js
- test/statsCases/split-chunks-prefer-bigger-splits/webpack.config.js
avoid zero sized modules as they lead to problems
add `minRemainingSize` option for splitChunks to ensure leftover chunks from splitting have a minimum size
defaults to `minSize` of cache group
defaults to global option when not specified
global option defaults to zero in development
fixes #8722
bugfix and new feature
yes
yes, splitting behavior changes
New option `splitChunks.minRemainingSize` and `splitChunks.cacheGroups.xxx.minRemainingSize`.
`minRemainingSize` defaults to `minSize` so it doesn't need to be specified manually expect in rare cases where deep control is needed. …
> add `minRemainingSize` option for splitChunks

- lib/NormalModule.js
- test/configCases/loaders/mode-default/index.js
- test/configCases/loaders/mode-default/loader.js
- test/configCases/loaders/mode-default/webpack.config.js
- test/configCases/loaders/mode-development/index.js
- test/configCases/loaders/mode-development/loader.js
- test/configCases/loaders/mode-development/webpack.config.js
- test/configCases/loaders/mode-none/index.js
- test/configCases/loaders/mode-none/loader.js
- test/configCases/loaders/mode-none/webpack.config.js
- test/configCases/loaders/mode-production/index.js
- test/configCases/loaders/mode-production/loader.js
- test/configCases/loaders/mode-production/webpack.config.js
This allows loader to conditionally apply logic based on the configured `mode`.  Without access to the `mode`, a loader author would have to access the (private) `this._compilation.compiler.options.mode` or require that users of the loader add a redundant option or set an environment variable.
New feature.
Yes.
No.
The `mode` property on the loader context needs to be documented.
Fixes #6496.
> Allow loaders to access the mode

- lib/web/JsonpMainTemplatePlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
Error created from load/error event handler has no useful stack trace whatsoever as it's an async event and stack has unwound already at that point.
To have better (sync) stacktrace of what triggered loading of the chunk, create error before stack has unwound and use it and its stacktrace later, in case of an error.
The reason this is useful, is that it allows to trace the root code that triggered problematic load of the chunk. Especially when using systems like Sentry where we don't know exactly how or where given failure has been triggered. This allows to better see the code that triggered the chunk and potentially to figure out the actual problem.
This potentially has some processing overhead as browser needs to create a stacktrace. It's probably not that big though but I haven't done …
> fix: provide useful stacktrace on chunk loading failure

- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- lib/optimize/SideEffectsFlagPlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/configCases/dll-plugin/0-create-dll/h.js
- test/configCases/dll-plugin/0-create-dll/h1.js
- test/configCases/dll-plugin/0-create-dll/ha.js
- test/configCases/dll-plugin/0-create-dll/hb.js
- test/configCases/dll-plugin/0-create-dll/webpack.config.js
- test/configCases/dll-plugin/1-use-dll/index.js
- test/configCases/dll-plugin/2-use-dll-without-scope/index.js
allow to redirect module and id in reexports
SideEffects plugin redirects reexports too
fixes #9146
bugfix
yes
no
nothing
> fix problem with dll and sideEffects

- declarations/WebpackOptions.d.ts
- lib/WebpackOptionsApply.js
- schemas/WebpackOptions.json
This is proposal feature PR to extend current webpack's `target` support for Electron (http://electron.atom.io/), named `electron-preload`. Please find below the description for what it's for with latest Electron changes.
As name stands for, it is a script `that will be loaded before other scripts run in the page. This script will always have access to node APIs no matter whether node integration is turned on or off` (https://electronjs.org/docs/api/browser-window). 
This script will be evaluated & executed before any web page load occurs when it's specified in option.
Technically preload script shares majority in common with `electron-renderer` target. Only notable difference is it is not available to use JSONPTemplate to load async chunks: …
> feat(target): support electron preload async chunk loading

- lib/web/JsonpMainTemplatePlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
This allows to catch failed chunk loads.
See https://github.com/sourcegraph/sourcegraph/pull/1803 for a real use case. When a chunk load failed, it is likely because the website got redeployed while the user was using it should be reloaded. Currently this requires asserting the error message, which is hacky.
feature?
I couldn't find any tests for this plugin nor the error and their existing properties.
No
Currently these errors (and the properties they already have) don't seem to be documented.
> Add name property to error thrown on chunk load failure

- lib/webworker/WebWorkerMainTemplatePlugin.js
- test/ConfigTestCases.test.js
- test/configCases/target/webworker/index.js
- test/configCases/target/webworker/module.js
fixes #7529, fixes #8562
In #8562, the changes made by @prateekbh seems don't work any more, as the webpack repository does not contain `lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js`.
For more detail, here is the config:
```js
// ...
output: {
path: path.resolve(__dirname, '../public'),
publicPath: '/',
filename: 'static/scripts/[name].js',
},
// ...
}
```
After webpack bundling, it will output the following snippet:
```js
__webpack_require__.e = function requireEnsure(chunkId) {
var promises = [];
promises.push(Promise.resolve().then(function() {
// "1" is the signal for "already loaded"
if(!installedChunks[chunkId]) {
importScripts("static/scripts/" + ({}[chunkId]||chunkId) + ".worker.js");
}
}));
return Promise.all(promises);
};
```
Without public path, …
> fix: add missing public path in importScripts

- lib/MultiWatching.js
- lib/Watching.js
- test/MultiWatching.unittest.js
- test/WatchSuspend.test.js
Provide suspend and resume Node API for watch mode, to stop compilation when it's unnecessary.
related issues: https://github.com/webpack/webpack/issues/7341, https://github.com/webpack/webpack/issues/7653
feature
yes
no
Two new apis of `watching`:
```js
watching.suspend()
watching.resume()
```
> feat(watching): allow suspend/resume compilation

- lib/NormalModuleReplacementPlugin.js
Fix for
```
Error: NormalModuleFactory.afterResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
at hooks.afterResolve.callAsync (webpack/lib/NormalModuleFactory.js:192:14)
```
Bugfix
> Update NormalModuleReplacementPlugin to new api

- lib/webpack.js
- test/Validation.test.js
misconfigured config file
Fixes #9295 
refactoring
N/A
Nope
Nil
> Handle cryptic error message being thrown

- lib/NormalModuleFactory.js
- test/configCases/loaders/issue-9053/a.js
- test/configCases/loaders/issue-9053/b.js
- test/configCases/loaders/issue-9053/c.js
- test/configCases/loaders/issue-9053/index.js
- test/configCases/loaders/issue-9053/node_modules/loader1.js
- test/configCases/loaders/issue-9053/node_modules/loader2.js
- test/configCases/loaders/issue-9053/node_modules/loader3.js
- test/configCases/loaders/issue-9053/webpack.config.js
Loaders are applied in the wrong order when using inline match resource, as shown in #9053. The resulting behaviour does not match the expected behaviour as described by the documentation.
I'm attempting to write a loader which depends on `matchResource` working as documented, and the bug has been open for a while with no progress.
A bugfix.
Yes.
Unsure. All tests were run and passing locally, but not sure if fix as written is appropriate, so opening a PR for review/guidance.
Hopefully none, as this makes `matchResource` behave as documented, however see above.
> [WIP] Fixes #9053: Wrong loaders order when using inline match resource

- lib/JsonGenerator.js
Use `JSON.parse(jsonSource)` for JSON modules instead of object literals.
This is an implementation of the idea that comes from https://v8.dev/blog/cost-of-javascript-2019
> As long as the JSON string is only evaluated once, the JSON.parse approach is much faster compared to the JavaScript object literal, especially for cold loads.
The article is written by the V8 team, but it should be true for all the JavaScript engines because JSON is much simpler than JavaScript.
NOTE: I didn't add an option to enable/disable this feature because users can easily use [json-loader](https://github.com/webpack-contrib/json-loader) that converts JSON to JavaScript.
A performance optimization.
No. This PR does not …
> [performance] use JSON.parse(jsonSource) for JSON modules

- lib/SourceMapDevToolPlugin.js
- lib/TemplatedPathPlugin.js
- test/configCases/plugins/source-map-dev-tool-plugin~append/index.js
- test/configCases/plugins/source-map-dev-tool-plugin~append/test.js
- test/configCases/plugins/source-map-dev-tool-plugin~append/webpack.config.js
I want to fully customize the path of generated map file as well as the path in `sourceMappingURL`.
I found fileContext hard to use because it will generate url like `http://localhost:50505/aaa/../b/name.js.map`, which should have been `path.normalize`d and generate `http://localhost:50505/b/name.js.map`, though these two might be the same to browser at all.
So why not have a `[file]` placeholder and let the users concatenate the path on their own?
sourceMap feature
Yes
No
[SourceMapDevToolPlugin](https://webpack.js.org/plugins/source-map-dev-tool-plugin/)
options.append
> Add [file] placeholder for sourceMappingURL in SourceMapDevToolPlugin

- package.json
- yarn.lock
This updates the watchpack package to the latest beta version, v2.0.0-beta.7. This fixes a few known issues listed in the PR here: https://github.com/webpack/watchpack/pull/114
The only change from the previous version is an option to `followSymlinks` that is turned off by default. This should have no impact on the normal behavior, but when turned on can help people using linked packages in their development flow.
The change landed in the watchpack repository with tests included.
No.
The change landed with documentation in the watchpack repository.
> chore(deps): update watchpack from watchpack@2.0.0-beta.6 to watchpack@2.0.0-beta.7

- examples/wasm-complex/webpack.config.js
- examples/wasm-simple/webpack.config.js
- lib/WebpackOptionsDefaulter.js
- lib/debug/ProfilingPlugin.js
- lib/node/ReadFileCompileAsyncWasmPlugin.js
- lib/node/ReadFileCompileWasmPlugin.js
- lib/wasm-async/AsyncWebAssemblyModulesPlugin.js
- lib/wasm/WebAssemblyModulesPlugin.js
- lib/web/FetchCompileAsyncWasmPlugin.js
- lib/web/FetchCompileWasmPlugin.js
- test/TestCases.template.js
- test/configCases/wasm/identical/webpack.config.js
- test/configCases/wasm/wasm-in-initial-chunk-error/webpack.config.js
since there is the `experiments` config now
rename
existing tests
yes
* `webassembly/experimental` -> `webassembly/sync`
* `webassembly/async-experimental` -> `webassembly/async`
> remove experimental from module type name

- .eslintrc.js
- lib/debug/ProfilingPlugin.js
fixes https://github.com/webpack/webpack/issues/9416
refactoring
no
no
nothing
> remove valid jsdoc rule in favour of eslint-plugin-jsdoc

- lib/ResolverFactory.js
- test/Parser.unittest.js
`Tapable` will deprecate HookMap's `tap tapAsync tapPromise` API, so I make this PR to replace the HookMap instance use `.tap()` API with `.for().tap()` API.
This PR is refactoring the HookMap API.
Yes.
No.
The pr has no perception of the user, do not need to be documented.
> HookMap: replace .tap() with .for().tap()

- declarations/WebpackOptions.d.ts
- lib/Compilation.js
- lib/Compiler.js
- lib/NormalModule.js
- lib/Stats.js
- lib/WebpackOptionsDefaulter.js
- lib/logging/Logger.js
- lib/logging/createConsoleLogger.js
- lib/logging/logToConsole.js
- lib/logging/runtime.js
- lib/node/NodeEnvironmentPlugin.js
- lib/webpack.js
- schemas/WebpackOptions.json
- test/Compiler.test.js
- test/Stats.unittest.js
- test/StatsTestCases.test.js
- test/Validation.test.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/logging/node_modules/custom-loader/index.js
- test/statsCases/logging/webpack.config.js
- test/statsCases/preset-detailed/webpack.config.js
- test/statsCases/preset-errors-only-error/webpack.config.js
- test/statsCases/preset-errors-warnings/webpack.config.js
- test/statsCases/preset-minimal/webpack.config.js
- test/statsCases/preset-none/webpack.config.js
- test/statsCases/preset-normal/webpack.config.js
- test/statsCases/preset-verbose/webpack.config.js
feature
yes
no
* Plugins should prefer to use `compilation.getLogger("PluginName")` for logging. This kind of logging is stored to the Stats and formatted in this way. It can be filtered and exported by the user.
* Plugins may use the `compiler.getInfrastructureLogger("PluginName")` for logging to, but logging to this is not stored in the Stats and therefore not formatted this way. Instead it's usually logged to the console/dashboard/gui directly. It can be filtered by the user.
* Loaders should prefer to use `this.getLogger()`. This is a shortcut to `compilation.getLogger()` with loader path and …
> add logging API

- test/cases/nonce/set-nonce/index.js
Prefer the IDL 'nonce' property over .getAttribute('nonce'), which does not work due to https://bugs.chromium.org/p/chromium/issues/detail?id=680419 and https://codereview.chromium.org/2628733005/.
> Prefer the IDL 'nonce' property over .getAttribute('nonce')

- lib/TemplatedPathPlugin.js
- test/HotModuleReplacementPlugin.test.js
After implementing bracket based dynamic routing (`[val]`) in Next.js we noticed that HMR for dynamic routes that used `webpack` path variables were broken due to extra replacing. 
For example, if a user does `pages/blog/[name]/comments.js`, in development when a HMR bundle is created it replaces the path causing `static/webpack/[id].[hash].hot-update.js` 
to output to:
`static/webpack/static/development/pages/static/development/pages/[name]/comments.js/comments.js.f2c9118fd02c6de02824.hot-update.js` 
instead of `static/webpack/static/development/pages/[name]/comments.js.0953cecf31a80df2bd53.hot-update.js`
Related issues: 
https://github.com/zeit/next.js/issues/7775
https://github.com/zeit/next.js/pull/8061
Let me know if you think this needs be handled differently/escaped elsewhere. …
> Escape path variables in replaced values for TemplatedPathPlugin

- lib/web/JsonpMainTemplatePlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/configCases/split-chunks/issue-9491/index.js
- test/configCases/split-chunks/issue-9491/test.config.js
- test/configCases/split-chunks/issue-9491/webpack.config.js
This PR fixes #9491 by allowing to use entrypoint names like `constructor` with `runtimeChunk: 'single'`/`namedChunks: true`.
Doing that currently resulted in the following error at runtime (see the issue for more details):
```
runtime.js:26 Uncaught TypeError: resolves.shift(...) is not a function
at Array.webpackJsonpCallback [as push] (runtime.js:26)
at constructor.js:1
```
Yes
That shouldn't be the case
N/A
> Fix JSONP main template to allow currently forbidden chunk IDs (#9491)

- lib/debug/ProfilingPlugin.js
While writing a custom profiler I ran into the issue that TerserPlugin never called it’s `end` trace. Eventually I tracked it down to the callback function. Instead of being overwritten it was being appended to the end of the function arguments. The callback has to be popped first because the added argument is a wrapper for the original callback.
bugfix.
I can investigate adding a test if needed.
No.
No changes to documentation needed.
---
> Fix asyncHook callback interceptor for ProfilingPlugin

- lib/ExportsInfoApiPlugin.js
- lib/ModuleGraph.js
- lib/WebpackOptionsApply.js
- lib/dependencies/ExportsInfoDependency.js
- test/cases/parsing/harmony-deep-exports/counter.js
- test/cases/parsing/harmony-deep-exports/index.js
- test/cases/parsing/harmony-deep-exports/reexport-namespace-again.js
- test/cases/parsing/harmony-deep-exports/reexport-namespace.js
improve usage/provide information for nested exports
improve tests for deep exports
feature
yes
no
In modules `__webpack_exports_info__` is available:
* `__webpack_exports_info__` is always true
* `__webpack_exports_info__.<exportName>.used` is `false` when the export is known to be unused, true otherwise
* `__webpack_exports_info__.<exportName>.useInfo` is
* `false` when the export is known to be unused
* `true` when the export is known to be used
* `null` when the export usage could depend on runtime conditions
* `undefined` when no info is available
* …
> add `__webpack_exports_info__` API to allow export introspection

- .gitignore
- lib/CachePlugin.js
> refactor: cache always true

- lib/buildChunkGraph.js
- test/configCases/chunk-graph/issue-9634/async-b.js
- test/configCases/chunk-graph/issue-9634/async-b2.js
- test/configCases/chunk-graph/issue-9634/entry-a.js
- test/configCases/chunk-graph/issue-9634/entry-b.js
- test/configCases/chunk-graph/issue-9634/leaf.js
- test/configCases/chunk-graph/issue-9634/module.js
- test/configCases/chunk-graph/issue-9634/shared.js
- test/configCases/chunk-graph/issue-9634/test.config.js
- test/configCases/chunk-graph/issue-9634/webpack.config.js
fixes #9634
when minAvailableModules of a ChunkGroup shrink, children of this ChunkGroup need to be recalculated
bugfix
yes
no
nothing
> fixes #9634

- lib/ContextModule.js
- lib/FileSystemInfo.js
- lib/cache/PackFileCacheStrategy.js
- lib/util/fs.js
- test/TestCasesCacheInstant.test.js
- test/TestCasesCachePack.test.js
improve error handling in pack file cache strategy
support context timestamp snapshot
make ContextModule serializable
fix snapshotting bug of managed paths
use managed and immutable path info for context hashes and timestamps
enabled managedPaths for node_modules during cache tests
bugfixes
existing tests
no
nothing
> Persistent Caching fixes

- lib/dependencies/HarmonyImportSpecifierDependency.js
- test/cases/inner-graph/no-side-effects/index.js
- test/cases/inner-graph/no-side-effects/module.js
- test/cases/inner-graph/no-side-effects/package/index.js
- test/cases/inner-graph/no-side-effects/package/package.json
- test/cases/inner-graph/no-side-effects/package/unusedModule.js
- test/configCases/inner-graph/defaultNamedFunction/module.js
- test/configCases/inner-graph/defaultNamedFunction/webpack.config.js
- test/configCases/inner-graph/defaultNamedFunctionExpression/module.js
- test/configCases/inner-graph/defaultNamedFunctionExpression/webpack.config.js
conditional import specifiers do not generate import statements when exports are unused
bugfix
yes
no
nothing
> fix bug with side-effect-free module removed due to scope analysis

- lib/Compiler.js
- test/configCases/asset-emitted/normal/webpack.config.js
change
yes
yes
The `assetEmitted` hook has different arguments now. The second argument is an object containing multiple information now `{ content: Buffer, source: Source, compilation: Compilation, outputPath: string, targetPath: string }`
cc @evilebottnawi
> change assetEmitted hook to include more info

- lib/optimize/SplitChunksPlugin.js
A minor code improvement.
There should not be any observable changes to behaviour.
Nope.
Nothing.
> nit: Don't recompute filename hash

- lib/NormalModule.js
As documented in https://github.com/webpack/webpack/issues/9718, the size function in NormalModule is a critical path with slows down watch mode recompilation. By caching the module size, this performance hit in watch mode can be avoided for modules that have not changed.
Refactor to improve performance
No
No
Nothing
**Profile**
As expected, this shaved about 2s off my incremental compile time (from ~6.5s to ~4.5s)
Before:
After:
> perf: cache module size in NormalModule

- lib/CommonJsStuffPlugin.js
- lib/RuntimePlugin.js
- lib/dependencies/RuntimeRequirementsDependency.js
- test/__snapshots__/StatsTestCases.test.js.snap
this ensures backward-compat for plugins that
rewrite `module._source` after a simple module
is already parsed and dependencies point to
ranges in the old source.
compat
no
no
nothing
> avoid rewriting source from "module.exports"

- declarations/WebpackOptions.d.ts
- lib/RuntimeTemplate.js
- lib/WebpackOptionsDefaulter.js
- lib/util/normalizeEcmaVersion.js
- schemas/WebpackOptions.json
- test/Schemas.lint.js
- test/Validation.test.js
- test/configCases/ecmaVersion/2009/index.js
- test/configCases/ecmaVersion/2009/webpack.config.js
- test/configCases/ecmaVersion/2015/index.js
- test/configCases/ecmaVersion/2015/webpack.config.js
- test/configCases/ecmaVersion/5/index.js
- test/configCases/ecmaVersion/5/webpack.config.js
- test/configCases/ecmaVersion/6/index.js
- test/configCases/ecmaVersion/6/webpack.config.js
feature
Improvements:
- Allow set `5`-`11` values for `output.ecmaVersion` (better DX, many other tools, like eslint, use the same logic)
- Allow set `2009`-`2020` values for `output.ecmaVersion` (better DX, many other tools, like eslint, use the same logic)
- Always normalize `output.ecmaVersion` - Why? This is very important for those who write plugins because you can set `output.ecmaVersion: 2019` or `output.ecmaVersion: 10` and it will require write own normalize logic, it is often very uncomfortable. We have a similar problem with `devtool` - you can setup words (`cheap`, `inline`, etc) in any order and this forces you to write additional logic, which negatively affects on performance and code look ugly.
- Also number notation (for …
> Feat improve ecma version option

- lib/Stats.js
As seen in https://github.com/facebook/create-react-app/issues/7783#issue-502900874 (and https://github.com/GoogleChrome/lighthouse/issues/1056 and others) if for some reasons the `timeZone` is undetected the locale-methods throw with "RangeError: Unsupported time zone specified undefined"
The issue itself was fixed in NodeJS 12, but affects other NodeJS LTS versions (6, 8, 10)
This PR deals with the issue similar to https://github.com/GoogleChrome/lighthouse/pull/1086/files and https://github.com/GoogleChrome/lighthouse/pull/1086/files
This is bit tricky to test this as it needs OS level changes or ENV variable setup at launch but manual steps to test this is
```js
nvm install 10 # install affected …
```
> fix: Deal with undetected timeZone in Stats.js

- lib/Stats.js
Fixes #9818 
cc @billneff79 @AndyOGo
Signed-off-by: petetnt <pete.a.nykanen@gmail.com>
> fix: Only add timeZone if toLocaleString throws with initial timeZone

- declarations/WebpackOptions.d.ts
- lib/stats/DefaultStatsFactoryPlugin.js
- lib/stats/DefaultStatsPresetPlugin.js
- schemas/WebpackOptions.json
- test/Errors.test.js
Add new `stats.errorStack` option to display it anyway.
bugfix
no
no
* new `stats.errorStack` option to display webpack-internal stack trace of errors
> Do not show stack trace of errors in stats by default

- lib/BannerPlugin.js
- test/configCases/plugins/banner-plugin/index.js
- test/configCases/plugins/banner-plugin/webpack.config.js
- Trailing whitespace isn't trimmed from the banners.
- The banner plugin itself generates a trailing space when an empty newline is added. You can see this in the generated clipboard.js file: https://github.com/zenorocha/clipboard.js/blob/d17eca050e705ae4932fd1be3e96abe38bd3397c/dist/clipboard.js#L4 (caused by the whiteline here https://github.com/zenorocha/clipboard.js/blob/85981026d1f464c9f645ffe543a3ba0d40c9b6c4/webpack.config.js#L10)
Advantages of removing the trailing whitespaces:
- Minor file size improvements
- Prevention of linting errors
- No conflicts when `trim_trailing_whitespace: true` is defined in `.editorconfig`
> Remove trailing whitespace from banners

- lib/wasm-async/AsyncWebAssemblyModulesPlugin.js
- lib/wasm/WebAssemblyModulesPlugin.js
fixes #9781
performance
existing tests
no
nothing
> lazy require webassemblyjs using modules

- lib/dependencies/RequireIncludeDependencyParserPlugin.js
- lib/dependencies/RequireIncludePlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/cases/chunks/issue-2443/index.js
- test/cases/chunks/parsing/index.js
- test/cases/errors/crash-missing-import/index.js
- test/cases/parsing/typeof/warnings.js
- test/cases/resolving/browser-field/index.js
- test/cases/resolving/issue-2986/index.js
- test/configCases/errors/import-missing/index.js
- test/configCases/filename-template/module-filename-template/index.js
- test/configCases/inner-graph/_helpers/entryLoader.js
- test/configCases/plugins/banner-plugin-hashing/index.js
- test/configCases/plugins/banner-plugin/index.js
- test/configCases/plugins/environment-plugin/index.js
- test/configCases/plugins/terser-plugin/index.js
- test/configCases/source-map/exclude-chunks-source-map/index.js
- test/configCases/source-map/namespace-source-path.library/index.js
- test/configCases/source-map/namespace-source-path/index.js
- test/configCases/source-map/nosources/index.js
- test/configCases/source-map/source-map-with-profiling-plugin/index.js
- test/configCases/source-map/sources-array-production/index.js
- test/configCases/split-chunks-common/library/index.js
- test/statsCases/tree-shaking/index.js
deprecation
yes
yes
* `require.include` is depreacted and will trigger a warning.
* `parser.requireInclude: true` will disable the warning
* `parser.requireInclude: false` will disable `require.include`
> emit a warning when require.include is used

- lib/WebpackOptionsApply.js
- lib/async-modules/InferAsyncModulesPlugin.js
- lib/dependencies/HarmonyCompatibilityDependency.js
- test/cases/async-modules/top-level-await-without-export/index.js
active async modules when top level await is used
bugfix
yes
no
nothing
> add missing runtime requirement for async module header

- declarations/WebpackOptions.d.ts
- schemas/WebpackOptions.json
Fixes the `ResolveOptions.plugins` types to use a plugin that takes in a resolver plugin instead of a compiler plugin.
While working on this I noticed that `enhance-resolver` doesn't allow passing in a function, unlike webpack and with its plugins. Not sure if you will want to address this in the future but still pointing it out.
Closes #10073
Fixes types.
N/A
No.
Nothing. This is a types fix only.
> Fix ResolveOptions.plugins types

- lib/optimize/ConcatenatedModule.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/configCases/concatenate-modules/load-chunk-function/a.js
- test/configCases/concatenate-modules/load-chunk-function/b.js
- test/configCases/concatenate-modules/load-chunk-function/c.js
- test/configCases/concatenate-modules/load-chunk-function/entry1.js
- test/configCases/concatenate-modules/load-chunk-function/entry2.js
- test/configCases/concatenate-modules/load-chunk-function/test.config.js
- test/configCases/concatenate-modules/load-chunk-function/webpack.config.js
fixes #10104
bugfix
yes
no
nothing
> fixes missing `__webpack_require__.e` in concatenated modules

- lib/HotModuleReplacementPlugin.js
Hi, this is my first attempt at a PR for webpack. 
It seems there was no ChunckGraph fallback assigned to this plugin. I took the instructions from https://github.com/webpack-contrib/mini-css-extract-plugin/issues/462#issuecomment-551221049 and applied it here as well.
Adding ChunckGraph fallback to HotModuleReplacementPlugin. Fixes https://github.com/webpack-contrib/mini-css-extract-plugin/issues/462
No
No
Nothing as far as I can tell
> Assign fallback ChunkGraph to HotUpdateChunks

- lib/dependencies/CommonJsExportsDependency.js
- lib/dependencies/CommonJsExportsParserPlugin.js
- lib/optimize/MangleExportsPlugin.js
- test/cases/cjs-tree-shaking/non-root-this/index.js
- test/cases/cjs-tree-shaking/non-root-this/module.js
- test/cases/cjs-tree-shaking/object-define-property-replace/index.js
- test/cases/cjs-tree-shaking/object-define-property-replace/module.js
- test/configCases/mangle/mangle-with-object-prop/commonjs.js
- test/configCases/mangle/mangle-with-object-prop/index.js
- test/configCases/mangle/mangle-with-object-prop/module.js
- test/configCases/mangle/mangle-with-object-prop/webpack.config.js
allow mangle even if object prototype export names are used
prevent mangling for object prototype export names in CommonJS
only treat Object.defineProperty for top-level this as export
replace Object.defineProperty correctly when value is in brakets
bugfix
yes
no
nothing
> bugfixes for exports and mangling

- declarations/WebpackOptions.d.ts
- lib/CommonJsStuffPlugin.js
- lib/DefinePlugin.js
- lib/ProvidePlugin.js
- lib/logging/Logger.js
- setup/setup.js
- test/NormalModule.unittest.js
- test/__snapshots__/StatsTestCases.test.js.snap
- yarn.lock
> update dependencies in-range

- package.json
- yarn.lock
Upgrade `terser-webpack-plugin` to latest to fix vulnerability issue on `serialize-javascript`
This is the original error:
https://github.com/advisories/GHSA-h9rv-jmmf-4pgx
This release include the fix:
https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v2.2.3
> chore: upgrade terser-webpack-plugin to 2.3.1 to fix vulnerability

- lib/WebpackOptionsApply.js
options.target must be string or function, otherwise will throw WebpackOptionsValidationError when run webpack(options) .
refactoring
no
no
> refactor(target): remove unnecessary judgment

- package.json
- test/ConfigTestCases.test.js
- test/HotModuleReplacementPlugin.test.js
- test/StatsTestCases.test.js
- test/TestCases.template.js
- test/WatchTestCases.test.js
- tooling/compile-to-definitions.js
- tooling/type-coverage.js
webpack supports Node.js 10.13.0 as minimum Node.js version now.
Node.js 10.13.0 provides recursive option for fs.mkdirSync.
So, mkdirp package is not needed.
refactoring
change tests
no
nothing
> Remove mkdirp package from devDependencies

- declarations.d.ts
- declarations/WebpackOptions.d.ts
- lib/HotModuleReplacement.runtime.js
- lib/node/NodeMainTemplate.runtime.js
- lib/node/NodeMainTemplateAsync.runtime.js
- lib/web/JsonpMainTemplate.runtime.js
- lib/webworker/WebWorkerMainTemplate.runtime.js
- schemas/WebpackOptions.json
Backport #10050 to webpack-4
Fix - #10217 
NA
None
Nothing
> Get rid of some hacks in declarations file for webpack-4

- schemas/ajv.absolutePath.js
fix : #10247 
NA
No
May be that webpack-4 can now handle Absolute network paths, Not sure
> fix: better handle absolute paths

- lib/optimize/InnerGraphPlugin.js
- test/cases/inner-graph/simple/index.js
- test/cases/inner-graph/simple/inner.js
- test/cases/inner-graph/simple/module.js
bugfix
yes
yes `/*#__PURE__*/` applies to only function calls now instead of expressions in general.
The `/*#__PURE__*/` annotation can be put in front of `CallExpression`s (function calls) to make the call itself as side-effect-free. Arguments are not marked, and may need to be marked separately.
When the init value in a variable declaration of an unused variable is considered as pure/side-effect-free, it marked as dead code, not executed and dropped by the minimizer. This behavior is controlled by `optimization.innerGraph: true`
> the pure annotation only applies to function calls

- lib/cache/PackFileCacheStrategy.js
- lib/cache/ResolverCachePlugin.js
- lib/optimize/ModuleConcatenationPlugin.js
- lib/serialization/ArraySerializer.js
- lib/serialization/BinaryMiddleware.js
- lib/serialization/FileMiddleware.js
- lib/serialization/ObjectMiddleware.js
- lib/serialization/PlainObjectSerializer.js
- lib/serialization/Serializer.js
- lib/serialization/SerializerMiddleware.js
- lib/util/LazySet.js
- lib/util/fs.js
- lib/util/internalSerializables.js
- lib/util/serialization.js
- test/PersistentCaching.test.js
- tooling/print-cache-file.js
cache is split into multiple .pack files which represent usage of cache items
this allows to only read/deserialize files that are needed
and reduces the need to rewrite .pack files
while still packaging multiple cache items together
lazy (de)serialization system has changed to allow writeLazy and writeSeparate
refactoring, feature
existing tests
yes
nothing
> refactor Persistent Cache

- .gitattributes
- declarations/plugins/AssetModulesPluginGenerator.d.ts
- lib/asset/AssetGenerator.js
- lib/asset/AssetModulesPlugin.js
- schemas/plugins/AssetModulesPluginGenerator.json
- test/__snapshots__/StatsTestCases.test.js.snap
- test/configCases/asset-modules/_static/file.html
- test/configCases/asset-modules/overridePath/index.js
- test/configCases/asset-modules/overridePath/webpack.config.js
- test/statsCases/asset/index.js
- test/statsCases/asset/static/file.html
- test/statsCases/asset/webpack.config.js
feature
```js
output: {
assetModuleFilename: "images/[hash][ext]"
},
module: {
rules: [
{
test: /\.(png|jpg)$/,
type: "asset"
},
{
test: /\.html$/,
type: "asset",
generator: {
filename: "static/[name][ext]"
}
}
]
},
experiments: {
asset: true
}
};
```
yes
no
about `generator.assetFilename`
> override filename for asset modules

- lib/Compilation.js
- lib/Compiler.js
to make it easier to find incompatible plugins
fixes #10341
compatibility
no
yes
nothing
> make compiler/compilation.cache read-only

- declarations/WebpackOptions.d.ts
- lib/Compilation.js
- lib/DllEntryPlugin.js
- lib/DynamicEntryPlugin.js
- lib/EntryOptionPlugin.js
- lib/EntryPlugin.js
- lib/ExportPropertyTemplatePlugin.js
- lib/FlagDependencyUsagePlugin.js
- lib/FlagEntryExportAsUsedPlugin.js
- lib/ProgressPlugin.js
- schemas/WebpackOptions.json
- test/Validation.test.js
- test/configCases/entry/descriptor/a.js
- test/configCases/entry/descriptor/b.js
- test/configCases/entry/descriptor/test.config.js
- test/configCases/entry/descriptor/webpack.config.js
some preparations to other cool features
feature
yes
no
`entry` configuration option.
When using an object for the `entry` configuration options advanced options can be provided with the following syntax:
``` js
entry: {
main: {
import: ["./entry1", "./entry2"], // or import: "./single-entry"
// advanced configuration here
}
}
```
Currently no advanced configuration is available. This will be added in later PRs.
> Add entrypoint descriptor with `import` property

- declarations/plugins/ProgressPlugin.d.ts
- lib/ProgressPlugin.js
- schemas/plugins/ProgressPlugin.json
- test/ProgressPlugin.test.js
feature
**Motivation:** on huge projects, there is super incorrect percent value. This feature makes possible to specify the percent calculation algorithm. For example on huge projects `percentBy: "entries"` gives more correctly percent value cause there are much entrypoints and they are known in advance
no, but added some other tests
no
ProgressPlugins has a new option `percentBy` which can take `"entries"` `"dependencies"` `"modules"` or `null` (default).
> add percentBy options to ProgressPlugin

- lib/FlagDependencyExportsPlugin.js
- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- test/cases/parsing/harmony-circular-star-reexport/a.js
- test/cases/parsing/harmony-circular-star-reexport/b.js
- test/cases/parsing/harmony-circular-star-reexport/c.js
- test/cases/parsing/harmony-circular-star-reexport/index.js
only retrigger flagging exports in dependencies when exports really changed
export * does no longer incorrectly provided exports which are already provided by something else
fixes #10332
bugfix
yes
no
nothing
> fix hanging build when using circular export * 

- lib/EnvironmentPlugin.js
- test/configCases/plugins/environment-plugin/errors.js
- test/configCases/plugins/environment-plugin/index.js
- test/configCases/plugins/environment-plugin/warnings.js
- test/configCases/plugins/environment-plugin/webpack.config.js
Currently, the EnvironmentPlugin adds a warning to the build if an environment variable is undefined and no default value was provided. This pull request changes webpack to error instead, if an expected environment variable is not found it is more likely that the user would want webpack to error.
This addresses issue #10296
feature
Yes
Yes, as per the review by @sokra this is a breaking change. If an environment variable is not found during build webpack will now error rather than warn
If an environment variable is not found during bundling and no default was provided webpack will now error …
> Add options arg to EnvironmentPlugin, fixes #10296

- bin/webpack.js
If STDIN is not in terminal mode when the webpack script is executed, the readline module will never execute the callback passed to question and the script will exit successfully, without ever building the pack.  An example of this is Rails' webpacker gem, which executes the webpack script in a subshell: https://github.com/rails/webpacker/blob/0b550a0ed66f2c01baa5f05f1126abada47a6c6f/lib/webpacker/compiler.rb#L67-L71
Bugfix.  If STDIN is not in terminal mode, we should exit with an error immediately, instead of attempting to ask a question to which we'll never receive an answer.
I did not see any existing tests for the `webpack.js` script, but will happily write some if there's an example of how they …
> Exit with an error if we can't prompt for webpack-cli installation.

- lib/ConstPlugin.js
- lib/Parser.js
- test/Compiler.test.js
- test/fixtures/asmjs.js
backports PR #10288
fixes #10283
This PR basically disables the ConstPlugin in asm.js functions.
Yes.
It should not cause any compatibility problems.
Probably nothing.
> backport: do not evaluate constants in asm.js, fix IIFE mode detection

- lib/DefinePlugin.js
- test/configCases/plugins/define-plugin/index.js
- test/configCases/plugins/define-plugin/webpack.config.js
Currently, _DefinePlugin_ doesn't support array as value. Let's see this example:
```js
new DefinePlugin({ ITEMS: [1, 2, 3] })
```
We get:
```js
{ '0': 1, '1': 2, '2': 3 }
```
With these changes, we get:
```js
[1, 2, 3]
```
Yes
Potentially, yes. Because before, an array was handled as an object
We can add information about using array in _DefinePlugin_, [here](https://webpack.js.org/plugins/define-plugin/#usage)
> feat(DefinePlugin): Support array as value in DefinePlugin

- declarations/WebpackOptions.d.ts
- schemas/WebpackOptions.json
#10389
schema fix
no
no, a bugfix
webpack 4 doesn't allow a function for output.hotUpdateChunkFilename
> disallow function for output.hotUpdateChunkFilename

- lib/ProgressPlugin.js
feature
no
no
ProgressPlugin uses the persistent cache to save last modules and dependencies count to make progress calculation more accurate.
> ProgressPlugin: save and restore total module count

- lib/optimize/ConcatenatedModule.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/cases/errors/harmony-import-missing2/a.js
- test/cases/errors/harmony-import-missing2/errors.js
- test/cases/errors/harmony-import-missing2/index.js
- test/cases/errors/harmony-import-missing2/module1.js
- test/cases/errors/harmony-import-missing2/module2.js
- test/cases/scope-hoisting/circular-root-export/external-ref.js
- test/cases/scope-hoisting/circular-root-export/external.js
- test/cases/scope-hoisting/circular-root-export/index.js
- test/cases/scope-hoisting/circular-root-export/module.js
- test/cases/scope-hoisting/circular-root-export/root-ref.js
- test/cases/scope-hoisting/circular-root-export/root.js
- test/cases/scope-hoisting/issue-10409/a.js
- test/cases/scope-hoisting/issue-10409/b.js
- test/cases/scope-hoisting/issue-10409/c.js
- test/cases/scope-hoisting/issue-10409/cts.js
- test/cases/scope-hoisting/issue-10409/index.js
- test/cases/scope-hoisting/issue-10409/main.js
to handle circular dependencies with non-concatenated modules
backport of #10426 and #10430
fixes #10409 for webpack 5
bugfix
yes
no
nothing
> hoist exports to the top of a concatenated module

- lib/APIPlugin.js
- lib/ChunkGroup.js
- lib/RuntimeGlobals.js
- lib/container/OverridableModule.js
- lib/container/OverridableOriginalDependency.js
- lib/container/OverridableOriginalModuleFactory.js
- lib/container/OverridablesPlugin.js
- lib/container/OverridablesRuntimeModule.js
- lib/container/parseOptions.js
- lib/util/internalSerializables.js
- test/configCases/container/overridables/cjs/test1.js
- test/configCases/container/overridables/cjs/test2.js
- test/configCases/container/overridables/index.js
- test/configCases/container/overridables/modules/test1.js
- test/configCases/container/overridables/modules/test2.js
- test/configCases/container/overridables/node_modules/package/index.js
- test/configCases/container/overridables/options/test1.js
- test/configCases/container/overridables/options/test2.js
- test/configCases/container/overridables/options/test3.js
- test/configCases/container/overridables/splitChunks/app.js
- test/configCases/container/overridables/splitChunks/index.js
- test/configCases/container/overridables/splitChunks/shared-separate.js
- test/configCases/container/overridables/splitChunks/shared.js
- test/configCases/container/overridables/splitChunks/vendor.js
- test/configCases/container/overridables/webpack.config.js
Adds an `OverridablesPlugin` which allows to mark modules as overridable. These modules must only be used in on demand loaded chunks. An `__webpack_override__` API allows to replace these modules.
The `OverridablesPlugin` constructor takes a description of overridable modules and their global name for overriding.
The following argument types are allowed:
* Object
* key is the override name
* value is a request pointing to a module
* when value is not an string it's treated as nested description and the listed argument types are handled in the same way, but with `key` plus `/` as prefix
* Array
* Items are requests pointing to modules
* override name is automatically determined by removing all `[^\w]+/` from the start of the request.
* Examples: "./some/module" -> "some/module", …
> add OverridablesPlugin

- declarations/WebpackOptions.d.ts
- lib/config/defaults.js
- schemas/WebpackOptions.json
- test/Defaults.unittest.js
- test/configCases/web/unique-jsonp/index.js
- test/configCases/web/unique-jsonp/package.json
- test/configCases/web/unique-jsonp/test.config.js
- test/configCases/web/unique-jsonp/webpack.config.js
It defaults to library name or name from package.json in context
output.uniqueName will be used to generate unique globals for
* output.jsonpFunction
* output.chunkCallbackName
* etc.
fixes #10441
feature
yes
no
new option output.uniqueName
> add output.uniqueName option

- lib/container/ContainerReferencePlugin.js
- lib/container/RemoteModule.js
- lib/container/RemoteOverrideModule.js
- lib/container/RemoteOverrideModuleFactory.js
- lib/container/RemoteRuntimeModule.js
- lib/container/RemoteToExternalDependency.js
- lib/container/RemoteToOverrideDependency.js
- lib/util/internalSerializables.js
- test/configCases/container/container-reference-override/index.js
- test/configCases/container/container-reference-override/module.js
- test/configCases/container/container-reference-override/new-test.js
- test/configCases/container/container-reference-override/test.config.js
- test/configCases/container/container-reference-override/webpack.config.js
- test/configCases/container/container-reference/index.js
- test/configCases/container/container-reference/module.js
- test/configCases/container/container-reference/test.config.js
- test/configCases/container/container-reference/webpack.config.js
add a ContainerReferencePlugin which allows to reference another container and consume modules from this container. It also allows to override overridable modules in that container.
``` js
new ContainerReferencePlugin({
remoteType: "var", // any supported external type
remotes: {
abc: "abcExternal"
}, // like externals, but key is the scope used for the container reference
overrides: {
react: "./lib/my-react.js"
} // keys is the overridable key, value the request in this build
})
```
TODOs:
feature
yes
no
TODO: not exposed yet
> add ContainerReferencePlugin

- lib/DllPlugin.js
- lib/FlagAllModulesAsUsedPlugin.js
- lib/FlagDependencyUsagePlugin.js
- test/configCases/dll-plugin-side-effects/0-create-dll/dependency.js
- test/configCases/dll-plugin-side-effects/0-create-dll/dependency2.js
- test/configCases/dll-plugin-side-effects/0-create-dll/index.js
- test/configCases/dll-plugin-side-effects/0-create-dll/module.js
- test/configCases/dll-plugin-side-effects/0-create-dll/test.config.js
- test/configCases/dll-plugin-side-effects/0-create-dll/webpack.config.js
- test/configCases/dll-plugin-side-effects/1-use-dll/index.js
- test/configCases/dll-plugin-side-effects/1-use-dll/webpack.config.js
- test/configCases/dll-plugin/0-issue-10475/index.js
- test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/constants.js
- test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/index.js
- test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/package.json
- test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/someFunction.js
- test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/working-constants.js
- test/configCases/dll-plugin/0-issue-10475/test.config.js
- test/configCases/dll-plugin/0-issue-10475/webpack.config.js
- test/configCases/dll-plugin/1-issue-10475/index.js
- test/configCases/dll-plugin/1-issue-10475/webpack.config.js
fix problem that modules were removed before they were flagged as used
fixes #10189
backport of #10205
fixes #10475
bugfix
yes
yes, dlls might be larger
nothing
> flag all modules as used for Dll

- lib/Dependency.js
- lib/ExternalModule.js
- lib/FlagDependencyExportsPlugin.js
- lib/ModuleGraph.js
- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- lib/dependencies/StaticExportsDependency.js
- lib/library/SystemLibraryPlugin.js
- lib/wasm/WebAssemblyParser.js
- test/configCases/externals/externals-system/index.js
- test/configCases/externals/externals-system/test.config.js
- test/configCases/externals/externals-system/webpack.config.js
- test/helpers/fakeSystem.js
[Codepen showing problem](https://codesandbox.io/s/reverent-rosalind-zei2s)
This fixes a bug where webpack currently treats SystemJS external modules as commonjs instead of ES modules. The bug means that the default export of a SystemJS external module is not accessible via `import defaultThing from 'external-thing';`.
Without exception, all modules in the SystemJS registry are ES module objects. Webpack should treat them as ES modules when determining default vs named exports.
I am a primary maintainer of SystemJS and have discussed this change with the other SystemJS maintainers, including @guybedford. We believe it best for webpack to treat all modules originating from SystemJS as ES modules.
Yes …
> Fix externals interop within SystemLibraryPlugin.

- package.json
- yarn.lock
https://npmjs.com/advisories/1179
https://github.com/webpack/webpack/issues/10561
webpack has a prototype pollution vulnerability down the tree and I'm going through and creating patches for the deps on this semver.
https://github.com/webpack/watchpack/pull/148
https://github.com/paulmillr/chokidar/pull/993
https://github.com/mapbox/node-pre-gyp/pull/492
Updates the minor version of watchpack
Nein, not sure if this needs one.
Nein, but the version of watchpack that is being added here does not technically exist yet, so checks will fail until then.
That this vulnerability has been patched.
> Update watchpack to the most recent minor version to remove minimist vulnerability.

- lib/ProgressPlugin.js
- lib/logging/createConsoleLogger.js
- lib/stats/DefaultStatsFactoryPlugin.js
- lib/stats/DefaultStatsPrinterPlugin.js
- test/BenchmarkTestCases.benchmark.js
- test/Compiler.test.js
- test/StatsTestCases.test.js
- test/__snapshots__/StatsTestCases.test.js.snap
According to the SI, there should be a space between a measurement
quantity and its unit symbol, so this commit fixes this issue
throughout Webpack. See #10656 and #10534.
Bugfix.
Yes.
No.
None.
> Fix measurement formatting as per SI rules

- lib/container/ContainerReferencePlugin.js
- lib/container/ModuleFederationPlugin.js
- test/configCases/container/module-federation/dep.js
- test/configCases/container/module-federation/index.js
- test/configCases/container/module-federation/module.js
- test/configCases/container/module-federation/other.js
- test/configCases/container/module-federation/self.js
- test/configCases/container/module-federation/test.config.js
- test/configCases/container/module-federation/webpack.config.js
- test/helpers/fakeSystem.js
Addressing subtask on the Module Federation Project board
https://github.com/webpack/webpack/projects/6#card-33743655
Defaulting options from webpack core output config
fix/enhancement
none required?
no
ModuleFederationPlugin options and their default states
> fix: module federation plugin library should be optional

- package.json
- test/__snapshots__/StatsTestCases.test.js.snap
- yarn.lock
I am running into heap overflows due to a memory leak in `terser-webpack-plugin`. See this [issue](https://github.com/webpack-contrib/terser-webpack-plugin/issues/199) for relevant information
I think that this upgrade would close this [PR](https://github.com/webpack/webpack/pull/10779) as well.
Updates the `terser-webpack-plugin` from 2.3.1 -> 2.3.6
I updated the snapshots
No
Nothing
> Updated terser-webpack-plugin from 2.3.1 to 2.3.6

- lib/index.js
- package.json
- test/configCases/container/0-container-full/webpack.config.js
- test/configCases/container/1-container-full/webpack.config.js
- test/configCases/container/2-container-full/webpack.config.js
- test/configCases/container/container-entry-overridables/webpack.config.js
- test/configCases/container/container-entry/webpack.config.js
- test/configCases/container/container-reference-override/webpack.config.js
- test/configCases/container/container-reference/webpack.config.js
- test/configCases/container/module-federation/webpack.config.js
- test/configCases/container/overridables/webpack.config.js
- types.d.ts
- yarn.lock
fix merge issues
expose plugins
yes
no
* The following plugins need to be documented:
* `webpack.container.OverridablesPlugin`
* `webpack.container.ContainerPlugin`
* `webpack.container.ContainerReferencePlugin`
* `webpack.container.ModuleFederationPlugin`
* Containers as general concept need to be documented
* separate compilation
* container entry is a manifest to load exposed modules
* But the compilation could be configured to have additional intialization logic when the container entry is loaded.
* exposed modules are loaded async
* overrides allow to replace modules in the container
* …
> upgrade tooling, expose container plugins, fix typings tests

- lib/AsyncDependenciesBlock.js
- lib/buildChunkGraph.js
- lib/container/OverridableDependenciesBlock.js
- lib/container/OverridableModule.js
- lib/container/OverridablesRuntimeModule.js
- test/configCases/container/overridables/cjs/test3.js
- test/configCases/container/overridables/index.js
- test/configCases/container/overridables/modules/test3.js
- test/configCases/container/overridables/webpack.config.js
- types.d.ts
feature
yes
no
* The limitation that overridables must not be in initial chunk has been removed.
* Once evaluated, overridables are no longer overridable.
* overridables that are used in initial chunk, can only be overridden by an sync module override that doesn't use Promises.
> support overridables in initial chunks

- declarations/WebpackOptions.d.ts
- declarations/plugins/container/ContainerReferencePlugin.d.ts
- declarations/plugins/container/ModuleFederationPlugin.d.ts
- lib/DllReferencePlugin.js
- lib/ExternalModule.js
- lib/ExternalModuleFactoryPlugin.js
- lib/ExternalsPlugin.js
- lib/InitFragment.js
- lib/RuntimeTemplate.js
- lib/config/defaults.js
- lib/config/normalization.js
- lib/dependencies/HarmonyAcceptDependency.js
- lib/dependencies/HarmonyImportDependency.js
- lib/library/SystemLibraryPlugin.js
- lib/wasm-async/AsyncWebAssemblyJavascriptGenerator.js
- lib/wasm/WebAssemblyJavascriptGenerator.js
- schemas/WebpackOptions.json
- schemas/plugins/container/ContainerReferencePlugin.json
- schemas/plugins/container/ModuleFederationPlugin.json
- test/Defaults.unittest.js
- test/__snapshots__/Cli.test.js.snap
- test/__snapshots__/StatsTestCases.test.js.snap
- test/configCases/externals/async-externals/index.js
- test/configCases/externals/async-externals/webpack.config.js
- types.d.ts
add `promise` external
add `import` external (uses import())
add `output.importFunctionName` option to change the `import()` function name
allow for inline external type when using arrays
fix some typings
fix namespace object behavior when using system external and accessing nested property
fix interop behavior for async dynamic modules
yes
no
* add `promise` external (like `var` but awaits the result)
* add `import` external (uses import() to load a native ESM)
* `output.importFunctionName` allows to set `import()` function name when used for `import` external.
> add support for async externals

- lib/container/ContainerReferencePlugin.js
- lib/container/options.js
- test/PersistentCaching.test.js
- test/configCases/container/0-container-full/webpack.config.js
- test/configCases/container/0-transitive-overriding/webpack.config.js
- test/configCases/container/1-container-full/webpack.config.js
- test/configCases/container/2-transitive-overriding/webpack.config.js
- test/configCases/container/container-entry-overridables/index.js
- test/configCases/container/container-entry-overridables/webpack.config.js
- test/configCases/container/container-entry/index.js
- test/configCases/container/container-entry/webpack.config.js
- test/configCases/container/container-reference-override/module.js
- test/configCases/container/container-reference/module.js
- test/configCases/container/error-handling/index.js
- test/configCases/container/exposed-overridables/webpack.config.js
- test/configCases/container/module-federation/module.js
- test/configCases/container/overridables/index.js
API change
existing tests
yes
In Module Federation:
* keys of the `exposes` option should be prefixed with `./`. The `.` key exposes a module as index module. (`ModuleFederationPlugin` and `ContainerPlugin`)
* Automatically inferred keys for `shared` `overridable` `overrides` `remotes` `exposes` do no longer do any modifications to the key. (no `./` removal)
> change Module Federation API to be more similar to exports field

- package.json
See webpack/schema-utils#97
Needed due to line here: https://github.com/webpack/webpack/blob/master/types.d.ts#L62
> chore: move @types/estree from devDependencies to dependencies.

- lib/HotModuleReplacementPlugin.js
- test/hotCases/define/issue-6962/a.js
- test/hotCases/define/issue-6962/module.js
fixes #11057
bugfix
yes
no
nothing
> make sure that the callback function in module.hot.accept is parsed

- package.json
- yarn.lock
Simply run https://github.com/atlassian/yarn-deduplicate
run yarn-deduplicate -s fewer yarn.lock
add it as validation in postinstall hook
Deps changes 
No, we just need to make sure the current test passes
N
o
Maybe to keep in mind to re run yarn deduplicate after deps upgrades and changes
> (deps) apply yarn deduplicate on yarn.lock & add validation

- lib/config/normalization.js
- test/Defaults.unittest.js
> return preset normal for stats true

- lib/ContextModule.js
- lib/ExternalModule.js
- lib/FlagDependencyUsagePlugin.js
- lib/Module.js
- lib/ModuleGraph.js
- lib/ModuleInfoHeaderPlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
- types.d.ts
Make ContextModule a static default exporting module
fix provided exports info for ExternalModule
This avoid invalidating these modules when used exports change, even while this makes no difference in the module
improvement
exiting tests
yes
nothing
> Avoid tracking/printing detailed usage info for modules without exportsType

- declarations/WebpackOptions.d.ts
- lib/config/defaults.js
- package.json
- schemas/WebpackOptions.json
- test/Defaults.unittest.js
- test/__snapshots__/Cli.test.js.snap
- types.d.ts
- yarn.lock
feature
updated snapshots
no
webpack supports `options.resolve.roots` option. Defaults to `options.context`. 
If request is an server-relative URL (starting with `/`)  `webpack` will try to resolve `path.join(root[i], request)` after trying to resolve the path as absolute path on non-windows systems
> add roots option

- declarations/WebpackOptions.d.ts
- lib/config/defaults.js
- lib/optimize/SplitChunksPlugin.js
- schemas/WebpackOptions.json
- test/Defaults.unittest.js
- test/Validation.test.js
- test/__snapshots__/Cli.test.js.snap
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/split-chunks-keep-remaining-size/d.js
- test/statsCases/split-chunks-keep-remaining-size/index.js
- test/statsCases/split-chunks-keep-remaining-size/webpack.config.js
- types.d.ts
change, refactor, bugfix
yes
no
* new option `splitChunks.enforceSizeThreshold` resp. ``splitChunks.cacheGroups[x].enforceSizeThreshold`
* when over this limit, `minRemainingSize`, `maxInitialRequests` and `maxAsyncRequests` are ignore
* This enforces big chunks to be splitted, e. g. big vendors, even if this adds more requests or keeps small remaining chunks
* `splitChunks.minSize` defaults to `20k` in production
* `splitChunks.enforceSizeThreshold` default to `50k` in production
> Http2 defaults for splitChunks

- lib/ModuleNotFoundError.js
- test/__snapshots__/StatsTestCases.test.js.snap
Perhaps this would be even clearer: "webpack no longer includes polyfills for node.js core modules by default. If you need this module, configure a polyfill for it."
> Fixed typo

- declarations/WebpackOptions.d.ts
- lib/optimize/SplitChunksPlugin.js
- schemas/WebpackOptions.json
- test/Validation.test.js
add new splitChunks.enforceSizeThreshold option
enforces splitting on certain size (ignoring maxRequests and minRemainingSize)
fix bug where sorting didn't work for minSize: 0
fixes #11167
yes
no
added enforceSizeThreshold to webpack 4 too
> splitChunks improvements

- declarations/WebpackOptions.d.ts
- lib/ContextModule.js
- lib/ModuleFactory.js
- lib/NormalModuleFactory.js
- lib/config/defaults.js
- lib/dependencies/RequireContextPlugin.js
- lib/rules/DescriptionDataMatcherRulePlugin.js
- lib/rules/RuleSetCompiler.js
- package.json
- schemas/WebpackOptions.json
- test/Defaults.unittest.js
- test/TestCases.template.js
- test/Validation.test.js
- test/__snapshots__/Cli.test.js.snap
- test/cases/mjs/cjs-import-default/package.json
- test/cases/mjs/esm-by-default/package.json
- test/cases/mjs/namespace-object-lazy/index.mjs
- test/cases/mjs/namespace-object-lazy/package.json
- test/cases/mjs/no-module-main-field/node_modules/m/a.js
- test/cases/mjs/no-module-main-field/node_modules/m/a.mjs
- test/cases/mjs/no-module-main-field/package.json
- test/cases/mjs/type-module/index.js
- test/cases/mjs/type-module/package.json
- test/cases/resolving/data-uri/index.js
- test/configCases/mjs/esm-by-default/webpack.config.js
- test/configCases/plugins/provide-plugin/webpack.config.js
- types.d.ts
- yarn.lock
improve experiments.mjs to be more compatibly with node.js ESM
- add support for `type: "module"` in package.json
- add support for `*.cjs`
- enable strict ESM for data uris with `text/javascript` or `application/javascript`
- disallow not fully specified requests in imports `*.mjs` or `type: "module"`
add `descriptionData` rule condition to match package.json info
fix passing resolveOptions along context modules
feature, experiment
yes
yes to the experiment
Using `*.js` with `"type": "module"` in package.json or `*.mjs` moves webpack into a strict ESM mode where more limitations are applied:
* …
> improve compatibly with node.js ESM

- declarations/WebpackOptions.d.ts
- lib/WebpackOptionsDefaulter.js
- package.json
- schemas/WebpackOptions.json
- yarn.lock
backport of #11143 
fixes #11206
feature
no
no
Invalid absolute paths that produced an error before may know resolved correctly, but I won't consider this as breaking
webpack supports `options.resolve.roots` option. Defaults to `options.context`. 
If request is an server-relative URL (starting with `/`)  `webpack` will try to resolve `path.join(root[i], request)` after trying to resolve the path as absolute path on non-windows systems
> Backport of resolve.roots for webpack 4

- package.json
Webpack tries to require `webpack-cli` without declaring it as a optional peer dependency which causes it to not get access to it under Yarn PnP
Fixes half of https://github.com/yarnpkg/berry/issues/1452
bugfix
No
No
N/A
> fix: add missing optional peer dependency webpack-cli

- appveyor.yml
- cspell.json
- lib/ConstPlugin.js
- lib/DefinePlugin.js
- lib/dependencies/CommonJsPlugin.js
- lib/dependencies/ContextDependencyHelpers.js
- lib/javascript/BasicEvaluatedExpression.js
- lib/javascript/JavascriptParser.js
- lib/javascript/JavascriptParserHelpers.js
- test/cases/parsing/evaluate-nullish/index.js
- test/cases/parsing/evaluate-nullish/test.filter.js
- test/cases/parsing/evaluate/index.js
- test/cases/parsing/nullish-coalescing/a.js
- test/cases/parsing/nullish-coalescing/b.js
- test/cases/parsing/nullish-coalescing/index.js
- test/cases/parsing/nullish-coalescing/test.filter.js
- test/helpers/supportsNullishCoalescing.js
- types.d.ts
> add nullish coalescing support

- package.json
Webpack is trying to access `webpack-cli` and `webpack-command` without declaring them as optional peer dependencies which causes it to not get access to either of them under Yarn PnP
PR for Webpack 5: https://github.com/webpack/webpack/pull/11189
bugfix
No
No
N/A
> fix: add missing optional peer dependencies

- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- test/cases/side-effects/dynamic-reexports/dynamic-reexport-default/dynamic.js
- test/cases/side-effects/dynamic-reexports/dynamic-reexport-default/index.js
- test/cases/side-effects/dynamic-reexports/index.js
fixes #11243
bugfix
yes
no
nothing
> ignore default export when reexporting a dynamic module

- declarations/WebpackOptions.d.ts
- lib/WebpackOptionsApply.js
- lib/optimize/MangleExportsPlugin.js
- schemas/WebpackOptions.json
- test/__snapshots__/Cli.test.js.snap
- test/configCases/mangle/mangle-with-object-prop/commonjs.js
- test/configCases/mangle/mangle-with-object-prop/index.js
- test/configCases/mangle/mangle-with-object-prop/module.js
- test/configCases/mangle/mangle-with-object-prop/test.config.js
- test/configCases/mangle/mangle-with-object-prop/webpack.config.js
- types.d.ts
feature
yes
no
* `optimization.usedExports` can now take `"size"` and `"deterministic"` as value in addition to `true` and `false`.
* `"size"` optimizes export names for minimal size
* `"deterministic"` and true optimized export names for small size, while being deterministic for long term caching.
* `"size"` is cases about ~1% smaller files compared to `"deterministic"`, but changing exports or exports usage in modules often causes all using modules to be invalidated.
> add size optimization mode to `optimization.mangleExports`

- lib/TemplatedPathPlugin.js
- lib/asset/AssetGenerator.js
- lib/asset/AssetParser.js
- lib/config/defaults.js
- test/Defaults.unittest.js
- test/configCases/asset-modules/query-and-custom-condition/index.js
- test/configCases/asset-modules/query-and-custom-condition/webpack.config.js
- test/configCases/asset-modules/query-and-custom-encoder/index.js
- test/configCases/asset-modules/query-and-custom-encoder/webpack.config.js
- test/configCases/asset-modules/query/index.js
- test/configCases/asset-modules/query/webpack.config.js
feature, latest `file-loader` release introduce support the `[query]` replacer in the `name` option for better CDN integration, let's do it for the `asset` module type and respect query string by default for better 0cjs
Yes
Yes, now we respect `[query]` by default.
Yes.
- the `assetModuleFilename` option has the `[hash][ext][query]` value by default
> feat: support `[query]` for asset modules

- test/SemVer.unittest.js
In #11271 I wrote some tests to help try an work out what was happening with the runtime versions of the semver functions.  I offered to add them to the test suite in that PR and @sokra suggested as a seperate PR to not hold up the bug fix getting through.
There's some pretty nasty code in here to generate the functions with a dummy `RuntimeTemplate` and evaluate the functions to be runnable in the test suite, so I'm happy to take suggestions on how to make those parts less nasty.  I did investigate using `new Function(...)` instead of `eval`, but there was an issue with accessing other functions in the module's scope when executing it in a NodeJS environment ([some details in the MSDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function#Differenc …
> added tests around minified runtime versions of semver functions

- lib/dependencies/HarmonyExportDependencyParserPlugin.js
- test/cases/parsing/issue-11353/async_generator_function.js
- test/cases/parsing/issue-11353/generator_function.js
- test/cases/parsing/issue-11353/index.js
The generator `*` control needs to be placed after the `function` keyword instead of suffixing the whole function body.
bugfix
Yes, created 9 test cases under `test\cases\parsing\issue-11353`
No, the API should remain the same.
Fix an issue when dealing with generator functions whereas the `*` character was being attached to the function body instead of the function keyword.
> Move `generator` control from suffix to prefix

- README.md
This PR updates the badges from `packagephobia.now.sh` to `packagephobia.com` to avoid a redirect.
Related to https://github.com/styfle/packagephobia/pull/587
Readme update
No
No
Nothing
> chore(badge): update to packagephobia.com

- declarations/WebpackOptions.d.ts
- lib/ContextModule.js
- lib/FileSystemInfo.js
- lib/NormalModule.js
- lib/WebpackOptionsApply.js
- lib/cache/PackFileCacheStrategy.js
- lib/cache/ResolverCachePlugin.js
- lib/config/defaults.js
- lib/config/normalization.js
- lib/validateSchema.js
- schemas/WebpackOptions.json
- test/ConfigCacheTestCases.test.js
- test/ConfigTestCases.template.js
- test/Defaults.unittest.js
- test/TestCasesCachePack.test.js
- test/Validation.test.js
- test/__snapshots__/Cli.test.js.snap
- test/__snapshots__/StatsTestCases.test.js.snap
- test/fixtures/buildDependencies/run.js
- test/watchCases/cache/managedPath/webpack.config.js
- test/watchCases/snapshot/unable-to-snapshot/webpack.config.js
- types.d.ts
* expose snapshot options for module, resolve, buildDependencies and resolveBuildDependencies
* move managedPaths and immutablePaths from config.cache to config.snapshot
* add timestamp + hash snapshotting mode
* use timestamp + hash mode by default in production and for buildDependencies
feature
not yet, but the new defaults test the 
yes, config options move. Hints added to point to the new locations.
* config options have moved `cache.managedPaths/immutablePaths` -> `snapshot.managedPaths/immutablePaths`
* new config options how snapshots are created.
* `snapshot.module`: Snapshots for …
> add "snapshot" configuration to allow to configure how snapshots are created

- declarations/WebpackOptions.d.ts
- lib/WebpackOptionsApply.js
- lib/config/defaults.js
- lib/config/normalization.js
- schemas/WebpackOptions.json
- test/Defaults.unittest.js
- test/Validation.test.js
- test/__snapshots__/Cli.test.js.snap
- types.d.ts
refactoring
existing tests
no
* new option `externalsPresets` which allows to enable the default externals for various targets. Each is a boolean property in this object:
* node
* nodeWebkit (deprecated)
* electronPreload
* electronMain
* web
* webAsync
> move default externals from target into externalsPresets option

- declarations/WebpackOptions.d.ts
- lib/Compilation.js
- lib/IgnoreWarningsPlugin.js
- lib/WebpackOptionsApply.js
- lib/config/normalization.js
- lib/stats/DefaultStatsFactoryPlugin.js
- lib/stats/DefaultStatsPrinterPlugin.js
- schemas/WebpackOptions.json
- test/Defaults.unittest.js
- test/Validation.test.js
- test/__snapshots__/Cli.test.js.snap
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/ignore-warnings/index.js
- test/statsCases/ignore-warnings/module.js
- test/statsCases/ignore-warnings/module2.js
- test/statsCases/ignore-warnings/webpack.config.js
- types.d.ts
improve warnings and errors handling in stats
respect warningsFilter for warnings count
include child compilation warnings and errors in count
show hint for child compilation errors and warnings
add config.ignoreWarnings
deprecate stats.warningsFilter
refactoring
yes
no, only deprecation
* `stats.warningsFilter` is deprecated
* `ignoreWarnings` is the new option
* `RegExp`
* `{module?: RegExp, file?: RegExp, message?: RegExp}`
* `function(WebpackError, Compilation): boolean`
> deprecate stats.warningsFilter in favor of ignoreWarnings

- lib/optimize/SplitChunksPlugin.js
- test/configCases/split-chunks/move-to-entrypoint/chunk.js
- test/configCases/split-chunks/move-to-entrypoint/entryB.js
- test/configCases/split-chunks/move-to-entrypoint/moduleA.js
- test/configCases/split-chunks/move-to-entrypoint/moduleB.js
- test/configCases/split-chunks/move-to-entrypoint/moduleC.js
- test/configCases/split-chunks/move-to-entrypoint/test.config.js
- test/configCases/split-chunks/move-to-entrypoint/webpack.config.js
bugfix
yes
no
`splitChunks.cacheGroups.*.name` can be used to move modules into a chunk that **is a parent of the source chunk**. Examples: `name: "runtime"` to move modules into the runtime chunk, `name: "entry-name"` to move modules into the entry chunk. On demand named chunks can also be used, but one have to be careful that the selected modules are only used below this chunk.
> allow to move modules to parent chunks

- lib/dependencies/WorkerPlugin.js
- test/configCases/worker/custom-worker/index.js
- test/configCases/worker/custom-worker/module.js
- test/configCases/worker/custom-worker/node_modules/web-worker.js
- test/configCases/worker/custom-worker/test.config.js
- test/configCases/worker/custom-worker/test.filter.js
- test/configCases/worker/custom-worker/webpack.config.js
- test/configCases/worker/custom-worker/worker.js
feature
yes
no
for javascript files one can customize WebWorker handling syntax with `parser.worker`.
Example to support the `web-worker` package:
```js
module: {
rules: [
{
test: /\.m?js$/,
parser: {
worker: ["default from web-worker", "..."]
}
}
]
}
```
> allow to pass custom worker syntax

- lib/ContextModuleFactory.js
- test/ContextModuleFactory.unittest.js
What existing problem does the pull request solve?
max call stack error when resolving dependencies
Resolves #11378 [Webpack 5] ContextModuleFactory - RangeError: Maximum call stack size exceeded
Bugfix
Yes
No
None
> fix bug for maxCallStack in ContextModuleFactory

- lib/hmr/HotModuleReplacement.runtime.js
- lib/hmr/JavascriptHotModuleReplacement.runtime.js
- test/HotTestCases.template.js
- test/configCases/sharing/consume-multiple-versions/index.js
- test/helpers/expectWarningFactory.js
- test/hotCases/runtime/require-disposed-module-warning/a.js
- test/hotCases/runtime/require-disposed-module-warning/b.js
- test/hotCases/runtime/require-disposed-module-warning/index.js
- test/hotCases/runtime/require-disposed-module-warning/module.js
Fix the warnUnexpectedRequire function where it uses a hoisted variable in a for-loop.
bugfix
No. The bugfix is for a warning. I think tests are unnecessary.
No
Nothing.
> fix: warnUnexpectedRequire binds wrong variable in for-loop

- lib/config/defaults.js
- lib/config/target.js
- test/Defaults.unittest.js
- test/fixtures/browserslist/package.json
defaults change
yes
yes
when browserslist info is available, this will be used by default
> make browserslist the default target when browserslist config is available

- declarations/WebpackOptions.d.ts
- lib/config/defaults.js
- lib/config/normalization.js
- lib/optimize/SplitChunksPlugin.js
- schemas/WebpackOptions.json
- test/Defaults.unittest.js
- test/Validation.test.js
- test/__snapshots__/Cli.test.js.snap
- types.d.ts
feature for plugins
no
no
nothing
> allow plugins to modify the default size types for splitChunks

- lib/Compilation.js
An entrypoint can be defined with `dependOn` specified as an array [see docs](https://webpack.js.org/configuration/entry-context/#entry), for example:
```javascript
splitmodule1: {
import: scanSourceFiles('./src/splitmodule1'),
dependOn: [ 'pluginregistry'] // Note that we could specify multiple dependencies here, e.g. dependOn: ['core', 'pluginregistry']
}
```
Using the Webpack Watcher results in the following error:
```
× ｢wdm｣: Error: Conflicting entry option dependOn = pluginregistry vs pluginregistry
at Compilation._addEntryItem (C:\Users\c.brueggemann\Documents\Projects\codesplit\node_modules\webpack\lib\Compilation.js:1616:7)
at Compilation.addEntry (C:\Users\c.brueggemann\Documents\Projects\codesplit\node_modules\webpack\lib\Compilation.js:1560:8)
at …
```
> Fix compilation of projects where dependsOn is an array

- lib/ModuleNotFoundError.js
- test/__snapshots__/StatsTestCases.test.js.snap
Give instructions suitable for more environments in the ModuleNotFoundError for Node.js polyfills.  Before this change, requiring a builtin module like `buffer` from a package symlinked from somewhere would give the following suggestion:
```
If you want to include a polyfill, you need to install 'buffer'.
```
However, installing `buffer` is not enough to resolve the issue as the package would not be reachable from place it was symlinked from and the same error would still be shown.  This PR changes the error message to be:
```
If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
- install 'buffer'
```
By setting the fallback to an absolute path the replacement is found from symlinked packages.
Resolves #11600.
**What …
> Improve suggested Node.js polyfill config

- lib/Compiler.js
- lib/Dependency.js
- lib/index.js
- lib/stats/StatsPrinter.js
- lib/util/Hash.js
- lib/util/LazyBucketSortedSet.js
- lib/util/cleverMerge.js
- types.d.ts
fix some jsdoc descriptions
fixes #11651
exposes webpack for https://github.com/webpack-contrib/mini-css-extract-plugin/issues/600
exposes cleverMerge for #11635
expose, types
no
nothing
Plugins can access webpack from the `webpack` property of the Compiler. This allows to remove the webpack peerDependency from the plugin.
> expose webpack from Compiler

- lib/ModuleTemplate.js
Current deprecation message for ModuleTemplate.hooks.hash is saying about ModuleTemplate.hooks.package. This PR fixes the message.
bug fix
No (Seems there are no tests related to deprecation messages)
No
I guess it doesn't need any documentation changes.
> Fix ModuleTemplate.hooks.hash deprecation message

- lib/optimize/ConcatenatedModule.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/cases/optimize/concat-star-import/index.js
- test/cases/optimize/concat-star-import/module.js
- test/cases/optimize/concat-star-import/node_modules/cmodule/index.js
- test/cases/optimize/concat-star-import/node_modules/cmodule/package.json
> fix: handle star import name collisions in module concatenation

- lib/config/browserslistTargetHandler.js
ie11 is an exception
fixes #11753
bugfix
no
no
nothing
> caniuse es6 doesn't report arrow-functions correctly

- lib/ExternalModule.js
- test/configCases/externals/this/index.js
- test/configCases/externals/this/webpack.config.js
- types.d.ts
Fixes #11724.
Changes how the object lookup is wrapped in an IIFE to avoid hiding the left side of the assignment inside a function.
When concatenating modules, the module exports are assigned to a local variable, not to `module.exports`. Therefore, the generated code of the module is:
```js
(function() { const lodash_namespace = this['lodash']; })();
```
But because the local variable is scoped inside the function, it's not visible outside it and can't be used by other modules.
If the assignment is to `module.export`, wrapping inside a function doesn't do any harm, that's why it always worked before external modules concatenation started to be supported.
After this patch, the IIFE wraps only the object lookup:
```js
const lodash_namespace = (function() { return this['lodash']; })();
``` …
> Make external modules of type 'this' work with module concatenation

- lib/Compilation.js
- lib/RuntimeTemplate.js
- lib/Template.js
- lib/asset/AssetGenerator.js
- lib/javascript/JavascriptModulesPlugin.js
- lib/stats/DefaultStatsPrinterPlugin.js
- test/Stats.test.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/output-module/chunk.js
- test/statsCases/output-module/index.js
- test/statsCases/output-module/module.js
- test/statsCases/output-module/webpack.config.js
- types.d.ts
feature
yes
no
two more properties in `info` (https://webpack.js.org/api/stats/#asset-objects)
* `sourceFilename` when asset was created from a source file (potentially transformed), the original filename relative to compilation context
* `javascriptModule` true, when asset is javascript and an ESM
> add asset info for `sourceFilename` and `javascriptModule`

- lib/WebpackOptionsDefaulter.js
#11207 intended for `resolve.roots` to have a default value, but was typo'd. See https://twitter.com/wSokra/status/1320840828412198913
This prevents `import Thing from '/thing-in-root'` from working out of the box.
No, but was discovered when testing it https://twitter.com/pyrolistical/status/1320825188175376384
Not in a meaningful way. Its technically breaking since `import Thing from '/thing-in-root'` would no longer error, but its unlikely anybody would have relied on that behaviour.
Mostly documented by #11207 but ideally would have more documentation describing the default value and hence …
> Fixed resolve.roots default value

- lib/optimize/ModuleConcatenationPlugin.js
- test/configCases/graph/issue-11856.2/a.js
- test/configCases/graph/issue-11856.2/b.js
- test/configCases/graph/issue-11856.2/b2.js
- test/configCases/graph/issue-11856.2/shared-c.js
- test/configCases/graph/issue-11856.2/shared-d.js
- test/configCases/graph/issue-11856.2/shared-e.js
- test/configCases/graph/issue-11856.2/test.config.js
- test/configCases/graph/issue-11856.2/webpack.config.js
- test/configCases/graph/issue-11856/a.js
- test/configCases/graph/issue-11856/b.js
- test/configCases/graph/issue-11856/shared-c.js
- test/configCases/graph/issue-11856/shared-d.js
- test/configCases/graph/issue-11856/test.config.js
- test/configCases/graph/issue-11856/webpack.config.js
fixes #11856
bugfix
yes
no
nothing
> fix incorrect concatenation when module runtime are merged

- declarations/WebpackOptions.d.ts
- declarations/plugins/WatchIgnorePlugin.d.ts
- package.json
- types.d.ts
- yarn.lock
fixes #11801
fixes #11850
deps, bugfix
no
no
nothing
> upgrade tooling for improved array types

- lib/WebpackOptionsApply.js
> chore: fix case typo

- lib/dependencies/CommonJsExportsParserPlugin.js
- test/cases/cjs-tree-shaking/esModule-getter/index.js
- test/cases/cjs-tree-shaking/esModule-getter/module.js
> fix crash when __esModule is called with defineProperty without value

- lib/dependencies/HarmonyImportDependency.js
- test/cases/cjs-interop/non-existing-export/esModule.js
- test/cases/cjs-interop/non-existing-export/index.js
- test/cases/cjs-interop/non-existing-export/module.js
- test/cases/cjs-interop/non-existing-export/warnings.js
- test/cases/cjs-tree-shaking/mutate/warnings.js
- test/cases/mjs/non-enumerable/errors.js
- test/cases/mjs/non-enumerable/warnings.js
bugfix
yes
a bugfix. previously such imports were incorrectly accepted
nothing
> emit errors for exports in commonjs modules for which we know that they don't exist

- bin/webpack.js
- cspell.json
Enhancement, feature
Refs https://github.com/webpack/webpack-cli/pull/2040#issuecomment-723059281
No
No
Nothing
> feat: add pnpm support for installing CLI

- lib/Compilation.js
- lib/Compiler.js
- lib/SourceMapDevToolPlugin.js
- lib/index.js
- lib/optimize/RealContentHashPlugin.js
- package.json
- test/configCases/process-assets/html-plugin/index.js
- test/configCases/process-assets/html-plugin/inline.js
- test/configCases/process-assets/html-plugin/normal.js
- test/configCases/process-assets/html-plugin/test.config.js
- test/configCases/process-assets/html-plugin/webpack.config.js
- types.d.ts
- yarn.lock
fix and add processAsset stages
allow to hook into RealContentHashPlugin for custom hashing
#11822
feature, bugfix
yes
no
* new processAssets stage: `PROCESS_ASSETS_STAGE_OPTIMIZE_INLINE`
* processAssets plugins can pass `additionalAssets: true` as tap option to be called to assets added in later plugin again. The `assets` argument will only contain the new assets in this case.
* processAssets plugins can pass `additionalAssets: assets => { ... }` as separate handler for assets added in later plugins.
* webpack.optimize.RealContentHashPlugin.getCompilationHooks(compilation).updateHash` is a new …
> allow to process assets that are added during processAssets

- lib/HotModuleReplacementPlugin.js
- lib/TemplatedPathPlugin.js
- lib/config/defaults.js
- lib/runtime/GetMainFilenameRuntimeModule.js
- lib/util/runtime.js
- test/ConfigTestCases.template.js
- test/Defaults.unittest.js
- test/HotModuleReplacementPlugin.test.js
- test/HotTestCases.template.js
- test/helpers/createFakeWorker.js
- test/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/chunk1.js
- test/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/chunk2.js
- test/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/index.js
- test/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/module.js
- test/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/shared.js
- test/hotCases/disposing/runtime-independent-filename/chunk1.js
- test/hotCases/disposing/runtime-independent-filename/chunk2.js
- test/hotCases/disposing/runtime-independent-filename/index.js
- test/hotCases/disposing/runtime-independent-filename/module.js
- test/hotCases/disposing/runtime-independent-filename/shared.js
- test/hotCases/disposing/runtime-independent-filename/warnings1.js
- test/hotCases/disposing/runtime-independent-filename/webpack.config.js
- test/hotCases/worker/update-in-worker/index.js
- test/hotCases/worker/update-in-worker/module.js
- test/hotCases/worker/update-in-worker/test.filter.js
- test/hotCases/worker/update-in-worker/worker.js
- types.d.ts
allow HMR to work in WebWorkers too
bugfix
yes
no. There is a new warning when using a bad config which hints you to change your config to avoid the bug.
* `[runtime]` can be used a placeholder in `output.hotUpdateMainFilename`.
> fix problem when HMR and different runtimes

- lib/web/JsonpChunkLoadingPlugin.js
- lib/web/JsonpChunkLoadingRuntimeModule.js
- test/Stats.test.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/configCases/split-chunks-common/issue-12128/a.js
- test/configCases/split-chunks-common/issue-12128/b.js
- test/configCases/split-chunks-common/issue-12128/index.js
- test/configCases/split-chunks-common/issue-12128/index2.js
- test/configCases/split-chunks-common/issue-12128/test.config.js
- test/configCases/split-chunks-common/issue-12128/webpack.config.js
- test/configCases/web/preexecuted-chunk/chunk.js
- test/configCases/web/preexecuted-chunk/index.js
- test/configCases/web/preexecuted-chunk/test.config.js
- test/configCases/web/preexecuted-chunk/webpack.config.js
Avoid duplicate chunks in template's `chunkLoadingGlobal`, its the issue #12128 which I reproduce in this repo https://github.com/zphhhhh/webpack-bug.
In`lib/web/JsonpChunkLoadingRuntimeModule.js`, we put all the common chunks to the global array `chunkLoadingGlobal` in template, but the array contains duplicate chunks because [this file's L470](https://github.com/webpack/webpack/blob/master/lib/web/JsonpChunkLoadingRuntimeModule.js#L470) and [L488](https://github.com/webpack/webpack/blob/master/lib/web/JsonpChunkLoadingRuntimeModule.js#L488).
We shouldn't make `parentChunkLoadingFunction` be `chunkLoadingGlobal.push`until `webpackJsonpCallback` execute completely. Just like it in webpack 4 [lib/web/JsonpMainTemplatePlugin.js#L500](https://github.com/webpack/webpack/blob/webpack-4/lib/web/ …
> fix: avoid duplicate chunks in template's chunkLoadingGlobal #12128

- lib/node/NodeTargetPlugin.js
~feature, node.js builtin support for "timers/promises"~
feature, adds support for **dns/promises**, **stream/promises**, **timers/promises**, **wasi**
https://nodejs.org/api/timers.html#timers_timers_promises_api
no.
no, additive.
n/a
> feat: add support for additional node.js builtin modules

- lib/util/compileBooleanMatcher.js
- test/compileBooleanMatcher.unittest.js
> Fix #12255: compileBooleanMatcher fails when prefix and suffix overlap

- declarations/WebpackOptions.d.ts
- examples/typescript/README.md
- schemas/WebpackOptions.json
- test/__snapshots__/Cli.test.js.snap
- types.d.ts
`Stats` doesn't have a `nestedModulesSpace` property as mentioned in the [docs](https://webpack.js.org/configuration/stats/#statsnestedmodulesspace). I have added the property to schema and updated the types. Also, this PR closes #12163.
It adds ```nestedModulesSpace``` property to `stats`.
Yes. I have added the tests.
No.
None. It's already documented [here](https://webpack.js.org/configuration/stats/#statsnestedmodulesspace).
> Added nestedModulesSpace to schema and updated the types

- declarations/WebpackOptions.d.ts
- lib/APIPlugin.js
- lib/Compilation.js
- lib/Compiler.js
- lib/EntryOptionPlugin.js
- lib/ExternalModuleFactoryPlugin.js
- lib/Module.js
- lib/ModuleFactory.js
- lib/NormalModule.js
- lib/NormalModuleFactory.js
- lib/config/normalization.js
- lib/optimize/ConcatenatedModule.js
- lib/optimize/SplitChunksPlugin.js
- lib/rules/RuleSetCompiler.js
- lib/stats/DefaultStatsFactoryPlugin.js
- lib/stats/DefaultStatsPresetPlugin.js
- lib/stats/DefaultStatsPrinterPlugin.js
- schemas/WebpackOptions.json
- test/Validation.test.js
- test/__snapshots__/Cli.test.js.snap
- test/configCases/layer/rules/index.js
- test/configCases/layer/rules/loader.js
- test/configCases/layer/rules/module-layer-change.js
- test/configCases/layer/rules/module-other-layer-change.js
- test/configCases/layer/rules/module.js
- test/configCases/layer/rules/reexport.js
- test/configCases/layer/rules/webpack.config.js
- types.d.ts
* add experiments.layers
* add layers to define different module layers
* support module layers in stats
* add layer support for NormalModules
fixes #11466
feature
yes
no
* `experiments.layers: true` enables the experimental feature
* `entry.xxx.layer: "name-of-layer"` allows to set the layer for an entrypoint
* `module.rules[].issuerLayer: RuleCondition` allows to filter/match by layer of issuer
* `module.rules[].layer: "name-of-layer"` allows to set the layer of an module
* `splitChunks.cacheGroups.xxx.layer` allows to select modules by layer
* `externals.byLayer["name-of-layer"]` allows to …
> add experiments.layers

- lib/RuntimeGlobals.js
- lib/runtime/LoadScriptRuntimeModule.js
- lib/web/JsonpChunkLoadingRuntimeModule.js
- test/Stats.test.js
- test/__snapshots__/StatsTestCases.test.js.snap
`chunkId` was available in webpack 4 and to improve migration it should be available in webapck 5 too.
#10826
cc @jscheid 
bugfix
no
no
nothing
> re-add chunkId to script loading when available

- lib/library/AssignLibraryPlugin.js
- test/configCases/library/invalid-name/errors.js
- test/configCases/library/invalid-name/index.js
- test/configCases/library/invalid-name/webpack.config.js
`bugfix` related to #11923
No, it does not introduce a breaking change, but only validation for `ModuleFederationPlugin`'s name property
In the documentation for `ModuleFederationPlugin`, it might be worth mentioning the change made by this PR.
As the library type for `ModuleFederationPlugin.name` is `var`by default, dashes(-) should not be included in it, as these are not allowed in Javascript declarations. Doing so will explicitly throw an error.
> fix: Check whether plugin names are valid Javascript identifiers

- lib/ChunkGraph.js
- lib/ids/IdHelpers.js
- test/configCases/plugins/mini-css-extract-plugin/chunk.js
- test/configCases/plugins/mini-css-extract-plugin/webpack.config.js
- test/configCases/plugins/mini-css-extract-plugin/x.js
also use module.nameForCondition() to compute module ids
fixes https://github.com/webpack-contrib/mini-css-extract-plugin/issues/676
bugfix
yes
no
nothing
> compute chunk roots correctly when using transitive connections

- declarations/WebpackOptions.d.ts
- package.json
- schemas/WebpackOptions.json
- test/__snapshots__/Cli.test.js.snap
- test/configCases/resolving/prefer-absolute/index.js
- test/configCases/resolving/prefer-absolute/webpack.config.js
- test/configCases/resolving/prefer-root/index.js
- test/configCases/resolving/prefer-root/webpack.config.js
- types.d.ts
- yarn.lock
feature
yes
no
new option `resolve.preferAbsolute`
it changes the order of `resolve.roots` and absolute paths. Usually `resolve.roots` is tried first and falling back to absolute paths. This option reverses the order.
> add resolve.preferAbsolute option

- lib/Compiler.js
- lib/WatchIgnorePlugin.js
- lib/util/fs.js
- types.d.ts
I started using WatchIgnorePlugin and it generates a runtime error like
```
TypeError: watcher.getContextInfoEntries is not a function
at Object.getContextTimeInfoEntries
at Watching.invalidate
```
This PR changes a callsite to use the correct function name
This is a blatant type error in master, as demonstrated by these searches: https://github.com/webpack/webpack/search?q=getContextInfoEntries
https://github.com/webpack/webpack/search?q=getContextTimeInfoEntries
I do not consider adding a test for this to be necessary.
No
There is nothing to add to the documentation
> Fix runtime type error in WatchIgnorePlugin

- lib/FileSystemInfo.js
- lib/cache/PackFileCacheStrategy.js
- package.json
- test/BuildDependencies.test.js
- test/fixtures/buildDependencies/esm-cjs-dep.js
- test/fixtures/buildDependencies/esm-dep.mjs
- test/fixtures/buildDependencies/esm.mjs
- test/fixtures/buildDependencies/index.js
- test/fixtures/buildDependencies/run.js
- yarn.lock
#12418
fixes #11908
feature
yes
no
BuildDependencies can now track ESM modules in an experimental way.
> improve build deps tracking (ESM, non-JS, better warnings)

- declarations/WebpackOptions.d.ts
- schemas/WebpackOptions.json
- test/__snapshots__/Cli.test.js.snap
- types.d.ts
`Stats` doesn't have a `chunkModulesSpace` property as mentioned in the docs. I have added the property to schema and updated the types. This PR closes #12411.
It adds ```chunkModulesSpace``` property to `stats`.
Yes. I've updated the test snapshots.
No.
None. It's already documented [here](https://webpack.js.org/configuration/stats/#statschunkmodulesspace).
> Add chunkModulesSpace property to stats schema

- declarations/WebpackOptions.d.ts
- lib/ExternalModuleFactoryPlugin.js
- schemas/WebpackOptions.json
- test/configCases/externals/resolve/index.js
- test/configCases/externals/resolve/webpack.config.js
- types.d.ts
improve types of externals configuration option
support promises in externals
feature
yes
no
* when passing an function to `externals`
* It may return a Promise now
* There is a `getResolve` function in the first argument which is equal to the `getResolve` in loader context
> offer getResolve to externals

- lib/Compilation.js
- test/configCases/rebuild/finishModules/a.js
- test/configCases/rebuild/finishModules/index.js
- test/configCases/rebuild/finishModules/loader.js
- test/configCases/rebuild/finishModules/module.js
- test/configCases/rebuild/finishModules/other-file.js
- test/configCases/rebuild/finishModules/webpack.config.js
This PR is to address the issue raised here: https://github.com/webpack/webpack/issues/11269 - The `removeReasonsOfDependencyBlock` method was calling the removed `dependency.module` 
Bugfix. 
Yes. I'm not very happy with the method of the testing here, but I'm not familiar enough with webpack to do it in a better way. 
The test works by replacing the contents of the `other-file`, and change the exports. The test then asserts that the exports have changed.
One idea I had was to use a loader to change the `other-file`.. However I struggled with writing a custom loader.
Very open to suggestions and improvements here. 
I don't believe so. 
**What needs to be …
> Remove usage of removed API in rebuildModule

- lib/ExportsInfo.js
The body of this case clause 'UsageState.Unknown' duplicates the body of this case clause 'case UsageState.Used'. This may be caused by a copy-paste error. If this usage is intentional, consider using fall-through to remove code duplication.
Refactoring
No. This PR doesn't need any new test.
No.
There is no need to document anything.
> Remove code duplication

- declarations/_container.d.ts
- declarations/plugins/container/ContainerPlugin.d.ts
- declarations/plugins/container/ModuleFederationPlugin.d.ts
- lib/container/ContainerEntryModule.js
- lib/container/ContainerPlugin.js
- schemas/_container.json
- schemas/plugins/container/ContainerPlugin.json
- schemas/plugins/container/ModuleFederationPlugin.json
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/module-federation-custom-exposed-module-name/entry.js
- test/statsCases/module-federation-custom-exposed-module-name/webpack.config.js
- types.d.ts
Module federation generates async chunks for exposed modules, which by
default named after the internal module id. This change allows users to
assign a custom name so that the file can be statically referenced.
closes  https://github.com/webpack/webpack/issues/12504
Feature
Added 1 stats test case
No, the new `name` option is optional
This change adds a new option under ModuleFederationPlugin.exposes, if there are existing documentation they should be updated.
> feat: support custom chunk name in container expose options

- test/helpers/supportsWorker.js
compatibility fix for unit tests when running on older node.js versions that do not support `new Worker(new Url())`
existing tests were failing on older node versions
no
nothing
> Fix new Worker() compatibility check in unit tests for older node versions

- lib/Compilation.js
- test/configCases/rebuild/rebuildWithNewDependencies/a.js
- test/configCases/rebuild/rebuildWithNewDependencies/index.js
- test/configCases/rebuild/rebuildWithNewDependencies/loader.js
- test/configCases/rebuild/rebuildWithNewDependencies/other-file.js
- test/configCases/rebuild/rebuildWithNewDependencies/webpack.config.js
Currently, module rebuilds that add new dependencies to the compilation are broken. This is due to the `processDependeciesQueue` returning the already processed module entry from the queue, rather than re-processing the module. 
The fix is to invalidate the module on the queue before calling `processModuleDependencies` so that it is correctly re-processed.
**What kind of change does this PR introduce?** 
bugfix
Yes 👍 
No
Nothing
> Fix module rebuilds that add new dependencies

- lib/MultiStats.js
- lib/Stats.js
- lib/index.js
- lib/stats/DefaultStatsFactoryPlugin.js
- lib/stats/DefaultStatsPrinterPlugin.js
- lib/stats/StatsPrinter.js
- types.d.ts
Add typings matching the JSON output.
Note: the types for output are defined as `Stats*` because the types are merged together into the root level `types.d.ts` which might cause issues with other definitions. I know we could use namespaces, but [I don't believe that is possible](https://github.com/microsoft/TypeScript/issues/14233) without fully converting to TypeScript itself.
No as it's primarily compile time based, so difficult to add tests. How I've tested this:
- Locally modified `tests/Stats.test.js` so that I captured the output of the `toJson` call into a file
- Locally apply the output to a JS file and do the type cast to verify it's correct.
No. …
> fix: add typings for DefaultStatsFactoryPlugin, Stats, and MultiStats

- lib/APIPlugin.js
- lib/RuntimePlugin.js
- test/configCases/asset-modules/base-uri/index.js
- test/configCases/asset-modules/base-uri/webpack.config.js
fix missing runtime requirement for base uri
fixes #12589
feature, bugfix
yes
no
New API available in modules: `__webpack_base_uri__`.
allows to read/write the base URI for the running application. Type is `string | URL`.
> add `__webpack_base_uri__` to change base URI at runtime

- declarations/WebpackOptions.d.ts
- lib/ModuleDependencyError.js
- lib/ModuleDependencyWarning.js
- lib/NoModeWarning.js
- lib/dependencies/HarmonyImportDependency.js
- lib/stats/DefaultStatsFactoryPlugin.js
- lib/stats/DefaultStatsPresetPlugin.js
- lib/stats/DefaultStatsPrinterPlugin.js
- schemas/WebpackOptions.json
- test/Errors.test.js
- test/__snapshots__/Cli.test.js.snap
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/details-error/webpack.config.js
- test/statsCases/module-trace-disabled-in-error/webpack.config.js
- test/statsCases/module-trace-enabled-in-error/webpack.config.js
- types.d.ts
fixes #12456
* Show error details automatically when only 2 or less errors are there
* Show message that points you to errorsDetails when error details are hidden
* Improve some error messages
* Highlight important parts of error message with colors
feature, dx
yes
no
`errorDetails: "auto"` is a new value and its the default. It will show error details for errors when there are only 1 or 2 errors.
> Show error details automatically when only 2 or less errors are there

- lib/hmr/LazyCompilationPlugin.js
mini bugfix for lazy compilation on old browsers.
Previously IE11 showed:
```
SCRIPT1003: Expected ':'
```
With this change the error message is more helpful:
```
Environment doesn't support lazy compilation (requires EventSource)
```
no
no
nothing
> Fix lazy compilation not-supported error message on IE11

- lib/serialization/ObjectMiddleware.js
This avoid unnecessary calls to loaders when serializer are already registered.
It should also improve performance a bit
bugfix
no
no
nothing
> only execute loader/require when no serializer is registered yet

- lib/MultiCompiler.js
- lib/MultiStats.js
- lib/Watching.js
- lib/stats/DefaultStatsPrinterPlugin.js
- lib/webpack.js
- test/Compiler.test.js
- test/MultiCompiler.test.js
- test/ProgressPlugin.test.js
- test/WatchClose.test.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/related-assets/webpack.config.js
- types.d.ts
feature, bugfix
yes
no a butfix.
dependencies is now handled in watch mode, which changes behavior a bit
* The `dependencies` config option is largely undocumented
* It is an array of `name`s of other configs in the same array of configs. All dependencies need to be compiled before this config starts compiling.
* In watch mode `dependencies` will invalidate the compiler when the dependency has changed and when a dependency is currently compiling or invalid this config will not compile until the dependency is done.
* There is a `parallelism: number` option on the configuration array now
* It …
> MultiCompiler parallelism and dependencies

- lib/WebpackOptionsApply.js
- lib/config/defaults.js
- lib/config/target.js
- lib/dependencies/WorkerPlugin.js
electron has `importScripts` in worker
only choose a chunkLoading which fits to the chunkFormat
prefer fetch wasm loading over node wasm loading
fixes #12683
bugfix
there are no electron tests sadly
no
nothing
> fixes for electron target

- cspell.json
- lib/node/NodeTargetPlugin.js
small fix from: https://github.com/webpack/webpack/pull/12181
> chore: move unknown word to cspell.json

- lib/optimize/ConcatenatedModule.js
- test/configCases/concatenate-modules/destructuring-assignment-with-default-value-and-variable-collision-nested/config.js
- test/configCases/concatenate-modules/destructuring-assignment-with-default-value-and-variable-collision-nested/index.js
- test/configCases/concatenate-modules/destructuring-assignment-with-default-value-and-variable-collision-nested/module-a.js
- test/configCases/concatenate-modules/destructuring-assignment-with-default-value-and-variable-collision-nested/webpack.config.js
- test/configCases/concatenate-modules/destructuring-assignment-with-default-value-and-variable-collision-simple/config.js
- test/configCases/concatenate-modules/destructuring-assignment-with-default-value-and-variable-collision-simple/index.js
- test/configCases/concatenate-modules/destructuring-assignment-with-default-value-and-variable-collision-simple/module-a.js
- test/configCases/concatenate-modules/destructuring-assignment-with-default-value-and-variable-collision-simple/webpack.config.js
When using destructuring assignment in a module, in combination with a default assignment, it can cause the property looked up in the generated code to be different than the one in the source code _(it uses `newName`)_ if there's a identifier collision.
```js
// index.js
import modA from "./module-a";
import modB from "./config";
const { testProp = "defaultValue" } = modB;
modA();
console.log(testProp);
```
```js
// module-a.js
// In the real code, `stats` is read from another Webpack build
// for the client bundle, generated by `@loadable/webpack-plugin`
const stats = { testProp: 'valueFromSomeFile' };
const { testProp } = stats;
export default function printModuleAProp() {
console.log(testProp);
}
```
```js
// config.js
export default {
testProp: "configuredValue",
};
```
Generated …
> Fix module concatenation renaming bug

- lib/index.js
- types.d.ts
adding watching to the list of exported types
I am using webback watching capability in my project, but since v5, types are being provided, but Watching type is not exposed, breaking my typescript project
bugfix for typescript projects leveraging watching capability
Yes
No
Nothing, this is just a missing exported type.
> adding watching to the list of exported types in types.d.ts

- lib/ExportsInfo.js
- lib/optimize/SideEffectsFlagPlugin.js
- test/cases/side-effects/issue-12570/chunk.js
- test/cases/side-effects/issue-12570/index.js
- test/cases/side-effects/issue-12570/inner-module.js
- test/cases/side-effects/issue-12570/inner-reexport.js
- test/cases/side-effects/issue-12570/module.js
- test/cases/side-effects/issue-12570/package.json
- test/cases/side-effects/issue-12570/reexport.js
- types.d.ts
This happens when multiple exports * export the same name but the first one is discovered later in the process
In this case the ExportInfo contains both connections, but the second one is inactive.
thanks to @MLoughry for helping to debug that issue
bugfix
yes
no
nothing
> fix bug where ExportInfo uses inactive connections to find the target of an export

- lib/Compilation.js
Fix letter spelling of missing a 's'.
Just a spelling problem, please review the code.
> Fix letter spelling of missing a 's'

- lib/optimize/RealContentHashPlugin.js
- test/__snapshots__/StatsTestCases.test.js.snap
- test/statsCases/real-content-hash/a/a.js
- test/statsCases/real-content-hash/a/b.js
- test/statsCases/real-content-hash/a/lazy.js
- test/statsCases/real-content-hash/b/a.js
- test/statsCases/real-content-hash/b/b.js
- test/statsCases/real-content-hash/b/lazy.js
- test/statsCases/real-content-hash/test.config.js
- test/statsCases/real-content-hash/webpack.config.js
> fix problem where emitting an asset twice affects the hash

- lib/util/fs.js
Fixes https://github.com/webpack/webpack/issues/12305
UNC paths, of the form `\\hostname\path\to\file` are defined in section 2.2.57 of https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-DTYP/%5bMS-DTYP%5d.pdf. See also https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths, for example.
bugfix
I don't know where the tests for these filesystem functions are. I'm happy to add tests if someone points to where they should go.
Also, I'm writing this a bit blind--I don't have a windows system set up to test this. This is very similar to the fix reported to work in practice from https://github.com/webpack/webpack/issues/12305, except it fixes the code given …
> Handle Windows UNC paths as Windows paths

- test/configCases/resolve/fallback/a/1.js
- test/configCases/resolve/fallback/a/2.js
- test/configCases/resolve/fallback/b/2.js
- test/configCases/resolve/fallback/index.js
- test/configCases/resolve/fallback/webpack.config.js
This is an additional test for showing the `resolve.fallback` functionality, ensuring that it does not override packages that do already exist.
my changes are just a test
nah
nothing
> Add a test case for resolve.fallback

- lib/SourceMapDevToolPlugin.js
- lib/config/defaults.js
- test/BuildDependencies.test.js
- test/StatsTestCases.test.js
- test/configCases/worker/node-worker-named/index.js
- test/fixtures/buildDependencies/run.js
- test/hotCases/worker/update-in-worker/index.js
- test/hotCases/worker/update-in-worker/worker.js
Also points out errors reading the package.json more verbosely
performance, caching
yes
no
You might see invalid JSON in package.json breaking the build, but that's intendent.
nothing
> avoid making the package.json in context a build dependency

- lib/util/deterministicGrouping.js
- test/__snapshots__/StatsTestCases.test.js.snap
Please see https://github.com/webpack/webpack/issues/12487#issuecomment-792747387 for explanation.
Bugfix, fixes #12487
This may, I guess, cause build to produce files smaller than `minSize`, but that's better than crashing in such cases.
Nope, I don't know this repo well enough to create them. Happy to work with anyone willing to come up with some.
No
Nothing
> fix deterministicGrouping looping over group.nodes's negative indexes

- declarations/WebpackOptions.d.ts
- lib/asset/AssetGenerator.js
- lib/asset/AssetModulesPlugin.js
- lib/asset/AssetParser.js
- lib/asset/AssetSourceParser.js
- package.json
- schemas/WebpackOptions.json
- test/__snapshots__/Cli.test.js.snap
- test/configCases/asset-modules/assetModuleFilename/index.js
- test/configCases/asset-modules/assetModuleFilename/webpack.config.js
- types.d.ts
- yarn.lock
fixes #12771
bugfix
yes
no, but a deprecation
* `filename` has been moved from the asset modules generator options to the parser options.
* The old option will still work, but is deprecated and should be removed from docs
* `module.parser.asset.filename` or `Rule.parser.filename` (for type asset)
* Also in `module.parser["asset/resource"].filename`
* Removed: `module.generator.asset.filename` and `module.generator["asset/resource"].filename`
> fix memory leak in asset generator

- lib/node/RequireChunkLoadingRuntimeModule.js
- lib/sharing/ConsumeSharedPlugin.js
- lib/sharing/ConsumeSharedRuntimeModule.js
- lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js
- test/hotCases/sharing/share-plugin/common.js
- test/hotCases/sharing/share-plugin/index.js
- test/hotCases/sharing/share-plugin/module.js
- test/hotCases/sharing/share-plugin/webpack.config.js
- Fixes a bug that caused HMR to fail when using Module Federation (`__webpack_modules__` is not defined).
- Fixes: #12830
I didn't, it would be great if some direction could be given as to where a test for something like this would go. Assuming `hotCases`? 
It doesn't introduce breaking changes.
This is an internals change, I don't believe this warrants a documentation change.
> fix: use runtime globals in shared plugin

- declarations/WebpackOptions.d.ts
- lib/Compilation.js
- lib/RuntimeTemplate.js
- lib/asset/AssetGenerator.js
- lib/asset/AssetModulesPlugin.js
- lib/asset/AssetParser.js
- schemas/WebpackOptions.json
- test/__snapshots__/Cli.test.js.snap
- test/configCases/asset-modules/assetModuleFilename/index.js
- test/configCases/asset-modules/assetModuleFilename/webpack.config.js
- test/configCases/asset-modules/emit/index.js
- test/configCases/asset-modules/emit/webpack.config.js
- types.d.ts
fixes #12474
feature
yes
no
* the parser options for asset modules have a new `emit` option. Defaults to true. Setting it to false will opt-out from writing assets from asset modules.
> add `emit` option for asset modules

- lib/dependencies/WorkerDependency.js
- lib/dependencies/WorkerPlugin.js
- lib/javascript/JavascriptParser.js
- test/configCases/worker/web-worker/index.js
- test/helpers/createFakeWorker.js
- types.d.ts
bugfix
No. The issue is, in Node.js (which Jest uses) everything works fine even without this change, since `type: 'module'` is silently ignored, and so I'm not sure how to test it aside from manually verifying the change.
It looks like there are no snapshots to compare against either.
For example, the output of `test/configCases/worker/**` tests has changed, and I could see it manually, but tests pass either way.
Potentially - in addition to existing restrictions, it will now also skip expressions like `new Worker(new URL('some.js'), import.meta.url), someDynamicExpressionForOptionsObject())` whereas previously they would be accepted. I think this is a …
> Remove `type: 'module'` from `new Worker` exprs

- lib/Compilation.js
- lib/DefinePlugin.js
- lib/Module.js
- lib/NormalModule.js
- test/BuildDependencies.test.js
- test/fixtures/buildDependencies/definedValue.js
- test/fixtures/buildDependencies/index.js
- test/fixtures/buildDependencies/run.js
- test/watchCases/plugins/define-plugin/0/index.js
- test/watchCases/plugins/define-plugin/0/module4.js
- test/watchCases/plugins/define-plugin/0/module5.js
- test/watchCases/plugins/define-plugin/webpack.config.js
- types.d.ts
The options of the DefinePlugin no longer have to be covered by build dependencies
feature
yes
no
* The constant options of the DefinePlugin do not have to be covered by build dependencies.
* but for the `DefinePlugin.runtimeValue` generator function build dependencies need to be used
* `DefinePlugin.runtimeValue` has now an options argument as second argument
* `options.fileDependencies: string[]` list of files the function depends on
* `options.contextDependencies: string[]` list of directories the function depends on
* `options.missingDependencies: string[]` list of not existing files the …
> DefinePlugin takes care of module invalidation when values have changed

- lib/cache/ResolverCachePlugin.js
When upgrading to v5, I ran into this issue https://github.com/webpack/webpack/issues/12701, which is caused by `core-js` and `babel` polyfilling the `addAll` method to all collection prototypes. webpack's use the existence of an `addAll` method to determine whether or not it's dealing with a `LazySet`, then it calls this method. Unfortunately, because the ES Proposal version expects `addAll(...items)` and `LazySet` expects `addAll(Iterable)`, this causes all sorts of issues.
This PR changes the `in` check for `addAll` in `addAllToSet` to an `instanceof` check for `LazySet`.
fixes #12701
I would like to add tests, but it wasn't clear to me where a test for this should go as none of the test files …
> fixed possible collision with addAll es proposal

- lib/NormalModuleFactory.js
- test/cases/entry-exports-field/imports/index.js
- test/cases/entry-exports-field/imports/package.json
- test/cases/entry-exports-field/imports/pkg.mjs
bugfix, fixes #12928
This is a failing test for usage of the "imports" field per https://github.com/webpack/webpack/issues/12928.
It extends the exports tests.
No
> fix package "imports"

- lib/MultiCompiler.js
- test/MultiCompiler.test.js
#12915 introduced a bug that causes watchers to remain blocked when a `MultiCompiler` is watched. This PR ensures that when an invalidation occurs after a successful watch-run the subsequent build does not hang.
Yes.
It shouldn't. 
Nothing, this is an internals change.
> fix: allow invalidation after first watch run

- lib/serialization/ObjectMiddleware.js
> improve cache serialization performance by 30%

- lib/index.js
- lib/stats/DefaultStatsFactoryPlugin.js
- types.d.ts
Fixes #13014
Typescript types improvement.
There don't appear to be tests for asserting typescript exports. if someone can point me at some, happy to update them.
No
N/A
---
As @alexander-akait mentioned, `StatsAsset` has so far been considered internal.
However, any type referenced by an exported type is also indirectly public/exposed, so we already had access to this type anyway and needed it when dealing with `assets`:
```ts
const fn = (asset: StatsAsset) => { ... };
stats.assets.map(fn);
```
One suggestion I had to reduce the surface we expose was to introduce a subset of the interface like …
> expose Stats types

- declarations/WebpackOptions.d.ts
- schemas/WebpackOptions.json
- test/__snapshots__/Cli.test.js.snap
- types.d.ts
I can't add `groupModulesByType: true` in the stats options or
```
all: true
groupModulesByType: false
```
But `groupModulesByType` is available in StatsPlugin
This PR fixes this.
bugfix
no
no
about groupModulesByType
> (fix): add missing scheme property stats.groupModulesByType

- declarations/WebpackOptions.d.ts
- lib/Compiler.js
- lib/FileSystemInfo.js
- lib/NormalModule.js
- lib/WebpackOptionsApply.js
- lib/cache/IdleFileCachePlugin.js
- lib/cache/MemoryCachePlugin.js
- lib/cache/MemoryWithGcCachePlugin.js
- lib/cache/PackFileCacheStrategy.js
- lib/config/defaults.js
- lib/config/normalization.js
- lib/javascript/JavascriptParser.js
- lib/serialization/ObjectMiddleware.js
- schemas/WebpackOptions.json
- test/Defaults.unittest.js
- test/__snapshots__/Cli.test.js.snap
- types.d.ts
* adds workaround for a v8 memory leak problem in ICs when code becomes optimized
* add GC to the memory cache and make it configurable
* memory GC happens by default when persistent cache is enabled and in development mode
* otherwise memory cache is kept forever
* make maxAge for persistent cache configurable
* GC the oldest content file even if it's not touched (to keep cache size small)
* filesystem cache will now no longer cache in memory, but restore items from disk again when it was persisted
* Caches will be cleared on shutdown. That should allow to GC cache items once they are serialized.
bugfix, memory leak, feature
n/a
no
**What needs to be …
> memory usage improvements, add GC support for memory cache, persistent cache only mode

- declarations/WebpackOptions.d.ts
- lib/config/defaults.js
- lib/logging/createConsoleLogger.js
- lib/node/NodeEnvironmentPlugin.js
- lib/node/nodeConsole.js
- schemas/WebpackOptions.json
- test/Compiler.test.js
- test/ConfigTestCases.template.js
- test/Defaults.unittest.js
- test/ProgressPlugin.test.js
- test/StatsTestCases.test.js
- test/TestCases.template.js
- test/__snapshots__/Cli.test.js.snap
- test/__snapshots__/StatsTestCases.test.js.snap
- test/helpers/LogTestPlugin.js
- test/helpers/captureStdio.js
- types.d.ts
Fixes #12899
Since it's my first try of contribution to webpack, even if I looked carefully for impacted default values etc, there can exists some missed parts. Please review carefully for me to fix things. Thanks!
feature
Yes
No
* `infrastructureLogging.colors` Enables/Disables colorful output.
* `infrastructureLogging.appendOnly` Only appends lines to the output. Avoids updating existing output e. g. for status messages.
* `infrastructureLogging.stream` Stream used for logging output. Defaults to process.stderr.
* `infrastructureLogging.console` Custom console used for logging.
* When stream is …
> feat: add colors flag to infrastructureLogging

- lib/Dependency.js
- lib/ExportsInfo.js
- lib/FlagDependencyExportsPlugin.js
- lib/dependencies/HarmonyExportExpressionDependency.js
- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- lib/dependencies/HarmonyExportSpecifierDependency.js
- test/configCases/side-effects/type-reexports/a.js
- test/configCases/side-effects/type-reexports/b.js
- test/configCases/side-effects/type-reexports/index.js
- test/configCases/side-effects/type-reexports/module.js
- test/configCases/side-effects/type-reexports/webpack.config.js
- types.d.ts
This allows to optimize cases where empty modules are reexported e. g. caused by typescript type-only exports
improvement
yes
no
nothing
> prioritize static reexport over runtime reexport for target determination

- lib/CodeGenerationResults.js
- lib/Compilation.js
- lib/Compiler.js
- lib/serialization/BinaryMiddleware.js
- types.d.ts
> memory and performance optimizations

- declarations/WebpackOptions.d.ts
- lib/EntryOptionPlugin.js
- lib/RuntimePlugin.js
- lib/config/normalization.js
- lib/runtime/PublicPathRuntimeModule.js
- schemas/WebpackOptions.json
- test/configCases/output/publicPath-web/c.js
- test/configCases/output/publicPath-web/d.js
- test/configCases/output/publicPath-web/webpack.config.js
- types.d.ts
related to https://github.com/webpack-contrib/mini-css-extract-plugin/pull/737
feature
yes
no
* `entry.xxx.publicPath` allows to set the public path per entry (see also `output.publicPath`)
> allow to specify `publicPath` for each entrypoint

- lib/dependencies/LoaderPlugin.js
- test/configCases/loader-import-module/css/index.js
- test/configCases/loader-import-module/css/loader.js
- test/configCases/loader-import-module/css/webpack.config.js
bugfix
yes
no
* Second argument to `this.importModule` is an `options` object with
* `options.layer` module layer in which modules should be built
* `options.publicPath` the public path used for the built modules
> fix passing publicPath to `this.importModule`

- lib/optimize/LimitChunkCountPlugin.js
Just a quick test whether the issue can easily be solved
by using the chunkGraph instead of the old methods.
https://github.com/webpack/webpack/issues/13099
bugfix
No
No
> Fix deprecation message for LimitChunkCountPlugin

- lib/FileSystemInfo.js
> cheaper getIterator

- lib/FileSystemInfo.js
- test/fixtures/buildDependencies/index.js
- test/fixtures/buildDependencies/run.js
escaped with \0
i don't understand the reasoning behind @sokra's escaping in enhanced resolve well enough to know if this makes sense or is basically just undoing the hard work he did to distinguish these characters from fragments. maybe he can chime in if this makes no sense to do
closes #13148
closes #12156
@sokra  not sure if the escaping in the commit below was meant to be used in other places but it breaks here. i'm very new to all of this code so let me know if this direction is wrong. 
https://github.com/webpack/enhanced-resolve/commit/17cf8fee0769cafce3067aa4d169cefad26e107a
bugfix
not yet. once again not sure if this is the right direction or just a regression of the fragment work in enhanced …
> fix(resolve): allows filesysteminfo to resolve files that have #'s

- lib/dependencies/WorkerPlugin.js
Make auto-generated runtime name a hash instead of leaking pathinfo
Make auto-generated runtime name more stable by using index instead of source code location
fixes #12883
bugfix
no
no
nothing
> fix problems with auto-generated runtime name for workers

- lib/util/fs.js
- types.d.ts
Ref: #11630 
Fixes callback signature types for InputFileSystem and OutputFileSystem. Errors in the callback may be null, but were not marked as such. This PR fixes that.
bugfix
not needed
no
nothing
> make errors nullable for call signatures of filesystem types

- lib/Watching.js
- lib/node/NodeWatchFileSystem.js
- test/WatchSuspend.test.js
- types.d.ts
bugfix
yes
no
nothing
Co-authored-by: Vladimir Razuvaev <vladimir.razuvaev@gmail.com>
> fix suspend and resuming watching correctly

- lib/EntryPlugin.js
- lib/ExportsInfo.js
- lib/config/target.js
- lib/serialization/BinaryMiddleware.js
- lib/stats/DefaultStatsFactoryPlugin.js
- lib/util/createHash.js
- lib/util/serialization.js
- types.d.ts
> Performance improvements

- lib/config/normalization.js
Fixes #13491 13491
allowCollectingMemory is being normalized away in options normalization. Small fix to pass it through from config.
bugfix
no, if there are tests that could have caught this, can update
no
no
> Respect allowCollectingMemory setting (being normalized away right now)

- lib/Compilation.js
- lib/cache/PackFileCacheStrategy.js
- lib/serialization/SerializerMiddleware.js
- lib/util/ArrayQueue.js
- lib/util/AsyncQueue.js
- types.d.ts
#13127
memory leaks
no
no
nothing
> reduce memory usage and fix memory leaks

- lib/util/LazySet.js
- test/LazySet.unittest.js
Closes #13573
The summarizeDependencies call is very expensive in large projects because of the huge merge/flatten cycle required by LazySet. I notice that many of these LazySets are empty, so lets short circuit those to limit the number of times the `size > 100000` trigger is met for merging.
performance improvement to LazySet in large projects
yep, and also regressions show in multiple tests due to high usage of LazySet
no
no
> perf: Limit frequency of LazySet flattening by shortcircuiting empty LazySets

- declarations/LoaderContext.d.ts
- types.d.ts
As stated in the [documentation](https://webpack.js.org/api/loaders/#thisemitfile), and proven in practice, `emitFile` accepts a buffer for the content argument. Currently, passing one results in a type error. This corrects the argument type.
bug fix
No
No
Nothing, this updates the type to match the documentation.
> Correct emitFile content argument type

- lib/node/NodeTargetPlugin.js
- test/ConfigTestCases.template.js
- test/configCases/node/node-prefix/index.js
- test/configCases/node/node-prefix/webpack.config.js
follow-up from: https://github.com/webpack/webpack/pull/12181
adds 'node:' prefixed builtin modules.
https://nodejs.org/docs/latest-v12.x/api/esm.html#esm_node_imports
https://github.com/nodejs/node/pull/37246
> feat: add node: prefixed modules

- examples/README.md
The wasm-simple and wasm-complex examples were missing from the `examples/README.md` table of contents. This adds them, in a new WebAssembly section, with brief descriptions.
Documentation
Not applicable.
No.
The changes _are_ documentation. Nothing more is needed.
> doc: add wasm examples to ToC

- lib/Compiler.js
- lib/NormalModuleFactory.js
- types.d.ts
this is a workaround to remove compilation-specific references from modules in the unsafe cache
I'm not proud of this solution, but it fixes it for now
Long term we might move these kind of references out of the module
into some kind of compilation/module graph specific store.
But that's not yet possible for backward-compat reasons.
#13127
bugfix
no
no
nothing
> fix memory leak when using the unsafe cache

- lib/Template.js
- lib/esm/ExportWebpackRequireRuntimeModule.js
- lib/esm/ModuleChunkFormatPlugin.js
- lib/esm/ModuleChunkLoadingPlugin.js
- lib/esm/ModuleChunkLoadingRuntimeModule.js
- test/configCases/library/0-create-library/webpack.config.js
- test/configCases/library/1-use-library/webpack.config.js
> add support for import chunk loading with runtime chunk

- lib/library/SystemLibraryPlugin.js
- test/configCases/externals/externals-system-custom/index.js
- test/configCases/externals/externals-system-custom/test.config.js
- test/configCases/externals/externals-system-custom/webpack.config.js
Hi!
This tiny change makes externals with custom type specified work correctly with "system" library target.
Now they only work with "umd" library target because of these lines:
https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/library/UmdLibraryPlugin.js#L126-L133
I see similar issue with AMD bundle type too, but let's start with System.js first ;)
bugfix
yes
I believe not :)
Nothing :)
> fix: fixed work of the non-system type externals for "system" library target

- lib/asset/AssetGenerator.js
- lib/schemes/DataUriPlugin.js
- test/configCases/asset-modules/input-data-url-encoding/index.js
- test/configCases/asset-modules/input-data-url-encoding/webpack.config.js
- test/configCases/asset-modules/input-data-url/index.js
bugfix https://github.com/webpack-contrib/css-loader/issues/1342
yes
no
nothing
> fix: data URI for `image/svg+xml`

- lib/hmr/HotModuleReplacement.runtime.js
- test/HotTestCases.template.js
- test/hotCases/invalidate/during-idle/index.js
- test/hotCases/status/accept/file.js
- test/hotCases/status/accept/index.js
This change allows handlers registered using `addStatusHandler` to return a `Promise`. The HMR system will wait until the promise settles before continuing. This allows asynchronous handling of state changes.
In our case, we use this to make sure that when our service worker is modified the update is complete and the service worker installed before the dev server triggers a reload on an unaccepted update.
The diff is much easier to read with ignore whitespace turned on.
New feature.
Yes.
No. Handler return values were ignored before, but the worst thing that could happen in the unlikely case that someone was inadvertently returning a `Promise` from a …
> Allow HMR status handlers to return a Promise

- lib/asset/AssetGenerator.js
- test/configCases/asset-modules/rule-generator-publicPath-override/index.js
- test/configCases/asset-modules/rule-generator-publicPath-override/webpack.config.js
Fixing the second issue described in this PR https://github.com/vercel/next.js/pull/27413#issue-695368311
empty string in `rule.generator.publicPath` gets ignored.
bugfix
yep
nope
nothing
> Fix generator publicPath behavior when empty string

- lib/FileSystemInfo.js
- lib/util/fs.js
- test/FileSystemInfo.unittest.js
- types.d.ts
refactor context snapshotting for abstraction purposes
add (symlink) unit test cases for FileSystemInfo snapshotting
fixes #12246
This allows symlinks to be correctly snapshotted by FileSystemInfo.
* circular references are eliminated
* context that includes a symlinked directory will include content of that directory
* For all snapshotting modes (timestamps, hashes, or both)
bugfix
yes
no
nothing
> track and resolve symlinks when reading context timestamps/hashes

- lib/Compilation.js
Although the callbacks for the `addModuleChain` and `addModuleTree` methods are of type `ModuleCallback`, the `result` parameter is always `undefined`. We are migrating some internal plugins from webpack 4 that use the `compilation._addModuleChain` method and rely on the callback to get the created module.
Thanks.
This fixes inconsistency between types and implementation. I'm not sure it's a bugfix since nothing internally was relying on the `result` parameter but it doesn't seem like a feature.
I did not add tests but I am open to recommendations about what to test here.
This change should be backwards compatible and all of the `compilation.addModuleChain` …
> Pass module to `compilation.addModuleChain()` callback when applicable

- lib/NormalModuleFactory.js
- test/configCases/loader-import-module/css/webpack.config.js
`.webpack[]` should not be used for resource path
fixes https://github.com/webpack-contrib/mini-css-extract-plugin/issues/755
yes
no
nothing
> match resource should not include special `.webpack[...]` extension

- lib/node/NodeTargetPlugin.js
node has stream/web built-in module. See https://nodejs.org/api/webstreams.html#webstreams_example_readablestream. And the latest `fetch-blob` depends on stream/web. When people use webpack to pack their code which depends on the latest `node-fetch@3.0.0`, it will give this error `Module not found: Error: Can't resolve 'stream/web'`
https://github.com/node-fetch/fetch-blob/issues/117#issue-990726939
> fix: add stream/web to NodeTargetPlugin

- lib/ModuleGraph.js
- lib/dependencies/CommonJsExportRequireDependency.js
- lib/dependencies/CommonJsFullRequireDependency.js
- lib/dependencies/HarmonyImportDependency.js
lazy assign connections to dependencies
in many cases (e. g. cached builds) we don't need the assignment
performance
no
no
nothing
> improve module graph building performance

- lib/dependencies/AMDRequireDependency.js
- lib/dependencies/RequireEnsureDependency.js
- lib/node/RequireChunkLoadingRuntimeModule.js
- lib/runtime/AsyncModuleRuntimeModule.js
- lib/sharing/ConsumeSharedRuntimeModule.js
- lib/sharing/ShareRuntimeModule.js
- test/__snapshots__/StatsTestCases.basictest.js.snap
bugfix for breaking code under ES3 when access `.catch` of promises, which is related to #13972
> use propertyAccess to generate .catch code

- lib/dependencies/CommonJsImportsParserPlugin.js
- lib/dependencies/CommonJsRequireContextDependency.js
- lib/dependencies/ContextDependency.js
- lib/dependencies/ContextDependencyTemplateAsRequireCall.js
- test/configCases/parsing/issue-14545/index.js
- test/configCases/parsing/issue-14545/module.js
- test/configCases/parsing/issue-14545/webpack.config.js
close #14545
Yes.
No.
No need.
> fix: create contexts in object shorthand syntax

- lib/RuntimePlugin.js
- test/configCases/entry/issue-13637/index-system.js
- test/configCases/entry/issue-13637/index-umd.js
- test/configCases/entry/issue-13637/test.config.js
- test/configCases/entry/issue-13637/webpack.config.js
- test/configCases/target/system-context/webpack.config.js
Fixes #13637. The `__system_context__` injection was not working when using entries with different `library.type` values.
Yes
No
> respect entry-specific library.type when exposing system context

- lib/stats/DefaultStatsPrinterPlugin.js
bugfix
fixes #14678 
no
nothing
nothing
> fix regexp in DefaultStatsPrinterPlugin.js

- lib/config/defaults.js
- lib/dependencies/HarmonyExportDependencyParserPlugin.js
- lib/dependencies/HarmonyExportImportedSpecifierDependency.js
- lib/dependencies/HarmonyImportDependencyParserPlugin.js
- lib/dependencies/HarmonyImportSpecifierDependency.js
- test/Defaults.unittest.js
- test/configCases/compiletime/exports-presence/webpack.config.js
The names of the new export options do not match the names present in the options schema. Note how different places have an "s" after exports while some don't. This change simply fixes all cases where the options used in webpack didn't match the outward display names.
https://github.com/webpack/webpack/blob/14dd4f912c013f060bf7843a3d5462a51ff3051b/types.d.ts#L5341
bugfix
no, but fixes recently added tests
kind of, but more fixes the options values introduced this morning
nothing beyond what needs to be documented for initial change
> Fix names of options to match the exported types

- lib/FileSystemInfo.js
- test/fixtures/buildDependencies/esm.mjs
> fix using single quotes with esm files

- lib/buildChunkGraph.js
- test/configCases/entry/no-chunking/a.js
- test/configCases/entry/no-chunking/async.js
- test/configCases/entry/no-chunking/b.js
- test/configCases/entry/no-chunking/nested.js
- test/configCases/entry/no-chunking/test.config.js
- test/configCases/entry/no-chunking/webpack.config.js
feature
yes
no
* `chunkLoading: false` disables on demand loading of chunks and puts everything in the main chunk
> add `chunkLoading: false` support

- lib/WatchIgnorePlugin.js
- lib/util/ArrayHelpers.js
- test/ArrayHelpers.unittest.js
Another small perf win I found from our CPU profiles. Seems there are a few other optimizations available in the watching setup and teardown in each invalidation cycle. In large projects, especially in monorepos which may even just ignore most files), there is a bunch of repeated work per entry. While I am still spending time ramping up in the area, I will try to take out some quick wins.
Based on CPU profiles, this change improves our recompile time by about 50ms. Not a lot, but its free!
perf
yes
no
no
> perf: Prevent running regexs over the same strings twice

- lib/debug/ProfilingPlugin.js
- test/ProfilingPlugin.test.js
fixes #14696
bugfix
no
no
nothing
> check hooks for existance before using in ProfilingPlugin

- module.d.ts
I changed `webpack/module` types to make sure that calling `import.meta.webpackHot.accept()` without arguments still works.
I used `@types/webpack-env` before and there the error handler parameter is optional. Error typing itself is not helpful though.
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2026ab9fbd33457124a0a6a55d5c1d1e3f696764/types/webpack-env/index.d.ts#L145
Types change.
Does webpack have tests for these type definitions? If not, then I would propose a tool called [expect-type](https://www.npmjs.com/package/expect-type), which looks pretty convenient. Here are some examples of what it could look like https://github.com/faergeek/typed-forms/blob/03d73b0964e47ac9a4984d74b0800b5 …
> Make errorHandler optional in accept(self)

- lib/WatchIgnorePlugin.js
- lib/Watching.js
- lib/node/NodeWatchFileSystem.js
- lib/util/fs.js
- package.json
- types.d.ts
- yarn.lock
Integrate changes in watchpack to ensure fileTimestamps and contextTimestamps are seperate (smaller) maps. Also, since we fill both maps in one call, we limit calling into the watcher twice to fill out those lists (by sharing the fileMap and directoryMap within all watcher calls).
Also includes the other features, bugfixes, and perf improvements listed here
https://github.com/webpack/watchpack/releases/tag/v2.3.0 
perf & feature
on watchpack side, yes. For webpack, no, ensure current tests pass, there is no expected change in functionality
no
yes, with watchpack update
allow functions passed to …
> perf: upgrade watchpack & split timestamp by file/dependency & only call collectTimeInfoEntries once per invalid

- lib/sharing/ConsumeSharedRuntimeModule.js
- test/configCases/container/1-container-full/webpack.config.js
- test/configCases/container/2-container-full/index.js
- test/configCases/container/2-container-full/webpack.config.js
- test/configCases/sharing/consume-module/index.js
closes #13020 
Add more info to the invalid singleton version error message
> feat: show which singleton loaded version

- lib/container/ContainerEntryModule.js
- test/ConfigTestCases.template.js
- test/configCases/container/0-container-full/test.config.js
- test/configCases/container/0-container-full/webpack.config.js
- test/configCases/container/1-container-full/package.json
- test/configCases/container/1-container-full/test.config.js
- test/configCases/container/1-container-full/webpack.config.js
This fixes the problems when using:
``` js
experiments: {
outputModule: true
},
plugins: [
new ModuleFederationPlugin({
library: { type: "module" },
...
```
bugfix
yes
no
nothing
> fix and test module federation with ESM

- lib/container/ContainerEntryModule.js
- lib/esm/ModuleChunkFormatPlugin.js
- lib/javascript/ChunkHelpers.js
- lib/javascript/StartupHelpers.js
- test/ConfigTestCases.template.js
- test/configCases/container/0-container-full/test.config.js
- test/configCases/container/0-container-full/webpack.config.js
- test/configCases/container/1-container-full/package.json
- test/configCases/container/1-container-full/test.config.js
- test/configCases/container/1-container-full/webpack.config.js
- test/configCases/module/runtime-chunk/test.config.js
- test/configCases/module/runtime-chunk/webpack.config.js
- test/configCases/module/split-chunks/index.js
- test/configCases/module/split-chunks/separate.js
- test/configCases/module/split-chunks/test.config.js
- test/configCases/module/split-chunks/webpack.config.js
> fix outputModule with initial splitChunks

- lib/RuntimeTemplate.js
- test/RuntimeTemplate.unittest.js
fix small regression  from https://github.com/webpack/webpack/pull/14784
no
no
nothing
> fix RuntimeTemplate

- lib/index.js
- types.d.ts
@Brian-McBride rebase of https://github.com/webpack/webpack/pull/12875
This exposes more type definitions that are required for proper plugin development using Typescript.
There are no existing type tests. Added the types and ran the `fix` script as directed.
Np, there are no type changes, just adding to the final export. The `fix` script changed the actual definition file. My edit was only to `lib/index.js`
Nothing. Typescript is self documentation.
> Adding types

- lib/sharing/ConsumeSharedModule.js
- lib/sharing/ConsumeSharedRuntimeModule.js
- test/configCases/sharing/consume-module/index.js
- test/configCases/sharing/consume-module/node_modules/singletonWithoutVersion.js
- test/configCases/sharing/consume-module/webpack.config.js
This addresses (fixes #14795) . Previously, when using module federation, if requiredVersion was false, the singleton flag would be entirely ignored. Since it's entirely valid to require one instance of a package be instantiated, but not care at all what version it is, this seems like an oversight.
The core of this change is in `ConsumeSharedModule.codeGeneration`, which now includes logic for when requiredVersion is false but singleton is true. Specifically, it causes the generated code to call one of two new functions - loadSingleton, or loadSingletonFallback if a fallback is present. The code for these new functions is located in `ConsumeSharedRuntimeModule.generate`, along with a helper function, getSingleton, which acts similarly to …
> Proposed fix to module federation to stop ignoring the singleton flag when requiredVersion is false

- package.json
- yarn.lock
First step in being able to complete:
https://github.com/webpack/enhanced-resolve/issues/316
https://github.com/xz64/license-webpack-plugin/issues/109
deps upgrade to support https://github.com/isaacs/node-graceful-fs/issues/221
no
no
nothing
> Upgrade graceful-fs to support throwIfNoEntry in input/output filesystem

- lib/Watching.js
Resolves #15040 
default config change
no, all tests pass though
no
https://webpack.js.org/configuration/watch/#watchoptionsaggregatetimeout
above default should be updated. not sure if docs defaults are updated automatically
> lower default aggregateTimeout to 20ms

- lib/CacheFacade.js
- test/MultiItemCache.unittest.js
One of the projects I'm on at work has such a large number of outputs (currently 1400 and growing) and that is causing webpack to crash during compilation. You can [see in the stack trace](https://gist.github.com/dtanders/b244f9d58757b2ad57486a2981a88097#file-webpack_stack_trace-txt-L7942) starting here that the same 6 lines repeat a little over 1200 times until the stack is exhausted. This is because the MultiItemCache in lib/CacheFacade.js uses recursion to iterate over it's item list when you call get().  This implementation prevents stack exhaustion both in the included unit test and in my testing with our project. I'm sure it could be more elegantly written but I've taken care to avoid behavioral changes other than preventing our use case from blowing the stack.
**What kind of change …
> Change the Implementation of get() in MultiItemCache to Prevent Stack Exhaustion

- lib/cli.js
- test/Cli.basictest.js
- test/__snapshots__/Cli.basictest.js.snap
- types.d.ts
Feature
- add `cliDescription` -  Sometimes we need specific descriptions for CLI options, for example when we are deprecating a CLI option only in favor of another  
- https://github.com/webpack/webpack-dev-server/pull/4091 
- https://github.com/webpack/webpack-dev-server/pull/4098
- add `negatedDescription` - `webpack-cli` creates a negative flag for each `boolean` flag, it uses [`negatedDescription` property for description if available](https://github.com/webpack/webpack-cli/blob/ebf665344079489f2b4f36d7d1c5e46b36550985/packages/webpack-cli/lib/webpack-cli.js#L467).
Yes
No
It is for internal …
> feat: allow specific description for CLI options

- lib/debug/ProfilingPlugin.js
- test/WatchTestCases.template.js
- test/watchCases/plugins/profiling-plugin/0/index.js
- test/watchCases/plugins/profiling-plugin/1/index.js
- test/watchCases/plugins/profiling-plugin/deprecations.js
- test/watchCases/plugins/profiling-plugin/webpack.config.js
Fixes #9114
By moving away from noStream mode, we get the same functionality (by pushing the fine "]" to make valid JSON) in non-watch scenario. In the watch scenario, we continue to keep the tracer running until the watch process ends. This will typically result in a near-complete JSON (missing a final "]"). Since streaming traces is so common, common stream inspectors (chrome://inspect) will fix up near-valid JSON for you.
bugfix
yes
no
nothing
> Fix ProfilingPlugin for watch scenarios

- README.md
Doc change only.
Checked the link, skipping the redirect HTTP => HTTPS this way 0:-)
There are 3 more HTTP-only links, but they sadly have to remain as is, since HTTPS is not available for them.
Not applicable.
No.
Nothing.
> browserify link: HTTP => HTTPS

- lib/async-modules/AwaitDependenciesInitFragment.js
- lib/dependencies/HarmonyCompatibilityDependency.js
- lib/runtime/AsyncModuleRuntimeModule.js
- lib/wasm-async/AsyncWebAssemblyJavascriptGenerator.js
- test/__snapshots__/StatsTestCases.basictest.js.snap
- test/cases/async-modules/double-import/a.js
- test/cases/async-modules/double-import/b.js
- test/cases/async-modules/double-import/index.js
- test/cases/async-modules/double-import/main.js
- test/cases/async-modules/double-import/shared.js
- test/cases/async-modules/top-level-error/counter.js
- test/cases/async-modules/top-level-error/index.js
- test/cases/async-modules/top-level-error/main.js
- test/cases/async-modules/top-level-error/module.js
- test/cases/async-modules/top-level-error/reexport.js
bugfix, fixes https://github.com/vercel/next.js/issues/32360
yes
no
nothing
> fix handling of errors thrown in async modules

- lib/APIPlugin.js
- lib/Module.js
- test/cases/parsing/api/id.js
- test/cases/parsing/api/index.js
- test/cases/parsing/api/module.js
- test/cases/parsing/api/typeof-module.js
feature
yes
no
* `__webpack_module__ ` equals to `module` but is always available (`module` is not available in strict ESM)
* `__webpack_module_id__` equals to `module.id` but is always available (`module` is not available in strict ESM)
> add __webpack_module__ and __webpack_module_id__ to the api

- lib/TemplatedPathPlugin.js
- test/configCases/asset-modules/resource-from-data-uri/index.js
- test/configCases/asset-modules/resource-from-data-uri/webpack.config.js
fixes #13835 
- infer extension from mime type
- set path like replacement to empty string
yes
no
for assets builded from data uri replacements:
`[name]`, `[file]`, `[query]`, `[fragment]`, `[base]`, `[path]` set to empty string
> fix resource name when filename is data uri

- lib/ContextModule.js
- lib/ContextModuleFactory.js
- lib/cache/ResolverCachePlugin.js
- package.json
- test/ContextModule.unittest.js
- test/ContextModuleFactory.unittest.js
- test/__snapshots__/StatsTestCases.basictest.js.snap
- test/configCases/resolve/issue-11335-context-module/index.js
- test/configCases/resolve/issue-11335-context-module/src/foo/widgets/b.js
- test/configCases/resolve/issue-11335-context-module/src/foo/widgets/c.js
- test/configCases/resolve/issue-11335-context-module/src/main/widgets/a.js
- test/configCases/resolve/issue-11335-context-module/src/main/widgets/b.js
- test/configCases/resolve/issue-11335-context-module/webpack.config.js
- test/statsCases/context-independence/a/c/a.js
- test/statsCases/context-independence/a/cc/b.js
- test/statsCases/context-independence/a/index.js
- test/statsCases/context-independence/b/c/a.js
- test/statsCases/context-independence/b/cc/b.js
- test/statsCases/context-independence/b/index.js
- test/statsCases/context-independence/webpack.config.js
- types.d.ts
- yarn.lock
bugfix
fixes #11335 
yes
no
nothing
> handle several resources in ContextModule

- lib/debug/ProfilingPlugin.js
- test/ProfilingPlugin.test.js
Fixes #15378
`ProfilingPlugin` wasnt passing along the `stage` attribute, which caused tap on the same hook to incorrectly order themselves based on their chosen stage. With fix, we are passing whole old tap info (with replaced function) so that we dont miss any other parameters. `stage` is the only other thing I know of, but I guess it also solves if someone attaches arbitrary data to a hook?
bugfix
yes
no
nothing
> Pass all attributes of old tap with only overidden fn

- lib/WebpackOptionsApply.js
- lib/dependencies/ContextDependencyHelpers.js
- lib/dependencies/ImportContextDependency.js
- lib/dependencies/ImportMetaContextDependency.js
- lib/dependencies/ImportMetaContextDependencyParserPlugin.js
- lib/dependencies/ImportMetaContextPlugin.js
- lib/dependencies/RequireContextPlugin.js
- lib/util/internalSerializables.js
- module.d.ts
- test/cases/chunks/context-weak/index.js
- test/cases/context/import-meta-webpack-context/dir/four.js
- test/cases/context/import-meta-webpack-context/index.js
- test/cases/context/import-meta-webpack-context/two-three.js
- test/cases/context/import-meta-webpack-context/two.js
feature 
closes #15372 
yes
no
`import.meta.webpackContext("directory", { recursive: boolean, regExp: RegExp, mode })` returns same as `require.context` but only for `javascript/auto`, `javascript/esm`
> import.meta.webpackContext

- lib/ContextModule.js
- lib/ContextModuleFactory.js
- lib/cache/ResolverCachePlugin.js
- package.json
- test/ContextModule.unittest.js
- test/ContextModuleFactory.unittest.js
- test/__snapshots__/StatsTestCases.basictest.js.snap
- test/configCases/resolve/context-resolve-with-ignore/a/foo/a.js
- test/configCases/resolve/context-resolve-with-ignore/a/foo/package.json
- test/configCases/resolve/context-resolve-with-ignore/b/foo/b.js
- test/configCases/resolve/context-resolve-with-ignore/b/foo/package.json
- test/configCases/resolve/context-resolve-with-ignore/index.js
- test/configCases/resolve/context-resolve-with-ignore/webpack.config.js
- test/configCases/resolve/empty-context-module/index.js
- test/configCases/resolve/empty-context-module/webpack.config.js
- test/configCases/resolve/issue-11335-context-module/index.js
- test/configCases/resolve/issue-11335-context-module/src/foo/widgets/b.js
- test/configCases/resolve/issue-11335-context-module/src/foo/widgets/c.js
- test/configCases/resolve/issue-11335-context-module/src/main/widgets/a.js
- test/configCases/resolve/issue-11335-context-module/src/main/widgets/b.js
- test/configCases/resolve/issue-11335-context-module/webpack.config.js
- test/statsCases/context-independence/a/c/a.js
- test/statsCases/context-independence/a/cc/b.js
- test/statsCases/context-independence/a/index.js
- test/statsCases/context-independence/b/c/a.js
- test/statsCases/context-independence/b/cc/b.js
- test/statsCases/context-independence/b/index.js
- test/statsCases/context-independence/webpack.config.js
- types.d.ts
- yarn.lock
> Fix resolving with yield

- lib/dependencies/HarmonyImportDependencyParserPlugin.js
- lib/javascript/BasicEvaluatedExpression.js
- lib/javascript/JavascriptParser.js
- test/cases/parsing/optional-chaining/b.js
- test/cases/parsing/optional-chaining/c.js
- test/cases/parsing/optional-chaining/index.js
- types.d.ts
instead of full member expression use only non-optional member expression part
I have added extra argument `membersOptions: boolean[]` to hooks `expressionMemberChain` and `callMemberChain`. it shows which member is optional (Could be used later to fully support optional chaining)
bugfix #12960 
yes
no
nothing
> dont count optional chaining in import specifier

- lib/FileSystemInfo.js
- test/BuildDependencies.longtest.js
feature/bugfix
closes #15574 
yes
no
in esm build dependencies webpack supports only `node:` prefixed Node.js modules (like `node:url`)
> support node: prefix in esm build dependencies

- lib/FileSystemInfo.js
- test/BuildDependencies.longtest.js
> support node.js builtin modules in esm build dependencies

- lib/hmr/HotModuleReplacement.runtime.js
- lib/hmr/JavascriptHotModuleReplacement.runtime.js
- lib/web/JsonpChunkLoadingRuntimeModule.js
- test/hotCases/runtime/import-after-download/index.js
- test/hotCases/runtime/import-after-download/unaffected-chunk.js
- test/hotCases/runtime/import-after-download/unaffected-inner.js
fix egde case where a HMR chunk is incorrectly downloaded when loading a unchanged chunk during HMR downloading
bugfix
yes
no
nothing
> fix egde case where a HMR chunk is incorrectly downloaded 

- lib/Compiler.js
closes #13624 
no need
no
nothing
> catch error in runAsChild callback

- lib/ExportsInfo.js
- test/cases/parsing/harmony-export-import-specifier/index.js
- test/cases/parsing/harmony-export-import-specifier/m.js
- test/cases/parsing/harmony-reexport/a.js
- test/cases/parsing/harmony-reexport/index.js
> fix ExportsInfo

- lib/RuntimePlugin.js
- lib/runtime/NonceRuntimeModule.js
- test/configCases/web/nonce/index.js
- test/configCases/web/nonce/nonce.js
- test/configCases/web/nonce/webpack.config.js
> add NonceRuntimeModule

- lib/NodeStuffPlugin.js
The current warning message can be hard to understand since it's grammatically incorrect.
1. if used with 'does' or 'doesn't' 'present' means to 'make a presentation' (https://www.quora.com/Which-one-is-correct-she-is-not-present-today-or-she-doesnt-present-today). I've changed to 'isnt't available' because 'available' seems a lot more used than 'present' in web development contexts. For example 'present in ES modules' returns only 1 Google search result (in the webpack documentation!) while 'available in ES modules' returns many pages.
2. Except in special cases like names of languages, a singular countable word takes an article. 'browser' is countable (https://dictionary.cambridge.org/dictionary/english/browser)
See for example …
> Fix grammar of warning message

- lib/FileSystemInfo.js
Bug reproduce:
In windows, we got `request = "D:\\c\\d"` when `conetxt = "C:\\a\\b"` and `childPath = "D:\\c\\d"`.
`request` is an absolute path, but it's handled with a relative path.
bugfix.
I not found any unit test for `checkResolveResultsValid` method.
no
None, just a bugfix in a special scene
> Fix error caused by request is an absolute path in Windows

- lib/FileSystemInfo.js
- test/FileSystemInfo.unittest.js
A large monorepo my team works on is seeing an issue where Webpack rebuilds report as finished, but `webpack-dev-server` doesn't respond until a minute later.
Starting with performance changes up front. (See below for a description of what we were seeing.) Here's the `LazySet` [`merge`](https://github.com/webpack/webpack/blob/93ce24d2dc40ee972a2ea5138f3c181563c913fd/lib/util/LazySet.js#L16-L22) performance for `compilation.fileDependencies` in this monorepo before/after:
| |`merge` Loop Iterations|Timing(ms)|
|-|-|-|
|Before|1,198,677|23,045.10|
|After|464,918|1,726.25|
These aren't scientific timings ran over multiple trials. I can perform that if needed.
Running the build in a CPU profiler revealed a large amount of time spent calling watchpack's `watch` function. This is after the …
> Improve watch performance by using stable identities for Snapshot iterables

- lib/index.js
- types.d.ts
This PR adds the ability for plugins to create custom dependencies that play nicely with `ModuleConcatenationPlugin`.
Currently, module concatenation uses `instanceof HarmonyImportDependency ` to check if a dependency is applicable.
because of that, it's preferred to not import `HarmonyImportDependency ` directly and use it from the injected webpack inside the plugin. In this PR I just exported the `HarmonyImportDependency` so it can be used via injection.
Note: 
Usually, dependencies have an effect on the generated code. but when dependencies are used just for information and do not have an effect on output code they could play nice with module `ModuleConcatenationPlugin` without bail out by default.
Another way to solve this is to not use `instanceof` and use some static/public key like …
> feat: export HarmonyImportDependency and generate types

- lib/javascript/JavascriptParser.js
- package.json
- test/cases/parsing/es2022/counter.js
- test/cases/parsing/es2022/es2022.js
- test/cases/parsing/es2022/index.js
- test/cases/parsing/es2022/reexport.js
- test/cases/parsing/es2022/test.filter.js
- yarn.lock
> support es2022

- .github/workflows/test.yml
This PR adds minimum token permissions for the GITHUB_TOKEN using https://github.com/step-security/secure-workflows.
GitHub recommends defining minimum GITHUB_TOKEN permissions for securing GitHub Actions workflows 
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/  
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
- The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) treats not setting token permissions as a high-risk issue 
This project is part of the top 100 critical projects as per OpenSSF (https://github.com/ossf/wg-securing-critical-projects), so fixing the token permissions to improve security.
Signed-off-by: Varun …
> ci: add GitHub token permissions for workflow

- lib/container/ModuleFederationPlugin.js
It looks to me like setting `shareScope` for `ModuleFederationPlugin` doesn't work without this change, because `ContainerPlugin` still tries to use `default`.
bugfix
No, but I didn't see any other tests for `ModuleFederationPlugin` either.
I don't think so.
I believe this change makes it more closely match existing documentation.
> Pass shareScope through to ContainerPlugin & ContainerReferencePlugin

- README.md
In README.md are added `pug-plugin` and modern powerful `pug-loader`.
This plugin enable to define Pug files in Webpack entry, extracts JS and CSS from sources specified directly in Pug:
```js
const PugPlugin = require('pug-plugin');
entry: {
index: './src/views/index.pug',      // output index.html
about: './src/views/about/index.pug' // output about.html
// ..
},
plugins: [
new PugPlugin(/* options */), // enable using Pug files in webpack entry
],
};
```
All source scripts and styles can be required in Pug, e.g.:
```pug
link(href=require('./styles.scss') rel='stylesheet')
script(src=require('./main.js'))
```
Generated HTML contains hashed CSS and JS output filenames:
```html
<link href="/assets/css/styles.05e4dd86.css" rel="stylesheet">
<script …
```
> docs: update in readme the list of plugins and loaders

- lib/dependencies/ProvidedDependency.js
- test/configCases/plugins/provide-plugin/a.js
- test/configCases/plugins/provide-plugin/b.js
- test/configCases/plugins/provide-plugin/harmony2.js
- test/configCases/plugins/provide-plugin/index.js
- test/configCases/plugins/provide-plugin/webpack.config.js
feature
closes #12441 
yes
no
nothing
> add tree-shaking to ProvidedDependency

- lib/NodeStuffPlugin.js
Improve the warning messages that were not fixed in https://github.com/webpack/webpack/commit/96c57bd9ff03665e3ba857c00f7f27039d24b8a6
UI change.
No, because the change affects the the contents of a message string.
No.
No need for documentation.
> chore: improve warning message grammar

- README.md
The `david-dm.org` website is down for 3 months, and the project `alanshaw/david` is not actively maintained anymore. `david-dm.org` should be considered dead, thus badges should be removed from README.
README updates.
New test cases are not required.
No.
N/A.
> docs: remove david-dm from README

- lib/index.js
- types.d.ts
After fighting for a long time with webpack to get it to generate WASM loading code that would work with `vscode` web extensions (see https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-main-file for why this is non-trivial), I understood that I will need to change the `webpack` WASM loading code. I even found [documentation](https://webpack.js.org/configuration/output/#outputwasmloading) saying it's possible. When I tried, I got an error message saying I just need to call `EnableWasmLoadingPlugin.setEnabled()`, which was very encouraging, however, I couldn't find a way to do that, so I had to patch `webpack` to export it.
Here is the plugin I wrote, in case anyone googles how to do the same:
https://github.com/SonOfLilit/vscode-web-wasm-rust
**What kind of …
> export EnableWasmLoadingPlugin to enable writing of wasm loading plugins, as documented

- lib/Compilation.js
- test/__snapshots__/StatsTestCases.basictest.js.snap
fixed sometimes log will be NaN%
no 
no
no
> fix: when the jobs parameter is an empty array, block unnecessary runCodeGenerationJobs

- hot/dev-server.js
This fixes an error message that I got while using HMR in webpack-dev-server with `target: "webworker"`. The error message can be reproduced with the example linked in [this comment](https://github.com/webpack/webpack/issues/14722#issuecomment-1134888597). @alexander-akait suggested to make a PR with a fix.
This PR just checks `typeof window` before calling `window.location.reload()` and changes the warning messages slightly when the page cannot be reloaded by webpack.
bugfix.
I tried to, but then I realized that the file `/hot/dev-server.js` is not tested anywhere, yet. Setting up a test scenario from scratch seems like a very hard thing to do :wink:.
I tested this manually with the example above to …
> Fix "window is not defined" when using HMR on worker

- lib/WebpackOptionsApply.js
- test/configCases/css/external-in-node/index.js
- test/configCases/css/external-in-node/webpack.config.js
**Issue:**
When using the CSS experiments and using @import in CSS code, the compilation fails with these error messages: 
```sh
Module build failed: UnhandledSchemeError: Reading from "http://example.com/image.png" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "http:" URIs.
```
**Changes:**
This PR will handle the @import rules for node and add a dedicated test.
**CSS example code:**
```css
@import "https://test.cases/path/../../../../configCases/css/external/external.css";
```
> fix(css): add node support for external @import

- lib/ids/IdHelpers.js
…ance
performance
No need
No.
No.
The old code about assignDeterministicIds fill rate is:
```js
Math.ceil(items.length * 1.25)
```
but in this [PR](https://github.com/webpack/webpack/pull/9849), it changed to
```js
Math.ceil(items.length * 20)
```
Because `items` is an array, and its length will never be a decimal. So it's not necessary to add `Math.ceil` now.
I removed `Math.ceil` to improve the performance.
And this change will not cause any Breaking Change, I ran all tests.
> perf: remove assignDeterministic verbose Math.ceil code to improve performance

- lib/optimize/RealContentHashPlugin.js
Hello,
We're working on a relatively big app:
~ 2M LOC
~ 10k assets
~ 10k hashes to compute
`RealContentHashPlugin` was taking substantial time to seal the compilation. After profiling the code, I've found that `createHash` was adding most of the time to the processing.
I wasn't able to reproduce it in synthetic tests. My current assumption is that high memory pressure and GC are involved. I can investigate it later but would like the fix to be checked in.
We use `webpack-subresource-integrity` plugin, half of the hashes come form it and are recalculated through the hook. Since `hash` is only needed when there wasn't one generated by an external plugin, it's safe to move its creation into the same conditional block, where it's used. 
This minor change improved `RealContentHashPlugin` …
> Initialize hash conditionally

- lib/optimize/RealContentHashPlugin.js
Fixes #16758
For applications with a very large number of assets, the cost of invoking a single regular expression with many many values in a group becomes very high.
By changing to a list of regular expressions (with helper methods for maintaining the original design) we can get a large performance improvement.
A simple way to view the performance difference between these two approaches is with the following short scripts:
```js
// benchmark-regex-group.js
const crypto = require('node:crypto');
function makeRandomString(length) {
return crypto.randomBytes(length).toString('hex');
}
const name = makeRandomString(40);
const keys = Array.from(Array(3000), () => makeRandomString(20));
const regex = new RegExp(keys.join("|"), "g");
name.replace(regex, found => 'replaced');
```
```js
const …
```
> Improve performance of hashRegExp lookup

- declarations/LoaderContext.d.ts
- types.d.ts
The `LoaderContext` type does not contain a `target` property, but [the documentation](https://webpack.js.org/api/loaders/#thistarget) mentions it on the loader context.
See #16753 for more information. Fixes #16753.
Adds a missing `target` property to the `LoaderContext` type.
Not exactly sure whether tests are needed for a tiny type change like this, also wouldn't really know where to begin to add a test for something like this, though I'm happy to add some if requested.
No.
N/A. Documentation for `target` on the `LoaderContext` [already exists](https://webpack.js.org/api/loaders/#thistarget).
> feat: Add `target` to `LoaderContext` type

- lib/optimize/RealContentHashPlugin.js
- test/configCases/contenthash/salt/index.js
- test/configCases/contenthash/salt/test.config.js
- test/configCases/contenthash/salt/webpack.config.js
Update `RealContentHashPlugin` to initialize hash instances with the value of `output.hashSalt`, if provided. This allows developers to use the `output.hashSalt` property to force all emitted webpack assets to have new hashes, even though the content has not changed, for example to deliberately cache break a CDN.
Note that if the `optimization.realContentHash` property was set to `false`, the value of `[contenthash]` already included `output.hashSalt` in the calculation.
Fix #16788
Yes. Changes verify that running three configs with identical source files and two different values of `output.hashSalt` produce exactly 2 unique output hashes.
This could be …
> Respect output.hashSalt in RealContentHashPlugin

- lib/optimize/RealContentHashPlugin.js
Reverts webpack/webpack#16759
Discussion here: https://github.com/webpack/webpack/pull/16759#issuecomment-1463933903
Performance benchmarks showing the improvement were calculated on an M1 Macbook Pro, subsequent performance benchmarks performed on more powerful machines running an Intel architecture show a substantial regression from these changes. I'd suggest that we revert this feature and cut a patch release.
> Revert "Improve performance of hashRegExp lookup"

- lib/runtime/LoadScriptRuntimeModule.js
- test/__snapshots__/StatsTestCases.basictest.js.snap
Remove redundant semicolons after onScriptComplete function  related to https://github.com/webpack/webpack/issues/16346
no
no
no
> Remove redundant semicolons after onScriptComplete function close: #16346

- lib/SourceMapDevToolPlugin.js
Hoists Regular Expression Literals into variables and gives them descriptive (?) names. 
Refactoring
No
Nothing documented, however I would like a review on the names of the variables themselves so they can be as descriptive as possible.
Fixes #15720
> hoist regexp literals in SourceMapDerToolPlugin

- lib/runtime/AutoPublicPathRuntimeModule.js
- test/__snapshots__/StatsTestCases.basictest.js.snap
Fixes https://github.com/webpack/webpack/pull/15003
Updated snapshots.
No
Nothing
> fix: add missing semicolon in `AutoPublicPathRuntimeModule`

- lib/ModuleGraph.js
Fixes https://github.com/webpack/webpack/issues/16829
No
No.
Nothing.
> fix: initialize `this._cacheStage` in ModuleGraph constructor

- lib/node/nodeConsole.js
- test/ProgressPlugin.test.js
Fixes https://github.com/webpack/webpack/pull/9815
> See the comment here: https://github.com/webpack/webpack/pull/9225#issuecomment-536501366
>
>There are several cases where process.stderr.columns could be undefined. Like, in the Vue CLI UI console, or in a CI log page. But that doesn't mean there's infinity room to display the lines. In these cases, we should fall back to the old behavior of the 40 max length.
yes
no
nothing
> fix: limit progress bar length to 40 when no columns provided

- lib/NormalModuleFactory.js
Improves error message.
Fixes https://github.com/webpack/webpack/issues/11695
New error message:
~~`<img width="881" alt="Screenshot 2023-03-11 at 11 03 19 AM" src="https://user-images.githubusercontent.com/46647141/224466954-2547715e-87cf-4183-9ab0-8d5587a8cbbe.png">`~~
Yes.
No.
Nothing.
> fix: improve error message if `resolve.extensions` is invalid

- lib/ErrorHelpers.js
Refactors Error helpers in a few ways
* Removes variable shadowing in replacement of easier type safety with comments
* Improve readability of function by renaming variables
* Add JSDoc comments and descriptions for each function
* Drop module exports to bottom of file in one location for ease of readability
> refactor(ErrorHelpers): Make error helpers named functions; add types

- lib/DefinePlugin.js
- lib/ModuleTypeConstants.js
- lib/json/JsonModulesPlugin.js
This PR introduces a new abstraction to the usages of module types passed to parser hooks. 
Currently today we are wasting a lot of memory using hundreds/thousands of the same string literals which can add up overtime. Also in the codebase there is no proper documentation for what each module type strings actually represent. 
This abstraction (and implementation in the DefinePlugin and JSONModulesPlugin) aim to improve understanding of these module types, provide improved type safety, and reduces overusage of memory for string literals. 
This PR also does the following: 
* Abstract plugin name in DefinePlugin and JSONModulesPlugin
* Abstract module types usages 
* hoists any RegExp literals and gives them somewhat useful names.
> refactor(moduletypes): introduce module type constants for plugins

- lib/FlagAllModulesAsUsedPlugin.js
- lib/FlagDependencyExportsPlugin.js
- lib/FlagDependencyUsagePlugin.js
- lib/FlagEntryExportAsUsedPlugin.js
This PR reduces the memory footprint of multiple small plugins by hoisting string literals (plugin name) which are reused multiple times. 
This enhances readability, in addition to reducing errors when updating plugin names, and _very slightly_ reduces memory footprint of the plugin (applied to all plugins, can be more impactful).
> refactor(plugins): reduce memory footprint in string usages for multiple plugins

- examples/css/README.md
- examples/css/style.module.css
- lib/css/CssParser.js
- test/configCases/css/css-modules-in-node/index.js
- test/configCases/css/css-modules/index.js
- test/configCases/css/css-modules/style.module.css
- test/configCases/css/css-modules/use-style.js
- test/configCases/css/large/index.js
**Issue:** 
When using the CSS `experiments` and using `@media` or `@supports` in CSS code, the nested class names are not replaced with their unique identifier.
**Changes:** 
This PR will handle `@media` and `@supports` atRule identifiers and enable the replacements of the nested rules names with the unique ids.
**CSS input code:**
```css
.main {
font-size: var(--large);
color: darkblue;
}
@media (min-width: 1024px) {
.main {
color: green;
}
}
@supports (display: grid) {
.main {
display: grid
}
}
```
**The compiled CSS code with the issue:**
You can see that **only** the top-level class name is replaced.
```css
.app-491-D {
font-size: var(--large);
color: darkblue;
}
@media (min-width: 1024px) {
.main {
color: green;
}
}
@supports (display: grid) {
.main {
display: grid
}
}
```
**The …
> fix(css parser): handle nested atRule

- test/configCases/plugins/banner-plugin/index.js
- test/configCases/plugins/banner-plugin/webpack.config.js
> Test: Add test for include option in banner plugin

- lib/ids/OccurrenceModuleIdsPlugin.js
- test/configCases/contenthash/module-ids-size/async.js
- test/configCases/contenthash/module-ids-size/file-1.js
- test/configCases/contenthash/module-ids-size/file-2.js
- test/configCases/contenthash/module-ids-size/file-3.js
- test/configCases/contenthash/module-ids-size/file.js
- test/configCases/contenthash/module-ids-size/index.js
- test/configCases/contenthash/module-ids-size/test.config.js
- test/configCases/contenthash/module-ids-size/webpack.config.js
Refactor occurrence order module ids algorithm (used when `moduleIds: "size"`) and fix a possible `NaN` bug in `OccurrenceModuleIdsPlugin.js`.
See discussion https://github.com/webpack/webpack/discussions/16899 for more details.
The module sort was encountering NaN values, causing the sort to be non-deterministic, resulting in a different moduleId assignment being used in each build run when moduleIds: "size" is configured.  This causes the build to be slightly different in size each time it's run.
Fix is to ensure that a number is always used when constructing a sum value.  If a module is not found in the initial chunk map, use a `0` instead of `undefined`.
> Fix non-deterministic moduleId assignment

- lib/config/defaults.js
There's no need to compute `﻿Template.toIdentifier(output.uniqueName)` twice or execute it for `﻿${webpackHotUpdate}${result}` and `﻿${webpackChunk}${result}`.
> minimize redundant `Template.toIdentifier` calls

- lib/Compilation.js
- lib/DependencyTemplate.js
- lib/Generator.js
- lib/Module.js
- lib/NormalModule.js
- lib/dependencies/PureExpressionDependency.js
- lib/javascript/JavascriptGenerator.js
- lib/util/runtime.js
- types.d.ts
bugfix
Not easy to reproduce,  TODO
no
no
> fix: fix pureDep returns null in some js files

- lib/ExternalModule.js
Some hard code arrow function in generateModuleRemapping and getSourceForModuleExternal
use helper functions to replace arrow functions 
fixes https://github.com/webpack/webpack/issues/17861
> fix: external module hard code arrow function

- lib/EnvironmentNotSupportAsyncWarning.js
- lib/ExternalModule.js
- lib/config/target.js
- lib/dependencies/HarmonyDetectionParserPlugin.js
- lib/wasm-async/AsyncWebAssemblyParser.js
- test/configCases/async-module/environment-not-support-async-warning/index.js
- test/configCases/async-module/environment-not-support-async-warning/reexport.js
- test/configCases/async-module/environment-not-support-async-warning/warnings.js
- test/configCases/async-module/environment-not-support-async-warning/webpack.config.js
related to #17958, also add the warning for async external (`external import`, `external module`, `external promise`, `external script`)
Add EnvironmentNotSupportAsync warning for async external (`external import`, `external module`, `external promise`, `external script`)
update `configCases/async-module/environment-not-support-async-warning`
no
none
> fix: add warning for async external

- lib/javascript/JavascriptParser.js
- types.d.ts
Performance optimization. Reuses a single VM context for evaluating all webpack magic comments, instead of a fresh context for each comment.
Reduces time spent in the magic comment parser by ~75% while still maintaining the same degree of sandboxing from the main process.
Feature already covered by several test cases.
No.
No documentation changes.
> Reuse VM context across webpack magic comments

- lib/util/numberHash.js
- test/Compiler.test.js
- test/Errors.test.js
- test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
- test/__snapshots__/ConfigTestCases.basictest.js.snap
- test/__snapshots__/StatsTestCases.basictest.js.snap
- test/configCases/asset-emitted/normal/webpack.config.js
- test/configCases/code-generation/re-export-namespace-concat/index.js
- test/configCases/code-generation/re-export-namespace/index.js
- test/configCases/css/css-modules-broken-keyframes/index.js
- test/configCases/css/css-modules/index.js
- test/configCases/css/css-modules/test.config.js
- test/configCases/css/large/index.js
- test/configCases/custom-source-type/localization/index.js
- test/configCases/mangle/mangle-with-object-prop/index.js
This is a bugfix for a couple issues with #18034:
- The implementation there suffered from loss of precision in the hash multiplication if the current value of the hash exceeded 536858016, since the product would then exceed `Number.MAX_SAFE_INTEGER`. This loss of precision is addressed by switching to the `Math.imul` function, which explicitly performs 32-bit integer multiplication and returns the 32 least significant bits.
- A modification of the reference algorithm to always operate on 8-bit input units introduced the likelihood of collisions between strings with two ASCII characters vs. a single higher Unicode code point. This modification was reverted to simply take the 16-bit Unicode character as a single input value.
 
**Did you add …
> fix: use Math.imul in fnv1a32 to avoid loss of precision, directly hash UTF16 values

- lib/dependencies/ExportsInfoDependency.js
- test/configCases/mangle/exports-info-can-mangle/a.js
- test/configCases/mangle/exports-info-can-mangle/b.js
- test/configCases/mangle/exports-info-can-mangle/index.js
- test/configCases/mangle/exports-info-can-mangle/webpack.config.js
fix canMangle on __webpack_exports_info__
before `exportName` is always an Array, so `exportsInfo.getExportInfo(exportName)` will always create a new export info, instead of getting the exist export info
added
no
none
> fix: __webpack_exports_info__.xxx.canMangle shouldn't always same as default

- lib/buildChunkGraph.js
- test/__snapshots__/StatsTestCases.basictest.js.snap
- test/configCases/chunk-graph/issue-17989/entry-a.js
- test/configCases/chunk-graph/issue-17989/entry-b.js
- test/configCases/chunk-graph/issue-17989/shared.js
- test/configCases/chunk-graph/issue-17989/test.config.js
- test/configCases/chunk-graph/issue-17989/util.js
- test/configCases/chunk-graph/issue-17989/util1.js
- test/configCases/chunk-graph/issue-17989/util2.js
- test/configCases/chunk-graph/issue-17989/webpack.config.js
fix #17989
In the issue reproduce, the chunk graph is:
notice the `Button + helper` chunk group, when it is created, its runtime is only `"main"`, and the activeState (in main runtime) of util is `false`, so util is not included in this chunk
with `remote -> App -> Button`, the runtime of `Button + helper` chunk group become `"remote" + "main"`, and the activeState (in remote runtime) of util is `true` (because `remote -> helper -> util`)
but when `processOutdatedChunkGroupInfo`, webpack still using the outdated activeState (main runtime), instead of the latest activeState (remote + main runtime), which causes the util not included in the `Button + helper` chunk
use the latest runtime to calculate the activeState of the outdated skipped …
> fix: should use new runtime to reconsider skipped connections activeState

- lib/dependencies/HarmonyImportSpecifierDependency.js
- test/configCases/mangle/mangle-with-destructuring-assignment/index.js
- test/configCases/mangle/mangle-with-destructuring-assignment/module2.js
- test/configCases/mangle/mangle-with-destructuring-assignment/module3.js
- test/configCases/mangle/mangle-with-destructuring-assignment/reexport.js
- test/configCases/mangle/mangle-with-destructuring-assignment/reexport2.js
- test/configCases/mangle/mangle-with-destructuring-assignment/webpack.config.js
fix #18091
should not mangle the export name when export is an reexport
```js
// module1.js
export * as module2 from "./module2"
// index.js
import { module2 } from "./module1"
const { a } = module2
```
since `const { a } = m2` is not destructing module1, it's destructing module1's property, so before the canMangle is set to true, but in this case, m2 is a reexport of module2, even though module2 is module1's property, but module2 is still a module, so it can't be mangled
This PR disable mangle reexport
added
no
none
> fix: should not mangle when destructuring a reexport

- lib/DefinePlugin.js
> chore: replace remaining RuntimeGlobals references

- lib/ExportsInfo.js
Remove duplicate assign to _otherExportsInfo.canMangleUse, as `this._otherExportsInfo.setHasUseInfo()` already assign `canMangle` https://github.com/webpack/webpack/blob/c39a24c34f3dbb9fc2b7e445bac6bb0a45b261a2/lib/ExportsInfo.js#L957
no
no
Not applied
> Remove duplicate assign to _otherExportsInfo.canMangleUse

- lib/dependencies/CommonJsImportsParserPlugin.js
This is merely a minor lint: it's unnecessary to maintain redundant return values.
> cleanup unnecessary return

- lib/LibManifestPlugin.js
- test/configCases/dll-plugin/5-issue-18200/a.js
- test/configCases/dll-plugin/5-issue-18200/b.js
- test/configCases/dll-plugin/5-issue-18200/errors.js
- test/configCases/dll-plugin/5-issue-18200/webpack.config.js
Output error information in specific dll-plugin usage scenarios. related to #18200.
Not yet, If necessary, I will add test cases after getting familiar with the test code.
No
I will send another PR to document repo later.
> chore: throw error when dll-plugin needs to generate multiple manifest files but the path config is incorrect.

- lib/config/defaults.js
- test/configCases/output/chunk-format-with-runtimeChunk/index.js
- test/configCases/output/chunk-format-with-runtimeChunk/test.config.js
- test/configCases/output/chunk-format-with-runtimeChunk/webpack.config.js
Set default value of `chunkLoading` to `import`(ESM) that fix runtimeChunk has no exports which causes syntaxError when setting `runtimeChunk` and `chunkFormat: module`
webpack.config.js
```javascript
// ...
target: "node",
optimization: {
runtimeChunk: "single",
minimize: false
},
output: {
module: true,
chunkFormat: 'module',
},
experiments: {
outputModule: true,
}
}
````
output:
- main.mjs
```javascript
// ...
// load runtime
import __webpack_require__ from "./runtime.mjs";
var __webpack_exec__ = (moduleId) => (__webpack_require__(__webpack_require__.s = moduleId))
import * as __webpack_chunk_0__ from "./main.mjs";
__webpack_require__.C(__webpack_chunk_0__);
var __webpack_exports__ = __webpack_exec__(463);
```
- …
> fix: SyntaxError when setting runtimeChunk and module chunkFormat

- lib/index.js
- types.d.ts
Simply adds the `InitFragment` class to exports so that plugins can utilize it for creating custom dependencies.  See discussion in #18230.
Refactor
n/a
No
n/a
> Export InitFragment class for plugins

- lib/dependencies/ExportsInfoDependency.js
- test/configCases/mangle/exports-info-can-mangle/c.js
- test/configCases/mangle/exports-info-can-mangle/index.js
This PR fixes a gap in #18060 , which only handled the case of a single level of property access in `__webpack_exports_info__.a.canMangle` and would ignore any subsequent properties, i.e. `__webpack_exports_info__.a.b.canMangle` would return the same value as the former, regardless of the ability to mangle the nested property `b`.
bugfix
Yes, added a unit test to verify that `__webpack_exports_info__.a.canMangle` and `__webpack_exports_info__.a.b.canMangle` return different results if `a` cannot be mangled but `b` can.
No.
This makes the `__webpack_exports_info__.a.b...c.canMangle` property act …
> (fix) Correct behavior of __webpack_exports_info__.a.b.canMangle

- lib/css/CssParser.js
- test/configCases/css/default-exports-parser-options/index.js
- test/configCases/css/default-exports-parser-options/style.module.css
- test/configCases/css/default-exports-parser-options/webpack.config.js
- test/configCases/css/named-exports-parser-options/index.js
feature - allow to use default and named export
The same as requested here - https://github.com/webpack-contrib/mini-css-extract-plugin/pull/1084
/cc @ahabhgk What do you think about it?
The main idea - allow to easy migrate from default to named, by default it is disabled (because we use only named export), but if developers have a lot of code, it is not easy to migrate fast, so developer can disable named export and use both of them
Yes
No
When named export is disabled for CSS modules you can get classes using (we redirect named export for better DX, it will allow to migrate from default export …
> feat(css): allow to use default and named export

- test/configCases/inner-graph/pr-18342/common/index.js
- test/configCases/inner-graph/pr-18342/common/pure.js
- test/configCases/inner-graph/pr-18342/entry1/index.js
- test/configCases/inner-graph/pr-18342/entry2/index.js
- test/configCases/inner-graph/pr-18342/entry3/a.js
- test/configCases/inner-graph/pr-18342/entry3/index.js
- test/configCases/inner-graph/pr-18342/test.config.js
- test/configCases/inner-graph/pr-18342/webpack.config.js
Add test case to [pr-16701](https://github.com/webpack/webpack/pull/16701)
Yes
No
No
> test: add test case to pr-16701

- lib/ExternalModule.js
For `ExternalModule`, render `init` code only when needing `moduleRemapping`, which will reduce useless code. Although the `init` code could be removed when minimizing, but this will help in some scenario, for example, we are using webpack to building bundleless package without running minimizing, this will help.
No, the test code is not minimized, they should sufficient so far. Feel free to let me what kind of case should be added. :)
No.
No.
> fix: only render init code when need moduleRemapping

- lib/css/CssParser.js
- test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
- test/__snapshots__/ConfigTestCases.basictest.js.snap
- test/configCases/css/css-import/style10.css
- test/configCases/css/css-import/style13.css
fix case `@import "./style.css";body{}`
before:
```css
.class-in-style-css{};
ody{}
```
after:
```css
.class-in-style-css{};
body{}
```
there are some new lines introduced in the snapshot, because before the new line is removed unexpectedly:
before:
```css
@import "./style.css";\n\nbody{}
//                      second \n: the removed new line
//                    first \n: end + 1
```
after:
```css
@import "./style.css";\n\nbody{}
//                      second \n: keep it as is
//                    first \n: the removed new line
```
bugfix
added
no
none
> fix: parse minimized css import

- .github/workflows/test.yml
fix the integration CI fails on node 10.x running on `macos-latest` lately.
some context:
- `macos-latest` now runs on ARM chips https://github.com/actions/runner-images/issues/9741#issuecomment-2075259811.
- no ARM version for node 10.x is [available](https://github.com/actions/node-versions/releases/tag/10.24.1-725060485), also see https://github.com/actions/setup-node/issues/1017#issuecomment-2077362713.
so this PR specify architecture for node 10.x on ARM64 macos-latest as a workaround.
> ci: use x64 arch node 10.x for macos-latest

- lib/config/defaults.js
- test/Defaults.unittest.js
- test/configCases/resolve-merging/imports-fields/index.js
- test/configCases/resolve-merging/imports-fields/node_modules/lib/index.js
- test/configCases/resolve-merging/imports-fields/node_modules/lib/lib.mjs
- test/configCases/resolve-merging/imports-fields/node_modules/lib/package.json
- test/configCases/resolve-merging/imports-fields/package.json
- test/configCases/resolve-merging/imports-fields/pkg.mjs
- test/configCases/resolve-merging/imports-fields/webpack.config.js
feat or fix, before using `importsFields: ["custom", "..."]` won't work, since there isn't a default value for importsFields
added
No
mention supports `"..."` in resolve importsFields (if needed)
> feat: support `"..."` in resolve importsFields

- lib/util/runtime.js
fixes `subtractRuntime` returns `undefined` when params `a` is `Set<runtime~a, runtime~b,runtime~c>` and params `b` is `runtime~a` but it is expected to return `Set<runtime~b,runtime~c>`
No
No
No
> fix: add return value to `subtractRuntime` fn

- lib/Compilation.js
- lib/DependencyTemplate.js
- lib/Generator.js
- lib/Module.js
- lib/NormalModule.js
- lib/dependencies/PureExpressionDependency.js
- lib/javascript/JavascriptGenerator.js
- lib/util/runtime.js
- test/__snapshots__/StatsTestCases.basictest.js.snap
- types.d.ts
This should be a more reasonable fix compared to #16701 
`runtimes` means: in these `runtimes`, the code generation result should be the same as `runtime`, if the chunk graph module's hash are the same, the `runtime` will added to `runtimes`
https://github.com/webpack/webpack/blob/400db90db807d630b6c9f5e7ccde2b8f01690f3b/lib/Compilation.js#L3298-L3306
For example, the test case added in #18343:
The `codeGenerationJobs` generated for `module(pure.js)` should be:
```js
[
{
module: "pure.js",
runtime: [runtime~entry1],
runtimes: [[runtime~entry1]]
},
{
module: "pure.js",
runtime: [runtime~entry2, runtime~entry3],
runtimes: [[runtime~entry2, runtime~entry3]]
},
]
```
instead of:
```js
[
{
module: "pure.js",
runtime: [runtime~entry2, …
```
> fix: consider runtime for pure expression dependency update hash

- lib/index.js
- types.d.ts
feature, need it for runtime modules - https://github.com/webpack-contrib/mini-css-extract-plugin/pull/1043/
No
No
No
> feat: export `compileBooleanMatcher` util

- lib/sharing/ConsumeSharedModule.js
- lib/sharing/ConsumeSharedRuntimeModule.js
- test/configCases/container/0-eager-shared/App.js
- test/configCases/container/0-eager-shared/emitter.js
- test/configCases/container/0-eager-shared/index.js
- test/configCases/container/0-eager-shared/node_modules/tiny-emitter/index.js
- test/configCases/container/0-eager-shared/node_modules/tiny-emitter/package.json
- test/configCases/container/0-eager-shared/package.json
- test/configCases/container/0-eager-shared/webpack.config.js
- test/configCases/container/eager-shared/index.js
- test/configCases/container/eager-shared/node_modules/tiny-emitter/index.js
- test/configCases/container/eager-shared/node_modules/tiny-emitter/package.json
- test/configCases/container/eager-shared/package.json
- test/configCases/container/eager-shared/webpack.config.js
Fixes eager consumption of shared dependencies. Full description is in this discussion: https://github.com/webpack/webpack/discussions/18001#discussioncomment-8381548
No, the reason for no tests attached can be found in the discussion link above. cc @alexander-akait 
No, as far as I understand how webpack container works.
This is yet to be defined, this PR is needed as a starting point.
> fix: Consumption of eager shared modules

- lib/ContextModule.js
- test/cases/context/issue-10969/index.js
fix pretty regexp when stripSlash is true
for example: `_prettyRegExp(/\.js$/ig)` should be `\\.js$ig` instead of `\\.js$/i`
Updated
No
None
> fix: strip slash for pretty regexp

- lib/javascript/ArrayPushCallbackChunkFormatPlugin.js
- lib/javascript/JavascriptModulesPlugin.js
- lib/library/AssignLibraryPlugin.js
- lib/library/EnableLibraryPlugin.js
- lib/library/ExportPropertyLibraryPlugin.js
- lib/optimize/ConcatenatedModule.js
- lib/prefetch/ChunkPrefetchPreloadPlugin.js
- test/__snapshots__/StatsTestCases.basictest.js.snap
- test/configCases/library/1-use-library/webpack.config.js
The initial goal of this PR is to reduce unnecessary runtime code in `modern-module`. As `__webpack_exports__` and related define property runtime is not needed.
Contains following changes:
1. Explicit define `RuntimeGlobals.exports` instead of using the always pre-rendered  `__webpack_exports__` in source, only render it when runtime requirements exist.
- where `RuntimeGlobals.onChunksLoaded` is added, also adding `RuntimeGlobals.exports`
- Add `RuntimeGlobals.exports` to `lib/library/AssignLibraryPlugin.js` and `lib/library/ExportPropertyLibraryPlugin.js` to inherit the explicit defined `RuntimeGlobals.exports` runtime.
2. Do not render `RuntimeGlobals.exports` &  `RuntimeGlobals.definePropertyGetters` in modern-module mode.
**Did you add …
> feat: reduce unnecessary exports runtime

- lib/ChunkGraph.js
- lib/CodeGenerationResults.js
This updates the `webpack` build to be forwards compatible with microsoft/TypeScript#58243, which uses a stricter return type for built-in iterators under the new `strictBuiltinIteratorReturn` option, which is enabled by default when building with `strict`.
Tests should not be necessary for this change.
No
Nothing, this is purely related to TypeScript type checking of the `webpack` project itself.
> Support strictBuiltinIteratorReturn

- lib/ExternalModule.js
- lib/ExternalModuleFactoryPlugin.js
- lib/ExternalsPlugin.js
- test/configCases/externals/module-import-externals-presets/index.js
- test/configCases/externals/module-import-externals-presets/test.filter.js
- test/configCases/externals/module-import-externals-presets/webpack.config.js
- types.d.ts
Adding fallback external type for `"module-import"` type when `"module"` and `"import"` are neither applicable.
In https://github.com/webpack/webpack/pull/18620, implement "module-import", but the premise is that we're using `import` or `import()` for external request, However, for example, if we use `require('...')`, "module-import" will failed to know which externals type to adopt ("import", "module", or even "node-commonjs"), and it will crash.
The possible options we may want to fall back to:
1. `node-commonjs`: to let `require('path')` code could run in Node.js + ESM (this is widely used).
2. `import`: possibly for some specific reason.
3. `module`: possibly for some specific reason.
4. `commonjs`: level the `require` there, to be …
> fix: module-import get fallback from externalsPresets

- lib/dependencies/HarmonyImportSpecifierDependency.js
- test/configCases/mangle/mangle-with-re-export-as-default/index.js
- test/configCases/mangle/mangle-with-re-export-as-default/module.js
- test/configCases/mangle/mangle-with-re-export-as-default/re-exports.js
- test/configCases/mangle/mangle-with-re-export-as-default/webpack.config.js
Webpack introduces mangle exports in destruction in #18319, there is an edge case can break user code
```js
// index.js
import foo from './re-exports'
const { value } = foo;
```
```js
// re-exports.js
import * as foo from './re-exports'
export { foo as default }
```
`const { value } = foo` can become invalid after mangle.
For more details you can see tests in this pr.
The reason is JSON module has no exportInfo with 'default', for example:
```json{ "foo": 1 }```
If I import json above, I get a JSON module with exportsInfo `{ "foo": ExportInfo }`, there is no ExportInfo for 'default', but user import json using default import, how does this be ?
Turns out there is a special case in `HarmonyImportSpecifierDependency` that will remove the …
> fix: mangle destruction incorrect with export named default

- lib/dependencies/URLPlugin.js
- test/ConfigTestCases.template.js
- test/configCases/parsing/url-ignore/file2.css
- test/configCases/parsing/url-ignore/file4.css
- test/configCases/parsing/url-ignore/index.js
- test/configCases/parsing/url-ignore/warnings.js
- test/configCases/parsing/url-ignore/webpack.config.js
Feature:
```js
new URL(/* webpackIgnore: true */ "file1.css", import.meta.url)
```
Because we support `import(/* webpackIgnore: true */ "./file.css");` we need support for this in `new URL()` too, otherwise it is imposible to migrate on `new URL` from `import(...);` (what we actually recommend). 
Also `import.meta.url` is not keeping as is, it will be replaced on `baseURI` in such case (for modules it is `new URL("./", import.meta.url)`, for other cases it is `document.baseURI`), so relative URLs will work correctly.
Yes
No
Need improve our docs about this feature
> feat: support `webpackIgnore` for `new URL()` construction

- lib/buildChunkGraph.js
- test/cases/chunks/runtime/webpack.config.js
Improve performance of code-splitting
see following module-graph
if module `other` has a lots of sub modules, we can avoid revisit those modules if minAvailableModules stays the same
module a dyn imports module b, buildChunkGraph will first create chunk a for module a, fills chunk a, then create chunk b for module b, fills chunk b.
if module b has another parent, then chunk b will be outdated and will be visited again, and **fills chunk b again**. But if chunk b has no minAvailableModules changes, we can skip visiting it, as it won't have any differences
No
No
> perf(buildChunkGraph): avoid unneeded re-visit

- lib/EnvironmentPlugin.js
- types.d.ts
Changes introduced in https://github.com/webpack/webpack/commit/adf2a6b7c6077fd806ea0e378c1450cccecc9ed0#diff-a150fb53afee945f23f3fe7c176007111f3ba81bb0d188af4077d4a0fc4caa37R3993 prevents updating webpack to 5.94.0 in some cases because previously EnvironmentPlugin/defaultValues could be initiated with any types (as it is being also documented), but now with types update it could only be `Record<string, string>`.
There are checks in code that stringify value & explicitly check if `undefined` was a value, so it might make sense to keep this as `Record<string, any>`: https://github.com/webpack/webpack/blob/94aba382eccf3de1004d235045d4462918dfdbb7/lib/EnvironmentPlugin.js#L40-L59 (which is also a documented behavior in https://webpack.js.org/plugins/environment-plugin/)
Closes #18719
**What …
> fix: make EnvironmentPlugin defaultValues types less strict

- lib/optimize/ConcatenatedModule.js
- test/configCases/scope-hoisting/issue-11897/index.js
- test/configCases/scope-hoisting/issue-11897/module2.js
- test/configCases/scope-hoisting/issue-11897/module3.js
- test/configCases/scope-hoisting/issue-11897/module4.js
- test/configCases/scope-hoisting/issue-11897/module5.js
Revert the source change in https://github.com/webpack/webpack/pull/18709, the test cases are reserved. Resolve https://github.com/web-infra-dev/rspack/issues/7591.
After adding new tests cases in this PR, I found it's hard to determine when to add the leading semicolon, as comments may appear before real code. Considering the risks and benefits of implementation, I decide to revert #18709 until we found a cheap and safe implementation. I also added new test cases by the way.
There's still a little change I made to resolve https://github.com/web-infra-dev/rspack/issues/7591: remove `CONCATENATED MODULE: ` prefix to make it easier for users to understand.
Yes.
**Does this PR introduce a breaking …
> fix: always add semicolon in concaten module and tweak

- lib/buildChunkGraph.js
- test/configCases/chunk-graph/rewalk-chunk/index.js
- test/configCases/chunk-graph/rewalk-chunk/module-a.js
- test/configCases/chunk-graph/rewalk-chunk/module-b.js
- test/configCases/chunk-graph/rewalk-chunk/module-c.js
- test/configCases/chunk-graph/rewalk-chunk/shared.js
- test/configCases/chunk-graph/rewalk-chunk/test.config.js
- test/configCases/chunk-graph/rewalk-chunk/webpack.config.js
Sorry in #18730 I introduced a bug
Whether to iterate block depends on 2 input, block and minAvailableModules. But in the old pr, I just take minAvailableModules into consideration
If entry block and minAvailableModules are the same, the result should the same. (Runtime changes will cause chunkGroupInfo to be pushed into outdatedQueue, and reconsider skipped connections)
> fix: decide processBlock by input block

- lib/TemplatedPathPlugin.js
- test/configCases/asset-modules/data-url-extract/index.js
- test/configCases/asset-modules/data-url-extract/webpack.config.js
- test/configCases/asset-modules/resource-from-data-uri/index.js
bugfix, prevent name conflicts for extracted DataURI's
Yes
No
No
> fix: use content hash as `[base]` and `[name]` for extracted DataURI's

- lib/ExternalModule.js
- test/configCases/externals/module-import/a.js
- test/configCases/externals/module-import/index.js
- types.d.ts
**To reproduce:** Given there's an external module `'module-a'` both being imported by static-import and dynamic import, and the external type is set to `'module-import'`.
**Expected:** The static import becomes ⁠`'module'`, while the other one is ⁠`'import'`.
**Actual:** Both external imports are either `'import'` or `'module'`.
**Why:** module identifier does not count in `dependencyMeta` which is used to distinguish `'module'` and `'import'` in `'module-import'`.
**Overview changes:**
- Split `'module-import` in `_getRequestAndExternalType` by adding `_resolveExternalType`. This change will help resolve both `'module-import' -> 'module'` & `'module'` and `'module-import' -> 'import'` & `'import'` to the same module, as `'module-import'` …
> fix(externals): distinguish “module” and “import” in “module-import”

- lib/HotModuleReplacementPlugin.js
- test/hotCases/runtime/add-runtime/index.js
- test/hotCases/runtime/add-runtime/lib/a.js
- test/hotCases/runtime/add-runtime/lib/b.js
- test/hotCases/runtime/add-runtime/lib/package.json
- test/hotCases/runtime/add-runtime/module.js
- test/hotCases/runtime/add-runtime/test.filter.js
- test/hotCases/runtime/add-runtime/webpack.config.js
- test/hotCases/runtime/add-runtime/worker.js
Initial compile we have only entry runtime, and we split a module 'lib' into separate chunk, then we modify some of entry module, make it imports a worker, the worker contains the module 'lib' as well.
We have 2 runtime: entry and worker
if one module exist both in entry and worker, and we split it into separate chunk, the chunk has runtime entry and worker, but the HotUpdate chunk only have runtime in the previous compilation, which is entry only, so it cannot render module 'lib', because 'lib' is generated using runtime entry + worker
For the detailed repro, you could check my test case
Yes.
> fix: hotUpdate chunk modified with new runtime should have correct runtime

- lib/container/RemoteRuntimeModule.js
- lib/sharing/ConsumeSharedRuntimeModule.js
- test/configCases/container/track-initial-chunks/App.js
- test/configCases/container/track-initial-chunks/ComponentA.js
- test/configCases/container/track-initial-chunks/index-2.js
- test/configCases/container/track-initial-chunks/index.js
- test/configCases/container/track-initial-chunks/node_modules/react.js
- test/configCases/container/track-initial-chunks/test.config.js
- test/configCases/container/track-initial-chunks/upgrade-react.js
- test/configCases/container/track-initial-chunks/webpack.config.js
ref: https://github.com/webpack/webpack/issues/18812
ref: https://github.com/webpack/webpack/issues/16173
Module Federation should track ALL referenced chunks, not just async chunks. 
This also resolves split chunks issues where initial chunks on an entry are code split
This also allows federation to track and call load handlers on any chunk associated with the runtime. 
Tracking async chunks only causes several problems. 
- initial split chunks wont work
- dependOn of entrypoint wont work
- multiple entrypoints have issues
- things like workers etc will not work as they depend on shared code but federation has no import map for the chunk to module ids in `require.f.consumes/remotes`
bugfix
not needed …
> fix: Module Federation should track all referenced chunks

- test/configCases/externals/import-assertion/webpack.config.js
- test/configCases/externals/import-attributes/webpack.config.js
Previously, the bundled result of `test/js/ConfigTestCases/externals/import-attributes/bundle0.mjs` was incorrect as below. It should be `./pkg.json` because ESM requires a fully specified path.
```js
/***/ ((module) => {
module.exports = import("./pkg", { with: {"type":"json"} });;
/***/ }),
```
I'm not sure the reason it's not panicked in webpack test, as webpack test is simulating many stuff like the runtime. But it did panic in Rspack ported webpack test (they're not fully aligned). However, according to the output code, it should be fixed this way.
Yes.
No.
No.
> test: fix import attributes external target

- lib/util/Queue.js
This PR addresses an issue in the Queue class where the dequeuing functionality was not handling the state of the queue correctly after an item was dequeued. The iterator for the Set inside the queue was not updated properly, which caused the dequeue method to always return undefined after the first iteration, even if new items were enqueued.
This change ensures that the iterator is reset each time an element is dequeued, allowing new elements to be dequeued properly after others are removed.
Bugfix: Corrects the behavior of the dequeue method to ensure that the iterator is correctly updated and the queue behaves as expected after dequeuing an element.
Not yet: Tests will be added if this change is …
> Fix queue iterator state in dequeue method to ensure correct behavior after item removal

- lib/DefinePlugin.js
- lib/javascript/JavascriptParser.js
- test/configCases/plugins/define-plugin-sub-key/foo.js
- test/configCases/plugins/define-plugin-sub-key/index.js
- test/configCases/plugins/define-plugin-sub-key/webpack.config.js
- types.d.ts
Fixes https://github.com/webpack/webpack/issues/18573
```javascript
import foo from './foo.js';
function works() {
return foo.bar;
}
function broken() {
const bar = foo.bar;
return bar;
}
works(); // does not throw
broken(); // throws ReferenceError
```
error output
```javascript
/* harmony import */ var _foo_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(686);
function works() {
return _foo_js__WEBPACK_IMPORTED_MODULE_0__/* ["default"] */ .A.bar;
}
function broken() {
const bar = foo.bar;
return bar;
}
works(); // does not throw
broken(); // throws ReferenceError
```
expected output
```javascript
/* harmony import */ var _foo_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(686);
function works() {
return …
```
> fix: sub define key should't be renamed when it's a defined variable

- declarations/plugins/JsonModulesPluginParser.d.ts
- lib/WebpackOptionsApply.js
- lib/config/defaults.js
- lib/dependencies/JsonExportsDependency.js
- lib/json/JsonModulesPlugin.js
- lib/json/JsonParser.js
- schemas/plugins/JsonModulesPluginParser.check.js
- schemas/plugins/JsonModulesPluginParser.json
- test/Defaults.unittest.js
- test/configCases/json/bailout-flag-dep-export-perf/data.json
- test/configCases/json/bailout-flag-dep-export-perf/index.js
- test/configCases/json/bailout-flag-dep-export-perf/webpack.config.js
- test/configCases/json/flag-dep-export-perf/data.json
- test/configCases/json/flag-dep-export-perf/index.js
- test/configCases/json/flag-dep-export-perf/webpack.config.js
perf only for `development` mode
Fixes https://github.com/webpack/webpack/issues/18458
Yes
No
Add two options to https://webpack.js.org/configuration/module/#moduleparser
for `json`
- `parse` - Function that executes for a module source string and should return json-compatible data.  Type `((input: string) => any)`, for For example we can use toml parser 
```js
const toml = require("toml");
module.exports = [
{ 
module: {
rules: [
{
test: /\.toml$/,
type: "json",
parser: {
parse(input) { 
return toml.parse(input);
}
}
}
]
}
}
];
```
- `exportsDepth` - The depth of json dependency flagged as …
> perf: improve FlagDependencyExportsPlugin for large JSON by depth

- lib/optimize/SplitChunksPlugin.js
- test/__snapshots__/StatsTestCases.basictest.js.snap
- test/statsCases/split-chunks-cache-group-filename/index.js
- test/statsCases/split-chunks-cache-group-filename/node_modules/a.js
- test/statsCases/split-chunks-cache-group-filename/node_modules/b.js
- test/statsCases/split-chunks-cache-group-filename/node_modules/c.js
- test/statsCases/split-chunks-cache-group-filename/webpack.config.js
This PR fixes a bug that we encountered with the `SplitChunksPlugin`: If you provide a `splitChunks.cacheGroups.{cacheGroup}.filename` option it will only be respected for first chunk in the group and not for any other chunks that might be created like those split based on `maxSize`. The fix is to copy over `filenameTemplate` for any new chunks that are created based on `deterministicGroupingForModules` results. 
One alternative I considered is to move the `filenameTemplate` copying to the `Chunk.split()` method: https://github.com/webpack/webpack/blob/3919c844eca394d73ca930e4fc5506fb86e2b094/lib/Chunk.js#L540
I added the `split-chunks-cache-group-filename` stats test case in …
> fix: preserve filenameTemplate in new split chunk

- lib/asset/AssetModulesPlugin.js
- lib/css/CssModulesPlugin.js
- lib/javascript/JavascriptModulesPlugin.js
- lib/wasm-async/AsyncWebAssemblyModulesPlugin.js
- lib/wasm-sync/WebAssemblyModulesPlugin.js
- test/configCases/optimization/issue-19184/files/file1.js
- test/configCases/optimization/issue-19184/files/file2.js
- test/configCases/optimization/issue-19184/files/file3.js
- test/configCases/optimization/issue-19184/files/file4.js
- test/configCases/optimization/issue-19184/files/file5.js
- test/configCases/optimization/issue-19184/index.js
- test/configCases/optimization/issue-19184/warnings.js
- test/configCases/optimization/issue-19184/webpack.config.js
Fixes #19141 
Specifically, addresses determinism of sort order across platforms by leveraging the fact that a developer who desires stable output cross-platform will have already ensured that module ids are stable, so it necessarily follows that sorting by module id will result in a deterministic sort order.
bugfix
Added a unit test that verifies that Javascript modules are rendered in sorted order.
The sort order of modules in rendered output will change, but a one-time alteration to that order is no different than changing a salt value.
> (fix) Use module ids for final render order

- lib/dependencies/CommonJsImportsParserPlugin.js
- test/configCases/parsing/require-resolve-ignore/index.js
- test/configCases/parsing/require-resolve-ignore/other.js
- test/configCases/parsing/require-resolve-ignore/webpack.config.js
feature, allow to ignore `reqiore.resolve` using `/* webpackIgnore: true */` comment
fixes https://github.com/webpack/webpack/issues/19132
Yes
No
Yes, need to show an example
```js
const x = require.resolve(/* webpackIgnore: true */ 'x');
```
https://webpack.js.org/configuration/module/#moduleparserjavascriptcommonjsmagiccomments
> feat: implement `/* webpackIgnore: true */` for `require.resolve`

- lib/ModuleFilenameHelpers.js
Tested in local Node environment, this change is 7–8× faster than before.
Why not use indexOf:
1. startsWith offers better semantics and cleaner code.
2. [Existing code](https://github.com/webpack/webpack/blob/fab79c1b5dc0b596929187c1bcfd90c08d9e4fbc/lib/NormalModule.js#L1058C1-L1069C3) and many other bundler libraries already use startsWith.
3. Converting a string into a regex is more time-consuming, while the performance difference in matching is minimal.
Given that Node continues to optimize startsWith, I believe this approach is sufficient for now.
Existing
No
No
> perf: use startsWith for matching instead of converting the string to a regex

- lib/wasm/EnableWasmLoadingPlugin.js
node async wasm loader was incorrectly using output.environment.module
to determine if import.meta statement should be used. Which may not match
the output flavor defined by output.module.
bugfix
no
no
no
Fixes #19209
> fix: node async wasm loader generation

- lib/library/AssignLibraryPlugin.js
- test/configCases/library/0-create-library/index.js
- test/configCases/library/0-create-library/non-external-named.js
- test/configCases/library/0-create-library/webpack.config.js
- test/configCases/library/1-use-library/index.js
- test/configCases/library/1-use-library/node_modules/external-named.js
- test/configCases/library/1-use-library/webpack.config.js
- test/configCases/library/cjs-static/index.js
Previously, any unprovided export will be skipped directly, which will lost export in the following common library usage:
```js
// reexport from an external module in the index file of a package
export * from 'external-module'
```
In this PR, I added a loop to assign exports in the ⁠way of `commonjs`  to ensure nothing is lost.
Yes.
I don't think so.
No.
> fix(commonjs-static): export unprovided variables

- test/JavascriptParser.unittest.js
This PR fixes the `HookMap#tap` deprecation warning by replacing it with `HookMap#for(...).tap(...)`. 
Updated the internal hook usage to use `for(...)` instead of `tap(key, ...)` cause previously it was showing deprecation warning while running tests. I have explained everything in the below mentioned issue.
RESOLVES #19304 
bugfix
Updated /webpack/test/JavascriptParser.unittest.js
No
NA
> fix: deprecation warning

- lib/javascript/JavascriptModulesPlugin.js
This PR fixes excessive calls of getAllReferences, which is an issue observed in #18917. In the discussion was not yet clear what causes the issue. But my project suffered since version 5.96.0, too. I was able to git-bisect and profile the issue. The issue appeared first in #18845 / 18d6cb5afe4528f4fa168aa9aab733b934f2351e. The profiles are too large, I'll just show screenshots.
Before this change my project did a release build in about 36s:
After that, the performance regressed to about 130s. You can see, getAllReferences is called now excessively:
To fix this, the PR does two things.
First, improve `allUsedNames.add(variable.name)` handling, otherwise all variables would be renamed, which causes many getAllReferences calls.
Second, move …
> fix: excessive calls of getAllReferences

- lib/library/ModernModuleLibraryPlugin.js
- test/configCases/library/modern-module-reexport-external/index.js
- test/configCases/library/modern-module-reexport-external/test.config.js
- test/configCases/library/modern-module-reexport-external/test.js
- test/configCases/library/modern-module-reexport-external/webpack.config.js
For library type 'modern-module', should not ignore exports with `unknown` exports info.
The exportsInfo of `ExternalModule` is `unknown` exports info, we should keep the export for it
Yes
> fix: should create export for external

- README.md
- Update README.md
- Yes
- No
Hallo @sokra, hello @alexander-akait,
I have added the new modern [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin) to the Plugin's list in the README.
This plugin allows using a template file as an [entry point](https://github.com/webdiscus/html-bundler-webpack-plugin#option-entry).
The HTML Bundler generates static HTML or template function from [any template](https://github.com/webdiscus/html-bundler-webpack-plugin#template-engine) (EJS, Handlebars, Nunjucks, Pug, etc.) containing source files of scripts, styles, images, fonts …
> docs: add new html-bundler-webpack-plugin to plugins list in README

- lib/Dependency.js
fixes https://github.com/webpack/webpack/discussions/19523
Shorty - some (including in our codebase) compactors are using `if ("start" in loc) {}` (for example for order of dependencies) and in 5.98.0 version it was `false`, after https://github.com/webpack/webpack/commit/87b203b27eb8d32101e75f1e589d2d162781120b it is always `true` and so we start compare with `0`, before we don't compare such deps, so because we start compare with `0` order become wrong
Hard to create good valid test, tried, but they are syntactical and don't provide a real fix 
Return old behaviour 
No need
> fix: regression with location

- lib/library/ModuleLibraryPlugin.js
- test/configCases/library/0-create-library/foo.js
- test/configCases/library/0-create-library/webpack.config.js
- test/configCases/library/1-use-library/webpack.config.js
fixes https://github.com/webpack/webpack/issues/19511
Currently we don't support all inlined modules for multiple module entry, we have TODO - https://github.com/webpack/webpack/blob/main/lib/javascript/JavascriptModulesPlugin.js#L1525
Yes
No
No
> fix: es export generation for multiple module entries

- lib/esm/ModuleChunkLoadingRuntimeModule.js
- test/ConfigTestCases.template.js
- test/configCases/output-module/public-path/test.config.js
- test/configCases/output-module/public-path/webpack.config.js
This fixes an issue for esm modules where they incorrectly used publicPath to locate the module. See https://github.com/webpack/webpack/issues/19495#issuecomment-2890514344 and https://github.com/webpack/webpack/issues/19432#issuecomment-2890205522. It was introduced in https://github.com/webpack/webpack/pull/19434
fixes https://github.com/webpack/webpack/issues/19547
> Fixed publicPath issue

- test/configCases/module/circular-externals/external-a.mjs
- test/configCases/module/circular-externals/external-b.mjs
- test/configCases/module/circular-externals/index.js
- test/configCases/module/circular-externals/module-a.js
- test/configCases/module/circular-externals/module-b.js
- test/configCases/module/circular-externals/test.config.js
- test/configCases/module/circular-externals/webpack.config.js
Tests verify that webpack correctly handles:
- Circular dependencies between ESM external modules (`external-a.mjs` ⇄ `external-b.mjs`)
- Live bindings preservation in circular scenarios
- Re-exports within circular dependencies
- Multiple imports of the same circular external module
Rel: #17121
yes
no
no need
> test: add test case for circular dependency with externals

- lib/DefinePlugin.js
- test/configCases/plugins/define-plugin/index.js
- test/configCases/plugins/define-plugin/webpack.config.js
Fixes https://github.com/webpack/webpack/issues/5392 https://github.com/webpack/webpack/issues/14800#issuecomment-2695148561.
There are some cases that can't be supported:
1. Some destructured properties might not be defined in DefinePlugin, but could exist at runtime.
```js
const { NODE_ENV, UNKNOWN } = process.env
```
2. Some destructured properties may be defined across multiple DefinePlugin.
```js
const { NODE_ENV, FOO, BAR } = process.env
```
```js
module.exports={
// ...
plugins: [
// ...
new DefinePlugin({
NODE_ENV: "development"
}),
new DefinePlugin({
FOO: "foo",
BAR: "bar"
})]
}
```
Yes
No
**What needs to be documented once your changes are …
> feat: improve support for destructing in `DefinePlugin`

- lib/javascript/JavascriptParser.js
- package.json
- yarn.lock
The parsing logic for `import defer` was copy-pasted from the https://www.npmjs.com/acorn-import-defer. I now:
- updated that package to also support parsing the `import source` proposal (https://github.com/tc39/proposal-source-phase-imports)
- renamed it to `acorn-import-phases`
- it's tested on Node.js 10.x+
- added proper type definitions, so that it can be easily used in the Webpack codebase.
My goal with that package was to share an implementation for `import defer` parsing across tools, so that parsing bugs don't need to be fixed across multiple repos. Let's use it? :)
Note that this PR explicitly disables `import source` parsing in that plugin, since webpack doesn't support it yet. It will make however implementing `import source` …
> Use `acorn-import-phases` plugin

- lib/ModuleGraph.js
- lib/NormalModule.js
- lib/optimize/SideEffectsFlagPlugin.js
- test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
- test/__snapshots__/ConfigTestCases.basictest.js.snap
- test/__snapshots__/StatsTestCases.basictest.js.snap
- test/configCases/css/css-order/index.js
- test/configCases/css/css-order/liba/common.js
- test/configCases/css/css-order/liba/index.js
- test/configCases/css/css-order/liba/teaser.module.css
- test/configCases/css/css-order/libb/button.module.css
- test/configCases/css/css-order/libb/common.js
- test/configCases/css/css-order/libb/index.js
- test/configCases/css/css-order/package.json
- test/configCases/css/css-order/webpack.config.js
- test/configCases/css/css-order2/component.js
- test/configCases/css/css-order2/dependency/dependency.css
- test/configCases/css/css-order2/dependency/dependency.js
- test/configCases/css/css-order2/dependency/dependency2.css
- test/configCases/css/css-order2/dependency/dependency2.js
- test/configCases/css/css-order2/dependency/index.js
- test/configCases/css/css-order2/dependency/package.json
- test/configCases/css/css-order2/index.js
- test/configCases/css/css-order2/package.json
- test/configCases/css/css-order2/webpack.config.js
- types.d.ts
Fixes https://github.com/webpack/webpack/issues/18961
Thanks to @jantimon for the detailed analysis of this issue. Instead of adopting the approach in #19012, I chose to fix the dependency order directly at the point where module updates are triggered, without relying on the internal implementation details of the graph.
Yes, The test cases come from
1. [reproduction-webpack-css-order](https://github.com/jantimon/reproduction-webpack-css-order/blob/main/%40applications/base/webpack.config.js) - For this case, the issue can be resolved just by adding compareSelect in  [lib/NormalModule.js](https://github.com/webpack/webpack/pull/19686/files#diff-a5db25852bfa94348bb69d94ab95dbef8474d789240b4345cf518e5dd645 …
> fix: keep the module graph traversal order consistent

- lib/ModuleGraph.js
- lib/NormalModule.js
- lib/util/comparators.js
- test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
- test/__snapshots__/ConfigTestCases.basictest.js.snap
- test/compareSourceOrder.unittest.js
- test/configCases/css/css-order3/component.js
- test/configCases/css/css-order3/dependency/dependency.css
- test/configCases/css/css-order3/dependency/dependency.js
- test/configCases/css/css-order3/dependency/dependency2.css
- test/configCases/css/css-order3/dependency/dependency2.js
- test/configCases/css/css-order3/dependency/dependency3.css
- test/configCases/css/css-order3/dependency/dependency3.js
- test/configCases/css/css-order3/dependency/index.js
- test/configCases/css/css-order3/dependency/package.json
- test/configCases/css/css-order3/index.js
- test/configCases/css/css-order3/package.json
- test/configCases/css/css-order3/webpack.config.js
- types.d.ts
Fixes https://github.com/webpack/webpack/pull/19686
```diff
it("dependency without the sourceOrder attribute must keep their original index in the array", () => {
const deps = [
// HarmonyImportSpecifierDependency
{ name: "b", sourceOrder: 10 },
// CommonJSRequireDependency
{ name: "a" },
// CommonJSRequireDependency
{ name: "d" },
// HarmonyImportSpecifierDependency
{ name: "c", sourceOrder: 5 }
];
sortWithSourceOrder(deps, dependencySourceOrderMap);
+   expect(deps.map(d => d.name)).toEqual(["c", "a", "d", "b"]); // ✅
-   expect(deps.map(d => d.name)).toEqual(["c", "b", "a", "d"]); // ❌
});
```
Yes
No
**What needs to be documented once your changes are …
> fix: Dependency without the sourceOrder attribute must keep their original index

- lib/optimize/SideEffectsFlagPlugin.js
- lib/util/comparators.js
- test/__snapshots__/ConfigCacheTestCases.longtest.js.snap
- test/__snapshots__/ConfigTestCases.basictest.js.snap
- test/configCases/css/css-order-reexport/component.js
- test/configCases/css/css-order-reexport/dependency/dependency.css
- test/configCases/css/css-order-reexport/dependency/dependency.js
- test/configCases/css/css-order-reexport/dependency/dependency2.css
- test/configCases/css/css-order-reexport/dependency/dependency2.js
- test/configCases/css/css-order-reexport/dependency/index.js
- test/configCases/css/css-order-reexport/dependency/package.json
- test/configCases/css/css-order-reexport/index.js
- test/configCases/css/css-order-reexport/package.json
- test/configCases/css/css-order-reexport/webpack.config.js
Fixes https://github.com/webpack/webpack/pull/19686
keep the import order of dependency and dependency2 in the reexport within component.js
```js
// ./component.js
export { dependency, dependency2 } from "./dependency";
export function component(...args) {
console.log(args);
}
// ./dependency/index.js
export * from "./dependency2";
export * from "./dependency";
```
```diff
// output
/***/ "./component.js":
/*!**********************!*\
!*** ./component.js ***!
\**********************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   component: () => (/* binding */ component),
/* …
```
> fix: keep module traversal consistent across reexport scenarios

- test/configCases/assets/compression-webpack-plugin-issues-390/webpack.config.js
Fixes https://github.com/webpack-contrib/compression-webpack-plugin/issues/390
The original commit that fixed the issue is https://github.com/webpack/webpack/commit/d2d34e6267e2e6558ffacc02af48202bee0473dc. This PR is only for fixing lint issues and verifying test case execution.
No
No
No
> fix: filter deleted assets in processAdditionalAssets hook

- lib/Dependency.js
- lib/ModuleGraph.js
- lib/dependencies/ModuleDependency.js
Fix circle deps:
`Dependency.js`/`ModuleDependency.js` -> `RawModule.js` -> `ModuleGraph.js` -> `CommonJsSelfReferenceDependency.js`/`HarmonyImportDependency.js` -> `Dependency.js`/`ModuleDependency.js`
Fixes the condition of `moduleGraph.isDeferred`:
Should return `true` only when incoming modules include `HarmonyImportDependency` (not `CommonJsSelfReferenceDependency`) and its `defer` is set to true.
Existing
No
No
> fix: circle deps when require `RawModule` and condition of `isDeferred`

- lib/Watching.js
- test/Watch.test.js
Fixes https://github.com/webpack/webpack/issues/15541. The issue is about two `invalidations` in quick succession.
We should emit assets even if invalidation occurs again. 
In the case of above issue, `hot update manifest` is only generated during the first compilation triggered by the initial invalidation.
If we skip emitting assets (in particular `hot update manifest` ) in the first compilation, it will cause HMR failed, resulting in a full reload.
**_Assets of first compilation_**
```
0 = {name: 'bundle.js', source: CachedSource, info: {…}}
1 = {name: 'simple-entry_js.bundle.js', source: CachedSource, info: {…}}
2 = {name: 'a_js_lazy-compilation-proxy.bundle.js', source: CachedSource, info: {…}}
3 = {name: …
```
> fix: should emit assets even if invalidation occurs again

- lib/esm/ExportWebpackRequireRuntimeModule.js
- lib/esm/ModuleChunkFormatPlugin.js
- lib/esm/ModuleChunkLoadingPlugin.js
- test/configCases/module/issue-19767/common.js
- test/configCases/module/issue-19767/index.js
- test/configCases/module/issue-19767/test.config.js
- test/configCases/module/issue-19767/webpack.config.js
Fixes https://github.com/webpack/webpack/issues/19767 The naming of functions exported within webpack cannot use "default" because the entryModule may have a default export.
Yes
No
No
> fix(esm): fix the failure export of internal function

- test/BenchmarkTestCases.benchmark.mjs
Hiya! @ovflowd mentioned to me that y'all are looking to speed up parts of Webpack. That's great, and I'm happy to help. Anyhow, I wanted to help, so I figured I'd start by looking at the benchmarks, and immediately noticed a few things I could improve: Benchmarks don't profile
Refactoring
The tests are the benchmarks
I certainly hope not.
The documentation has already been updated
> feat(benchmark): support profiling

- .github/workflows/test.yml
PR Description:
This PR pins Node.js 24.6 (=24.x) to version 24.5.0 in the CI workflow as a temporary workaround for a Node.js regression that causes CI failures.
Related to Node.js issue: https://github.com/nodejs/node/issues/59480
CI/build configuration fix
N/A
No
None
> ci: pin Node.js 24.x to 24.5.0 to fix CI failures

- lib/async-modules/AwaitDependenciesInitFragment.js
- test/configCases/async-module/issue-19803/a.js
- test/configCases/async-module/issue-19803/b.js
- test/configCases/async-module/issue-19803/c.js
- test/configCases/async-module/issue-19803/d.js
- test/configCases/async-module/issue-19803/index.js
- test/configCases/async-module/issue-19803/webpack.config.js
Fixes https://github.com/webpack/webpack/issues/19803
```bash
● ConfigTestCases › async-module › issue-19803 › issue-19803 should compile
ReferenceError: Cannot access 'c' before initialization
at Object.c (undefined-issue-19803-0-/Users/x/webpack/test/js/ConfigTestCases/async-module/issue-19803/bundle0.mjs:86:48)
at undefined-issue-19803-0-/Users/x/webpack/test/js/ConfigTestCases/async-module/issue-19803/bundle0.mjs:38:43
```
No
No
No
> fix: resolve execution order issue from extra await in async modules

- lib/ConstPlugin.js
Fixes https://github.com/webpack/webpack/issues/19806.
We now only generate empty block when unreachable/unused statement is `BlockStatement`,  preventing the `unreachable code` warning in `Firefox`.
Existing
No
No
> fix: avoid empty block for unused statement

- lib/esm/ModuleChunkLoadingRuntimeModule.js
This fixes an issue with hot module replacement when using `experiments.outputModule: true`.
To reproduce the issue:
1. Create `src/index.js` containing:
```javascript
import 'webpack/hot/signal.js'
let count = 0;
const interval = setInterval(() => {
console.log('label 1', { count: count++ })
}, 1000);
if (import.meta.webpackHot) {
import.meta.webpackHot.accept()
import.meta.webpackHot.dispose(() => {
clearInterval(interval);
});
}
```
2. Create `webpack.config.js`:
```javascript
import { ChildProcess, fork } from 'node:child_process';
import webpack from 'webpack';
export default /** @satisfies {import('webpack').Configuration} */ ({
devtool: 'source-map',
target: ['node'],
experiments: {
outputModule: true
},
plugins: [
new webpack.HotModuleReplacementPlugin(),
/** @this …
```
> fix: ignore import failure during HMR update with esm output

- lib/config/defaults.js
- test/Defaults.unittest.js
- test/configCases/asset-modules/type-text/index.js
- test/configCases/asset-modules/type-text/webpack.config.js
feat - https://github.com/whatwg/html/issues/9444 and https://github.com/tc39/proposal-import-bytes?tab=readme-ov-file#is-there-any-prior-art
Yes
No
Yes we need to add an example on the asset modules page
> feat: added support for `import file from "./file.ext" with { type: "text" }` to get text content

- lib/dependencies/ImportMetaPlugin.js
- test/cases/parsing/asi/warnings.js
- test/cases/parsing/import-meta/warnings.js
**Summary**
This improves the `import.meta` direct access warning. I find the current warning is sorta unclear as to what "Accessing import.meta directly" means in this context. I've updated it to clarify that `import.meta` cannot be used as a standalone expression because of static analysis requirements and provides clear examples of correct usage.
Just logs/docs.
Updated. None added
No
Not relevant.
> fix(warnings): update import.meta warning messages for clarity
